### ISSUE TITLE
Where is wechat accessToken?

### ISSUE THREAD

**Issue by monyuan** [casdoor/casdoor#1008]
AccessToken must be exposed!

Because after a new token is generated, the old token will become invalid！
The accesstoken of the official account may be used in multiple projects！

微信公众号的accessToken存在哪里，是否暴露了出来？

微信的accesstoken的机制是，新的产生老的失效，一个公众号的accesstoken可能很多项目都在用。
被casdoor占用，微信公众号将无法做任何的开发

**Comment by hsluoyz** [comment]
@Resulte

**Comment by Resulte** [comment]
@monyuan  plz see this [doc](https://casdoor.org/docs/how-to-connect/oauth) for how to get AccessToken.

**Comment by hsluoyz** [comment]
Closed as resolved
