### ISSUE TITLE
#977  Can't open login page

### ISSUE THREAD

**Issue by cccy0** [casdoor/casdoor#1010]
#977 

I repeated this problem   
started it with docker   
request url : `https://xxx.xxx.xxx/login/oauth/authorize?client_id=f208312d4aee1941d102&response_type=code&redirect_uri=http://localhost:9000/callback1&scope=read&state=casdoor`   
the request url of CSS and JS files is not correct   
![1660305982245](https://user-images.githubusercontent.com/29329157/184350632-d07e39e0-657a-4a21-8857-85b03d13f9d1.png)

**Comment by hsluoyz** [comment]
@cccy0 plz try latest version, if not fixed, plz report your Casdoor version

**Comment by cccy0** [comment]
docker image v1.86.0 has beed fixed ,  tks~
