### ISSUE TITLE
can not login with admin/123 on docker casbin/casdoor:latest

### ISSUE THREAD

**Issue by fernandolguevara** [casdoor/casdoor#1031]
I'm trying to access to the admin dashboard using `admin/123` but casdooor throw this error

```json
{
  "status": "error",
  "msg": "Unauthorized operation",
  "sub": "",
  "name": "",
  "data": null,
  "data2": null
}
```

the enforcer says `built-in/admin` isn't allowed

![image](https://user-images.githubusercontent.com/969516/185514862-3e638e31-912d-4437-a12f-f8bc51354dcc.png)

**Comment by cofecatt** [comment]
Check the database table 'permission_rule' to see whether there is any data

**Comment by cofecatt** [comment]
> 

Check the db table named `casdoor`.`permission_rule` whether there is any data, it may be a bug start with docker.

**Comment by fernandolguevara** [comment]
@hsluoyz can we have at least some test on the login methods to avoid this kind of issues on the future?

**Comment by hsluoyz** [comment]
@fernandolguevara good idea, created here: https://github.com/casdoor/casdoor/issues/1036

**Comment by Bruc3Stark** [comment]
@fernandolguevara i wonder how did this bug finally be solved 😕 i met the same question when i upgrade casdoor from v1.105.0 to v1.270.0, and now i cannot even reset the admin password 😡
