### ISSUE TITLE
problem with postgres database config

### ISSUE THREAD

**Issue by seahurt** [casdoor/casdoor#1052]
When config with postgres:
```
driverName = postgres
dataSourceName = "user=postgres password=postgres host=localhost port=5432 sslmode=disable dbname=casdoor"
```
I got err: `panic: pq: database "casdoorcasdoor" does not exist`

---

After change code in authz/authz.go: line:31 to the following, problem solved

```
a, err := xormadapter.NewAdapterWithTableName(conf.GetConfigString("driverName"), conf.GetBeegoConfDataSourceName(), "casbin_rule", tableNamePrefix, true)
```

But this change may break other database, like mysql.

So I suggest uniform the DSN for every supported database in casdoor, and change it to target DSN when passing to driver

---
我的建议是在casdoor的代码中将所有数据库的DSN统一，但是在传入外部的库的时候，根据类型生成对应的DSN
比如，我们可以将pg数据库的DSN定义为下面的格式:

```
postgres://username:password@host:port/dbname?sslmode=require
```
然后，通过url.Parse解析各个部分，构建出数据库驱动需要的DSN:
```
user=postgres password=postgreshost=localhost port=5432 sslmode=disable dbname=casdoor
```

**Comment by seahurt** [comment]
好吧，原来文档里面有写怎么配置pg数据库。:clown_face:

**Comment by hsluoyz** [comment]
@seahurt yes, plz see: https://casdoor.org/docs/basic/server-installation#postgresql

![image](https://user-images.githubusercontent.com/3787410/185853095-087f9edd-f6f1-4fb0-82e7-95e12ca2a25d.png)
