### ISSUE TITLE
Can Wechat OAuth and Wechat MiniProg account be identified as the same user

### ISSUE THREAD

**Issue by Linvery** [casdoor/casdoor#1056]
Background: in the wechat system, every application (WeChat Media Platform , wechat MiniProg, website application, mobile application) even the same user has a different openid.
Example：
User：xiaoming
First, he opened the  WeChat Media Platform and logs in, then he get a openid (example: abcd-1234-5678).
![2ea9fb5cb97df49da4f600a4225df03](https://user-images.githubusercontent.com/23356865/185863614-655c4209-d03f-4d7d-a82f-8863e9b2e12c.jpg)

Second , he logs in wechat MiniProg ,he get a openid (example: defg-8888-5252)
![2a63c2fae9ca49f80f6747f21856e87](https://user-images.githubusercontent.com/23356865/185866831-5dc37f39-3404-4f1d-b9ea-ff945c5868c7.jpg)

There is a problem. We can't identify different application scenarios under the wechat system.
Therefore, wechat launched the wechat open platform, Bind wechat MiniProg and WeChat Media Platform application to wechat open platform, then miniProg and Media Platform will get unionid in addition to openid when the user logs in.(If it is not bound, only openid will be obtained when logging in)
In the above example, all applications of the same user are the same unionid(WeChat Media Platform: hjkl-1234-5678,Wechat Mini Prog: hjkl-1234-5678)
![image](https://user-images.githubusercontent.com/23356865/185865872-ec41110a-2427-4f9c-8915-008e4ba752bd.png)

My question is that currently, only the users in the PC scenario (scanning QR code for login) and WeChat Media Platform are identified as the same user, but wechat MiniProg are not yet associated. In casdoor, wechat applets are still like islands without unionid.

WeChat Media Platform => A user
PC scenario => A user
Wechat MiniProg => B user

https://casdoor.org/zh/docs/provider/oauth/Wechat
https://casdoor.org/zh/docs/integration/wechat_miniprogram
In the casdoor document, these two scenarios are separated,At the same time, the accounts are separated and cannot be identified as the same user

**Comment by Linvery** [comment]
中文版：现在只做到了，“公众账号”和”网站应用“互联，并没有做到（“公众账号”和”网站应用“）与 “微信小程序”互联

**Comment by hsluoyz** [comment]
@dirname

**Comment by dirname** [comment]
You can fix that by setting/getting the `unionid` in the `properties` field. For details, see #985 .

**Comment by hsluoyz** [comment]
@dirname how to do that (setting/getting the unionid)?

**Comment by hsluoyz** [comment]
@Linvery is this resolved?
