### ISSUE TITLE
Cannot get user info with scope params set

### ISSUE THREAD

**Issue by seahurt** [casdoor/casdoor#1059]
It seems "scope" param is not used.

version:  `casbin/casdoor-all-in-one:v1.101.0        e80e882f5661`

---

<img width="672" alt="image" src="https://user-images.githubusercontent.com/3347603/186091061-551eb1d9-c052-4490-afb8-66c5217c4864.png">

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by hsluoyz** [comment]
@dirname I think `openid` is a valid option in OAuth 2.0. @seahurt

**Comment by hsluoyz** [comment]
@leo220yuyaodog plz add this to: https://casdoor.org/docs/how-to-connect/oauth#how-to-use-accesstoken

**Comment by hsluoyz** [comment]
@leo220yuyaodog plz add this to: https://casdoor.org/docs/how-to-connect/oauth#how-to-use-accesstoken

**Comment by leo220yuyaodog** [comment]
Actually, casdoor defalut assume you added `openid` scope in oidc, is equvalent to no scope. I improve the document about how to add scope. @seahurt
