### ISSUE TITLE
[docker compose] not working

### ISSUE THREAD

**Issue by baguskna** [casdoor/casdoor#1066]
after I cloned the repo, I ran the app using docker-compose --build -d and I encountered this issue

<img width="1240" alt="Screen Shot 2022-08-27 at 12 17 54" src="https://user-images.githubusercontent.com/53422369/187015979-70bf2d63-4e71-48ea-b274-c7455e08e5e4.png">

**Comment by baguskna** [comment]
nothing app running in 3306 port on my docker container

**Comment by hsluoyz** [comment]
Closed as stale.
