### ISSUE TITLE
Add config gate to controller url schema (http / https)

### ISSUE THREAD

**Issue by maslow** [casdoor/casdoor#1085]
![image](https://user-images.githubusercontent.com/7122237/187814595-d2762464-8e65-47f9-b2c5-d09199896872.png)

1. do not hard code the protocol (http shcema) depends on `localhost` prefixed url, just support a config gate.
2. do not hard code `localhost:8000` to `localhost:7001`, use `runmode: dev | prod` or other env / config gate instead.

**Comment by hsluoyz** [comment]
@maslow fixed by: https://github.com/casdoor/casdoor/commit/4536fd06369d1c0ae9cbf49fa2458f9849673b26

Now you can use `origin` in app.conf to specify origin full URL
