### ISSUE TITLE
use WebAuthn credentials got error: Error validating origin

### ISSUE THREAD

**Issue by wangshuai-007** [casdoor/casdoor#1090]
I use the sample container:
`docker run -d -p 8000:8000 casbin/casdoor-all-in-one`

after login with admin 

I add WebAuthn credentials and input windows Pin

After that,I got error:

`Error validating origin`

![image](https://user-images.githubusercontent.com/17959236/188066948-0854bd93-8ff1-4afd-958f-db1bfec3f90b.png)

How can I use the `WebAuthn credentials`?

**Comment by ComradeProgrammer** [comment]
Checklist:
1. are you using https or localhost, if not, please switch to one of them.
2. Is "origin" field properly configured? configure file is app.conf
if problems still exist, please reply

**Comment by wangshuai-007** [comment]
After config `origin` in `app.conf` with [webauthn](https://casdoor.org/zh/docs/webauthn/overview) 
I can add `WebAuthn credentials`
