### ISSUE TITLE
login failed when using casbin/casdoor:v1.107.0 and external datasource

### ISSUE THREAD

**Issue by flyingdew** [casdoor/casdoor#1093]
I uses casbin/casdoor:v1.107.0 image and external datasource.I get problem when login.

The log says:
2022/09/03 09:35:40.803 [D]  |     172.17.0.1| 403 |   2.365713ms| nomatch| POST     /api/login

But when I switch to the old version v1.49.0, it works.

**Comment by hsluoyz** [comment]
@flyingdew plz use a new DB

**Comment by flyingdew** [comment]
Yes,I did create a new db manully.

Finally I figured this out by setting sock5Proxy to "" in app.conf.
But it is good when using image v1.49.0. So I guess it's not the code's problem, maybe the docker image build process has changed?

**Comment by hsluoyz** [comment]
@flyingdew you should always use the latest version of `app.conf`

**Comment by wangshuai-007** [comment]
I have the same error :
```bash
2022/09/08 03:21:48.765 [D]  |   xxx.xx.xx.xx| 403 |    1.27095ms| nomatch| POST     /api/login
```
my container version is `casbin/casdoor:v1.111.0`

mydb info is 
```bash
DBMS: MySQL(版本 8.0.30)
```

when I first login with `admin` and `123`
I can got 403 error .

![image](https://user-images.githubusercontent.com/17959236/189027630-546a5aa3-cbfc-4871-a4d5-eb68f2ed69cb.png)

**Comment by hsluoyz** [comment]
@cofecatt

**Comment by cofecatt** [comment]
> 

I tried it with the casdoor v1.111.0 image and MySQL: 8.0.30 on the docker, and it was ok

**Comment by cofecatt** [comment]
> 

If you want to get a reply quickly, please join our QQ group and ask questions in the group to reply faster

**Comment by wangshuai-007** [comment]
I have test a lot.

Now, I know ,`403` login error is caused by `origin` config in `/conf/app.conf`.

After I remove config value of `origin`,I can login success.

But, for [webauthn](https://casdoor.org/zh/docs/webauthn/overview) feature.

I need add `origin` value.

So,what's the right way to use `webauthn`?

My `casdoor` application is proxy by `Nginx`,Is it caused 403 error(for add `origin` value)?

**Comment by dardourimohamed** [comment]
@wangshuai-007  Just prepend your `origin` value with `https://`
