### ISSUE TITLE
Model URL in UI leads to 404 error

### ISSUE THREAD

**Issue by fischermario** [casdoor/casdoor#1103]
Clicking on any model name (built-in or custom models) leads to a 404 error. Only the Edit button works as expected.

The link points to a wrong url. Instead of `/models/built-in/model-built-in` it points to `/models/model-built-in`.

![ui-bug](https://user-images.githubusercontent.com/10214295/188460619-5e1bafa9-57f4-4a4f-9e75-6be98d17aaa0.png)

**Comment by hsluoyz** [comment]
@fischermario can you make a PR to fix it?

**Comment by hsluoyz** [comment]
@NJUSTgzy

**Comment by fischermario** [comment]
Please check PR and merge.
