### ISSUE TITLE
The GO_PROXY_SETTING variable in build.sh is always empty

### ISSUE THREAD

**Issue by wenxuan70** [casdoor/casdoor#1105]
https://github.com/casdoor/casdoor/blob/7599e2715add09f0625ec9b22cf80cb09f9baec3/build.sh#L9

**Comment by hsluoyz** [comment]
@cofecatt

**Comment by wenxuan70** [comment]
By executing the following `test.sh` script, I found that `GO_PROXY_SETTING` is always empty.

```shell
#!/bin/bash
GO_PROXY_SETTING=$(GOPROXY=https://goproxy.cn,direct)
echo "$GO_PROXY_SETTING"
```

![image](https://user-images.githubusercontent.com/55948263/188472887-5dd210f8-60a5-4d41-9217-11cddb409402.png)

When the user cannot access websites such as google, a proxy needs to be set to successfully download the go dependency, so `GO_PROXY_SETTING` is empty, which will cause the download of the dependency to fail.

**Comment by cofecatt** [comment]
> 

I will handle this
