### ISSUE TITLE
A "redirect" parameter needs to be added to the profile page to allow the user to save the profile and return to the page we want him to go to

### ISSUE THREAD

**Issue by Zerek-Cheng** [casdoor/casdoor#1117]
![截图](https://user-images.githubusercontent.com/16066557/189370520-bbd6aaac-158a-4a64-a0ee-7fd2c8a23d9e.png)

**Comment by hsluoyz** [comment]
@joy0010

**Comment by joy0010** [comment]
@Zerek-Cheng  Hi. Here is a demo. Is that ok?

https://user-images.githubusercontent.com/61197663/189900707-a95da2be-8eec-4d10-a047-700da667347f.mov

**Comment by Zerek-Cheng** [comment]
> I mean, when in https://oauth.xxxxx.cn/account?redirect=http://baidu.com/页面是保存&退出后跳转到 http://baidu.com/

**Comment by leo220yuyaodog** [comment]
@Zerek-Cheng I plz review #1152

**Comment by Zerek-Cheng** [comment]
> @Zerek-Cheng plz review #1152

LGTM , thks

**Comment by Zerek-Cheng** [comment]
> @Zerek-Cheng plz review #1152


I have an idea that this jump page should conform to the "Redirect URLs" judgment logic in the application configuration, otherwise there may be related security issues
