### ISSUE TITLE
The background picture of the new version of the login interface cannot be full screen

### ISSUE THREAD

**Issue by jyxenlink** [casdoor/casdoor#1127]
The background picture of the new version of the login interface cannot be full screen, and the mobile terminal interface is not well adapted. It is recommended that only the login box be displayed in the mobile terminal mode, and the background and the left, middle and right settings of the login box be removed.

![{V` F5KLTIK85YV{%FOB${B](https://user-images.githubusercontent.com/3787410/190840669-657d9f4a-b7e3-4244-9b05-7e65cc0c2564.png)

这个新增的背景图片样式很好，但是有没有具体的背景图片大小参考值，或者对背景图片代码进行一下css优化，这个半截背景吊在上面实在谈不上美观啊

要考虑到高分辨率屏幕背景图片的自适应

还有就是要考虑移动终端的显示效果，面板位置左中右选项针对移动终端显示应该是不生效（背景也可以考虑），不然移动终端下面首页显示效果还不如不增加背景前的效果。

**Comment by hsluoyz** [comment]
@leo220yuyaodog
