### ISSUE TITLE
How to flexibly add a custom password encryption type ？ 

### ISSUE THREAD

**Issue by yangguangwuwu** [casdoor/casdoor#1137]
How to flexibly add a custom password encryption type ？ 
[casdoor](https://github.com/casdoor/casdoor)/[cred](https://github.com/casdoor/casdoor/tree/master/cred)/manager.go
Can only modify this file There is no more convenient way

**Comment by hsluoyz** [comment]
@yangguangwuwu it can be added by modifying code. You can contribute this new type to us by making a PR.

**Comment by yangguangwuwu** [comment]
There are many types of encryption that PR can't solve

Each application will have its own encryption method

A plug-in like mechanism is needed to resolve this

New Only the corresponding configuration and new file need to be added

Otherwise there will be an infinite number of encryption types PR

**Comment by hsluoyz** [comment]
@yangguangwuwu there's no good way for Golang code to support plugin mechanism. Go is a static language. The easiest way I can think of is that you make a PR to our code base to add a new method

**Comment by chenjpu** [comment]
[Yaegi ](https://github.com/traefik/yaegi) can be used to define dynamic plugins.
