### ISSUE TITLE
User cannot manipulate to log out when changed the profile like "organization", "username"

### ISSUE THREAD

**Issue by Thunder-CL** [casdoor/casdoor#1141]
If the organization of the current login user is changed successfully, the system displays a message that the user does not belong to the original organization, and the system automatically directs to the login page. However, when you log in to the system again, the system displays a message that the user should log out the logined account first to login. However, it is directed to the login page automatically, user cannot manipulate to log out.

**Comment by Thunder-CL** [comment]
![change](https://user-images.githubusercontent.com/51190452/190882885-d000847b-5238-40ec-8cfd-55edae35faba.png)

**Comment by Thunder-CL** [comment]
Add note here: I found that when changed I can logout in the top right corner, but when I do not logout and manipulate like update user info to save the changes, the problem I put up will take place.

**Comment by lujiefsi** [comment]
@hsluoyz

I feel uncertain whether these two issuses( [issues-1427](https://github.com/casdoor/casdoor/issues/1427) and [issues-1427](https://github.com/casdoor/casdoor/issues/1141)) are the same.

anyway, Could you please vaild it on https://huntr.dev/bounties/d43eac1c-b2a2-423e-a84d-9b2f7facbada/ 

I think this can be a security issuse: [CWE-613: Insufficient Session Expiration](https://cwe.mitre.org/data/definitions/613.html)

and i will test it on  latest release.

**Comment by lujiefsi** [comment]
Hi, i have pull the latest image and find that we have fix it by disabing adding users. But i still find that the deleted users can still edit or add the application, provider and others. The most immportant is that we can still add token. I think we should fix it.
