### ISSUE TITLE
Tables displayed in pages have some problems.

### ISSUE THREAD

**Issue by Thunder-CL** [casdoor/casdoor#1142]
When using the slider under the pages incluing  "Roles", "Permissions", "Adapters", "Webhooks", and "Payments", the "Name" column of the table is covering the other columns. Unlike the other pages, the "Name" column is the first column which is fixed will not cover the other columns when sliding.

**Comment by Thunder-CL** [comment]
![cover](https://user-images.githubusercontent.com/51190452/190882912-3e7246c4-8638-4c35-9636-040da9703ede.png)

**Comment by hsluoyz** [comment]
@Thunder-CL this is intended, letting people know the name after scrolling. See: https://ant-design.gitee.io/components/table-cn/#components-table-demo-fixed-columns-header

**Comment by Thunder-CL** [comment]
I know that function, but if the "Name" column set as the first (or last) column maybe looks like more comfortable.

**Comment by hsluoyz** [comment]
@Thunder-CL this is purely a UI issue. If you are intensively using this feature, we can discuss further

**Comment by Thunder-CL** [comment]
@hsluoyz OK, thanks for your answering. It is not a big deal. It's just that I can be a little obsessive to see it is not fixed in the first/last column.
