### ISSUE TITLE
Bug: WebAuthn Login

### ISSUE THREAD

**Issue by yaotthaha** [casdoor/casdoor#1143]
When you try to login with WebAuthn, it will jump to the user panel instead of the original login application.

**Comment by hsluoyz** [comment]
@ComradeProgrammer

**Comment by yaotthaha** [comment]
Please reopen this issue, the bug is not fixed.

The redirect link is incorrect after login.

Use Password:
```
https://example.com/redirect_uri?code=1e9dfec8*******c7216&state=qn1pKXYYuprPQigN1PrQsegLf309pXLa
```

Use WebAuthn:
```
https://example.com/redirect_uri?code=Auth/yaott&state=UsXE80uTt8oMGQ7vu731HpxLNp5FtZK7
```
