### ISSUE TITLE
Bug: OpenID invalid Address Format

### ISSUE THREAD

**Issue by Congyuwang** [casdoor/casdoor#1151]
OpenID spec requires a jsonObject with optional fields as the `address` field in idToken: `{xxx}` (see https://openid.net/specs/openid-connect-core-1_0.html#AddressClaim). However, Casdoor handles `address` as an array of strings: `[xxx]` (see https://github.com/casdoor/casdoor/blob/e1331f314d015e5afb53f601d19dee99f6c351a8/object/user.go#L51). My suggestion is to use `{"formatted": "xxx address"}` to replace the old `["xxx address"]` in IDToken.

This causes some standard openIdConnect client library to panic when deserializing IdToken:
`Failed to parse payload JSON: Error(\"invalid length 0, expected struct AddressClaim with 6 elements\"`

https://docs.rs/openidconnect/latest/openidconnect/

**Comment by Congyuwang** [comment]
Any plan on how to fix this? I think a change directly in `User` class would have a rather wide impact. Perhaps just make some modification specifically for OpenID IDToken is more proper.

**Comment by gtn1024** [comment]
@Congyuwang Fixed, can you try the latest [v1.119.1](https://github.com/casdoor/casdoor/releases/tag/v1.119.1)?

**Comment by Congyuwang** [comment]
This does solve my problem.

**Comment by Congyuwang** [comment]
Any comment ob why this commit is reverted, and any further proposal on its solution? @hsluoyz
