### ISSUE TITLE
Grafana Redirect URI error

### ISSUE THREAD

**Issue by serialt** [casdoor/casdoor#1156]
Casdoor Grafana has configured the redirect url, but when logging in, casdoor reports that the url of localhost is not in the redirect list，after add localhost to the redirect url list, it will jump to localhost, change localhost to domain of grafana, it is working , the database record is right

![image](https://user-images.githubusercontent.com/58406690/191925212-a8419d0a-f014-48b6-a9c7-db338416c114.png)

**Comment by serialt** [comment]
casbin/casdoor-all-in-one:v1.118.0
grafana: 9.1.5

**Comment by hsluoyz** [comment]
@wangguan1024

**Comment by serialt** [comment]
grafaba conf
![image](https://user-images.githubusercontent.com/58406690/191928145-4c6a99ec-867b-4dc0-8b82-b67b47c080c7.png)

**Comment by wangguan1024** [comment]
@serialt 
Hi! I failed to recurrence this bug. I set "www.baidu.com" as the first item of Redirect URIs, it is successful to redirect the Baidu website. There is no error saying localhost does not exist in the Redirect URI list.

**Comment by wangguan1024** [comment]
@serialt 
I recurrence this bug by chance, but only once. By reading source code and debug, I suspect that there is a problem with the saving logic of the URI List. Can you recurrence this bug?

**Comment by wangguan1024** [comment]
@serialt 
Hi, I seem to have found the reason. 
In the conf webpage, as long as the redirect URIs is modified, clicking copy button generate a URL with the new redirect URIs as a param, but only when you click save button or save&exit button, the newly modified URIs will be written to the database. So the redirect page will give a error message about the URIs.

**Comment by serialt** [comment]
I choose another  machine and grafana instance,I can  recurrence this bug again.  

casbin in 172.16.16.50
grafana in 172.16.16.8

my casdoor docker-compose.yaml 
```
version: '3.1'
services:
  casdoor:
    restart: always
    image: casbin/casdoor:v1.119.0
    ports:
      - "8000:8000"
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./casdoor/conf:/conf
```
casdoor conf 
```
appname = casdoor
httpport = 8000
runmode = dev
copyrequestbody = true
driverName = mysql
dataSourceName = root:rocky123@tcp(172.16.16.50:3306)/
dbName = casdoor
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider = 
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = "127.0.0.1:10808"
verificationCodeTimeout = 10
initScore = 2000
logPostOnly = true
origin =
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100
```

grafana conf
```
[auth.generic_oauth]
name = Casdoor
icon = signin
enabled = true
allow_sign_up = true
client_id = 96af38316c830f6ccb84
client_secret = 4e3c09a544a35230f52d7ba328f079c132e9c619
scopes = user:email
empty_scopes = false
email_attribute_name = email:primary
email_attribute_path =
login_attribute_path =
name_attribute_path =
role_attribute_path =
role_attribute_strict = false
groups_attribute_path =
id_token_attribute_name =
team_ids_attribute_path =
auth_url = http://172.16.16.50:8000/login/oauth/authorize
token_url = http://172.16.16.50:8000/api/login/oauth/access_token
```

casdoor db 
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/58406690/192102054-5e5524a8-fd7d-4f2e-b181-138b5553a655.png">

casdoor web conf
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/58406690/192102087-6e0d03e0-3fd3-443c-8916-4ba4745446df.png">

casdoor error msg

<img width="747" alt="image" src="https://user-images.githubusercontent.com/58406690/192102100-c3f6ef58-73ce-4e25-8402-59ed51e93939.png">

**Comment by serialt** [comment]
when I add `http://localhost:3000/login/generic_oauth` to Redirect URI list, it wil redirect  to `http://localhost:3000/login/generic_oauth?code=634e8be9f65ff59ccf75&state=rhDr_okzjzYKnOSO-wUrngZCcKELGbvmB8xx0hd8Ves=`

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/58406690/192102454-58ab8787-569d-4582-8914-d6c535168c4f.png">

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/58406690/192102496-9f0e2ab8-a6f3-4ee1-a12b-bf7ecaeff1e2.png">

**Comment by hsluoyz** [comment]
@wangguan1024

**Comment by wangguan1024** [comment]
@serialt 
OK, I will continue to find the reason for the bug.

**Comment by wangguan1024** [comment]
@serialt 
Hi! Is your recurrence environment still preserved? If so, please give me the redirect_url param of the casdoor oauth page's URL.

Just like that

![image](https://user-images.githubusercontent.com/45236136/192143365-0609aac4-49a3-4e94-b000-b5aad7b3418d.png)

**Comment by serialt** [comment]
> @serialt Hi! Is your recurrence environment still preserved? If so, please give me the redirect_url param of the casdoor oauth page's URL.
> 
> Just like that
> 
> ![image](https://user-images.githubusercontent.com/45236136/192143365-0609aac4-49a3-4e94-b000-b5aad7b3418d.png)

http://172.16.16.50:8000/login/oauth/authorize?access_type=online&client_id=96af38316c830f6ccb84&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin%2Fgeneric_oauth&response_type=code&scope=user%3Aemail&state=vgznsEzHEz5jFiCv___KVtgtcS2Hh90DqN48rdh0jfo%3D

**Comment by serialt** [comment]
> @serialt Hi! Is your recurrence environment still preserved? If so, please give me the redirect_url param of the casdoor oauth page's URL.
> 
> Just like that
> 
> ![image](https://user-images.githubusercontent.com/45236136/192143365-0609aac4-49a3-4e94-b000-b5aad7b3418d.png)

`http://172.16.16.50:8000/login/oauth/authorize?access_type=online&client_id=96af38316c830f6ccb84&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin%2Fgeneric_oauth&response_type=code&scope=user%3Aemail&state=HdtrofooAEQPf3quYlbH4XD_zPVR57UfnApOqH8l8DM%3D`

**Comment by serialt** [comment]
I create two app in casdoor by read the casdoor.org，I'm confused that why the gitea redirect_url  is working？

**Comment by wangguan1024** [comment]
> > @serialt Hi! Is your recurrence environment still preserved? If so, please give me the redirect_url param of the casdoor oauth page's URL.
> > Just like that
> > ![image](https://user-images.githubusercontent.com/45236136/192143365-0609aac4-49a3-4e94-b000-b5aad7b3418d.png)
> 
> `http://172.16.16.50:8000/login/oauth/authorize?access_type=online&client_id=96af38316c830f6ccb84&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin%2Fgeneric_oauth&response_type=code&scope=user%3Aemail&state=HdtrofooAEQPf3quYlbH4XD_zPVR57UfnApOqH8l8DM%3D`

@serialt 
Can you show me the network logs when the browser jumps from your grafana page to the oauth page? Maybe you need to change the network speed at the browser console settings to take screenshots conveniently.

**Comment by serialt** [comment]
> > > @serialt Hi! Is your recurrence environment still preserved? If so, please give me the redirect_url param of the casdoor oauth page's URL.
> > > Just like that
> > > ![image](https://user-images.githubusercontent.com/45236136/192143365-0609aac4-49a3-4e94-b000-b5aad7b3418d.png)
> > 
> > 
> > `http://172.16.16.50:8000/login/oauth/authorize?access_type=online&client_id=96af38316c830f6ccb84&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin%2Fgeneric_oauth&response_type=code&scope=user%3Aemail&state=HdtrofooAEQPf3quYlbH4XD_zPVR57UfnApOqH8l8DM%3D`
> 
> @serialt Can you show me the network logs when the browser jumps from your grafana page to the oauth page? Maybe you need to change the network speed at the browser console settings to take screenshots conveniently.

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/58406690/192144806-b00f2e91-287b-4564-bb8c-8fb27cf57de8.png">

**Comment by wangguan1024** [comment]
> > > > @serialt Hi! Is your recurrence environment still preserved? If so, please give me the redirect_url param of the casdoor oauth page's URL.
> > > > Just like that
> > > > ![image](https://user-images.githubusercontent.com/45236136/192143365-0609aac4-49a3-4e94-b000-b5aad7b3418d.png)
> > > 
> > > 
> > > `http://172.16.16.50:8000/login/oauth/authorize?access_type=online&client_id=96af38316c830f6ccb84&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin%2Fgeneric_oauth&response_type=code&scope=user%3Aemail&state=HdtrofooAEQPf3quYlbH4XD_zPVR57UfnApOqH8l8DM%3D`
> > 
> > 
> > @serialt Can you show me the network logs when the browser jumps from your grafana page to the oauth page? Maybe you need to change the network speed at the browser console settings to take screenshots conveniently.
> 
> <img alt="image" width="1274" src="https://user-images.githubusercontent.com/58406690/192144806-b00f2e91-287b-4564-bb8c-8fb27cf57de8.png">

Sorry, I means the network logs of grafana page before redirecting.

**Comment by serialt** [comment]
> > > > > @serialt Hi! Is your recurrence environment still preserved? If so, please give me the redirect_url param of the casdoor oauth page's URL.
> > > > > Just like that
> > > > > ![image](https://user-images.githubusercontent.com/45236136/192143365-0609aac4-49a3-4e94-b000-b5aad7b3418d.png)
> > > > 
> > > > 
> > > > `http://172.16.16.50:8000/login/oauth/authorize?access_type=online&client_id=96af38316c830f6ccb84&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin%2Fgeneric_oauth&response_type=code&scope=user%3Aemail&state=HdtrofooAEQPf3quYlbH4XD_zPVR57UfnApOqH8l8DM%3D`
> > > 
> > > 
> > > @serialt Can you show me the network logs when the browser jumps from your grafana page to the oauth page? Maybe you need to change the network speed at the browser console settings to take screenshots conveniently.
> > 
> > 
> > <img alt="image" width="1274" src="https://user-images.githubusercontent.com/58406690/192144806-b00f2e91-287b-4564-bb8c-8fb27cf57de8.png">
> 
> Sorry, I means the network logs of grafana page before redirecting. And including the Name field please. ![image](https://user-images.githubusercontent.com/45236136/192145162-856cf7f3-b72a-49a9-b6e1-c174c7914e6b.png)

Sorry，It's my fault， I do not set the root_url  in  grafana.conf, Thanks!!!

**Comment by wangguan1024** [comment]
You are welcome

> > > > > > @serialt Hi! Is your recurrence environment still preserved? If so, please give me the redirect_url param of the casdoor oauth page's URL.
> > > > > > Just like that
> > > > > > ![image](https://user-images.githubusercontent.com/45236136/192143365-0609aac4-49a3-4e94-b000-b5aad7b3418d.png)
> > > > > 
> > > > > 
> > > > > `http://172.16.16.50:8000/login/oauth/authorize?access_type=online&client_id=96af38316c830f6ccb84&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin%2Fgeneric_oauth&response_type=code&scope=user%3Aemail&state=HdtrofooAEQPf3quYlbH4XD_zPVR57UfnApOqH8l8DM%3D`
> > > > 
> > > > 
> > > > @serialt Can you show me the network logs when the browser jumps from your grafana page to the oauth page? Maybe you need to change the network speed at the browser console settings to take screenshots conveniently.
> > > 
> > > 
> > > <img alt="image" width="1274" src="https://user-images.githubusercontent.com/58406690/192144806-b00f2e91-287b-4564-bb8c-8fb27cf57de8.png">
> > 
> > 
> > Sorry, I means the network logs of grafana page before redirecting. And including the Name field please. ![image](https://user-images.githubusercontent.com/45236136/192145162-856cf7f3-b72a-49a9-b6e1-c174c7914e6b.png)
> 
> Sorry，It's my fault， I do not set the root_url in grafana conf, Thanks!!!

You are welcome.
