### ISSUE TITLE
The Docker install on portainer is not working fine

### ISSUE THREAD

**Issue by miguelgargallo** [casdoor/casdoor#1163]
panic: dial tcp 127.0.0.1:3306: connect: connection refused

goroutine 1 [running]:

github.com/casdoor/casdoor/object.(*Adapter).createTable(0xc00026d740)

	/go/src/casdoor/object/adapter.go:125 +0x877

github.com/casdoor/casdoor/object.InitAdapter(0x0)

	/go/src/casdoor/object/adapter.go:50 +0xb1

main.main()

	/go/src/casdoor/main.go:38 +0xa7

**Comment by forestmgy** [comment]
@miguelgargallo This is because localhost in Docker means different from local 
plz try this ,it will help you
https://casdoor.org/docs/basic/try-with-docker
![image](https://user-images.githubusercontent.com/101162387/192485366-a3d6c7a2-2027-4415-ad32-fcb5fa015d3c.png)
