### ISSUE TITLE
Bug:  panic: runtime error: slice bounds out of range [:1] with length 0

### ISSUE THREAD

**Issue by forestmgy** [casdoor/casdoor#1166]
When I use the latest version and execute `go run main.go`, there are some problems

`
[xorm] [warn]  2022/09/28 17:00:12.577857 Table permission_rule has column p_type but struct has not related field
Socks5 proxy enabled: 127.0.0.1:10808
[xorm] [warn]  2022/09/28 17:00:12.607090 Table casbin_rule has column p_type but struct has not related field
panic: runtime error: slice bounds out of range [:1] with length 0

goroutine 1 [running]:
github.com/casbin/casbin/v2/persist.LoadPolicyLine({0xc00003abc0, 0x19}, 0x7?)
        D:/developer_tool/Go_SDK/go1.18.3/bin/pkg/mod/github.com/casbin/casbin/v2@v2.30.1/persist/adapter.go:41 +0x4a5
github.com/casbin/xorm-adapter/v3.loadPolicyLine(0xc000032c00?, 0x1ee6780?)
        D:/developer_tool/Go_SDK/go1.18.3/bin/pkg/mod/github.com/casbin/xorm-adapter/v3@v3.0.1/adapter.go:269 +0x245
github.com/casbin/xorm-adapter/v3.(*Adapter).LoadPolicy(0xc0000e64b0, 0x20d4780?)
        D:/developer_tool/Go_SDK/go1.18.3/bin/pkg/mod/github.com/casbin/xorm-adapter/v3@v3.0.1/adapter.go:281 +0x15f
github.com/casbin/casbin/v2.(*Enforcer).LoadPolicy(0xc000590c00)
        D:/developer_tool/Go_SDK/go1.18.3/bin/pkg/mod/github.com/casbin/casbin/v2@v2.30.1/enforcer.go:276 +0x1cc
github.com/casbin/casbin/v2.(*Enforcer).InitWithModelAndAdapter(0xc000590c00, 0xc0006df800, {0x1e6fc60c440?, 0xc0000e64b0?})
        D:/developer_tool/Go_SDK/go1.18.3/bin/pkg/mod/github.com/casbin/casbin/v2@v2.30.1/enforcer.go:170 +0x29a
github.com/casbin/casbin/v2.NewEnforcer({0xc00070feb0, 0x2, 0x1?})
        D:/developer_tool/Go_SDK/go1.18.3/bin/pkg/mod/github.com/casbin/casbin/v2@v2.30.1/enforcer.go:106 +0x406
github.com/casdoor/casdoor/authz.InitAuthz()
        D:/project/project2/casdoor/authz/authz.go:66 +0x18d
main.main()
        D:/project/project2/casdoor/main.go:44 +0x158`

**Comment by leo220yuyaodog** [comment]
Cause by https://github.com/casdoor/casdoor/pull/1165

**Comment by forestmgy** [comment]
Thank you, I've resolved this problem by deleting table 'casbin_rule' and restart this project, it works fine
