### ISSUE TITLE
Bug: steam login users may have same nickname or violates the restriction of casdoor username

### ISSUE THREAD

**Issue by jack77213** [casdoor/casdoor#1222]
The current version  (v1.133.0) uses Steam nickname as username, but multiple Steam users can use the same username, and the username can contain CJK characters. Suggest to use unique 64bit steamtid as username.
https://github.com/casdoor/casdoor/blob/v1.133.0/idp/goth.go#L285
#1203

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/8b222ce2e396dc52feb3b6adc55d3ad58d31d4b3
