### ISSUE TITLE
bug：using wechat, baidu, etc, login fail: There was a problem signing you in..

### ISSUE THREAD

**Issue by hoorayman** [casdoor/casdoor#1230]
There was a problem signing you in..
The username may only contain alphanumeric characters, underlines or hyphens, cannot have consecutive hyphens or underlines, and cannot begin or end with a hyphen or underline.
![image](https://user-images.githubusercontent.com/73151874/196599433-aedb58a6-7263-4e1a-b1f3-54b20708ae9b.png)

**Comment by Airkro** [comment]
Have you tried [1.134.0](https://github.com/casdoor/casdoor/releases/tag/v1.134.0)?
The same problem has been fix, See https://github.com/casdoor/casdoor/issues/1223

**Comment by hoorayman** [comment]
Yes, no problem when using v1.134.0, thanks.
