### ISSUE TITLE
How to connect to Jira?

### ISSUE THREAD

**Issue by dingchenzy** [casdoor/casdoor#1255]
I want to log into Jira with Casdoor, how to configure it?

**Comment by hsluoyz** [comment]
@dingchenzy plz modify all texts into English

**Comment by jakiuncle** [comment]
hi,you can use casdoor java jdk to do it or I do it.

**Comment by hsluoyz** [comment]
@dingchenzy see docs: https://casdoor.org/docs/integration/java/jira

**Comment by dingchenzy** [comment]
Thank you
