### ISSUE TITLE
Memory leak problem

### ISSUE THREAD

**Issue by yaozhuangyanlingyu** [casdoor/casdoor#1256]
The database synchronizer method has a memory leak problem:
getOriginalUsers()

Phenomenon: When it was first deployed to the k8s, the memory occupied about 20mb, the upper limit of memory was set to 256mb, and the synchronizer executed every minute. After running for one day, the memory became 600+mb, causing the service to run abnormally

After the test, it is modified as follows, and then it returns to normal:
func (syncer *Syncer) getOriginalUsers() ([]*OriginalUser, error) {
	sql := fmt.Sprintf("select * from %s", syncer.getTable())
	results, err := syncer.Adapter.Engine.QueryString(sql)
	if err != nil {
		return nil, err
	}

	users := syncer.getOriginalUsersFromMap(results)

	// Memory leak problem handling
	for _, m := range results {
		for k, _ := range m {
			delete(m, k)
		}
	}
	return users, nil
}

**Comment by Abingcbc** [comment]
Maybe the root cause https://github.com/golang/go/issues/42455
It may be better to set the env variable GODEBUG=madvdontneed=1
