### ISSUE TITLE
Allow using application's own login page UI to call Casdoor login API

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#1259]
Like below, the application still maintains its own frontend page, but it calls Casdoor RESTful API to do the job. We need to wrap all necessary APIs into the frontend SDKs like casdoor-js-sdk to let the user call them

![(HY6KXP5KK$ GBJAG${`6Y2](https://user-images.githubusercontent.com/3787410/200012200-18692b78-6f43-4a28-8b2c-55add00b6450.png)

**Comment by akp660** [comment]
I want to contribute on ui part

**Comment by z0mb1ek** [comment]
is it keycloak?

**Comment by Vermasushant144** [comment]
Hello I am sushant verma gfg lead in niet college.
I want do work on this issue so please sir assign me .
Thank you
