### ISSUE TITLE
no id field in api "/api/get-models" and "/api/get-permissions"

### ISSUE THREAD

**Issue by JhouXerox** [casdoor/casdoor#1276]
no id field in api "/api/get-models" and "/api/get-permissions"

because of it
I can't get detail info by api "/api/get-model?id=" and "/api/get-permission?id="

**Comment by JhouXerox** [comment]
I'm using docker container. casbin/casdoor-all-in-one v1.149.0

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by leo220yuyaodog** [comment]
> no id field in api "/api/get-models" and "/api/get-permissions"
> 
> because of it I can't get detail info by api "/api/get-model?id=" and "/api/get-permission?id="

Now Casdoor accept "id" format `owner/name`. In backend, casdoor parse the "id" to `owner` and `name`. Then use the `owner` and `name` to get unique `model` or `permission`.  Does that can solve your problem?

**Comment by JhouXerox** [comment]
> > no id field in api "/api/get-models" and "/api/get-permissions"
> > because of it I can't get detail info by api "/api/get-model?id=" and "/api/get-permission?id="
> 
> Now Casdoor accept "id" format `owner/name`. In backend, casdoor parse the "id" to `owner` and `name`. Then use the `owner` and `name` to get unique `model` or `permission`. Does that can solve your problem?

thanks for your reply.
It works

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/24403596/200842938-118643bd-3d7c-4750-990a-7bdc1d5f3d41.png">
