### ISSUE TITLE
Casdoor Idp communicates with SAC through SAML

### ISSUE THREAD

**Issue by fearless87** [casdoor/casdoor#1287]
Good evening, help to follow up, thank you!

1. Background of the problem
![image](https://user-images.githubusercontent.com/8747775/201388079-ed65b599-6aa6-417f-80f9-61fd6d53b8e1.png)

- The same Casdoor Idp SAML configuration has no problem connecting to gosaml2
- Similarly, an error occurs when the Casdoor Idp SAML configuration connects to the SAC

2. Even SAC's error description
![image](https://user-images.githubusercontent.com/8747775/201387641-a83c68dc-2b73-45a9-bc41-2ed10cc48138.png)

- The following error message is displayed when Compress SAML Response is enabled
Protocol message signature failed signature pre-validation
- The following error message is displayed when Compress SAML Response is disabled
Encountered error parsing message into its DOM representation

3. Problem progression (Possible cause)
- You can connect to SAC from a third party IDAAS Authing
![)EWH2L_N{PO40MXH_RLR544](https://user-images.githubusercontent.com/8747775/201388389-98bcb972-b747-4bd5-ab7c-2b97fa379008.png)

- The only reason between them to be verified
Casdoor：The SAC requests a SAMLResponse through get
Authing：The Authing post SAMLResponse to the SAC

Thanks.

**Comment by hsluoyz** [comment]
@fearless87 Casdoor now supports SAML POST too, update to latest version to try it. Also see docs: https://casdoor.org/docs/how-to-connect/saml/overview#configuration-in-casdoor-idp
