### ISSUE TITLE
I hope the official team can automatically upgrade the Docker container

### ISSUE THREAD

**Issue by star7th** [casdoor/casdoor#1294]
The Docker image I use is casbin/casdoor: v1.32.0. When I try to change the image to casbin/casdoor: v1.157.0, an error occurs:

```

[xorm] [warn]  2022/11/14 02:20:21.194025 Table cert has column public_key but struct has not related field
[xorm] [warn]  2022/11/14 02:20:21.220707 Table casbin_rule has column p_type but struct has not related field
[xorm] [warn]  2022/11/14 02:20:21.233234 Table casbin_rule has column p_type but struct has not related field
panic: runtime error: slice bounds out of range [:1] with length 0
goroutine 1 [running]:
github.com/casbin/casbin/v2/persist.LoadPolicyLine({0xc0001855a0, 0x19}, 0x7)
        /go/pkg/mod/github.com/casbin/casbin/v2@v2.30.1/persist/adapter.go:41 +0x4a5
github.com/casbin/xorm-adapter/v3.loadPolicyLine(0xc000695110, 0x15c7680)
        /go/pkg/mod/github.com/casbin/xorm-adapter/v3@v3.0.1/adapter.go:269 +0x245
github.com/casbin/xorm-adapter/v3.(*Adapter).LoadPolicy(0xc00009ba40, 0x17b3940)
        /go/pkg/mod/github.com/casbin/xorm-adapter/v3@v3.0.1/adapter.go:281 +0x15f
github.com/casbin/casbin/v2.(*Enforcer).LoadPolicy(0xc00069a800)
        /go/pkg/mod/github.com/casbin/casbin/v2@v2.30.1/enforcer.go:275 +0x42
github.com/casbin/casbin/v2.(*Enforcer).InitWithModelAndAdapter(0xc00069a800, 0x18df6a0, {0x7f5b02f359e8, 0xc00009ba40})
        /go/pkg/mod/github.com/casbin/casbin/v2@v2.30.1/enforcer.go:169 +0xfe
github.com/casbin/casbin/v2.NewEnforcer({0xc0005cfeb0, 0x2, 0x1})
        /go/pkg/mod/github.com/casbin/casbin/v2@v2.30.1/enforcer.go:105 +0x406
github.com/casdoor/casdoor/authz.InitAuthz()
        /go/src/casdoor/authz/authz.go:68 +0x18e
main.main()
        /go/src/casdoor/main.go:44 +0x158


```

It seems that the incompatibility is caused by the change of database structure. I hope the upgrade script can be integrated into the new version of Docker image. When it is judged that the data is old, it will be automatically upgraded

**Comment by hsluoyz** [comment]
@forestmgy

**Comment by forestmgy** [comment]
Do you have a table named `migrations` in your database?

**Comment by forestmgy** [comment]
@star7th Or you can drop `permission_rule` and `casbin_rule` and restart. I 'll find why it is not work in Docker

**Comment by star7th** [comment]
There is no table called migrations. 
I drop permission_ rule and casbin_rule and restart . It works.

**Comment by star7th** [comment]
But there are two other problems. I don't know whether to write them here or issue them again
1. After v1.32.0 is upgraded to v1.157.0, the super administrator account admin cannot log in with the original password. I don't know if this is related to the encryption method I changed in the background.
2. When I reset the password by email, it prompts "tls: first record does not look like a TLS handshake" before sending the email verification code

**Comment by forestmgy** [comment]
> But there are two other problems. I don't know whether to write them here or new issue
> 
> 1. After v1.32.0 is upgraded to v1.157.0, the super administrator account admin cannot log in with the original password. I don't know if this is related to the encryption method I changed in the background.
> 2. When I reset the password by email, it prompts "tls: first record does not look like a TLS handshake" before sending the email verification code

@star7th maybe you can open a new issue

**Comment by hsluoyz** [comment]
Moved to: https://github.com/casdoor/casdoor/issues/1295
