### ISSUE TITLE
Not built-in organization's user cannot call the Casbin API

### ISSUE THREAD

**Issue by MagicalSheep** [casdoor/casdoor#1305]
Casbin APIs such as `/api/enforce` and `/api/batch-enforce` should be able to be called from other organizations' user, since it is used for external applications' user authorization. However, if we use an `access_token` from the not built-in organization in this version will only get an unauthorized operation error like below. 

### Set `access_token` in the HTTP header

![0](https://user-images.githubusercontent.com/45689738/202410305-4c75b410-9a31-4489-9dbc-d9439371111b.png)

### Request body and response body

![1](https://user-images.githubusercontent.com/45689738/202410431-5bf98768-f0e1-4a23-b24f-120310ee8220.png)

### Backend log

```shell
subOwner = TestOrg, subName = TestUser, method = POST, urlPath = /api/enforce, obj.Owner = , obj.Name = , result = deny
2022/11/17 16:57:29.421 [I]  (::1: ) subOwner = TestOrg, subName = TestUser, method = POST, urlPath = /api/enforce, obj.Owner = , obj.Name = , result = deny
subOwner = TestOrg, subName = TestUser, method = POST, urlPath = /api/batch-enforce, obj.Owner = , obj.Name = , result = deny
2022/11/17 16:59:59.601 [I]  (::1: ) subOwner = TestOrg, subName = TestUser, method = POST, urlPath = /api/batch-enforce, obj.Owner = , obj.Name = , result = deny
```

**Comment by MagicalSheep** [comment]
Minor changes in `authz/authz.go` can solve the problem. But I can't make sure whether changing the rule text is ok for Casdoor. For this reason, I just open the issue.

**Comment by hsluoyz** [comment]
@MagicalSheep see Casnode example code: https://github.com/casbin/casnode/blob/master/casdoor/user.go and docs: https://casdoor.org/docs/how-to-connect/sdk#5-optional-interact-with-the-user-table

Your application should use app's clientId and clientSecret to call the API

**Comment by MagicalSheep** [comment]
> @MagicalSheep see Casnode example code: https://github.com/casbin/casnode/blob/master/casdoor/user.go and docs: https://casdoor.org/docs/how-to-connect/sdk#5-optional-interact-with-the-user-table
> 
> Your application should use app's clientId and clientSecret to call the API

@hsluoyz Using the Basic Auth method for the authorization API will cause the interface to not work properly. This is because the information carried in the Authentication field in the HTTP request header can only be used to identify the application (`app/{app_name}`), not a user in the organization (`{org_name}/{user_name}`).

At this stage, the authorization API obtains the subject information from the Cookies, and the information of the Cookies is parsed by the filter from the Authentication field of the request header. For the permissions policy used by Casdoor, `app/{app_name}` is sufficient to determine whether to allow the API. However, the authorization API does not use application information, but the information of the calling subject, which requires the Bearer method to control the authorization API.

I think this is a design mistake of the authorization API. Authorization subject information should be passed to the authorization handler function as an API parameter, and the API itself is authenticated using Basic Auth. This will not break Casdoor's API permission control strategy.

**Comment by hsluoyz** [comment]
@MagicalSheep the normal users from non `built-in` orgs can't access these APIs. For your scenario, your application should use the application's identity (clientId & clientSecret) to access these APIs. If you really want to let normal users to access it, you can expose these APIs in your own backend.

**Comment by MagicalSheep** [comment]
> @MagicalSheep the normal users from non `built-in` orgs can't access these APIs. For your scenario, your application should use the application's identity (clientId & clientSecret) to access these APIs. It's something like `machine-to-machine` authentication.
> 
> If you really want to let normal users to access it, you can expose these APIs in your own backend. Casdoor will not expose it by default to avoid security issues.

@hsluoyz That's what I suggest above to solve the problem. Just add a parameter `v0` for these APIs and keep the `Basic Auth` method the Casdoor uses to avoid access from normal users. 
 
Without `v0` parameter the non-built-in application cannot make use of the Casbin that Casdoor. See [pull request which exposes Casbin APIs](https://github.com/casdoor/casdoor/pull/955#issuecomment-1206368214) for how the backend works with these APIs. They use `Bearer Auth` method however it is not what I suggest changing. 

I can make a pull request to do changes if you agree with this suggestion. Otherwise, there will be some mistakes in the documentation, and need some extra explanation.

**Comment by hsluoyz** [comment]
@MagicalSheep yes, `v0` should be added. You are welcome to make a PR
