### ISSUE TITLE
PG XORM create table error

### ISSUE THREAD

**Issue by huiwenhan** [casdoor/casdoor#1307]
D:\project\dpp\casdoor>go run main.go
[xorm] [info]  2022/11/18 19:31:10.265604 [SQL] SELECT tablename FROM pg_tables WHERE schemaname = $1 [public] - 87.7421ms
[xorm] [info]  2022/11/18 19:31:10.287558 [SQL] SELECT column_name, column_default, is_nullable, data_type, character_maximum_length,
    CASE WHEN p.contype = 'p' THEN true ELSE false END AS primarykey,
    CASE WHEN p.contype = 'u' THEN true ELSE false END AS uniquekey
FROM pg_attribute f
    JOIN pg_class c ON c.oid = f.attrelid JOIN pg_type t ON t.oid = f.atttypid
    LEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = f.attnum
    LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
    LEFT JOIN pg_constraint p ON p.conrelid = c.oid AND f.attnum = ANY (p.conkey)
    LEFT JOIN pg_class AS g ON p.confrelid = g.oid
    LEFT JOIN INFORMATION_SCHEMA.COLUMNS s ON s.column_name=f.attname AND c.relname=s.table_name
WHERE n.nspname= s.table_schema AND c.relkind = 'r'::char **AND c.relname = $1AND** s.table_schema = $2 AND f.attnum > 0 ORDER BY f.attnum; [organization public] - 4.2163ms
panic: pq: trailing junk after parameter 在 "$1A" 或附近的

**Comment by forestmgy** [comment]
@huiwenhan Can you give me more details? Like the PG version, the Casdoor version, etc.
And is this your first time starting Casdoor?

**Comment by forestmgy** [comment]
Please follow the instruction of docs here https://casdoor.org/docs/basic/server-installation#configuration

**Comment by cofecatt** [comment]
![image](https://user-images.githubusercontent.com/60803595/202859198-71633880-923e-47ce-ae12-c339551182fa.png)


> D:\project\dpp\casdoor>go run main.go [xorm] [info] 2022/11/18 19:31:10.265604 [SQL] SELECT tablename FROM pg_tables WHERE schemaname = $1 [public] - 87.7421ms [xorm] [info] 2022/11/18 19:31:10.287558 [SQL] SELECT column_name, column_default, is_nullable, data_type, character_maximum_length, CASE WHEN p.contype = 'p' THEN true ELSE false END AS primarykey, CASE WHEN p.contype = 'u' THEN true ELSE false END AS uniquekey FROM pg_attribute f JOIN pg_class c ON c.oid = f.attrelid JOIN pg_type t ON t.oid = f.atttypid LEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = f.attnum LEFT JOIN pg_namespace n ON n.oid = c.relnamespace LEFT JOIN pg_constraint p ON p.conrelid = c.oid AND f.attnum = ANY (p.conkey) LEFT JOIN pg_class AS g ON p.confrelid = g.oid LEFT JOIN INFORMATION_SCHEMA.COLUMNS s ON s.column_name=f.attname AND c.relname=s.table_name WHERE n.nspname= s.table_schema AND c.relkind = 'r'::char **AND c.relname = $1AND** s.table_schema = $2 AND f.attnum > 0 ORDER BY f.attnum; [organization public] - 4.2163ms panic: pq: trailing junk after parameter 在 "$1A" 或附近的

**Comment by hsluoyz** [comment]
@huiwenhan duplicated with: https://github.com/casdoor/casdoor/issues/1318

Fixed by: https://github.com/casdoor/casdoor/pull/1321
