### ISSUE TITLE
 Why can't a user be set as an admin or a global admin?

### ISSUE THREAD

**Issue by kxbin** [casdoor/casdoor#1308]
The switch cannot be clicked.

![image](https://user-images.githubusercontent.com/17782922/202839339-8951ec15-ec7b-4f97-a172-32443084241e.png)

**Comment by hsluoyz** [comment]
@kxbin use `built-in/admin` to login, like: https://door.casdoor.com/users/casbin/chenchangbing@gmail.com

it can be enabled:

![image](https://user-images.githubusercontent.com/3787410/202955601-48ecaa06-3a2e-4d27-8d5b-f038f4292d53.png)

**Comment by kxbin** [comment]
@hsluoyz  Hello, I'm pretty sure I'm using the `built-in/admin` login 

In `https://door.casdoor.com` demo, also some users are unable to click, such as:

![image](https://user-images.githubusercontent.com/17782922/202981840-78f25165-8b5f-432b-9b97-d977801dcb85.png)

![image](https://user-images.githubusercontent.com/17782922/202981942-3ef4787b-21b5-471d-8c99-d23b29b9e316.png)

For users who can click, an unauthorized operation will be prompted when saving, such as:

![image](https://user-images.githubusercontent.com/17782922/202982195-c5fa2485-51e7-4891-bbc7-c82dff7e34aa.png)

![image](https://user-images.githubusercontent.com/17782922/202982282-afb3d2cc-35a0-45ff-a24d-f2e5bbd1830c.png)

**Comment by hsluoyz** [comment]
@kxbin All the users under built-in organization, including admin will have the full administrator power on the Casdoor platform by default. So you cannot change the switch.

The demo site is read-only. You cannot modify its setting

**Comment by kxbin** [comment]
Thank you :)
