### ISSUE TITLE
Inconsistent translation format for tooltips

### ISSUE THREAD

**Issue by imchell** [casdoor/casdoor#1309]
The format of tooltips in English is "xxx - Tooltip" while they are "xxx" in Chinese.

![english 1](https://s2.loli.net/2022/11/20/IOybn7Yi3Q6EguD.png)
![chinese 1](https://s2.loli.net/2022/11/20/4zfoimAOc1a6ru7.png)
![english 2](https://s2.loli.net/2022/11/20/cHjg8Gl1Bibepyq.png)
![chinese 2](https://s2.loli.net/2022/11/20/N8mZY4VkfgG3ecw.png)

**Comment by hsluoyz** [comment]
@imchell this is because no one is translating the En. @yoyo314 can you do this?

**Comment by hsluoyz** [comment]
Already resolved
