### ISSUE TITLE
How to set as `admin` or `globalAdmin`

### ISSUE THREAD

**Issue by kxbin** [casdoor/casdoor#1312]
Link to issue #1308 

Under the identity of built-in/admin, I don’t know how to turn on this switch. 

I think there needs to be some clarification in the docs, or maybe this is a bug?

In the demo of https://door.casdoor.com, some users can click the switch to switch, but when saving, it will prompt unauthorized operation.

**Comment by hsluoyz** [comment]
@kxbin All the users under built-in organization, including admin will have the full administrator power on the Casdoor platform by default. So you cannot change the switch. See: https://casdoor.org/docs/basic/core-concepts#how-does-casdoor-manage-itself

The demo site is read-only. You cannot modify its setting

**Comment by kxbin** [comment]
@hsluoyz  Thank you, I see. I tested successfully in my environment
