### ISSUE TITLE
DB Syncer question

### ISSUE THREAD

**Issue by alenapoliakova** [casdoor/casdoor#1342]
Hello 👋!

I have a question about parameters in Casdoor DB syncer:

- What is "**Avatar base URL**" and "**Affiliation table**"? When I need to use it? I didn't see information about it in docs.

- When I need to use "**Is Hashed**" checkbox? (In docs I saw description: "whether to calculate hash value", well, but for what purpose you need to calculate value?)

Thank you for answer 🙂

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by leo220yuyaodog** [comment]
> Hello 👋!
> 
> I have a question about parameters in Casdoor DB syncer:
> 
> * What is "**Avatar base URL**" and "**Affiliation table**"? When I need to use it? I didn't see information about it in docs.
> * When I need to use "**Is Hashed**" checkbox? (In docs I saw description: "whether to calculate hash value", well, but for what purpose you need to calculate value?)
> 
> Thank you for answer 🙂
1.  "Avatar base URL" and "Affiliation table" are used when synchronizing users.  When sync users, if "Avatar base URL" is not empty and `user.avatar` not hasPrefix http, new `user.avatar` will be  `Avatar base URL + user.avatar`. 
2.  When enable "Is Hashed", if the field of user in orgin table update,  the syncer will sync the user. If not enable "Is Hashed", meaning the field update, but the syncer need not to sync the user.

**Comment by alenapoliakova** [comment]
Thank you for detailed explanation!
