### ISSUE TITLE
Web sends to API list applications only with owner=admin

### ISSUE THREAD

**Issue by alenapoliakova** [casdoor/casdoor#1379]
Hello👋!

I am using Casdoor system. I sent request to Casdoor API for create application with owner "user" (this user doesn't have admin rights). Casdoor created this application (response: `{'status': 'ok', 'msg': '', 'sub': '', 'name': '', 'data': 'Affected', 'data2': None}`).

I login with "user" and press "Applications", Casdoor sent request: `get-applications?owner=admin&p=1` with owner=admin:
![image](https://user-images.githubusercontent.com/92956391/206017461-302a1168-d2b9-4cd7-8f69-36bc874df679.png)

But I am not an admin and I don't see my Application what I have been created.

**Comment by hsluoyz** [comment]
@alenapoliakova the `owner` field for an application should always be `admin`, it's just a hard-coded value and doesn't mean a user named `admin` owns this application. An application can and only can belong to one organization, specified by the `organization` field
