### ISSUE TITLE
Add new provider category: Notification

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#1382]
### Discussed in https://github.com/casdoor/casdoor/discussions/1378

<div type='discussions-op-text'>

<sup>Originally posted by **Vladimir-Va** December  7, 2022</sup>
Hello Casdoor team.
Is possible add Telegram provider for send message for telegram bot?
I think that when implementing [this request](https://github.com/casdoor/casdoor/discussions/1358) it will be very helpful.</div>

By @Vladimir-Va

We can consider integrating: https://github.com/nikoksr/notify to support a lot of message types like Telegram

**Comment by imp2002** [comment]
I'm working on this.
