### ISSUE TITLE
Verification code reports account doesn't exist error even when the user is signing up a new account

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#1395]
This PR: https://github.com/casdoor/casdoor/pull/1334 introduced a bug: it still reports account doesn't exist even when the user is signing up a new account. Verification code is used in following places, it should be:

1. Sign up -> account for the Email/Phone should not exist
2. Sign in -> account for the Email/Phone should exist
3. Forget password -> account for the Email/Phone should exist
4. Change account info -> account for the Email/Phone should exist

![image](https://user-images.githubusercontent.com/3787410/206887576-8c7307eb-61af-4442-b30e-2b72df642909.png)

**Comment by hsluoyz** [comment]
@forestmgy

**Comment by forestmgy** [comment]
Ok, I'll handle this
