### ISSUE TITLE
Can not found Jenkins plugin

### ISSUE THREAD

**Issue by bluicezhen** [casdoor/casdoor#1401]
I was looking into the documentation for the casdoor project, and it mentions that there is a Jenkins plugin available for download from the Jenkins Plugin Store or directly from their website. However, I could not find the plugin in the Jenkins Plugin Store, and the documentation does not provide any direct download link. Can you provide more information on how to obtain the Jenkins plugin for casdoor?
https://casdoor.org/docs/integration/java/jenkins%20plugin

Also see discussion here: https://github.com/casdoor/casdoor/discussions/1402

**Comment by hsluoyz** [comment]
@Abingcbc

**Comment by Abingcbc** [comment]
@bluicezhen You can search in the official plugin store now and follow its instructions
 https://plugins.jenkins.io/casdoor-auth/
![image](https://user-images.githubusercontent.com/34068205/208597591-289df8a5-b748-4678-9d9b-a03f8c006492.png)
