### ISSUE TITLE
localhost dev mode can't access backend api because of cors

### ISSUE THREAD

**Issue by SealinGp** [casdoor/casdoor#1408]
i follow the https://casdoor.org/docs/basic/server-installation for local dev .then i got this cors error.
![image](https://user-images.githubusercontent.com/32982627/208468919-53898d43-9b8a-4fb3-bdd5-235e7e5cc5b4.png)
![image](https://user-images.githubusercontent.com/32982627/208468824-f39a3fff-a8fa-42c3-9376-1a94e7f97608.png)
![image](https://user-images.githubusercontent.com/32982627/208469049-e28ba854-8f07-47b2-9910-2cb88e9815e9.png)

my app.conf file content
```
appname = casdoor
httpport = 8000
runmode = dev
copyrequestbody = true
driverName = mysql
dataSourceName = root:a123456@tcp(127.0.0.1:3306)/
dbName = casdoor
tableNamePrefix =
showSql = true
redisEndpoint =
defaultStorageProvider = 
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = "127.0.0.1:10082"
verificationCodeTimeout = 10
initScore = 2000
logPostOnly = false
origin = "http://localhost:7001"
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100
ldapServerPort = 389
languages = en,zh,es,fr,de,ja,ko,ru
quota = {"organization": -1, "user": -1, "application": -1, "provider": -1}
```

**Comment by SealinGp** [comment]
it will be fixed in my case if i change code like this
```golang

const (
	headerOrigin           = "Origin"
	headerAllowOrigin      = "Access-Control-Allow-Origin"
	headerAllowMethods     = "Access-Control-Allow-Methods"
	headerAllowHeaders     = "Access-Control-Allow-Headers"
	headerAllowCredentials = "Access-Control-Allow-Credentials"
)

func CorsFilter(ctx *context.Context) {
	origin := ctx.Input.Header(headerOrigin)
	originConf := conf.GetConfigString("origin")

	if origin == originConf {
		ctx.Output.Header(headerAllowOrigin, origin)
		ctx.Output.Header(headerAllowMethods, "POST, GET, OPTIONS")
		ctx.Output.Header(headerAllowHeaders, "Content-Type, Authorization")
		ctx.Output.Header(headerAllowCredentials, "true")

		if ctx.Input.Method() == "OPTIONS" {
			ctx.ResponseWriter.WriteHeader(http.StatusOK)
		}
		return
	}

	// if origin != "" && originConf != "" && origin != originConf {
	// 	if object.IsAllowOrigin(origin) {
	// 		ctx.Output.Header(headerAllowOrigin, origin)
	// 		ctx.Output.Header(headerAllowMethods, "POST, GET, OPTIONS")
	// 		ctx.Output.Header(headerAllowHeaders, "Content-Type, Authorization")
	// 	} else {
	// 		ctx.ResponseWriter.WriteHeader(http.StatusForbidden)
	// 		return
	// 	}

	// 	if ctx.Input.Method() == "OPTIONS" {
	// 		ctx.ResponseWriter.WriteHeader(http.StatusOK)
	// 		return
	// 	}
	// }
}

```
![image](https://user-images.githubusercontent.com/32982627/208472802-6c9f9df5-9474-4004-a407-a323043bf6a6.png)

**Comment by hsluoyz** [comment]
@ziranl16

**Comment by SealinGp** [comment]
> @SealinGp Hi, may I ask which release version did you clone?

![image](https://user-images.githubusercontent.com/32982627/208806036-df6e8377-1aab-4f20-a4aa-03bc0727a271.png)

commit: 26acece8aff3882ef1325a6f35e132ea1b84efb5
branch: master
tag: v1.189.0

**Comment by SealinGp** [comment]
> Hi @SealinGp , I tried to replicate the issue locally(win10) but mine seems to be working fine with all the recent commits in the master branch. I have searched online for relevant solutions, maybe you could also look at this extension [Allow CORS: Access-Control-Allow-Origin](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf) to resolve the issue instead of changing the code directly?
> 
> Moreover, would you mind seeing if you could successfully deploy earlier commits?
> 
> ![image](https://user-images.githubusercontent.com/62609375/208844055-30f5b7bd-2149-4412-96df-b4bd44273da9.png)
> 
> ![image](https://user-images.githubusercontent.com/62609375/208844010-ea1c06c0-957f-4859-9b2c-3c73ab373248.png)

your origin conf is empty ? can you show me the origin config value ?

**Comment by SealinGp** [comment]
> > your origin conf is empty ? can you show me the origin config value ?
> 
> yes,
> 
> ```
> appname = casdoor
> httpport = 8000
> runmode = dev
> copyrequestbody = true
> driverName = postgres
> dataSourceName = "user=postgres password=123456 host=localhost port=5432 sslmode=disable dbname=casdoor"
> dbName =
> tableNamePrefix =
> showSql = false
> redisEndpoint =
> defaultStorageProvider = 
> isCloudIntranet = false
> authState = "casdoor"
> socks5Proxy = "127.0.0.1:10808"
> verificationCodeTimeout = 10
> initScore = 2000
> logPostOnly = true
> origin =
> staticBaseUrl = "https://cdn.casbin.org"
> isDemoMode = false
> batchSize = 100
> ldapServerPort = 389
> languages = en,zh,es,fr,de,ja,ko,ru
> quota = {"organization": -1, "user": -1, "application": -1, "provider": -1}
> ```

maybe you should start web server to access the page, then you can get this error, i still got the same error using your config file.

the below operation previous required:
 - [nvm-windows](https://github.com/coreybutler/nvm-windows)

here are my steps to start web dev server(after installed nvm-windows).
1. web/src/Setting.js set backend api url 
 ```js
export const ServerUrl = "http://localhost:8000";
 ```
2. install dependencies & start web server
```bash
# assume you located in /xxx/casdoor dir
pwd=$PWD
cd $pwd/web && nvm install v16.10.0 && nvm use v16.10.0 && npm install --global yarn && yarn install && yarn start
```
then access http://localhost:7001/ and press F12 to see the console log

**Comment by SealinGp** [comment]
> Hi @SealinGp , yup I started the frontend & backend service using the commands as shown below. Doesn't seem to have this error. I installed [Go 1.6+](https://go.dev/dl/), [Node.js LTS (16 or 14)](https://nodejs.org/), and [Yarn 1.x](https://classic.yarnpkg.com/en/docs/install)
> 
> ![image](https://user-images.githubusercontent.com/62609375/208865396-2c85266a-f3fd-458f-a7e5-7625b2f19d18.png)
> 
> ![image](https://user-images.githubusercontent.com/62609375/208865501-c7fd98a5-489f-40db-9e22-da2c4441a11d.png)

i'm confused. can i see your web/src/Setting.js file content ?

**Comment by SealinGp** [comment]
> @SealinGp okay I now can replicate the error and have found the key part. In web/src/Setting.js, if the `ServerUrl` is empty, everything works fine. Else it results in CORS error. For your convenience, you can first leave web/src/Setting.js without modifications when running locally. I will debug the issue later.
> 
> ![image](https://user-images.githubusercontent.com/62609375/208869693-425bbdd4-b02f-4233-8c75-502256a59ca1.png)

i figure it out, just shutdown the local nginx server will be normal. thanks for your help. ^_^
