### ISSUE TITLE
The redirect url is incorrect after the user resets the password on the login page

### ISSUE THREAD

**Issue by HanadaLee** [casdoor/casdoor#1409]
When a user forgets his password, he will do the following.

The login page of the application -> Click Forgot Password -> Enter username/email -> Email or mobile phone to get the verification code -> Retset password -> **Redirect to login page or target application**

But After clicking Change Password, you will be redirected to https://cas.example.com/forget/https:/www.xxxxxx.com/login

![image](https://user-images.githubusercontent.com/33758411/208473188-a778ad61-1c0d-4b03-9fce-1c249e231361.png)

![image](https://user-images.githubusercontent.com/33758411/208473257-47731464-e990-4ce0-8459-c39e343cc9ee.png)

![image](https://user-images.githubusercontent.com/33758411/208473377-b4c6b15e-26c3-4922-a183-17b91414f4af.png)

![image](https://user-images.githubusercontent.com/33758411/208473501-e34117b1-4f07-4522-b18e-da42ccce481f.png)

It is currently known that www.xxxxxx.com in https://cas.example.com/forget/https:/www.xxxxxx.com/login is the [Home] corresponding to the [Signup Application] to which the user belongs.

**Comment by hsluoyz** [comment]
@imchell
