### ISSUE TITLE
The modify rule control of account items does not take effect

### ISSUE THREAD

**Issue by HanadaLee** [casdoor/casdoor#1414]
![image](https://user-images.githubusercontent.com/33758411/208731896-2d45a622-a364-4c95-96b8-9b7bc4772e6e.png)

As shown in the picture, the permission I set is that only administrators can modify this configuration. 
Ordinary users of the organization should only have viewing permissions, but in fact users can freely modify this configuration and elevate themselves to administrators. The configuration fails completely.

![image](https://user-images.githubusercontent.com/33758411/208732358-b6519cad-e6ba-41b2-8490-02652b6f1a0b.png)

![image](https://user-images.githubusercontent.com/33758411/208732381-6f5d5306-457b-42dd-abc9-552ac3c6ff7c.png)

![image](https://user-images.githubusercontent.com/33758411/208732402-75a4cb91-8743-4de7-895b-011060fd46f2.png)

![image](https://user-images.githubusercontent.com/33758411/208732430-9e16b55f-9e3d-45d4-adc4-1f83c15bf3e8.png)

**Comment by HanadaLee** [comment]
Also I think view rule and modify rule should be divided into four options: Self, Admin, Global admin and Immutable.

**Comment by imp2002** [comment]
https://user-images.githubusercontent.com/41513919/209277714-b272319f-6fbb-4ef6-ace6-562cd469fb8e.mp4

`view_rule` don't work in `is admin` indeed, but just in view, I can't modify the rule elevate themselves to administrators. Or is there something wrong with my usage, cloud you provide more information.

**Comment by HanadaLee** [comment]
You may need to test with a user from another organization instead of the built-in.

**Comment by imp2002** [comment]
的确没有做权限验证，存在提权漏洞

**Comment by imp2002** [comment]
Indeed, there is no permission verification in backend, and there is a privilege escalation vulnerability fix in #1438. 

And maybe some change should do in frontend too, but how your login the web use a organization that not built-in. When I login with a not built-in user, it show not exist user it's look like only built-in user can login. 

And I change built-in's view-rule and modify-rule, it's work right.
![image](https://user-images.githubusercontent.com/41513919/210137954-e318c906-f5e2-4634-b30f-5227b4e42b43.png)
