### ISSUE TITLE
Missing supported response mode

### ISSUE THREAD

**Issue by itineric** [casdoor/casdoor#1417]
Using genuine OIDC fails since the casdoor ".well-known/openid-configuration" does not declare the 'query' and 'fragment' default supported response modes as defined in the spec (see here : https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#ResponseModes )

We get:
```
"response_modes_supported": [
    "login",
    "code",
    "link"
  ],
```

We should get:
```
"response_modes_supported": [
    "query",
    "fragment",
    "login",
    "code",
    "link"
  ],
```

**Comment by hsluoyz** [comment]
@itineric can you make a PR to fix it?
