### ISSUE TITLE
Missing Background on Application Edit Page Previews

### ISSUE THREAD

**Issue by imchell** [casdoor/casdoor#1418]
The background of preview is all blank.

![preview](https://s2.loli.net/2022/12/23/FNOEoPxDZ6yjRiq.png)

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by leo220yuyaodog** [comment]
> @leo220yuyaodog

The commit https://github.com/casdoor/casdoor/commit/a0dc6e06cd12be4f7331ac64c0c693c51f986ad6 optimized the entryPages, move background to entryPage. Preview  box use the LoginPage componet directly, so it don't have background.  We need to adjust  the code to optimize the preview box.
