### ISSUE TITLE
Support login UI customization

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#142]
We know our login page (https://door.casbin.com/login) is provided by Casdoor itself. But the customers may want to customize their own login UI, like changing button color, changing background color, changing input box style, etc.

The customers should be able to upload or specify their own HTML, and Casdoor can use the uploaded HTML as login UI.

**Comment by hsluoyz** [comment]
@1340908470 plz do this

**Comment by 1340908470** [comment]
https://github.com/casbin/casdoor/pull/146

**Comment by nexmoe** [comment]
how about just importing a css file to let everyone edit

**Comment by hsluoyz** [comment]
@nexmoe sounds good! Can you implement it via a PR?

**Comment by JokerQyou** [comment]
Why is #146 closed without merging? I see the sign-in form can be customized a little bit but the CSS is only limited to the form itself, not the whole page.

**Comment by hsluoyz** [comment]
@JokerQyou this issue is already fixed, see: https://door.casdoor.com/applications/app-built-in

![image](https://user-images.githubusercontent.com/3787410/193849829-3f19a380-e4ad-4888-ac28-93fb665df803.png)

**Comment by hsluoyz** [comment]
@JokerQyou can you create a new issue and talk about your idea detailedly?
