### ISSUE TITLE
Casdoor does not properly termine existing user sessions when the user was deleted 

### ISSUE THREAD

**Issue by lujiefsi** [casdoor/casdoor#1427]
First, a user login casdoor in one page. Then the admin deletes the user in another page. But the user is still able to do any operations inside casdoor . Notice that refreshing the page will ask the user to login again.

Impact
If the user is admin, even after a user's account is deleted, the user can still access the administration panel (and add or delete users) and has complete access to the system.

More details can be seen in https://huntr.dev/bounties/d43eac1c-b2a2-423e-a84d-9b2f7facbada/  if you receive the mail in admin@casdoor.org.

**Comment by hsluoyz** [comment]
Dup with: https://github.com/casdoor/casdoor/issues/1141
