### ISSUE TITLE
bug: normal user can not update their own profile

### ISSUE THREAD

**Issue by leo220yuyaodog** [casdoor/casdoor#1452]
As show below, normal user can not update their own profile.

![image](https://user-images.githubusercontent.com/71440988/210682623-eb72edc5-0ccf-48f6-af09-5a3f1479d3bc.png)

**Comment by 1307super** [comment]
这个问题我也发现了, 代码里这俩判断也有问题:
reflect.DeepEqual(oldUser.Roles, newUser.Roles)
reflect.DeepEqual(oldUser.Permissions, newUser.Permissions)

这个判断是相等的时候 修改, 实际上应该是不相等修改, 但是修改为不相等时, 因为oldUser这俩属性是nil, newUser是切片, 而前端并不能修改角色和权限, 所以这里恒不相等, 我本地改成了下图后, 恢复正常:

![image](https://user-images.githubusercontent.com/35326304/210688808-2ce55a8f-7f8d-43d9-9e42-180311ed1a06.png)

**Comment by hsluoyz** [comment]
I think this bug is caused by PR: https://github.com/casdoor/casdoor/pull/1438 , @imp2002 can you fix it?
