### ISSUE TITLE
Link account automatically

### ISSUE THREAD

**Issue by luyentm** [casdoor/casdoor#1453]
Thank you for awesome SSO app. How can we auto link account between provider based on email or phone? This feature similarly as firebase authentication!

**Comment by hsluoyz** [comment]
@luyentm can you give a detailed scenario as example?

**Comment by luyentm** [comment]
> @luyentm can you give a detailed scenario as example?

@hsluoyz I have an application with 2 providers: Google and Facebook. Currently, If I login by google and facebook provider, casdoor will create 2 users. My expectations: Application have a new checkbox: auto link account by email. It is mean Casdoor just create only 1 user if the Google/Facebook use the same email.
This behavious similarly with firebase authentication:
![image](https://user-images.githubusercontent.com/3795545/211058150-b3da51be-a0bb-47e6-8ad9-c752d4c6a44b.png)

**Comment by tlthanh** [comment]
I really hope this issue will be solved, I am having the same issue!
