### ISSUE TITLE
Return a 500 status code when updating a user

### ISSUE THREAD

**Issue by HanadaLee** [casdoor/casdoor#1455]
After https://github.com/casdoor/casdoor/pull/1438 was released, I tested the update user and found that he responded with 500 status code. The following is the log printed inside the container.

![image](https://user-images.githubusercontent.com/33758411/210815668-81c140c2-5d6f-4694-b0e3-f41f09a2ad8a.png)

![image](https://user-images.githubusercontent.com/33758411/210816210-72552afe-464b-44a8-94e7-1dd2d68fa3df.png)

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/pull/1454
