### ISSUE TITLE
ldap can not sync user

### ISSUE THREAD

**Issue by tangwei0928** [casdoor/casdoor#1471]
release：1.215.0
in the built-in Organization, add ldap server
![0D0A37441BC6357749685889A18EF6A1](https://user-images.githubusercontent.com/34976326/212071860-9d2c42c0-f0fb-437d-a5e7-6ed7baaf1e6c.jpg)
![image](https://user-images.githubusercontent.com/34976326/212071909-03182def-59e6-4d06-952f-9f5e4f571ec0.png)

but ldap can not sync user
i can see uses,but can not sync
![BACF3B6E857E8EFB5E49EC2548727525](https://user-images.githubusercontent.com/34976326/212072860-c0370c3c-6df0-4c27-9675-9543642d06df.jpg)

**Comment by tangwei0928** [comment]
user table only has admin user
![3DB12D7B243355C83E5BC704AEE49775](https://user-images.githubusercontent.com/34976326/212073972-0f2d58e6-86aa-4650-abbe-0eb823b5854c.jpg)

**Comment by OutOfEastGate** [comment]
@tangwei0928 Hi,Casdoor will first load the ladp user into the memory. At this time, you can choose to manually synchronize to the database. After the specified time, the data will be automatically synchronized to the database. At this time, the check box is not allowed to be selected.

Please check whether the database name and table name in your app.conf are correct. By default, casdoor uses the casdoor database and user table.

 I hope it can help you.

**Comment by OutOfEastGate** [comment]
In addition, please ensure that each user has a different uid, and casdoor distinguishes different users through the uid

**Comment by tangwei0928** [comment]
Still not,ladp users cannot be synchronized with built-in organization

**Comment by tangwei0928** [comment]
After the specified time, the ldap data can not be automatically synchronized to the database

**Comment by OutOfEastGate** [comment]
> After the specified time, the ldap data can not be automatically synchronized to the database

Please ensure that your ladp user meets the following conditions：

User distinguishment: Casdoor's synchronization only supports those ldap users which are subclass of posixAccount(to be precise, casdoor uses (objectClass=posixAccount) to query ldap users). Casdoor uses uid to exclusively identify a user, thus please make sure every ldap user has a different uid.

detail：https://casdoor.org/zh/docs/ldap/overview

**Comment by hsluoyz** [comment]
Closed as resolved
