### ISSUE TITLE
Frontend: `application` in SignupPage's state is undefined when jumping from the login page

### ISSUE THREAD

**Issue by hezean** [casdoor/casdoor#1489]
In both the master branch and the latest docker package, when I jump to the sign up page, `state.application` is undefined, which leads the phonePrefix to be `+undefined`. I can get the correct one only after refreshing the page.

Tested under Chrome and Safari.

![Screenshot 2023-01-22 at 22 51 37](https://user-images.githubusercontent.com/49837965/213922270-3535a433-13a2-4734-8fef-454ea58b9cdb.png)

<img width="606" alt="Screenshot 2023-01-22 at 22 50 52" src="https://user-images.githubusercontent.com/49837965/213922217-8407c888-498a-4358-a5bd-687e3f68065b.png">

**Comment by hsluoyz** [comment]
@leo220yuyaodog
