### ISSUE TITLE
[frontend] sometimes menu items don't work when screen size is small

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#1498]
Sometimes work, sometimes don't work

https://user-images.githubusercontent.com/3787410/215114029-adc0e1d5-a2fb-42fe-b12e-7f439a16ebb0.mp4

**Comment by imp2002** [comment]
It's look like a bug of antd. Info and reproduction in https://github.com/ant-design/ant-design/issues/40565
