### ISSUE TITLE
Public Internet Security Concerns

### ISSUE THREAD

**Issue by bluicezhen** [casdoor/casdoor#1507]
I am currently using Casdoor's SAML and OpenID to provide login functionality for my AWS VPC Client and Jenkins. However, I have concerns regarding the exposure of Casdoor's management functionality to the public Internet. I would like to understand which url I need to block for public access without affecting the user login process.

**Comment by hsluoyz** [comment]
@bluicezhen Casdoor is designed to be exposed in Internet just like any other close-source or open-source auth providers. What you requested is more of an enterprise-level security advice (just like any other software you use, like how to securely use or "enhance" Nginx) and is not the main focus of this open source project.
