### ISSUE TITLE
The cn attribute is inconsistent in ldap server search method.

### ISSUE THREAD

**Issue by imshenyz** [casdoor/casdoor#1508]
Hi, 

While I test the ldap server function, it print
```<username> auth test failed: LDAP Result Code 49 "Invalid Credentials": invalid credentials ErrMsg: The user: <orgName>/<DisplayName> doesn't exist```

So I check the code in ldapserver.go, and I found line 108 and 110 assign inconsistent attribute to cn.

https://github.com/casdoor/casdoor/blob/b47baa06e1a75c9a538b8b12acf513f6968bab7d/controllers/ldapserver.go#L106-L116

It cause the error above.

**Comment by hsluoyz** [comment]
@imshenyz hi, what LDAP client do you use? And can you make a PR to fix this issue?
