### ISSUE TITLE
Unable to delete files uploaded from Tencent Cloud COS with Chinese in the file name

### ISSUE THREAD

**Issue by ReflexFox** [casdoor/casdoor#1514]
![image](https://user-images.githubusercontent.com/42571543/216250767-b9ad687d-c669-4306-b585-7a9ff3194e6d.png)

**Comment by OutOfEastGate** [comment]
@ReflexFox Hi, thank you for your feedback. I have found the cause of the bug. Could you please provide the real file name you uploaded?

**Comment by ReflexFox** [comment]
@OutOfEastGate  副本yaizy产品功能对比(1).xlsx
