### ISSUE TITLE
Email provider expects '@' in the provider Username field

### ISSUE THREAD

**Issue by arunwij** [casdoor/casdoor#1516]
I am testing casdoor-all-in-one (v1.229.0) Docker image locally. I created an Email Provider and when I  click "Test Connection" it gives me the following success message, 

"Successfully connecting smtp server"

When I try "Send Test Email" option the application shows following error,
**gomail: could not send email 1: gomail: invalid address "\"Email\" <\*\*\*\*\*\*\*\*\*\*e9f8>": mail: missing @ in addr-spec**

It seems the Email Provider is using the Username field to send the email and it's not happy it does not contain '@' in the Username field. It's not necessary to have an '@' in the Username. 

I am using [Mailtrap](https://mailtrap.io/home) as the sandbox email service. 

Please see the image attachment for additional info.

![casdoor email provider](https://user-images.githubusercontent.com/18640541/216494068-f583fad4-7394-4bf2-888d-a231f6857072.png)

**Comment by hsluoyz** [comment]
@arunwij you should use an Email address as username, even mailtrap supports this: https://mailtrap.io/blog/smtp-auth/#:~:text=the%20username%20is%20the%20same%20as%20your%20email%20address

It seems that all providers like Gmail follow this rule. And gomail (the mail lib we used) also assumed this convention.

**Comment by arunwij** [comment]
@hsluoyz sorry for the delayed reply. I need to check if Mailtrap supports email usernames. 

I also came across this in [AWS SES](https://aws.amazon.com/ses/). AWS also uses SMTP credentials username without "@". (Support  plain usernames without email addresses) 

These are old AWS creds that are not valid anymore. 
![Monosnap 2023-02-06 09-20-16](https://user-images.githubusercontent.com/18640541/216881367-cbb7328e-4037-456e-a4c2-fd87c7d86b49.png)

**Comment by hsluoyz** [comment]
@arunwij it seems to be a bug of gomail, the Email library we used: https://github.com/go-gomail/gomail/issues/168 , we will find a way to fix it

**Comment by arunwij** [comment]
Okay, Thank you.
