### ISSUE TITLE
Beego Cookie Session

### ISSUE THREAD

**Issue by gaurishhs** [casdoor/casdoor#1528]
Hi! Instead of using Redis, Can you provide a config option to use cookie sessions (supported by Beego)

**Comment by hsluoyz** [comment]
@gaurishhs Beego sessions always rely on cookie on client-side. The difference is server-side. By default Casdoor stores session data into files, it can be also configured to use Redis: https://casdoor.org/docs/basic/server-installation#via-ini-file:~:text=great%20than%20INFO.-,redisEndpoint,-is%20the%20Redis
