### ISSUE TITLE
website icons href are too long will be automatically truncated

### ISSUE THREAD

**Issue by ReflexFox** [casdoor/casdoor#1529]
original href

https://XXXXX/casdoor/resource/built-in/admin/%25E9%2597%25AA%25E8%2590%258C%25E6%259C%258D%25E9%25A5%25B0%2B%2528logo%2529%2B%2B%25282%2529.png?t=1675820491227459709

after saved href

https://XXXXX/casdoor/resource/built-in/admin/%25E9%2597%25AA%25E8%2590%258C%25E6%259C%

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/42571543/217407850-e01e6de9-91ae-4331-8cb6-489b5bb5955c.png">

**Comment by hsluoyz** [comment]
@OutOfEastGate
