### ISSUE TITLE
When I use casdoor on low version ios system and vivo phone, there is a problem that js can't be loaded

### ISSUE THREAD

**Issue by vycz** [casdoor/casdoor#1553]
#### This is the system ua

![1 2K15H30{SEMM WNCHCDOV](https://user-images.githubusercontent.com/20987132/218467652-348fdd96-d798-4579-95c9-4c57a9f4423c.jpg)

#### ios13
![`UK1I_%$Y$MOP_2L F0I~BS](https://user-images.githubusercontent.com/20987132/218467225-caa63f16-3684-42ec-82ba-5c50e9a2fc70.png)

#### vivo phone
![40%GMKDJ79 QRIPJT@6I}`4](https://user-images.githubusercontent.com/20987132/218467259-b0a45e63-625b-4f5a-9704-8686903d12c6.png)

**Comment by hsluoyz** [comment]
It doesn't work on Chrome 87, Windows 10 either.

I think the main reason is that Casdoor uses Antd 5: https://github.com/casdoor/casdoor/pull/1362 and Antd 5 is somehow incompatible with some old browsers. Antd 4 won't have this problem

![image](https://user-images.githubusercontent.com/3787410/219392080-ffa51b51-cb30-4453-8d66-15f376a9e655.png)
