### ISSUE TITLE
Error 1049: Unknown database

### ISSUE THREAD

**Issue by makorne** [casdoor/casdoor#1560]
podman run --rm -p 8000:8000 casbin/casdoor-all-in-one

All looks as working excluding to changing the Adapter Policy:

Login and goto:
http://localhost:8088/adapters

Click Edit (default adapter)
**Failed to sync policies: Error 1049: Unknown database 'dbName'**

After redirect to:
http://localhost:8000/adapters/built-in/adapter_oypfwj  (default adapter)

Set dbName:
`casdoor`

Add any policy:

Policies:  ....
Click Save in this field

**Flash: Failed to add: Error 1049: Unknown database 'dbName'**

**Comment by hsluoyz** [comment]
@makorne you should make sure this DB connection string is correct. And it's not `casdoor` DB itself

![image](https://user-images.githubusercontent.com/3787410/219826650-b22f3449-765b-440b-90c8-aa7c6d5a84a5.png)
