### ISSUE TITLE
[frontend] add "sure to delete" to i18n

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#1569]
Remove the suffix noun so we only need to translate once, example:

`Sure to delete session: xxx` --> `Sure to delete: xxx`

![image](https://user-images.githubusercontent.com/3787410/219849332-918f8759-df8d-4ccd-815a-60032072553d.png)

**Comment by SaurabhChauhan213** [comment]
can i work on this

**Comment by hsluoyz** [comment]
@SaurabhChauhan213 OK
