### ISSUE TITLE
First run OK, second run causes error

### ISSUE THREAD

**Issue by zzg** [casdoor/casdoor#1570]
![1676736883222](https://user-images.githubusercontent.com/1320246/219876380-3026e8bb-f55c-4e51-b6fe-ea1d8d62a2ec.jpg)

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by hsluoyz** [comment]
@zzg fixed by: https://github.com/casdoor/casdoor/commit/3bda8fb9dc66dc41a9ddbc7b6655cab54224109a
