### ISSUE TITLE
Does casdoor support revoke oauth2 access token?

### ISSUE THREAD

**Issue by deljuven** [casdoor/casdoor#1574]
Is there some API or method to revoke certain OAuth2 aceess token or refresh token?

For example, a user can get login from different devices, and get different access tokens in these devices. Then, does casdoor support to revoke one of these access tokens to get him logout from one device? 

There is only delete token and logout api in [open api definition](https://door.casdoor.com/swagger/#/).

**Comment by hsluoyz** [comment]
@deljuven Casdoor supports single-sign-out by kicking user cookies, see demo at: https://door.casdoor.com/sessions

Assigned OAuth2 aceess token is issued by Casdoor and self-explanary. It is usually cannot be revoked from how it works.

**Comment by fischermario** [comment]
@hsluoyz: 

> what should be used as the ID?

As you have full control over the token's properties you can generate an ID for example with SHA256 from a cryptographically secure random string.

> Will using ID affect revoking the token?

Of course! Every token should have an ID in its properties. Only this ID is stored in the database. The contents of the token's properties can be trusted as the token as a whole will be verified. You can then provide an API endpoint to check for the token being valid or not. This would allow casdoor to have a blacklist of revoked token IDs without storing the tokens itself.

**Comment by hsluoyz** [comment]
@fischermario sounds good. Can you make a PR to fix it?

**Comment by hsluoyz** [comment]
@deljuven @fischermario how to design the token revoke and verify API? Is there any standard to follow?

**Comment by fischermario** [comment]
@hsluoyz I'm already working on a tentative design for this feature because you requested a PR which I would be glad to provide.

**Comment by hsluoyz** [comment]
@deljuven @fischermario we tend not to accept a home-made token revoke and verify API except it's part of OAuth 2.0 or OIDC standard. That being said, if OAuth 2.0 or OIDC has defined how to do token revoke and verify API, we will follow it and implement it. But if there's not, we will not accept another whole set of "home-made" solution or design.

However, it doesn't mean this cannot be done. You can use Casdoor RESTful API to do the same effect, see visualized example at: https://door.casdoor.com/tokens

1. Revoke: delete a token
2. Verify: get a token

![image](https://user-images.githubusercontent.com/3787410/230713780-0aead5dd-70e4-4091-8b7f-1dc83ae3cf31.png)

**Comment by nighca** [comment]
> we tend not to accept a home-made token revoke and verify API except it's part of OAuth 2.0 or OIDC standard. That being said, if OAuth 2.0 or OIDC has defined how to do token revoke and verify API, we will follow it and implement it.

@hsluoyz If I'm not mistaking, [token-revocation](https://oauth.net/2/token-revocation/) is part of OAuth 2.0.
