### ISSUE TITLE
[Feature request] SSO Form filling feature

### ISSUE THREAD

**Issue by ReflexFox** [casdoor/casdoor#1576]
feature like
Authing ASA https://docs.authing.cn/v2/guides/asa/ 
alibabacloud https://www.alibabacloud.com/help/zh/idaas/latest/y9yam5

Existing work: https://github.com/casdoor/casdoor-chrome-extension

**Comment by hsluoyz** [comment]
@ReflexFox the Casdoor Chrome plugin has already been released: https://github.com/casdoor/casdoor-chrome-extension

Install it via Chrome Web Store: https://chromewebstore.google.com/detail/casdoor-browser-plugin/bnjbegmkpjbcpneclidlbloadenondlm
