### ISSUE TITLE
[Bug] SAML Login still got "Failed to log in: err: EOF"

### ISSUE THREAD

**Issue by dev-techmoe** [casdoor/casdoor#1582]
# Step to reproduce
1. create a app called `test`
2. fill Name/DisplayName with `test`, and fill `SAML Reply URL` with `https://httpbin.org/anything` (it's just a test service to view all the http request)
3. save the app
4. visit `https://<casdoor_app_domain>/login/saml/authorize/admin/test` and click login
5. still got this message
![image](https://user-images.githubusercontent.com/7919562/221086789-8b459066-d1fe-4f60-91c0-c9331dcef117.png)

This can be reproduced  on the demo site: https://demo.casdoor.com/applications

I'm new user for casdoor and I love this project, but I cant get any valuable information from this error message, could you give some ways to find out how the error happened? I tested to run app in dev mode but I cant get anything from log.. Perhaps we need some more clear error message in this case? Thank you.

**Comment by leo220yuyaodog** [comment]
@dev-techmoe I'm can not repoduce your bug. But I improve the error message in https://github.com/casdoor/casdoor/pull/1584 .
Please try it to see what error caused the problem of your application.

**Comment by dev-techmoe** [comment]
thank you @leo220yuyaodog, I had figured out what cause this problem in this afternoon, my SAML SP (a caddy server with caddy-security plugin) seems cant send correct SAMLRequest to casdoor, it's my problem and I'm try to debug my caddy server, thank you for your PR :)
