### ISSUE TITLE
accept-language header with '*' will cause error

### ISSUE THREAD

**Issue by lookis** [casdoor/casdoor#1585]
```
Handler crashed with error runtime error: slice bounds out of range [:2] with length 1
```
https://github.com/casdoor/casdoor/blob/412a8b5da7c82c0299c931a0b5730d4f99700db4/conf/conf.go#L109

this line should be 
```go
if language == "" || language == "*" {
```

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/910816c7a32d3e8e4ae6ba4b4c0e2d932284e246
