### ISSUE TITLE
Login and registration POPUP

### ISSUE THREAD

**Issue by eveneme** [casdoor/casdoor#1589]
Hi login and register best option in popup window

**Comment by leo220yuyaodog** [comment]
> popup window

Do you mean the login and register position in the window? 
![image](https://user-images.githubusercontent.com/71440988/221465641-016fe999-f0ab-42d5-aed3-996ce18b3b61.png)

What is your expected function? Can you tell me more details?

**Comment by eveneme** [comment]
yes, popup window center website
