### ISSUE TITLE
OAuth 2 access token generated in client-credentials pattern cannot be intropected

### ISSUE THREAD

**Issue by deljuven** [casdoor/casdoor#1594]
It seems that access token comes from client-credential mode can not be parsed correctly

**Comment by hsluoyz** [comment]
@deljuven can you give more details?

**Comment by deljuven** [comment]
@hsluoyz 
I call oauth/token with grant_type set as client-credentials, and then intropect API returns some error message showed application not found.
I tried to reproduce the scenario using demo.casdoor.com, but find introspect API failed today. The only thing I can get is
```
{
    "active": false
}
```

**Comment by deljuven** [comment]
Sorry, I think I made some mistake. The API accepts form data only, but I pass the token with json payload.

**Comment by deljuven** [comment]
When I tried to use access token created via client-credentails mode, there is the following error.
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/836399/223133581-1f23525d-6e91-4f29-bde2-5db01888bb6d.png">

**Comment by hsluoyz** [comment]
@deljuven can you make a PR to fix it?

**Comment by deljuven** [comment]
For client-credential mode, username in token is generated with "app/" prefix by default.
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/836399/224220266-28e55338-fcbc-4cec-b5ff-af51cfdcf9d0.png">
