### ISSUE TITLE
Captcha does not work when I try to login

### ISSUE THREAD

**Issue by yaotthaha** [casdoor/casdoor#1610]
Cloudflare captcha, works in provider edit page's preview, but doesn't show up in login page.

https://user-images.githubusercontent.com/95022881/222611265-b5905952-d76a-4971-a1e7-fab765a0bc25.mp4

https://user-images.githubusercontent.com/95022881/222611288-ca013d2e-92f0-4e89-af06-f2efb321cf39.mp4

**Comment by akp660** [comment]
I want to work on this issue

**Comment by leo220yuyaodog** [comment]
@yaotthaha Set the rule always. THe chaptcha will work in login.

![image](https://user-images.githubusercontent.com/71440988/222869874-3d885f33-ed3f-46db-90a1-1dcec0f351c6.png)

**Comment by yaotthaha** [comment]
> @yaotthaha Set the rule always. THe chaptcha will work in login.
> 
> ![image](https://user-images.githubusercontent.com/71440988/222869874-3d885f33-ed3f-46db-90a1-1dcec0f351c6.png)

![IMG_20230304_100436](https://user-images.githubusercontent.com/95022881/222870053-02aa96a0-2aef-4c34-b5a7-e48061337e9f.jpg)

Yes, I have set it to "Always". But it does not work.

**Comment by leo220yuyaodog** [comment]
> > @yaotthaha Set the rule always. THe chaptcha will work in login.
> > ![image](https://user-images.githubusercontent.com/71440988/222869874-3d885f33-ed3f-46db-90a1-1dcec0f351c6.png)
> 
> Yes, I have set it to "Always". But it does not work.

Oh, I check the source code. I find now only the "default" type captcha will work when login. We'll  support all kind of captcha.
https://github.com/casdoor/casdoor/blob/f8bc87eb4e5ba3256424cf14aafe0549f812f1cf/web/src/auth/LoginPage.js#L552-L565

**Comment by yaotthaha** [comment]
🥳

**Comment by leo220yuyaodog** [comment]
@yaotthaha Please review https://github.com/casdoor/casdoor/pull/1619 . You can test the pr to see if cloudflare captcha works.

**Comment by yaotthaha** [comment]
Thank. It works now.
