### ISSUE TITLE
countryCode isn't sent to server and signup error: verification:Phone number is invalid in your region

### ISSUE THREAD

**Issue by zedzhu** [casdoor/casdoor#1612]
I found countryCode isn't sent to server, and causes the error "verification:Phone number is invalid in your region". 
I use the latest branch master which includes the bug fix relates to empty countryCode in release v1.255.1.

![image](https://user-images.githubusercontent.com/6426766/222664141-821d704b-48d4-41f9-9bd6-e936a47ba117.png)
![image](https://user-images.githubusercontent.com/6426766/222664165-c946c237-2386-4bad-b766-8f9bd8bd7b10.png)

**Comment by hsluoyz** [comment]
@zedzhu please add CN (+86) to your organization's `Supported country codes` like: https://door.casdoor.com/organizations/casbin

`Supported country codes` means the allowed country codes to send SMS for users inside this organization.

![image](https://user-images.githubusercontent.com/3787410/222775889-c250f4f7-ee64-4b18-9b21-cba8d7888026.png)

You can also debug this line of code here:

![image](https://user-images.githubusercontent.com/3787410/222776268-4d5a15a0-9ce4-424a-b99b-40c227a8f4e0.png)

**Comment by zedzhu** [comment]
Yes, I noticed that setting and already added my county code to my organization. However, it didn't work. It seems like the browser doesn't set the countryCode value in the request form, you may see the that in the screenshot.
<img width="334" alt="截屏2023-03-05 20 09 02" src="https://user-images.githubusercontent.com/6426766/222959841-bc29df7e-3289-4116-ac18-211f3375cf98.png">
![image](https://user-images.githubusercontent.com/6426766/222960060-0f82501e-56aa-4bfd-aba4-b9d15f54b43c.png)
