### ISSUE TITLE
account_items empty when creating a new org via api

### ISSUE THREAD

**Issue by fischermario** [casdoor/casdoor#1615]
**Error description:**

When trying to create a new organization by calling the /api/add-organization endpoint with the template payload from init_data.json the ui will not show any data on new users created within this organization.

**Steps to reproduce:**

1. Deploy new casdoor container on an empty database.

2. Login:

curl -c /tmp/cookies.txt -d '{"application":"app-built-in","organization":"built-in","username":"admin","password":"123","type":"login"}' http://127.0.0.1:8110/api/login

3. Deploy a new certificate for the soon to be created organization (omitted here as it is not relevant).

4. Create a new organization:

curl -b /tmp/cookies.txt -d '{"owner":"admin","name":"org-my","displayName":"My-Org","websiteUrl":"","favicon":"","passwordType":"bcrypt","passwordSalt":"QWERTY","phonePrefix":"86","defaultAvatar":"","tags":[]}' http://127.0.0.1:8110/api/add-organization

5. Create a new application for the newly created organization (omitted here as it is not relevant).

6. Create a new user within the organization:

curl -b /tmp/cookies.txt -d '{"owner":"org-my","name":"admin-my","type":"normal-user","password":"test123","displayName":"My-Admin","avatar":"","email":"test@test.com","phone":"","address":[],"affiliation":"","tag":"","isAdmin":true,"isGlobalAdmin":false,"isForbidden":false,"isDeleted":false,"signupApplication":"app-my","createdIp":""}' http://127.0.0.1:8110/api/add-user

7. Try to display the user's details in the ui and get the following:

![error_github](https://user-images.githubusercontent.com/10214295/222697387-c9e16367-9917-4285-a26d-17faec32ae83.png)

**Root cause:**

When calling the /api/add-organization endpoint with the template payload from init_data.json the field 'account_items' of the 'organization' table will be populated with a null value. This leads to the effect above. To avoid this error it would be wise to set a default value for this field.

**Comment by hsluoyz** [comment]
@fischermario hi, can you make a PR to fix it?

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/46f090361e00f1821085e368b723a0c5f2fe2d93
