### ISSUE TITLE
Cannot create Policies -  connection refused

### ISSUE THREAD

**Issue by makorne** [casdoor/casdoor#1622]
Hi

I try to create an adapter with domains:  [ by instruction](https://user-images.githubusercontent.com/101162387/192485366-a3d6c7a2-2027-4415-ad32-fcb5fa015d3c.png)

Copied casbin db to casbin_domains:

![Casdoor_Domains_Screenshot_2023-03-06_11-53-26](https://user-images.githubusercontent.com/26540498/223030689-7be53076-1ebb-41c2-8a72-5719e96095c7.png)

Successfully created model model_domains

Successfully created model adapter_domain:

![Adapter_domains_Screenshot_2023-03-06_12-21-17](https://user-images.githubusercontent.com/26540498/223030727-c1b4f16d-f415-444c-a48c-13b8b5f631ca.png)

**So, the mysql connect is working.**

But I cannot create Policies - after clicking **Save**:

Failed to add: dial tcp [::1]:3306: connect: connection refused

![Error_Casbin_Screenshot_2023-03-06_12-23-56](https://user-images.githubusercontent.com/26540498/223032271-3b005167-e077-4509-a3a1-624f9fe2056d.png)

Why???

**Comment by hsluoyz** [comment]
@makorne make sure you have a running MySQL DB at: 
![image](https://user-images.githubusercontent.com/3787410/223321968-ab89ecd2-7599-4101-9cf3-062ef6b71727.png)

and Casdoor Go backend can access it.

**Comment by makorne** [comment]
> @makorne make sure you have a running MySQL DB at: ![image](https://user-images.githubusercontent.com/3787410/223321968-ab89ecd2-7599-4101-9cf3-062ef6b71727.png)
> 
> and Casdoor Go backend can access it.

I wrote: **So, the mysql connect is working.**  and showed this screenshot before:
![Adapter_domains_Screenshot_2023-03-06_12-21-17](https://user-images.githubusercontent.com/26540498/223325211-4299850b-d738-4cd9-8231-2bdb0f415b35.png)

How are just done: "Successfully created model model_domains" and  "Successfully created model adapter_domain:"  if there no connect to db???

**Comment by hsluoyz** [comment]
The database used by Casdoor: https://casdoor.org/docs/basic/server-installation#configure-database and the database specified in an adapter is NOT the same thing. You may specify them inside the same MySQL instance but they are not the same thing.

But they both use XORM to access the DB. The error message shows that XORM cannot access to localhost:3306 with root. You need to re-check it

**Comment by makorne** [comment]
> specified in an adapter (aka used by Casbin) is NOT the same thing. You may specify them inside the same MySQL instance but they are not the same thing.

But  nothing written  about different databases by this link. 
Only about one database.

In my conf:

driverName = mysql
dataSourceName = root:123456@tcp(localhost:3306)/
dbName = casbin_domains

Why it can modify  model_domains and adapter_domain but not  Policies?

It seems easier to change  policies in db  directly.
Do I need to change casbin_rule table only?
