### ISSUE TITLE
Dingtalk login report logging error

### ISSUE THREAD

**Issue by chickx** [casdoor/casdoor#1629]
in demo ， i use dingtalk to logging
but dingtalk report failed to logging
![微信图片_20230308151411](https://user-images.githubusercontent.com/2011679/223646245-9e7fee73-99bd-484a-9e80-f2b78f691d01.png)
i find the link in demo create dingtalk logging like this
https://login.dingtalk.com/oauth2/auth?client_id=dingppxf28rvbt3zcqcr&redirect_uri=https://door.casdoor.com/callback&scope=openid&response_type=code&state=JmFwcGxpY2F0aW9uPWFwcC1idWlsdC1pbiZwcm92aWRlcj1wcm92aWRlcl9jYXNkb29yX2Rpbmd0YWxrJm1ldGhvZD1zaWdudXA=
need add "&prompt=consent" to make the link like this
https://login.dingtalk.com/oauth2/auth?client_id=dingppxf28rvbt3zcqcr&redirect_uri=https://door.casdoor.com/callback&scope=openid&response_type=code&state=JmFwcGxpY2F0aW9uPWFwcC1idWlsdC1pbiZwcm92aWRlcj1wcm92aWRlcl9jYXNkb29yX2Rpbmd0YWxrJm1ldGhvZD1zaWdudXA=&prompt=consent
to make sure i can use dingtalk logging

**Comment by hsluoyz** [comment]
@chickx fixed by: https://github.com/casdoor/casdoor/commit/71db1f62a96ae351ca8d7836fea4a0cd056e59af
