### ISSUE TITLE
[Feature request] Dingtalk support connecting `casdoor` users by organization email

### ISSUE THREAD

**Issue by anyidea** [casdoor/casdoor#1634]
As many users don't set their personal email on dingtalk app, we cannot get email info from api `/v1.0/contact/users/{unionId}`([docs](https://open.dingtalk.com/document/orgapp/dingtalk-retrieve-user-information)). Often the case is that organize managers set their staff email on the dingtalk management platform which leads to that we must call another api: `/topapi/v2/user/get`([docs](https://open.dingtalk.com/document/orgapp-server/query-user-details)) to fetch email.
  

Is there a chance that we connect `dingtalk` users with `casdoor` users through mobile phone?

**Comment by hsluoyz** [comment]
@anyidea please join the QQ group
