### ISSUE TITLE
[refactor] change all `c.Data["json"] =` to `responseOk()` in Go backend

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#1641]
![image](https://user-images.githubusercontent.com/3787410/224469288-9f03db70-ee9f-4704-a107-4ffe45546519.png)

**Comment by hsluoyz** [comment]
@thanhtinhpas1 hi, can you also work on this as the next step of: https://github.com/casdoor/casdoor/pull/1993 ?

**Comment by thanhtinhpas1** [comment]
> @thanhtinhpas1 hi, can you also work on this as the next step of: https://github.com/casdoor/casdoor/pull/1993 ?

Sure, I'm just busy yesterday, will start tomorrow.
