### ISSUE TITLE
How to set up casdoor to use in flarum

### ISSUE THREAD

**Issue by gitzaai** [casdoor/casdoor#1642]
How to set up casdoor to use in flarum: https://github.com/flarum/flarum

Requirements: I currently have Wordpress and 2 flarums, and I want to log in to other sites with an account through casdoor.

The current problem is that flarum cannot obtain the user information of casdoor

Flarum uses the extension of fof/passport   (The OAuth2 (and Laravel passport) compatible oauth extension): https://github.com/FriendsOfFlarum/passport

### The fof/passport settings:

[![FOF1_2023-03-11_15-12-31.png](https://cdnjson.com/images/2023/03/11/FOF1_2023-03-11_15-12-31.png)](https://cdnjson.com/image/fMGK1)

### fof/passport doc

[![Snipaste_2023-03-11_14-53-06.png](https://cdnjson.com/images/2023/03/11/Snipaste_2023-03-11_14-53-06.png)](https://cdnjson.com/image/fMRek)

### organization

![organization_2023-03-11_15-05-27.png](https://cdnjson.com/images/2023/03/11/organization_2023-03-11_15-05-27.png)

### application1

[![application1_2023-03-11_15-07-08.png](https://cdnjson.com/images/2023/03/11/application1_2023-03-11_15-07-08.png)](https://cdnjson.com/image/fM13G)

### application2

![application2_2023-03-11_15-07-27.png](https://cdnjson.com/images/2023/03/11/application2_2023-03-11_15-07-27.png)

### application3

![application3_2023-03-11_15-08-01.png](https://cdnjson.com/images/2023/03/11/application3_2023-03-11_15-08-01.png)

### application4

![application4_2023-03-11_15-08-19.png](https://cdnjson.com/images/2023/03/11/application4_2023-03-11_15-08-19.png)

### providers1

![providers1_2023-03-11_15-08-50.png](https://cdnjson.com/images/2023/03/11/providers1_2023-03-11_15-08-50.png)

### Result

![Snipaste_2023-03-08_19-47-32.png](https://cdnjson.com/images/2023/03/11/Snipaste_2023-03-08_19-47-32.png)

**Comment by hsluoyz** [comment]
@gitzaai fixed in: https://github.com/casdoor/casdoor/commit/989fec72bfec5268bb9f667c27c4bae5cd86a2db

Update your Casdoor code to use that commit, and "Api URL" should use `xxx/api/user` like:

![image](https://user-images.githubusercontent.com/3787410/227280406-ae02f89b-2dc6-4c8d-abb6-5104b0b56ac1.png)
