### ISSUE TITLE
Add Application Login Option: Auto Redirect.

### ISSUE THREAD

**Issue by Jonathan523** [casdoor/casdoor#1644]
Auto redirect to idp when there is only one set and no other login method is enabled.

**Comment by hsluoyz** [comment]
@Jonathan523 this is already supported: enable `Auto signin` in application edit page: https://door.casdoor.com/applications/casbin/app-casbin-oa

![image](https://user-images.githubusercontent.com/3787410/224552390-91fc9f54-159c-4d66-b8a2-447ad856c20e.png)

**Comment by Jonathan523** [comment]
What I'm saying is that when password login is disabled and there is only one OAuth provider, any user attempting to log in should be redirected directly to the OAuth provider for authentication instead of automatically logging in when they have already logged into Casdoor.

**Comment by Jonathan523** [comment]
Anyone who can solve this?

**Comment by hsluoyz** [comment]
@Jonathan523 @fischermario fixed by: https://github.com/casdoor/casdoor/commit/0d12972e9280cf5b4ef8d8e93b7de9452c9d04ac
