### ISSUE TITLE
Potential performance issues

### ISSUE THREAD

**Issue by chenjpu** [casdoor/casdoor#1649]
https://github.com/casdoor/casdoor/blob/2cca1c91364d38662d525552a7d2d31bf09f8801/controllers/auth.go#L454

```
object.GetUsers(application.Organization)
```

The project has 100w users, Do we need to query all ?

**Comment by hsluoyz** [comment]
@chenjpu hi, your question is very variable and we will have a fix for it. However, you should not use that title `Stinky Code`. It's offensive. Can you change that?

**Comment by chenjpu** [comment]
Thanks for having such a good open source project, we are currently evaluating it on the project
