### ISSUE TITLE
Health check http path? 

### ISSUE THREAD

**Issue by chenjpu** [casdoor/casdoor#1654]
Is there a monitoring check path that does not generate the cookie?
Discovery Access static resources also generates cookie information on the server.

**Comment by chenjpu** [comment]
server-side callback cas api ```/p3/serviceValidate``` will also generates  useless cookie information

**Comment by hsluoyz** [comment]
@chenjpu why doesn't want cookie?

**Comment by chenjpu** [comment]
Health checks are all server access, do not need this kind of information, regular checks will produce different cookie.

**Comment by hsluoyz** [comment]
@chenjpu you are totally right. But the beego frameworks enables cookie for APIs by default. And we don't have time to pick out which APIs don't need cookie. We will not contribute time on this. If you are willing to make a PR, it's welcome.
