### ISSUE TITLE
userinfo() return data but "please login first" ?

### ISSUE THREAD

**Issue by Rebellioncry** [casdoor/casdoor#1657]
{
    "status": "error",
    "msg": "Please login first",
    "sub": "",
    "name": "",
    "data": "Please login firs\r\nt",
    "data2": null
}
I use https://github.com/zitadel/oidc to do that

**Comment by Rebellioncry** [comment]
I solve this problem

**Comment by hsluoyz** [comment]
@Rebellioncry how did you resolve this issue?
