### ISSUE TITLE
How to use Casdoor with NGINX with custom location? 

### ISSUE THREAD

**Issue by jdjingdian** [casdoor/casdoor#1659]
I have my nginx conf like this, but I cant get Casdoor to work

```
location / {
			rewrite static https://mydomain:8443/uac/static/ redirect;
		    try_files $uri $uri/ =404;
	    }

location /uac/ {
			proxy_redirect off;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header REMOTE-HOST $remote_addr;
			proxy_pass http://192.168.4.31:8080/;
			
	    }

```

I would like to access Casdoor with https://mydomain:8443/uac ，how should I setup my nginx conf?

**Comment by hsluoyz** [comment]
@jdjingdian Casdoor must be deployed at root: https://mydomain:8443

**Comment by javyxu** [comment]
> 
hello, Have you solved this problem?

**Comment by hsluoyz** [comment]
@BBM-Freehub yes, any domain would work. HTTPS would be better. Sub path is not supported
