### ISSUE TITLE
Azure AD support custom request address

### ISSUE THREAD

**Issue by ainuoyan** [casdoor/casdoor#1661]
When using Azure ad, if the application is registered in single-tenant mode, sso login will not be successful. The error message is https://xxx.com/callback?error=invalid_request&error_description=AADSTS50194. The application 'e61**********847' (Casdoor) is not configured as a multi-tenant application. The use of /common endpoints is not supported for such applications created after '10/15/2018'. Use a specific tenant endpoint or configure the application as multi-tenant.

![image](https://user-images.githubusercontent.com/14355237/225349000-a1a2e58b-f47d-48b5-8c8f-6e62c31d3ffb.png)

https://learn.microsoft.com/en-us/answers/questions/960066/aad-returned-an-error-response-case-usage-of-the-c

**Comment by nomeguy** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/76eb60633583acb068b9fd4890628a19a09ec9aa
