### ISSUE TITLE
[casbin/casdoor:v1.272.0] embed swagger not found(404)

### ISSUE THREAD

**Issue by lzw5399** [casdoor/casdoor#1664]
# Problem
When I using the latest version(v1.272.0) docker image in docker hub, the embed swagger return 404

![image](https://user-images.githubusercontent.com/45249999/225804326-0eb2a07f-3aac-4c1e-935b-64ab590805ca.png)

# Reproduce step
1. docker run
```shell
docker run \
  -d \
  -e driverName=mysql \
  -e dataSourceName="$CASDOOR_DB_ADDR" \
  -e dbName='casdoor' \
  -p 8000:8000 \
  casbin/casdoor:v1.272.0
```
2. visit `http://localhost:8000/swagger`

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casdoor/casdoor/releases/tag/v1.273.0
