### ISSUE TITLE
Apache HTTP Server Malformed Range and Range-Request Option Handling Remote Denial of Service Vulnerability

### ISSUE THREAD

**Issue by chjuashduq** [casdoor/casdoor#1671]
Hello, security vulnerabilities were detected in the deployment of Casdoor, but I cannot find any usage of Apache. Could you please advise me on how to upgrade to fix the vulnerability?
![image](https://user-images.githubusercontent.com/82489770/226275989-38dc1204-52f4-4c3b-bd0c-23c6c99f8a32.png)

**Comment by hsluoyz** [comment]
@chjuashduq hi, Casdoor doesn't use Apache HTTP server anywhere in the code (it's open source so you can check it by yourself). So it doesn't make sense for Casdoor to have such problem.

Can you share which software or service provided this security report?

**Comment by chjuashduq** [comment]
是否是casdoor引用的第三方服务中，引用了Apache Http

> @chjuashduq你好，Casdoor 没有在代码中的任何地方使用 Apache HTTP 服务器（它是开源的，所以你可以自己检查）。所以 Casdoor 有这样的问题是没有意义的。
> 
> 您能否分享提供此安全报告的软件或服务？

**Comment by chjuashduq** [comment]
> @chjuashduq hi, Casdoor doesn't use Apache HTTP server anywhere in the code (it's open source so you can check it by yourself). So it doesn't make sense for Casdoor to have such problem.
> 
> Can you share which software or service provided this security report?

Is Apache Http referenced by a dependency in any third-party services referenced by Casdoor?

**Comment by hsluoyz** [comment]
@chjuashduq

1. please use English in this community, and modify all your existing texts into English, otherwise this issue may be closed.
2. Also don't post the same issue for twice.

Apache HTTP server is a standalone service developed by C language. Casdoor is a pure Go program, which only imports Go libraries. Casdoor has nothing to do with Apache HTTP server.

**Comment by chjuashduq** [comment]
> @chjuashduq
> 
> 1. please use English in this community, and modify all your existing texts into English, otherwise this issue may be closed.
> 2. Also don't post the same issue for twice.
> 
> Apache HTTP server is a standalone service developed by C language. Casdoor is a pure Go program, which only imports Go libraries. Casdoor has nothing to do with Apache HTTP server.
> 
> If someone has used Apache HTTP server in their deployment (like using as a reverse proxy) and introduced any problems, this is their own issue, not Casdoor's. Please find those people who deployed the services.

Okay. I'm very sorry. This is my first time using the issue function. I'll pay attention in the future. May I ask what web service container Casdoor uses?
