### ISSUE TITLE
webauthn package "go:build comment without // +build comment" error on CentOS-8.5.2 and go 1.16

### ISSUE THREAD

**Issue by G-lin** [casdoor/casdoor#1678]
#  go run main.go
get error: "/root/go/pkg/mod/github.com/go-webauthn/webauthn@v0.8.2/metadata/metadata.go:15:2: //go:build comment without // +build comment"

**Comment by hsluoyz** [comment]
@G-lin provide:

1. your OS version (like Ubuntu 18.04 x64 or Windows 11 x86)
2. Go version (like Go 12.1)
3. Casdoor version (like v1.2.3)

**Comment by G-lin** [comment]
OS version ： CentOS-8.5.2
go version : go1.16.12
Casdoor version : v1.276.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月22日(星期三) 晚上9:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [casdoor/casdoor] run error！ (Issue #1678)






@葛琳提供：

您的操作系统版本（如Ubuntu 18.04 x64或Windows 11 x86）

围棋版本（如围棋12.1）

Casdoor版本（如v1.2.3版）

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by longxu0509** [comment]
Upgrade to go 1.17 should fix it，If version is lower than 1.17 – need to to update golang on new version for fix it.

**Comment by hsluoyz** [comment]
Closed as resolved

**Comment by hsluoyz** [comment]
@G-lin why doesn't Go 1.20 work? What error?

**Comment by G-lin** [comment]
error ：“github.com/go-webauthn/webauthn/metadata: build constraints exclude all Go files in ***@***.***/metadata”



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月25日(星期六) 上午9:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [casdoor/casdoor] webauthn package &quot;go:build comment without // +build comment&quot; error on CentOS-8.5.2 and go 1.16 (Issue #1678)





 
@G-lin why doesn't Go 1.20 work? What error?

**Comment by longxu0509** [comment]
@G-lin I tested it with go1.20.2 but it doesn't seem to have this problem.
![~8__ W_NLM_E_9F4L6EN (O](https://user-images.githubusercontent.com/108991596/227755907-5d502900-cf93-498e-ae8c-f1ee02408261.png)

**Comment by G-lin** [comment]
Now it's working. It might be due to my incorrect configuration of the Go language environment. Sorry about that!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月26日(星期天) 中午12:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [casdoor/casdoor] webauthn package &quot;go:build comment without // +build comment&quot; error on CentOS-8.5.2 and go 1.16 (Issue #1678)





 
@G-lin I tested it with go1.20.2 but it doesn't seem to have this problem.
