### ISSUE TITLE
[Question] can user customize the built-in OAuth provider icon (e.g. Github, Wechat)

### ISSUE THREAD

**Issue by lzw5399** [casdoor/casdoor#1679]
Hi Casdoor team:

Is there any way to customize the following built-in provider icon, or can only use "custom" type OAuth provider 

![image](https://user-images.githubusercontent.com/45249999/227139674-ad5d2ca8-a891-44c1-8363-8a24702217b2.png)

Thank you for your job!

**Comment by hsluoyz** [comment]
@lzw5399 why do you want to customize that?

**Comment by lzw5399** [comment]
It seems not a common scenario for Casdoor. I'll close the issue
