### ISSUE TITLE
[docs] Issue about connecting to Grafana via Casdoor SSO like Role Mapping

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#1684]
There are problems with the documentation for integrating Grafana. https://casdoor.org/docs/integration/go/grafana Following the documentation does not configure successfully, and many additional configurations need to be added, which can be found in the Grafana official documentation.

After integration, the role cannot be mapped.

role_attribute_path

/etc/grafana/grafana.ini

```ini
[auth.generic_oauth]
role_attribute_path = contains(roles[], 'admin') && 'Admin' || contains(roles[], 'editor') && 'Editor' || 'Viewer'
```

https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/#role-mapping

https://github.com/grafana/grafana/blob/main/conf/defaults.ini#L662

**Comment by dfang** [comment]
@hsluoyz 

the JMESPath expression should be like this

```
role_attribute_path = contains(roles[*].name, 'admin') && 'Admin' || contains(roles[*].name, 'editor') && 'Editor' || 'Viewer'
```

i've created a [PR](https://github.com/casdoor/casdoor-website/pull/447/files) in casdoor/casdoor-website.

i think this issue can be closed.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor-website/pull/447
