### ISSUE TITLE
Swagger api  /api/get-system-info

### ISSUE THREAD

**Issue by dfang** [casdoor/casdoor#1685]
<img width="1414" alt="Screen Shot 2023-03-26 at 09 28 23" src="https://user-images.githubusercontent.com/1277047/227750326-de5bddfc-08bc-4ab4-92d3-8f553c79f9e9.png">
why id param is required in [/api/get-system-info in Swagger](https://door.casdoor.com/swagger/#/System%20API/ApiController.GetSystemInfo) ?  

in [sysinfo page](https://door.casdoor.com/sysinfo)
<img width="1413" alt="Screen Shot 2023-03-26 at 09 33 17" src="https://user-images.githubusercontent.com/1277047/227750443-9cf3be07-af79-43ad-8df9-4a7042aae9d7.png">

**Comment by hsluoyz** [comment]
@dfang `id` is not required any more, however this API still requires login like other APIs. Swagger docs has been updated: https://github.com/casdoor/casdoor/commit/32b05047dcc20a94b0798b18afa2d4c4dff7018c

**Comment by dfang** [comment]
nice!
