### ISSUE TITLE
Azure AD single-tenant mode work error

### ISSUE THREAD

**Issue by ainuoyan** [casdoor/casdoor#1687]
When using Azure ad, if the application is registered in single-tenant mode, casdoor does not work properly.

After changing the "common" in line 106 of  idp/goth.go  to the tenant id or domain name, it works perfectly.

![PYR2AH_L@1LV)%0)~N19HFR](https://user-images.githubusercontent.com/14355237/227762024-f89fe8a7-c2de-4913-97ec-af34a7090092.png)

**Comment by nomeguy** [comment]
fixed by: https://github.com/casdoor/casdoor/commit/8eb68ba817dff8eb268cc884c78a384cbf0e3ce5
