### ISSUE TITLE
How to configure WeChat payment

### ISSUE THREAD

**Issue by monyuan** [casdoor/casdoor#1695]
Casdoor can add payment providers, which will be used to add payment methods to products on the product page. Currently, the supported payment providers include Alipay, WeChat Pay, PayPal and GC.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/56907515/228110257-5679b261-7cb9-402b-9f65-88c3b2eac83e.png">

**Comment by hsluoyz** [comment]
@monyuan see: https://casdoor.org/docs/provider/payment/WeChatPay

**Comment by wevsmy** [comment]
@hsluoyz Hello, there is no provider of wechatpay in the source code?

**Comment by hsluoyz** [comment]
@wevsmy the code will be coming soon
