### ISSUE TITLE
Sign in after password reset gives error "Login failed: Please log out first"

### ISSUE THREAD

**Issue by wsolara** [casdoor/casdoor#1703]
Hello! I use Casdoor v1.281.0

I created my own organization and application. And signed up the user in the application.

How do I get the error:

1. Go to login page
2. Click "Forgot password"
3. Enter email (or username)
4. Send code to email
5. Enter code from email
6. Reset password (enter password and confirm password)
7. After that, we were again redirected to the login page. What well..
8. Enter username, and password or other mfa
9. Getting error -"Login failed: Please log out first"

![photo_2023-03-31_19-45-54 (2)](https://user-images.githubusercontent.com/69395209/229453254-990a65fc-b3a8-4baa-ab41-26940b27e9b6.jpg)

10. Reloading the page redirects to home page

How can I fix it manually? Or this global error? Thank you.

**Comment by hsluoyz** [comment]
@wsolara hi, can you record a video to reproduce the bug and paste it here?

**Comment by singh1475** [comment]
This message indicates the user is still active on the server to fix this clear the user's session cookies:

**Comment by leo220yuyaodog** [comment]
@wsolara  You can just refresh the broswer to login. It it a bug caused by redirecting to incorrect url.

**Comment by wsolara** [comment]
> @wsolara hi, can you record a video to reproduce the bug and paste it here?

[leo220yuyaodog](https://github.com/leo220yuyaodog) hello, can I change this url somewhere?
