### ISSUE TITLE
Advice,It's time to change Casdoor's version release

### ISSUE THREAD

**Issue by Nash-x9** [casdoor/casdoor#1704]
First of all, thanks to all Casdoor members for their support of open source
I think the current distribution is in need of a change
Currently, a commit or a set of feature updates triggers a release, which results in a lot of releases, which is very unfavorable to management and user use.
I suggest distinguishing between production, development and Nightly releases.

**Comment by hsluoyz** [comment]
It follows the workflow of semantic-release and we don't have plan to change to another release model recently.
