### ISSUE TITLE
WebAuthn gives error: "Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded."

### ISSUE THREAD

**Issue by wsolara** [casdoor/casdoor#1706]
Hello! I have the error when logging in with Webauthn or when adding a WebAuthn device.

Casdoor Version: [v1.281.0](https://github.com/casdoor/casdoor/releases/tag/v1.281.0)

Browser Google Chrome Version: 111.0.5563.146

How to reproduce:

1. Go to login page
2. Select WebAuthn
3. Enter username
4. Click Sign in button
5. Getting error in browser console: 
`Uncaught (in promise) DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at rO (https://casdoor.vitim.io/static/js/main.a301da6f.js:2:3740754)
    at https://casdoor.vitim.io/static/js/main.a301da6f.js:2:3909520`
6. Step 4 and 5 can be repeated many times

Or another scenario:

1. Go to user profile
2. Click Add webauthn device button
3. Getting error notification: "Failed to connect to server: InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.."

Recording how to reproduce it:
[out_webauthn.webm](https://user-images.githubusercontent.com/69395209/229780732-3a086f65-fc39-4582-ad2b-1dc9294e30bb.webm)

**Comment by hsluoyz** [comment]
@wsolara hi, can you check starting from which release version this problem happens?

**Comment by wsolara** [comment]
[hsluoyz](https://github.com/hsluoyz), ok, I'll try

**Comment by wsolara** [comment]
> @wsolara hi, can you check starting from which release version this problem happens?

[hsluoyz](https://github.com/hsluoyz) Hello, I checked, in versions 1.260.0, 1.261.0 there is no such error, starting from version 1.262.0 there is an error

**Comment by hsluoyz** [comment]
@wsolara are you sure that this PR: https://github.com/casdoor/casdoor/pull/1623 has caused this issue? I don't think that one line change has anything to do with WebAuthn..

**Comment by hsluoyz** [comment]
ping @wsolara

**Comment by wsolara** [comment]
> @wsolara are you sure that this PR: #1623 has caused this issue? I don't think that one line change has anything to do with WebAuthn..

[hsluoyz](https://github.com/hsluoyz) I can see from the commits that the webauthn library was changed here - https://github.com/casdoor/casdoor/compare/v1.261.0...v1.262.0

**Comment by hsluoyz** [comment]
@wsolara yes, good catch. We updated the webauthn library at that time and perhaps this action introduced this bug.

The original commit is: https://github.com/duo-labs/webauthn/commit/a22482edaa3b

It is changed to: https://github.com/go-webauthn/webauthn/releases/tag/v0.8.2

Actually `go-webauthn/webauthn` is forked from `duo-labs/webauthn`. So can you check starting from which commit of `go-webauthn/webauthn` repo this issue happens? You can use binary-search. This will help us locate the problem.

**Comment by wsolara** [comment]
> @wsolara yes, good catch. We updated the webauthn library at that time and perhaps this action introduced this bug.
> 
> The original commit is: [duo-labs/webauthn@a22482edaa3b](https://github.com/duo-labs/webauthn/commit/a22482edaa3b)
> 
> It is changed to: https://github.com/go-webauthn/webauthn/releases/tag/v0.8.2
> 
> Actually `go-webauthn/webauthn` is forked from `duo-labs/webauthn`. So can you check starting from which commit of `go-webauthn/webauthn` repo this issue happens? You can use binary-search. This will help us locate the problem.

ok

**Comment by XDTD** [comment]
> > @wsolara yes, good catch. We updated the webauthn library at that time and perhaps this action introduced this bug.
> > The original commit is: [duo-labs/webauthn@a22482edaa3b](https://github.com/duo-labs/webauthn/commit/a22482edaa3b)
> > It is changed to: https://github.com/go-webauthn/webauthn/releases/tag/v0.8.2
> > Actually `go-webauthn/webauthn` is forked from `duo-labs/webauthn`. So can you check starting from which commit of `go-webauthn/webauthn` repo this issue happens? You can use binary-search. This will help us locate the problem.
> 
> Ok, I will try

I have tried using different versions of webauthn, and it seems that versions from [this commit](https:github.com/go-webauthn/webauthn/commit/6abd3517301412ba1f6a25c0d88ce59b22a463c6) onwards can trigger this bug. To address this bug， you can specify the version of webauthn as v0.5.0 or an earlier in the go.mod file of casdoor. I will continue to investigate what has caused this problem.
