### ISSUE TITLE
Bug in WeCom provider

### ISSUE THREAD

**Issue by scrollsyou** [casdoor/casdoor#1707]
https://github.com/casdoor/casdoor/blob/a8937d3046a934af991c442794a6f16b8428fe16/web/src/ProviderEditPage.js#L355

There is an issue with this line of code when getting the value. Should it be changed to `value={method.id}` to make the i18n other than English work correctly?

**Comment by hsluoyz** [comment]
@scrollsyou hi, please use English, and can you make a PR to fix it?

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/4ad21e7781109374bcede06be175b50255cbb998
