### ISSUE TITLE
[Question] How to add multiple audience

### ISSUE THREAD

**Issue by shiningstarts** [casdoor/casdoor#1708]
I want to add multiple audiences, it does no supporte.
```go
claims := Claims{
		User:      user,
		TokenType: "access-token",
		Nonce:     nonce,
		// FIXME: A workaround for custom claim by reusing `tag` in user info
		Tag:   user.Tag,
		Scope: scope,
		RegisteredClaims: jwt.RegisteredClaims{
			Issuer:    originBackend,
			Subject:   user.Id,
			Audience:  []string{application.ClientId},
			ExpiresAt: jwt.NewNumericDate(expireTime),
			NotBefore: jwt.NewNumericDate(nowTime),
			IssuedAt:  jwt.NewNumericDate(nowTime),
			ID:        jti,
		},
	}
```

**Comment by shiningstarts** [comment]
> @shiningstarts can you give a reason why you want multiple audiences? Is it something should be supported in the OAuth 2.0 or OIDC standard?

I think multiple applications share a token, user can login only once without redirect.
[JWT](https://www.rfc-editor.org/rfc/rfc7519#section-) can register multiple audiences.

**Comment by hsluoyz** [comment]
@shiningstarts you mean SSO for multiple applications? No. Just changing this JWT format doesn't let your multiple applications "automatically" login. You need the SSO feature here: https://casdoor.org/docs/how-to-connect/single-sign-on

**Comment by shiningstarts** [comment]
> @shiningstarts you mean SSO for multiple applications? No. Just changing this JWT format doesn't let your multiple applications "automatically" login. You need the SSO feature here: https://casdoor.org/docs/how-to-connect/single-sign-on

I use "micro-frontend" to build website, multiple applications share a token.
Use "auto login" will redirect many times, it's not friendly.
<img width="646" alt="image" src="https://user-images.githubusercontent.com/22713311/230535111-2029f994-c2a7-401b-ae9b-45d5ae8f879b.png">

**Comment by cic1988** [comment]
How would Casdoor team suggest if this feature is not available?
