### ISSUE TITLE
what is the id_token_hint of logout api?

### ISSUE THREAD

**Issue by zedzhu** [casdoor/casdoor#1712]
I tried access_token and id_token, both get the error:

{
  "status": "error",
  "msg": "未查询到对应token, accessToken无效",
  "sub": "",
  "name": "",
  "data": null,
  "data2": null
}

**Comment by leo220yuyaodog** [comment]
@zedzhu The accesstoken that the client get from casdoor.

**Comment by zedzhu** [comment]
Thanks a lot, it works now, it's the id_token which is the same as access_token returned from /api/login/oauth/access_token.
