### ISSUE TITLE
Wrong Vietnamese flag

### ISSUE THREAD

**Issue by saosangmo** [casdoor/casdoor#1722]
hi there,
Correct Vietnamese flag is https://cdn.casbin.org/flag-icons/VN.svg.
But now I get this: https://cdn.casbin.org/flag-icons/VI.svg.

thank you!
![Screen-Shot-2023-04-10-at-17 57 53](https://user-images.githubusercontent.com/4606931/230889339-449e8277-fe7f-4c6b-8d91-d193f36bf661.png)

**Comment by hsluoyz** [comment]
@saosangmo sorry for this mistake. Can you make a PR to fix it?

**Comment by hsluoyz** [comment]
@saosangmo no, I think it's our side. "vi" is mistaken for "vn": https://github.com/casdoor/casdoor/search?q=vi&type=

**Comment by saosangmo** [comment]
@hsluoyz I have made PR for this issue. Please review it for me.
Thanks you!
