### ISSUE TITLE
Page shows wrong language

### ISSUE THREAD

**Issue by zedzhu** [casdoor/casdoor#1731]
There is only one language(Chinese) in my organization settings, but it still uses English language at the first page visit.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/6426766/231337768-21fa7d9c-f3bd-4f37-b60b-1417370814c7.png">

<img width="676" alt="image" src="https://user-images.githubusercontent.com/6426766/231337387-c487cdc0-ee0a-47ad-a0f3-ee15d949b51f.png">

**Comment by hsluoyz** [comment]
@zedzhu that setting only controls what options to show in the language box UI. To always use one language, you should modify the `ForceLanguage` value to the language code like `zh` and re-build the frontend project

https://github.com/casdoor/casdoor/blob/14fa914e6f7f9fe045ebb53606e81853f3d8e73b/web/src/Conf.js#L19

**Comment by zedzhu** [comment]
> @zedzhu that setting only controls what options to show in the language box UI. To always use one language, you should modify the `ForceLanguage` value to the language code like `zh` and re-build the frontend project
> 
> https://github.com/casdoor/casdoor/blob/14fa914e6f7f9fe045ebb53606e81853f3d8e73b/web/src/Conf.js#L19

Could this ForceLanguage also be an option in organization settings? I think rebuild the whole frontend for this is a little cost.
