### ISSUE TITLE
Default language control

### ISSUE THREAD

**Issue by zedzhu** [casdoor/casdoor#1732]
@zedzhu that setting only controls what options to show in the language box UI. To always use one language, you should modify the `ForceLanguage` value to the language code like `zh` and re-build the frontend project

https://github.com/casdoor/casdoor/blob/14fa914e6f7f9fe045ebb53606e81853f3d8e73b/web/src/Conf.js#L19

_Originally posted by @hsluoyz in https://github.com/casdoor/casdoor/issues/1731#issuecomment-1504511399_
            
Could this ForceLanguage also be an option in organization settings? I think there are some costs to rebuild the whole frontend for this on every casdoor upgrade.

And BTW, maybe the real need is DefaultLanguage instead of ForceLanguage.

**Comment by hsluoyz** [comment]
@zedzhu not every page has fetched the organization object. Also waiting for fetching AJAX call will generate latency.
