### ISSUE TITLE
Signup by oauth not working

### ISSUE THREAD

**Issue by zedzhu** [casdoor/casdoor#1733]
I followed the documentation https://casdoor.org/docs/basic/core-concepts to access signup by oauth, but it caused an error, however, it's ok if using \<your-casdoor-hostname\>/signup/\<your-application-name\> url.
<img width="970" alt="image" src="https://user-images.githubusercontent.com/6426766/231346873-058716b0-b709-4bcf-a418-522fd9927acc.png">

<img width="537" alt="image" src="https://user-images.githubusercontent.com/6426766/231347149-e1ad73fe-ed5d-45a4-b908-18e945998164.png">

**Comment by hsluoyz** [comment]
@zedzhu enable Signup in application edit page:

![image](https://user-images.githubusercontent.com/3787410/231451294-dfc2ba2e-2cdc-4c89-957e-d4a8999507f3.png)
