### ISSUE TITLE
Bug: Submit error in prompt page 

### ISSUE THREAD

**Issue by zedzhu** [casdoor/casdoor#1735]
There is a submit error in prompt page after signup, Docker image: casbin/casdoor:v1.292.0
<img width="519" alt="image" src="https://user-images.githubusercontent.com/6426766/231397356-68ac564e-2d5a-4ec7-9b3d-c0d5d754d69a.png">

But I already delete the "Display name" item in Signup items:
<img width="1742" alt="image" src="https://user-images.githubusercontent.com/6426766/231397748-272c8be9-07bf-4113-808f-b055a053de00.png">

**Comment by wjsvec** [comment]
May I ask if you can assign it to me?

**Comment by zedzhu** [comment]
> May I ask if you can assign it to me?

Sorry I can't

**Comment by hsluoyz** [comment]
@zedzhu if all signup items don't enable "Prompted", the prompt page will not show up at all. So how did you see it?

![image](https://user-images.githubusercontent.com/3787410/232181375-0e5ac0b6-5d82-4071-abad-c585f3169260.png)
