### ISSUE TITLE
[Bug] model RBAC With Domains/Tenants

### ISSUE THREAD

**Issue by shiningstarts** [casdoor/casdoor#1737]
### Test in Editor
[shared test](https://editor.casbin.org/#EA94QLSTX)
![image](https://user-images.githubusercontent.com/22713311/231664427-5883a724-63bf-4b64-90b1-715b576c8f8f.png)

#### Model
<img width="944" alt="image" src="https://user-images.githubusercontent.com/22713311/231665107-32dbff3a-ab7e-4576-8f93-9109382297ee.png">

#### Role
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/22713311/231664977-12ba0bad-c74a-4fed-9f2e-cfbfb6448684.png">

#### Permission
<img width="847" alt="image" src="https://user-images.githubusercontent.com/22713311/231665637-5266142c-c582-4430-aba0-a6d4a38644b1.png">

```json
{
	"owner": "built-in",
	"name": "permission-domain",
	"createdTime": "2023-04-13T11:15:31+08:00",
	"displayName": "permission-domain",
	"users": [],
	"roles": [
		"built-in/role"
	],
	"domains": [
		"domain"
	],
	"model": "rbac-domain",
	"adapter": "",
	"resourceType": "Application",
	"resources": [
		"resources"
	],
	"actions": [
		"Read"
	],
	"effect": "Allow",
	"isEnabled": true,
	"submitter": "admin",
	"approver": "admin",
	"approveTime": "2023-04-13T11:16:16+08:00",
	"state": "Approved"
}
```
<img width="756" alt="image" src="https://user-images.githubusercontent.com/22713311/231666141-e2a570ac-157b-4971-80fd-6dd526c6e9c1.png">

#### Enforce by Casbin APIs

<img width="797" alt="image" src="https://user-images.githubusercontent.com/22713311/231666434-55987ff0-5916-47be-b6f8-f9538bbf3477.png">

```bash
curl --location 'http://localhost:8000/api/enforce' \
--header 'Authorization: Basic YTdiN2Y2MDNlNzdlMWYyYmZkZmE6OTlhYWE4MjAzNWYxMTY3NTJmODM2MWNiNDg5ZjU3YjdmMzEyZTAxMQ==' \
--header 'Content-Type: application/json' \
--data '{
    "id": "built-in/permission-domain",
    "v0": "built-in/user",
    "v1": "domain",
    "v2":"resources",
    "v3": "read"
}'
```

### Question
The result is puzzling，I think it should be true.
When I modify db like this(swap v1 and v2)，the result is expected. 
<img width="777" alt="image" src="https://user-images.githubusercontent.com/22713311/231667610-922030e0-0b36-4779-af4f-b2511819f493.png">
<img width="663" alt="image" src="https://user-images.githubusercontent.com/22713311/231668306-47fdb799-a360-4597-bf4a-c1abd9abbd13.png">

**Comment by hsluoyz** [comment]
@shiningstarts yes, the g policy order is wrong, fixed by: https://github.com/casdoor/casdoor/commit/78b62c28ab7e29c571e62e4ca242885dbc83e047
