### ISSUE TITLE
Bug:  Organization LDAPs can not sync Windows AD users

### ISSUE THREAD

**Issue by lifehacking** [casdoor/casdoor#1740]
version: 1.283.0

In org page set a ldap config(windows AD), casdoor can read windows AD users  info. but can't sync AD users to casdoor User page, becasue Sync page users checkbox disabled(users info not already synced)

**Comment by leo220yuyaodog** [comment]
@lifehacking Can you provider a screenshot of the user info page. like this:
![image](https://user-images.githubusercontent.com/71440988/232230777-d72204a6-53df-471f-a77c-f4e309d6b3fd.png)

**Comment by lifehacking** [comment]
> @lifehacking Can you provider a screenshot of the user info page. like this: ![image](https://user-images.githubusercontent.com/71440988/232230777-d72204a6-53df-471f-a77c-f4e309d6b3fd.png)

![1](https://user-images.githubusercontent.com/12913767/232661404-130992b7-b890-4ac3-87ef-17892f3b2c4e.png)

**Comment by leo220yuyaodog** [comment]
> > @lifehacking Can you provider a screenshot of the user info page. like this: ![image](https://user-images.githubusercontent.com/71440988/232230777-d72204a6-53df-471f-a77c-f4e309d6b3fd.png)
> 
> ![1](https://user-images.githubusercontent.com/12913767/232661404-130992b7-b890-4ac3-87ef-17892f3b2c4e.png)

Do the users have uid?

**Comment by lifehacking** [comment]
@hsluoyz  User page do not has win AD user info

**Comment by lifehacking** [comment]
@leo220yuyaodog 
![2](https://user-images.githubusercontent.com/12913767/232661772-74bea542-138a-48d6-9e00-f04f2edb8448.png)

**Comment by hsluoyz** [comment]
@lifehacking plz join QQ group for discussion:https://casdoor.org/help

**Comment by hsluoyz** [comment]
Closed as staled
