### ISSUE TITLE
signup/oauth and auto-signup/oauth functions do not work properly?

### ISSUE THREAD

**Issue by zq99299** [casdoor/casdoor#1741]
问题：signup/oauth 和  auto-signup/oauth 功能无法正常使用？
Problem: signup/oauth and auto-signup/oauth functions do not work properly?

----
当前使用的版本号 / The current version number: docker v1.287.0
----

故障描述 / Fault description：
<img width="825" alt="image" src="https://user-images.githubusercontent.com/11927113/231997714-fcb021d9-7722-4df3-b2bc-b4a4de8bd5b1.png">

signup/oauth：

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/11927113/232002634-495fd1bb-60b4-4386-9f97-cb8b454e9482.png">

我使用的地址是：`http:/localhost:8000/signup/oauth/authorize?client_id=d29729e7e1e11f4aba62&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fsso%2Fcallback&scope=read&state=xxx`  本来应该跳转到 `client_id=d29729e7e1e11f4aba62` 对应的应用注册界面，但是跳转到了 casdoor 的注册页面

The address I used is: `http:/localhost:8000/signup/oauth/authorize?client_id=d29729e7e1e11f4aba62&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fsso%2Fcallback&scope=read&state=xxx`  The application registration page corresponding to 'client_id=d29729e7e1e11f4aba62' should be redirected to the casdoor registration page instead

---

auto-signup/oauth ：
<img width="635" alt="image" src="https://user-images.githubusercontent.com/11927113/231999944-59effac8-fd43-4262-ad32-b846b11b29c1.png">

我使用的地址是: `http://localhost:8000/auto-signup/oauth/authorize?client_id=d29729e7e1e11f4aba62&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fsso%2Fcallback&scope=read&&scope=read&state=xxx`  这个地址跳转到了正确的应用，但是只能登录，不能注册

The address I used is: `http://localhost:8000/auto-signup/oauth/authorize?client_id=d29729e7e1e11f4aba62&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fsso%2Fcallback&scope=read&&scope=read&state=xxx`  This address redirects to the correct application, but it can only be logged in, not registered

**Comment by hsluoyz** [comment]
@zq99299 please create issue using English. This one will be deleted.
