### ISSUE TITLE
[question] Issues with CORS on application signup

### ISSUE THREAD

**Issue by jakeeknight** [casdoor/casdoor#1742]
I'm running casdoor using docker and I'm getting cors issues when trying to signup to an application within casdoor.

I'm creating custom signup/login pages instead of the default casdoor ones which will be ran on a different URL than the casdoor instance.

The origin config setting is set in app.conf and I've added my redirect URL to the applications setting which is what the code checks for in the cors_filter function here: https://github.com/casdoor/casdoor/blob/master/routers/cors_filter.go#L32 

Edit: I get no issues if I hit casdoor default endpoints i.e /api/signup, this is when I try sign up a user to an application specifically. e.g http://localhost:8000/signup/APPLICATION_NAME

**Comment by hsluoyz** [comment]
@jakeeknight can you give a way for us to reproduce? including sharing your custom signup/login pages code?

Also can you debug the code here: https://github.com/casdoor/casdoor/blob/master/routers/cors_filter.go#L32 to see the difference between the built-in-app and other apps?

**Comment by jakeeknight** [comment]
> @jakeeknight can you give a way for us to reproduce? including sharing your custom signup/login pages code?
> 
> 
> 
> Also can you debug the code here: https://github.com/casdoor/casdoor/blob/master/routers/cors_filter.go#L32 to see the difference between the built-in-app and other apps?

Hi, sure. It's a simple setup.

The signup/login pages were made in Next.js using the casdoor-js-sdk library running on localhost:3000 and the docker casdoor is running on localhost:8000.

I have checked the cors_filter code and I don't see why the errors occur to me as I've added localhost:3000 to the redirect urls in the application UI.

**Comment by hsluoyz** [comment]
@jakeeknight you have mistaken the frontend URLs as backend APIs.

- Frontend signup URL: [GET] http://localhost:7001/signup/APPLICATION_NAME (docs: https://casdoor.org/docs/basic/core-concepts#login-urls)
- Backend signup API: [POST] http://localhost:8000/api/signup (docs: https://door.casdoor.com/swagger/#/Login%20API/ApiController.Signup)

The backend signup API has a "/api" prefix and it doesn't have the APPLICATION_NAME
