### ISSUE TITLE
is a getEnforcer() bug?

### ISSUE THREAD

**Issue by JK-97** [casdoor/casdoor#1758]
the tablename is not my set on ui
![image](https://user-images.githubusercontent.com/16853338/233016061-ceba2705-e769-435e-80a0-699046fda878.png)
![image](https://user-images.githubusercontent.com/16853338/233016345-16f06d2b-1bbf-4cc4-9350-cd55204759d1.png)

always adapter name

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/e75d26260a07d7499ffde8447c3c4487bc19c002
