### ISSUE TITLE
k8s oidc auth  how to use casdoor

### ISSUE THREAD

**Issue by j0rGeT** [casdoor/casdoor#1765]
I create application in casdoor，add oidc configuration to k8s apiserver. but oidc can not to auth by casdoor application. Can casdoor support oidc in k8s？

**Comment by hsluoyz** [comment]
@j0rGeT Casdoor supports the OIDC standard: https://casdoor.org/docs/how-to-connect/oidc-client . So it should already support all kinds of OIDC configuration including k8s apiserver.

If you find any issues when connecting k8s to Casdoor via OIDC, please provide details to reproduce your issue

**Comment by yehong-z** [comment]
@j0rGeT Hi ! I noticed you posted this issue some time ago. Have you been able to resolve the problem? If not, I'd be happy to try and help out.
