### ISSUE TITLE
[security] support data encryption stored in the database

### ISSUE THREAD

**Issue by lzw5399** [casdoor/casdoor#1778]
Due to the requirements of some security audits / laws, some field(email / phone / uername) stored in plain text in the database may be considered a vulnerability. Can it support encrypted storage, e.g. symmetric encryption (AES)

**Comment by hsluoyz** [comment]
@lzw5399 storing that kind of information is not a vulnerability. If that is, you can find nearly all web systems are containing the so-called "vulnerability". A common sense is that you require extremely high enterprise level (like bank, telecom, etc.) protection, then you need to use Enterprise version. And that is not within the scope of this open source project.
