### ISSUE TITLE
[feature] Ability to modify admin page header 

### ISSUE THREAD

**Issue by MadL1me** [casdoor/casdoor#1780]
Casdoor have a lot of features implemented. Each set of features have its own page and corresponding link. 

But sometimes, you don't need all features that casdoor provides. For example, for me, features like chats, messages, resources, feels irrelevant for IAM.

![image](https://user-images.githubusercontent.com/46647517/233909781-6fbc64fb-ef34-4f82-8c43-ede98b38b162.png)

And in my workflow (I think as in workflow of others) often you'll never use that features, but they will still appear in header. It would be great, if somewhere in casdoor options, you'll be able to turn of/on links to show in header

**Comment by hsluoyz** [comment]
@MadL1me can you make a PR?

**Comment by MadL1me** [comment]
@hsluoyz, yes. I would contribute to this issue, as well as .net sdk, in free time this/next week

**Comment by hsluoyz** [comment]
@MadL1me "chats, messages" has been already moved to Casibase: https://github.com/casibase/casibase

And the existing menu items have been grouped now:

![image](https://github.com/casdoor/casdoor/assets/3787410/dad4d9ea-4c52-4a5a-b33b-6ad2e3587128)
