### ISSUE TITLE
[feature] set organization as context

### ISSUE THREAD

**Issue by MadL1me** [casdoor/casdoor#1781]
As we know, organizations (or in case of keycloak - realm) - is an abstraction for separating multiple tenants into united logical model. 

In Keycloak or Zitadel, only one organization can be selected to be edited at once. This helps a lot, because you'll not make mistake between roles, users and permission of different organization. Currently, is Casdoor, this mechanism is not very comfortable to use.

Usually, when you need to create some roles/users, you'll do that in a single organization at once. For example, you'll create user in ORG1, then some roles in ORG1, then permissions, etc. As well, as when you work with ORG1, you want to see ONLY models, which are using organization ORG1. 

In Casdoor, if you have multiple organizations, the tables are not so informative to use. You almost never need to see all roles/users/permissions for all organizations at once. This can be illustrated with image below: 

![image](https://user-images.githubusercontent.com/46647517/233911705-7c5ed4d7-4ebe-4356-8b91-81066e46d628.png)

So, it would be much more UX to be able to set current organization you are working with. This will help in multiple ways: 
- You can see roles/permissions/users only for selected organization, without the need to set filters every time on every page
- When you create new user/role/permission/etc, organization would be selected automatically

**Comment by hsluoyz** [comment]
@MadL1me this is mostly a frontend issue. Can you make a PR to add it?

**Comment by hsluoyz** [comment]
@ISulimanov no, it should be a drop-down in top-right menu. "All" by default, can also choose org.

**Comment by ISulimanov** [comment]
@MadL1me @hsluoyz  we would like to contribute this feature, because our Casdoor admin really struggle without it

**Comment by hsluoyz** [comment]
@ISulimanov OK, plz provide a demo picture or video
