### ISSUE TITLE
[feature] Ability to enforce with batch of policies

### ISSUE THREAD

**Issue by iPortNe** [casdoor/casdoor#1782]
Like casbin's GetStarted, casdoor should have ability to enforce (sub,obj,act) without assigning a single permission id.
By giving a model name, it should be able to enforce (sub,obj,act) with all permissions in casdoor associated with the same model.

**Comment by hsluoyz** [comment]
@iPortNe what API name should be used? BatchEnforce()? https://casbin.org/docs/data-permissions#2-use-batchenforce

Also can you describe the expected response output? Better with a real example

**Comment by iPortNe** [comment]
@hsluoyz 
One possible implement could be just like enforce(sub, obj, act) in casbin, with an additional parameter to specify the model.
The result type of this funciton is boolean. The function may look like ModelEnforce(modelName, sub, obj, act).
Also, it could have another function with parameters like ModelPermission(modelName,sub,obj), the return data is an array of permitted actions.

**Comment by hsluoyz** [comment]
@iPortNe batchEnforce() returns a boolean array

**Comment by iPortNe** [comment]
@hsluoyz 
batchEnforce need to pass permission id in each element, which many clients that use casdoor service may not know.

**Comment by hsluoyz** [comment]
@iPortNe fixed by: https://github.com/casdoor/casdoor/commit/6f0b7f3f24ac127107e8defcb9ca9558817041cc
