### ISSUE TITLE
Unable to sync all users from LDAP to CASDOOR

### ISSUE THREAD

**Issue by thomasechen** [casdoor/casdoor#1783]
We use LDAP module to connect to the LDAP server , and found the following issues.

1. Multiple Users are listed but only one user will be synced to the database.

Lots of people are marked as "synced"
![image](https://user-images.githubusercontent.com/73772546/234059906-d41e173c-64a1-42cc-b6cb-0ccea4dac40e.png)

Only one user is shown in the User sections
![image](https://user-images.githubusercontent.com/73772546/234060182-68ce4b88-8bef-4bd6-acb8-16504bd2b22c.png)

3. Using the synced users to login after setting the application "auth" relevant configuration  , system response the password is wrong
![image](https://user-images.githubusercontent.com/73772546/234060611-fb0a0393-6476-4322-8645-05fa1ffbb22a.png)

**Comment by yamaritta** [comment]
Hi!
We have the same problem with Windows LDAP.
Users are not synced:
![image](https://user-images.githubusercontent.com/41572091/234198495-aa0eff6c-fc44-46a9-87d8-dbbb1401b597.png)
![image](https://user-images.githubusercontent.com/41572091/234198584-0fbd7805-5927-43c6-8f88-7bad92d29759.png)

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by leo220yuyaodog** [comment]
@thomasechen Can your provider more details about the password issue? You need to use the password of LDAP user. Instead of checking password stored in casdoor's database, Casdoor connects to LDAP server and verifies whether the user's password is correct.

**Comment by thomasechen** [comment]
@leo220yuyaodog 
Let me share more information. We use the eDIrectory( Micro Focus ) as our LDAP source and the following are the steps I am doing.

1. Create an Organization with the LDAP config and then sync the user between LDAP and CASDOOR. As the screenshot I provided before. We have unique uid number for each person . In the LDAP configuration settings of the organization , I use the format like this ou=XXX,ou=xxxx,o=XXX (instead of using ou=xxx,dc=xxxx,com=XXX) 

![image](https://user-images.githubusercontent.com/73772546/234313853-fc2d0a65-6302-466a-9c43-f08925dc1bdd.png)

2. CASDOOR could find the correct users but only one user was created after the synchronization.

3. The only user synchronized from the LDAP is my account( I event not access my account in the system and set the password). I use my account/password which exactly as same as the one in the LDAP to login with no luck(Pretty sure no any typing error)


Thanks

**Comment by hsluoyz** [comment]
@thomasechen hi, we saw `eDirectory( Micro Focus )` is a commercial product, which we cannot easily get access to, which stopped us from reproducing your issue. Can you share an instance of eDirectory for us to connect our Casdoor to? Please join QQ group at: 645200447

**Comment by yamaritta** [comment]
Hi! What about my case with Windows LDAP? Do you have problems with reproduce?

**Comment by hsluoyz** [comment]
@yamaritta please create GitHub issue

**Comment by hsluoyz** [comment]
Closed as stale
