### ISSUE TITLE
pq: value too long for type character varying

### ISSUE THREAD

**Issue by manduted** [casdoor/casdoor#1795]
Updating a user's default profile picture URL in an organization with more than 100 characters will prompt an error.

![Snipaste_2023-04-28_09-17-19](https://user-images.githubusercontent.com/47053686/235031869-76ead8ca-98b0-44db-ad15-ae75d942e347.jpg)
![Snipaste_2023-04-28_09-17-43](https://user-images.githubusercontent.com/47053686/235031883-24934885-b010-4520-b115-46e5bee9ec41.jpg)

Because the length of default_avatar in the database is set to 100.
Maybe consider increasing the default length because url are long.
Or you can select the image in the Casdoor resource instead of copying its Url first

**Comment by hsluoyz** [comment]
@manduted how long is your avatar URL?

**Comment by manduted** [comment]
> @manduted你的头像网址有多长？

Sorry,I didn't do the math, but I don't think it was more than 100 characters.

However, I have changed the length of the item corresponding to the database to 200 and then it can be saved and no error

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/7e4562efe1783fcd6e83d9852799b6627dd5889c
