### ISSUE TITLE
[Question] How to use SAML Identity Provider (IdP) initiated SSO

### ISSUE THREAD

**Issue by shiningstarts** [casdoor/casdoor#1806]
How to use SAML Identity Provider (IdP) initiated SSO

**Comment by hsluoyz** [comment]
@shiningstarts see docs:

- Casdoor as SAML IdP: https://casdoor.org/docs/how-to-connect/overview#saml
- Casdoor as SAML SP: https://casdoor.org/docs/provider/saml/overview
