### ISSUE TITLE
Bug: minIO provider invalid cause by error path 

### ISSUE THREAD

**Issue by imp2002** [casdoor/casdoor#1813]
Use minIO provider upload a file, the **returned url is wrong**.

- It can't be preview:

![image](https://user-images.githubusercontent.com/41513919/236664630-bde95005-2970-49f6-81da-36dca687e0b2.png)

- Can't get the file from the url:

![image](https://user-images.githubusercontent.com/41513919/236664698-fd68e415-8530-4427-8d98-ff129c456740.png)

I check my `s3` in AWS web found the **url always prefix with bucket name**.

The right path should be `/${prefix-we-set}/resource/${application-name}/${onwer}/xxx.jpg`
But get `/${bucket-name}/${prefix-we-set}/resource/${application-name}/${onwer}/xxx.jpg`

**Comment by hsluoyz** [comment]
@imp2002 can you make a PR to fix it?
