### ISSUE TITLE
Use OAuth why does the authorization code mode not call back after the authorization is successful?

### ISSUE THREAD

**Issue by keepondream** [casdoor/casdoor#1820]
in v1.309.0 and v1.310.0 , When I have authorized success the code is response by json not to callback redirect url.
this is imgage for v1.309 and v1.310
![image](https://user-images.githubusercontent.com/24251510/236760070-72e78ce8-b5d2-40e6-83d5-5f533a5df25e.png)
request url is : http://localhost:7001/login/oauth/authorize?client_id=9b28c625d55985e6238a&redirect_uri=https%3A%2F%2Foauthdebugger.com%2Fdebug&scope=openid&response_type=code&response_mode=query&state=4af30sopg0l&nonce=m57oixmfi2

In OAuth2.0 protocol, the code of the authorization code mode is returned to the client, so how to return

**Comment by keepondream** [comment]
but in v1.308.0 , it is ok

**Comment by hsluoyz** [comment]
@keepondream there are a lot of commits between `v1.308.0` and `v1.309.0`, can you check which commit starts to have this issue?

**Comment by hsluoyz** [comment]
@keepondream why close?

**Comment by meodemsao** [comment]
i have same issue with latest version

**Comment by hsluoyz** [comment]
@meodemsao create new issue
