### ISSUE TITLE
Smaller bundle size of React SPA for user login

### ISSUE THREAD

**Issue by srv1n** [casdoor/casdoor#1823]
I have been playing around with casdoor and it is awesome. Thanks for the great project. 

Ive noticed that the entire frontend is a single SPA. While this is absolutely ok for admin login/management. But the entire SPA is also loaded for end user logins. This is about 4Mb or so and it takes a while to load. We have worked hard to optimize our own app which comes around 300Kb. Having end users load 4Mb just to log in seems much in this scenario. 

Since end users dont need all the functionality would it be possible to consider
1. code splitting the from end. Hoping that will only load the min js needed.
2. seperate frontend for admins and users.

**Comment by hsluoyz** [comment]
@srv1n hi, can you make a PR to fix it?

**Comment by rifkimubarok** [comment]
@hsluoyz maybe can use lazy loading

**Comment by hsluoyz** [comment]
Dup with: https://github.com/casdoor/casdoor/issues/1777

Tracked in: https://github.com/casdoor/casdoor/pull/2005
