### ISSUE TITLE
[Bug] Uploading Terms of Use on Edit Application Page Generates Error

### ISSUE THREAD

**Issue by xanxiver** [casdoor/casdoor#1825]
Hi, currently when I try to upload terms of use on edit application page (https://demo.casdoor.com/applications/casbin/app-example), it generates the following error.

![image](https://user-images.githubusercontent.com/14087528/237017449-05b5ce82-b1b5-473b-9f3a-205e6d5f3ce9.png)

I suspect it is because of trying to find application based on `parent` parameter https://github.com/casdoor/casdoor/blob/master/controllers/resource.go#L238, when the `parent` parameter value is `ApplicationEditPage` in the page.

Thank you

**Comment by mooleetzi** [comment]
hi, @xanxiver could you pls upload your `terms of use` file or you can contact me with email, i need it to handle this issue, thx.

**Comment by hsluoyz** [comment]
@xanxiver fixed by: https://github.com/casdoor/casdoor/commit/e360b06d12bc8ae2d451d7b956e480947350a627
