### ISSUE TITLE
Add tree structure to organization page

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#1828]
The users in an organization can be in a tree structure instead of only a list. The tree data structure can be stored inside the Golang Organization object as `Tree` member. Each node is called "group". The group can be physical or virtual.

Another similar issue: https://github.com/casdoor/casdoor/issues/949

The final effect looks like:

![b31118c667bf7f957231c0322ccee3e](https://github.com/casdoor/casdoor/assets/3787410/7ee8861b-b492-4578-92bb-d6a17030ee83)

**Comment by thanhtinhpas1** [comment]
do we have any plan for this @hsluoyz? I want to make a PR for this but the wireframe is still not clearly. Can I suggest a wire for it then we can start the implement phase?

**Comment by anyidea** [comment]
Is this feature under development?

**Comment by thanhtinhpas1** [comment]
@anyidea I think no, do u want to contribute this feature with me? You can create a PR and I will work on it with u.
