### ISSUE TITLE
Support SaaS Add sub organizations to the organization

### ISSUE THREAD

**Issue by keepondream** [casdoor/casdoor#1830]
1. One organization can have multiple sub -organizations
2. One user can be in multiple organizations
3. An application can be used by a specified user or default all user

![image](https://github.com/casdoor/casdoor/assets/24251510/b423c01d-daae-48c4-9cdb-cdfd5e718613)
A root organization has multiple suborganizations. 
A user can belong to multiple organizations, 
and an application can be used by an organization or a specific user

**Comment by hsluoyz** [comment]
Not planned
