### ISSUE TITLE
[backend] bug: "Data too long for column 'favicon'" when editing organization's favicon

### ISSUE THREAD

**Issue by CKylinMC** [casdoor/casdoor#1831]
When I created an organization and want to change its favicon, I paste a githubusercontent url into the field, then I got error.

![image](https://github.com/casdoor/casdoor/assets/11648014/b7a3f57e-121b-4024-b45c-b62229cbf368)

![image](https://github.com/casdoor/casdoor/assets/11648014/717a9555-b845-4435-9155-058a6eef5225)

then I found the error from server log:

![image](https://github.com/casdoor/casdoor/assets/11648014/0a9e1aef-1485-4bcb-b6e9-caab7f4df498)

This link has 101 chars length, shouldn't be a problem.

**Comment by CKylinMC** [comment]
I found the parameter “u” and “v” in URL is not necessary in this case, so it could be OK. But in some times links could be much more long, **I think should increase the length limit, or give a hint of the length limit.**

**Comment by hsluoyz** [comment]
The real error message should be returned to front:

![image](https://github.com/casdoor/casdoor/assets/3787410/314d79c9-524f-4200-99fc-dfb066784b21)
