### ISSUE TITLE
Ldap can not sync users without uid number

### ISSUE THREAD

**Issue by yamaritta** [casdoor/casdoor#1832]
Hi, we have classical Windows Active directory. 
Users are marked as synced:
![234198495-aa0eff6c-fc44-46a9-87d8-dbbb1401b597](https://github.com/casdoor/casdoor/assets/41572091/eb66f5df-1c37-4cfe-9270-bd310eabd4d2)
but there are no users
![234198584-0fbd7805-5927-43c6-8f88-7bad92d29759](https://github.com/casdoor/casdoor/assets/41572091/591095a1-f8a4-4f15-90f1-9b87ea5d8793)

**Comment by hsluoyz** [comment]
@yamaritta to import LDAP data into Casdoor users, you should use LDAP syncer: https://door.casdoor.com/syncers/syncer_casbin instead of organization's LDAP feature

**Comment by yamaritta** [comment]
please, describe the differences between ldap syncer and  button "Sync LDAP" in organization card?

**Comment by yamaritta** [comment]
I set up synchronization by article https://casdoor.org/ru/docs/ldap/config

**Comment by yamaritta** [comment]
@hsluoyz The problem is that the sync button is disabled if users don't have uuid. Do you have plans to improve this?

**Comment by yamaritta** [comment]
@hsluoyz In windows active directory unique identifier is samAccountName attribute. It seems that ldap settings need an option from which user attribute to get a unique identifier.
