### ISSUE TITLE
Force user to change password after login

### ISSUE THREAD

**Issue by ISulimanov** [casdoor/casdoor#1833]
As administrator I wont to be able force specific user to change password.

As a option it could be boolean prop in user like - passwordChangesRequired. 
If true - than after first login - user has to change his password. 

Is there kind of feature in roadmap? 
Or it should be implemented on client side ?

**Comment by hsluoyz** [comment]
@ISulimanov sounds OK. Can you make a PR to add it?

**Comment by ISulimanov** [comment]
sure, we will send PR in 1-2 weeks
