### ISSUE TITLE
Validation is absent for AddApplication API request

### ISSUE THREAD

**Issue by zabbius** [casdoor/casdoor#1839]
```
app := &casdoorsdk.Application{
  Name: "test app",
 }

 ok, err := casdoorsdk.AddApplication(app)
 ```

This Go code breaks at least 'Applications' web page by creating DB row with nulls. AddApplication returns OK. It seems that validation is absent on server side.

**Comment by hsluoyz** [comment]
@zabbius fixed by: https://github.com/casdoor/casdoor/commit/0b5ecca5c8c292bcc427c7f440e55e8cc297a86e
