### ISSUE TITLE
[backend] User should have PasswordType like Organization is

### ISSUE THREAD

**Issue by aegoroff** [casdoor/casdoor#1840]
# What we have now
1. Lets suppose you have an organization that has some specific password type (plain, salt, etc.).
2. Now you change it (password type)
3. Nowdays after doing so you cannot login after changing Organization's PasswordType because CredManager created using new organization PasswordType which is different from old one

# What should we do

1. We have to use old password type settings (i.e. created when user created) because we dont change all users' passwords after changing organzation's password type
2. This password type settings should be kept alongside each user (add new column to user table or keep it just inside password hash like Apache passwords https://httpd.apache.org/docs/2.4/misc/password_encryptions.html)
3. This user's setttings will be changed later when user decided to change his (her) pasword, and in this case organization password type will be used for it
4. Newly created users should inherit organization's password type

**Comment by hsluoyz** [comment]
@aegoroff sounds good. Can you make a PR?

**Comment by aegoroff** [comment]
Yes, i'll do
