### ISSUE TITLE
[backend] Add health check API to monitor service

### ISSUE THREAD

**Issue by thanhtinhpas1** [casdoor/casdoor#1842]
Currently, I deployed Casdoor to my server by using K8s, but Casdoor didn't have `/health` API, so I can't process the deployment. 
K8s need API  health check to control whether the service is healthy or not.

Can we add this endpoint?

**Comment by hsluoyz** [comment]
@thanhtinhpas1 hi, can you make a PR to add it?

**Comment by thanhtinhpas1** [comment]
> @thanhtinhpas1 hi, can you make a PR to add it?

Sure, will send an MR in a few days.

**Comment by hsluoyz** [comment]
@thanhtinhpas1 done at: https://github.com/casdoor/casdoor/commit/3d9b305bbb7a6b1eaf41ad191c7b32cce42355cb
