### ISSUE TITLE
[backend] Enforce with `resource` only

### ISSUE THREAD

**Issue by thanhtinhpas1** [casdoor/casdoor#1846]
Currently, we just enforce whenever know one of two params `permissionId` or `modelId`, but in my case when integrating Casdoor with Apisix, I want to enforce only with `resource` (URI of request in my case).

I suggest we have the option to get a list of permissions based on data of `PermissionRule` and then enforce. Another benefit of it is performance, above suggestion will reduce the amount of permissions need to enforce each time.

**Comment by hsluoyz** [comment]
@thanhtinhpas1 can you make a PR?

**Comment by thanhtinhpas1** [comment]
> @thanhtinhpas1 can you make a PR?

Sure, will send a PR for this.

**Comment by thanhtinhpas1** [comment]
Already make a PR for this issue, @hsluoyz please take a look [PR 1855](https://github.com/casdoor/casdoor/pull/1855)
