### ISSUE TITLE
[Feature request] Dingtalk support connecting casdoor users by mobile phone

### ISSUE THREAD

**Issue by anyidea** [casdoor/casdoor#1848]
Can DingTalk integration with Casdoor users additionally support mobile phones? It currently supports organization emails.

**Comment by hsluoyz** [comment]
@anyidea can you debug here and see if you get the non-empty Phone value?

https://github.com/casdoor/casdoor/blob/f82292ec4ef558f56350751812fd8b0063df9224/idp/dingtalk.go#L165-L174

**Comment by hsluoyz** [comment]
@anyidea fixed by: https://github.com/casdoor/casdoor/commit/983a30a2e068f950e1cc9953b11b4d0ac1d1907d
