### ISSUE TITLE
[BUG] new social account users cannot be connected with existing Casdoor users

### ISSUE THREAD

**Issue by anyidea** [casdoor/casdoor#1849]
If the Casdoor application has user registration turned off, users logging in for the first time via third-party social logins will not be associated with existing Casdoor users via email. Instead, they will encounter an error, indicating that new user registration is not possible.

**Comment by hsluoyz** [comment]
@anyidea fixed by: https://github.com/casdoor/casdoor/commit/37d0157d416c5ff7529a849756a89e734b49223a
