### ISSUE TITLE
[Bug] : get cert panic when user login 

### ISSUE THREAD

**Issue by mostcute** [casdoor/casdoor#1854]
![image](https://github.com/casdoor/casdoor/assets/23225426/4987baaa-48a7-4f20-839c-29214f6afc86)

**Comment by mostcute** [comment]
found the code query cert by owner==admin
`return getCert("admin", application.Cert)`

i want to use app.Owner to replace the "admin"

but there is another problem , app's owner != cert's owner, app can use the cert which owner is not app's owner

**Comment by hsluoyz** [comment]
@XDTD
