### ISSUE TITLE
about get-provider API ClientSecret and ClientSecret2 filed response "***"

### ISSUE THREAD

**Issue by PierceDeng** [casdoor/casdoor#1862]
If I use casdoor to manage the provider's data, how can I synchronize the provider's data from casdoor to my business application? Because when I call the get-provider interface, the ClientSecret field and ClientSecret2 field return data as '***'. Unable to return unencrypted data after reviewing the code logic written by the author. After trying to use webhook, I couldn't get the unencrypted clientsecret either, if only I had passed parameters and checked permissions to return normal data.

![image](https://github.com/casdoor/casdoor/assets/37127578/055991e0-3f10-4bd3-9453-356e30572416)

**Comment by hsluoyz** [comment]
@PierceDeng fixed by: https://github.com/casdoor/casdoor/commit/de73ff0e604d06cca8c30af69b7a166dd2401302

1. Add `&withSecret=1` GET parameter
2. Use global admin or app user to authenticate the API
3. Make sure demo mode is OFF

**Comment by PierceDeng** [comment]
thx
