### ISSUE TITLE
[bug] app (from sdk) cannot update accountItem with "Admin" ModifyRule

### ISSUE THREAD

**Issue by xanxiver** [casdoor/casdoor#1865]
Hi on the latest release, application that try to use /api/update-user from SDK cannot update accountItem with "Admin" ModifyRule (previously it can)

I think it is because, update-user use `c.IsAdmin()` https://github.com/casdoor/casdoor/blob/master/controllers/user.go#L171

In `IsAdmin()` there is `user == nil` check, and if you use SDK the user will be `nil` https://github.com/casdoor/casdoor/blob/master/controllers/base.go#L51
https://github.com/casdoor/casdoor/blob/master/controllers/base.go#L62

**Comment by hsluoyz** [comment]
@xanxiver hi, can you provide the link for the PR or commits that breaks this feature?

**Comment by xanxiver** [comment]
Hi @hsluoyz , this is the related [PR](https://github.com/casdoor/casdoor/pull/1789)

I'm not sure if this is intended change or not.

Thanks

**Comment by xanxiver** [comment]
Another [PR](https://github.com/casdoor/casdoor/commit/95f4f4cb6d4607edd939f823efff1b6ea5da9c0f#diff-64a63228546ebdbd9a1ee7a43793f89b24047f3bd080a952d86abdd38ed2b258R166-R177) that related to this change @hsluoyz 

changing `c.IsGlobalAdmin()` to `c.IsAdmin()`

**Comment by hsluoyz** [comment]
@leo220yuyaodog
