### ISSUE TITLE
 AD login not working

### ISSUE THREAD

**Issue by yamaritta** [casdoor/casdoor#1867]
Hi!
In Microsoft AD search filter &(uid=login) doesn`t work.
Case 1 filter fields is empty
![image](https://github.com/casdoor/casdoor/assets/41572091/93867163-1e90-4071-98c5-4d758e95e412)
![image](https://github.com/casdoor/casdoor/assets/41572091/e3964b17-165d-4e6f-9a88-4ab12472067f)
![image](https://github.com/casdoor/casdoor/assets/41572091/f4258b0d-5903-4663-af9d-baef867abc8d)
Case 2 uid is selected in filter fields
![image](https://github.com/casdoor/casdoor/assets/41572091/2434b21f-d73a-431f-b3bf-188ebeb3d87a)
![image](https://github.com/casdoor/casdoor/assets/41572091/839d7ac7-4ba6-467c-a389-ecdf711ee8b0)

In this cases  would be better to use samAccountName as filter attribute.

**Comment by leo220yuyaodog** [comment]
@yamaritta Hi, I add "sAMAccountName" field at the UI as a solution.  Do you think it is OK?  See pr #1869

**Comment by yamaritta** [comment]
@leo220yuyaodog It is very good! Users will be able to flexibly configure the connection
