### ISSUE TITLE
The resource list does not display uploaded files

### ISSUE THREAD

**Issue by anothertenyears** [casdoor/casdoor#1874]
using "Local file System" upload picture.
After the image is uploaded successfully, it is not displayed in the resource list.
#1822 
[![p9IYirD.png](https://s1.ax1x.com/2023/05/21/p9IYirD.png)](https://imgse.com/i/p9IYirD)

api/get-account
[![p9IY9xK.png](https://s1.ax1x.com/2023/05/21/p9IY9xK.png)](https://imgse.com/i/p9IY9xK)

api/get-resources
[![p9IYPKO.png](https://s1.ax1x.com/2023/05/21/p9IYPKO.png)](https://imgse.com/i/p9IYPKO)

**Comment by anyidea** [comment]
Same issue with Aliyun OSS

**Comment by hsluoyz** [comment]
@anothertenyears can you make a PR to fix it?
