### ISSUE TITLE
[backend] add password complexity options to organization edit page

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#1884]

**Comment by ovsinc** [comment]
Hi.
This topic is also interesting to me. I propose to discuss a sketch of how it might look. I took the form "Keycloak Password Policy" as a basis.

![Uploading organization with password complexity.png…]()

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/pull/1949
