### ISSUE TITLE
[feature]The home application icons are too large

### ISSUE THREAD

**Issue by anyidea** [casdoor/casdoor#1886]
The home screen application icons are too large. Can they support custom styles, such as size and image?
![sso_homepage-9a368fa35b6e7bf07c333b423155be30](https://github.com/casdoor/casdoor/assets/48710760/a4cd1e90-5ead-48d3-bd5f-32592507a414)

**Comment by anyidea** [comment]
It would be even better if the application names could be centered.

**Comment by hsluoyz** [comment]
@anyidea image is app's logo. What size do you want?

**Comment by anyidea** [comment]
> 

Can the image size be configured?

**Comment by hsluoyz** [comment]
No. You need to customize the code.

Closed here
