### ISSUE TITLE
staticBaseUrl seem invalid in app.conf

### ISSUE THREAD

**Issue by Matrix-0** [casdoor/casdoor#1887]
I have deployed my own static file server, but when I modify `app.conf`, the front-end pages are still using the default static file server at https://cdn.casbin.org.  

Is this a bug or is the [documentation ](https://casdoor.org/docs/basic/server-installation#via-ini-file)incorrectly described?
> staticBaseUrl is address of the static image when the system initializes the database.

I changed https://github.com/casdoor/casdoor/blob/95ab2472ce84c479be43d6fc4db6533fc738b259/web/src/Setting.js#L34 and recompiled the front-end file and it worked.

**Comment by hsluoyz** [comment]
@Matrix-0 what's your question? Actually, if you changed all `https://cdn.casbin.org/` occurences to something else, then it will not show up any more, right?
