### ISSUE TITLE
Casdoor as SAML SP with keycloak login not work 

### ISSUE THREAD

**Issue by yamaritta** [casdoor/casdoor#1894]
Hi! I try to use Casdoor as SAML SP  with keycloak different version and casdoor can't login.

**In Keycloak 12.0.4 (version of our test environment)**

1. Create realm
![image](https://github.com/casdoor/casdoor/assets/41572091/6d3bfc27-82d9-4b82-8acb-931828f55e94)
2. Configure client connection
![image](https://github.com/casdoor/casdoor/assets/41572091/fd6b367c-4c92-47a1-8d04-a88211aa207d)
3. Download metadata files in moq auth format
4. Create new provider in casdoor
![image](https://github.com/casdoor/casdoor/assets/41572091/29378466-a1ea-445c-8c2b-ea0ffcaf6750)

5. Try to login
![image](https://github.com/casdoor/casdoor/assets/41572091/d2e88b58-3efd-4219-927c-87b99452d135)

**In Keycloack 21.1.1 (latest version running in docker with start-dev parameter)**

1. create realm
![image](https://github.com/casdoor/casdoor/assets/41572091/dd57872a-592d-4d0a-98bc-36bf7647901f)
2. Configure client connection
![image](https://github.com/casdoor/casdoor/assets/41572091/0819bc84-24cd-469b-9c70-c7112c49c57a)
![image](https://github.com/casdoor/casdoor/assets/41572091/f1bd035a-d0d3-4496-9d59-84eab5826f20)
![image](https://github.com/casdoor/casdoor/assets/41572091/eaf1bbe5-e8bc-4995-bfcd-1524e2d9fa13)
3. Copy metadata SP from realm settings
4. Create new provider in casdoor
![image](https://github.com/casdoor/casdoor/assets/41572091/87884006-d2af-45fb-9c21-c916ff7126f8)
5. Try to login
![image](https://github.com/casdoor/casdoor/assets/41572091/dec68e4e-d5c9-4352-97b4-a1e44c052766)

I also tried to change the client ID from  full path to relative /api/acs, but that didn't help

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by leo220yuyaodog** [comment]
@yamaritta please try keycloack v6.0.1. High version is unavailable.
