### ISSUE TITLE
Bug: creating two providers with the same name ends an unexpected exception and behavior

### ISSUE THREAD

**Issue by yamaritta** [casdoor/casdoor#1895]
Hi!
Steps to reproduce:
1. Create first provider any type (for example saml) with name test and default option
![image](https://github.com/casdoor/casdoor/assets/41572091/f11ee083-2f8d-49fc-8f46-18f2fb841bf5)
![image](https://github.com/casdoor/casdoor/assets/41572091/91d6cb4b-3c18-4d55-a76d-bd8b097cf1fd)
2. Try  to create another provider with the same name
![image](https://github.com/casdoor/casdoor/assets/41572091/1bc3f349-d04b-4d61-952e-426a6c8db8bf)
![image](https://github.com/casdoor/casdoor/assets/41572091/b9e9af60-ce60-4bb5-8c9e-75370200c8fb)
3. Return to  list of providers. There is no previous provider. But there is a new provider with an unexpected name 
![image](https://github.com/casdoor/casdoor/assets/41572091/2ee62a67-c794-4d93-b9c1-36f5f9497988)

**Comment by hsluoyz** [comment]
@yamaritta this is not a bug. The error message improvement is tracked in: https://github.com/casdoor/casdoor/issues/1831

And it's not an "unexpected" name, it's a random name provider just generated after you clicked "Add", you need to click "Cancel" to remove it.

**Comment by yamaritta** [comment]
Why was first provider created deleted?
