### ISSUE TITLE
Role: add optional field "description"

### ISSUE THREAD

**Issue by KirovVerst** [casdoor/casdoor#1900]
I want to add a new field "description" to the role entity. It will be an optional string field that can be used to provide some additional information about a role.

Could this feature be considered as a useful feature for Casdoor?

**Comment by hsluoyz** [comment]
@KirovVerst yes, it seems to be very useful! Can you make the PR to add it?

Please refer to existing code:

![image](https://github.com/casdoor/casdoor/assets/3787410/c2e18f12-df1a-4a39-99c8-c799cf8ea4df)

**Comment by KirovVerst** [comment]
@hsluoyz , yes, I'll make the PR. Thanks for the reference to existing code!

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/a7bbafbee45f970e20b749f2cf07c7f71d6bef7f
