### ISSUE TITLE
Support logger cofiguration from file

### ISSUE THREAD

**Issue by zabbius** [casdoor/casdoor#1902]
Now logger config is hardcoded in `main.go` and cannot be changed without recompiling and rebuilding docker image. Most of products have such option.

**Comment by hsluoyz** [comment]
@zabbius can you make a PR to add it?

**Comment by zabbius** [comment]
I'm not a Go developer, but will try to do it =)

**Comment by hsluoyz** [comment]
Use Beego's built-in logging ways, and use GPT if you are not good at it

**Comment by zabbius** [comment]
have tried to do my best =)
https://github.com/casdoor/casdoor/pull/1904

**Comment by hsluoyz** [comment]
Not very meaningful, you can fork and change it by yourself
