### ISSUE TITLE
[backend] webhooks bug

### ISSUE THREAD

**Issue by ofeng** [casdoor/casdoor#1918]
when admin update or delete user ， casdoor aways send the admin userinfo to the  callback URL ，not the real user。

**Comment by hsluoyz** [comment]
@ofeng when you use User-A (logged in as User-A) to update or delete User-B, `extendedUser` is User-A's info, `object` is User-B's info, see: https://door.casdoor.com/webhooks/webhook_hasura

![image](https://github.com/casdoor/casdoor/assets/3787410/190c1c63-0061-4ab2-b137-0f0ffb51cc66)

**Comment by ofeng** [comment]
Thank you  for your help，but callback  url  can not recieve the  "object" fields
casdoor deploy by docker
version: v1.308.0

**Comment by hsluoyz** [comment]
@ofeng use latest version (current: v1.327.0)

**Comment by cy948** [comment]
@hsluoyz Hi, I trigger webhook `update-user` by update user's email in version [v1.695.0](https://github.com/casdoor/casdoor/releases/tag/v1.695.0), but the webhooks post object does not contain field `email`, is it a bug?
The object is the string as below: 
```
{"owner":"kts11j","name":"user_pyapye","createdTime":"2024-11-28T19:57:33+08:00","updatedTime":"2025-02-17T15:26:13+08:00","deletedTime":"","id":"b5a7c5b5-3e79-47ff-85a8-537b07fee2f9","externalId":"","type":"normal-user","password":"***":false}
```

**Comment by hsluoyz** [comment]
@cy948 

1. Create a new issue
2. If the field is empty, maybe omitted?

**Comment by cy948** [comment]
@hsluoyz ok, I will create a issue later with more details. 😊
