### ISSUE TITLE
Stop using static salt to hash passwords and start using dynamic one

### ISSUE THREAD

**Issue by aegoroff** [casdoor/casdoor#1919]
### Problem
Now to hash passwords using `Sha256SaltCredManager,` `Md5UserSaltCredManager `and `Pbkdf2SaltCredManager` static salt value are used. Aside from that there are some inconsistency among `Sha256SaltCredManager` and `Md5UserSaltCredManager` where `Sha256SaltCredManager` uses organizationSalt to hash password, but `Md5UserSaltCredManager` uses userSalt. i.e.
```
func (cm *Sha256SaltCredManager) GetHashedPassword(password string, userSalt string, organizationSalt string) string {
	res := getSha256HexDigest(password)
	if organizationSalt != "" {
		res = getSha256HexDigest(res + organizationSalt)
	}
	return res
}
```
and
```
func (cm *Md5UserSaltCredManager) GetHashedPassword(password string, userSalt string, organizationSalt string) string {
	res := getMd5HexDigest(password)
	if userSalt != "" {
		res = getMd5HexDigest(res + userSalt)
	}
	return res
}
```
Move on. Because `Sha256SaltCredManager` uses single salt value for all organization's users it provokes security hole because all users with the same password will have the same hash and it'll make possible dictionary or rainbow tables attacks.

### Possible solution
It would be nice to have random salt (only user salt, organization salt must be removed) which changed each time user change his(her) password.

Additional information in Wikipedia https://en.wikipedia.org/wiki/Salt_(cryptography)

**Comment by hsluoyz** [comment]
@aegoroff can you make a PR to add it? To keep backward-compatibility, we can add new options like: `Sha256SaltCredManager (Dynamic Salt)`

**Comment by aegoroff** [comment]
@hsluoyz i'll make but not right now. About backward-compatibility - we can just copy organization salt into user salt for such users and this salt will be regenerated next time user change password but keep possibility to login to others (that not changed it's password). So we change algorithm and dont break users' possibility to login

**Comment by hsluoyz** [comment]
@aegoroff OK, BTW, did you write the last migrator? The performance is very bad for large users.. Please avoid this for next time: https://github.com/casdoor/casdoor/commit/5349fa7ff3de2a3b142115d4af7fcb7e1597264a

**Comment by aegoroff** [comment]
@hsluoyz correct i did that. Thank you for fix and the lesson, i forgot about performance and promise not to do migration like this any more. Thank you once again :)
