### ISSUE TITLE
Image not found https://cdn.casbin.org/img/social_wechatminiprogram.png 

### ISSUE THREAD

**Issue by jony4** [casdoor/casdoor#1928]
https://cdn.casbin.org/img/social_wechatminiprogram.png

**Comment by jony4** [comment]
![image](https://github.com/casdoor/casdoor/assets/13718575/e465a95d-4126-4d12-bb66-be2886d874bc)

**Comment by hsluoyz** [comment]
Added in: https://github.com/casbin/static/commit/6ce4cd7a7cf6e30219bc8c5168a18e83646ae6fe
