### ISSUE TITLE
Is it possible to support array of organization in the userinfo?

### ISSUE THREAD

**Issue by robincodex** [casdoor/casdoor#1929]
I know that now userinfo already has `organization` field, when I use casdoor to login to [harbor](https://goharbor.io/), I found that harbor can't recognize `organization`, because harbor only recognize type `[]string`, so I wonder if casdoor can add `organizations` field with type []string, so that it is more applicable in more sites.

**Comment by hsluoyz** [comment]
@robincodex is this `organizations` field part of any standards like OIDC? If yes, please provider a reference URL.

And what should be filled into []string? Only one element (aka the organization)?

**Comment by robincodex** [comment]
> @robincodex is this `organizations` field part of any standards like OIDC? If yes, please provider a reference URL.
> 
> And what should be filled into []string? Only one element (aka the organization)?

Sorry, I don't understand the OIDC standards, maybe it's the `groups` field? It seems Azure is using the `groups` field, because I saw this https://github.com/goharbor/harbor/issues/17998.

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casdoor/casdoor/commit/7298d138bc2bd189dafa3829bd2338689d0bc400

**Comment by robincodex** [comment]
Thank you.
