### ISSUE TITLE
User pages cannot be accessed properly after using the tableNamePrefix parameter

### ISSUE THREAD

**Issue by chencu5958** [casdoor/casdoor#1932]
I used 1.3.29.1 released in the release page to do the test, and found that using tableNamePrefix = prefix, accessing the user page after starting casdoor gives `Error 1146: Table 'database_account_test.user' doesn't exist` error, no matter change docker version or source code test have the problem, use 1.3.25.0 to 1.3.27.0 test have no the problem, the lowest version switch to `1.3.28.0` encountered the problem, reproduce the problem using Docker container + Mysql8.0

**Comment by chencu5958** [comment]
Test all configuration files are default, only the Mysql database connection parameters were modified to connect to the remote database for testing

**Comment by hsluoyz** [comment]
@chencu5958 can you test which commit between `v1.327.0` and `v1.328.0` causes this issue?

**Comment by chencu5958** [comment]
> @chencu5958 can you test which commit between `v1.327.0` and `v1.328.0` causes this issue?

I guess it should be caused by this [commit#1](https://github.com/casdoor/casdoor/commit/5349fa7ff3de2a3b142115d4af7fcb7e1597264a) or this [commit#2](https://github.com/casdoor/casdoor/commit/b1b3184e75ae5eed6c96c2a85f5e26411952983e)

This is using go run in commit#1 In the case of main.go, saving directly cannot run
```YAML
PS D:\casdoor> go run .\main.go
panic: Error 1146: Table 'database_account_test.user' doesn't exist

goroutine 1 [running]:
github.com/casdoor/casdoor/object.(*Migrator_1_314_0_PR_1841).IsMigrationNeeded(0x1f2baa0)
        D:/casdoor/object/migrator_1_314_0_PR_1841.go:27 +0xc7
github.com/casdoor/casdoor/object.DoMigration()
        D:/casdoor/object/migrator.go:36 +0x130
main.main()
        D:/casdoor/main.go:38 +0xa5
exit status 2
```

Commit#2 is running normally, but when accessing the API endpoint corresponding to the user page, `http://example.com/api/get-global-users`, `Error 1146: Table 'database will appear_ Account_ Test. user 'does not exist` error

**Comment by hsluoyz** [comment]
@chencu5958 can you try this? https://github.com/casdoor/casdoor/commit/43439bc8c6ec8d587f3e398cd8bfb06bc74aba8f

**Comment by chencu5958** [comment]
> @chencu5958 can you try this? [43439bc](https://github.com/casdoor/casdoor/commit/43439bc8c6ec8d587f3e398cd8bfb06bc74aba8f)

Tested the same problem, I personally suspect that one of the two commit updates has caused the problem

**Comment by hsluoyz** [comment]
@XDTD

**Comment by XDTD** [comment]
@chencu5958  I have submitted a PR to solve this issue. can you please try [this](https://github.com/casdoor/casdoor/pull/1945)?

**Comment by chencu5958** [comment]
> @chencu5958 I have submitted a PR to solve this issue. can you please try [this](https://github.com/casdoor/casdoor/pull/1945)?

I just tried it out and I won't encounter this bug now. Thank you very much for helping me solve this problem
