### ISSUE TITLE
When using synchronizer, user updates cannot be synchronized. Why?

### ISSUE THREAD

**Issue by EthanY92** [casdoor/casdoor#1933]
For example, when I updated the user password, the password was not synchronized to casdoor. I saw the updated log, but the data in the database did not change.
![image](https://github.com/casdoor/casdoor/assets/128674487/b5fe7bf5-f81c-4345-af0c-b4d6b3bb85dd)
![image](https://github.com/casdoor/casdoor/assets/128674487/3e29bb9b-1681-45ad-98df-d148bee9a87c)

**Comment by hsluoyz** [comment]
@EthanY92 can you debug the code here? `columns` should contain `password`

https://github.com/casdoor/casdoor/blob/764054848869c5abcf0ab1b58f022943d3310c68/object/syncer_user.go#L139-L147

**Comment by EthanY92** [comment]
@hsluoyz I do not have debug, I have configured the synchronization of the password field on the page，columns should contain password。 And the hash value is not saved during the first synchronization. Is this normal?

**Comment by hsluoyz** [comment]
@EthanY92 hi, do you have QQ or weChat?

**Comment by hsluoyz** [comment]
@EthanY92 hi, I have two questions:

1. Can other fields (like display name, Email) be synced? Or just password doesn't work?
2. Does you issue happen all the times you using Casdoor? Or just one recent Casdoor release introduced this bug?

**Comment by EthanY92** [comment]
@hsluoyz 
1.Other fields also cannot be synced.
2.It's a issue every time .  I am using now is v1.329.0。

**Comment by hsluoyz** [comment]
@EthanY92 can you check if this PR: https://github.com/casdoor/casdoor/pull/1998 has fixed your issue?

**Comment by hsluoyz** [comment]
@Baihhh
