### ISSUE TITLE
casdoor-all-in-one on docker not working.

### ISSUE THREAD

**Issue by younus-ma** [casdoor/casdoor#1940]
<img width="976" alt="image" src="https://github.com/casdoor/casdoor/assets/38235448/18dfe068-bc20-4859-bac0-38c2c6b9166f">

I run casbin/casdoor-all-in-one on my mac according to the requirements of the document, but I get the results shown in the figure, please help to locate the reason

**Comment by hsluoyz** [comment]
@younus-ma fixed by: https://github.com/casdoor/casdoor/commit/cc566bf31f1ad438588b60e430ac84e5aab2c955

**Comment by hsluoyz** [comment]
@younus-ma fixed by: https://github.com/casdoor/casdoor/commit/ff87c4ea33c036db6ba62064634eacca4c6fbf97
