### ISSUE TITLE
Errors on setup casdoor app with docker image

### ISSUE THREAD

**Issue by lrojas89** [casdoor/casdoor#1942]
Hi, i setup casdoor using docker image, i use a docker-compose yaml with postgres and get this erros
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
db           | 2023-06-06 16:39:45.195 CDT [38] ERROR:  relation "session" does not exist at character 74
db           | 2023-06-06 16:39:45.195 CDT [38] STATEMENT:  SELECT "owner", "name", "application", "created_time", "session_id" FROM "session"
db           | 2023-06-06 16:39:45.197 CDT [38] ERROR:  relation "user" does not exist at character 22
db           | 2023-06-06 16:39:45.197 CDT [38] STATEMENT:  SELECT count(*) FROM "user" WHERE (password_type=$1)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
and the casdoor app get 
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
casdoor-app  | [xorm] [warn]  2023/06/06 16:39:45.890203 Table permission_rule has column id but struct has not related field
casdoor-app  | [xorm] [warn]  2023/06/06 16:39:46.004365 Table permission_rule has column id but struct has not related field
casdoor-app  | logs.BeeLogger.SetLogger: unexpected end of JSON input
casdoor-app  | panic: unexpected end of JSON input
casdoor-app  | 
casdoor-app  | goroutine 1 [running]:
casdoor-app  | main.main()
casdoor-app  |  /go/src/casdoor/main.go:78 +0x565
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

The PostgresSQL version is 12.12 and the casdoor app version are v1.329.0, v1.330.0, v1.331.0 but in the version 1.251.0 everythings is OK

**Comment by hsluoyz** [comment]
@lrojas89 hi, can you binary-search the versions from 1.251.0 to v1.329.0, to see starting from which version this issue happens? This will help a lot for troubleshooting.

**Comment by hsluoyz** [comment]
@baiyunlqy I didn't see any commits wrong between v1.326.0 and v1.327.0 , can you binary-search the commits from v1.326.0 to v1.327.0, to see starting from which commit this issue happens?

Thanks again!

**Comment by hsluoyz** [comment]
@lrojas89 the second issue is fixed in: https://github.com/casdoor/casdoor/commit/2d0473162217c42ff4161c1510d3252a03a8d65f

For 1st issue, I guess it's the DB migration issue. So plz use a new DB to start Casdoor, then manually migrate your data from old DB to new DB
