### ISSUE TITLE
Secure database initialization

### ISSUE THREAD

**Issue by ovsinc** [casdoor/casdoor#1947]
I suggest optimizing database initialization.
My proposal allows you to increase security.

Now the process of calls making changes to the database at the casdoor initialization stage looks like this:
`DoMigration()` -> `CreateTables()` -> `InitDb()` -> `InitFromFile()`

It is considered safe to perform the process of preparing the database for operation separately from the operation of the application. Large privileges are usually required to prepare and initialize a database. And in order for the application to work, a user with limited access rights is created.

I propose to divide these actions into two applications.
In the cli, the initialization utility will be able to prepare the database for operation (`DoMigration()` -> `CreateTables()` -> `InitDb()` -> `InitFromFile()`). This utility will run if necessary.

**Comment by hsluoyz** [comment]
No need to change this for now
