### ISSUE TITLE
fix: add and edit item need extra requests in all tablle

### ISSUE THREAD

**Issue by 907997375** [casdoor/casdoor#1948]
The coupling between adding and editing pages is too high, requiring additional requests and events to achieve functionality. Decouple the two pages and use the same page component through adding new routes

add page
1.The item has been added before entering the add page.（expect：execute when clicking save&exit button）
2.save&exit need 2 requests that add and updata.（expect：only an add request）
3.cancel need 2 requests that add and delete.（expect：no request）
4.save in page is edit function.（expect: remove save button in add page)
5.add page become edit page after f5 reload. (expect: add an page by same component)

edit page
1.i will have extra request if i think no change. (expect: no request by adding a exit button)
https://github.com/casdoor/casdoor/assets/82175017/f16ddeeb-239e-409a-b77e-f4a8af119348

**Comment by 907997375** [comment]
@hsluoyz If you feel that the process needs to be modified, I can submit a PR within 1-2 weeks to fix this issue. We need to add an add page without adding any files, just modify the function trigger timing and buttons. I think the edit function can be removed from the add page and an exit button can be added to the edit page. The current process coupling is too high and is prone to unknown bugs.

**Comment by hsluoyz** [comment]
a suitable and clean PR (< 10 lines of code modification for one page) is welcome

**Comment by 907997375** [comment]
@hsluoyz 
I estimate that it only takes 10 lines or less to modify the execution time of the function, as the function is not a problem. However, the add function of the table is now implemented before jumping to the page, and more lines are needed to move it to the add page. The current add page is actually an editing page and includes the deletion function, so it requires additional request support. I try to reduce the amount of code modifications as much as possible to make the process normal.
