### ISSUE TITLE
Send Email Always with code "123456"

### ISSUE THREAD

**Issue by mostcute** [casdoor/casdoor#1950]
![img_v2_a939e1d3-9fa3-408a-b596-8962768b4ehu](https://github.com/casdoor/casdoor/assets/23225426/c99e14e2-892e-4060-a435-63ebae98639f)

**Comment by mostcute** [comment]
if use the sdk to send email,it will always send with 123456

**Comment by hsluoyz** [comment]
@mostcute as you see, your `emailForm.Content` should not contain format string `%s` to let Casdoor replace it with `123456`. Just  use a real verification number
