### ISSUE TITLE
Nil reference error when adding a new provider

### ISSUE THREAD

**Issue by oyamo** [casdoor/casdoor#1956]
Nil reference error when testing a new email provider
I am using the casdoor docker image [v1.326.0](https://hub.docker.com/layers/casbin/casdoor/v1.326.0/images/sha256-6d6fbabc5011672f5616c53634827f9119f3800cb5426ffc0e1ebd70b74a546a?context=explore)

![image](https://github.com/casdoor/casdoor/assets/34618315/ae63f6a9-e70b-44bc-a8b2-6cd30b8c78f4)

**Comment by hsluoyz** [comment]
@oyamo real error can be shown with this commit: https://github.com/casdoor/casdoor/commit/e0d2bc3dc90c8109dc38331f4afcd4be1a70ca8a
