### ISSUE TITLE
BatchEnforce() API add details

### ISSUE THREAD

**Issue by hound672** [casdoor/casdoor#1980]
`batch enforce` response contains only array of bools, 
so it's difficult to recognize which permission bool flag stands for
I suggest to add  some addition information to response.
For example, I send this batch enforce:
```
[
{"built-in/my_user", "test_group", "users", "read"},
{"built-in/my_user", "test_group", "items", "read"}
]
```

And then I'd like to get response smth like:
```
[
   {"v0": "test_group", "v1": "users", "v2": "read", "res": true}, 
   {"v0": "test_group", "v1": "items", "v2": "read", "res": false}
]
```

**Comment by hsluoyz** [comment]
@hound672 can you make a PR?

**Comment by hound672** [comment]
I'll try.
But I thought about response format.
Since enforce returns only bool flag for request, maybe it'll be better to return array of bools but in the same order and only for requested permission?
For now casdoor returns all results for passed model. 
I mean: we send batch enforce:
'''
[
{"built-in/my_user", "test_group", "users", "read"},
{"built-in/my_user", "test_group", "items", "read"}
]'''
And then expect to receive this array: '''[true, false]'''
Where the first item is for '''"{built-in/my_user", "test_group", "users", "read"}''', and the second for '''"built-in/my_user", "test_group", "items", "read"}'''
What do you think?

**Comment by hsluoyz** [comment]
@hound672 isn't it already this in the code? You can specify `permissionId` arg.

What do you get now? and what you expect?

**Comment by thanhtinhpas1** [comment]
@hound672  The response currently was ordering, I think we no need to add more information like your example.

Does it make sense to you too @hsluoyz ?

**Comment by hsluoyz** [comment]
@thanhtinhpas1 yes, exactly. The response follows the order of the request. So no need to add extra info. Closed here
