### ISSUE TITLE
Cant add adapter, get error

### ISSUE THREAD

**Issue by wildwind123** [casdoor/casdoor#1982]
when i add model, i see in database this records.

![image](https://github.com/casdoor/casdoor/assets/34130873/8be578fa-0a59-4bbe-a6fe-2ae6eae1defb)

when i add adapter, i see this error, in ajax request

![image](https://github.com/casdoor/casdoor/assets/34130873/c1e32ecc-e108-4603-b975-0787abc3d993|width=100px)

i try debug, and i think model sql search is wrong ( should search without owner ? )

![image](https://github.com/casdoor/casdoor/assets/34130873/a59007bd-a39e-4cb7-a3d6-6f766853200d)

![image](https://github.com/casdoor/casdoor/assets/34130873/731dcd1e-120a-4c2b-8e5d-f91fbf3cf6fa)

owner in sql query is admin, but in database owner is build-in.

if i change owner in database to admin, i can edit policies

![image](https://github.com/casdoor/casdoor/assets/34130873/936b87bf-7f73-4899-8057-80e4be372166)

![image](https://github.com/casdoor/casdoor/assets/34130873/8cf8bad8-a05e-41de-9af0-4ed8148a40c2)

**Comment by hsluoyz** [comment]
@wildwind123 fixed by: https://github.com/casdoor/casdoor/commit/7884e10ca31675a095057f80751821e416fbe141
