### ISSUE TITLE
"groups" claim maybe weird in OIDC with Harbor

### ISSUE THREAD

**Issue by WinterOfBit** [casdoor/casdoor#1983]
Particularly in OIDC auth. 
Configuring OIDC auth for my Harbor:

Casdoor Organinzation: built-in
User Groups: 
- admin
- admin-harbor (sub of admin)

In harbor, I configured "Group Claim Name" to "groups" as mentioned in #1929 and "OIDC Admin Group" to admin-harbor.

However when user registered and logged in he is not admin. And "Groups" page in harbor recognized a "built-in" group. Confusing.

I do noticed that /api/get-account returned "groups" field, in which groups are listed as uuids, but even if I alted "OIDC Admin Group" in harbor to the uuid of any group, nothing happens. Maybe the "groups" claim in fact delivered "build-in", the organization name to harbor is the issue?

PS. weird that [commit mentioned](https://github.com/casdoor/casdoor/issues/1929#issuecomment-1574844214) in #1929 is marked unsuccessful...

**Comment by WinterOfBit** [comment]
Thanks a lot for fixing the group uuid list issue. However my problem with harbor OIDC seems not solved yet and I'm not quite sure if this is about my config error. Here is my harbor config, and casdoor side is same as mentions above:

**Comment by hsluoyz** [comment]
@WinterOfBit please show your result for `get-account` API like:

![image](https://github.com/casdoor/casdoor/assets/3787410/a06110c2-7e7f-4b91-a2a2-3ee9376c807f)

and what do you get and what do you expect in Harbor?

**Comment by WinterOfBit** [comment]
> @WinterOfBit please show your result for `get-account` API like:
> 
> ![image](https://github.com/casdoor/casdoor/assets/3787410/a06110c2-7e7f-4b91-a2a2-3ee9376c807f)
> 
> and what do you get and what do you expect in Harbor?

Seems /api/get-account stills returns group-uuids. Already bumped to v1.342.0 and recreated groups:
![IMG_20230619_102136.jpg](https://github.com/casdoor/casdoor/assets/68735689/5ef7aeae-24e2-4eb8-aa2e-e3a8d9f62187)

![IMG_20230619_102124.jpg](https://github.com/casdoor/casdoor/assets/68735689/01eebce7-7276-4c5a-a1a7-0eeb30cfeeb8)

Do I need to purge my database as well?

I hope harbor to recognize my user group and assign admin correctly. For now harbor claimed organization name "built-in" from "groups" claim

**Comment by hsluoyz** [comment]
@WinterOfBit 

> Do I need to purge my database as well?

Yes, please delete DB

And use latest code: https://github.com/casdoor/casdoor/commit/58aa7dba6a32c840ce21e215250c16f46123a7a1

Then restart Casdoor
