### ISSUE TITLE
Groups cannot be edit in user profile page,the input area is in gray

### ISSUE THREAD

**Issue by masquerade1943** [casdoor/casdoor#1992]
Groups cannot be edit in user profile page,the input area is in gray, when I move mouse on the input the cousor shows not editable, is anything I didn't notice? please help

**Comment by masquerade1943** [comment]
I was running casdoor in docker ,version v1.343.0

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by hsluoyz** [comment]
@masquerade1943 go to your org's edit page (as admin), e.g., https://door.casdoor.com/organizations/built-in

Make sure the "Modify rule" for the `Groups` account item is set correctly

![image](https://github.com/casdoor/casdoor/assets/3787410/1c94e9a8-af8f-4c5e-820b-f35a26de1d21)

**Comment by masquerade1943** [comment]
much thanks!
