### ISSUE TITLE
Panic when set password while create user

### ISSUE THREAD

**Issue by thanhtinhpas1** [casdoor/casdoor#1994]
Steps:
1. Access the user page
2. Click Add
3. Click Modify Password
4. Input password
5. Click Save

Expect:
The password was set success

Actual:
Nothing happened

<img width="1069" alt="image" src="https://github.com/casdoor/casdoor/assets/28798624/e042b129-7e02-47cf-a2f1-bda6699f71a6">

Backend panic:
<img width="568" alt="image" src="https://github.com/casdoor/casdoor/assets/28798624/30d3f4ee-4569-4441-b780-4f2c147cbc19">

**Comment by hsluoyz** [comment]
@thanhtinhpas1 hi, why close?

**Comment by thanhtinhpas1** [comment]
@hsluoyz When i retry, it is success, dont know why. I need time to find exactly what happen.

**Comment by thanhtinhpas1** [comment]
@hsluoyz I think this issue will happen sometimes whenever the backend has not created user yet, and we call set-password, it will lead to panic.

It can happen by many factors, for example:
1. API create user was slow
2. Network connection was unstable
etc

**Comment by hsluoyz** [comment]
@thanhtinhpas1 what version of Casdoor do you use? The latest line 212 cannot crash:

![image](https://github.com/casdoor/casdoor/assets/3787410/ddc0c7de-febf-44a4-a989-fe13ab640cd7)

**Comment by thanhtinhpas1** [comment]
@hsluoyz I'm running in master branch, this line was not crash, it crashed in `organization.go` line **234** when backend tried to get `user.Owner`.

<img width="592" alt="image" src="https://github.com/casdoor/casdoor/assets/28798624/4b91d8c3-fe25-45a6-a4f5-8280dcac3bc6">

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/f3aed0b6a8a2a199acadcff9e9e2e2a7e38c5cbb
