### ISSUE TITLE
[feature] custom claim for custom oauth provider

### ISSUE THREAD

**Issue by WinterOfBit** [casdoor/casdoor#2018]
Currently custom oauth provider CustomUserInfo struct looks like:
![image](https://github.com/casdoor/casdoor/assets/68735689/32af8167-5edc-4828-a2bf-0afa14db7afd)

And doc declares to ask for these fields:
![image](https://github.com/casdoor/casdoor/assets/68735689/9986466b-7d98-44f8-82ac-8eb31a0bf45c)

So firstly, the issue is that the "id" filed has been mapped to "sub" claim,  which is not mentions in doc and **may be not provided at all** (at lest in my provider, and mine provided "uuid"). However meanwhile the userInfo.id is so import for user accont linking. Thats why I got the "Failed to link user account" issue.

And for example my custon provider returns a struct like
```json
{
    "id": "",
    "uuid": "",
    "avatar": "",
    "name": "",
    "email": "",
    "groups": []
}
```

What I'm trying to say is that why not make all claims for custon oauth provider fully configurable? That brings more flexibility and is more compatible and reasonable.

**Comment by hsluoyz** [comment]
@WinterOfBit what oauth provider are you using? Also point to the docs about their custom UserInfo struct

**Comment by WinterOfBit** [comment]
My oauth provider is customized based on Laravel, and mainly referred to impl of gitea. GItea used [Goth](https://github.com/markbates/goth)  
 https://github.com/markbates/goth/blob/492927988958a49753893bce51f9c972dce82929/providers/gitea/gitea.go#L158C6-L158C6  . It works well as out gitea auth source (provider type=gitea) and as our nextcloud oauth provider. 

So Goth used "id" claim, and nextcloud works well but I cannot find docs about which claim it used. Meanwhile I noticed that AWS provided "sub" claim. 

So I'm not quite sure if my provider didn't meed the standards or we could actually map "id" filed to another claim?

**Comment by leo220yuyaodog** [comment]
@WinterOfBit https://github.com/casdoor/casdoor/pull/2029 support a fully configurable of the user mapping, you can determine what field of the user struct from the idp mapping to the casdoor user field. You can have a test and see if there is anything need to improve

**Comment by WinterOfBit** [comment]
Nice! I' test with my provider and my gitea server as another custom provider!

**Comment by WinterOfBit** [comment]
One more issue I believe: 
Currently [custom.go](https://github.com/leo220yuyaodog/casdoor/blob/18bbc6815a140b800d1301c4225ea712790e5bea/idp/custom.go#L111) mapped go from the re-constructed dataMap with key "id" , which is good and implemented the functionality elegantly.
![image](https://github.com/casdoor/casdoor/assets/68735689/cd6273cd-f4db-4592-bf22-72f71e3f1ece)

However it also called `utils.ParseId(interface{})` to …… cast it to string I guess?
![image](https://github.com/casdoor/casdoor/assets/68735689/e3935a0d-60b8-421c-be34-e2aea9a28214)

But it missed a case that it is string already. So if the input is string, unluckily this fuction fails, which looks quite weird..... e.g.:
![image](https://github.com/casdoor/casdoor/assets/68735689/ee0ec713-7e08-44bb-a75d-5b00a68ff0e2)
