### ISSUE TITLE
[question] Casbin group policy with domains

### ISSUE THREAD

**Issue by hound672** [casdoor/casdoor#2020]
Hello.
We'd like to implement groups management in our application which similar to Gitlab groups.
There are users, groups and links between them.

You can specify role for user in the group.
For example, user_1 belongs to group_1 with role admin,
user_2 belongs to group_2 with role admin and group_1 with role auditor.

For now, we're using RBAC with domains model.

Model:
```
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act
```

Policy and role definition we make with casbin editor:
```
p, admin, group_1, view_report, read
p, admin, group_1, create_report, read
p, admin, group_1, share_report, read
p, auditor, group_1, view_report, read

p, admin, group_2, view_report, read
p, admin, group_2, create_report, read
p, admin, group_2, share_report, read
p, auditor, group_2, view_report, read

g, user_1, admin, group_1
g, user_2, auditor, group_1
g, user_3, auditor, group_1

g, user_1, auditor, group_2
g, user_2, admin, group_2
```

Enforse works as expected:

```
user_1, group_1, view_report, read // true since user_1 belongs to domain group_1 with admin role (and admin role has view_report, read)
user_2, group_1, view_report, read // true as well
user_1, group_1, create_report, read // true 
user_2, group_1, create_report, read // false since there user_2 belongs as auditor to domain group_1 (add auditor doesn't have create_report, read )
```

And for `group_2`:
```
user_1, group_2, view_report, read // true
user_2, group_2, view_report, read // true as well
user_1, group_2, create_report, read // false 
user_2, group_2, create_report, read // true
```

Here is the link to casbin editor with this policy: https://editor.casbin.org/#ATL44EZVS

How we can mapping this policy rules to casdoor?
Should we duplicate each role for every domain? And after that we duplicate each permission for every domain's role, do we?

Otherwise it doesn't work as expected.
For example:
1. I create two roles: admin, auditor by casdoor and pass our domains (group_1, group_2)
2. I create three permissions: view_report, create_report, share_report. Link them to roles.

After that we have in the `permission rule` table:
```
ptype,v0,v1,v2,v3,v4,v5
p,built-in/admin,group_1,view_report,"","",built-in/share_report
p,built-in/admin,group_1,create_report,"","",built-in/view_report
p,built-in/auditor,group_1,view_report,"","",built-in/view_report
p,built-in/admin,group_1,create_report,"","",built-in/view_report
g,built-in/hound,admin,group_1,"","",""
g,built-in/vbliznetsov,auditor,group_1,"","",""
```

There is no any information about our domains.

One way which found is to duplicate roles and permissions:
1. For each domain create set of roles: `group_1_admin`, `group_1_auditor`, `group_2_admin` etc
And assign user to specified role: from below example it'd be `user_1` assigned to role `group_1_admin` role, `user_2` assigned to role `group_1_auditor` etc

2. For each role create set of permissions as well: `group_1_view_report`, `group_2_create_report` etc 
And assing domain in permission: `group_2_create_report` assigned to `group_2` subdomain etc

It works but there is too much duplicates.

Any suggestions?

**Comment by hound672** [comment]
Recently groups support was added.
What do you think about integrate casbin policies and groups?
For example, we can add user to group with specified role and then `casdoor` is able to add `group policy`.

**Comment by thanhtinhpas1** [comment]
> Recently groups support was added. What do you think about integrate casbin policies and groups? For example, we can add user to group with specified role and then `casdoor` is able to add `group policy`.

@hsluoyz  I think it is a good idea. Pls let us know your idea so we can pair work about it.

**Comment by ISulimanov** [comment]
Plus one for this feature. 
From our point of view, one the most perspective side of Casdoor is seamless integration with Casbin (that looks like extremely powerful, but still little bit hard to adopt). 

In this case Casdoor is like a bridge that join easy-to-use approach of Casdoor with power of Casbin.   

It will be perfect if community will help to add support for such as use-case.

**Comment by dvonta** [comment]
Hello folks, has anyone worked on this yet?

**Comment by ISulimanov** [comment]
> Hello folks, has anyone worked on this yet?

From our side - no, 
We have some idea - like add `roleId` to `user_group_relation`  that will be translated to something like this

`g, user_1, admin, group_1`


but so far looks forward to @hsluoyz and @leo220yuyaodog.

**Comment by hound672** [comment]
@hsluoyz another way is to implement API for managing cabin's rules directly in casdoor.
In that case we are able to manage casbin rules by ourself.
What do you think?

**Comment by leo220yuyaodog** [comment]
Hi, folks, I'm working on the issue. 
We plan to use Casbin to manage the user permisson in Casdoor. We all know that Casdoor does not integrate Casbin completely. Now that we have groups, we can use RBAC with domain to manage the permissions of Casdoor users. However, existing permissions are not easily supported directly.  In order for everyone to easily configure the user rights of Casdoor without breaking the flexibility of the existing Casbin API. I'm going to change the structure to the following picture.
![image](https://github.com/casdoor/casdoor/assets/71440988/aac2e0d0-469b-4734-939c-ba8de81c1b17)

What do you think about? Any suggestions are welcome.
