### ISSUE TITLE
[bug] Org admin may get info about other orgs 

### ISSUE THREAD

**Issue by ISulimanov** [casdoor/casdoor#2022]
Steps: 

- Create new organization, let's call it F5
- Add new user to F5 as org admin 
- Make login as F5 org admin
- Paste https://casdoor-host/api/get-organizations?owner=admin to new browser tab

Expected result: 

- Receive only own organization

Actual result:

 - Receive all organizations

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/55784c68a3dc8397be5e55b888a9d7e163e69244
