### ISSUE TITLE
Cant getting token based on the username and password.

### ISSUE THREAD

**Issue by nihalgurjar47** [casdoor/casdoor#2038]
I read this document of yours, located at https://github.com/casdoor/casdoor-python-sdk. In this document, you have implemented a way to obtain a token based on a username and password.
However, I am unable to obtain the token.
I am encountering an error. Please refer to the screenshot below for further details.
![Screenshot from 2023-07-04 18-34-14](https://github.com/casdoor/casdoor/assets/104414738/670ad094-abad-431f-803b-18b1f6289012)

**Comment by hsluoyz** [comment]
@nihalgurjar47 add `password` to your app's `grant types`: https://door.casdoor.com/applications/casbin/app-example

![image](https://github.com/casdoor/casdoor/assets/3787410/059c4a53-9e7d-42f7-9e92-591bf2e0d067)
