### ISSUE TITLE
Lark provider error: "Provider login via Lark (Feishu) prompts an illegal request, please contact the application developer."

### ISSUE THREAD

**Issue by Phoebus888** [casdoor/casdoor#2052]
![image](https://github.com/casdoor/casdoor/assets/45359605/9d08cd16-dbe8-44eb-8937-bcccfe216c23)

This problem also appears on the official demo. How can it be configured and resolved?

https://door.casdoor.com/login

**Comment by Phoebus888** [comment]
I have configured the redirect url for this flying book, but I still report this error. Is this a system problem?

**Comment by Chinoholo0807** [comment]
> I have configured the redirect url for this flying book, but I still report this error. Is this a system problem?

Please make sure you have added the corresponding redirect URL in your lark application, such as `https://door.casdoor.com/callback`.
