### ISSUE TITLE
[bug]  gomail: invalid address "\"email\" <>": mail: invalid string

### ISSUE THREAD

**Issue by revitteth** [casdoor/casdoor#2057]
When trying to test the mail provider I can't get past this issue. 

I'm running locally in docker, and the SMTP connection succeeds, however on trying to send a test mail, this error is returned:

`gomail: invalid address "\"email\" <>": mail: invalid string`

**Comment by hsluoyz** [comment]
@revitteth what Email service provider do you use?

also plz provide a demo video for your Email provider like: https://door.casdoor.com/providers/admin/provider_email_sendgrid

![image](https://github.com/casdoor/casdoor/assets/3787410/cca3c0dd-2635-4bc7-8ab8-848ac800e98b)

**Comment by Chinoholo0807** [comment]
> 



> Additionally: `gomailfalse could not send email 1false gomailfalse invalid address "\"raf\" <>"false mailfalse invalid string` from the signup/login. Where raf is my application name.
> 
> Perhaps this is just misconfiguration but there is no mention of the configuration item driving this in the docs. I can dig in the code and make assumptions but might be easier to fix with a sensible default. If someone can point me in the right direction I'm happy to PR a change.

If the SMTP connection succeeds, it indicates that there are no issues with the `Host` and `Port` configurations of your email provider. Based on the error message you provided, it suggests that there might be an issue with the `Test Email` . Please make sure to enter a valid email address, such as `xxx@foxmail.com`. Could you plz share your email provider configuration?

**Comment by revitteth** [comment]
Hi, this is using SMTP to a mailhog container running as part of the same system. From a go program I can send over emails to this mailhog instance - so the issue seems to be with the sending of the test mail from casdoor specifically. It looks like the way the fromAddress is generated in the case of a missing one would not be a valid email, but I'm unsure.

**Comment by Chinoholo0807** [comment]
> Hi, this is using SMTP to a mailhog container running as part of the same system. From a go program I can send over emails to this mailhog instance - so the issue seems to be with the sending of the test mail from casdoor specifically. It looks like the way the fromAddress is generated in the case of a missing one would not be a valid email, but I'm unsure.

@revitteth I have deployed Casdoor and MailHog using docker on the same host, and I have successfully tested sending test emails. Following is my Casdoor Email Provider configure, could you plz share your email provider configuration or a demo video?
![image](https://github.com/casdoor/casdoor/assets/54203997/50c2e2f9-9289-4fdb-a785-153db2c159f7)
![image](https://github.com/casdoor/casdoor/assets/54203997/666bdc26-fa37-452f-99be-b52415f15094)
![image](https://github.com/casdoor/casdoor/assets/54203997/8283f8ac-4ddf-4c03-a65e-b52c14d82921)
