### ISSUE TITLE
deploy-cdn  error

### ISSUE THREAD

**Issue by G-lin** [casdoor/casdoor#2058]
when i try to run "go test" as "https://casdoor.org/docs/deployment/deploy-cdn" 
An error has occurred ：“./deploy_test.go:28:21: assignment mismatch: 1 variable but object.GetProvider returns 2 values”

My configuration is shown in the following figure
<img width="867" alt="image" src="https://github.com/casdoor/casdoor/assets/7637270/c464122d-0db1-415d-9857-4c22a5f9a7f5">

**Comment by hsluoyz** [comment]
@imp2002 can you make a quick PR to fix it?

**Comment by G-lin** [comment]
@imp2002
After modifying according to your suggestion and executing again, another error was reported as shown in the following figure
<img width="834" alt="image" src="https://github.com/casdoor/casdoor/assets/7637270/3d151136-76ff-4098-973e-1b19568a4782"> @hsluoyz

**Comment by hsluoyz** [comment]
@G-lin fixed by: https://github.com/casdoor/casdoor/commit/a193ceb33d9605d72361b7ee238ff1b68e7fceec
