### ISSUE TITLE
Error reported when user uploads avatar to minio (https)

### ISSUE THREAD

**Issue by wuguaner** [casdoor/casdoor#2060]
my casdoor using https，When users upload their avatars to minio (https)
RequestError: send request failed caused by: http: server gave HTTP response to HTTPS client

**Comment by hsluoyz** [comment]
@wuguaner what Casdoor version and Minio version do you use? Provide a demo video

**Comment by wuguaner** [comment]
casdoor version: v1.351.0
minio version: 2021-02-14T04:01:33Z
when casdoor use http, upload avatars to minio is ok
![image](https://github.com/casdoor/casdoor/assets/34933361/ebe32414-4c9d-47f3-bd1e-3b318b18aff3)

**Comment by Chinoholo0807** [comment]
> casdoor version: v1.351.0 minio version: 2021-02-14T04:01:33Z when casdoor use http, upload avatars to minio is ok ![image](https://user-images.githubusercontent.com/34933361/252884357-ebe32414-4c9d-47f3-bd1e-3b318b18aff3.png)

@wuguaner  Please make sure that your MinIO service has TLS (Transport Layer Security) enabled. You can refer to this document  https://min.io/docs/minio/linux/operations/network-encryption.html

**Comment by hsluoyz** [comment]
@wuguaner plz:

1. Provide your provider info, like screenshot of https://door.casdoor.com/providers/admin/provider_storage_aws_s3
2. Is Casdoor HTTP or HTTPS?
3. Is Minio HTTP or HTTPS?

**Comment by wuguaner** [comment]
![image](https://github.com/casdoor/casdoor/assets/34933361/5968fd53-97f2-4f21-9303-8cde575c1869)
casdoor using https
mino using https

**Comment by wuguaner** [comment]
casdoor version v1.363.0
when user uploads avatar to minio (https) 
Still reporting an error：
RequestError: send request failed caused by: Put "https://test-minio.kxgcc.com:31149/casdoor/avatar/lianjian/wyq.png": http: server gave HTTP response to HTTPS client

**Comment by hsluoyz** [comment]
@wuguaner it's your Minio server's issue. The URL is HTTPS but the response is HTTP.

**Comment by wuguaner** [comment]
the url is ok?
![image](https://github.com/casdoor/casdoor/assets/34933361/39b0b907-6efd-4817-aab3-097f06658e14)

**Comment by hsluoyz** [comment]
@wuguaner browser open won't work. Can you try `PUT` instead of `GET` via tools like Postman?

**Comment by wuguaner** [comment]
Put request, can be uploaded
![Uploading image.png…]()

**Comment by hsluoyz** [comment]
@wuguaner what's your QQ?

**Comment by UsherFall** [comment]
> ![image](https://user-images.githubusercontent.com/34933361/253133876-5968fd53-97f2-4f21-9303-8cde575c1869.png) casdoor using https mino using https

Have you changed the endpont configuration in the provider? Try changing it to the following
<img width="451" alt="image" src="https://github.com/casdoor/casdoor/assets/98513748/5a507a4d-5662-42c9-a47c-7dfa24913520">

**Comment by wuguaner** [comment]
QQ: 3579575615
![image](https://github.com/casdoor/casdoor/assets/34933361/537cafdf-35ab-4a1a-b09f-0780e2e4027b)
changed the endpont configuration in the provider， Still the same mistake

**Comment by AloneFire** [comment]
Same problem, any new progress? 同样的问题，有什么新进展吗？

**Comment by hsluoyz** [comment]
Cannot reproduce this issue. Closed here
