### ISSUE TITLE
different variants to pass ldap id in different API requests

### ISSUE THREAD

**Issue by yamaritta** [casdoor/casdoor#2062]
1. get-ldap  and  get-ldap-users expects concatenated owner and ldap`s id
api/get-ldap-users?id=test/8349f133-8075-447f-9bf0-beb8d060409f

2. sync-ldap-users expect separately owner and ldap`s id
api/sync-ldap-users?owner=test&ldapId=8349f133-8075-447f-9bf0-beb8d060409f

Сould you pass owner and id separately everywhere or  only id?

**Comment by hsluoyz** [comment]
@yamaritta use `id` now: https://github.com/casdoor/casdoor/commit/666ff48837016de9c47434dec1aeb8ddbe509fc9
