### ISSUE TITLE
sensitive data in get ldap

### ISSUE THREAD

**Issue by yamaritta** [casdoor/casdoor#2063]
get-ldap returned admin password 
![image](https://github.com/casdoor/casdoor/assets/41572091/48f03d6f-0391-45dd-be7f-38f91924d225)
In another requests passwords and client secrets are replaced with ***
Please fix it

**Comment by hsluoyz** [comment]
@yamaritta fixed by: https://github.com/casdoor/casdoor/commit/438c999e119722b480b331436f136ac561f26be9
