### ISSUE TITLE
 compliance rest standards

### ISSUE THREAD

**Issue by yamaritta** [casdoor/casdoor#2065]
Documentation says:
_The Go backend only exposes its functionality via RESTful API._

But some requests don't meet rest API standards. For example many delete request expects full deleted object in body and many get requests expects id in query not uri.

By standard a resource has an identifier, which is a URI that uniquely identifies that resource.
For example, if your API stored animals, a resource name might be “animals.” The path to access that resource might be  /api/animals . The resource would then be combined with HTTP methods like so:

 GET /api/animals : retrieve a list of animals
 POST /api/animals : add a new animal
 GET /api/animals/dog : retrieve a single animal by ID
 PUT /api/animals/dog : update a single animal by ID
 DELETE /api/animals/dog : delete an animal by ID

**Comment by hsluoyz** [comment]
@yamaritta it's the generalized "RESTful" API, not the strict RESTful definition
