### ISSUE TITLE
Get *** of Access secret when update api key

### ISSUE THREAD

**Issue by HanadaLee** [casdoor/casdoor#2071]
One month ago, I found that a new function is released https://github.com/casdoor/casdoor/pull/1971.
I plan to use it as my API Gateway auth key. But when I generate a new key, I get *** in Access secret area

**Comment by HanadaLee** [comment]
![https://static.hanada.info//memo/2023/07/12/1689172734/d2c6dc81-dc08-4192-8fd7-c82b8b0b051b.png]

**Comment by hsluoyz** [comment]
@HanadaLee how do you authenticate with the API Gateway? (HTTP bear token or parameter format?)

**Comment by HanadaLee** [comment]
I plan to read this value directly from the backend mysql database, and use it to build the authentication module of my own API gateway system, so casdoor is only used as the storage medium of the apikey.

Now the Access secret is not displayed when it is generated, which is unreasonable. And the demo video in the pull request shows that the Access secret will be displayed when the api key is generated, is there any change that breaks this?

**Comment by hsluoyz** [comment]
@HanadaLee `AccessSecret` is similar as user's `Password`, so it's masked before leaving the backend. It's good for security.

https://github.com/casdoor/casdoor/blob/0a0c1b47881addb25778df8ff5e43a12a90f18b2/object/user.go#L421-L450

I need to know how you authenticate with the API Gateway, to see if we can show its value under some conditions

**Comment by HanadaLee** [comment]
Like any IAM program, the user must obtain his own key and secret when generating the APIKEY before using it to call the API. So the user must at least see the plaintext secret when it is generated, otherwise he has nowhere to get the secret. I think it can be considered to display the secret only when generating or updating the APIKEY, and only display it when viewing ***

**Comment by hsluoyz** [comment]
@HanadaLee fixed by: https://github.com/casdoor/casdoor/commit/38f031bc86a4304e6e62b8f9856b0a23da00f246
