### ISSUE TITLE
deploy-cdn error

### ISSUE THREAD

**Issue by G-lin** [casdoor/casdoor#2072]
after i run "go test" as "https://casdoor.org/docs/deployment/deploy-cdn"

The path uploaded to Alibaba Cloud Cloud Object storage has an additional "/static/" path, and the reference to the web page does not include the "/static/" path.

This needs to be modified：
<img width="776" alt="image" src="https://github.com/casdoor/casdoor/assets/7637270/2f09aa7a-bc16-444d-bd96-0c14e7a53595">

Change it to this way and it will run normally：
<img width="748" alt="image" src="https://github.com/casdoor/casdoor/assets/7637270/50b147c1-c623-4bd0-8ac5-cdc176a51bbe">

**Comment by G-lin** [comment]
<img width="776" alt="image" src="https://github.com/casdoor/casdoor/assets/7637270/2f09aa7a-bc16-444d-bd96-0c14e7a53595">

**Comment by hsluoyz** [comment]
@G-lin in our demo site, it has the "static" path in CDN: https://door.casdoor.com/login

```html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>
        <meta name="theme-color" content="#000000"/>
        <meta name="description" content="Casdoor - An Identity and Access Management (IAM) / Single-Sign-On (SSO) platform with web UI supporting OAuth 2.0, OIDC, SAML and CAS"/>
        <link rel="apple-touch-icon" href="https://cdn.casbin.org/img/favicon.png"/>
        <link rel="manifest" href="https://cdn.casbin.org/site/casdoor/manifest.json"/>
        <title>Casdoor</title>
        <script defer="defer" src="https://cdn.casbin.com/static/js/main.7d1cc7ab.js"></script>
        <link href="https://cdn.casbin.com/static/css/main.1013e3f2.css" rel="stylesheet">
    </head>
    <body>
        <noscript>You need to enable JavaScript to run this app.</noscript>
        <div id="root"></div>
    </body>
</html>
```

You can remove or modify it based on your need. This code example won't be changed.
