### ISSUE TITLE
add new parameters to ldap users

### ISSUE THREAD

**Issue by yamaritta** [casdoor/casdoor#2073]
Please, extend model in request get-ldap -users with new parameters: userPrincipalName, memberOf 
 
These parameters are very useful for ldap integration

**Comment by hsluoyz** [comment]
@yamaritta hi, I saw you have raised a lot of LDAP-related issues. You are more familiar with LDAP than me. Would you like to create PRs to fix these LDAP issues? It would be much faster I think than I learn LDAP stuff and make PR.

**Comment by yamaritta** [comment]
ok

**Comment by hsluoyz** [comment]
can you make a PR to support it?

**Comment by yamaritta** [comment]
yes, we will soon

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/a1806439f8ea144b2db4ea1179e2e88f43a63e22
