### ISSUE TITLE
Custom HTTP or Websocket Service as SMS provider

### ISSUE THREAD

**Issue by consam** [casdoor/casdoor#2075]
Hello Casdoor team.
Is possible add Custom HTTP or Websocket Service as SMS provider?

**Comment by hsluoyz** [comment]
@consam it can be added to the core service, can you make a PR?

**Comment by hsluoyz** [comment]
@Baihhh

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/33a922f026450dd04e6b7b9364676f981a0fa886

**Comment by adbrv** [comment]
Hi Casdoor team, there is no custom sms provider in panel, release v1.459
