### ISSUE TITLE
BUG: Panic in func (c *ApiController) GetUser() if no user exist in DB

### ISSUE THREAD

**Issue by aegoroff** [casdoor/casdoor#2079]
Method func (c *ApiController) GetUser() has following implementation (extract):
```go
	var user *object.User
	switch {
	case email != "":
		user, err = object.GetUserByEmail(owner, email)
	case phone != "":
		user, err = object.GetUserByPhone(owner, phone)
	case userId != "":
		user = userFromUserId
	default:
		user, err = object.GetUser(id)
	}

	if err != nil {
		c.ResponseError(err.Error())
		return
	}

	user.MultiFactorAuths = object.GetAllMfaProps(user, true)
```
if code excecution use default branch of switch (i.e. user, err = object.GetUser(id)) panic will occur in line user.MultiFactorAuths = object.GetAllMfaProps(user, true) if no user exist in db

The real reason of this problem is in function func getUser(owner string, name string) (*User, error) from object/user.go
it's implementation  

```go
        func getUser(owner string, name string) (*User, error) {
	if owner == "" || name == "" {
		return nil, nil
	}

	user := User{Owner: owner, Name: name}
	existed, err := adapter.Engine.Get(&user)
	if err != nil {
		return nil, err
	}

	if existed {
		return &user, nil
	} else {
		return nil, nil
	}
}
```
so in case of no user found (existed will be false) nil error and nil user will be returned so it'll cause abovementioned problem. I'm not sure whether an error should be returned in this case or caller should always check user result not to be nil - it's your decision.

**Comment by ISulimanov** [comment]
> I'm not sure whether an error should be returned in this case or caller should always check user result not to be nil - it's your decision.

404 could be reasonable if user does not exist by id 
same for other entities

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/19ab168b1288772836570b2a0f92edc09c936338
