### ISSUE TITLE
Theme Primary color can't save

### ISSUE THREAD

**Issue by G-lin** [casdoor/casdoor#2081]
After I save it, click 'Edit' or 'Default Settings'

<img width="996" alt="image" src="https://github.com/casdoor/casdoor/assets/7637270/2e62209a-4c0e-4e3c-bb5b-7f160d79612e">

**Comment by leo220yuyaodog** [comment]
@G-lin The theme takes effect immediately only when the administrator changes the theme of the organization to which the administrator belongs. If the global administrator changes the theme of another organization, the theme does not take effect on the current management page.

**Comment by AloneFire** [comment]
Same problem, when the page is modified'colorPrimary ', the page is refreshed and displayed as the default color. I guess it should be a problem with the front-end components, not showing the configured value.

**Comment by hsluoyz** [comment]
@AloneFire where did you configure theme and what UI do you expect to change? Maybe you have configured the wrong place. Can you share a video?

**Comment by AloneFire** [comment]
> @AloneFire where did you configure theme and what UI do you expect to change? Maybe you have configured the wrong place. Can you share a video? 您在哪里配置主题以及您希望更改哪些 UI？可能是你配置错了地方。你能分享一个视频吗？


https://github.com/casdoor/casdoor/assets/20330223/ea72ff0b-8317-4da6-885c-5d086525b482
