### ISSUE TITLE
Add .NET Maui App OpenIDConnect example 

### ISSUE THREAD

**Issue by RVShershnev** [casdoor/casdoor#2083]
Dear Casdoor Team,

I am faced with the problem of connecting a MAUI application to the Casdoor. 
I think my [example](https://github.com/RVShershnev/casdoor-dotnet-maui-example) will be useful for .NET developers.

The example can be added to the documentation.

**Comment by hsluoyz** [comment]
@RVShershnev what's the problem you mentioned? Or you just want to share a working example?

**Comment by RVShershnev** [comment]
@hsluoyz  yes, I want to share a working example.

**Comment by hsluoyz** [comment]
@RVShershnev great. Can you add this example here? after: https://casdoor.org/docs/category/desktop-sdks

![image](https://github.com/casdoor/casdoor/assets/3787410/dc275f3b-be91-444b-8ad3-c92c383dfc7e)

by making PR to: https://github.com/casdoor/casdoor-website
