### ISSUE TITLE
Implementation of using ca certificate check in external ssl connection (ldap, openId, saml) 

### ISSUE THREAD

**Issue by yamaritta** [casdoor/casdoor#2087]
Hello!  We have created a pull request with an implementation of using the ca certificate in ssl ldap. 
https://github.com/casdoor/casdoor/pull/2069
But you closed it.  I could explain our decision.  I understand that you don't like the new certificate scope.  But when checking the ssl connection, additional parameters, such as a private key, the signature algorithm are not needed.  If we use the scope of the certificate for ssl verification, we will force  user to set unused fields and confuse him.  Please, help me understand how to rewrite pull request so that you accept it.

**Comment by hsluoyz** [comment]
@yamaritta you can hide some unused fields, or even change the text labels if needed, see provider: https://github.com/casdoor/casdoor/blob/master/web/src/ProviderEditPage.js , the principle is to re-use existing data fields and code as much as possible, reduce maintain burden

**Comment by hsluoyz** [comment]
Closed as stale
