### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by yamaritta** [casdoor/casdoor#2088]
Hi, please, create Contributing guidelines. 
Guidelines help your project contributors do good work
There are examples:
https://github.com/dotnet/runtime/blob/main/CONTRIBUTING.md
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors
https://github.com/google/go-github/blob/master/CONTRIBUTING.md

**Comment by hsluoyz** [comment]
@yamaritta see: https://casdoor.org/docs/contributing
