### ISSUE TITLE
BUG: CreateTables will panic if using PostgreSQL

### ISSUE THREAD

**Issue by zedzhu** [casdoor/casdoor#2105]
I use PostgreSQL and find casdoor  has a panic error during startup since v1.334.0:

goroutine 1 [running]:
github.com/casdoor/casdoor/object.CreateTables(0x58?)
	/go/src/casdoor/object/adapter.go:60 +0x4c
main.main()
	/go/src/casdoor/main.go:43 +0x3e
panic: pq: syntax error at or near "NOT"

And I see this code:
``` golang
func (a *Adapter) CreateDatabase() error {
	engine, err := xorm.NewEngine(a.driverName, a.dataSourceName)
	if err != nil {
		return err
	}
	defer engine.Close()

	_, err = engine.Exec(fmt.Sprintf("CREATE DATABASE IF NOT EXISTS %s default charset utf8mb4 COLLATE utf8mb4_general_ci", a.dbName))
	return err
}
```
Maybe the  reason of the error is PostgreSQL doesn't support the “IF NOT EXISTS” option for the CREATE DATABASE command.

**Comment by hsluoyz** [comment]
@zedzhu fixed by: https://github.com/casdoor/casdoor/commit/fc9528be43290c8d3c2f8cb4f0f63d17143952ac
