### ISSUE TITLE
Payment step for pricing 

### ISSUE THREAD

**Issue by Regin13** [casdoor/casdoor#2108]
Hi Casdoor team!
Thanks for usefull product. 
Could you please add configurable payment step for pricing page?
https://casdoor.org/docs/pricing/overview
We would like to use Stripe for example.
Our flow is Pricing page => payment => finish sign up.
Cheers.

**Comment by Regin13** [comment]
maybe its alrady possible with https://casdoor.org/docs/products/payment
but i cant figer out how

**Comment by hsluoyz** [comment]
@Regin13 hi, can you provide more details?

**Comment by Regin13** [comment]
Hi! 
Btw thanks for dashboard!
So as a option if no trial for plan - show window where i should make payment via debit card and only after succes payment user will be redirected back and proceed registration flow.
