### ISSUE TITLE
get-resource api fails due to authz filter middleware and code logic.

### ISSUE THREAD

**Issue by WinterOfBit** [casdoor/casdoor#2114]
Encountered working on https://github.com/casbin/casibase/pull/594

Currently `/api/get-resource` is totally unavailable.

### Latest commit, try: 
- /api/get-resource?id=/resource/built-in/app-built-in/test
- /api/get-resource?id=/built-in/app-built-in/test
- /api/get-resource?id=built-in/app-built-in/test

All fail with error: `GetOwnerAndNameFromId() error` . Stack trace to `casdoor/routers/authz_filter.go:72`.
This fails due to [authz_filter.go](https://github.com/casdoor/casdoor/blob/a6f803aff1e634ae92b669975baa366a6b3b39c8/routers/authz_filter.go#L72) middleware calls [string.go#GetOwnerAndNameFromId()](https://github.com/casdoor/casdoor/blob/a6f803aff1e634ae92b669975baa366a6b3b39c8/util/string.go#L91) ahead to check the `id` query param regardless of the api definition and `GetOwnerAndNameFromId()` do fail when the id does not match the format of `{owner}/{name}` (containing one `/`). And this should be unsuitable for resource related id/name format. (Moreover if trim the `id` param to shorter like `app-built-in/test` it's even less likely to get the correct response)

### My workaround: replace `id` query param to `key` in [controllers/resource.go](https://github.com/casdoor/casdoor/blob/a6f803aff1e634ae92b669975baa366a6b3b39c8/controllers/resource.go#L98C27-L98C27)
Luckily without `id` param I passed through the `authz` middleware and unluckily the code logic blocks this api now. 
Generally said `/api/get-resource` now pass the `key` param (formerly`id`) to `GetOwnerAndNameFromIdNoCheck()` function to split it to a `owner` and a `name` field. Then use the `owner` and `name` to query in the db. Doing this on a single `key` (or `id`) param causes I had to call `/api/get-resource?key=built-in//resource/built-in/app-built-in/test` to get the right resouce and other `key` formats still fail. Passing key `built-in//resource/built-in/app-built-in/test` does not seem to be any valid or Intuitive key format.

#### Generally said. `/api/get-reource` currently fails due to auth filter middleware force-checking `id` query param. Altering `id` query param to `key` (or any other than `id`) does not fix because there are some code logic issues handling this param.

**Comment by WinterOfBit** [comment]
same issue also on `/api/update-resource`

**Comment by hsluoyz** [comment]
@WinterOfBit can you disable `authz filter` first and see which id will work?

**Comment by WinterOfBit** [comment]
> @WinterOfBit can you disable `authz filter` first and see which id will work?

@hsluoyz same result as altering `id` query param with `key`. only `built-in//resource/built-in/app-built-in/test` would work. Otherwise return "null"

**Comment by hsluoyz** [comment]
@WinterOfBit fixed by: https://github.com/casdoor/casdoor/commit/09f40bb5ce0c89f79a0cdd648a8ee94edd94ee59

You can now use `http://localhost:8000/api/get-resource?id=built-in/casdoor/avatar/built-in/admin.png`
