### ISSUE TITLE
How to delete session?

### ISSUE THREAD

**Issue by pyxiscloud** [casdoor/casdoor#2116]
I have web application , where `users` can login
Webapp open new tab and login with casdoor, if `user` check "`Auto sign`" then this browser tab save cookie, and even if this user logout from Webapp, another user can automatically login without password.

Example:
1. Login to webapp (auto sign enabled)
2. change password
3. logout
4. open Webapp and then we got auto login even without password.

How can I delete casdoor session?

**Comment by hsluoyz** [comment]
@pyxiscloud 

1. Disable Casdoor's session by disabling `Signin session` in application edit page: https://door.casdoor.com/applications/casbin/app-vue-python-example

![image](https://github.com/casdoor/casdoor/assets/3787410/6e3b1226-4048-4962-b9b8-ac60f6c4c3fe)

2. Admin actively kicks off a user in sessions page: https://door.casdoor.com/sessions

![image](https://github.com/casdoor/casdoor/assets/3787410/2c17d215-a67f-4b6d-8065-be7717fa3d2a)

**Comment by pyxiscloud** [comment]
This switch not works? (same result)
Session is stored.
I noticed, that this problem is appeared only if Forgoten password changed.

**Comment by hsluoyz** [comment]
@pyxiscloud demo video to show it doesn't work

**Comment by pyxiscloud** [comment]
Here is 2 videos:
1 - it's ok: [link](https://drive.google.com/file/d/1EcxOKZeH7PwfXLF8_ZJ6EWSUofXgYxfg/view?usp=drive_link)
- login
- delete saved tokens 
- reload web app page
- after casdoor page opened, I can enter any login / password


2 - not ok, but I use forgot password [link](https://drive.google.com/file/d/1HaJ1lzz6jbwSoPFcML84t4nckb8OCj3u/view?usp=sharing)
- in web app page login, then on casdoor page "Forgot password" and change it
- after password changed, it open login page but it already logged in (it shows after reload casdoor page)
- when I try to login from web app, it opens casdoor, but it's already logged in!

Think there some error in frontend on "Forgot password"?

**Comment by leo220yuyaodog** [comment]
@pyxiscloud Hello, about the forgot password feature,  it has be refactor in pr https://github.com/casdoor/casdoor/commit/b99a0c3ca2e5486340ef3debe3cee2fae420f73a#diff-4af81d69166aa81a4af07af8d3e0ee9dde199e6469f483b4c4d74ec00338b2c8L129 

You can use the new version to fix the problem.

**Comment by pyxiscloud** [comment]
@leo220yuyaodog , Hello , I use latest casdoor version (1.370). That PR is from april 2023.

**Comment by pyxiscloud** [comment]
@hsluoyz can you check video, please?

**Comment by leo220yuyaodog** [comment]
> @leo220yuyaodog , Hello , I use latest casdoor version (1.370). That PR is from april 2023.

Please check your code, it seems that there is a problem with the release or for unknown reasons, you did not download the correct code. To be sure, the current Forget password feature is exactly what you expected, and in the previous version, it did work as you demonstrated in your video.

**Comment by hsluoyz** [comment]
@pyxiscloud check the version in sysinfo: https://door.casdoor.com/sysinfo

![image](https://github.com/casdoor/casdoor/assets/3787410/9ab2a3f7-dd00-453b-8133-23d8bcc599df)

**Comment by pyxiscloud** [comment]
@hsluoyz 
I have 1.372
![image](https://github.com/casdoor/casdoor/assets/14041313/2cb94b74-349e-44f9-9d1f-5c3af6feca10)
Runned it from docker.

But still have the same Forger password feature

**Comment by pyxiscloud** [comment]
@hsluoyz I've check it without docker and all works fine! (manually build and run on server)
Looks like docker image contains old frontend version
Thank you
