### ISSUE TITLE
How can I default deny all permissions?

### ISSUE THREAD

**Issue by aosolao** [casdoor/casdoor#2119]
![Snipaste_2023-07-24_11-41-37](https://github.com/casdoor/casdoor/assets/30789071/6feda618-4eec-4b24-809b-9e7794d4cb84)
![Snipaste_2023-07-24_10-37-00](https://github.com/casdoor/casdoor/assets/30789071/f3db25a0-424c-43f7-81bf-8f95cddabfec)

I want to default deny all application permissions when a role has no permissions.
When I tested it with the Casbin editor, there was no problem.
However, when I used it in Casdoor, I found that the result was not as expected. When the role has no permissions configured, it allows all permissions.
Could you tell me if this is a configuration error or a bug?
I am using the Priority model:

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = priority(p.eft) || deny

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

version: [v1.370.0](https://github.com/casdoor/casdoor/releases/tag/v1.370.0)

**Comment by leo220yuyaodog** [comment]
@aosolao Can you provide you permission list page in Casdoor and the details about what scenario you use the permissons?  As this issue https://github.com/casdoor/casdoor/issues/1483 says, if you add multiple permissions, as long as one of them is met, it will pass for user login.

**Comment by aosolao** [comment]
> @aosolao Can you provide you permission list page in Casdoor and the details about what scenario you use the permissons? As this issue #1483 says, if you add multiple permissions, as long as one of them is met, it will pass for user login.

My Casdoor is a completely new installed environment, and I'm currently experimenting with features, so I don't have a fixed configuration yet.
Several applications are set up in casdoor, zentao, Jenkins, and so on
In my tests, I found that users can log in to all applications when the permission list is empty.
I can not login to an application until I add a permission rule that deny the role login to that application.

**Comment by hsluoyz** [comment]
@aosolao 

1. Show your `permissions` result in JSON from: https://door.casdoor.com/api/get-permissions?owner=&p=1&pageSize=10&field=&value=&sortField=&sortOrder=

Like:

```json
{
  "status": "ok",
  "msg": "",
  "sub": "",
  "name": "",
  "data": [
    {
      "owner": "casbin",
      "name": "permission-casibase-admin",
      "createdTime": "2023-06-23T01:15:09+08:00",
      "displayName": "Casibase Admin Permission",
      "description": "",
      "users": [
        "casbin/admin"
      ],
      "roles": [],
      "domains": [
        "default"
      ],
      "model": "Default",
      "adapter": "",
      "resourceType": "TreeNode",
      "resources": [
        "/"
      ],
      "actions": [
        "Admin"
      ],
      "effect": "Allow",
      "isEnabled": true,
      "submitter": "admin",
      "approver": "admin",
      "approveTime": "2023-06-23T01:15:09+08:00",
      "state": "Approved"
    },
    {
      "owner": "casbin",
      "name": "permission-built-in",
      "createdTime": "2022-01-01T15:42:28+08:00",
      "displayName": "Built-in Permission",
      "description": "",
      "users": [
        "built-in/Gabo-Dev",
        "built-in/samuelzhang",
        "casbin/Thecosy",
        "casbin/aaa"
      ],
      "roles": [
        "built-in/role-built-in"
      ],
      "domains": [],
      "model": "model-built-in-rbac",
      "adapter": "",
      "resourceType": "Application",
      "resources": [
        "app-built-in"
      ],
      "actions": [
        "Read",
        "Admin"
      ],
      "effect": "Allow",
      "isEnabled": true,
      "submitter": "111",
      "approver": "222",
      "approveTime": "",
      "state": "Pending"
    }
  ],
  "data2": 2
}
```

2. What you expect and what you got

**Comment by aosolao** [comment]
> @aosolao
> 
>     1. Show your `permissions` result in JSON from: https://door.casdoor.com/api/get-permissions?owner=&p=1&pageSize=10&field=&value=&sortField=&sortOrder=以 `permissions` JSON格式显示您的结果：https://door.casdoor.com/api/get-permissions?所有者=&p=1&pageSize=10&field=&value=&sortField=&sortOrder=
> 
> 
> Like: 比如：
> 
> ```json
> {
>   "status": "ok",
>   "msg": "",
>   "sub": "",
>   "name": "",
>   "data": [
>     {
>       "owner": "casbin",
>       "name": "permission-casibase-admin",
>       "createdTime": "2023-06-23T01:15:09+08:00",
>       "displayName": "Casibase Admin Permission",
>       "description": "",
>       "users": [
>         "casbin/admin"
>       ],
>       "roles": [],
>       "domains": [
>         "default"
>       ],
>       "model": "Default",
>       "adapter": "",
>       "resourceType": "TreeNode",
>       "resources": [
>         "/"
>       ],
>       "actions": [
>         "Admin"
>       ],
>       "effect": "Allow",
>       "isEnabled": true,
>       "submitter": "admin",
>       "approver": "admin",
>       "approveTime": "2023-06-23T01:15:09+08:00",
>       "state": "Approved"
>     },
>     {
>       "owner": "casbin",
>       "name": "permission-built-in",
>       "createdTime": "2022-01-01T15:42:28+08:00",
>       "displayName": "Built-in Permission",
>       "description": "",
>       "users": [
>         "built-in/Gabo-Dev",
>         "built-in/samuelzhang",
>         "casbin/Thecosy",
>         "casbin/aaa"
>       ],
>       "roles": [
>         "built-in/role-built-in"
>       ],
>       "domains": [],
>       "model": "model-built-in-rbac",
>       "adapter": "",
>       "resourceType": "Application",
>       "resources": [
>         "app-built-in"
>       ],
>       "actions": [
>         "Read",
>         "Admin"
>       ],
>       "effect": "Allow",
>       "isEnabled": true,
>       "submitter": "111",
>       "approver": "222",
>       "approveTime": "",
>       "state": "Pending"
>     }
>   ],
>   "data2": 2
> }
> ```
> 
>     2. What you expect and what you got你所期待的和你得到的

![Snipaste_2023-08-01_09-43-59](https://github.com/casdoor/casdoor/assets/30789071/96085af2-c420-4a54-8f6e-6b933639e115)

I don't have any permissions set up, but users can still log in to applications such as Zentao or Jenkins through casdoor. I want to default to rejecting user logins to any application without any permissions.

**Comment by hsluoyz** [comment]
@aosolao the login restriction by default is disabled when you don't have permissions. You need to add at least one permission to enable it. This is because a lot of people don't use this feature, they don't use "Permissions" tab at all. We cannot forbid the logins when people don't do anything.

**Comment by aosolao** [comment]
When there are no permission rules, the system allows everything.
When there is at least one permission rule, even if it is an "allow" rule, the system will deny all unauthorized applications.
Is that what you mean?
However, I tried adding only one "allow application A" rule, but application B can still log in through Casdoor. Is this expected behavior? Did I misunderstand something?

@hsluoyz

**Comment by hsluoyz** [comment]
@aosolao 

> When there is at least one permission rule, even if it is an "allow" rule, the system will deny all unauthorized applications.

it will deny all unauthorized users/roles, not applications

> However, I tried adding only one "allow application A" rule, but application B can still log in through Casdoor.

It's on the scope of application. If you add only one "alice allow application A" permission, what happens is that all users other than "alice" cannot access application A. It has nothing to do with application B.
