### ISSUE TITLE
About permission_rule table

### ISSUE THREAD

**Issue by aosolao** [casdoor/casdoor#2121]
![Snipaste_2023-07-24_13-48-19](https://github.com/casdoor/casdoor/assets/30789071/3acc5b10-8789-44bc-b042-25675a2e3b41)

When I create a new permission for a role, some records for each user contained in the role is inserted into the permission_rule table, and the v2 and v3 fields are empty. Is this the expected behavior?

version: [v1.370.0](https://github.com/casdoor/casdoor/releases/tag/v1.370.0)

**Comment by hsluoyz** [comment]
@aosolao yes, that's expected. It's Casbin's `g` policy for RBAC: https://casbin.org/docs/rbac
