### ISSUE TITLE
Provide support to enforce permission checking with synced policies by an adapter

### ISSUE THREAD

**Issue by towerhe** [casdoor/casdoor#2122]
Adapter can sync policies from outside databases, but these synced policies are not used for checking permissions at all.

I think we can provide the method to create an enforcer with a defined adapter, it can use the synced policies.

```go
func getEnforcerByAdapter(adapter *Adapter) *casbin.Enforcer {
    // ...
}
```

When we need to check permissions, we can provide a new param like `adapterId` to the enforce api. Then the api creates enforcer with the specified adapter and handle the enforcing request.

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by leo220yuyaodog** [comment]
@towerhe I'm working on migrating the adapter sync policy feature to a new module, enforcer. The enforcer is inited with an adapter and a model. You can then specify enforcerId to check the request. Can the new feature meets you expections?

**Comment by towerhe** [comment]
@leo220yuyaodog thanks! It is exactly what i need. I saw enforcer module (#2130) is merged, but the casbin_api is not support this feature by now.

**Comment by towerhe** [comment]
Check #2160
