### ISSUE TITLE
BUG: use createDatabase flag for createDatabaseForPostgres

### ISSUE THREAD

**Issue by ISulimanov** [casdoor/casdoor#2134]
Now `createDatabase` does't have any impact on `createDatabaseForPostgres`
It could leads to unexpected behavior especially when user does't have full permissions for DB Instance.

**Comment by aegoroff** [comment]
![image](https://github.com/casdoor/casdoor/assets/2218102/3ae8091a-4422-4705-94f1-486d44374629)
![image](https://github.com/casdoor/casdoor/assets/2218102/aed8ec90-dae3-47c7-a43d-fc80b942e83a)

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/6986dad2957ed57c5df0601d60ffda8940aa8627
