### ISSUE TITLE
BUG: resets admin password after editing ldap

### ISSUE THREAD

**Issue by yamaritta** [casdoor/casdoor#2135]
steps to reproduce:
1. create new ldap settings with admin`s login and password
2. open created settings - password is ***. It is OK
3. save without changing anything
4. sync  does not work because password was changed to *** 

expected result: if user did not change password, then previous password  will not be reset

**Comment by hsluoyz** [comment]
Hi @yamaritta , can you make a PR to fix it?

**Comment by yamaritta** [comment]
@hsluoyz Hi, what would be the best way to fix?
