### ISSUE TITLE
About staticBaseUrl

### ISSUE THREAD

**Issue by aosolao** [casdoor/casdoor#2140]
![Snipaste_2023-07-26_17-18-56](https://github.com/casdoor/casdoor/assets/30789071/4e2798a4-0e93-4444-83c3-b59b74fbeb15)
![Snipaste_2023-07-26_17-15-52](https://github.com/casdoor/casdoor/assets/30789071/1f87038c-36e0-4ddb-b0d5-959da62f3e23)

I have set the "staticBaseUrl" configuration item to my own static storage service in the settings. However, the static images on the Casdoor page are still being loaded from Casdoor's official address. Is this a bug?

Version: [v1.370.0](https://github.com/casdoor/casdoor/releases/tag/v1.370.0)

**Comment by hsluoyz** [comment]
@aosolao change this too

https://github.com/casdoor/casdoor/blob/e98264f9578bf3616e3e9688cc30fe1a8357311b/web/src/Setting.js#L34
