### ISSUE TITLE
About StaticBaseUrl 2

### ISSUE THREAD

**Issue by aosolao** [casdoor/casdoor#2144]
I use docker to deploy casdoor. The docker image I use is casbin/casdoor:v1.370.0. I can't find the setting file you mentioned in it.
Is it because the docker image file structure is different?
[casdoor/web/src/Setting.js](https://github.com/casdoor/casdoor/blob/e98264f9578bf3616e3e9688cc30fe1a8357311b/web/src/Setting.js#L34)

#2140

**Comment by hsluoyz** [comment]
@aosolao Docker images don't have frontend source code. You need to build Casdoor from source

**Comment by aosolao** [comment]
@hsluoyz  Is it possible to modify the static resource address for a Docker image deployment of casdoor?

**Comment by hsluoyz** [comment]
No
