### ISSUE TITLE
About staticBaseUrl3

### ISSUE THREAD

**Issue by aosolao** [casdoor/casdoor#2145]
#2144
#2140
![256184199-4e2798a4-0e93-4444-83c3-b59b74fbeb15](https://github.com/casdoor/casdoor/assets/30789071/41efe124-791e-4178-9722-f355a49751d7)
![Snipaste_2023-07-27_11-56-58](https://github.com/casdoor/casdoor/assets/30789071/343e4891-4bb3-43ee-ab75-f5212ceb41e4)

Earlier, when we used the image version casbin/casdoor:v1.351.0, the staticBaseUrl configuration worked and after configuring it, the static file address was changed to our own address (as shown in the above image). However, after using the latest image version casbin/casdoor:v1.370.0, the staticBaseUrl configuration no longer works.

**Comment by hsluoyz** [comment]
@aosolao can you try all versions between v1.351.0 and v1.370.0 and see which version starts to have this issue?

**Comment by aosolao** [comment]
@hsluoyz  The version "casbin/casdoor:v1.356.0" is the last version without this issue, while problems started to appear from version "casbin/casdoor:v1.357.0".

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/6c628d7893c04130a3a348029676e305865085dc
