### ISSUE TITLE
How to deploy casdoor using subpath?

### ISSUE THREAD

**Issue by k9li** [casdoor/casdoor#2147]
like ```https://casdoor.com/door/```

**Comment by hsluoyz** [comment]
@k9li deploying Casdoor to a path under a domain is not supported

**Comment by k9li** [comment]
@hsluoyz any plan to support it?

**Comment by ISulimanov** [comment]
@k9li isn't it possible to solve it at the nginx or another proxy level?

**Comment by hsluoyz** [comment]
> @hsluoyz any plan to support it?

No

**Comment by k9li** [comment]
@ISulimanov i tried nginx but it doesn't work, maybe there is some hardcoded conflict
