### ISSUE TITLE
Can we make post_logout_redirect_uri optional on /api/logout?

### ISSUE THREAD

**Issue by ppadron** [casdoor/casdoor#2151]
Hi there!

Before submitting a PR for this I would like to ask if this is something that would be accepted into Casdoor:

Can we make the `post_logout_redirect_uri` optional on `/api/logout`?

This parameter is only useful when this endpoint is called directly by the end user with a browser. When `/api/logout` is called by a backend service a redirect doesn't make sense.

For now we are using a fixed URL just so the call is successful, but it would be great if `post_logout_redirect_uri` could be omitted.

What do you think?

**Comment by hsluoyz** [comment]
OK, done: https://github.com/casdoor/casdoor/commit/ca47af2ee165a0099dddca20afb7c83fd3bf2812
