### ISSUE TITLE
Bug at  : /api/get-version-info

### ISSUE THREAD

**Issue by bestHAI** [casdoor/casdoor#2156]
## Bug at : `util/system.go:GetVersionInfoFromFile`

I build dokcer image with Jenkins, when I request the api `/api/get-version-info` , got response

```json
{
    "status": "error",
    "msg": "open /home/jenkins/agent/workspace/casdoor/casdoor/version_info.txt: no such file or directory",
    "sub": "",
    "name": "",
    "data": null,
    "data2": null
}
```

## Cause analysis

It looks like the problem is: the function `runtime.Caller(0)` gets the absolute path at compile time, not the runtime

**Comment by hsluoyz** [comment]
@bestHAI when building Casdoor's docker image, the Dockerfile should write the version information into `version_info.txt` and put it inside Docker image, so Casdoor can read it: 
https://github.com/casdoor/casdoor/blob/5e4ba4f3380900de1e65947a5aa6c7a5bd2c4fa1/Dockerfile#L12

If you don't do this, you will encounter that error
