### ISSUE TITLE
Organization not listed

### ISSUE THREAD

**Issue by satishviswanathan** [casdoor/casdoor#2157]
I recently started testing casdoor for one of the application that I'm working on, I'm still new and trying to figure how things are working.

Installed casdoor all-in-one docker.

docker run -p 8000:8000 casbin/casdoor-all-in-one

I have created an organization and then went on to create an application.  While creating the application I see an option to select the Organization. I was expecting to see the organization in the dropdown however I'm just seeing the default built-in Organization. 

![image](https://github.com/casdoor/casdoor/assets/17437409/418b53eb-f39b-4ec3-98e1-8c54b6164fca)

I'm trying to figure out what I'm missing here. Any help is appreciated !

**Comment by hsluoyz** [comment]
@satishviswanathan use the latest version

**Comment by satishviswanathan** [comment]
thank you @hsluoyz  for you reply. does the following docker command pull that version ?

![image](https://github.com/casdoor/casdoor/assets/17437409/508fa56b-c704-44f9-99c5-7b4ad41fb726)

**Comment by hsluoyz** [comment]
@satishviswanathan that's a Docker and Dockerhub issue. You need to make sure to pull the latest image
