### ISSUE TITLE
[feature] casbin apis support to use specified enforcer to check permissions

### ISSUE THREAD

**Issue by towerhe** [casdoor/casdoor#2160]
I think that it is the time to add a query param to casbin apis  to specify the enforcer used to check permissions, since PR #2149 was merged.

By now, casbin apis only support three query params: `permissionId`, `modelId` and `resourceId`. We can introduce a new query param like `enforcerId`, then in the backend casbin apis use `enforcerId` to construct an enforcer for checking permissions.

**Comment by Frederic-Zhou** [comment]
Hi, @towerhe 
I just deployed my system with microservices. I want to authenticate with a user management and permissions service like Casdoor.  I want the user to access the APISIX route after logging in, and verify through Casdoor whether the currently logged-in user's role can access this address and method and I don't need to write any code in other microservices. Can authz-Casdoor and Casdoor achieve such an effect? and how to do it?

**Comment by towerhe** [comment]
@Frederic-Zhou 

You can use authz-casdoor for authenticating users of your microservices. 

authz-casdoor can not be used to authorize users' permissions.

BTW, authz-casbin creates enforcers in two ways: 

1. with model and adapter text config;
2. load model and adapter from specified path.

So it can not use the casbin apis provided by casdoor.

**Comment by Frederic-Zhou** [comment]
> @Frederic-Zhou
> 
> You can use authz-casdoor for authenticating users of your microservices.
> 
> authz-casdoor can not be used to authorize users' permissions.
> 
> BTW, authz-casbin creates enforcers in two ways:
> 
> 1. with model and adapter text config;
> 2. load model and adapter from specified path.
> 
> So it can not use the casbin apis provided by casdoor.

thanks！

**Comment by leo220yuyaodog** [comment]
@towerhe I done the feature and did some testing. Please check if the pr meet your expection.
