### ISSUE TITLE
Adapter creation error 

### ISSUE THREAD

**Issue by satishviswanathan** [casdoor/casdoor#2162]
Casdoor version

Installed via docker

![image](https://github.com/casdoor/casdoor/assets/17437409/64f97444-cd39-4ef6-9788-69a3dd4fede6)

Error

![image](https://github.com/casdoor/casdoor/assets/17437409/11970a56-a008-440b-b5dc-075a4812acdd)

**Comment by hsluoyz** [comment]
@satishviswanathan use latest version higher than `v1.377.1`: https://github.com/casdoor/casdoor/releases/tag/v1.377.1

**Comment by satishviswanathan** [comment]
@hsluoyz can I install that built via docker ?

It would be helpful, if you can share the same

**Comment by hsluoyz** [comment]
@satishviswanathan yes, install this image: https://hub.docker.com/layers/casbin/casdoor/v1.378.0/images/sha256-ea0fe44f06aab550b3d27d39b9fa8c4a91b0e3f22fc79236a2676692cf3b668e?context=explore

**Comment by satishviswanathan** [comment]
@hsluoyz  installed version v1.378.0

![image](https://github.com/casdoor/casdoor/assets/17437409/95dc594f-9d46-4253-91d3-2450b8be3aad)


Now when I create an Organization, it always saves with the default name and display name and I'm unable to update the name in edit mode.

![image](https://github.com/casdoor/casdoor/assets/17437409/9ce114df-1e96-45be-b669-ba4450884b1c)

**Comment by hsluoyz** [comment]
@satishviswanathan if this is a new issue, please create new github issue
