### ISSUE TITLE
Bug: 'GetPermissionsAndRolesByUser' does not filter permissions by organization

### ISSUE THREAD

**Issue by dvonta** [casdoor/casdoor#2169]
The code below does not filter permissions by organization, which can cause the selection of permissions on both organizations when there are two roles with the same name in different organizations.

![image](https://github.com/casdoor/casdoor/assets/133938648/30d339b0-db52-49c3-b177-dc73268f98aa)

### Steps to reproduce

Create two organizations with the same name.
Create a role in each organization with the same name.
The result will contain permissions from both organizations.

### Expected behavior
The result should only contain permissions from the organization that the role belongs to.

### Proposed solution
The Where clause should be modified to filter permissions by the organization. For example:
`roleId := role.Owner + "/" + role.Name`
`err := adapter.Engine.Where("roles like ?", "%"+roleId+"\"%").Find(&perms)`

*Note: However, I think we should separate these into an Id-mapping table instead of using a string array of Ids with `like %%` to avoid future bugs.

**Comment by hsluoyz** [comment]
@leo220yuyaodog
