### ISSUE TITLE
adapter update error

### ISSUE THREAD

**Issue by Frederic-Zhou** [casdoor/casdoor#2171]
v1.380.0
<img width="1046" alt="image" src="https://github.com/casdoor/casdoor/assets/3068492/603a0a3a-25aa-47f4-84c4-942a33c2a6a1">

Post request body on the web ui:
```
{
    "owner": "built-in",
    "name": "permission-adapter-built-in",
    "createdTime": "2023-08-02T17:30:21Z",
    "type": "Database",
    "databaseType": "mysql",
    "host": "casdoor-db",
    "port": 3306, //number
    "user": "root",
    "password": "123456",
    "database": "casdoor",
    "table": "casbin_user_rule",
    "tableNamePrefix": "",
    "isEnabled": true,
    "model": "permission-model-built-in"
}
```

adapter struct
```
type Adapter struct {
	Owner       string `xorm:"varchar(100) notnull pk" json:"owner"`
	Name        string `xorm:"varchar(100) notnull pk" json:"name"`
	CreatedTime string `xorm:"varchar(100)" json:"createdTime"`

	Type            string `xorm:"varchar(100)" json:"type"`
	DatabaseType    string `xorm:"varchar(100)" json:"databaseType"`
	Host            string `xorm:"varchar(100)" json:"host"`
	Port            string `xorm:"varchar(20)" json:"port"` //string
	User            string `xorm:"varchar(100)" json:"user"`
	Password        string `xorm:"varchar(100)" json:"password"`
	Database        string `xorm:"varchar(100)" json:"database"`
	Table           string `xorm:"varchar(100)" json:"table"`
	TableNamePrefix string `xorm:"varchar(100)" json:"tableNamePrefix"`

	IsEnabled bool `json:"isEnabled"`

	*xormadapter.Adapter `xorm:"-" json:"-"`
}
```
The `port` field of the post request body is the number, BUT the `Port` field of the Adapter struct is `string`.
This type mismatch caused an error : `保存失败: json: cannot unmarshal number into Go struct field Adapter.port of type string`

**Comment by leo220yuyaodog** [comment]
@Frederic-Zhou Please rebuild your frontend.

**Comment by Frederic-Zhou** [comment]
This modification will cause a new problem, and the old version database will not be able to convert the parameters of the int type.
```
[xorm] [warn]  2023/08/03 14:51:53.719824 Table adapter column port db type is VARCHAR(20), struct type is INT
panic: arg port as int: strconv.ParseInt: parsing "": invalid syntax

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
	/Users/zeta/workspace/casdoor/authz/authz.go:38 +0x153
main.main()
	/Users/zeta/workspace/casdoor/main.go:51 +0xaa
exit status 2
```

**Comment by leo220yuyaodog** [comment]
> This modification will cause a new problem, and the old version database will not be able to convert the parameters of the int type.
> 
> ```
> [xorm] [warn]  2023/08/03 14:51:53.719824 Table adapter column port db type is VARCHAR(20), struct type is INT
> panic: arg port as int: strconv.ParseInt: parsing "": invalid syntax
> 
> goroutine 1 [running]:
> github.com/casdoor/casdoor/authz.InitApi()
> 	/Users/zeta/workspace/casdoor/authz/authz.go:38 +0x153
> main.main()
> 	/Users/zeta/workspace/casdoor/main.go:51 +0xaa
> exit status 2
> ```

You can modify the database manually.

**Comment by Frederic-Zhou** [comment]
Perhaps changing the port field of the front-end request content from int to string is more concise and compatible with the field type of the data table that has already been created.

**Comment by hsluoyz** [comment]
@Frederic-Zhou int port is used everywhere already in Casdoor, so will not change back to string
