### ISSUE TITLE
Organization create issue in V1.380.0

### ISSUE THREAD

**Issue by satishviswanathan** [casdoor/casdoor#2172]
**Casdoor** version

![image](https://github.com/casdoor/casdoor/assets/17437409/3f4ff326-9a8e-43c1-bdbf-543a41abbadb)

**Issue**

_When_ I create an Organization, it always saves with the default name and display name and I'm unable to update the name in edit mode.

![image](https://github.com/casdoor/casdoor/assets/17437409/afa3032e-0da6-4c1f-afaa-42e9dec0d840)

**Comment by hsluoyz** [comment]
@satishviswanathan please provide a video here to reproduce this issue

**Comment by hsluoyz** [comment]
Dup with: https://github.com/casdoor/casdoor/issues/2175
