### ISSUE TITLE
Support yandex captcha

### ISSUE THREAD

**Issue by RVShershnev** [casdoor/casdoor#2173]
Request to add Yandex Captcha.
docs: https://cloud.yandex.com/en/docs/smartcaptcha/

**Comment by hsluoyz** [comment]
@RVShershnev can you make a PR to support it?

**Comment by RVShershnev** [comment]
No. Perhaps you could make this feature in the next version?

**Comment by hsluoyz** [comment]
Sorry but we don't have plan to add this feature. It's welcomed if a PR could be contributed.
