### ISSUE TITLE
The organization name field cannot be modified

### ISSUE THREAD

**Issue by kinglinggo** [casdoor/casdoor#2175]
https://github.com/casdoor/casdoor/assets/50543168/ae8eab91-39e6-447e-9f8a-fbff2180f512

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by hsluoyz** [comment]
@kinglinggo fixed by: https://github.com/casdoor/casdoor/commit/689d45c7fa712ac272941f2bb5ff2872e3187e34
