### ISSUE TITLE
Adapter creation issue in v1.382.0

### ISSUE THREAD

**Issue by satishviswanathan** [casdoor/casdoor#2186]
Casdoor version : 

![image](https://github.com/casdoor/casdoor/assets/17437409/0807bb56-2693-41fa-bad5-268c5b2767c8)

Adapter creation screen
![image](https://github.com/casdoor/casdoor/assets/17437409/3ab28d68-856f-44f9-b2e3-e7b7cf06506c)

Issue 

This screen doesn't have model mapping as shown in the documentation.

![image](https://github.com/casdoor/casdoor/assets/17437409/6423f16e-d5ec-4920-9b06-728cd6163767)

**Comment by hsluoyz** [comment]
@satishviswanathan Adapter doesn't have Model any more. Use Enforcer instead: https://door.casdoor.com/enforcers , this way follows the Casbin better.

@leo220yuyaodog plz update the docs

**Comment by satishviswanathan** [comment]
@hsluoyz  Thank you for your help
