### ISSUE TITLE
When I use the RBAC model to involve roles, and then call the /api/enforce interface, such an error will occur. Why?

### ISSUE THREAD

**Issue by shawees** [casdoor/casdoor#2198]
table data:
![image](https://github.com/casdoor/casdoor/assets/36656500/50034dab-750d-48b1-b25c-130ab8e45c45)
permissions:
![image](https://github.com/casdoor/casdoor/assets/36656500/9bbebb72-6524-4557-bc30-73b337249fab)
model:
![image](https://github.com/casdoor/casdoor/assets/36656500/f65456bd-b035-438f-a9e0-236933c94356)
test:
![image](https://github.com/casdoor/casdoor/assets/36656500/127836a3-137b-41d1-a2ad-9628cf33fb8f)

**Comment by hsluoyz** [comment]
@shawees use latest version that contains this commit: https://github.com/casdoor/casdoor/commit/eafaa135b438372d915aed71d67855781fec2134

**Comment by shawees** [comment]
@hsluoyz  The /api/enforce interface specifies the enforcerId is also the case
