### ISSUE TITLE
User edit blank page

### ISSUE THREAD

**Issue by aosolao** [casdoor/casdoor#2211]
![Snipaste_2023-08-14_10-38-16](https://github.com/casdoor/casdoor/assets/30789071/e6b4f0e3-83f2-40f5-a909-e0e300903d2f)
![Snipaste_2023-08-14_10-41-07](https://github.com/casdoor/casdoor/assets/30789071/d67c32f9-5d74-4630-9107-f70f6d9f4277)

After updating to version 1.388, when synchronizing users from LDAP to Casdoor, clicking the "Edit" button on the user list results in a blank page.

**Comment by hsluoyz** [comment]
@aosolao paste frontend (F12 console) and backend crash logs here

**Comment by aosolao** [comment]
![Snipaste_2023-08-14_11-14-34](https://github.com/casdoor/casdoor/assets/30789071/57f07bd0-7bc6-4d20-aaf5-dac75ae37b79)
@hsluoyz

**Comment by hsluoyz** [comment]
@aosolao fixed by: https://github.com/casdoor/casdoor/commit/b7a001ea397cb726ae3c4277871f403b48ad0510
