### ISSUE TITLE
[question] Setup MFA (type=app) for custom user from admin

### ISSUE THREAD

**Issue by netandreus** [casdoor/casdoor#2215]
When I open user profile and try to set up MFM - Multi-factor method (type=app) for some user - Casdoor asked me password of my admin user and set up TOTP for **admin** user, not selected user.
<img width="1273" alt="mfa" src="https://github.com/casdoor/casdoor/assets/313477/1c5de46a-644b-4059-a774-e590f750bddd">

How can I set MFM for one of my users?

**Comment by hsluoyz** [comment]
@netandreus did you resolve the previous issue: https://github.com/casdoor/casdoor/issues/2213 ? How?

**Comment by leo220yuyaodog** [comment]
@netandreus See #2100

**Comment by netandreus** [comment]
> @netandreus did you resolve the previous issue: #2213 ? How?

Yes. Problem resolved by removing volume mount from docker-compose.yml:
```
    volumes:
      - ./volumes/conf:/conf/
```
Also this folder on host was empty.
May be Casdoor can't merge configuration from conf dir and env variables.

**Comment by netandreus** [comment]
> #2100
> Casdoor just supports user to enbale MFA by itself. 

@hsluoyz is it true? We need to setup MFA for our users. What should we do in this case?

**Comment by hsluoyz** [comment]
@netandreus why do you want to setup MFA for a different user? Usually you won't own your users' devices like phone number, email account, authenticator app, etc. even if you are their boss/admin

**Comment by netandreus** [comment]
@hsluoyz yes, we provide phones to our users and deploy application to them. Our users don't want to customize phones such way.

> you can log into their account via org master password, then set MFA inside their account.

This may solve our case, I try to check it tomorrow. Thanks.

**Comment by hsluoyz** [comment]
> we provide phones to our users and deploy application to them. Our users don't want to customize phones such way.

You can directly edit their phone field as admin, no need to mess with MFA

**Comment by netandreus** [comment]
Hello, @hsluoyz ! I have a trouble.
> you can log into their account via org master password, then set MFA inside their account.

When user already has MFA and I trying to log into his account with master password - Casdoor asked me to enter totp-code for this user, but I doesn't know it. I think login with master password should processed without MFA, even it configured for user. What do you think about this problem?
