### ISSUE TITLE
The /api/enforce interface specifies the enforcerId and this error occurs, which is the same as this issue

### ISSUE THREAD

**Issue by shawees** [casdoor/casdoor#2220]
![image](https://github.com/casdoor/casdoor/assets/36656500/a481868d-cebb-405d-8f42-464b4308fdb3)
issues：https://github.com/casdoor/casdoor/issues/2198
version：casdoor-all-in-one:v1.390.0

**Comment by hsluoyz** [comment]
@shawees the error means that your policy definition in Casbin model has 3 elements, but your adapter's policy rule has 6 elements. They don't match. See more details at Casbin docs: https://casbin.org/docs/syntax-for-models#policy-definition
