### ISSUE TITLE
The /api/enforce interface specifies the enforcerId and this error occurs

### ISSUE THREAD

**Issue by shawees** [casdoor/casdoor#2222]
enforcer:
![image](https://github.com/casdoor/casdoor/assets/36656500/890401ef-8771-44e1-a281-988957ddaac1)
model:
![image](https://github.com/casdoor/casdoor/assets/36656500/8b852683-7c0c-4f59-ba9c-351c804da916)
adapter:
![image](https://github.com/casdoor/casdoor/assets/36656500/3fef684a-6c42-4dbf-8119-77a01fcd6678)
test：
![image](https://github.com/casdoor/casdoor/assets/36656500/fdcf65ea-a647-4000-a72a-96b4e751274b)

According to the model, only three parameters need to be passed
Could you please help me take a look

**Comment by leo220yuyaodog** [comment]
@shawees Use permissionId as parameter instead of enforcerId
