### ISSUE TITLE
other org global admin Unauthorized to edit users

### ISSUE THREAD

**Issue by xiaoleyang2018** [casdoor/casdoor#2223]
other org global admin , called test1,  login from  casnode--> click setting --> Jump to casdoor --> click UserMamagerment/Users  ，resp is 403 ;like roles is also 403

**Comment by shmy** [comment]
<img width="803" alt="image" src="https://github.com/casdoor/casdoor/assets/19339440/890e7232-cfb1-4472-be0f-30bb314a680c">
Same issue
