### ISSUE TITLE
/api/get-user-count got number of users logged in always 0

### ISSUE THREAD

**Issue by bestHAI** [casdoor/casdoor#2233]
The API `/api/get-user-count` gets the number of users logged in, but it's always 0? Even if a user is already logged in, it's still 0

See: https://door.casdoor.com/api/get-user-count?isOnline=1 , result is always 0

![image](https://github.com/casdoor/casdoor/assets/3787410/5ad89b3d-b45a-4f66-a9ba-ed6ba517a5c4)

This is because User's `isOnline` field is not set to true in any conditions. This feature is just not implemented yet

![image](https://github.com/casdoor/casdoor/assets/3787410/2d0df130-7cae-4d00-add4-9aeb9d6d344a)

**Comment by hsluoyz** [comment]
@bestHAI not zero now:

![image](https://github.com/user-attachments/assets/ac9ae178-0cf1-41f9-9299-f8c8cff47472)
