### ISSUE TITLE
Organizations public certificates

### ISSUE THREAD

**Issue by netandreus** [casdoor/casdoor#2247]
Is there a way to fetch public key of organization like GitHub?
For example I can get my public key without auth by fetching this url: https://github.com/netandreus.keys
It needed for validate JWT token at the connected application. How can I fetch organization's public key without auth?

**Comment by hsluoyz** [comment]
@netandreus I don't think now Casdoor's org has something called "public key". What is used for? Why is it needed?

**Comment by hsluoyz** [comment]
@netandreus can you make a PR?

**Comment by netandreus** [comment]
@hsluoyz  now there are two possibilities for obtaining the result.
1. Use Casdoor API
2. Develop side web-service, running at neighboring container near casdoor containers.

#### 1. Use Casdoor API
1. Make request to fetch ```certificateId``` for application:
```
curl -X 'GET' \
  'https://casdoor_host.com/api/get-application?id=admin%2Fapp_code' \
  -H 'accept: application/json'
```
2. Make request to fetch certificate content (both public and private):
```
curl -X 'GET' \
  'https://casdoor_host/api/get-cert?id=organization_code%2Fcertificate_id' \
  -H 'accept: application/json'
```

#### 2. Side web-service
1. Connect to database and fetch certificate's public key.
2. Provide it to http-client

#### Pros and cons
Cons of first method (using casdoor API) is we need to authorizate to obtain a public key, and now there is no way (please correct me if it false) to retrieve public(!) certificate for given application without authorization.

Cons of second method (using side service) is we need to interact with database directly. It is advisable to avoid this.

#### My opinion
I don't know Casdoor well for making PR for this issue, but I can share code of my side service (written on TypeScript), serving public keys requests. Please let me know your opinion about this issue.

**Comment by netandreus** [comment]
### Problem

@hsluoyz This request allowed only if we already authorized in Casdoor. For example, if we just try this request:
```
curl -X 'GET' \
  'http://localhost:8000/api/get-application?id=admin/application_9kybb9&withKey=1' \
  -H 'accept: application/json'
```
response will be:
```
{
"status": "ok",
"msg": "",
"sub": "",
"name": "",
"data": null,
"data2": null
}
```
This is expected and generally does not solve the problem of obtaining the public key of an application (by its name) in the case where we are not authorized. 

I'm trying to understand how to implement the functionality of obtaining a public application key without authorization, as it done for the user in GitHub.

```
curl -X 'GET' \
  'https://github.com/netandreus.keys' \
  -H 'accept: application/json'
```

### Possible solution
On the client side (relatively Casdoor) we already have clientId and clientSecret for taget application. We need to verify received OauthToken by application's public key.  For this purposes we need to obtain application's public key. May be you can make some API-method like this one:

**Request**
```
curl -X 'GET' \
  'https://localhost:8000/api/get-application-public-key?id=admin%2Fapplication_9kybb9&clientId=xxxxxxx&clientSecret=yyyyyy' \
  -H 'accept: application/json'
```
**Response**
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABOOOOCAQDMbnMAIWmQSzYDVF1eGii304u5RPZYrb1n/xWkP7I3r4lwZgvnYY3WWteEPz5bh+fidSBDZGzkIUHj0iCZ9H3u3Nv5YAu2zElDJ1Vrfvpiav0tiR6dRoj4slHyb79sFbrfEHx263dXpujSPf5RVI0T4rbisvWQkqpJc+XDBFDSFLDPSKF:LNLSKDFMDSL23423432hlkkjklh$#$#QADCSYK/h+dlyU6lKODnKlVSJ4NwojnD6HFQKN/re44eIYBYUR0YEd6xr0E1CURehlAcvsT06rACqxw1jfkRh7M5sbmB99kTcksgXOPrFY2etQTpud1YOkqPfE/GiDZo6uySKL5FMG+7jJDjmUD0BkLgs7+2GayNAWLdp9hbkNU1kYvb5a1ax6Pp/2v7OyaeYniYk15laVh5T6bwDYlHBplCejdcowTdjRctAhyyN6Qy5/f5y3WzWHY9EJvV1KMu7xL8D1iC0+5AsdJrESBNGk4PJRujawxXYy5+sExpzN+ZSshJLiWE2mSKGLVaChWAsguU+cXnraN0ZMpxdMCop0gI73W7FWuH2DlseJoZ6fl9lAVmAvMYmk4pWxQnwRO/B/lOZXaEfgIbzbQcGFcK8//zPNO3QdveGLCXYC6CzHVzdc+ygqGDGL3H0GVH9Ex5CS1u5Kti/XK7wy+vHcAfHIC0FEpGW2/0j9jcSLePTwxd/ZK1UEVHoacw==
```

**Comment by hsluoyz** [comment]
@netandreus https://door.casdoor.com/api/get-application?id=admin/app-built-in is public, see: https://door.casdoor.com/login

![image](https://github.com/casdoor/casdoor/assets/3787410/1c5eb34e-fcc6-439e-aaf4-ae202003f6c0)
