### ISSUE TITLE
Casdoor users roles question

### ISSUE THREAD

**Issue by kovriginaaa** [casdoor/casdoor#2248]
Hello!
We have docker with
1) casdoor (casbin/casdoor image)
2) postgres 13.3 db

In Casdoor we have:
1) Organization - telemap_org
2) 2 users for this organization:
 2.1) user_telemap1 - has option "is admin" activated, role "read_role_telemap", permission "permission_telemap"
 2.2) user_telemap2 - has role "read_role_telemap", permission "permission_telemap"
3) role "read_role_telemap"
4) model "model_telemap" and its text
5) adapter "adapter_postgresql" for connection to postgresql successfully connected
6) 2 policies synchronized in adapter 
p	read_role_telemap	*	read				
p	permission_telemap	*	read
7) enforcer "enforcer_telemap" for connecting "model_telemap" with "adapter_postgresql"

When i try to log in under user_telemap1 all casdoor tabs are there and i can create something (as soon as this user is admin)
When i try to log in under user_telemap2 only Home page is available and when i try to reach something like http://localhost:8000/users i see "403 Unathorized/ Sorry you do not have permissions to accesss this page or logged in status invalid"

Where is my mistake?
I want to create different roles with access to different tab, for example. 
But on the first step - create a user with read access to all and i failed.
Could you help me please where is a mistake?
[casdoor-202308231515.txt](https://github.com/casdoor/casdoor/files/12418084/casdoor-202308231515.txt)

**Comment by hsluoyz** [comment]
@kovriginaaa a user needs to be org admin (`isAdmin` is true) first to be able to see the user list
