### ISSUE TITLE
casdoor docker installation for v1.399.0

### ISSUE THREAD

**Issue by satishviswanathan** [casdoor/casdoor#2252]
I used to install the previous version using the following command. However for the new version v1.399.0 the app is not starting.

![image](https://github.com/casdoor/casdoor/assets/17437409/1e720803-24da-4429-ba1e-c6ecfff81414)

_**Log**_

![image](https://github.com/casdoor/casdoor/assets/17437409/4536185b-ca55-43ed-8ae0-37a05ed2aa64)

**Comment by hsluoyz** [comment]
@satishviswanathan make sure you are actually running v1.399.0 tag:

`
docker run -p 8000:8000 casbin/casdoor-all-in-one:v1.399.0
`


My side is OK:

![image](https://github.com/casdoor/casdoor/assets/3787410/32b7e79b-1b64-4c0b-9591-45a4bdc9342b)
