### ISSUE TITLE
Unable to use some SDK methods via Client Credentials in created application and organization

### ISSUE THREAD

**Issue by theburyat** [casdoor/casdoor#2253]
I'm using .NET SDK with Casdoor v.1.399.0. I got token by client id and secret. I picked all available types in application Grant Types.

![image](https://github.com/casdoor/casdoor/assets/54956408/a343b543-b981-4516-ade3-212ff82ffc01)

When I want to get application with .NET SDK with ```GetApplicationAsync```, everything is going good, but when I try to get organization or permissions with ```GetOrganizationAsync``` or ```GetPermissionsAsync```, I get only CasdoorApiException with message "Unauthorized operation".  Below is my programm code:

```
using Casdoor.Client;
using Microsoft.IdentityModel.Logging;

var httpClient = new HttpClient(new HttpClientHandler { ServerCertificateCustomValidationCallback = (_, _, _, _) => true});
var options = new CasdoorOptions
{
    Endpoint = "http://localhost:8000",
    OrganizationName = "organization",
    ApplicationName = "app",
    ApplicationType = "native",
    ClientId = "20f079f1bd7b0e5da9b9",
    ClientSecret = "9893f5cf47db52a06df93c5feecb66f8adfda18d",

    RequireHttpsMetadata = false
};

var client = new CasdoorClient(httpClient, options);

IdentityModelEventSource.ShowPII = true;

var token = await client.RequestClientCredentialsTokenAsync();
if (token.IsError)
{
    Console.WriteLine("Bad first login");
    return;
}
client.SetBearerToken(token.AccessToken);

var app = await client.GetApplicationAsync("admin/app");
var permissions = await client.GetPermissionsAsync();

```

Why does it works in such way? Maybe token, that is requested by client id and secret has less permissions and I can get only info about application with it?

**Comment by theburyat** [comment]
Also, situation is the same, when I try to get users by ```GetUsersAsync```, CasdoorApiException with message "Unauthorized operation"

**Comment by theburyat** [comment]
@hsluoyz isn't there any progress?

**Comment by hsluoyz** [comment]
@theburyat this has nothing to do with .NET SDK. It's about that you don't have permission to call API.

You need to do debugging and set a breakpoint at the following function, to see why it rejected your API call

https://github.com/casdoor/casdoor/blob/953be4a7b6adf06b3a7b9027bd0d0a67a19ddf20/authz/authz.go#L111-L133

**Comment by theburyat** [comment]
@hsluoyz  I tried to debug, but I don't understand, how can I give a permission to get some info for application?

**Comment by theburyat** [comment]
@hsluoyz I have seen that if I parse access token, that I got from request by client credentials, user Id is "admin/{my application name}" and property IsAdmin is "false", that's why I can't request for any data outside application. Also, I can't make this user admin or give it some permissions, because it doesn't appear in request for users or in web ui. Could you tell me, how cat I give more permissions to this user?
