### ISSUE TITLE
[BUG]Registration is Set to Not Require a Password, but Actually Prompts "Password Must Be at Least 6 Characters

### ISSUE THREAD

**Issue by dwzkit** [casdoor/casdoor#2256]
Description:
When using Casdoor for user registration, we have set up the backend to not require a password during the registration process. However, after the user enters their phone number and verification code, the system still prompts that "Password must be at least 6 characters." This results in an inconsistency between the settings and actual behavior.

Steps to Reproduce:

- Open the Casdoor registration page.
- Enter a valid phone number and verification code.
- Attempt to register.

Expected Behavior:
When the backend is set to not require a password, users should be able to register successfully without receiving a password-related error prompt.

Actual Behavior:
Despite the backend being set to not require a password, users still receive an error prompt stating "Password must be at least 6 characters" during registration.

Screenshots:
<img width="1891" alt="image" src="https://github.com/casdoor/casdoor/assets/41875799/b853c51b-769a-480b-80b8-ed3b016829ab">

<img width="1175" alt="image" src="https://github.com/casdoor/casdoor/assets/41875799/c953a334-c29f-45bb-83ba-35cd2e361ff8">

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by dwzkit** [comment]
Thank you so much for resolving the bug so efficiently. It's now working.
