### ISSUE TITLE
get-user route does not work with python casdoorSDK

### ISSUE THREAD

**Issue by majodu** [casdoor/casdoor#2260]
`api-casdoor-1  | 2023/08/25 16:45:30.551 [C]  the request url is  /api/get-user
api-casdoor-1  | 2023/08/25 16:45:30.551 [C]  Handler crashed with error runtime error: invalid memory address or nil pointer dereference
api-casdoor-1  | 2023/08/25 16:45:30.552 [C]  /usr/local/go/src/runtime/panic.go:884
api-casdoor-1  | 2023/08/25 16:45:30.552 [C]  /usr/local/go/src/runtime/panic.go:260
api-casdoor-1  | 2023/08/25 16:45:30.552 [C]  /usr/local/go/src/runtime/signal_unix.go:835
api-casdoor-1  | 2023/08/25 16:45:30.552 [C]  /go/src/casdoor/controllers/user.go:173
api-casdoor-1  | 2023/08/25 16:45:30.554 [C]  /usr/local/go/src/reflect/value.go:584
api-casdoor-1  | 2023/08/25 16:45:30.555 [C]  /usr/local/go/src/reflect/value.go:368
api-casdoor-1  | 2023/08/25 16:45:30.556 [C]  /go/pkg/mod/github.com/beego/beego@v1.12.12/router.go:897
api-casdoor-1  | 2023/08/25 16:45:30.556 [C]  /usr/local/go/src/net/http/server.go:2947
api-casdoor-1  | 2023/08/25 16:45:30.556 [C]  /usr/local/go/src/net/http/server.go:1991
api-casdoor-1  | 2023/08/25 16:45:30.556 [C]  /usr/local/go/src/runtime/asm_arm64.s:1172`

I cant seem to get get-user func to work on the latest docker image v1.400.0 and  the python casdoorSDK. I am accessing the admin account with nothing added to the built-ins. I have already logged in as a user. Is there something I am missing?

**Comment by hsluoyz** [comment]
@majodu fixed by: https://github.com/casdoor/casdoor/commit/a637707e7798c2a5da29bf60ccd966412323fecb
