### ISSUE TITLE
The displayName argument in /api/update-user should be optional   

### ISSUE THREAD

**Issue by strong-xiaoge** [casdoor/casdoor#2268]
Why must the displayName parameter be passed?

If I don't want to modify this parameter, can I not pass this parameter.

 
![image](https://github.com/casdoor/casdoor/assets/48307703/4d678bb6-9dc2-4948-9042-7987ddf4e4b5)

**Comment by hsluoyz** [comment]
@strong-xiaoge use latest Casdoor version, the code has changed:

![image](https://github.com/casdoor/casdoor/assets/3787410/79a24986-d2e7-43d0-bdcc-40c40b143eb7)

**Comment by strong-xiaoge** [comment]
> @strong-xiaoge use latest Casdoor version, the code has changed:
> 
> ![image](https://user-images.githubusercontent.com/3787410/263672564-79a24986-d2e7-43d0-bdcc-40c40b143eb7.png)

This is a check for registered interface data, not a check for updated interface data

**Comment by hsluoyz** [comment]
@strong-xiaoge if you don't want to modify displayName, just pass the old value
