### ISSUE TITLE
Could not access casdoor frontent with systemd service.

### ISSUE THREAD

**Issue by SupremeLiam** [casdoor/casdoor#2269]
If I use systemd for starting casdoor backend program with the system boots, when I visit the website, it returns this.
```
{
  "status": "error",
  "msg": "Unauthorized operation",
  "data": null,
  "data2": null
}
```

This is the script of `/etc/systemd/system/casdoor.service`:
```
[Unit]
Description=Casdoor backend
After=network.target multi-user.target
Wants=network.target multi-user.target
 
[Service]
User=root
ExecStart=/root/casdoor/casdoor
 
[Install]
WantedBy=multi-user.target
```

However, if I just start the casdoor with `./casdoor`, it will respond normally.

I am wondering what the difference is and how to solve it.

**Comment by hsluoyz** [comment]
@SupremeLiam I'm not familar with systemd. I suggest you do debugging and set breakpoint at the following code, to see why permission deny occurs.

https://github.com/casdoor/casdoor/blob/d3d4646c56f02477789a2c16d33f4a0f5f69ff0f/authz/authz.go#L111-L133

**Comment by Selflocking** [comment]
I think the reason for this error is that casdoor did not find the web directory:

```json
{
  "status": "error",
  "msg": "Unauthorized operation",
  "data": null,
  "data2": null
}
```

I think you can solve this by setting the working directory, e.g. like this:

```diff
[Unit]
Description=Casdoor backend
After=network.target multi-user.target
Wants=network.target multi-user.target
 
[Service]
User=root
+ WorkingDirectory=/root/casdoor
ExecStart=/root/casdoor/casdoor
 
[Install]
WantedBy=multi-user.target
```
