### ISSUE TITLE
Add a payment system to support multiple channels like Paypal, Alipay, Wechat Pay, etc.

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#227]
Required by: https://github.com/casbin/casnode/issues/343

**Comment by hsluoyz** [comment]
@Kininaru @WindSpiritSR @sh1luo

**Comment by rafaelgfirmino** [comment]
The casdoor site has this definition:
"A UI-first centralized authentication / Single-Sign-On (SSO) platform supporting OAuth 2.0, OIDC and SAML, integrated with Casbin RBAC and ABAC permission management"

Way casdoor need add payment system ?
I think the focus casdoor is Authentication and Authorization using casbin, for me this feature payment not make sense.
all engagement must be with authentication and authorization.

**Comment by Kininaru** [comment]
@rafaelgfirmino Agree with you.
