### ISSUE TITLE
How to integrate firebase?

### ISSUE THREAD

**Issue by buildnewapp** [casdoor/casdoor#2271]
Google's Firebase also provides login authentication function. How can I integrate phone login, email login, and Google login from Firebase into the casdoor?

Why was the firebase integration issue I mentioned yesterday deleted?

**Comment by hsluoyz** [comment]
@buildnewapp Casdoor itself is a SSO with phone login, email login, and Google login. It doesn't need another provider like Firebase to provide these. They are "mutually exclusive". If you use Firebase, you doesn't need to use Casdoor then

**Comment by hsluoyz** [comment]
@buildnewapp use this: https://github.com/casdoor/casdoor-firebase-example
