### ISSUE TITLE
edit user is block

### ISSUE THREAD

**Issue by zhaobingchun** [casdoor/casdoor#2274]
![image](https://github.com/casdoor/casdoor/assets/8914995/a4de2c6f-dedf-4f66-b9ac-a76c9055a6ce)
![image](https://github.com/casdoor/casdoor/assets/8914995/705e06ff-45d0-46ef-bf9e-5dd9311257d9)
![image](https://github.com/casdoor/casdoor/assets/8914995/46894fd7-6ba2-4eed-9a73-725578c25eec)
i use the laste version, but i't already black

**Comment by hsluoyz** [comment]
@zhaobingchun the demo site is good: https://door.casdoor.com/users/built-in/Sid

I suggest you deleting all tables in your DB and restart Casdoor

![image](https://github.com/casdoor/casdoor/assets/3787410/ded5865e-6da6-4189-8f7b-fdc94478151a)
