### ISSUE TITLE
Control/Bypass the hashing/encryption algorithm of the password for users import

### ISSUE THREAD

**Issue by yescine** [casdoor/casdoor#2282]
**Feature Description**
When sign-up or import users from external apps/system/data-base the password already hashed with some hashing algorithm like bcrypt, When using the API route `/api/add-user` it automatically try to encrypt the password using the `Organization password type` (even if the imported password is already encrypted.

**Existing solution**
We can import user using the syncer but it involve one time data-base to data-base operation, it would be great to have an API endpoint `/api/upload-user` which verify if the password comply with `Organization password type` and save it directly to data-base.

This way we can use Casdoor as centralized microservice for identities management for different existing apps/systems and automate the process via API call

Example of how to override the default hashing algorithm when adding users, ex: {"encryptionScheme":"bcrypt"}
https://fusionauth.io/docs/v1/tech/apis/users#import-users

**Comment by hsluoyz** [comment]
@yescine fixed by: https://github.com/casdoor/casdoor/commit/669ac7c61875443c0f4206f896f9cb165ae81f49

Fill in `user.PasswordType` to avoid second user pass encryption

**Comment by yescine** [comment]
@hsluoyz Thanks, tested it worked.
Add this to official Docs.

**Comment by hsluoyz** [comment]
@yescine can you help add it to docs by making a PR?

**Comment by yescine** [comment]
@hsluoyz Sorry for late reply, I added to doc.
https://github.com/casdoor/casdoor-website/pull/563
