### ISSUE TITLE
Too Many Connection Mysql

### ISSUE THREAD

**Issue by habibiazmi123** [casdoor/casdoor#2283]
How to solve this problem?

![image](https://github.com/casdoor/casdoor/assets/8370125/d96d2a46-9d63-4251-91e7-9090bc268bf3)

if I see `SHOW PROCESS LIST;` the tasks are never finished instead they are piling up so that the error appears

![image](https://github.com/casdoor/casdoor/assets/8370125/e71e509f-09c0-489b-ba5b-771c04f9ae61)

Is it because the connection is not closed? after running the task

**Comment by hsluoyz** [comment]
@habibiazmi123 did you use Syncer?

**Comment by habibiazmi123** [comment]
> @habibiazmi123 did you use Syncer?

yes, I used it before, but now it is disabled

**Comment by hsluoyz** [comment]
@habibiazmi123 Casdoor uses XORM to access DB, it only creates one XORM engine, see code: https://github.com/casdoor/casdoor/blob/master/object/ormer.go

So there's no way to trigger your issue I think. If you believe there's something wrong with the code, please point out
