### ISSUE TITLE
"Failed to save: Display name cannot be empty" if displayname field is disabled

### ISSUE THREAD

**Issue by neil-lcv-cs** [casdoor/casdoor#2290]
Hi Casdoor team,

When the "display name" field is disabled in an organization, editing an user always fails because Casdoor requires the displayname to be filled.

Here are our organization options:
![image](https://github.com/casdoor/casdoor/assets/142019916/31edc8e0-d4a1-4bb6-8c6d-42ffa734efc8)

I believe the behavior is likely to be the same with the username field.

Here’s what we get when we try to edit *any field* from an user of our organization:
![image](https://github.com/casdoor/casdoor/assets/142019916/0be579d0-ca63-466b-afd9-1731de1aad82)

The same happens when an user wants to edit their own preferences (eg. change their email or password).

Since those two fields seems to be mandatory for OIDC, a way to fix this would be to construct the missing fields on server-side upon `/api/signup` and `/api/add-user`, based on other fields, similar to this:

https://github.com/casdoor/casdoor/blob/6700d2e24478fccfb96aff27721520c4f7e0736b/idp/goth.go#L452-L467

`DisplayName` can fallback to `Username`/Name if empty, which can itself fallback to `ID` if empty. Also making the `ID` field mandatory for all organizations seems reasonable to me.

**Comment by hsluoyz** [comment]
@neil-lcv-cs using "?allowEmpty=1" to bypass empty displayName check in update-user API: https://github.com/casdoor/casdoor/commit/e584a6a111b78650b4daf886267b9b7f4668cfee
