### ISSUE TITLE
How can I limit parameters such as login time, login day, type of operating system used during user login?

### ISSUE THREAD

**Issue by HRNasr** [casdoor/casdoor#2293]
Hello
I have some question:
1- Does it support  Radius ?
2- How can I limit parameters such as login time, login day, type of operating system used during user login?
3-  add Persian language.

**Comment by hsluoyz** [comment]
@HRNasr Persian added: https://github.com/casdoor/casdoor/commit/b0aaf09ef110526ecbd62184b9e3b6152ed5972f

**Comment by hsluoyz** [comment]
@HRNasr Radius has been converted into a separate issue: https://github.com/casdoor/casdoor/issues/2294
