### ISSUE TITLE
Can't add Apple oauth provider

### ISSUE THREAD

**Issue by ilyamobi** [casdoor/casdoor#2298]
Hello. Tried to add Apple provider, cause it don't have client secret, leaved it blank. And after trying to login via this provider, got this error. Help me, please.
![apple_oauth_bug](https://github.com/casdoor/casdoor/assets/1139133/778116ae-3213-4b31-ad8e-052f53aaa47d)

**Comment by UsherFall** [comment]
According to the documentation: https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens
you need to create the client secret yourself and it cannot be left blank.
![image](https://github.com/casdoor/casdoor/assets/98513748/3d5c218c-be3f-4465-9201-125ac3e65a7c)

**Comment by ilyamobi** [comment]
I generated client secret according to apple documentation (https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens), used https://mysite.com/callback as callback url and got the same error. What am I doing wrong?
