### ISSUE TITLE
Issue with Plan and Product Creation for Specific Organization

### ISSUE THREAD

**Issue by tulalatula** [casdoor/casdoor#2301]
Hello,

I've encountered some issues while creating plans and products in the backend.

Background:
The system has a default organization called built-in (let's call it Organization A). For my specific business requirements, I created an organization named qmsg (referred to as Organization B). Under Organization B, I then set up an application named qmwd.

Issue:
When I created a plan for the qmsg organization in the backend under the "Plan" section, it automatically generated a product (let's call this Product C).
<img width="1435" alt="Pasted Graphic" src="https://github.com/casdoor/casdoor/assets/79890642/e9bd9b2f-781f-4398-975f-15156469638d">

Product C belongs to Organization B. However, when I share the purchase link of Product C, the system prompts users to log in or register through the entrance of Organization A. They can't perform related operations via Organization B.
<img width="1427" alt="Fcaudoor o n Ceuu • ese G Rese • s O OTA8" src="https://github.com/casdoor/casdoor/assets/79890642/3c600a42-7488-4248-a595-355835d5afa4">

Objective:
I aim to create a product for Organization B, and I want users to be able to purchase and pay for it normally. Could you please guide me on how to achieve this?

**Comment by Chinoholo0807** [comment]
I think the way you use pricing and plan is incorrect. You should not directly share the link of automatically created Product C. The correct flow is as follows:
1. Create a `Pricing D`, fill the `Application` field with `qmwd`.
2. Add `Plan B` to `Pricing D`.
3. Share the link to `Pricing D` with users. Users can choose `Plan B` and proceed with signup and purchase the `Product C`
You can refer to https://casdoor.org/docs/pricing/overview for more information.

**Comment by hsluoyz** [comment]
Closed as resolved

**Comment by tulalatula** [comment]
> @tulalatula I think the way you use pricing and plan is incorrect. You should not directly share the link of automatically created Product C. The correct flow is as follows:
> 
> 1. Create a `Pricing D`, fill the `Application` field with `qmwd`.
> 2. Add `plan_djolxh` to `Pricing D`.
> 3. Share the link to `Pricing D` with users. Users can choose `plan_djolxh` and proceed with signup and purchase the `Product C`
>    You can refer to https://casdoor.org/docs/pricing/overview for more information.

Hello,

Thank you for your previous guidance regarding the correct use of pricings and plans. I've followed the steps provided, but I've encountered another issue related to product pricing.

Steps to reproduce:

I created Product C and set a specific price for it in the backend.
Upon saving, the displayed price for Product C in the system UI consistently shows as 0.
Even when trying to adjust the product's price directly in the database, the UI still displays the price for Product C as 0.
Issue:
Due to this, when setting up plans associated with Product C, the price is also shown as 0, making it impossible for users to make payments.

Expected Behavior:
When a price is set for a product in the backend, it should correctly reflect both in the system UI and any associated plans.
<img width="1435" alt="image" src="https://github.com/casdoor/casdoor/assets/79890642/c42ad1fe-6bac-46e5-852c-6c0fb52857b5">
I'd appreciate any guidance on resolving this. Is this a known issue or is there something I might be missing in the configuration?
<img width="1064" alt="image" src="https://github.com/casdoor/casdoor/assets/79890642/1839de08-162d-4886-a63d-545180710608">


Thank you for your assistance.

**Comment by Chinoholo0807** [comment]
@tulalatula  Could you please tell me the version of your Casdoor? The pricing and plan features require Casdoor to have a version >= than v1.404.0.  From the screenshot you provided, it appears that your version is not the latest one. 
Moreover, please do not directly edit the related product of the plan. Instead, edit the plan itself, and the related product will be automatically updated.

**Comment by tulalatula** [comment]
> Could you please tell me the version of your Casdoor? The pricing and plan features require Casdoor to have a version >= v1.404.0. From the screenshot you provided, it appears that your version is not the latest one.
> Moreover, please do not directly edit the related product of the plan. Instead, edit the plan itself, and the related product will be automatically updated.

Hello, and thank you for your assistance and guidance. I have successfully updated Casdoor to the latest version and can now create products that can be paid for. However, I have encountered two new questions that I would like to inquire about:

How can I provide the created product links to users for payment? When I send the test links to users, the system prompts them to log in to Organization A, even though these products were created for Organization B.
The products I've created are billed on a monthly basis. After a user successfully makes a payment, how can I associate it with a subscription? For example, if a user makes a payment today, how should I set the subscription expiration date to October 8th?
Thank you very much for your support and response!

**Comment by tulalatula** [comment]
> @tulalatula Could you please tell me the version of your Casdoor? The pricing and plan features require Casdoor to have a version >= v1.404.0. From the screenshot you provided, it appears that your version is not the latest one. Moreover, please do not directly edit the related product of the plan. Instead, edit the plan itself, and the related product will be automatically updated.

Hello, and thank you for your assistance and guidance. I have successfully updated Casdoor to the latest version and can now create products that can be paid for. However, I have encountered two new questions that I would like to inquire about:
1.How can I provide the created product links to users for payment? When I send the test links to users, the process is as follows,  I'm unable to complete the payment successfully.
<img width="1370" alt="f Casdoor" src="https://github.com/casdoor/casdoor/assets/79890642/88928125-a1ca-41a9-a76c-e03b96a2dd94">

（Organization A's login pag）

<img width="1133" alt="奇妙文档会员定价" src="https://github.com/casdoor/casdoor/assets/79890642/ea1d07c7-18ba-4a7f-a397-569db58323ee">

<img width="1388" alt="奇妙文档会员定价" src="https://github.com/casdoor/casdoor/assets/79890642/ba3dd931-89e3-4765-b9e9-088ef8d39913">

<img width="420" alt="Product for Plan 奇妙时光-中级会员奇妙时光-中级会员Monthly" src="https://github.com/casdoor/casdoor/assets/79890642/38be823e-e69c-445d-9165-3a3effff8308">

When I click on the link above and select 'Get Started,' it redirects me to the registration page. However, when I successfully register and try to make a payment, I encounter the above error.

2.The products I've created are billed on a monthly basis. After a user successfully makes a payment, how can I associate it with a subscription? For example, if a user makes a payment today, how should I set the subscription expiration date to October 8th? 
<img width="1383" alt="Pasted Graphic 5" src="https://github.com/casdoor/casdoor/assets/79890642/9db34958-3ed8-4c9e-bcf3-3f8faed4b789">

Thank you very much for your support and response!

**Comment by dwzkit** [comment]
I have noticed that the current flow of our payment configuration project goes as follows: Prepare to pay - Register first - Pay - Log in. Our project involves users who have already completed registration and need to upgrade from being free users. For example, they may want to upgrade from a free user to a basic member, from a basic member to an intermediate member, and from an intermediate member to an advanced member. In such cases, the user is already registered and logged in, which means that the payment process doesn't need to go through the Register-Pay-Log in sequence again. Does Casdoor support this kind of workflow?  @Chinoholo0807 @hsluoyz

**Comment by Chinoholo0807** [comment]
@dwzkit  
Currently Casdoor only support flow :  Prepare to pay - Register first - Pay - Log in
1. If you change the `User type` field of user from `normal-user` to `paid-user`, The next time the user logs in, they will jump to the pricing page and select the plan to buy. Currently, users are not supported to proactively upgrade.
![image](https://github.com/casdoor/casdoor/assets/54203997/10203e3f-f687-4287-94b8-0522acef92fa)


3. You can configure the `Return URL` of the product (which is related to the plan) and after payment finish, user will redirect to the `Return URL`
![image](https://github.com/casdoor/casdoor/assets/54203997/0f8d3663-1fe8-4ced-a806-a4afcbf54dee)
![image](https://github.com/casdoor/casdoor/assets/54203997/77ce9b44-ff4c-473f-8348-f09b5316da78)

**Comment by Chinoholo0807** [comment]
@tulalatula 
1. we fix the bug in the latest version ,please update your Casdoor and try again :D
2. After payment finished , Casdoor will auto create subscription for the user ( if the user signup through the flow : Select Plan  - Signup - Pay - Log in )

**Comment by dwzkit** [comment]
> @dwzkit Currently Casdoor only support flow : Prepare to pay - Register first - Pay - Log in
> 
> 1. If you change the `User type` field of user from `normal-user` to `paid-user`, The next time the user logs in, they will jump to the pricing page and select the plan to buy. Currently, users are not supported to proactively upgrade.
>    ![image](https://user-images.githubusercontent.com/54203997/266648021-10203e3f-f687-4287-94b8-0522acef92fa.png)
> 2. You can configure the `Return URL` of the product (which is related to the plan) and after payment finish, user will redirect to the `Return URL`
>    ![image](https://user-images.githubusercontent.com/54203997/266647658-0f8d3663-1fe8-4ced-a806-a4afcbf54dee.png)
>    ![image](https://user-images.githubusercontent.com/54203997/266647757-77ce9b44-ff4c-473f-8348-f09b5316da78.png)

I believe that having users first become registered free users and then choosing projects to upgrade or products to purchase is a very common scenario. However, the process of requiring registration before making a payment is still relatively rare in my opinion. If it's possible to support a flow from registering as a user to making a paid purchase, that would be perfect.

**Comment by hsluoyz** [comment]
@dwzkit plz create new issue. Don't ask questions on a closed issue
