### ISSUE TITLE
Integration Concerns with "Sign-up Page HTML" and "Login Page HTML" Options in Admin Panel

### ISSUE THREAD

**Issue by dwzkit** [casdoor/casdoor#2309]
### Description:
The admin panel provides options for "Sign-up Page HTML" and "Login Page HTML," giving the impression that one can customize the HTML style for these pages. However, it's unclear how to integrate this with the existing sign-up and login form functionalities.
<img width="778" alt="image" src="https://github.com/casdoor/casdoor/assets/41875799/67e96e4e-a4a0-413e-921b-b22a109eef85">

I tried entering custom HTML for the sign-up page, and it replaced the entire content, including the original sign-up form, essentially breaking the registration capability of the page.
<img width="810" alt="image" src="https://github.com/casdoor/casdoor/assets/41875799/9721233a-7e54-44eb-b7d3-06678d5f9646">

While the official documentation does discuss UI customization(https://casdoor.org/docs/application/ui-customization), it doesn't specifically mention or explain the use of the "Sign-up Page HTML" or "Login Page HTML" options in the admin panel. This leaves me unsure whether these features are actually functional and, if they are, how to correctly use them.
### Questions:
- Are the "Sign-up Page HTML" and "Login Page HTML" features fully functional?
- If yes, How can custom HTML be integrated with the existing sign-up and login functionalities?
- Is there a way to include custom HTML without losing the original form elements?
- Is there any documentation or example on how to correctly utilize these options for customization?
### Expected Behavior:
- Ability to add custom HTML while retaining the existing form functionalities for sign-up and login.
### Actual Behavior:
- Adding custom HTML removes the original sign-up and login forms, causing the loss of their functionalities.
### Suggested Solutions:
- Provide documentation or guidelines for integrating custom HTML with existing functionalities.
- Perhaps offer a placeholder or tag within the HTML where the form elements will be inserted, allowing for customization around them.

**Comment by lakkvak** [comment]
Why was the issue closed? I would also like to know why the "Login Page HTML" field is needed, if filling it in completely removes the functionality

**Comment by Sjoerd82** [comment]
Same here...

**Comment by hsluoyz** [comment]
Create new issue
