### ISSUE TITLE
Does Casdoor support redis cluster as a session manager?

### ISSUE THREAD

**Issue by popzones** [casdoor/casdoor#2311]
I modified the app.conf file and I typed the DNS of the redis cluster. But It seems that casdoor can not write data to redis. It seems connect to the read only node.

**Comment by hsluoyz** [comment]
@popzones that feature is provided by Beego, the web framework used by Casdoor, plz ask the Beego community: https://github.com/beego/beego

**Comment by popzones** [comment]
Beego doesn't support cluster mode
