### ISSUE TITLE
Database syncer can't work with null-fields on source table

### ISSUE THREAD

**Issue by netandreus** [casdoor/casdoor#2315]
May be something changed in Casdoor last time. At version ```v1.407.0``` after I start my Database Syncer erros occures:
```
[2023-09-08 09:21:39] sql: Scan error on column index 11, name "confirmation_token": converting NULL to string is unsupported
```
Field ```confirmation_token``` is on my database which is source for Casdoor syncer. I can't just set empty values to ```confirmation_token``` field because I have uniqual index for this field. 

Can you modify Database Syncer so that fields of type NULL are cast to the empty string during syncing process?

P.S. This field is not meaningfull for me. May be earlier Casdoor just ignored fileds not listed in ```Table columns``` setting of Syncer and now it's behavior changed?

**Comment by hsluoyz** [comment]
@netandreus can you check which is the first version to have this issue? Especially v1.402.0 and v1.403.0, because I suspect this commit did the change:

![image](https://github.com/casdoor/casdoor/assets/3787410/3ca1e812-6b45-40f9-860e-398857817381)

**Comment by hsluoyz** [comment]
@netandreus also what DB and version do you use?

**Comment by netandreus** [comment]
@hsluoyz Yes, just give me some time for this. We use ```mysql:8.0.34``` [official docker image from dockerhub](url).

**Comment by netandreus** [comment]
@hsluoyz I checked the versions. Syncer in version 1.402 works fine. Issue first occured in version 1.403. May be it's really because this commit: https://github.com/casdoor/casdoor/commit/7e349c17682863ff8bb50df168dda05f77b8dfec

**Comment by hsluoyz** [comment]
@netandreus I think it's this commit: https://github.com/casdoor/casdoor/commit/fc3866db1c63cf469f7bb77e291e2a8e1faafa05

Can you debug to check which code line throws this error?

**Comment by netandreus** [comment]
@hsluoyz Yes, I did a little research. You were right, problem located at first two lines of [this function](https://github.com/casdoor/casdoor/blob/master/object/syncer_user.go#L35) and it appeared after [this commit](https://github.com/casdoor/casdoor/commit/fc3866db1c63cf469f7bb77e291e2a8e1faafa05#diff-93c8d13a814a48f5b9e9966ba81897dda345d2e4f95a2433704cab427f1e031cR34):

**./object/syncer_user.go**
```
func (syncer *Syncer) getOriginalUsers() ([]*OriginalUser, error) {
	var results []map[string]string
	err := syncer.Ormer.Engine.Table(syncer.getTable()).Find(&results)
	if err != nil {
		return nil, err
	}

	// Memory leak problem handling
	// https://github.com/casdoor/casdoor/issues/1256
	users := syncer.getOriginalUsersFromMap(results)
	for _, m := range results {
		for k := range m {
			delete(m, k)
		}
	}

	return users, nil
}
```
There can be null values at the database, and Xorm can't map null values to ```[]map[string]string``` type. As a solution you can use ```sql.NullString``` type like this:

```
import (
...
"database/sql"
...
)

var results []map[string]sql.NullString
err := syncer.Ormer.Engine.Table(syncer.getTable()).Find(&results)
```
But dependent functions (line ```getOriginalUserMap()```) need to be changed also. I tried changing dependent functions but ran into other errors.

```
(base) andrey@mac current % go run main.go
# github.com/casdoor/casdoor/object
object/syncer_util.go:220:30: cannot use result[strings.Trim(name, " ")] (map index expression of type sql.NullString) as type string in argument to append
object/syncer_util.go:224:13: cannot use result[tableColumnName] (map index expression of type sql.NullString) as type string in assignment
object/syncer_util.go:253:48: cannot use value (variable of type sql.NullString) as type string in argument to util.ParseBool
object/syncer_util.go:255:48: cannot use result["enabled"] (map index expression of type sql.NullString) as type string in argument to util.ParseBool
```


I think you can do this much faster.

### Links
- [Go SQL error "converting NULL to string is unsuported"](https://devtidbits.com/2020/08/03/go-sql-error-converting-null-to-string-is-unsupported/)

**Comment by hsluoyz** [comment]
@netandreus can you check if this commit works? https://github.com/casdoor/casdoor/commit/0fe34c2f53371b207bd3a67bd6875c4d8bbdf507

**Comment by netandreus** [comment]
@halozhy Yep, now it works! Thanks a lot!
