### ISSUE TITLE
Unable to login with not signed up user in OAuth provider

### ISSUE THREAD

**Issue by theburyat** [casdoor/casdoor#2318]
Hello! I added custom OAuth provider into casdoor and users could login with it successfully, my provider could sign up the users, who were not logined yet. Then I setup some roles and permissions, and it's become unable to login with users, who were not logined and signed up in casdoor yet, because casdoor sign up them, but don't set any role. Is there any way to configure provider so it could register new user with any role?

**Comment by theburyat** [comment]
> When you add some permisions, it enters Allow-only mode, anything not explicitly permitted will be denied.
When I include new user into sub users to any role by hands, login is successful. I'd like, that it would be done automatically

**Comment by hsluoyz** [comment]
What roles and permissions have you set?

**Comment by theburyat** [comment]
There are my setup:

Model (default rbac model):
![image](https://github.com/casdoor/casdoor/assets/54956408/55f1fa4b-77c6-4682-838e-a1ab8cd58bce)

Role:
![image](https://github.com/casdoor/casdoor/assets/54956408/14f26681-0fe9-419d-bf38-daa265609438)

Permission:
![image](https://github.com/casdoor/casdoor/assets/54956408/9e17af49-a037-48bb-a244-45c1181adb62)

Users:
![image](https://github.com/casdoor/casdoor/assets/54956408/6ecae99e-e247-49c5-8561-7bcd3bbf39dc)

On the picture with users you can see 2 users. Both of them were created, when I signed in with my custom provider. On the picture with roles I set one of users to "Sub users" by hands, and now I can login to my application with this user. But when I try to login to this app with second user (test2), I see this:
![image](https://github.com/casdoor/casdoor/assets/54956408/412ba21a-b955-40a8-953e-fdb226edcfe1)

If I will add "test2" user to "Sub users" in my Role, I could sign in with this user too, but I want that my provider could do it automatically, when it sign up the user

**Comment by hsluoyz** [comment]
@theburyat plz use Casdoor latest version

From the latest code, you can see, login will only be denied when the permission effect is deny

https://github.com/casdoor/casdoor/blob/b633ecdcf29fec5a828fb4180cf95392b2dad583/object/check.go#L353-L390

**Comment by hsluoyz** [comment]
@theburyat fixed by: https://github.com/casdoor/casdoor/commit/616629ef99bcf49922aa42bc74f40223b1b25664
