### ISSUE TITLE
Tencent SMS send failed

### ISSUE THREAD

**Issue by cold-runner** [casdoor/casdoor#2319]
![1](https://github.com/casdoor/casdoor/assets/86516312/43d8e321-2d0d-48de-97bb-5ec04e9578f0)

When I configured Tencent Cloud SMS to send a test text message, casdoor prompted me to send it successfully, but when I checked the sending record in the background of Tencent Cloud SMS, the text message was not sent successfully. Of course, my mobile phone did not receive the text message.
![2](https://github.com/casdoor/casdoor/assets/86516312/4b9ea5a3-6ed1-48ad-8b41-6aafb0aa3f3b)
And after testing, the text message cannot be sent in the login URL page. This seems to be that casdoor did not correctly parse the template content corresponding to the template code when sending the text message.

I use docker casbin/casdoor ,the image ID is 5433df87883f

**Comment by hsluoyz** [comment]
@cold-runner select country code as "+86":

![image](https://github.com/casdoor/casdoor/assets/3787410/45a0c6ca-b98c-458b-87dc-1a4265beaeb4)

**Comment by cold-runner** [comment]
It is exactly what I have done. The problem does not seem to be what you said, and you have also seen that there are sending records in the Tencent Cloud background, but the content sent does not meet the requirements.

**Comment by hsluoyz** [comment]
@cold-runner your SMS template is wrong, it should not be empty, you need to check your Tencent cloud settings or contact their support:

![image](https://github.com/casdoor/casdoor/assets/3787410/2d235148-2d7f-4129-8f45-7ecf32559e8f)

**Comment by cold-runner** [comment]
![1](https://github.com/casdoor/casdoor/assets/86516312/473ed981-72e2-4796-a080-b5145f2c93de)
![2](https://github.com/casdoor/casdoor/assets/86516312/503c3991-a65e-4501-a7cb-bc1f78f5d70a)
![3](https://github.com/casdoor/casdoor/assets/86516312/7a906a30-efc7-4c8f-8edc-db8f9e2534ce)
Maybe there is something wrong with my configuration. Is my configuration correct?

**Comment by cold-runner** [comment]
![4](https://github.com/casdoor/casdoor/assets/86516312/9ca6f927-3489-4db1-a913-b7e3f187ea97)
I didn't find a description of Tencent Cloud SMS configuration in official documentation and other issues

**Comment by cold-runner** [comment]
I found the problem. The premise of successful sending is that only one variable parameter in the SMS template can be set.

**Comment by hsluoyz** [comment]
@cold-runner what do you mean by "one variable parameter"?

**Comment by cold-runner** [comment]
![1](https://github.com/casdoor/casdoor/assets/86516312/7e0bf8e0-fd3e-4609-a2dd-a91a53f3efe5)
Sending fails when I use the SMS template below, while I can send successfully using the template above. The difference between the two is the number of variable parameters in the template, which is the `{}` part
