### ISSUE TITLE
How to leverage casbin integrated in casdoor for access control in your own application ?

### ISSUE THREAD

**Issue by cold-runner** [casdoor/casdoor#2321]
I know that I can get user information by calling`ParseToken`in `casdoor-go-sdk`; add permission configuration in casdoor, but I don't know how to verify it in my application. The normal method should be to add middleware to the route of the application, but I only found a way to get the Get class such as permission table in `casdoor-go-sdk`. Maybe this middleware needs to be written by yourself? Or is there a more elegant way?

**Comment by ISulimanov** [comment]
@cold-runner Did you try enforce?

https://casdoor.github.io/docs/permission/exposed-casbin-apis

**Comment by cold-runner** [comment]
> @cold-runner Did you try enforce?
> 
> https://casdoor.github.io/docs/permission/exposed-casbin-apis

Yes, I was able to achieve my needs through the enforce method, but I still feel that the configuration is not sensitive enough, which causes me to add a lot of permission tables when configuring permissions and match them multiple times in my third-party app
