### ISSUE TITLE
[Bug]Modify personal password without entering the old password.

### ISSUE THREAD

**Issue by gcorecorp** [casdoor/casdoor#2324]
In casdoor, it is possible to successfully modify personal password without entering the old password.

![CleanShot 2023-09-12 at 09 36 42@2x](https://github.com/casdoor/casdoor/assets/110085341/f122e7c6-6143-460b-aa29-bfe23c20e0dc)

**Comment by gcorecorp** [comment]
1. normal user

**Comment by gcorecorp** [comment]
1. normal user
2. myself
3. https://door.casdoor.com/users/{org}/{username}

**Comment by hsluoyz** [comment]
@gcorecorp fixed by: https://github.com/casdoor/casdoor/commit/1276da4daa606d3a587df147bce98fc7d36fa4da
