### ISSUE TITLE
go 1.21.0 can't call GetOAuthToken function. 

### ISSUE THREAD

**Issue by popzones** [casdoor/casdoor#2327]
It seems can not parse the Json

token, err := casdoorsdk.GetOAuthToken("8269f4308a718ec07add", "fqwfqwfqw")
	if err != nil {
		panic(err)
}

panic: invalid character '<' looking for beginning of value

**Comment by hsluoyz** [comment]
@popzones can you provide the Go backend console output? There should be a panic for this error

**Comment by popzones** [comment]
panic: invalid character '<' looking for beginning of value

goroutine 1 [running]:
main.main()
        /root/code/go_code/main.go:46 +0x17f
exit status 2

**Comment by hsluoyz** [comment]
@popzones can you give the code line? I don't understand `main.go:46 +0x17f`

**Comment by hsluoyz** [comment]
Closed as stale
