### ISSUE TITLE
Can not access application public certificate for non "admin" organization

### ISSUE THREAD

**Issue by netandreus** [casdoor/casdoor#2329]
### Problem
I have two organizations. First is default ```admin``` organization. It has ```cert-built-in``` certificate, and I can read it from this url:
```
http://localhost:8000/api/get-application?id=admin/app-built-in&withKey=1
```
as you mentioned in this comment https://github.com/casdoor/casdoor/issues/2247#issuecomment-1702736588.

Also I have another organization ```org```, which owned certificate ```cert_one```. My application ```app``` has certificate ```one/cert_one```. You say, that i should use ```admin``` (not ```one```) to get public certificate like this. I try to get it like this:
```http://localhost:8000/api/get-application?id=admin/app&withKey=1```
or this
```http://localhost:8000/api/get-application?id=one/app&withKey=1```

When I do this error occures:
```casdoor:runtime error: invalid memory address or nil pointer dereference```

<img width="785" alt="Screenshot 2023-09-13 at 10 20 52 AM" src="https://github.com/casdoor/casdoor/assets/313477/2ffc9648-1917-431d-8733-e3a244f1caba">

But if I change certificate for ```app``` from ```cert_one``` (owned by ```one``` organization) to ```cert-built-in``` (owned by ```admin``` Shared) - all good.

### Questions
1. How can I get public certificate for my ```app``` application, which owned by ```one``` organization?

### Source code

**./controllers/application.go**

```
// GetApplication
// @Title GetApplication
// @Tag Application API
// @Description get the detail of an application
// @Param   id     query    string  true        "The id ( owner/name ) of the application."
// @Success 200 {object} object.Application The Response object
// @router /get-application [get]
func (c *ApiController) GetApplication() {
	userId := c.GetSessionUsername()
	id := c.Input().Get("id")

	application, err := object.GetApplication(id)
	if err != nil {
		c.ResponseError(err.Error())
		return
	}

	if c.Input().Get("withKey") != "" && application.Cert != "" {
		cert, err := object.GetCert(util.GetId(application.Owner, application.Cert))
		if err != nil {
			c.ResponseError(err.Error())
			return
		}

		application.CertPublicKey = cert.Certificate
	}

	c.ResponseOk(object.GetMaskedApplication(application, userId))
}
```

Error in this line: ```application.CertPublicKey = cert.Certificate```

### Related tickets
- [Organization public certificates](https://github.com/casdoor/casdoor/issues/2247)

**Comment by hsluoyz** [comment]
@netandreus fixed by: https://github.com/casdoor/casdoor/commit/450ef49d5f913b2e5bbb380bae02622107bd8f35
