### ISSUE TITLE
work with casdoor in Multi-Tenant App

### ISSUE THREAD

**Issue by HRNasr** [casdoor/casdoor#2331]
What is the proper way to use  casdoor by casdoor-go-sdk in a multi-tenant application  for connect to multiple applications in different organizations? in multi-tenant app work with multi organization in casdoor (per organization one app) 
Please guide me

**Comment by hsluoyz** [comment]
@HRNasr you can initialize a new [Client](https://github.com/casdoor/casdoor-go-sdk/blob/26865e8e3f9a4eb265b0c1afd441b03eaf7f3c10/casdoorsdk/auth.go#L28) for each application
