### ISSUE TITLE
[BUG] While using CAS Auth

### ISSUE THREAD

**Issue by rifkimubarok** [casdoor/casdoor#2333]
in the latest version of Casdoor, when using authentication with CAS technology, an error occurs when performing serviceValidate with the statement
`xml: unsupported type: map[string]interface {}`
<img width="864" alt="image" src="https://github.com/casdoor/casdoor/assets/42726159/ee474280-9416-46ca-a298-3348682faab1">

**Comment by hsluoyz** [comment]
@rifkimubarok hi, can you provide the full URL?

**Comment by rifkimubarok** [comment]
@hsluoyz 
`http://10.10.45.54:8800/cas/built-in/app-built-in/serviceValidate?service=http://localhost:8080/test&ticket=ST-1182554718527291592`

this error show while validate ticket.

**Comment by hsluoyz** [comment]
@rifkimubarok fixed by: https://github.com/casdoor/casdoor/commit/e82c46936daffb4103fbe4baf93832dbb8e2f28b

**Comment by rifkimubarok** [comment]
@hsluoyz thanks

**Comment by hsluoyz** [comment]
@rifkimubarok can you check if it works?

**Comment by rifkimubarok** [comment]
@halozhy the result still error
<img width="1680" alt="image" src="https://github.com/casdoor/casdoor/assets/42726159/1605af71-b2f1-46c3-95b7-7ec1e0d9b14e">

<img width="1680" alt="image" src="https://github.com/casdoor/casdoor/assets/42726159/f2fd8363-4517-48c6-8c8f-d51846bb497f">


`<cas:serviceResponse xmlns:cas="http://www.yale.edu/tp/cas">
  <cas:authenticationSuccess>
    <cas:user>admin</cas:user>
    <cas:proxyGrantingTicket>PGTIOU-61d34c8a-d302-45c5-986d-c01af4f78132</cas:proxyGrantingTicket>
    <cas:attributes>
      <cas:authenticationDate>2023-09-15T18:23:11.116176917+07:00</cas:authenticationDate>
      <cas:longTermAuthenticationRequestTokenUsed>false</cas:longTermAuthenticationRequestTokenUsed>
      <cas:isFromNewLogin>false</cas:isFromNewLogin>
      <cas:userAttributes>
        <cas:attribute name="displayName">Admin</cas:attribute>
        <cas:attribute name="isDefaultAvatar">false</cas:attribute>
        <cas:attribute name="createdTime">2023-09-14T16:12:47+07:00</cas:attribute>
        <cas:attribute name="createdIp">127.0.0.1</cas:attribute>
        <cas:attribute name="ranking">1</cas:attribute>
        <cas:attribute name="isDeleted">false</cas:attribute>
        <cas:attribute name="roles"><nil></cas:attribute>
        <cas:attribute name="phone">12345678910</cas:attribute>
        <cas:attribute name="owner">built-in</cas:attribute>
        <cas:attribute name="id">265de3d1-dcc3-44a4-a4b3-f65279f6cabb</cas:attribute>
        <cas:attribute name="isOnline">false</cas:attribute>
        <cas:attribute name="mfaPhoneEnabled">false</cas:attribute>
        <cas:attribute name="groups"><nil></cas:attribute>
        <cas:attribute name="signinWrongTimes">0</cas:attribute>
        <cas:attribute name="email">admin@example.com</cas:attribute>
        <cas:attribute name="mfaEmailEnabled">false</cas:attribute>
        <cas:attribute name="name">admin</cas:attribute>
        <cas:attribute name="emailVerified">false</cas:attribute>
        <cas:attribute name="isForbidden">false</cas:attribute>
        <cas:attribute name="password">***</cas:attribute>
        <cas:attribute name="countryCode">US</cas:attribute>
        <cas:attribute name="tag">staff</cas:attribute>
        <cas:attribute name="webauthnCredentials"><nil></cas:attribute>
        <cas:attribute name="properties">map[]</cas:attribute>
        <cas:attribute name="permissions"><nil></cas:attribute>
        <cas:attribute name="type">normal-user</cas:attribute>
        <cas:attribute name="isAdmin">true</cas:attribute>
        <cas:attribute name="managedAccounts"><nil></cas:attribute>
        <cas:attribute name="affiliation">Example Inc.</cas:attribute>
        <cas:attribute name="recoveryCodes"><nil></cas:attribute>
        <cas:attribute name="karma">0</cas:attribute>
        <cas:attribute name="score">2000</cas:attribute>
        <cas:attribute name="passwordType">plain</cas:attribute>
        <cas:attribute name="avatar">https://cdn.casbin.org/img/casbin.svg</cas:attribute>
        <cas:attribute name="address">[]</cas:attribute>
        <cas:attribute name="signupApplication">app-built-in</cas:attribute>
      </cas:userAttributes>
    </cas:attributes>
  </cas:authenticationSuccess>
</cas:serviceResponse>`

**Comment by hsluoyz** [comment]
@rifkimubarok can you check the newer v1.418.0 version?

**Comment by rifkimubarok** [comment]
@hsluoyz okay, now CAS AUTH is working properly.
