### ISSUE TITLE
registered users can edit admin properties

### ISSUE THREAD

**Issue by csefe** [casdoor/casdoor#2340]
Hi,
I have set up casdoor with docker compose, and registered a user but I can edit admin properties with registered users account, is that normal?
Thanks.
<img width="1682" alt="Screenshot 2023-09-17 at 19 57 03" src="https://github.com/casdoor/casdoor/assets/8126873/32728a4f-bf28-4828-87a8-46bae3063e54">

**Comment by hsluoyz** [comment]
@csefe All users under the `built-in` organization, including `admin`, will have full administrator privileges on the Casdoor platform: https://casdoor.org/docs/basic/core-concepts#how-does-casdoor-manage-itself

**Comment by csefe** [comment]
Thanks for clarification
