### ISSUE TITLE
[Bug]Failed to save permissions with roles

### ISSUE THREAD

**Issue by anyidea** [casdoor/casdoor#2346]
If i edit and save permissions with roles, errors will be raised as below.
![image](https://github.com/casdoor/casdoor/assets/48710760/b2896484-cbb5-4381-9766-e7ce4cce99da)

![image](https://github.com/casdoor/casdoor/assets/48710760/7acaadaf-d9d6-4576-b24a-05d96b23e8b3)

**Comment by hsluoyz** [comment]
@anyidea the page looks good to me: https://door.casdoor.com/permissions/built-in/permission_example

![image](https://github.com/casdoor/casdoor/assets/3787410/abbf4d6f-841a-4307-9562-ebb7a4ba9f67)
