### ISSUE TITLE
[Feature]Support setting roles for groups

### ISSUE THREAD

**Issue by anyidea** [casdoor/casdoor#2347]
Currently, Casdoor already supports setting roles for users. Can it also support setting roles for groups?

![CleanShot 2023-09-20 at 16 06 20@2x](https://github.com/casdoor/casdoor/assets/48710760/84f64936-e4b4-479e-92fc-db77f63d80c1)

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/f9cc6ed0642b86dd75af5a8bb851c530209bb474
