### ISSUE TITLE
"ID" in OAuth provider's "User mapping" config has no effect

### ISSUE THREAD

**Issue by NexZhu** [casdoor/casdoor#2350]
"ID" in OAuth provider's "User mapping" config has no effect

![image](https://github.com/casdoor/casdoor/assets/4370605/1c69c2fb-4c4e-4e58-b43e-442a1d2db46b)

Because in `controllers/auth.go` `user.Id` is always generated:
https://github.com/casdoor/casdoor/blob/3b2820cbe3b691da4195a4a42968af8f97615567/controllers/auth.go#L622
```go
					user = &object.User{
						Owner:             application.Organization,
						Name:              userInfo.Username,
						CreatedTime:       util.GetCurrentTime(),
						Id:                util.GenerateId(), // <-- Here, not using userInfo.Id
						Type:              "normal-user",
						DisplayName:       userInfo.DisplayName,
						Avatar:            userInfo.AvatarUrl,
						Address:           []string{},
						Email:             userInfo.Email,
						Phone:             userInfo.Phone,
						CountryCode:       userInfo.CountryCode,
						Region:            userInfo.CountryCode,
						Score:             initScore,
						IsAdmin:           false,
						IsForbidden:       false,
						IsDeleted:         false,
						SignupApplication: application.Name,
						Properties:        properties,
					}
```

The resulted `ID` is always a random generated UUID.
![image](https://github.com/casdoor/casdoor/assets/4370605/a834474b-5212-41a7-a108-893ecb302d79)

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/111d1a578659279e826e6999cc2b640a66df7752
