### ISSUE TITLE
Question:  token is not valid yet

### ISSUE THREAD

**Issue by HRNasr** [casdoor/casdoor#2357]
I have problem when login to system with error  (token is not valid yet)  in parsejwttoken function.
how to resolve this problem???

all config in organization and application define is  Casdoor Default

**Comment by hsluoyz** [comment]
@HRNasr what SDK do you use? Did you try the example code at: https://casdoor.org/docs/how-to-connect/sdk/ ?

Can you provide your code to reproduce the issue? and the demo video?

**Comment by hsluoyz** [comment]
@HRNasr use latest version Casdoor and casdoor-go-sdk

**Comment by hsluoyz** [comment]
@HRNasr I don't know how you write your code. But I confirmed these following two examples work:

- https://github.com/casbin/casvisor
- https://github.com/casdoor/casdoor-go-react-sdk-example

You need to refer your code to these above two projects
