### ISSUE TITLE
Question: token is not valid yet in web-app

### ISSUE THREAD

**Issue by HRNasr** [casdoor/casdoor#2358]
I have problem when login to system with error (token is not valid yet) in parsejwttoken function.
how to resolve this problem???

all config in organization and application define is Casdoor Default

**Comment by hsluoyz** [comment]
@HRNasr you don't need to create new and duplicated issues, when you already get answers from: https://github.com/casdoor/casdoor/issues/2357#issuecomment-1732970593

Like I said, I confirmed these following two examples work:

- https://github.com/casbin/casvisor
- https://github.com/casdoor/casdoor-go-react-sdk-example

You need to refer your code to these above two projects
