### ISSUE TITLE
LDAP sync selected users error

### ISSUE THREAD

**Issue by cx2c** [casdoor/casdoor#2364]
curl 'http://127.0.0.1:8000/api/sync-ldap-users?id=organization_76t33t/8d883124-bb7c-461a-9af4-a12a85acbcef' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh;q=0.9,en;q=0.8' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: text/plain;charset=UTF-8' \
  -H 'Cookie: csrftoken=uwPI42NfELE4TBY9loLO0hskr3rUKE1ROc29kxQwo0JJTR67UNMyiOgCja1uyZHn; casdoor_session_id=db484d7c0951e2fea114f2eba2e85cfe' \
  -H 'Origin: http://127.0.0.1:8000' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://127.0.0.1:8000/ldap/sync/organization_76t33t/8d883124-bb7c-461a-9af4-a12a85acbcef' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '[{"uidNumber":"277","uid":"zhangsan","cn":"李三","gidNumber":"","uuid":"79c8b0e0-883d-1039-96f8-29097a96d128","userPrincipalName":"","displayName":"","Mail":"","email":"zhangsan@xx.com","EmailAddress":"","TelephoneNumber":"","mobile":"","MobileTelephoneNumber":"","RegisteredAddress":"","PostalAddress":"","groupId":"1180","address":"","memberOf":""}]' \
  --compressed

2023/09/26 09:55:18.592 [I]  (172.17.0.1: ) subOwner = built-in, subName = admin, method = POST, urlPath = /api/sync-ldap-users, obj.Owner = , obj.Name = , result = allow
2023/09/26 09:55:18.713 [C]  the request url is  /api/sync-ldap-users
2023/09/26 09:55:18.713 [C]  Handler crashed with error runtime error: invalid memory address or nil pointer dereference
2023/09/26 09:55:18.713 [C]  /usr/local/go/src/runtime/panic.go:884
2023/09/26 09:55:18.713 [C]  /usr/local/go/src/runtime/panic.go:260
2023/09/26 09:55:18.713 [C]  /usr/local/go/src/runtime/signal_unix.go:835
2023/09/26 09:55:18.713 [C]  /go/src/casdoor/object/user.go:915
2023/09/26 09:55:18.713 [C]  /go/src/casdoor/object/user.go:624
2023/09/26 09:55:18.713 [C]  /go/src/casdoor/object/ldap_conn.go:330
2023/09/26 09:55:18.713 [C]  /go/src/casdoor/controllers/ldap.go:271
2023/09/26 09:55:18.713 [C]  /usr/local/go/src/reflect/value.go:584
2023/09/26 09:55:18.713 [C]  /usr/local/go/src/reflect/value.go:368
2023/09/26 09:55:18.713 [C]  /go/pkg/mod/github.com/beego/beego@v1.12.12/router.go:897
2023/09/26 09:55:18.713 [C]  /usr/local/go/src/net/http/server.go:2947
2023/09/26 09:55:18.713 [C]  /usr/local/go/src/net/http/server.go:1991
2023/09/26 09:55:18.713 [C]  /usr/local/go/src/runtime/asm_amd64.s:1594
2023/09/26 09:55:18.713  [HTTP] http: superfluous response.WriteHeader call from github.com/beego/beego/context.(*Response).WriteHeader (context.go:240)

**Comment by cx2c** [comment]
把uuid字段拿掉之后可以正常返回200，但是用户实际上没有同步成功

**Comment by hsluoyz** [comment]
@cx2c fixed by: https://github.com/casdoor/casdoor/commit/981908b0b6eade907435544e4cee462b782a26c1
