### ISSUE TITLE
The editing of the enforcer data is abnormal. Data of type g cannot be added

### ISSUE THREAD

**Issue by ginlink** [casdoor/casdoor#2365]
- Add a g type, prompt success
![image](https://github.com/casdoor/casdoor/assets/35068110/bab52800-d60c-47be-b23d-677005a1a1c4)

- But the data disappeared on the front page. Although the data exists in the database, it is of type p.
![image](https://github.com/casdoor/casdoor/assets/35068110/21e79d05-0e4b-476c-8e6d-0f56b442b3e9)

- version: v1.423.0

**Comment by hsluoyz** [comment]
@ginlink fixed by: https://github.com/casdoor/casdoor/commit/81a8b91e3f58a82da16abc3f8f4fb5dab508134b
