### ISSUE TITLE
Records and Webhooks occurs even if event did't happend

### ISSUE THREAD

**Issue by ISulimanov** [casdoor/casdoor#2368]
**Problem:** 
If some exception happens during request handling (such /api/update-user and e.t.c. ) we still will have new Record and webhook call. 

**Reason:** 
	`beego.InsertFilter("*", beego.BeforeRouter, routers.RecordMessage)`

**Proposal:** 
Change to `beego.InsertFilter("*", beego.AfterExec, routers.RecordMessage)`

**Benefits:**
- No false records / webhook calls in case of panic 
- There is option to include response status code to record  / webhook
- No possibility to race condition ( when webhook calls lead to API request before the entity is updated in the database

**Comment by hsluoyz** [comment]
@ISulimanov sounds good, can you make a PR?
