### ISSUE TITLE
Users imported from LDAP, after logging in from Lark, can they automatically be associated using email or name?

### ISSUE THREAD

**Issue by cx2c** [casdoor/casdoor#2370]
Currently, after importing users from LDAP and then integrating with Lark third-party login, it results in two separate users.

I'd like to ask about the proper use: I want to utilize LDAP, including importing users and password login. On this premise, I also want to support Lark login. How should I implement this?

**Comment by hsluoyz** [comment]
@cx2c after importing users from LDAP, do your user have Email?

**Comment by cx2c** [comment]
> @cx2c after importing users from LDAP, do your user have Email?

yes. 
but the user name  from feishu is in chinese

**Comment by hsluoyz** [comment]
@cx2c Casdoor usually uses Email to link two users. If the existing user A has Email: abc@example.com, the new user B from Lark has the same Email: abc@example.com.  Is this true?

This is impossible, because Casdoor doesn't allow two users in same org to have same Email

**Comment by cx2c** [comment]
> @cx2c Casdoor usually uses Email to link two users. If the existing user A has Email: [abc@example.com](mailto:abc@example.com), the new user B from Lark has the same Email: [abc@example.com](mailto:abc@example.com). Is this true?
> 
> This is impossible, because Casdoor doesn't allow two users in same org to have same Email

The  Organization and the Email are the same, the first user is from LDAP, the last user is from Lark.
<img width="1571" alt="image" src="https://github.com/casdoor/casdoor/assets/13431516/277fb542-3dfe-49ce-b198-143a8b609474">

**Comment by cx2c** [comment]
> @cx2c Casdoor usually uses Email to link two users. If the existing user A has Email: [abc@example.com](mailto:abc@example.com), the new user B from Lark has the same Email: [abc@example.com](mailto:abc@example.com). Is this true?
> 
> This is impossible, because Casdoor doesn't allow two users in same org to have same Email

ok 👌
<img width="304" alt="image" src="https://github.com/casdoor/casdoor/assets/13431516/9db4a47c-5a3a-4770-ac8d-f0aad460f32e">

**Comment by hsluoyz** [comment]
@cx2c it's great! Just enabling the `Enable Email linking` button proved to be a good solution!
