### ISSUE TITLE
bug: enforce error when check login permission with multiple models

### ISSUE THREAD

**Issue by leo220yuyaodog** [casdoor/casdoor#2373]
https://github.com/casdoor/casdoor/blob/7e0bce2d0f3c1e70071614932cda3b4e43d09d2c/object/check.go#L375-L381

As the line 375 shows, It get the enforcer from permission:
https://github.com/casdoor/casdoor/blob/7e0bce2d0f3c1e70071614932cda3b4e43d09d2c/object/check.go#L375

Then perform the function `Enforce()`,  It is a hard-code 3 size request, but the enfocers maybe have different models that define different size of request. For example, the RBAC with domian model. It needs 4 sizes of request. So it can throw an error belows:

![image](https://github.com/casdoor/casdoor/assets/71440988/51fbce51-87c7-41e2-b4cb-840d4ad049d3)

https://github.com/casdoor/casdoor/blob/7e0bce2d0f3c1e70071614932cda3b4e43d09d2c/object/check.go#L378

**Comment by hsluoyz** [comment]
@leo220yuyaodog can you make a PR to fix it?
