### ISSUE TITLE
bug: Casdoor Provider for Okta broken

### ISSUE THREAD

**Issue by julzds** [casdoor/casdoor#2374]
The provider for Okta seems to be broken. When configured as described in the docs here: [https://casdoor.org/docs/provider/oauth/okta](https://casdoor.org/docs/provider/oauth/okta)
The login with the credentials of the okta user (calling the `/v1/authorize` endpoint) seems to be working correctly but when casdoor is trying to call `/v1/token` right before calling the callback url of the application the following error occurred: `There was a problem signing you in. Post “/v1/token”: unsupported protocol scheme “”` 

This error looks a lot like it originates from faulty or empty hosturl. We were able to workaround this problem by using a custom provider with the following urls:
Auth URL: https://dev-123456.okta.com/oauth2/default/v1/authorize
Token URL: https://dev-123456.okta.com/oauth2/default/v1/token
UserInfo URL: https://dev-123456.okta.com/oauth2/default/v1/userinfo

**Comment by hsluoyz** [comment]
@julzds did you provide the `domain` parameter? It should be something like:

![image](https://github.com/casdoor/casdoor/assets/3787410/773af832-ba2f-4c53-8069-b06d7c111246)

See docs: https://casdoor.org/docs/provider/oauth/okta/

![image](https://github.com/casdoor/casdoor/assets/3787410/6fe92fb5-d43d-45ac-a0d5-61b9703ee3ac)

**Comment by julzds** [comment]
Hi @hsluoyz,
yes I configured the provider as described in the docs and used the domain of our dev account at okta which looks like this: [https://dev-123456.okta.com/oauth2/default](https://dev-123456.okta.com/oauth2/default)
