### ISSUE TITLE
Error in login

### ISSUE THREAD

**Issue by HRNasr** [casdoor/casdoor#2382]
Hello
I downloaded and installed the latest version of casdoor (1.427.0) from the site and run it without any changes (just creating a database and entering its information in the settings file). But when I log in, I get the following error message:
403  nomatch  POST /api/login

To solve this problem, I have to make a special setting before running

**Comment by hsluoyz** [comment]
@HRNasr can you try v1.428.0?

**Comment by zelangchen** [comment]
how did you  solve this problem ?

**Comment by sosofun123** [comment]
Has this issue been resolved in version 1.428.0?

**Comment by sosofun123** [comment]
> @HRNasr can you try v1.428.0?

The issue still exists.

**Comment by hsluoyz** [comment]
@HRNasr @zelangchen @sosofun123 try latest v1.429.0: https://github.com/casdoor/casdoor/releases/tag/v1.429.0
