### ISSUE TITLE
bug: Twilio SMS template is not replaced by exact verification code

### ISSUE THREAD

**Issue by HRNasr** [casdoor/casdoor#2386]
when set user mfa to sms. sms send to user but not totp in sms.
It is the same in provider SMS test section. I have to do a special configuration.
the template is       verification code is %s

**Comment by hsluoyz** [comment]
@HRNasr which SMS provider do you use? Plz provide screenshot and video for SMS test

**Comment by hsluoyz** [comment]
@HRNasr so what's the problem?

What to expect and what you got?
