### ISSUE TITLE
[Question] Do we have any function to limit user login 

### ISSUE THREAD

**Issue by zhenyu2025** [casdoor/casdoor#2392]
hi team, I want to limit user to login some application, like whitelist/blacklist for user and OIDC target domain. do we have any function about it? 

my test cases:

| user | request domain | whitelist user | blacklist domain | login result|
| ------------- | -------------| ------------- |------------- | ------------- |
| a  | w1.test.com  | yes | no | success |
| a  | w2.test.com    | yes | yes | success |
| a  | w2.test.com    | no | yes | failed |
| b  | w1.test.com    | no | no | success |

**Comment by hsluoyz** [comment]
@zhenyu2025 yes, you can configure permissions to restrict certain users to log into certain applications, see docs: https://casdoor.org/docs/permission/permission-configuration
