### ISSUE TITLE
Logout event will return null result, when Webhook

### ISSUE THREAD

**Issue by Sun-FreePort** [casdoor/casdoor#2399]
when user logout, I can't got real user info, this webhook result:

```json
{
	"id": 0,
	"owner": null,
	"name": "a69c8eaf-eb06-432d-b856-edc522b92369",
	"createdTime": "2023-10-13T06:51:08Z",
	"organization": null,
	"clientIp": "192.168.65.1",
	"user": null,
	"method": "POST",
	"requestUri": "\/api\/logout",
	"action": "logout",
	"object": null,
	"isTriggered": false,
	"extendedUser": null
}
```

**Comment by hsluoyz** [comment]
@Sun-FreePort 

1. Add `logout` to events
2. Enable `Is user extened`
3. Make sure `extendedUser` has no-empty value in Preview

![image](https://github.com/casdoor/casdoor/assets/3787410/502fbafb-3ccc-44a0-b958-31443631db07)

**Comment by Sun-FreePort** [comment]
@hsluoyz Hi.

Yep, I still keep enabled your setting, but result still keep empty. so I print more information in there:

- Casdoor version: 版本: [v1.432.0](https://github.com/casdoor/casdoor/releases/tag/v1.432.0)
- My system: Windows 10 64x
- Docker from [offical all in one](https://hub.docker.com/r/casbin/casdoor-all-in-one)
- Use organizations: build-in
- Use user (logout it): admin

If you need any information, tell me please.

**Comment by Sun-FreePort** [comment]
> @hsluoyz Hi.
> 
> Yep, I still keep enabled your setting, but result still keep empty. so I print more information in there:
> 
> * Casdoor version: 版本: [v1.432.0](https://github.com/casdoor/casdoor/releases/tag/v1.432.0)
> * My system: Windows 10 64x
> * Docker from [offical all in one](https://hub.docker.com/r/casbin/casdoor-all-in-one)
> * Use organizations: build-in
> * Use user (logout it): admin
> 
> If you need any information, tell me please.

Other `build-in` user to logout would tell me empty result.

this is my screen on Casdoor backend:

![screenshot-20231013-160534](https://github.com/casdoor/casdoor/assets/19473984/49c93ce5-3263-403a-bae8-5b298a02ca38)

**Comment by hsluoyz** [comment]
@Sun-FreePort fixed by: https://github.com/casdoor/casdoor/commit/69b144d80f927dd886bb6dc72b21980b1d67ba8e
