### ISSUE TITLE
Page user profile without field to update groups

### ISSUE THREAD

**Issue by gtjadsonsantos** [casdoor/casdoor#2408]
https://github.com/casdoor/casdoor/assets/42282908/5e4108cc-09d3-49a1-aee2-654bcb497d7e

Casdoor Version: v1.435.0

**Comment by hsluoyz** [comment]
@gtjadsonsantos you should add `Groups` to "Account items" like: https://door.casdoor.com/organizations/casbin#:~:text=profile%20public%20%3A-,Account%20items,-%3A

see docs: https://casdoor.org/docs/organization/accountCustomization/

![image](https://github.com/casdoor/casdoor/assets/3787410/b2420157-907e-4385-82f2-54bd59c74f2c)
