### ISSUE TITLE
Use casdoor to create organizations, users, and applications, and use casbin to control access to that user, but it does not take effect

### ISSUE THREAD

**Issue by qq1176914912** [casdoor/casdoor#2411]
I created the organization using casdoor, created applications and users for the organization, and created access control permissions for the organization using casbin. My executor:
![image](https://github.com/casdoor/casdoor/assets/79817742/d7903064-ed09-49b3-bed9-3defff28f638)
My Model：
`[request_definition]
r = subOwner, subName, method, urlPath, objOwner,objName

[policy_definition]
p = subOwner, subName, method, urlPath, objOwner,objName

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (r.subOwner == p.subOwner || p.subOwner == "*") && \
    (r.subName == p.subName || p.subName == "*") && \
    (r.method == p.method || p.method == "*") && \
    (r.urlPath == p.urlPath || p.urlPath == "*") && \
    (r.objName == p.objName || p.objName == "*") && \
    (r.objOwner == p.objOwner || p.objOwner == "*")`
My Organization：
![image](https://github.com/casdoor/casdoor/assets/79817742/5fe514d8-41e5-4654-885c-25cdc47dc21b)
My User：
![image](https://github.com/casdoor/casdoor/assets/79817742/303aeeba-4f77-4e53-837b-7348e7b6d4f8)
My app
![image](https://github.com/casdoor/casdoor/assets/79817742/3d848741-e139-449f-bc0a-780d89ae67c3)
My Authority
![image](https://github.com/casdoor/casdoor/assets/79817742/493101a8-225d-4e47-ae7e-2b149de9662a)
But when I log in to the root user I created, I still do not have permission to add the actuator：
![image](https://github.com/casdoor/casdoor/assets/79817742/4e59ab15-06f9-4ff2-9518-fc347cc6979c)
Why is this, am I missing any key steps?
If needed, I can provide my SQL storage file.

**Comment by qq1176914912** [comment]
My project runs locally after downloading the git project. The casbin model and permission configuration refer to the default admin configuration

**Comment by qq1176914912** [comment]
After debugging, it was found that all the internal policies of the casdoor were written dead here：
![image](https://github.com/casdoor/casdoor/assets/79817742/a05c9c91-d293-4bdc-b5aa-9d055b082802)
So guess, casdoor calls the internal API interface, and all the policies here are unrelated to the data we configured in the casbin executor, without going through the database

**Comment by hsluoyz** [comment]
@qq1176914912 fixed by: https://github.com/casdoor/casdoor/commit/a10548fe732a55c585971095c61956a1dff40207
