### ISSUE TITLE
[feature request] casdoor should allow user to specific frontend_origin for authorization_endpoint

### ISSUE THREAD

**Issue by link89** [casdoor/casdoor#2414]
When running `casdoor` in docker container, the other app will access it via docker internal network by the service name `casdoor`: http://casdoor/.well-known/openid-configuration. Since `casdoor` will use the same origin for all url resource in the openid-configuration document, which make the frontend url `authorization_endpoint` is also using the origin `casdoor`. This will lead to a frontend error of wrong host. I find this problem when I am building a docker-compose for casdoor + minio as a dev environment.

I think casdoor should allow user to specific the `frontend_origin` besides of just `origin`, so that when using inside docker, the user can set `frontend_origin` to `http://127.0.0.1:8000` and `origin` (backend origin) to `http://casdoor:8000`. 

Currently the code seems not allow https://github.com/casdoor/casdoor/blob/cbdeb91ee81a43f570e620e7c6fbec5cb28b70cb/object/oidc_discovery.go#L62C8-L113

**Comment by hsluoyz** [comment]
@link89 fixed by: https://github.com/casdoor/casdoor/commit/fbc603876f9314e198046191738f7a2b175fbc85

Use `originFrontend` in app.conf
