### ISSUE TITLE
Add custom fields to sign up page

### ISSUE THREAD

**Issue by ireneeromero** [casdoor/casdoor#2415]
I need to be able to add custom fields to the registry of my application and not only the default ones. 

More specifically I would need a field that is a dropdown where you can choose all the elements of the dropdown that you want. It would be something similar to the Country/Region field but with the functionality mentioned above.
![image](https://github.com/casdoor/casdoor/assets/61683312/eea1ece9-2da5-4f8b-b6bc-20595bb7f9f9)

Does anyone know if it is possible or how it would be done?

**Comment by hsluoyz** [comment]
@ireneeromero see: https://casdoor.org/docs/application/signup-items-table

**Comment by ireneeromero** [comment]
I had already taken a look at that page, but it does not solve what I want.

I need a field with a custom name, and the possible values to be displayed in a previously defined dropdown. 

For example, a field called "Hobbies" and that the user when registering can choose between playing soccer, watching series, playing tennis, painting or cooking. And that he can choose as many hobbies as he wants, without repeating from the list.

**Comment by ireneeromero** [comment]
I had already taken a look at that page, but it does not solve what I want.

I need a field with a custom name, and the possible values to be displayed in a previously defined dropdown.

For example, a field called "Hobbies" and that the user when registering can choose between playing soccer, watching series, playing tennis, painting or cooking. And that he can choose as many hobbies as he wants, without repeating from the list.

**Comment by frankie-zeng** [comment]
suppose need re-open the issue

**Comment by hsluoyz** [comment]
Support single-choice and multiple-choices signup items

![image](https://github.com/user-attachments/assets/ac392419-04a6-4be1-b610-b65e21ca8e1d)
