### ISSUE TITLE
email provider not work

### ISSUE THREAD

**Issue by arrow2012** [casdoor/casdoor#2418]
I have set email provider 
<img width="1959" alt="image" src="https://github.com/casdoor/casdoor/assets/46478986/04fe76b8-f1ac-4640-b237-a3642a511f32">
<img width="1150" alt="image" src="https://github.com/casdoor/casdoor/assets/46478986/979dbac6-1d54-4bfa-98e2-bccd64bcdb97">

when I reset password with email address , comes with error

<img width="1136" alt="image" src="https://github.com/casdoor/casdoor/assets/46478986/15664c39-8782-49d9-92cb-a11b84405b4b">

**Comment by hsluoyz** [comment]
@arrow2012 add the Email provider to the application's `Providers` list, error message improved here: https://github.com/casdoor/casdoor/commit/3f535917517d926f85c6e9273f93dd8700107ca7

**Comment by arrow2012** [comment]
change password with error: Missing parameter

<img width="924" alt="image" src="https://github.com/casdoor/casdoor/assets/46478986/6459c4ad-0a3c-4b01-9170-2fc3ae913bb2">
