### ISSUE TITLE
reset password with email  error

### ISSUE THREAD

**Issue by arrow2012** [casdoor/casdoor#2419]
<img width="1178" alt="image" src="https://github.com/casdoor/casdoor/assets/46478986/3862f881-750c-4c7e-9e63-353a635199bf">
<img width="1007" alt="image" src="https://github.com/casdoor/casdoor/assets/46478986/f7a83e86-944b-44dc-912e-46074b790f75">

**Comment by arrow2012** [comment]
but email code is correct ,then next input password and confirm .
then I click change password again  show Missing parameter
<img width="1128" alt="image" src="https://github.com/casdoor/casdoor/assets/46478986/e2b4e021-6d1b-47be-b571-6c13896c192c">

**Comment by hsluoyz** [comment]
@arrow2012 if you keep creating such simple question, I suggest you asking at Discord: https://discord.gg/5rPsrAzK7S instead of here. The github issues are for more complicated questions, bug reports, etc.

**Comment by arrow2012** [comment]
输入手机号码
手机号码无效

**Comment by arrow2012** [comment]
<img width="829" alt="image" src="https://github.com/casdoor/casdoor/assets/46478986/73ae4281-16fd-4023-9e41-6a6e38cab157">
phone number is correct ,but invaild

**Comment by arrow2012** [comment]
please invite me disacord again

**Comment by arrow2012** [comment]
old password in db is 123456, how can I reset password ?
