### ISSUE TITLE
[Bug]Unable to reset the password via the 'forgot password' feature

### ISSUE THREAD

**Issue by anyidea** [casdoor/casdoor#2423]
When I follow the steps to reset my password,  I receive an incorrect password error message. 
If I submit the form for the second time, I receive missing parameters error message.

![CleanShot 2023-10-19 at 16 57 55@2x](https://github.com/casdoor/casdoor/assets/48710760/1d3cd2d5-ecbf-473a-a675-9ebab8b5a158)

**Comment by hsluoyz** [comment]
@anyidea hi, can you make a PR to fix it?

**Comment by anyidea** [comment]
Same with issue #2419

**Comment by anyidea** [comment]
> @anyidea hi, can you make a PR to fix it?

ok
