### ISSUE TITLE
Cannot login on linux platform, but it is ok on windows

### ISSUE THREAD

**Issue by i0gan** [casdoor/casdoor#2424]
2023/10/19 17:39:59.210 [D]  | 113.89.200.186| 403 |   1.512234ms| nomatch| POST     /api/login

**Comment by i0gan** [comment]
Post data to /api/login, but reponse 403
{"application":"app-built-in","organization":"built-in","username":"admin","password":"123","autoSignin":true,"type":"login"}

**Comment by hsluoyz** [comment]
@i0gan show your:

1. Demo video
2. Browser URL
3. `Host` field of the 403 request
4. `Origin` field of the 403 request

**Comment by hsluoyz** [comment]
1. It has Cypress UI test for both PR and direct commits: https://github.com/casdoor/casdoor/tree/master/web/cypress/e2e
2. The community has its development cycle and pace. If you don't like frequent new commits, just stay on a old code branch and avoid updating it.
3. I can't reproduce your issue on Ubuntu 22.04 and http://localhost:8000

Without further input as asnwering my questions, this issue will be closed.

**Comment by i0gan** [comment]
@hsluoyz Thanks bro for your patient answer!
