### ISSUE TITLE
[Bug]Respect the is-read-only settings in the syncer.

### ISSUE THREAD

**Issue by anyidea** [casdoor/casdoor#2426]
![CleanShot 2023-10-19 at 18 08 07@2x](https://github.com/casdoor/casdoor/assets/48710760/0f00157b-9e2b-44a6-af21-5fcc48de5fc9)

Currently, despite enabling the read-only option in the synchronizer, modifying user information and adding new users still results in synchronization with the external table.

**Comment by hsluoyz** [comment]
@anyidea hi, can you make a PR to fix it?
