### ISSUE TITLE
Question: how can we change the SAML canonicalization and Transform method

### ISSUE THREAD

**Issue by jump2cn** [casdoor/casdoor#2428]
I found the allowed canonicalization method 'xml-c14n' in pysaml2, not what the Casdoor is using (xml-c14n11), so how can I switch my saml response using 'xml-c14n'?

FYI: https://github.com/IdentityPython/pysaml2/issues/864

**Comment by hsluoyz** [comment]
@anyidea @jump2cn can you make a PR to fix it?

**Comment by hsluoyz** [comment]
@jump2cn fixed by: https://github.com/casdoor/casdoor/commit/22b57fdd23f32937631bffc0dd7f254037447121

Enable `Enable SAML C14N10` switch in the application edit page

![image](https://github.com/casdoor/casdoor/assets/3787410/87b0e3c9-9516-48aa-ab0e-70ea02bd2cfd)

**Comment by jump2cn** [comment]
hi @hsluoyz ,  sorry, maybe the URL I listed confused you. In the new code we can get `REC-xml-c14n-20010315`  in the response,
but [SAML recommended canonicalization method](https://github.com/IdentityPython/pysaml2/issues/864#issuecomment-1200419652) are :

-    http://www.w3.org/2001/10/xml-exc-c14n#
 -   http://www.w3.org/2001/10/xml-exc-c14n#WithComments
