### ISSUE TITLE
Table permission_rule has column id but struct has not related field

### ISSUE THREAD

**Issue by i0gan** [casdoor/casdoor#2432]
[xorm] [warn]  2023/10/20 16:27:42.033884 Table permission_rule has column id but struct has not related field
When I add a user in Role Edit page to bind, It's too slow to handle this request. and server log shows "Table permission_rule has column id but struct has not related field", I have 172 permissions in my casdoor system. just a little bit permissions.

**Comment by hsluoyz** [comment]
@i0gan your DB is old. Delete your DB or DB table and restart

**Comment by i0gan** [comment]
@hsluoyz Thanks bro!

**Comment by agedcat** [comment]
I have the same question.

![image](https://github.com/casdoor/casdoor/assets/76728773/d0433deb-cc11-4081-93e6-0e2f239dbf87)

db: mariadb
version:10.8

**Comment by wuxiao-ling197** [comment]
@rnik12 hello,I have the same problem and I can`t create my own organization ,but I didn`t find the new db file,how can I get it? Please~

**Comment by hsluoyz** [comment]
Create new issue if needed, this issue has stopped appending
