### ISSUE TITLE
Provide a faster single sign-on experience for logged-in users

### ISSUE THREAD

**Issue by HanadaLee** [casdoor/casdoor#2433]
Currently, casdoor supports the function of automatically logging in when visiting another site after logging in on one site. But the current login experience is not good.
![image](https://github.com/casdoor/casdoor/assets/33758411/1efb5aac-9ade-4773-9999-2464a553deae)
When a user visits site A and completes the login using single sign-on. At this time, if he visits site B, site B will also redirect him to the login interface. After the redirection, the following things will happen:
1. Load the home page and static resources
2. Load the login interface
3. Display logged in user information
4. Login detected and automatically redirected

![image](https://github.com/casdoor/casdoor/assets/33758411/262e747c-1fed-43bf-ae87-af11377fb7aa)

（The picture above shows a login page. Note that the user has clearly logged in, but he has stayed on this page for more than 10 seconds, waiting for the entire page to load and automatically redirecting back to the site he wishes to log in to.）

The entire redirection process may last for more than 10 seconds, and a login box that requires entering the account and password appears. The user even mistakenly thinks that he needs to enter the account and password again to log in. As a result, the redirection is triggered when the account and password are entered halfway. This greatly affects the single sign-on experience. 

For comparison, CAS is unaware of single sign-on. When site B redirects to CAS, CAS will find that the user has logged in and will directly initiate a 302 jump instead of loading the login box first and then slowly triggering the jump logic.

Therefore I want to implement the following logic:

When the application redirects to Casdoor, it should be determined as early as possible whether the user is logged in. When it is found that the user is logged in, the current login logic is interrupted, the login process is directly completed and redirected back to the application. Users should not perceive the existence of Casdoor when they visit site B after logging in, but just feel that they have been redirected several times.

**Comment by hsluoyz** [comment]
@HanadaLee can you make a PR to fix it?

**Comment by HanadaLee** [comment]
> @HanadaLee can you make a PR to fix it?

Sorry, I am not familiar with golang code or frontend. I am just an operation and maintenance engineer. This is just a suggestion for my current login process.

**Comment by hsluoyz** [comment]
@HanadaLee fixed by: https://github.com/casdoor/casdoor/commit/6ef2b5178225f657f09e7960e1a8d7a70e2ea068
