### ISSUE TITLE
ARM image is deleted

### ISSUE THREAD

**Issue by HanadaLee** [casdoor/casdoor#2434]
The original distribution provided an official ARM64 build image, but it was suddenly removed in recent versions. (I usually update only once every few versions, so I just now discovered that the ARM64 build has been deleted from the official image library)

I'm running casdoor with an arm64 server and now I have to build my own CI/CD service to build the casdoor image for arm64

![image](https://github.com/casdoor/casdoor/assets/33758411/5d7dda6a-ea24-473e-bd7b-5b2e0e9384a0)

Is there any reason preventing ARM64 images from being provided anymore? Although the proportion of servers using ARM is relatively small, I think it is very necessary to provide ARM64 images.

**Comment by hsluoyz** [comment]
@HanadaLee see: https://github.com/casdoor/casdoor/issues/2416#issuecomment-1766442931

The Arm64 build makes the CI 10 times slower in usual days and recently it just causes CI to fail, so totally stopped the release process. We don't have more resources to fix/maintain it, so just removed it.

If anyone could fix that bug (slow and stop), and test well in his own fork. We are happy to have it back (by merging the PR). But we won't put more resources on it ourselves.

**Comment by hsluoyz** [comment]
Thanks to this PR: https://github.com/casdoor/casdoor/pull/2969 , the arm64 image is back starting from v1.621.0: https://hub.docker.com/r/casbin/casdoor/tags
