### ISSUE TITLE
Handler crashed with error the maximum policy_definition field number cannot exceed 5, got 6

### ISSUE THREAD

**Issue by agedcat** [casdoor/casdoor#2435]
When I create a permission, I got "Handler crashed with error the maximum policy_definition field number cannot exceed 5, got 6".

![image](https://github.com/casdoor/casdoor/assets/76728773/710d26f2-82bd-4616-9eca-f5cf0eb3aa7f)

![image](https://github.com/casdoor/casdoor/assets/76728773/127fdbba-ab1b-435f-aef1-acd8198ddcbc)

version:
latest version

**Comment by hsluoyz** [comment]
@agedcat the error has been exposed to frontend: https://github.com/casdoor/casdoor/commit/37744d6cd77494491daf46db2b7a504c83d8ec65

The reason for the error is very straight-forward. You cannot use `api-model` here. Choose the other one, `user-model` or create your own Casbin model.

![image](https://github.com/casdoor/casdoor/assets/3787410/7a6c4957-5eed-4f6f-9dfe-0fff8e19b824)

**Comment by agedcat** [comment]
Thanks.
