### ISSUE TITLE
the model: for permission: built-in/permission_i9qkgr is not found

### ISSUE THREAD

**Issue by agedcat** [casdoor/casdoor#2436]
When I create a permission, then I click the "save"  buttun, a error occured.

![image](https://github.com/casdoor/casdoor/assets/76728773/da32cd51-078a-4d70-a50e-09b9dab4d49c)

No addtinal config. Just default config.

![image](https://github.com/casdoor/casdoor/assets/76728773/8d81ca63-93b2-4630-98b7-453283316e67)

**Comment by hsluoyz** [comment]
@agedcat as it said, model should not be empty
