### ISSUE TITLE
index.html not found in Production Mode on Windows

### ISSUE THREAD

**Issue by ankexun** [casdoor/casdoor#2441]
In the Windows platform, when installing according to the document at https://casdoor.org/zh/docs/basic/server-installation, Development Mode works properly. However, in Production Mode, there's an error indicating "web/build/index.html" cannot be found. I suspect this is due to the fact that on the Windows platform, the path uses backslashes.

**Comment by hsluoyz** [comment]
@ankexun Go and Casdoor handles Windows path well. The error message will show the full path of index.html Casdoor requires. And check if that path exists.

**Comment by ankexun** [comment]
错误信息和目录结构如下
![image](https://github.com/casdoor/casdoor/assets/28135520/56613cb4-f0a9-40c7-a2fb-a4575906b26e)
![image](https://github.com/casdoor/casdoor/assets/28135520/bc84d3a0-bc4e-4f35-84f0-812c0e3732a3)

**Comment by hsluoyz** [comment]
Cannot reproduce this issue
