### ISSUE TITLE
[bug?]The 'Is deleted' option conflicts with the introduction

### ISSUE THREAD

**Issue by qq1176914912** [casdoor/casdoor#2444]
If I currently have an account (test) that is an organization administrator, I log in to this account using a browser, and then log in to admin using another browser. At this time, I use the admin account to delete the test account by checking 'IS delete'“
![image](https://github.com/casdoor/casdoor/assets/79817742/ce1b33df-436f-4e8c-b0af-91df8d8d71ca)
At this point, the menu in the browser where I logged in to the test account can still access editing, deletion, modification, and other operations normally. Only when I log in again will I be prompted that the account does not exist. If I follow the prompt in 'deleted': No operation can be performed, should I check this option and even if the test account does not exit, I can see the menu, But the access should all be 403 (similar to checking the organization administrator option), is this a bug?

**Comment by hsluoyz** [comment]
@qq1176914912 fixed by: https://github.com/casdoor/casdoor/commit/f6a7888f8357f9213e5f54007083f427708a9860
