### ISSUE TITLE
github.com/vartanbeno/go-reddit/v2@v2.0.0: verifying module: checksum mismatch

### ISSUE THREAD

**Issue by lee-vivi** [casdoor/casdoor#2446]
github.com/vartanbeno/go-reddit/v2/reddit: github.com/vartanbeno/go-reddit/v2@v2.0.0: verifying module: checksum mismatch

when  use  go mod tidy  ,auto downloand : github.com/vartanbeno/go-reddit/v2 ；

casdoor version:4.0.2
golang 1.20
use go mod tidy
error:
github.com/vartanbeno/go-reddit/v2/reddit: github.com/vartanbeno/go-reddit/v2@v2.0.0: verifying module: checksum mismatch

How to solve it？

**Comment by hsluoyz** [comment]
@lee-vivi can you make a PR to fix it?
