### ISSUE TITLE
[bug]The adapter in the permission does not automatically create a table

### ISSUE THREAD

**Issue by qq1176914912** [casdoor/casdoor#2449]
As shown in the following figure
![image](https://github.com/casdoor/casdoor/assets/79817742/0ab8d3bb-b158-49f5-8845-e6faef4b7086)
if a value is filled in the adapter and does not exist in the database, a table will be automatically created. However, I tried and found that it did not automatically create a table and still defaults to the existence of permission_ In the rule table

**Comment by hsluoyz** [comment]
Give more details and configs, also demo video

**Comment by qq1176914912** [comment]
I created a permission named testquan in the permission and configured the value of the adapter as testshipei, as shown in the following figure：
![image](https://github.com/casdoor/casdoor/assets/79817742/64c4e53b-24fb-473b-aa46-c5147f5a64d3)
After I clicked Save, I did not see the testshipei table in the database, and the permissions I just created were still saved in Permission by default_ In the rule table: as shown in the figure
![image](https://github.com/casdoor/casdoor/assets/79817742/f923e0af-5f54-4b5d-9e00-bed30004f600)
Still saved in the default table
![image](https://github.com/casdoor/casdoor/assets/79817742/fbe74139-3c18-429f-ac0b-c24e1d0fbb39)

**Comment by qq1176914912** [comment]
> @qq1176914912 debug and set breakpoint at the below code, see why it doesn't create table:
> 
> https://github.com/casdoor/casdoor/blob/9d03665523a42269bad3662ad72adb9a002830d9/object/permission.go#L145-L213

Sorry, as I am not familiar with the go language, I have not come to any conclusions after debugging. If there is no problem with your side, it may be just a problem with my configuration

**Comment by hsluoyz** [comment]
Cannot reproduce
