### ISSUE TITLE
A UI bug of header bar

### ISSUE THREAD

**Issue by HanadaLee** [casdoor/casdoor#2452]
This can be reproduced when logging in to the backend using a non-built-in user.

![image](https://github.com/casdoor/casdoor/assets/33758411/6e4dff73-88f9-4252-a77b-3a2cca38ba6f)

**Comment by hsluoyz** [comment]
@HanadaLee can you make a PR?

**Comment by HanadaLee** [comment]
> @HanadaLee can you make a PR?

Sorry I don't have enough coding skills, this is just a bug feedback.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/f77fafae24357abf6127fe757f142c67b5641760
