### ISSUE TITLE
apple signup on demo fails on https://door.casdoor.com/signup

### ISSUE THREAD

**Issue by gedw99** [casdoor/casdoor#2453]
go to:https://door.casdoor.com/signup 

Click the Apple Icon which redirects to : https://appleid.apple.com/auth/authorize?client_id=casdoor&redirect_uri=https://door.casdoor.com/api/callback&state=JmFwcGxpY2F0aW9uPWFwcC1idWlsdC1pbiZwcm92aWRlcj1wcm92aWRlcl9jYXNkb29yX2FwcGxlJm1ldGhvZD1zaWdudXA=&response_type=code%20id_token&scope=name%20email&response_mode=form_post 

fails with "Invalid web redirect url" on the apple web gui.

---

Also rather than redirecting, can't we use the quicker Apple Signin with passkeys ?

**Comment by hsluoyz** [comment]
@gedw99 fixed by: https://github.com/casdoor/casdoor/commit/9703f3f712f0dc02513922632c065b9e65ed191b

For  `Apple Signin with passkeys`, can you create a new github issue for tracking?

**Comment by gedw99** [comment]
@hsluoyz 

thanks ..

Apple Signin with passkeys issue is here : https://github.com/casdoor/casdoor/issues/2465
