### ISSUE TITLE
Add more description about webhooks

### ISSUE THREAD

**Issue by alenapoliakova** [casdoor/casdoor#2454]
Hello👋🏼! I am interesting in Casdoor system.

In the docs I found the chapter ["Webhooks"](https://casdoor.org/ru/docs/webhooks/overview) with a small description of webhooks in Casdoor.

Could you tell us more about using webhooks in Casdoor? Where do I need to use it or maybe it is only used for developers?

Many thanks 🤟🏼

**Comment by alenapoliakova** [comment]
> one of these events is triggered, a JSON payload will be sent to the configured URL via a POST request

Where can I configure the URL?

**Comment by alenapoliakova** [comment]
> The application will parse the JSON payload and execute the specified function

What is an "application"? Maybe it is Casdoor's Go Backend or something else?

**Comment by hsluoyz** [comment]
Read the docs first.

**Comment by phoenixtechnam** [comment]
Good day, the event hooks documentation is incomplete, where do I get full information?
https://casdoor.org/docs/webhooks/overview/
