### ISSUE TITLE
[Feature]Filter the application list to exclude apps that users cannot access.

### ISSUE THREAD

**Issue by anyidea** [casdoor/casdoor#2464]
Even though I've set certain apps as inaccessible for a particular user in the permissions list, they are still visible in the home page app list.

**Comment by anyidea** [comment]
I believe the home page app list could include an API, something like "/api/get-user-applications," to filter the applications accessible to the user.

**Comment by hsluoyz** [comment]
@anyidea no need, just use `/api/get-applications`, filter out the ones that don't have access. BTW, can you make a PR?

**Comment by anyidea** [comment]
> @anyidea no need, just use `/api/get-applications`, filter out the ones that don't have access. BTW, can you make a PR?

We can apply permission filtering for non-admin users in the `GetOrganizationApplications` method.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/498cd02d49db6b48d58c651485f5a2e5045e316d
