### ISSUE TITLE
Any plan to encryption username,phone,email and other private information in database table?

### ISSUE THREAD

**Issue by julor** [casdoor/casdoor#2485]
Any plan to encryption username,phone,email and other private information in database table?

**Comment by hsluoyz** [comment]
This has nothing to do with Casdoor itself. What you should do is choosing an encryption-enabled database.

**Comment by julor** [comment]
No！
just like password stored in db,sometimes phone,email are as important  as password

**Comment by julor** [comment]
any update？

**Comment by hsluoyz** [comment]
@julor this feature is not planned in short term. As an advice, if you are looking for this level of extreme security for your company, you should look for an enterprise solution
