### ISSUE TITLE
Make a Casdoor .NET SDK for .NET apps to use

### ISSUE THREAD

**Issue by sagilio** [casdoor/casdoor#259]

**Comment by sagilio** [comment]
Can you assign this issue to me and create a `casdoor-dotnet-sdk` repo on casdoor organization for me. @hsluoyz

**Comment by hsluoyz** [comment]
Done: https://github.com/casdoor/casdoor-dotnet-sdk

**Comment by hsluoyz** [comment]
@hackerchai can you work on this?

**Comment by hackerchai** [comment]
> @hackerchai can you work on this?

yeah working on this

**Comment by hsluoyz** [comment]
Moved to: https://github.com/casdoor/casdoor-dotnet-sdk/issues/1
