### ISSUE TITLE
Browser compatible issue: StyleProvider hashPriority is not working.

### ISSUE THREAD

**Issue by YukiteruDev** [casdoor/casdoor#2597]
There is this code in `App.js` which should disable all the `:where` selectors in the page and make the styles compatible to legacy browsers:
```javascript
<StyleProvider hashPriority="high" transformers={[legacyLogicalPropertiesTransformer]}>
  {this.renderPage()}
</StyleProvider>
```
But it's not working as expected, components inside the `/login` page are still using the `:where` selector.

This happends to the latest unmodified version of casdoor.

**Comment by hsluoyz** [comment]
@LaurenceYoungDev can you make a PR to fix it?

**Comment by hsluoyz** [comment]
Cannot reproduce, closed
