### ISSUE TITLE
Support initial import of more object types

### ISSUE THREAD

**Issue by SchoolGuy** [casdoor/casdoor#2606]
Hi there! Thanks for your awesome work. I am positively surprised by how easy it is to bootstrap Casbin.

The data is very easy to obtain via Swagger, as such I assumed I would be able to also import the following objects via `inital_data.json`:

- Groups
- Adapters
- Enforcers

**Comment by hsluoyz** [comment]
@SchoolGuy the code is here:

https://github.com/casbin/casdoor/blob/48ba5f91ed191ad62e7747aba360afa6e52906a5/object/init_data.go#L51-L63

Can you make a PR?

**Comment by SchoolGuy** [comment]
@hsluoyz if you don't mind that it takes a week or two of course.
