### ISSUE TITLE
feat: Syncers for synchable Id-Providers

### ISSUE THREAD

**Issue by leoncamel** [casdoor/casdoor#2623]
Currently, it seems casdoor only support database syncer. 

In the case, we use AzureAD/WeCom as idP. It will also need some syncer for API-like Id-Providers. For example in this case, the admin role can only modify user info, or assign roles, **after** the specific user logged in.

So, I think, we need some way to solve this issue:
1. Extend Id-Provider interface with `sync()`? For example, AzureAD provide [Microsoft Graph API](https://learn.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http), and [MS Graph's Golang SDK](https://github.com/microsoftgraph/msgraph-sdk-go). And other Id-Providers may provide similiar APIs
2. Refactor Syncer interface, for non-database like syncers, like: HTTP based? or external application ?

Any comments about this feature request?

**Comment by hsluoyz** [comment]
@leoncamel sounds good. Can you split the syncers to different issues? One issue for one syncer. Because one syncer itself is a big code change itself

**Comment by leoncamel** [comment]
@hsluoyz Sure, I will submit idP related syncer as new issue. This issue remains as a umbrella issue to discuss general concepts.

**Comment by hsluoyz** [comment]
@leoncamel can you make PR?

**Comment by hsluoyz** [comment]
@leoncamel I think this can be implemented by a new syncer. There's no need to build on top of the OAuth provider. They use different APIs and have nothing much shared in common.

**Comment by leoncamel** [comment]
@hsluoyz Yes.

But, I not sure how to **share** parameters between idP and its syncer. For the WeCom case, they may share `ClientID` and `ClientSecret`?

Any thoughts?

**Comment by hsluoyz** [comment]
@leoncamel don't need to share. Just store it in syncer object for a second time

**Comment by hsluoyz** [comment]
Closed as stale

**Comment by hsluoyz** [comment]
@leoncamel done by: https://github.com/casdoor/casdoor/issues/4328 and https://github.com/casdoor/casdoor/issues/4334
