### ISSUE TITLE
Issue with 2FA not working when LDAP authentication is enabled

### ISSUE THREAD

**Issue by alexnet123** [casdoor/casdoor#2654]
## Description
We are encountering an issue where two-factor authentication (2FA) fails to work properly when LDAP authentication is enabled. It seems that the TOTP secret is not being saved correctly in the session, leading to failures in the 2FA process.

## Steps to Reproduce
1. Enable LDAP authentication.
2. Attempt to set up 2FA for a user.
3. Notice that the TOTP secret does not get saved in the session, causing the 2FA setup to fail.

## Expected Behavior
The TOTP secret should be saved in the user's session, allowing the 2FA setup to complete successfully and function correctly.

## Actual Behavior
The TOTP secret is not being saved in the session when LDAP authentication is enabled. This results in the failure of 2FA setup and functionality.

## Possible Solution
Investigate how the session management is handled during the LDAP authentication process and ensure that the TOTP secret is correctly stored in the session.

## Additional Information
- This issue seems to occur only when LDAP authentication is enabled.
- Relevant code sections include the LDAP authentication module and session handling during 2FA setup.
- No errors are logged, suggesting a silent failure in the session storage process.

Any assistance or guidance in resolving this issue would be greatly appreciated. Thank you.

**Comment by alexnet123** [comment]
![Screenshot from 2024-01-30 01-10-17](https://github.com/casbin/casdoor/assets/75438030/cb446302-d5ca-4d3e-b138-1384b8530c5e)

**Comment by leo220yuyaodog** [comment]
@alexnet123 What exactly do you mean by **Enable LDAP authentication**?

**Comment by alexnet123** [comment]
My Casdoor is connected to an LDAP server. When I perform authentication without 2FA, my application authenticates smoothly. However, if I add 2FA to the LDAP authentication process, the authentication fails.

**Comment by hsluoyz** [comment]
@alexnet123 can you provide a demo video to show this error? It will explain everything better

**Comment by leo220yuyaodog** [comment]
The screenshot shows error when enable the 2FA, this should have nothing to do with LDAP. 

> ![Screenshot from 2024-01-30 01-10-17](https://private-user-images.githubusercontent.com/75438030/300618847-cb446302-d5ca-4d3e-b138-1384b8530c5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTQ3OTcsIm5iZiI6MTcwNjY5NDQ5NywicGF0aCI6Ii83NTQzODAzMC8zMDA2MTg4NDctY2I0NDYzMDItZDVjYS00ZDNlLWIxMzgtMTM4NGI4NTMwYzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA5NDgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMzIyYzFiNjI2MmRiMmNmMTA2OGZkYzhmMTRlNjhlN2VjMThhZmFjMWFhMDdkODIxMWZiZmI0YjQyZjdlMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UVsdehyvd970ZUqFr228K7gEa5fvdANCPqem0zHPAu8)


> My Casdoor is connected to an LDAP server. When I perform authentication without 2FA, my application authenticates smoothly. However, if I add 2FA to the LDAP authentication process, the authentication fails.

You'd better provide the failed details about the LDAP login process with 2FA.

**Comment by alexnet123** [comment]
When you enable LDAP with 2FA, the secret is not recorded in the session. Go checks for the secret in the session, but it's not there. This is how I understand the process.

**Comment by hsluoyz** [comment]
@alexnet123 can you please just provide a demo video to reproduce the error? Right now I think we are more of wasting time here

**Comment by alexnet123** [comment]
Okay, I'll record a video. Do you need any additional logs?

**Comment by alexnet123** [comment]
there is a video file in the archive

[2024-02-01 22-47-16.zip](https://github.com/casbin/casdoor/files/14130257/2024-02-01.22-47-16.zip)

**Comment by alexnet123** [comment]
does not work
