### ISSUE TITLE
Unpredictable Behavior Using Sqlite Database Adapter

### ISSUE THREAD

**Issue by zicklag** [casdoor/casdoor#2689]
When using Casdoor with the sqlite database adapter I would get an error connecting the [Outline](https://www.getoutline.com/) software to Casdoor using OIDC. The steps I would take are:

1. Create a new organization, application, and user in casdoor.
2. Start an Outline server and set it's OIDC login settings to use casdoor with the application I created.
3. Login to the outline server using the casdoor user. This works ✅
4. Logout of the wiki
5. Try to log back into the wiki. This doesn't work. ❌

After step 5 I get an error message in my Outline server logs that says it failed to parse JSON from `/api/userinfo`, and it shows that it gets some unreadable binary data from the body `/api/userinfo` endpoint.

After building casdoor myself locally and doing some tests, I discovered that casdoor frequently runs into an error or a panic with the message:

     database is locked (5) (SQLITE_BUSY) 

The admin interface works fine most of the time with Sqlite, but sometimes when I try to save an item it fails the first time, and I have to try again before it works.

I think this issue might be related to this one on Xorm: https://gitea.com/xorm/xorm/issues/1979.

I verified that things work fine when using PostgreSQL.

**Comment by hsluoyz** [comment]
sqlite is not recommended for production use. More official DB like MySQL, Postgres is recommended. And this is a XORM issue rather than Casdoor, you should ask for help from XORM community.
