### ISSUE TITLE
Higher Security Default Settings

### ISSUE THREAD

**Issue by zicklag** [casdoor/casdoor#2690]
When you first setup Casdoor the `app-built-in` is configured to allow sign-ups. If you don't disable sign-ups immediately, it allows people to join the server as administrators.

This is a very easy thing to accidentally forget to do. It is also easy to miss the warning in the documentation, and new users might not know that it is a risk.

I think that new Casdoor instances should start off with sign-ups disabled, so that there is not this risk.

---

Another potential risk is the password hashing default setting. By default passwords are stored in plain text, which is not ideal. I think we should follow the OWASP password storage recommendation by default:

https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html

**Comment by hsluoyz** [comment]
@zicklag all you mentioned can be changed by configuration. The default setting will not be changed.

**Comment by hsluoyz** [comment]
A lot of open source projects have default username/password. If you don't change the default password. It's also a so-called "issue" based on your definition. Will you ask them to provide another way one by one?

It's no doubt that it's your responsibility to use the open source project in secure way.

This issue will be deleted shortly after this response.
