### ISSUE TITLE
question: where to configure s3ForcePathStyle

### ISSUE THREAD

**Issue by Nymphxyz** [casdoor/casdoor#2699]
I have same issue with this #1974 one and I saw we have a fix which added a new field `s3ForcePathStyle` in this PR #1985.

But I couldn't see this field in the web UI.

My casdoor version is 1.530.

![image](https://github.com/casdoor/casdoor/assets/65056401/70498670-8076-4dc6-ad06-02d068ecb1c9)

**Comment by hsluoyz** [comment]
@Nymphxyz it's a hard-coded value in backend and never be a frontend config in web UI: https://github.com/search?q=repo%3Acasdoor%2Fcasdoor+S3ForcePathStyle&type=pullrequests

In latest versions, `S3ForcePathStyle` is hard-coded to `true` for Minio. Do you have any reason to want to set it to false?

![image](https://github.com/casdoor/casdoor/assets/3787410/fbb0b1c6-4f18-4296-b353-4c13815f824f)

**Comment by Nymphxyz** [comment]
Because the request address is using `https://casdoor/` domain. I thought it was the configuration issue. But if it's already hard coded, not sure why I still have this same issue https://github.com/casdoor/casdoor/issues/1974:

![image](https://github.com/casdoor/casdoor/assets/65056401/87b2383b-c236-4ebe-abc3-379e466ce8bf)

**Comment by Nymphxyz** [comment]
Okay. I found a way to fix it, in MINIO the `domain` field is missing. But if you switch to AWS you will find the `domain` field is filled with `casdoor`. I update the field and switch back to `MINIO` the issue has been fixed.

I think it's a bug.

![image](https://github.com/casdoor/casdoor/assets/65056401/1df0e073-490a-40f8-9f7a-81b6eb03791f)

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/7481b229a41d8e241ac7fe6d4112f45d74dc63a3
