### ISSUE TITLE
Bug: MFA enable endpoint not working v.1.468.0

### ISSUE THREAD

**Issue by dshilovprpl** [casdoor/casdoor#2701]
Endpoint workin only via admin user. If I try to call it from nodejs SDK I'm receiving error:
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>beego application error</title>
    <style>
        html, body, body * {padding: 0; margin: 0;}
        #header {background:#ffd; border-bottom:solid 2px #A31515; padding: 20px 10px;}
        #header h2{ }
        #footer {border-top:solid 1px #aaa; padding: 5px 10px; font-size: 12px; color:green;}
        #content {padding: 5px;}
        #content .stack b{ font-size: 13px; color: red;}
        #content .stack pre{padding-left: 10px;}
        table {}
        td.t {text-align: right; padding-right: 5px; color: #888;}
    </style>
    <script type="text/javascript">
    </script>
</head>
<body>
    <div id="header">
        <h2>casdoor:interface conversion: interface {} is nil, not []string</h2>
    </div>
    <div id="content">
        <table>
            <tr>
                <td class="t">Request Method: </td><td>POST</td>
            </tr>
            <tr>
                <td class="t">Request URL: </td><td>/api/mfa/setup/enable</td>
            </tr>
            <tr>
                <td class="t">RemoteAddr: </td><td>10.0.2.147</td>
            </tr>
        </table>
        <div class="stack">
            <b>Stack</b>
            <pre>/usr/local/go/src/runtime/panic.go:884
/usr/local/go/src/runtime/iface.go:262
/go/src/casdoor/object/mfa_sms.go:74
/go/src/casdoor/controllers/mfa.go:131
/usr/local/go/src/reflect/value.go:584
/usr/local/go/src/reflect/value.go:368
/go/pkg/mod/github.com/beego/beego@v1.12.12/router.go:897
/usr/local/go/src/net/http/server.go:2947
/usr/local/go/src/net/http/server.go:1991
/usr/local/go/src/runtime/asm_amd64.s:1594
</pre>
        </div>
    </div>
    <div id="footer">
        <p>beego 1.12.3 (beego framework)</p>
        <p>golang version: go1.19.9</p>
    </div>
</body>
</html>

**Comment by hsluoyz** [comment]
@dshilovprpl 

1. Use latest version of Casdoor
2. Give more details

**Comment by dshilovprpl** [comment]
Added details here. Latest version also not working with another issue. I'll provide error from the new version soon

**Comment by dshilovprpl** [comment]
Latest version issue:
`{
  status: 'error',
  msg: 'destination is missing',
  sub: '',
  name: '',
  data: null,
  data2: null
}`

**Comment by dshilovprpl** [comment]
![image](https://github.com/casdoor/casdoor/assets/109940471/e84bcd88-195b-42bd-827e-f390512e00b6)

**Comment by hsluoyz** [comment]
@dshilovprpl can you provide a demo video?

**Comment by hsluoyz** [comment]
@leo220yuyaodog
