### ISSUE TITLE
Bug: enable MFA error while calling it via nodejs SDK

### ISSUE THREAD

**Issue by dshilovprpl** [casdoor/casdoor#2703]
I'm trying to set MFA via SDK and catch the following error.
I'm calling the same endpoints as it is on the UI:

1. initiate
response:
```
{
  status: 'ok',
  msg: '',
  sub: '',
  name: '',
  data: {
    enabled: false,
    isPreferred: false,
    mfaType: 'email',
    recoveryCodes: [ '5823d499-7fd2-4c0b-afec-6517c3a1a685' ]
  },
  data2: null
}
```

2. enable
response:
```
{
  status: 'error',
  msg: 'recovery codes is missing',
  sub: '',
  name: '',
  data: null,
  data2: null
}
```

Upd: Payloads the same as it is on the UI

**Comment by leo220yuyaodog** [comment]
@dshilovprpl If you use sdk to call the API, please set a time interval between calls, such as 200 ms. The beego framework has some bugs in its session when processing concurrent requests.

**Comment by dshilovprpl** [comment]
@leo220yuyaodog 
I tried it, but still the same. I split calls to different endpoints and wait about minute before the call enable

**Comment by leo220yuyaodog** [comment]
@dshilovprpl Have you update your Casdoor version to V1.536.0 ? I use API to enable the MFA of user successfully.

![image](https://github.com/casdoor/casdoor/assets/71440988/f8280915-2060-48e1-9873-432cb7fd747b)

![image](https://github.com/casdoor/casdoor/assets/71440988/49768928-f328-4d47-8d6e-ccfd79d9f9d3)

**Comment by dshilovprpl** [comment]
@leo220yuyaodog
Yeah, I'm using latest (V1.536.0) version.
1. I used not built-in organization - I created organization and created cert for it.
2. I used node js SDK. 

I think, that you have used admin token for the making requests. 
Maybe cause of issue on difference between authorization and access rights for the admin and SDK auth via cert?
Or maybe it is using another session and system can't find recovery codes?

**Comment by leo220yuyaodog** [comment]
> @leo220yuyaodog Yeah, I'm using latest (V1.536.0) version.
> 
> 1. I used not built-in organization - I created organization and created cert for it.
> 2. I used node js SDK.
> 
> I think, that you have used admin token for the making requests. Maybe cause of issue on difference between authorization and access rights for the admin and SDK auth via cert? Or maybe it is using another session and system can't find recovery codes?
> 
> UPD: Installation - k8s with redis

I think it may be the session problom, you need to set cookie in nodejs sdk and send request to `mfa/setup/enable` with the sessionId in the response of `mfa/setup/initiate`. Because Casdoor uses session to store the recovery codes. I'm not sure if the nodejs sdk sets cookie automatically. In the browser and postman, it default has the cookie.

**Comment by dshilovprpl** [comment]
@leo220yuyaodog Thank you! You right. I prepared PR for the nodejs SDK: https://github.com/casdoor/casdoor-nodejs-sdk/pull/48
