### ISSUE TITLE
Can't obtain access token using casdoor-python-sdk

### ISSUE THREAD

**Issue by sagarve** [casdoor/casdoor#2706]
I have a casdoor running inside a docker container which I'm able to access on localhost:8001 (using [casdoor production image](https://hub.docker.com/r/casbin/casdoor), not the all-in-one image). I've created an application and mentioned Password, Verification code and WebAuthn as signin methods. 

Since my application doesn't have a frontend, I've tried to get an access token using username-password as well as client_credentials but in both cases, I'm getting response saying _**'grant_type: password is not supported in this application'**_ & _**'grant_type: client_credentials is not supported in this application'**_. I've re-check all the arguments including clientid, client_secret, org_name, application_name, certificate, everything matches from UI. 

Please help in resolving this issue. Below is my python code snippet 

```py
    certificate: str = '''-----BEGIN CERTIFICATE-----
    MIIE2TCCAsGgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCYxDjAMBgNVBAoTBWFk
    ...
    ofNI5Q4FjBW5C9tdbgS2ZiQkrTpGprBgzoAGseAQE79w8cSY6z+WiJVfb0GN
    -----END CERTIFICATE-----'''
    endpoint = 'http://localhost:8001'
    client_id = 'c422fbeb7a36f9cac746'
    client_secret = '35fd3feb11c4983f567dda39a1c0c05573d1593a'
    org_name = 'built-in'
    application_name = 'application_gs44us'
    
    sdk = CasdoorSDK(
        endpoint,
        client_id,
        client_secret,
        certificate,
        org_name,
        application_name,
    )
    
    token = sdk.get_oauth_token(username='admin', password='123')
    access_token = token
    print(f"access_token: {access_token}")
    decoded_msg = sdk.parse_jwt_token(access_token) # or sdk.parse_jwt_token(access_token, kwargs)
    print(f"decoded_msg: {decoded_msg}")
```

**Comment by hsluoyz** [comment]
@sagarve add all grant types in your application edit page like: https://door.casdoor.com/applications/casbin/app-vue-python-example

![image](https://github.com/casdoor/casdoor/assets/3787410/fe9c8978-ae27-4433-8ba4-b6717488e76a)

**Comment by sagarve** [comment]
I've added these grant types already, still getting same results.

**Comment by sagarve** [comment]
I'm able to get an access code with a fresh application. Thanks @hsluoyz
