### ISSUE TITLE
This warning indicates that the suffixCls prop is being passed to a DOM element, but React does not recognize it as a valid prop

### ISSUE THREAD

**Issue by Abhijrathod** [casdoor/casdoor#2707]
BUG: Warning: React does not recognize the `suffixCls` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `suffixcls` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
section
./node_modules/antd/es/layout/layout.js/BasicLayout<@http://localhost:7001/static/js/bundle.js:134344:63
Layout
StyleProvider@http://localhost:7001/static/js/bundle.js:76731:18
FormProvider@http://localhost:7001/static/js/bundle.js:345503:26
ProviderChildren@http://localhost:7001/static/js/bundle.js:124628:18
ConfigProvider@http://localhost:7001/static/js/bundle.js:124750:52
App@http://localhost:7001/static/js/bundle.js:1497:142
I18nextWithTranslation@http://localhost:7001/static/js/bundle.js:413103:26
C@http://localhost:7001/static/js/bundle.js:417193:31
Router@http://localhost:7001/static/js/bundle.js:416648:30
BrowserRouter@http://localhost:7001/static/js/bundle.js:416162:35

**Comment by hsluoyz** [comment]
@Abhijrathod just warning, no need to fix
