### ISSUE TITLE
Not able to sync user access policies into the enforcer

### ISSUE THREAD

**Issue by sagarve** [casdoor/casdoor#2712]
Hi,

I have a casdoor running inside a docker container which I'm able to access on localhost:8001 (using [casdoor production image](https://hub.docker.com/r/casbin/casdoor), not the all-in-one image). I'm trying to sync my casbin policies from my postgres DB into casdoor, for which I've created an adapter and an enforcer using that adapter. The enforcer successfully loads policies from DB and loaded into the casdoor UI when I sync them for the first time. The issue occurs when I open the enforcer again, it doesn't show the loaded policies and instead show an error message as shown in the screenshot attached (which looks like it's trying to create the same policy rows again). Plz suggest a resolution for this particular issue.

Also wanted to know, if before I call the enforcer API for checking user authorisation for a particular resource, do I need to manually sync the enforcer again in case any new policies were added into the DB? Or does it refer to the configured postgres DB directly to query user permissions?

<img width="1316" alt="image" src="https://github.com/casdoor/casdoor/assets/110984367/35b04214-efa4-4e98-ac43-6619b87f4416">

**Comment by sagarve** [comment]
Any update on this?

**Comment by sagarve** [comment]
@hsluoyz Can you help resolving this issues?
Also, it would be really helpful if you could help clarify this question
"Also wanted to know, if before I call the enforcer API for checking user authorisation for a particular resource, do I need to manually sync the enforcer again in case any new policies were added into the DB? Or does it refer to the configured postgres DB directly to query user permissions?"

**Comment by hsluoyz** [comment]
@hsluoyz what posgres version did you use? Did you try MySQL too? What are the reproduce steps?

**Comment by sagarve** [comment]
I used Postgres 15. No I didn't try MySQL. 
Reproduce steps:
1. Create an adapter. Test that DB connection is successful
2. Create an enforcer using that adapter and sync policies (Policies show up)
3. Save and Exit
4. Opening that enforcer again shows this error message.

**Comment by dacongda** [comment]
I can't reproduce this problem in the newest version, can you record a video to display?

I use pgsql 16 to reproduce.

**Comment by dacongda** [comment]
> @hsluoyz Can you help resolving this issues? Also, it would be really helpful if you could help clarify this question "Also wanted to know, if before I call the enforcer API for checking user authorisation for a particular resource, do I need to manually sync the enforcer again in case any new policies were added into the DB? Or does it refer to the configured postgres DB directly to query user permissions?"

 it refer to the configured postgres DB directly to query user permissions

**Comment by hsluoyz** [comment]
Closed for cannot reproduce
