### ISSUE TITLE
Not able to sync users from postgres to casdoor

### ISSUE THREAD

**Issue by sagarve** [casdoor/casdoor#2713]
Hi,

I have a casdoor running inside a docker container which I'm able to access on localhost:8001 (using [casdoor production image](https://hub.docker.com/r/casbin/casdoor), not the all-in-one image). I'm trying to sync users from my backend postgres DB to Casdoor using a Syncer. Since the column names for user table in my postgres somewhat differ for Casdoor column name options available, I'm only using `id` and `email` columns (which are the only mandatory ones I believe) to sync user data and mapping them to `Id` and `Name` column names in casdoor but I've been getting below password auth error even though the password is correct (Since I created an adapter using the same user-password and the connection was successful). 
Plz suggest a resolution and debugging steps for such issues.

<img width="1436" alt="syncer_error" src="https://github.com/casdoor/casdoor/assets/110984367/e42055ce-bd86-4748-833a-0b6b7bf76769">

**Comment by sagarve** [comment]
Any update on this?

**Comment by hsluoyz** [comment]
@sagarve your postgres password is wrong.

**Comment by hsluoyz** [comment]
@sagarve Casdoor uses XORM (https://xorm.io/) to interact with DB. That password failed error is directly returned by XORM and Casdoor does very little during the process. You can try connecting to DB via XORM directly. If you think there are bugs, report to XORM community: https://xorm.io/
