### ISSUE TITLE
/static/js/main.6d274e43.js ContentDownload too long

### ISSUE THREAD

**Issue by moxixuan** [casdoor/casdoor#2715]
https://github.com/casdoor/casdoor/assets/19483437/0a8c63d2-93e1-49f3-9719-4251008173d9

hi, main.6d274e43.js is too big, it's 8M and it's taking too long to load, is there anything I can do to optimize it? I am running [casdoor](https://hub.docker.com/r/casbin/casdoor) from docker.

**Comment by hsluoyz** [comment]
@moxixuan use latest version Casdoor, it is only 2 MB
