### ISSUE TITLE
Incorrect display of login page http://localhost:8000/login/built-in

### ISSUE THREAD

**Issue by moxixuan** [casdoor/casdoor#2716]
I just upgraded the docker image version of casdoor, when I log in to http://localhost:8000, the login page shows the following, do I need to migrate the data files? Or do I need to upgrade something else. thanks~
![图片](https://github.com/casdoor/casdoor/assets/19483437/1c0e95fb-0aff-49be-a067-ea5303d00dd4)

**Comment by hsluoyz** [comment]
@moxixuan don't ask trivial questions in issues, go to discord. This issue will be deleted
