### ISSUE TITLE
Understanding if my usecases can be implemented using casbin or casdoor

### ISSUE THREAD

**Issue by sagarve** [casdoor/casdoor#2722]
Hi, I'm new to casbin/casdoor and wanted to understand if below usecases can be implemented using casbin or preferably casdoor. First, I'd like to explain in brief about my application, it's a multi-tenant app for which we've created separate schemas in our postgres db to store information related to each client separately.

 Usecases:
1. Roles and permissions shared by all clients.
2. Custom roles, which clients can create for themselves and they'll be specific to the client that created them.
3. User groups. I want to assign permissions based on individual users and user groups inside an organisation.
4. I want to provide a User access to individual entities. Entities may be created in a hierarchy.
5. I want to create/modify/revoke user access, manage roles and user groups from my application's UI and not casdoor UI.
6. I want to maintain everything in postgres db.
7. For authentication, I'm using azure AD B2C.

I tried to implement this using casbin, but casbin only allows me to use a single enforcer and expects every policy (roles, user groups, access policies) to be in a single place so that it can match based on matcher config. Is it possible to keep user groups, roles and access policies in separate DB tables and enforce using data from multiple tables? 

Also, can this be achieved using casdoor, considering I want to use my own application UI to perform these actions?

**Comment by hsluoyz** [comment]
All the usercases can be done by Casdoor
