### ISSUE TITLE
feature: Add HS256 cert

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#2751]
### Discussed in https://github.com/casdoor/casdoor/discussions/2748

@magiskboy

<div type='discussions-op-text'>

<sup>Originally posted by **magiskboy** February 25, 2024</sup>
I tried to create a new cert with HS256 algorithm but I got an error "Failed to save: crypto/rsa: message too long for RSA key size". In this picture, it is my configuration. How can I create a cert with HS256?

Update
==============

At that time, only frontend options are added: https://github.com/casdoor/casdoor/commit/5b151f4ec4d74432ac4189e470e454204e7eb2d5 . So it doesn't work. Need to implement it fully in backend.

![image](https://github.com/casdoor/casdoor/assets/13352088/2ea0b298-51c1-4d86-abad-0f7f02394bef)
</div>

**Comment by hsluoyz** [comment]
@magiskboy can you make a PR?

**Comment by magiskboy** [comment]
yeah, I will
