### ISSUE TITLE
Export existing configuration into init_data.json

### ISSUE THREAD

**Issue by Sjoerd82** [casdoor/casdoor#2760]
Would be nice if we could export existing settings into a init_data.json file.
This would make it easy to deploy new instances quickly from an existing instance.
Or reuse and deploy setting into new environments.

Related: https://github.com/casdoor/casdoor/issues/2461

**Comment by hsluoyz** [comment]
@Sjoerd82 Data exported to file is supported, see docs: https://casdoor.org/docs/deployment/data-initialization/#export-config-data

**Comment by Sjoerd82** [comment]
Thanks, this helps a lot!
