### ISSUE TITLE
Incorrect STYLE opening tags within STYLE-block generated by extendApplicationWithSigninItems

### ISSUE THREAD

**Issue by Sjoerd82** [casdoor/casdoor#2764]
An extra `<style>`-tag is generated in some places in the sign-in HTML.
![image](https://github.com/casdoor/casdoor/assets/15013786/1bf999ca-5285-40da-9c9d-812f25f9d2f1)

This is likely caused by the `extendApplicationWithSigninItems` function in `object/application.go`.
Not being very familiar with the source code, it seems to be caused by an incorrect end tag `<style>`, which should probably be `</style>`.

Line 225:
`"\n<style>\n  .login-logo-box {\n  }\n<style>\n",`

This occurs in multiple locations. Also on lines 233, 241, 249, 257, 265, 273, 281.

**Comment by Sjoerd82** [comment]
Should use tag "bug".

**Comment by hsluoyz** [comment]
@Sjoerd82 hi, can you make a PR to fix it?

**Comment by Sjoerd82** [comment]
Would have :-) But someone else has beat me to it 🥇
