### ISSUE TITLE
"Form CSS" is not included in output.

### ISSUE THREAD

**Issue by Sjoerd82** [casdoor/casdoor#2765]
Whatever styles I add to the form CSS never end up in the HTML of the page (I scanned the entire output, including a referenced stylesheet.)

I am referring to this field (organization):
![image](https://github.com/casdoor/casdoor/assets/15013786/958e4bc6-68d8-4e62-aa9c-d1dfbb3c01af)

I am using an IFRAME. I did notice that IFRAME's are handled slightly different, maybe that's the cause?

I need this to make the background transparent, so I can blend the IFRAME login box better into my application UI.

On a side note. The term "Form CSS" is somewhat ambiguous. It's not clear if this is meant to style the form only, or if you can style the entire page. Perhaps "Custom CSS", or something similar is a better term.

**Comment by hsluoyz** [comment]
@Sjoerd82 fixed in: https://github.com/casdoor/casdoor/commit/bc399837ccde6c459dfc0f411361ca9599dd5cfd

For IFRAME, you can modify the code as belows:

![image](https://github.com/casdoor/casdoor/assets/3787410/ed908f4a-640e-40a5-ad79-6fc928886c0c)

**Comment by Sjoerd82** [comment]
Sorry, not yet getting it.. This means that "Form CSS" cannot be used when in an IFRAME?

Is there a way to influence the style for an IFRAME login page? (Other than providing a full HTML replacement page, which does work, but is a lot more work, plus you probably lose the translation).

**Comment by hsluoyz** [comment]
@Sjoerd82 why can't you modify the code? Iframe CSS is rarely used. I'm still seeing if other people have same requirement before deciding to support it.

For i18n, yeah it may not work maybe. But I don't have time to check that. Let someone fix it.
