### ISSUE TITLE
Select language and light/dark mode for signin, signup, and error page

### ISSUE THREAD

**Issue by Sjoerd82** [casdoor/casdoor#2766]
Often, the application already has a language and theme set.
For a fluent integration of the Casdoor pages, these should then be used there as well.

We could make this possible by adding url query parameters that pre-select the two settings.
For example: `...&lang=de&theme=dark`, and if nothing is set use the Casdoor/organization default.

It seems the login box is based on Ant Blocks UI, which already has strong integration for light/dark mode, and maybe even themes.

This would make a great improvement to Casdoor! :-)

**Comment by Sjoerd82** [comment]
Use tag "enhancement".

**Comment by hsluoyz** [comment]
@Sjoerd82 can you make a PR?

**Comment by Sjoerd82** [comment]
> @Sjoerd82 can you make a PR?

I'm neither a Go nor React developer, and have no prior knowledge of the source code.
That didn't stop me to have a look though. And it seems that this enhancement can probably best be realized in `web/src/auth/auth/EntryPage.js`.

.. it was at this point that I realized setting language is already possible! (ex. `...&language=de`)
The only fix is to document it :-)

To make setting the theme possible too, something like this:
```
  getThemeParam(params) {
    // "/page?theme=dark"
    const theme = params.get("theme ");
    if (theme !== null) {
      setTheme(theme, ????);
...
```
Not sure where best to call it, and what `initThemeAlgorithm` does.

Probably best if an actual Casdoor dev implements this...
