### ISSUE TITLE
creation of a new organization within an organization

### ISSUE THREAD

**Issue by waffle-frame** [casdoor/casdoor#2772]
I have a question. 

Can I add a new organization outside the built environment?
I tried to do this by logging into the organization I created, but the add button was disabled.

![image](https://github.com/casdoor/casdoor/assets/113475097/e7e40f18-a739-40a2-abf4-104f53d1e6ba)

**Comment by hsluoyz** [comment]
@waffle-frame only the built-in org has the superpower to manage other orgs. All other orgs are equal. So one cannot create another one
