### ISSUE TITLE
Edit user page display issues

### ISSUE THREAD

**Issue by chencu5958** [casdoor/casdoor#2777]
When I create a test account with a non-built-in organization, I find that the account settings page does not show the account-related settings options, which I didn't encounter with 1.500
![image](https://github.com/casdoor/casdoor/assets/82279230/17124bc3-f102-43fa-9bc6-aab827c650ce)

**Comment by chencu5958** [comment]
I found this problem from 1.555.1, I tested it to 1.554.0 and there is no such bug

**Comment by chencu5958** [comment]
1.555.0 also has this problem

**Comment by hsluoyz** [comment]
@chencu5958 try 1.554.1

**Comment by hsluoyz** [comment]
@chencu5958 fixed by: https://github.com/casdoor/casdoor/commit/fbdd5a926d1f64a98693374870a9b696a0a13345
