### ISSUE TITLE
suggest: When you log in to the CASDOOR callback page, it can be deleted to the http of FROM?

### ISSUE THREAD

**Issue by LiusCraft** [casdoor/casdoor#2783]
My own application website has realized the generation of login address that jumps to a third -party platform.

After the login is completed, it will be adjusted to the callback page of Casdoor. It has a logic on the front end of the judgment that the final call page will jump to the page. The front -end code found that HTTP will jump in the form of a new window, but this requires user authorization to allow pop -ups to be allowed

source code: [web/src/Setting.js](https://github.com/casdoor/casdoor/blob/89df80baca7c3917448901b94b9ce61e245151e7/web/src/Setting.js#L701C17-L701C29)

from=http://xxxxhost

> It is the process of Casdoor's account binding. The different thing is that the FROM address is not Casdoor but the address of my application site. It takes HTTP to jump to the past

**Comment by hsluoyz** [comment]
@LiusCraft can you try the latest version >= v1.558.0 ? This issue should have been fixed in: https://github.com/casdoor/casdoor/pull/2778

**Comment by LiusCraft** [comment]
My problem, it has indeed solved it in the latest version
