### ISSUE TITLE
error on line 14 at column 168: Attribute xmlns redefined

### ISSUE THREAD

**Issue by DevOpserzhao** [casdoor/casdoor#2784]
I'm a local developer.
use http://localhost:7001/api/saml/metadata?application=admin/application_devops&post=true

error  

error on line 14 at column 168: Attribute xmlns redefined

`<EntityDescriptor xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="http://localhost:8000">
  <IDPSSODescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <KeyDescriptor use="signing">
      <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
        <X509Data xmlns="http://www.w3.org/2000/09/xmldsig#">
          <X509Certificate xmlns="http://www.w3.org/2000/09/xmldsig#">MIIE2TCCAsGgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCYxDjAMBgNVBAoTBWFkbWluMRQwEgYDVQQDDAtjZXJ0X2gwd2EyZjAeFw0yNDAzMDYxNjIwMThaFw00NDAzMDYxNjIwMThaMCYxDjAMBgNVBAoTBWFkbWluMRQwEgYDVQQDDAtjZXJ0X2gwd2EyZjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANlHszL84VDddgA9t2X3JO6vfiyR46wL7U/AWVDIDrFb64QlxYiNvZ+vlh/jADS0CiviRsnb6kdAFZpSwyyY1uNeg9cZEuxsQqTXoFDPZpsakbBmLl+z8VsyX/RhCNXRAs41Tc654L0/gMNpdZefMjlZXKnrB7ejwZjo22q0AFL9YH9ZwabLguBQwsZ9zSbdXGMdB8YgbRLcgoaUhe5Z/NYjb7vrXJQVPvzzS1euoMqLOHSwjGwLcmQxDjmAplNeJaA0kakc2a9ERphwlOuNn12/nAtdEBmKURWwJtWSCpDeZUteEsc9byRmDmIUF+WT8oO1fdREmg8pqiZ8+JgkQwTsB0JSKTldcaY1xFMRA5np714asaF2f3OavTtRPEvnOhSiStA+a/KH6G3v4pjM3aTEYgqor8uKjR2CUfW5M/rMV9KovkMj61Q+G0gVxJCUTLEdTCVE7bRG7NoAO+Yu6tAXX0S/VjABIN0m6aBamEkwSIAi/UhDqFgJ8ZXa1daCy/HOtp1HAmDMs5RhtG71mMUcr8QweIGcG+K+e5STKbJHzgU58aNxpX4NbW42hiYo1O/Mh6e0cm4enhQ5kZQelNNXCjv5euYBW6Oz19ea2G4JT774o2XzPfXSXS6bzEbSX90JMbPxf/0sCIMZIN/WqegjrLyns4w4v+dtjeY561TXAgMBAAGjEDAOMAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAK48RYiI+9RwPoozFkn6O9TPw6Zhp0o2h73STzCz+b0K61fMRZ+JmKvzKPrz3JhyfI9ZPXeXR+D1hLMCTBZ5wRutSfe9uXg8jTLq7rf933N5Vxv+yhP+j5CT60szWcEB4HaNPAYtsb6VVFHpL/YL4D8LN4ZBNNvlOMoBh2I/PSwmpSzTzdSC3Ds3QFncuu49Ee3qU1gSxEK0NpZJl+cKNyi9WgV0NgKrJAtGdcsixTLGaqPWzRpYxJorxRbBAy7GYL9RvswrPCYSb9bmxh+aalpmxBZ+7z0q4iSfAkeq1mEI89MXkj/mD0GUHD6FualfE2EYbdD2o26s/fCz9L34EDk+q2VH77lQHmhskb4KkxLDlyNsRdD6wCqOK0bd15l+34CJY7EpCJCEZtwaBVPXYQ6PewM7FwViN0+D9xkkQblakaBFFvWLNk8L4Vs5Im9FnPaZ7Nsg47OZFh0sK/SIOkr3MibQXfIikDdCuroxmkkTm5buO6Lwmn76gTtLrVnE7MW5oz5Zl7INYvJkjvj2E9kCjaAhxK5Yp0XiLjcyDQeCA8GJr2bHbWFv5zPVMgm14H/iI+2eP0OlA7r3btkTEMdTa3XTtoYhKmjg6rWdsLZ97f3l7/E+PfKv96QH2Z2aS0nHlFTbaQAAvHcewgfb+lQhT2H/vdgtL37jMmidimNe</X509Certificate>
        </X509Data>
      </KeyInfo>
    </KeyDescriptor>
    <NameIDFormat xmlns="">urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
    <NameIDFormat xmlns="">urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</NameIDFormat>
    <NameIDFormat xmlns="">urn:oasis:names:tc:SAML:2.0:nameid-format:transient</NameIDFormat>
    <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://localhost:8000/api/saml/redirect/admin/application_devops" xmlns=""></SingleSignOnService>
    <Attribute Name="Email" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" FriendlyName="E-Mail" xmlns="urn:oasis:names:tc:SAML:2.0:assertion" xmlns=""></Attribute>
    <Attribute Name="DisplayName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" FriendlyName="displayName" xmlns="urn:oasis:names:tc:SAML:2.0:assertion" xmlns=""></Attribute>
    <Attribute Name="Name" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" FriendlyName="Name" xmlns="urn:oasis:names:tc:SAML:2.0:assertion" xmlns=""></Attribute>
  </IDPSSODescriptor>
</EntityDescriptor>`

**Comment by hsluoyz** [comment]
@DevOpserzhao hi, can you make a PR to fix it?

**Comment by hsluoyz** [comment]
@DevOpserzhao Casdoor already defined some built-in attributes like Name, Email, DisplayName, etc. You should not add them again in the "SAML attributes" table in application edit page like: https://door.casdoor.com/applications/built-in/app-built-in#:~:text=POST%20binding%20%3A-,SAML%20attributes,-%3A

![image](https://github.com/casdoor/casdoor/assets/3787410/7919648b-3acd-4471-b5d2-4dcb4804393a)

Built-in attributes:

https://github.com/casdoor/casdoor/blob/c532a5d54d6ddde86955482fe45a0f5f6f2cef55/object/saml_idp.go#L91-L104

**Comment by DevOpserzhao** [comment]
I have changed the code to fix it

**Comment by DevOpserzhao** [comment]
> @DevOpserzhao can you make a PR to share your code?

sure,  My local environment
GOARCH='arm64'
GOVERSION='go1.22.1'
