### ISSUE TITLE
java-sdk has no method about policy

### ISSUE THREAD

**Issue by zy110836** [casdoor/casdoor#2787]
It is possible to add policies visually in casdoor, but it is inconvenient. I hope that the API about policies can be provided and can be called in Java-sdk.
![WeChat433a168e5c4c8bf3ec855e3db70c1459](https://github.com/casdoor/casdoor/assets/127188519/64b4c660-a283-4fbe-acf0-58d604cd1b72)
![WeChatfe0cdd8f822b2eda5bdce86ccb6c89b8](https://github.com/casdoor/casdoor/assets/127188519/0fe10b90-d75c-4376-a494-2ffe52526271)

**Comment by MoonsuCha** [comment]
Hello. Is there any update progress on nodejs sdk? It appears that there is no policy-related SDK part in the node js SDK.

**Comment by hsluoyz** [comment]
@MoonsuCha create a github issue
