### ISSUE TITLE
<img width="2536" alt="image" src="https://github.com/casdoor/casdoor/assets/45530032/59e9a10d-cb4d-4ae5-a442-c8d4ba36f61a">

### ISSUE THREAD

**Issue by DevOpserzhao** [casdoor/casdoor#2789]
<img width="2536" alt="image" src="https://github.com/casdoor/casdoor/assets/45530032/59e9a10d-cb4d-4ae5-a442-c8d4ba36f61a">

_Originally posted by @DevOpserzhao in https://github.com/casdoor/casdoor/issues/2784#issuecomment-1985379232_
 
why hava  xmlns=""  text in xml

**Comment by hsluoyz** [comment]
@DevOpserzhao you can reply to the old issue. But don't send image as new issue here.

This is the 2nd time. If it happens again, I'm afraid you will be blocked from creating new issue in this repo.

This issue will be deleted shortly.
