### ISSUE TITLE
Make a Casdoor auth middleware for APISIX

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#279]
We already have the Casbin middleware: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/authz-casbin.md

Now we also need a Casdoor one. Maybe first we need to make a casdoor-lua-sdk, then make a APISIX middleware.

**Comment by hsluoyz** [comment]
@rushitote can you help on this?

**Comment by rushitote** [comment]
@hsluoyz Sure, I will first take a look into Casdoor and the codebase and then we can start the development of Casdoor Lua SDK.

**Comment by hsluoyz** [comment]
Just use standard OIDC, no need for middleware: https://github.com/casbin/casdoor/issues/358

**Comment by hsluoyz** [comment]
@rushitote any update?

**Comment by hsluoyz** [comment]
Hi @leeqvip can you take a look?
