### ISSUE TITLE
Seeking advice on optimizing user authorization with RBAC using Casdoor Go SDK

### ISSUE THREAD

**Issue by nemirlev** [casdoor/casdoor#2796]
Hello,

I'm currently exploring the best practices for implementing user authorization in a project utilizing the Casdoor Go SDK, particularly within the context of the Role-Based Access Control (RBAC) model. As I am relatively new to this area, I am keen to learn from your expertise to ensure I'm adopting the most efficient and secure approach.

My current setup involves the default model configuration as follows:

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

For path access control, I specify permissions in the router like this:

```go
http.HandleFunc("/private", tokenAuthMiddleware(privateHandler, "service1.read"))
```

And I perform the permission check as shown below:

```go
func tokenAuthMiddleware(next http.HandlerFunc, requiredPermission string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		authHeader := r.Header.Get("Authorization")
		if authHeader == "" || !strings.HasPrefix(authHeader, "Bearer ") {
			http.Error(w, "Unauthorized: No token provided", http.StatusUnauthorized)
			return
		}

		token := strings.TrimPrefix(authHeader, "Bearer ")
		if !validateTokenWithCasdoor(token, requiredPermission) {
			http.Error(w, "Unauthorized: Invalid or expired token", http.StatusUnauthorized)
			return
		}

		next(w, r)
	}
}

func validateTokenWithCasdoor(token string, requiredPermission string) bool {
	claims, err := casdoorsdk.ParseJwtToken(token)
	if err != nil {
		fmt.Println("Error validating JWT token:", err)
		return false
	}

	user, _ := casdoorsdk.GetUser(claims.User.Name)
	for _, perm := range user.Permissions {
		if perm.Name == requiredPermission && perm.IsEnabled {
			fmt.Println("Permission verified for user with claims:", claims)
			return true
		}
	}

	fmt.Println("Permission not found or not enabled for user:", claims.Name)
	return false
}
```

I am confident that there might be a more optimized or standardized method to handle this process, especially in verifying roles/permissions effectively. Could you provide any recommendations or best practices on this matter? Additionally, if there are any improvements or alternative approaches to the current method I'm using, I'd be greatly appreciative of your guidance.

Thank you for your time and support.

**Comment by hsluoyz** [comment]
@nemirlev why don't you just use the permissions property inside the JWT? I think the JWT already contains permissions by default? See:

https://github.com/casdoor/casdoor/blob/57431a59ad67d5c992d505f261d1bd14470e9b03/object/token_jwt.go#L363-L387

If you are using "JWT" format option, you already have:

https://github.com/casdoor/casdoor/blob/57431a59ad67d5c992d505f261d1bd14470e9b03/object/token_jwt.go#L242-L244

**Comment by nemirlev** [comment]
@hsluoyz Hello.


Because the token is transferred from the client to the server.  It is stored in cookies, and this is a problem. There is a size limit. We can use roles instead, and we will solve this problem, but then we will not have atomicity.

**Comment by hsluoyz** [comment]
You should store it in local storage then

**Comment by nemirlev** [comment]
@hsluoyz It's not safe.

https://auth0.com/docs/secure/security-guidance/data-security/token-storage#don-t-store-tokens-in-local-storage
