### ISSUE TITLE
OVHCloud SMTP email issue

### ISSUE THREAD

**Issue by stephenfreelance** [casdoor/casdoor#2797]
Hello, I'm trying to add an email provider for the "forgot password" feature. I'm getting "tls: first record does not look like a TLS handshake" error when setting up the provider. Here are the settings I'm using:
- port: 587
- username: my email
- password: my password
- host: pro1.mail.ovh.net
I tested those settings in an external client and everything works: I'm able to send and receive emails.
Do you have any idea why it doesn't work here? Thanks!

**Comment by hsluoyz** [comment]
@stephenfreelance make sure you choosed the `Disable SSL` option correctly:

![image](https://github.com/casdoor/casdoor/assets/3787410/d101b59f-4453-4955-b24c-8182ada45959)

@stephenfreelance if not fixed, what's the Email provider you used? We may try to configure one and test it

**Comment by stephenfreelance** [comment]
Thank you for the response, I have tested with and without "Disable SSL" enabled, I have the same issue

**Comment by hsluoyz** [comment]
@stephenfreelance what's the Email service vendor (like AWS cloud, etc.) you used? We may try to configure one and test it

**Comment by stephenfreelance** [comment]
I'm using OVHCloud

**Comment by hsluoyz** [comment]
@stephenfreelance I don't have OVHCloud, and I find it very difficult to even register an account for it. And after I registered maybe one correct account, I cannot find the Email service. So I kind of give it up now. Can you provide your cred for us to test? Otherwise I'm afraid it's hard for us to proceed now

**Comment by hsluoyz** [comment]
@stephenfreelance hi, it's very difficult to find the correct register page and service dashboard for OVHCloud. There seem to be multiple websites. Can you give some pointers?

**Comment by gabor-rabatin-volteum** [comment]
Thank you @hsluoyz for the amazingly fast response, it works with the new [v1.595](https://github.com/casdoor/casdoor/releases/tag/v1.595.0)

**Comment by hsluoyz** [comment]
@stephenfreelance hi, can you provide a link for the specific service in OVHCloud? There are many categories of Email services in OVH

**Comment by Bsheepcoder** [comment]
Gomail has a similar issue, I gave an answer, you can use it as a reference. I am trying to solve it.
 [tls: first record does not look like a TLS handshake #135](https://github.com/go-gomail/gomail/issues/135#issuecomment-2105137098)

**Comment by Bsheepcoder** [comment]
Are you using this from OVHCloud as the SMTP Server?
![image](https://github.com/casdoor/casdoor/assets/73925108/44d1742c-04cb-462d-ad53-d09cd0840413)

**Comment by hsluoyz** [comment]
@stephenfreelance you need to turn ON the "Disable SSL" option like: https://door.casdoor.com/providers/admin/provider_email_ovhcloud . It works for me.

![image](https://github.com/casdoor/casdoor/assets/3787410/9d5ae259-5a6d-470f-8653-a07d1a064cbc)
