### ISSUE TITLE
custom attributes for the user table

### ISSUE THREAD

**Issue by waffle-frame** [casdoor/casdoor#2803]
Hello. 

The other day I needed to add some new fields for a user and store them in a token during login. 

I haven't found a way to do this.
There are plans to implement this, I need advice on how necessary this will be

**Comment by hsluoyz** [comment]
@waffle-frame modify the code to add new fields to the User struct. Or add to the properties of the User:
https://github.com/casdoor/casdoor/blob/e1e5943a3e6b9e3daab352b7e002a2ae16758dbf/object/user.go#L195

**Comment by waffle-frame** [comment]
@hsluoyz

Tell me where I can see this on the admin page?

**Comment by hsluoyz** [comment]
@waffle-frame not planned for now. Too tedious to support this. Just modify the code by yourself, it's much easier
