### ISSUE TITLE
"fs" Module Not Found Error in Browser with face-api.js

### ISSUE THREAD

**Issue by xyt417** [casdoor/casdoor#2807]
face-api.js library is trying to require the fs module, which is a core Node.js module that provides an API for interacting with the file system. However, this module is not available in the browser environment.

This might be resolved by including the following line in the webpack.configure.resolve.fallback field of the craco.config.js file:
```json
"fs": false

**Comment by hsluoyz** [comment]
@xyt417 hi, can you make a PR to fix it?

**Comment by HGZ-20** [comment]
Thank you for raising the issue and providing the solution. We have submitted a PR(#2810) to fix this problem.
