### ISSUE TITLE
 does the username support  case insensitive? 

### ISSUE THREAD

**Issue by wayneliu0019** [casdoor/casdoor#2813]
the username of casdoor is case sensitive which means `user1` and `User1` are two different users in casdoor, does it support case insensitive or is there a switch button or configuration item to treat `user1` and `User1` as one user? 

thanks!

**Comment by hsluoyz** [comment]
@wayneliu0019 why is that needed?

**Comment by wayneliu0019** [comment]
@hsluoyz  it is caused by our business logic, we need to view `user1` and `User1` the same user name, does casdoor support this feature ? 
if not, is there any workaround to resolve this demand?

thanks!!

**Comment by hsluoyz** [comment]
@wayneliu0019 fixed by: https://github.com/casdoor/casdoor/commit/0329d24867bab9c0c12e1fbc7c57fd2794341c6a

You can set `isUsernameLowered = true` in app.conf to support case insensitive username:

https://github.com/casdoor/casdoor/blob/0329d24867bab9c0c12e1fbc7c57fd2794341c6a/conf/app.conf#L18
