### ISSUE TITLE
Optimizing Signin Logic for Enhanced User Experience

### ISSUE THREAD

**Issue by u3breeze** [casdoor/casdoor#2817]
Could we refine the logic behind "Keep signin session," "Enable auto signin," and the "Auto signin next time" option on the login page? Consider this simplified approach:

1. "Enable auto signin" requires that "Keep signin session" is enabled in the application settings.
2. "Auto signin next time" is displayed on the front end only when "Keep signin session" and "Enable auto signin" are both active in the application settings.
3. The actual auto signin on the front end hinges on the user's choice of "Auto signin next time."

**Comment by u3breeze** [comment]
Based on actual tests, auto signin indeed depends on "Keep signin session." Without it enabled, no session is saved after logging in, disabling auto login for the next time.
I mean, is this the logic behind the settings here?
![image](https://github.com/casdoor/casdoor/assets/5889405/edc4d90b-6b16-4a9d-84cf-5de57db95b82)

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/91268bca7044ea335d1c962dcac9a03957538ca7
