### ISSUE TITLE
When using CAS protocol login will prompt password error

### ISSUE THREAD

**Issue by RWh1te0** [casdoor/casdoor#2820]
I use the login service by synchronizing AD users to Casdoor. However, I have noticed that when logging in to applications using the CAS protocol, attempting to log in with an LDAP account and password on the Casdoor login page results in a password error. This issue does not affect applications using OIDC and SAML protocols, as LDAP credentials can be used to log in successfully.
![image](https://github.com/casdoor/casdoor/assets/46064017/f361e9ca-a2ff-4889-85d2-8287c72f06a0)

**Comment by hsluoyz** [comment]
@RWh1te0 you can try adding LDAP to your application's signin methods table:

![image](https://github.com/casdoor/casdoor/assets/3787410/331024ea-0322-4a5a-a028-4685e2ae0ba8)

**Comment by RWh1te0** [comment]
@hsluoyz same result...
![image](https://github.com/casdoor/casdoor/assets/46064017/704f1764-faa7-4f1b-b9e5-989d829cb114)

**Comment by hsluoyz** [comment]
@RWh1te0 Use English screenshots, this issue will be deleted shortly
