### ISSUE TITLE
The mfa is not work in My Acount page

### ISSUE THREAD

**Issue by wxytjustb** [casdoor/casdoor#2823]
Accessing My Account Page
<img width="1677" alt="image" src="https://github.com/casdoor/casdoor/assets/3654858/71138657-2e11-4ade-9b0f-b155c58d2b4c">

Select App Setup
<img width="1560" alt="image" src="https://github.com/casdoor/casdoor/assets/3654858/64a42de2-e1f2-4c42-82a8-8915ad49239f">
 
Veify Password
<img width="863" alt="image" src="https://github.com/casdoor/casdoor/assets/3654858/e49c2247-e2b5-4d2f-ac53-1a02dc58f1c3">

No further action
<img width="805" alt="image" src="https://github.com/casdoor/casdoor/assets/3654858/09375942-0bfe-47e7-9156-47baa8e0cc0b">

When I use admin account to check this user, there is no button for type app.
![image](https://github.com/casdoor/casdoor/assets/3654858/d10ea20f-6193-4661-a6c4-0546c4ac86e2)

How can I configure the app-based MFA?

**Comment by leo220yuyaodog** [comment]
@wxytjustb The admin can not set app type mfa for user. It's need user itself use his device to generate the secrect.

**Comment by wxytjustb** [comment]
> @wxytjustb The admin can not set app type mfa for user. It's need user itself use his device to generate the secrect.

Thank you for your reply. 
My Account Page is the user's own personal settings page. The screenshot I sent is what the user sees, not the admin's page.
As a regular user, when I set up any type of MFA, nothing happens.

After entering the verification password, I expected the image below to appear, but it did not. 
![image](https://github.com/casdoor/casdoor/assets/3654858/7a379d3b-5f57-429d-ad0d-daf98fec5801)

**Comment by hsluoyz** [comment]
@wxytjustb can you post your browser console logs? (F12)

**Comment by wxytjustb** [comment]
> @wxytjustb can you post your browser console logs? (F12)

console logs
![image](https://github.com/casdoor/casdoor/assets/3654858/5c009b26-1f0a-4600-884b-39ede5069924)

network logs
![image](https://github.com/casdoor/casdoor/assets/3654858/d0bf2a2d-5b6d-4f06-aac2-3541cd607f41)

/api/mfa/setup/initiate request
![image](https://github.com/casdoor/casdoor/assets/3654858/efa47784-10fc-422e-b594-06eef594cde8)


/api/mfa/setup/initiate response
![image](https://github.com/casdoor/casdoor/assets/3654858/0f80207e-877a-4186-bed1-deeaed48fa22)

**Comment by hsluoyz** [comment]
@wxytjustb I tried and it worked. Go to demo site: https://demo.casdoor.com/login/casbin , login with username: `test` and password: `123`. The QR code showed up. So this is your own issue.

![image](https://github.com/casdoor/casdoor/assets/3787410/bbfc0562-4e5b-4c1a-be3b-7a23c1999ae7)

**Comment by SAMOXA** [comment]
Same probem. Email and SMS also not showing.
If user is not admin all work fine. 
Admin user can`t set 2FA/MFA for itself account.

**Comment by dacongda** [comment]
> Same probem. Email and SMS also not showing. If user is not admin all work fine. Admin user can`t set 2FA/MFA for itself account.

fail to reporduce, can you tell me how to do to reproduce this bug?

**Comment by hsluoyz** [comment]
@SAMOXA next time, provide detailed reproduce steps on demo site or self-hosted, provide demo video

This issue will be closed here
