### ISSUE TITLE
Please add linux/arm64 architecture to current docker images.

### ISSUE THREAD

**Issue by netandreus** [casdoor/casdoor#2824]
There are no linux/arm64 docker images after v1.428.0 Please add ```linux/arm64``` architecture to current docker images.

Image with linux/arm64:
https://hub.docker.com/r/casbin/casdoor/tags?page=1&name=v1.428.0

<img width="639" alt="Screenshot 2024-03-19 at 16 00 43" src="https://github.com/casdoor/casdoor/assets/313477/b5061619-60db-4f29-8ccd-daa301fa0e14">

Image without linux/arm64:
https://hub.docker.com/r/casbin/casdoor/tags?page=1&name=v1.578.0

<img width="639" alt="Screenshot 2024-03-19 at 16 00 55" src="https://github.com/casdoor/casdoor/assets/313477/e6c510ef-bb35-4d96-8c58-e921a4683ef4">

**Comment by hsluoyz** [comment]
@netandreus see: https://github.com/casdoor/casdoor/issues/2416#issuecomment-1766442931

**Comment by hsluoyz** [comment]
Thanks to this PR: https://github.com/casdoor/casdoor/pull/2969 , the arm64 image is back starting from v1.621.0: https://hub.docker.com/r/casbin/casdoor/tags
