### ISSUE TITLE
Sign in with Apple error: json: invalid use of ,string struct tag, trying to unmarshal unquoted value into bool

### ISSUE THREAD

**Issue by silenceWe** [casdoor/casdoor#2828]
Sign in with Apple error: json: invalid use of ,string struct tag, trying to unmarshal unquoted value into bool

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/8c415be7c7ee95aa071bda14b2c14b1f6dd61c82
