### ISSUE TITLE
login invalid captcha provider: 

### ISSUE THREAD

**Issue by keac** [casdoor/casdoor#2832]
Continuously entering the wrong account and password for multiple times, unable to load the verification code correctly
![image](https://github.com/casdoor/casdoor/assets/16091665/f816656b-7cf7-46b1-8f73-11f6dcd0d38f)

![image](https://github.com/casdoor/casdoor/assets/16091665/dc5834c8-85af-497d-b691-df4a2ee6165b)

**Comment by hsluoyz** [comment]
@keac how to reproduce it in settings?

**Comment by keac** [comment]
![image](https://github.com/casdoor/casdoor/assets/16091665/86382f2c-d081-48a0-ac93-91177c47877c)

**Comment by hsluoyz** [comment]
@keac you need to use latest version Casdoor. I tried and it works:

![image](https://github.com/casdoor/casdoor/assets/3787410/9a249372-a663-49f3-bd5d-9037d5b76e52)
