### ISSUE TITLE
feature: put DefaultFailedSigninLimit and DefaultFailedSigninFrozenTime into an application config

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#2837]
Right now, `DefaultFailedSigninLimit` and `DefaultFailedSigninFrozenTime` are hard-coded into the code. It's inconvenient for people to modify it dynamically (see issue like: https://github.com/psyai-net/webAppbug/issues/55). So we can put them into two integer input boxes in application edit page.

https://github.com/casdoor/casdoor/blob/d97f833d2adf54a68eb7473b1907176ccfb5bd2d/object/check.go#L31-L34

**Comment by hsluoyz** [comment]
Already done long ago

**Comment by lsh-0** [comment]
I'm not sure if the documentation reflects this:

https://deepwiki.com/search/how-do-i-change-the-lock-out-t_2b1b568e-054f-489a-98bf-fcae50735511

<img width="2713" height="4739" alt="Image" src="https://github.com/user-attachments/assets/3c9bfdd9-51e9-4916-83b7-6b1a82065793" />

**Comment by hsluoyz** [comment]
@lsh-0 you can add it by PR to: https://github.com/casdoor/casdoor-website
