### ISSUE TITLE
Login page input fields should have autocomplete attributes

### ISSUE THREAD

**Issue by jum** [casdoor/casdoor#2840]
The input field for the user name should have an autocomplete=“username” and password accordingly an autocomplete=“current-password” attribute. In the case of webauthn there should an autocomplete=“username webauthn” attribute for the user name to make filling out the values easier for the user as the browser pre-fills the data.

**Comment by jum** [comment]
I forgot: a type=“email” for the user name field may help users with mobile devices to avoid the auto-capitalization of the plain input field. Even though I use all lower case usernames for webauthn, the autocapitalization of the first letter is annoying.

**Comment by hsluoyz** [comment]
Hi @jum good idea! Can you make a PR?

**Comment by jum** [comment]
I can try, but currently I am traveling with no time to work on it. Will look into it when I am back home. Am 26.03.2024 um 22:41 schrieb Eric Luo ***@***.***>:﻿
Hi @jum good idea! Can you make a PR?

**Comment by jum** [comment]
No, still traveling. Probably several weeks. Am 02.04.2024 um 08:56 schrieb Eric Luo ***@***.***>:﻿
@jum any update?

**Comment by hsluoyz** [comment]
No one is contributing to this, closed here
