### ISSUE TITLE
Feature: Auto-register for unregistered phone numbers using SMS verification login

### ISSUE THREAD

**Issue by cyy95** [casdoor/casdoor#2850]
To improve user experience, I suggest implementing auto-registration for unregistered phone numbers. When a user enters a correct verification code for an unregistered phone number, the system should automatically create a new account for them.

This feature will simplify the onboarding process and reduce the steps needed to create an account. 

Refer to the figure below:
<img width="543" alt="image" src="https://github.com/casdoor/casdoor/assets/16273668/be6d15ae-a9d8-48ed-afb4-aff6d003e930">

**Comment by cyy95** [comment]
<img width="575" alt="image" src="https://github.com/casdoor/casdoor/assets/16273668/b06cffc3-8ff8-4d5b-b5fd-f13814c182e4">

**Comment by hsluoyz** [comment]
Not planned
