### ISSUE TITLE
Unable to login requires logout

### ISSUE THREAD

**Issue by Tiper-In-Github** [casdoor/casdoor#2851]
After accessing the root directory (/), I automatically redirected to the login page, but I was unable to log in. I was prompted to log out first.
I deployed the project in Docker and integrated the database and Redis. When I visited the website, it automatically redirected me to the login page for me to log in. However, after entering the information, it prompted me to logout first
![c159760bf6ccca917222f663a93f4f92](https://github.com/casdoor/casdoor/assets/62596032/c958beda-fc74-4e61-82b7-7954fc6a6bfd)
![1b699d267e18dde2d11b4db985300780](https://github.com/casdoor/casdoor/assets/62596032/5578a9c8-f5be-4e93-9f9f-b7564733dfef)

💻The prompt information may come from these codes:
![faaa4ed602e430c87c2dc00d16629e01](https://github.com/casdoor/casdoor/assets/62596032/9a4c0bed-bd45-4741-958e-3e523b598bfc)
![1f8237bc6791a1608afc4a40c4da107e](https://github.com/casdoor/casdoor/assets/62596032/ec71ce40-97ab-425d-9939-09749666f9ce)

**Comment by hsluoyz** [comment]
Cannot be reproduced, closed for now

**Comment by Tiper-In-Github** [comment]
The problem has been resolved, it is due to the interface data returned by casdoor being cached by CDN instead of XHR. Setting the API path to not cache can solve the problem
