### ISSUE TITLE
tags are not applied to api routes

### ISSUE THREAD

**Issue by waffle-frame** [casdoor/casdoor#2855]
Hello.

I encountered a strange thing when testing Casdoor. Using the official documentation, I studied the topic about tags.
I tested this functionality on the web interface and decided to apply it in my project. The problem is that the tags do not work for API routes. I figured this out through debugging [here](https://github.com/casdoor/casdoor/blob/6161040c678c9a3f950e5c33fcd66a90c473518c/controllers/webauthn.go#L200)

Why not make tags available for API routes, it’s very convenient?

**Comment by hsluoyz** [comment]
@waffle-frame can you make a PR to support it?

**Comment by waffle-frame** [comment]
@hsluoyz 
Yes, sure

**Comment by hsluoyz** [comment]
@waffle-frame what do you mean by "API routes"?

**Comment by waffle-frame** [comment]
@hsluoyz 
endpoint
