### ISSUE TITLE
Adding Self-Signed Certificate for LDAP Connection

### ISSUE THREAD

**Issue by alexnet123** [casdoor/casdoor#2859]
Hello,

I'm working on integrating LDAP over TLS and I'm using a self-signed certificate. I've run into an issue where the connection fails due to the certificate being self-signed. Could you guide me on how to properly configure the application to accept a self-signed certificate for the LDAP connection?

Thank you for your help!

**Comment by hsluoyz** [comment]
@alexnet123 provide reproducable steps (how you configured LDAP and cert), show screenshot and video for error messages

**Comment by alexnet123** [comment]
how to establish trust in self-signed certificates
