### ISSUE TITLE
Call add-user/update-user api with roles parameter no effect

### ISSUE THREAD

**Issue by MyColorfulDays** [casdoor/casdoor#2862]
When I call `add-user/update-user` api with `roles` parameter, although the user is created success, the roles not effect.
I want the roles of the user can be effect when I create or update user.

step 1.  prepare role to bind user.
<img width="905" alt="image" src="https://github.com/casdoor/casdoor/assets/21351745/74b57993-9068-41af-9104-5894c8b6c5a3">

step 2. call api to add/update user with `roles` parameter.
<img width="1106" alt="image" src="https://github.com/casdoor/casdoor/assets/21351745/87fffe4a-6592-4aae-93cc-1b328dd98179">

step 3. check the user create/update success, but the roles field is not what I want.
<img width="850" alt="image" src="https://github.com/casdoor/casdoor/assets/21351745/0cc8b007-1455-404e-b0f3-2a22d79319d1">

**Comment by hsluoyz** [comment]
@MyColorfulDays add roles in the "Roles" tab here: https://door.casdoor.com/roles

![image](https://github.com/casdoor/casdoor/assets/3787410/3e58bd5e-f274-46a7-8651-8916c302e273)

**Comment by MyColorfulDays** [comment]
Accoding to [swagger user api](https://door.casdoor.com/swagger/#/User%20API/ApiController.AddUser), when call `add-user/update-user` api can send the `roles` parameter to set user roles, but the users roles is not set success.
Can you support set user roles when call the add-user/update-user api.

**Comment by hsluoyz** [comment]
@MyColorfulDays as I said, you should call the Role API: https://door.casdoor.com/swagger/#/Role%20API

the roles field in user is virtual and is retrieved from the Role API too, it's read-only. If you want to modify it, call Role API
