### ISSUE TITLE
Why does /api/userinfo only return a very minimal set of information?

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [casdoor/casdoor#2866]
```json
{"sub":"50f86c88-cec8-4129-9688-8cbc25c5d047","iss":"http://localhost:8000","aud":"7b73ea18f885b5bbb9e7","preferred_username":"liuhuapiaoyuan","name":"nickname","picture":"https://cdn.casbin.org/img/casbin.svg"} , 
```
After testing, why can only so few fields be returned? No email, no phone

**Comment by hsluoyz** [comment]
@liuhuapiaoyuan the userinfo API is used by the OIDC flow, and the fields are determined by your OIDC scopes: https://casdoor.org/docs/how-to-connect/oidc-client#oidc-userinfo-fields . If your scope contains it, you will have it

![image](https://github.com/casdoor/casdoor/assets/3787410/ff869759-53e9-4909-ae3a-7b0aa70ae79d)

If you are not using OIDC, you can use get-account API (for yourself) or get-user API (for others). These APIs will provide full user fields.

**Comment by liuhuapiaoyuan** [comment]
Thank you very much. What interface can I use to update the current user's avatar, nickname, etc? Using POST
/api/update-user
？？
