### ISSUE TITLE
Put users and groups under the same menu and present them as a tree list on the front end

### ISSUE THREAD

**Issue by potatoone** [casdoor/casdoor#2868]
**1. It is strongly recommended to put users and groups under the same tree list, hoping to add batch select delete, disable and other functions.**

_`For example`_

![图片1](https://github.com/casdoor/casdoor/assets/72010312/30c7d673-89ee-4d5a-bd1a-af41cc177855)
<br>
**2. I also recommend adding the ability to quickly import user group parameters through an excel spreadsheet.**

_`Add groups field`_

![企业微信截图_17128261312797](https://github.com/casdoor/casdoor/assets/72010312/25fec165-30b5-4125-add2-89788b33b445)
<br>
- Minor additional advice: The tree list can be multi-selected mouse drag to quickly change the user group ownership migration

**Comment by hsluoyz** [comment]
Not planned, modify code by yourself
