### ISSUE TITLE
the token is valid even after logout

### ISSUE THREAD

**Issue by waffle-frame** [casdoor/casdoor#2869]
Hello.
Now I tested the logout endpoint.
When you try to logout, only the session is deleted, but the token remains in the token table, so the token, which should be invalid, still continues to work.

Perhaps deleting the session is enough for the token to stop working, if this is the case, tell me how to properly invalidate the token.

https://github.com/casdoor/casdoor/blame/master/controllers/account.go#L361

**Comment by hsluoyz** [comment]
@waffle-frame logout only clears the session cookie instead of the token. Delete the token by yourself by delete-token API
