### ISSUE TITLE
Editing login, registration, and forgotten password forms

### ISSUE THREAD

**Issue by kliatskiidenis** [casdoor/casdoor#2871]
The css styles added through the fields on the form edit page do not work as you expect, they edit the parent element, not the element itself, as indicated in the table. For example, on the screen, if you open the "user login" edit field and you want to change the background and height of the input, but the input is not edited.
<img width="1418" alt="2024-04-14-07 50 22" src="https://github.com/casdoor/casdoor/assets/128329970/4f766489-e071-4f23-a60a-902843dae5d8">
<img width="1229" alt="2024-04-14- 07 52 28" src="https://github.com/casdoor/casdoor/assets/128329970/fd5fc5f7-3320-421c-9346-7076aa9489c1">

the button can be changed only if you copy all the styles that the button itself has
<img width="1413" alt="2024-04-14-08 02 05" src="https://github.com/casdoor/casdoor/assets/128329970/e7da5708-436d-424e-9cac-00f54afe43a3">
<img width="1134" alt="2024-04-14- 08 02 45" src="https://github.com/casdoor/casdoor/assets/128329970/b58d7cf5-19ba-42eb-a4c5-cb9d4fbdd585">

**Comment by dacongda** [comment]
about signin button , you can use !important to solve , 

```
  .login-button {
    width: 100%;
    height:70px !important;
  }
```
![image](https://github.com/casdoor/casdoor/assets/47297289/e831c33c-5595-45bc-ab04-89c766aa0842)

about password field and username field ,  i may be solve soon

**Comment by dacongda** [comment]
btw, it seems that it is impossible to change the color of username field and password field without using the css selector

**Comment by kliatskiidenis** [comment]
> btw, it seems that it is impossible to change the color of username field and password field without using the css selector

and even when I edit the fields in the login form, the registration form remains unchanged, how to edit it?

**Comment by kliatskiidenis** [comment]
where to find the fields to edit in the registration form, for example, the location of the button, according to the design, I need to put the button at the bottom and at full width
<img width="560" alt="2024-04-14 22 50 13" src="https://github.com/casdoor/casdoor/assets/128329970/360c822b-ebd7-4f38-8146-c9b93fa6a45f">

**Comment by technodrome** [comment]
After visiting the demo, it seems to me that the layout, positions, colors, etc is completely hardcoded, save for form "editor" in the admin UI. This is very unfortunate approach. One should have complete control over look and feel of all user-related pages and their elements. Complete control over styling, positioning - in short, templating. Yes, there should be defaults, but hardcoded values cannot possibly be considered defaults. 

Templates should be available with references to `{{ .signupButton }}` etc. Editor should concentrate on available items / logic, not on their order or styles. BTW, solving CSS specificity problems by using `!important` is most definitely suboptimal and cannot be considered a proper solution. It's a hack, at best.

**Comment by dacongda** [comment]
> where to find the fields to edit in the registration form, for example, the location of the button, according to the design, I need to put the button at the bottom and at full width <img alt="2024-04-14 22 50 13" width="560" src="https://private-user-images.githubusercontent.com/128329970/322306350-360c822b-ebd7-4f38-8146-c9b93fa6a45f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTU2MTksIm5iZiI6MTcxMzE1NTMxOSwicGF0aCI6Ii8xMjgzMjk5NzAvMzIyMzA2MzUwLTM2MGM4MjJiLWViZDctNGYzOC04MTQ2LWM5YjkzZmE2YTQ1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwNDI4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTUzNGQ3NWU0ODY4MjRjNmJlYzNkM2Y1OGNjN2YyMDQzMTJkNmM1ZjEyMjE2ZGEzOTI3Mjc1MzY2MWMwMjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f3SXazduY_lWnHE6JfxDiwgswpvp_Fh7Idg-t2fK8s4">

currently we can only change the style of signin form , the custom setting of signup form is in progress

**Comment by dacongda** [comment]
> After visiting the demo, it seems to me that the layout, positions, colors, etc are completely hardcoded, save for form "editor" in the admin UI. This is very unfortunate approach. One should have complete control over look and feel of all user-related pages and their elements. Complete control over styling, positioning - in short, templating. Yes, there should be defaults, but hardcoded values cannot possibly be considered defaults.
> 
> Templates should be available with references to `{{ .signupButton }}` etc. Editor should concentrate on available items / logic, not on their order or styles. BTW, solving CSS specificity problems by using `!important` is most definitely suboptimal and cannot be considered a proper solution. It's a hack, at best.

we use [antd](https://ant-design.antgroup.com/components/overview/) for our input , select ,button ... components, so it is hard to change the style with css, althogh it provide change theme by json, but use json to edit theme may bring extra learning cost

**Comment by kliatskiidenis** [comment]
> наразі ми можемо змінити лише стиль форми входу, користувальницьке налаштування форми реєстрації триває

Can you tell me when the functionality will be implemented to fully edit the appearance of the Registration, Login and Forgot password forms?

**Comment by dacongda** [comment]
> > наразі ми можемо змінити лише стиль форми входу, користувальницьке налаштування форми реєстрації триває
> 
> Can you tell me when the functionality will be implemented to fully edit the appearance of the Registration, Login and Forgot password forms?

may be this week

**Comment by kliatskiidenis** [comment]
> may be this week

Please make it possible to completely replace the colors and sizes of the input checkboxes and other form elements, as well as the possibility to replace placeholders, labels and text with your own.
<img width="518" alt="2024-04-15 о 08 57 25" src="https://github.com/casdoor/casdoor/assets/128329970/6b19ec9b-79d3-479e-8edb-0488cf669562">
<img width="292" alt="Знімок екрана 2024-04-15 о 09 32 54" src="https://github.com/casdoor/casdoor/assets/128329970/571b7ab8-a4f6-4d12-b39a-064478519d9e">

**Comment by dacongda** [comment]
> > may be this week
> 
> Please make it possible to completely replace the colors and sizes of the input checkboxes and other form elements, as well as the possibility to replace placeholders, labels and text with your own. <img alt="2024-04-15 о 08 57 25" width="518" src="https://private-user-images.githubusercontent.com/128329970/322369760-6b19ec9b-79d3-479e-8edb-0488cf669562.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxODQxNjAsIm5iZiI6MTcxMzE4Mzg2MCwicGF0aCI6Ii8xMjgzMjk5NzAvMzIyMzY5NzYwLTZiMTllYzliLTc5ZDMtNDc5ZS04ZWRiLTA0ODhjZjY2OTU2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxMjI0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDcwZjgyNjRlNzczMDA1MDM1N2M4ZTFmNWVhZDYwM2ZhZTFjM2M3NDkzMGZmMWM4MmQ4NWVmZTI4MTJjNjk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SE02ZSOFQF3dcX8McDM_eZ1W3JkQzMBw75SZGWb84bQ"> <img alt="Знімок екрана 2024-04-15 о 09 32 54" width="292" src="https://private-user-images.githubusercontent.com/128329970/322376469-571b7ab8-a4f6-4d12-b39a-064478519d9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxODQxNjAsIm5iZiI6MTcxMzE4Mzg2MCwicGF0aCI6Ii8xMjgzMjk5NzAvMzIyMzc2NDY5LTU3MWI3YWI4LWE0ZjYtNGQxMi1iMzlhLTA2NDQ3ODUxOWQ5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxMjI0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMmE0ZDE1OWFiMTczMmZlZmQ1ZTg0YWYxZGM4YjFlMzBkZDZhOTRiNGUxYzVlM2I2ZGE3NjkwMjhjODdlMzk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Csu7m7-YwyX6T9HHrCD5TwJJIscadW-3I8F3wO7k7iQ">

emmm. i think it will be better to change the source code

**Comment by kliatskiidenis** [comment]
https://github.com/casdoor/casdoor/pull/2880

Does this mean that you have already made it possible to change the appearance of the registration form?

**Comment by dacongda** [comment]
> #2880
> 
> Does this mean that you have already made it possible to change the appearance of the registration form?

yes, but still have some limited
