### ISSUE TITLE
Please add to the site more detailed instructions for changing the elements of the forms

### ISSUE THREAD

**Issue by kliatskiidenis** [casdoor/casdoor#2872]
Please add to the site more detailed instructions for changing the elements of the forms, because it is not clear how to edit the registration form and the forgotten password form. Designers send us layouts with completely different fields, buttons and a completely different arrangement of field names, and it is not clear how to do it.
It would be good to use your own pages for login, registration, forgot password, which will correspond to the design of the project.

**Comment by hsluoyz** [comment]
Need to add docs:

![image](https://github.com/casdoor/casdoor/assets/3787410/ffd69562-1b1b-4657-82c6-3df7823f47a9)

**Comment by hsluoyz** [comment]
@kliatskiidenis see docs:

- Signup items table: https://casdoor.org/docs/application/signup-items-table
- Signin items table: https://casdoor.org/docs/application/signin-items-table
