### ISSUE TITLE
Show error on oauth signin if a user with that email already exists

### ISSUE THREAD

**Issue by sumann7916** [casdoor/casdoor#2873]
Currently, if I sign in with google with a particular email, say: `myemail@gmail.com` and again sign in with my github account which was created with the same email, two users are created with the same email. I would like to instead send an error that the email is not unique or rather link it to the same user.

**Comment by hsluoyz** [comment]
@sumann7916 this is already supported.

Enable "Enable Email linking" in application edit page. For example: https://door.casdoor.com/applications/built-in/app-built-in

![image](https://github.com/casdoor/casdoor/assets/3787410/97de65ae-6024-472d-bf8e-b4f21cd8717d)
