### ISSUE TITLE
Please add the Ukrainian language in the "Registration", "Login", "Forgot password" forms.

### ISSUE THREAD

**Issue by kliatskiidenis** [casdoor/casdoor#2874]
Please add the Ukrainian language to the "Registration", "Login", "Forgot password" forms, because you can choose the language, but the content of the forms is not translated.

**Comment by hsluoyz** [comment]
@kliatskiidenis can you make a PR to modify: https://github.com/casdoor/casdoor/blob/master/web/src/locales/uk/data.json ?

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/87e2b97813ed3dbc9f0924804587fd309618a538
