### ISSUE TITLE
How to enable/disable user mfa by casdoor-go-sdk

### ISSUE THREAD

**Issue by quyouyuan** [casdoor/casdoor#2876]
Dose the casdoor-go-sdk implement enable/disable user mfa method, I'm not found it.

**Comment by quyouyuan** [comment]
Dose the casdoor-go-sdk support enable/disable user mfa method, I'm not found it.

**Comment by quyouyuan** [comment]
I have tried update user api with `mfaEmailEnabled` parameter, but still no effect.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/dfa4503f2490b7ef9cee5a275822e3e8a891594e
