### ISSUE TITLE
[bug-report] : signup error "Code has not been sent yet!"

### ISSUE THREAD

**Issue by jimczj** [casdoor/casdoor#2878]
When multiple people register, there may be errors in sending the verification code because the application settings only allow registration using phone numbers. `DisableVerificationCode` func can pass a empty value. When passed with empty values,  the latest record is set to is_used.

Version:
v1.595.0

**Comment by jimczj** [comment]
This code has bug


<img width="569" alt="企业微信截图_33a44f94-ac8d-4c18-856a-55ebb82a6910" src="https://github.com/casdoor/casdoor/assets/13499146/70aa63f6-aff6-4dc8-bf5e-1db175a00359">



https://github.com/casdoor/casdoor/blob/master/controllers/account.go#L264

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/66d0758b1317721c8c835d95df2cc3da7337de41
