### ISSUE TITLE
feature: Support more arch for docker image: casdoor-all-in-one

### ISSUE THREAD

**Issue by leoncamel** [casdoor/casdoor#2884]
Hey, casdoor community.

Currently, the casdoor-all-in-one docker image only provide `linux/amd64` arch. Should we add more arch support? For example, `linux/amd64`?

Thanks, and Best Regards.

**Comment by hsluoyz** [comment]
Duplicated, see: https://github.com/casdoor/casdoor/issues/2416#issuecomment-1766442931
