### ISSUE TITLE
security problem

### ISSUE THREAD

**Issue by jindong5210** [casdoor/casdoor#2887]
Any application with clientId, clientSecret can delete other applications via RESTful API even it belongs to  different organization 
﻿
eg:
Application A belongs to Organization A1
Application B belongs to  Organization B1
Application A can delete Application B via RESTful API

**Comment by jindong5210** [comment]
> @jindong5210 is "Organization A1" the `built-in` org?
@hsluoyz it's not a `built-in` org, I created these two organizations using casdoor UI

**Comment by JamSECU** [comment]
@hsluoyz 
[Fix "app" user API denied issue](https://github.com/casdoor/casdoor/commit/1305899060d4e734a81dfec54c566d5a563126f6)
app has all permissions.

**Comment by polarathene** [comment]
For reference, better demonstrated (and descriptive issue title) at the duplicate: https://github.com/casdoor/casdoor/issues/3037

**Comment by hsluoyz** [comment]
Dup with: https://github.com/casdoor/casdoor/issues/3003
