### ISSUE TITLE
I couldn't get enforce to work correctly on the Casdoor SDK

### ISSUE THREAD

**Issue by yigitmoyagro** [casdoor/casdoor#2888]
Hello, I've defined models and then enforcers on Casdoor. I've also defined a permission to use in methods. Afterwards, I'm trying to use enforcer methods via the Go Casdoor SDK. However, I couldn't get it to work no matter what I try. It always returns false. Can you help me?

```
	casbinReq := casdoorsdk.CasbinRequest{"admin", "/test", "GET"}
	tt, err := casdoorsdk.Enforce("xxx/perm_xxx", "xxx/xxx_rest_model", "xxx/yyy-backend", casbinReq)
```

**Comment by yigitmoyagro** [comment]
Model 

`[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && regexMatch(r.act, p.act)`


![image](https://github.com/casdoor/casdoor/assets/166943721/efe2e37f-30a2-4676-a187-2083ef0e4468)

**Comment by hsluoyz** [comment]
fixed by: https://github.com/casdoor/casdoor-go-sdk/pull/113
