### ISSUE TITLE
sync without fill owner by casdoor

### ISSUE THREAD

**Issue by HRNasr** [casdoor/casdoor#2891]
1- Is it possible to sync the external database with the user table without choosing a tenant (owner)? We have to fill this field (owner) ourselves and not by the casdoor. This mode is helpful for merging multi-tenancy database with casdoor user databases and
2- sync with Custom where  (not all data)

**Comment by hsluoyz** [comment]
@HRNasr then setup multiple syncers for each owner/tenant
