### ISSUE TITLE
Encrypted users password

### ISSUE THREAD

**Issue by HRNasr** [casdoor/casdoor#2892]
For some applications, plain user passwords are required. But keeping the password safe is also important. The possibility of adding encrypted passwords with a specified key for each tenant can help in these scenarios.
ex: AES-CBC or ...

**Comment by hsluoyz** [comment]
@HRNasr password encryption is supported. See docs: https://casdoor.org/docs/organization/overview

![image](https://github.com/casdoor/casdoor/assets/3787410/b5805b48-3c53-4fd7-adf5-4ede4df79338)
