### ISSUE TITLE
Encrypted-Password

### ISSUE THREAD

**Issue by HRNasr** [casdoor/casdoor#2899]
one question:
current method is password-hashing and not password-encryption
or i wrong ???

_Originally posted by @HRNasr in https://github.com/casdoor/casdoor/issues/2892#issuecomment-2072435549_

**Comment by dacongda** [comment]
you can enctypt password by setting password type in organization setting
![image](https://github.com/casdoor/casdoor/assets/47297289/01eec561-5602-4fd1-84bc-be6e8c0d2656)

**Comment by dacongda** [comment]
when you set type to plain, it will do nothing .
