### ISSUE TITLE
[feature] support receive sms code to signin/login?

### ISSUE THREAD

**Issue by irelance** [casdoor/casdoor#2901]
![pic](https://github.com/casdoor/casdoor/assets/2898566/13bdb2dc-8029-4224-9df6-cc4e66f8e648)

Does casdoor has plan to support this way to verify user phone number?

**Comment by hsluoyz** [comment]
@irelance yes, see: https://door.casdoor.com/login

![image](https://github.com/casdoor/casdoor/assets/3787410/f7fe9fe1-2c0e-48ad-87f3-8af91de1f02b)

**Comment by irelance** [comment]
No, I mean. Casdoor not send code to user. Instead, user send code to sms provider, and casdoor get the receive code from sms provider

**Comment by hsluoyz** [comment]
@irelance does any SMS service vendor provide such API? We cannot support it without API
