### ISSUE TITLE
how to deny all user but only allow special role?

### ISSUE THREAD

**Issue by jump2cn** [casdoor/casdoor#2902]
> @link89 you deny all first, then allow someone 

hi @hsluoyz 
I have created two permissions for users, one is to deny all, the other one allow a role. and the user have matched by permission in the user info page, but it still deny when user login.
![图片](https://github.com/casdoor/casdoor/assets/1173757/1ce07c0a-f379-4caf-8e2d-83ac82932b63)
![图片](https://github.com/casdoor/casdoor/assets/1173757/478060cf-5ead-4cf8-9312-d1b1124ab453)

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

_Originally posted by @jump2cn in https://github.com/casdoor/casdoor/issues/2881#issuecomment-2081357117_

**Comment by yoadey** [comment]
I've struggled with exactly the same issue.
I found the following code, which explains the current situation:
https://github.com/casdoor/casdoor/blob/master/object/check.go#L440
Therefore: If you don't define a deny-all permission, but for each app it's own allow rule, it should give you the desired outcome.

**Comment by hsluoyz** [comment]
@jump2cn like @yoadey said, understand the auth model first. Then debug the code to know why the permission is not triggered
