### ISSUE TITLE
Sign up prompt not working

### ISSUE THREAD

**Issue by filwaline** [casdoor/casdoor#2903]
After saving the application and signing up, the prompt page is not showing, and its preview does not reflect the changes made to signup items. 

using docker image: casbin/casdoor:latest

**Comment by hsluoyz** [comment]
@filwaline plz provide more reproduce steps. And the demo video to show this error

**Comment by filwaline** [comment]
Check out this [demo](https://demo.casdoor.com/applications/casbin/app-casvisor) and its corresponding [prompt page](https://demo.casdoor.com/prompt/app-casvisor).

The prompt displays "Sign Up Error: You are not expected to see this prompt page" instead of the sign-up items that are not visible but require prompted.

**Comment by hsluoyz** [comment]
@filwaline I tried and it worked:

![image](https://github.com/casdoor/casdoor/assets/3787410/83c00185-27b9-4e43-be80-b3f0af38e605)

![image](https://github.com/casdoor/casdoor/assets/3787410/6f90a1fd-907a-4a39-a3f6-b86e9662f77a)

**Comment by filwaline** [comment]
Yes, providers do work, but what I want is for text fields like email and phone to work as well. Unfortunately, they are not working.

**Comment by hsluoyz** [comment]
@filwaline it's not "not working". It's "not supported". You are asking for a new feature instead of reporting a bug. And that feature is currently not planned.
