### ISSUE TITLE
Can a user visit his profile page via casdoor's home page?

### ISSUE THREAD

**Issue by link89** [casdoor/casdoor#2905]
Given a user account test-user sign up with an app named test-app in organization test-org, 
when I use this user account to sign in casdoor, 
I get this error ` The user: built-in/test-user doesn't existed`

Is there anything I can do for the user to access his profile in casdoor, so that he can change his password, avatar, etc.

**Comment by hsluoyz** [comment]
@link89 see demo: https://forum.casbin.com/

![image](https://github.com/casdoor/casdoor/assets/3787410/074794be-27d0-42b5-b108-1ff59d38a59b)

Goes to:

![image](https://github.com/casdoor/casdoor/assets/3787410/76dd86cc-dce6-47de-9657-03005d2097e4)
