### ISSUE TITLE
can not add group info for user

### ISSUE THREAD

**Issue by jump2cn** [casdoor/casdoor#2907]
hi team,
I have an instance that is updated from an old version, and now it is 1.503.0. I found the user info page lost many fields, is there any control option to effect this? or some fields in the database are missing?

![图片](https://github.com/casdoor/casdoor/assets/1173757/f873e9c6-130e-42ec-b43c-24192ae8215a)

![图片](https://github.com/casdoor/casdoor/assets/1173757/5392222f-92f3-41a4-b528-9dcfbc2f9a9a)

**Comment by hsluoyz** [comment]
@jump2cn the community here only provides support for the latest version (aka v1.602.0 for now). So either you upgrade to latest version and update your wording, or you find a third-party which provides old version support.
