### ISSUE TITLE
webhook for signup via social login doesn't fire, signup through login ui will fire webhook

### ISSUE THREAD

**Issue by ivancetus** [casdoor/casdoor#2912]
in controllers auth.go

previously working version use two object.AddRecord to send webhooks
```go
record := object.NewRecord(c.Ctx)
record.Organization = application.Organization
record.User = user.Name
util.SafeGoroutine(func() { object.AddRecord(record) })

record2 := object.NewRecord(c.Ctx)
record2.Action = "signup"
record2.Organization = application.Organization
record2.User = user.Name
util.SafeGoroutine(func() { object.AddRecord(record2) })
```

however, current version use this method which I have no idea how it works
```go
c.Ctx.Input.SetParam("recordUserId", user.GetId())
c.Ctx.Input.SetParam("recordSignup", "true")
```

as title says, it won't send webhook for social login (signup)

**Comment by ivancetus** [comment]
update: I notice that in `routers/record.go` `AfterRecordMessage` webhook action is stated as `record2.Action = "new-user"` instead of `signup`, I got the functionality back by adding an identical webhook for my signup webhook that listens for action "new-user".

**Comment by hsluoyz** [comment]
@ivancetus yes, it's renamed to "new-user" now
