### ISSUE TITLE
Question: Token is not valid yet

### ISSUE THREAD

**Issue by HRNasr** [casdoor/casdoor#2921]
When and why does the following error occur?
"token is not valid yet"

I get this error almost every day at the first login !!!!!!!!!

**Comment by hsluoyz** [comment]
@HRNasr what scenario? Can you provide a demo video to show this error?

**Comment by hsluoyz** [comment]
@HRNasr I think it's your machine's timestamp not correct issue. Sync your time via NTP

**Comment by hsluoyz** [comment]
@HRNasr try the demo site: https://demo.casdoor.com/ , I can't reproduce it with the demo site
