### ISSUE TITLE
Cannot delete `buil-in` org and `build-in` application when edit config in `init_data.json`

### ISSUE THREAD

**Issue by ladung** [casdoor/casdoor#2925]
I have a error when edit `build-in` organization in `init_data.json`
![image](https://github.com/casdoor/casdoor/assets/43999277/04e7e65f-608a-4ef8-8b7c-e66b7c1aa8b8)

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/2187310dbc50b85351cb0811808187ea58a0be8b
