### ISSUE TITLE
How to verify whether the access token is expired or invalid?

### ISSUE THREAD

**Issue by webyushao** [casdoor/casdoor#2929]
After obtaining access_token using getAuthToken method on node side, I want to know when the access_token will expire. May I ask which interface can I check?
My process is to get the access_token through getAuthToken and then get the userInfo through the parseJwtToken method.

**Comment by hsluoyz** [comment]
@webyushao plz change all your texts (title and content) into English

**Comment by webyushao** [comment]
@hsluoyz If you have time, please explain the whole process of login verification, thank you

**Comment by hsluoyz** [comment]
@webyushao access_token is a JWT. It contains expire time after JWT parsing
