### ISSUE TITLE
After the /api/logout interface is invoked, casdoor is still logged in

### ISSUE THREAD

**Issue by webyushao** [casdoor/casdoor#2931]
I am calling the api/logout interface, passing in the access_token parameter, and the interface returns 
{ 
    "status": "ok", 
    "msg": "", 
    "sub": "", 
    "name": "", 
    "data": "built-in/renyu",
    "data2": null
}
However, I found that casdoor is still in the login state, and the casdoor_session_id in the cookie is still there. Why?

**Comment by hsluoyz** [comment]
I tried the demo site: https://door.casdoor.com/ and it works

![image](https://github.com/casdoor/casdoor/assets/3787410/721e9c69-513e-4860-8277-87d81e52352f)
