### ISSUE TITLE
Bug in sync database

### ISSUE THREAD

**Issue by HRNasr** [casdoor/casdoor#2933]
Bug in the database sync
1- The password is displayed as an star in the edit mode, which gives an error when the db connection test is performed, even though there is no problem when inserting the record.
2- The sync does not work properly and panics when the service is start. cronjob is not working and stop

goroutine panic: no users are provided

**Comment by hsluoyz** [comment]
@HRNasr 

For 1, star is only shown to frontend. For DB connection test, it runs in backend and the password is not star.

For 2, it has been fixed by: https://github.com/casdoor/casdoor/commit/0ecc1d599fda9913e4adfb429bf7298bd2de71e0

**Comment by hsluoyz** [comment]
For 1, moved to: https://github.com/casdoor/casdoor/issues/2943
