### ISSUE TITLE
StaticFilter doesn't 404 properly

### ISSUE THREAD

**Issue by wearpants** [casdoor/casdoor#2935]
Stumbled on this while debugging some reverse proxy issues - `StaticFilter` will serve the contents of `index.html` when requested file doesn't exist , instead of returning a 404 response. See these lines: https://github.com/casdoor/casdoor/blob/d24ddd4f1c7076497cb9e50bf835cd5c4d79c310/routers/static_filter.go#L132-L133

**Comment by hsluoyz** [comment]
@wearpants what do you mean by "requested file doesn't exist"? What's the scenario?

**Comment by wearpants** [comment]
When I request a file that does not exist on disk in the `/web/build` directory, instead of a 404 response, I get back the contents of `index.html`

```
$ curl http://mycasbin.example.com/NONESUCH
<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="Casdoor - An Identity and Access Management (IAM) / Single-Sign-On (SSO) platform with web UI supporting OAuth 2.0, OIDC, SAML and CAS"/><link rel="apple-touch-icon" href="https://demo.omaha-data.com/casdoor/static/img/favicon.png"/><link rel="manifest" href="https://demo.omaha-data.com/casdoor/static/site/casdoor/manifest.json"/><title>Casdoor</title><script defer="defer" src="./static/js/main.05f504df.js"></script><link href="./static/css/main.b5f23b34.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>
```

**Comment by hsluoyz** [comment]
@wearpants this is expected. As the frontend is a React SPA. You better learn what React is first.
