### ISSUE TITLE
face authentication without typing in the username

### ISSUE THREAD

**Issue by addisflava** [casdoor/casdoor#2936]
Hello there 
Am trying to use casdoor to grant users access to a secure area  , and am trying to see if i can get the facial recognition to work without asking  users to type in the user name . basically  do a face match with all the saved user facial data and get username and authorize the user . I really like to implement this with casdoor because  its user friendly and admins love used it with other things . i also really like  the subscription  mode which means i can give access to users for a period of time .
any help in the right direction will do

**Comment by addisflava** [comment]
Hello @hsluoyz

**Comment by hsluoyz** [comment]
@addisflava github way is making PR. And if you don't know how to code about it, I don't think we can make this feature right finally.

Doing so without username is very difficult. This is why we don't do this. I thought you proposed this idea so you know how to do this. But you said you don't know how to do it. So my answer is that I can't promise that we can do this well at this stage.
