### ISSUE TITLE
WeCom Login URL Need update

### ISSUE THREAD

**Issue by Coldfengzi** [casdoor/casdoor#2937]
according to
[https://developer.work.weixin.qq.com/community/question/detail?content_id=16454500534344725872](url) and
[https://developer.work.weixin.qq.com/document/path/98152#%E9%99%84%E5%BD%95](url)

[Provider.js](https://github.com/casdoor/casdoor/blob/c302dc7b8e22587c5f00652629173cc2ce38cc67/web/src/auth/Provider.js)
need change:
https://open.work.weixin.qq.com/wwopen/sso/qrConnect
==>
https://login.work.weixin.qq.com/wwlogin/sso/login/?login_type=CorpApp

**Comment by hsluoyz** [comment]
@Coldfengzi hi, can you make a PR to update it?

**Comment by hsluoyz** [comment]
@Coldfengzi can you make a PR?
