### ISSUE TITLE
Login field is case sensitive and untrimmed

### ISSUE THREAD

**Issue by krav** [casdoor/casdoor#2939]
I'm trying out Casdoor, and getting complaints from a significant percentage of users having trouble logging in.

Particularly people register with "email@example.com" only to later try to log in as "Email@example.com" or "email@example.com "--and getting rejected as a non-existent account. Sometimes they proceed to try and register again, being told that the account already exists. 

Can we add optionally downcasing and trimming the username field? 

(Using postgres as a backing database btw, this is possibly case insensitive in others?)

**Comment by hsluoyz** [comment]
This can be an org setting, or app.conf config
