### ISSUE TITLE
Where is the definition of "POST /api/enforce"?

### ISSUE THREAD

**Issue by ochive** [casdoor/casdoor#2940]
I don't know go lang, I can't find it in [enforcer.go](https://github.com/casdoor/casdoor/blob/master/controllers/enforcer.go).It seems only has CRUD of enforcer.

In Swagger, the api only supply "permission id"、“model id”、“resource id”、“owner”,  I expect a param like "enforce name" or "model name + adapter name" to use specific enforcer to do policy check, just like do it in casbin api.

Any help is greatly appreciated.

**Comment by hsluoyz** [comment]
@ochive the enforce API is in:

https://github.com/casdoor/casdoor/blob/c302dc7b8e22587c5f00652629173cc2ce38cc67/controllers/casbin_api.go#L25-L46

Actually you can use `enforcerId` as the param for this API, see this example (via casdoor-go-sdk): https://github.com/casdoor/casdoor-go-sdk/commit/c590d041256bf9049c40b0b17566f3b846496876

![image](https://github.com/casdoor/casdoor/assets/3787410/da836ae9-6e08-47e7-a462-d2b9901c1d43)

**Comment by ochive** [comment]
Thanks very much, I did it!
```bash
curl --location 'http://localhost:8000/api/enforce?enforcerId=sample_org%2Fenforcer_sample_rbac' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic ZWE0ODFlZTQ2YTRiNTUyNTcxYzY6Yzk0Yzk4OWYzNzNmMWE1N2JhOGNjMzkzM2ZmNWM4ZWI3MzhlNzc0ZA==' \
--header 'Cookie: casdoor_session_id=2f18717752adf3f1c78e372161780ee9' \
--data '[
  "lily","menu-home","read"
]'
```
