### ISSUE TITLE
Update user address failed

### ISSUE THREAD

**Issue by usb00** [casdoor/casdoor#2946]
Whether I'm in a local docker or demo environment, when I update user address, it alert

> json: cannot unmarshal string into Go struct field User.address of type []string

maybe the data type of Go is not match

![image](https://github.com/casdoor/casdoor/assets/169243230/c7e71139-6b84-4aad-9aac-b90014cbf733)

**Comment by hsluoyz** [comment]
`User.address` is a string array. The web UI should be modified to support "Address line 1" and "Address line 2" like below. So the update will succeed.

![image](https://github.com/casdoor/casdoor/assets/3787410/a88614ea-9256-44d0-835e-558b9d911dd2)
