### ISSUE TITLE
is "api/api/swagger.json " a valid rest call?

### ISSUE THREAD

**Issue by wayneliu0019** [casdoor/casdoor#2948]
I've deployed a casdoor with docker, and expose the service with `8000` port, I found weird API call: 

<img width="791" alt="image" src="https://github.com/casdoor/casdoor/assets/43563618/bcbd35ee-2718-409c-8379-dbc41a33ccfd">

Is `/api/api/swagger.json` a valid rest api call? I think it should be `/api/swagger.json` which requires authentication. 

My casdoor verison is `v1.571.0`
thanks

**Comment by hsluoyz** [comment]
@wayneliu0019 no matter, it's open source any way. Like: https://door.casdoor.com/api/api/swagger.json
