### ISSUE TITLE
Obtain the access_token based on the code

### ISSUE THREAD

**Issue by iamsee** [casdoor/casdoor#2949]
Obtain the access_token based on the code, when using the client_secret and other parameters in the document
![image](https://github.com/casdoor/casdoor/assets/6944557/3e323345-d69e-4dc7-aa32-e16a93fcdcac)
Response:
![image](https://github.com/casdoor/casdoor/assets/6944557/4d41732d-8d65-487f-a2a4-9ef8a85d3f9e)

**Comment by hsluoyz** [comment]
@iamsee it seems that your flow is wrong somewhere. The demo site: https://door.casdoor.com/ and all our users don't report such issue or bug in OAuth.
