### ISSUE TITLE
How to enable TOTP for a user?

### ISSUE THREAD

**Issue by waterloo3122** [casdoor/casdoor#2950]
For the built-in admin user

<img width="2518" alt="image" src="https://github.com/casdoor/casdoor/assets/6322033/cc4e9e15-4435-44b0-bd15-d642e9934da9">

Multi-factor authentication of Type app is editable:
<img width="1340" alt="image" src="https://github.com/casdoor/casdoor/assets/6322033/eb41783c-530a-44ed-b9e5-bcb1583c25fa">
<img width="2495" alt="image" src="https://github.com/casdoor/casdoor/assets/6322033/f53a5d83-7f21-4ad2-9672-3f29b7bc57de">

For a user I Created, Multi-factor authentication of Type app is not editable:

<img width="2506" alt="image" src="https://github.com/casdoor/casdoor/assets/6322033/a1bb0d47-18ca-43f3-939b-cc9c74d7371c">

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by leo220yuyaodog** [comment]
@waterloo3122 The totp type MFA need to be set by user itselt. After all, an administrator cannot own a user's device code.

**Comment by waterloo3122** [comment]
Thanks very much . 
One more question please, 
how to reset a user's mfa if a user lost his mfa device?
