### ISSUE TITLE
[Bug] QQ login on Android failed due to the missing 'state' parameter

### ISSUE THREAD

**Issue by Nyrest** [casdoor/casdoor#2959]
# Problem
I couldn't login to Casdoor using QQ on any Android browser, while desktop login is working well.
The `state` parameter in the url query of the callback url seems to be missing on Android.
PC callback: `https://door.casdoor.com/callback?code=XXX&state=XXX`
Android callback: `https://door.casdoor.com/callback?code=XXX`
This problem occurs on both the self-hosted instance and the Casdoor demo.

Tested on Chrome, Edge, and Firefox.
QQ: 8.9.80

# Reproduce
1. Log in to https://door.casdoor.com/login using QQ on an Android device
2. Get the error `There was a problem signing you in..`
3. `state` parameter in the url query is expected to be missing.

**Comment by hsluoyz** [comment]
@Nyrest provide a video to reproduce it

**Comment by Nyrest** [comment]
https://github.com/casdoor/casdoor/assets/16686147/c03b1120-dcec-4145-a877-20f729875b8d
