### ISSUE TITLE
[question] Token Endpoint responses with 'success' even when `client-secret` is wrong 

### ISSUE THREAD

**Issue by amoraitis** [casdoor/casdoor#2964]
Hitting the Token-Endpoint with incorrect client-secret value returns HTTP Status 200 OK, with an error.
![image](https://github.com/casdoor/casdoor/assets/17813786/589fe533-eb87-4ac7-bc6f-eebebd15dab6)

Is that expected? Should not this return another response code (failure) and return the error in the JSON response as defined [here](https://openid.net/specs/openid-connect-core-1_0.html#TokenErrorResponse)?

[Example from Microsoft's implementation.](https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols-oidc#error-response-1)

**Comment by hsluoyz** [comment]
@amoraitis Casdoor returns HTTP 200 for application-level errors, to differ from network errors. Use status and msg to parse the error
