### ISSUE TITLE
[feature] let user change his password on first login

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#2968]
Add a boolean field: `needUpdatePassword` to user. If it's true, when the user logs in next time, he will be redirectly to password reset page after successful login.

**Comment by ISulimanov** [comment]
could be considered as an implementation ref https://github.com/casdoor/casdoor/pull/2104

**Comment by hsluoyz** [comment]
@ISulimanov I think that previous PR should not be referred to in my opinion. That's why that PR doesn't get merged. If this issue's contributor follows your PR again, he will fail too. Thanks for understanding. These chats will be deleted shortly.
