### ISSUE TITLE
Casdoor forward auth on Caddy

### ISSUE THREAD

**Issue by excaliburzarau** [casdoor/casdoor#2972]
Hello guys,

I am currently trying to implement casdoor on my homelab. I currently have Caddy reverse proxy on my system. 

I tried to find documentation on forward auth for Casdoor with Caddy without success. 

I was able to find how it should work for Authentik as seem below.

app.company {
    # always forward outpost path to actual outpost
    reverse_proxy /outpost.goauthentik.io/* http://outpost.company:9000

    # forward authentication to outpost
    forward_auth http://outpost.company:9000 {
        uri /outpost.goauthentik.io/auth/caddy

        # capitalization of the headers is important, otherwise they will be empty
        copy_headers X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid X-Authentik-Jwt X-Authentik-Meta-Jwks X-Authentik-Meta-Outpost X-Authentik-Meta-Provider X-Authentik-Meta-App X-Authentik-Meta-Version

        # optional, in this config trust all private ranges, should probably be set to the outposts IP
        trusted_proxies private_ranges
    }

    # actual site configuration below, for example
    reverse_proxy localhost:1234
}

I believe it should be similar but not quite. 

Did anyone implement this on Caddy that can provide an example of how my Caddyfile should be for Casdoor forward auth?

Best Regards

**Comment by stepin** [comment]
https://www.authelia.com/integration/trusted-header-sso/introduction/#response-headers has some description about expected headers. Idea that JWT is parsed on API GW level (in caddy or in dedicated microservice) and then other microservices receives some trusted headers.

Something like this https://github.com/CSU-OSA/Akashic-auth ? For sure, it will be better if this feature (headers for backend microservices) will be supported and described in the main project.

Also, https://github.com/casdoor/casdoor/issues/2001 looks like duplication.

Also, looks like https://github.com/casbin/caddy-authz has policy checks but it doesn't send any headers to microservices but it can be good starting point.

**Comment by excaliburzarau** [comment]
Hello

Thank you for the Reply. I ended up applying a different sso solution. 
But Will Be a good help to other people on the same situation i was.

Best Regards
