### ISSUE TITLE
[Feature] (SAML) Add optional assertion & message signing

### ISSUE THREAD

**Issue by stephenjamieson** [casdoor/casdoor#2977]
**Is your feature request related to a problem? Please describe.**

Some applications require both the assertion and message to be signed.  Currently, Casdoor will sign the message only which does not meet the application requirements. As an aside, it may be a good idea to add signing for other parts of the response like the metadata as well if desired.  Note that other providers such as [Authentik](https://github.com/goauthentik/authentik/issues/7909) have the same limitation.  

**Describe the solution you'd like**

An option for each application that will sign both the message and assertion in the SAML response.

**Comment by hsluoyz** [comment]
@stephenjamieson can you make a PR?

**Comment by stephenjamieson** [comment]
Would love to, however I am not very familiar with SAML nor golang at the moment.

**Comment by hsluoyz** [comment]
@stephenjamieson can you make a PR?

**Comment by stephenjamieson** [comment]
Hi @hsluoyz, I've decided to go another direction.  Thanks.
