### ISSUE TITLE
User's password is still not encrypted after setting the password storage algorithm

### ISSUE THREAD

**Issue by seeleclover** [casdoor/casdoor#2982]
After changing the password storage algorithm of the organization to bcrypt, I immediately created several users and set passwords under this organization. But I saw in the user table of the database that the user's password is still in plain text. May I ask if this is a security problem?

![image](https://github.com/casdoor/casdoor/assets/37256067/c3354faa-517c-47c3-b450-578b5069f561)

**Comment by seeleclover** [comment]
I found in the code that in Line 512 of the file `controllers/user.go` , in the `SetPassword` function, the variable `newPassword` was passed directly to `targetUser.Password` without hash encryption.

![image](https://github.com/casdoor/casdoor/assets/37256067/58caaaea-fdda-4d34-8ee3-eeb5d7968d21)

In addition, I also discovered another issue. In Line 513 of the file, the value of `targetUser.NeedUpdatePassword` is set to `false`, but immediately in Line 515, the `object.UpdateUser` method still takes "need_update_password" as an input parameter. Is there a corresponding relationship here?

**Comment by dacongda** [comment]
> I found in the code that in Line 512 of the file `controllers/user.go` , in the `SetPassword` function, the variable `newPassword` was passed directly to `targetUser.Password` without hash encryption.
> 
> ![image](https://private-user-images.githubusercontent.com/37256067/335896314-58caaaea-fdda-4d34-8ee3-eeb5d7968d21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzgxODQsIm5iZiI6MTcxNzQ3Nzg4NCwicGF0aCI6Ii8zNzI1NjA2Ny8zMzU4OTYzMTQtNThjYWFhZWEtZmRkYS00ZDM0LThlZTMtZWViNWQ3OTY4ZDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA1MTEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZWQ4YWRlZTIwYzlkNTMyOWNkNjY3MWEwNGFmOGYwZWExNzgzYTM0YWE3NjcyZDNlOGE0ZWU2YjA4OGFiNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bRoMrzOrUAa0ad4MYX7PvKc1AHDDHTfgGZdyBdD1A28)
> 
> In addition, I also discovered another issue. In Line 513 of the file, the value of `targetUser.NeedUpdatePassword` is set to `false`, but immediately in Line 515, the `object.UpdateUser` method still takes "need_update_password" as an input parameter. Is there a corresponding relationship here?

the string array for UpdateUser define which column will be updated, so I add need_update_password to the array.
