### ISSUE TITLE
MFA Switch without skip the previous configuration

### ISSUE THREAD

**Issue by HRNasr** [casdoor/casdoor#2983]
Is it possible to switch between methods SMS and Email and TOTP-APP for mode MFA without changing the (Config) recovery codes and initial configuration in the system? Apparently, with any change in the selection of the preferred method, the previous settings are deleted.

**Comment by hsluoyz** [comment]
@HRNasr can you provide more details? screenshots and videos

**Comment by EZ4Jam1n** [comment]
@HRNasr Thank you for your feedback. The current design of switching MFA methods in Casdoor aims to ensure system security and data integrity. Similar to the MFA process on platforms like GitHub, our implementation removes the previous authentication method when switching to a new one, requiring the user to reconfigure using the new method.

We understand that this can be inconvenient, especially for users of the TOTP_APP method. If we receive more feedback indicating that this approach is not user-friendly, we may consider optimizing the process to allow users or administrators to change the authentication method without deleting the existing registration information.
