### ISSUE TITLE
casdoor's casbin model not support casbin built-in function

### ISSUE THREAD

**Issue by pathing** [casdoor/casdoor#2991]
casdoor's casbin model not support casbin built-in function, such as keyMatch

**Comment by hsluoyz** [comment]
@pathing can you make a PR?

**Comment by dacongda** [comment]
it did support keyMatch when I use enforcer and model directly by using casbin api exposed by casdoor 

enforcer
![image](https://github.com/user-attachments/assets/47630d28-edd3-4d0c-a546-5e570e2b418b)

model
![image](https://github.com/user-attachments/assets/7e35bca0-ac8c-47b8-9c37-e6496f8288e4)

request & result
![image](https://github.com/user-attachments/assets/56f78790-bffa-4897-9341-1a5fc94b826e)

**Comment by hsluoyz** [comment]
Closed for cannot reproduce
