### ISSUE TITLE
api/login/oauth/access_token need using mobile verification codes

### ISSUE THREAD

**Issue by harryhan1989** [casdoor/casdoor#2992]
api/login/oauth/access_token

I hope this endpoint can implement verification of mobile verification codes for logging in to a WeChat Mini Program using mobile verification codes. Since enterprise applications require predefined users, the method of automatically registering and verifying through the code returned by the WeChat Mini Program is not feasible. I cannot allow automatic registration by others.

Let me know if you need any further assistance!

**Comment by hsluoyz** [comment]
Have no idea what this issue is talking about
