### ISSUE TITLE
All users can login admin dashboard and can change all configs and can delete all other users.

### ISSUE THREAD

**Issue by pozen** [casdoor/casdoor#2998]
All users can login admin dashboard and can change all configs and can delete all other users except the admin.Is this a question?

Even I add role which just contain Read operate. Which applied to normal users.  BUT it is not worked.

**Comment by hsluoyz** [comment]
@pozen see docs: https://casdoor.org/docs/basic/core-concepts#how-does-casdoor-manage-itself

and given that you are causing uncomfortable and bias among the community with your title and text, this issue will be deleted shortly.
