### ISSUE TITLE
[bug] fix the address issue for OIDC

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#3001]
See: https://github.com/Timshel/vaultwarden/issues/65#issuecomment-2156223591

**Comment by Timshel** [comment]
When searching for the issue I found this previous issue with additional information: https://github.com/casdoor/casdoor/issues/1184.
There is some mention of previously reverted code due to conflict and a hint on a possible way to fix it.

I won't have time to look at it so Good luck :).

**Comment by rimm74rus** [comment]
And exactly the same problem with proxmox authorization

**Comment by Timshel** [comment]
Commit was reverted so probably make sense to reopen the issue.
Tested the `1.632.0` release, and it was failing too.

When manually exchanging the code for token I could see:
```
  "address": {
    "formatted": "",
    "street_address": "",
    "locality": "",
    "region": "",
    "postal_code": "",
    "country": ""
  },
```
So a bit unsure why it would fail, but I would recommend to just not include the field when there is no data.

**Comment by dacongda** [comment]
can you tell us what tool / platform you are using that cause this problem ?

**Comment by dacongda** [comment]
> Commit was reverted so probably make sense to reopen the issue. Tested the `1.632.0` release, and it was failing too.
> 
> When manually exchanging the code for token I could see:
> 
> ```
>   "address": {
>     "formatted": "",
>     "street_address": "",
>     "locality": "",
>     "region": "",
>     "postal_code": "",
>     "country": ""
>   },
> ```
> 
> So a bit unsure why it would fail, but I would recommend to just not include the field when there is no data.

can you tell us what tool / platform you are using that cause this problem ?

**Comment by Timshel** [comment]
I'm using https://github.com/ramosbugs/openidconnect-rs which in general follow the spec quite strictly.

Since the change in `1.632.0` was reverted I did not spend more time trying to understand why it failed even with the new format.

**Comment by dacongda** [comment]
> I'm using https://github.com/ramosbugs/openidconnect-rs which in general follow the spec quite strictly.
> 
> Since the change in `1.632.0` was reverted I did not spend more time trying to understand why it failed even with the new format.

thanks for reply, we will try to fix it soon.

**Comment by dacongda** [comment]
> I'm using https://github.com/ramosbugs/openidconnect-rs which in general follow the spec quite strictly.
> 
> Since the change in `1.632.0` was reverted I did not spend more time trying to understand why it failed even with the new format.

I guess you are using the gitlab example of the openidcinnect-rs. however, the gitlab exapmle example add some external fields to the UserInfoClaim, you can remove the relevant these field to fix the problem, like below.

```rust
struct GitLabClaims {
    // Deprecated and thus optional as it might be removed in the futre
    // sub_legacy: Option<String>,
    // groups: Vec<String>,
}
```

**Note: you need to use v1.632.0 **

**Comment by Timshel** [comment]
Just to clarify I'm not really using Casdoor, I'm maintaining a PR to add OpenId Connect to Vaultwarden and someone had issues with it. 

As for your suggestion since the Address is part of the default [CoreIdTokenClaims](https://docs.rs/openidconnect/latest/openidconnect/core/type.CoreIdTokenClaims.html) it's not easy to ignore.
