### ISSUE TITLE
How to ensure the user info has email without MFA?

### ISSUE THREAD

**Issue by jump2cn** [casdoor/casdoor#3009]
Hi team,

My users can log in through third-party Oauth authorization, but some authorization sources do not require an email address. I hope that these users can provide the email after logging in. 

Enabling the MFA feature for org to send the verify code through email will also block the login process, but it's too complex for my normal user. Is there any simple way to do this?

maybe we can add an option to enable a new flow about 'fill user base info' for this case. to require the user to complete the registration form for the first time OAuth login.
![MFA process](https://github.com/casdoor/casdoor/assets/1173757/16aea1d8-7f69-4fd2-b079-556b86933bb4)

**Comment by javi17** [comment]
![Screenshot from 2024-09-05 16-16-41](https://github.com/user-attachments/assets/b7d2df81-f7bf-4797-b265-29aa2ffc6b69)
