### ISSUE TITLE
Permission Rules are not inserted to the custom adapter

### ISSUE THREAD

**Issue by seeleclover** [casdoor/casdoor#3012]
When I created permission rules, I created a custom adapter according to the requirements of the document and filled in the corresponding database table name of the adapter in the permission rule menu. 

![image](https://github.com/casdoor/casdoor/assets/37256067/4720c3f3-f27c-4d66-b9ab-b21f0a7c214e)

However, the rules were not written to this table, but were still written to the original `permission_rule` table.

![image](https://github.com/casdoor/casdoor/assets/37256067/b9009b6c-08cc-46f7-bb2e-bb6e8f7d8bcf)
![image](https://github.com/casdoor/casdoor/assets/37256067/d69c5c46-3446-488e-9aac-f60d12ec4d6c)

**Comment by hsluoyz** [comment]
@seeleclover use English everywhere (including images). This issue will be deleted shortly
