### ISSUE TITLE
SendCloud Email Sending Service Integration into Casdoor

### ISSUE THREAD

**Issue by frank-email-sms** [casdoor/casdoor#3014]
Hello Casdoor Team,

I am exploring the possibility of integrating SendCloud's email sending service into the Casdoor project. This integration would enable Casdoor to send emails for various user interactions such as registration confirmation, password reset, etc.

I have come across a Go language package that seems suitable for this purpose: https://github.com/frank-email-sms/sendcloud-email-go.

My questions are:

[^1]: Is there any existing support or plan to integrate SendCloud's email service into Casdoor?
[^2]: If not, would the Casdoor team be open to accepting a contribution that adds this integration?
[^3]: Are there any specific guidelines or best practices for contributing to Casdoor?
[^4]: What are the potential challenges or considerations for integrating an external email service into Casdoor?

I am willing to contribute to this integration effort if the Casdoor team sees value in it. Thank you for considering my inquiry and for your time.

**Comment by hsluoyz** [comment]
@frank-email-sms who are you? Why are you hiding your identity? What's your real github account?

The sendcloud is not the correct one. We will not add it.

This issue will be deleted shortly
