### ISSUE TITLE
Casdoor DB requires DROP access to be granted to my DB user

### ISSUE THREAD

**Issue by praveenkumar1798** [casdoor/casdoor#3025]
The user created for my database doesn't have access to DROP or ALTER OR DELETE for security reasons in my organization. At max we can add drop or alter or delete access for few tables but not for the entire server. Is there a way to bypass this error. If dropping the table is the only option what are the other tables to which drop access should be given ?

panic: Error 1142: DROP command denied to user '###############' for table 'casbin_api_rule' . 

Need some help here. Thanks.

**Comment by SuccessZ** [comment]
@praveenkumar1798 Could you provide more detailed steps to trigger the bug? For example, what operations were performed on what data?
