### ISSUE TITLE
Certificate value in every SAML Response is getting changed

### ISSUE THREAD

**Issue by gayathrisj** [casdoor/casdoor#3029]
The certificate value in every SAML Response is changing, because of that, the user cannot log in to Atlassian through SAML SSO with the error Invalid Thumbprint.

**Comment by hsluoyz** [comment]
@gayathrisj why is it changed? Can you point out the source code location?

**Comment by hsluoyz** [comment]
Closed as stale

**Comment by gayathrisj** [comment]
Please find the below summary for the above issue from the JIRA team:
1. Checked the SAML SSO Configurations on the Atlassian cloud and it looks good
2. Checked the SSO configurations on IDP as well and verified the required values
3. Tried to login for one user and captured the HAR File as well from the user login
4. The user's SSO login got failed with the error Invalid Thumbprint
5. We have analysed the HAR File from the user login and found that the Certificate value present in HAR file is different than the actual value updated on Atlassian

**Next step:**
1. From the HAR File analysis it looks like the Certificate value in every SAML Response is getting changed and because of that the user is unable to login to Atlassian through SAML SSO.
2. You can check with the IDP team about the same and ask them to fix or update this on the IDP, so we can get only one certificate while logging through SAML SSO.

**Comment by gayathrisj** [comment]
@hsluoyz  please can you check the above one

**Comment by hsluoyz** [comment]
@gayathrisj I don't personaly use Atlassian cloud. It's commercial and we will not buy one to test it for you. Better come with a PR so we can help review it.
