### ISSUE TITLE
casdoor proxmox ve (bs)

### ISSUE THREAD

**Issue by rimm74rus** [casdoor/casdoor#3030]
If the automatic login option is enabled in the application settings, then digitization occurs "openid authentication failure; rhost=::ffff:*.*.*.* msg=Failed to verify ID token: Invalid nonce: nonce mismatch"
If the option is disabled, it redirects to the casdoor authorization page and authorization passes.

**Comment by hsluoyz** [comment]
@rimm74rus can you give more details for reproduce steps?

**Comment by rimm74rus** [comment]
that's all there is in the logs. If you check the Auto sign in box in casddor in identity/Application, then in proxmox ve there is such an error in the logs "openid authentication failure; rhost=::ffff:... msg=Failed to verify ID token: Invalid nonce: nonce mismatch"
If you disable the Auto sign in option, then you are redirected to the casdoor authorization page where you can select an active user session and then authorization in proxmox ve is triggered. That is, the capture of an active session does not work.

**Comment by rimm74rus** [comment]
@hsluoyz 
that's all there is in the logs. If you check the Auto sign in box in casddor in identity/Application, then in proxmox ve there is such an error in the logs "openid authentication failure; rhost=::ffff:... msg=Failed to verify ID token: Invalid nonce: nonce mismatch"
If you disable the Auto sign in option, then you are redirected to the casdoor authorization page where you can select an active user session and then authorization in proxmox ve is triggered. That is, the capture of an active session does not work.

**Comment by hsluoyz** [comment]
@rimm74rus I mean provide screenshots and videos
