### ISSUE TITLE
Casdoor ignore keycloak()

### ISSUE THREAD

**Issue by DemidRol713** [casdoor/casdoor#3031]
I want to add provider Keycloak and authorize through it, but in the current version of CasDoor(1.634.0) does not give the opportunity to do so. Having looked through the network, I saw that there is no keycloak in the list. I did everything according to the instructions in the documentation.
KeyCloak 25.0.1
Then I tried casdoor:v1.540.0 and it worked, but after logging in, it redirected to localhost:8000/api/asc, where it gave 403 Forbidden error.
Can you please tell me what I have configured wrong?
CasDoor provider KeyCloak:
![image](https://github.com/casdoor/casdoor/assets/55896086/8c8b9a4a-0099-47bf-9802-598de9e2119c)
Casdoor application app-built-in:
![image](https://github.com/casdoor/casdoor/assets/55896086/3cbfca1e-483e-4aec-b1a3-57b61fc0ee3a)
Keycloak realm:
![image](https://github.com/casdoor/casdoor/assets/55896086/a1bc6d35-894c-4e9e-aab9-e037f3ffdc27)
Keycloak client:
![image](https://github.com/casdoor/casdoor/assets/55896086/61f24091-f325-4b87-8d5c-2f6be8b9ac9e)
![image](https://github.com/casdoor/casdoor/assets/55896086/ecb4c533-44df-4a1a-ad72-7bc6bb5fe86e)
![image](https://github.com/casdoor/casdoor/assets/55896086/4ca97324-571f-4904-a56d-6a026d4a5507)
![image](https://github.com/casdoor/casdoor/assets/55896086/fdf9969a-35ac-4519-bf6b-ab358399207a)
![image](https://github.com/casdoor/casdoor/assets/55896086/4ca0b26f-c727-4452-82ab-d7ce62f04db8)

Casdoor 1.634.0 login:
![image](https://github.com/casdoor/casdoor/assets/55896086/18bb891e-8ee0-4175-b117-9e014eabf23e)
![image](https://github.com/casdoor/casdoor/assets/55896086/3baf7101-5681-4086-9b9f-02a26b7aabf0)

Casdoor 1.540.0 login:
![image](https://github.com/casdoor/casdoor/assets/55896086/7d138286-dbb5-4d71-ba87-61ff8ede89b8)
![image](https://github.com/casdoor/casdoor/assets/55896086/05d1cb48-3105-431b-b87c-e4b96c0d9a6d)

  After logging in with the keycloak:
  ![image](https://github.com/casdoor/casdoor/assets/55896086/82e09005-9c7f-4766-aabc-c7f301811c0b)
  
KeyCloak metadata:
<md:EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" entityID="http://localhost:8080/realms/casdoor">
<md:IDPSSODescriptor WantAuthnRequestsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
<md:KeyDescriptor use="signing">
<ds:KeyInfo>
<ds:KeyName>GB1--WaS6r9JRlyHPagFUA71XAR17d0CkcGNQ-jSPZU</ds:KeyName>
<ds:X509Data>
<ds:X509Certificate>MIICnTCCAYUCBgGQbgtywjANBgkqhkiG9w0BAQsFADASMRAwDgYDVQQDDAdjYXNkb29yMB4XDTI0MDcwMTExMjQyMloXDTM0MDcwMTExMjYwMlowEjEQMA4GA1UEAwwHY2FzZG9vcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKnfjhCCP9nvpbMyJSFhWol2miwJkh8SSerFllw0UTqirNA2t7h77fBGVQB7gTqarx2tqmq2CfcUaWnO2RMvo1yOFG10UVTDDfOURLZwzzltvDgoEhBynOZ/qJo2BUClNgDeSkmcoc67rW1btsMo5NXLwryCfEEmQA2WGy8cnRvITYPYgDCSUQwDynymSY2rJAVXt8drkAiujBdgV+SJPWx9o75zvUVIQ27EE6HJRHi/4cwe310WvviRMAjehnzt+taRgTEmsqYsOzFQ9tK3cRFRebaSNaeBIpecqyC4ckEKBixwPVXMl61PVcrtz5ip5On1j1rghXeSsDfD9a6B8FECAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAmzdcd6nK3zDV7fY9fnhzAdfMPFrAhc2MiYn6xxxazqT8JPFWJUQkXJXKo5no0t7sLxUllwcE2o4G8QQX4ILBC1pT+AuXsk15DO5uwnXUTAj4an6BbRfZUpLN+Baeo1fkUgSzTreO+R1CI13jxYVgbkaCJbxtKx/9sobcXzFcMrQeNc7LhfcKIaTSuuHN1OO3d7liNU+N3cxEgzSautR717k7cikPt/j8jGTOKzCqRnjx5ZBgW3d6OzrXglnKSOncXuqCzOHE+jAhiawltvK0OYTmrMuNoYC93KvAdR6mGb7lroCAomsA8xwHLNHYvQYhOCbOOWipi/TF8X82Y0VzMA==</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</md:KeyDescriptor>
<md:ArtifactResolutionService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="http://localhost:8080/realms/casdoor/protocol/saml/resolve" index="0"/>
<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:8080/realms/casdoor/protocol/saml"/>
<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://localhost:8080/realms/casdoor/protocol/saml"/>
<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="http://localhost:8080/realms/casdoor/protocol/saml"/>
<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="http://localhost:8080/realms/casdoor/protocol/saml"/>
<md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</md:NameIDFormat>
<md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</md:NameIDFormat>
<md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</md:NameIDFormat>
<md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
<md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:8080/realms/casdoor/protocol/saml"/>
<md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://localhost:8080/realms/casdoor/protocol/saml"/>
<md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="http://localhost:8080/realms/casdoor/protocol/saml"/>
<md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="http://localhost:8080/realms/casdoor/protocol/saml"/>
</md:IDPSSODescriptor>
</md:EntityDescriptor>

**Comment by hsluoyz** [comment]
@DemidRol713 all English. This is either not planned.
