### ISSUE TITLE
Does the internal LDAP Server redirect to other LDAP sources?

### ISSUE THREAD

**Issue by dsp-active** [casdoor/casdoor#3032]
Hello there,

I got a quick question that isn't quite explained in the web docs. I got a test scenario that has a 2nd authorization application acting as a forward-auth proxy connected to a running Casdoor installation through its internal LDAP server. Casdoor has a configured organization that is hooked up to another external LDAP source (= on-prem AD) to get its users. The users are all properly synced and the communication between the two apps works.

While a direct login through Casdoor works without any issues, the login on the 2nd authorization platform only works with manually added users and not the synced AD users. Judging by the logs, the users are being detected, but the password is apparently always wrong. Since the password is visible in plain text, I can tell that it should be valid. I don't have any password hashes set and I do know that Casdoor doesn't save any passwords for the users that are synced through LDAP in its own database.

Does the internal LDAP server not redirect the password validation to the organizations connected LDAP source in this case? Or is it just a configuration issue on my part? I just wanna make sure before spending even more time troubleshooting this scenario.

**Comment by hsluoyz** [comment]
@dsp-active you should debug Casdoor code to check. It should be sending password to LDAP server for checks

**Comment by dsp-active** [comment]
> @dsp-active you should debug Casdoor code to check. It should be sending password to LDAP server for checks

Thanks for clarifying! It does seem to be a problem with my configuration of Casdoor itself, because I checked the LDAP server using ldapsearch inside of the container and it shows the same exact behaviour - manually added users work, synced users don't.

Since direct logins through Casdoor and OIDC work, it can't be a problem with how the AD is hooked up to it. The issue only happens using the LDAP protocol on the internal LDAP server and there aren't a whole lot of configuration options for that. I'm just scratching my head at this point.~

> ldap_bind: Invalid credentials (49) - password or code is incorrect

Are there recommended ways of debugging Casdoor in more detail than what's revealed in the logs? I'm not too versed in actually analyzing sent and received packages but I could also check the server hosting the AD for the request package that Casdoor sends to it.

**Comment by dsp-active** [comment]
@hsluoyz Hey there, I think I found the issue and it might actually be in need of a fix. Look at this:


This is how the LDAP server calls the object function to check the bind:
**_/ldap/server.go_**
`bindUser, err := object.CheckUserPassword(bindOrg, bindUsername, bindPassword, "en")`

This is how the internal auth controller calls the same function:
**_/controllers/auth.go_**
`user, err = object.CheckUserPassword(authForm.Organization, authForm.Username, password, c.GetAcceptLanguage(), enableCaptcha, isSigninViaLdap, isPasswordWithLdapEnabled)`


As it stands right now, the "LDAP server > other LDAP sources" auth chain will always run into the following issue:
**_/object/check.go_**
`if !isSigninViaLdap && !isPasswordWithLdapEnabled {
    return nil, fmt.Errorf(i18n.Translate(lang, "check:password or code is incorrect"))
}`
because it never actually changes these 2 bool parameters during function calling and they're False by default. The auth controller has a few lines of code to check these vars beforehand.

**Comment by dsp-active** [comment]
Opened up a PR - [Link](https://github.com/casdoor/casdoor/pull/3059)

I got it to work on my end, so I'll close this issue for now.
