### ISSUE TITLE
Do not give hints of registered emails/accounts

### ISSUE THREAD

**Issue by owziga** [casdoor/casdoor#3035]
Hello,

When you try to log in using a non registered account you get an error like: `Failed to sign in: The user: XXXX doesn't exist`, but if you provide a wrong password for a registered user you get an error like: `Failed to sign in: password or code is incorrect, you have 3 remaining chances`.

In my opinion it should return an invalid login message for both cases to avoid bots or third parties to get which account are registered.

Best regards.

**Comment by hsluoyz** [comment]
@owziga why we give clearer messages than commercial systems is that people always feels confusing about the obselete messages and think the system has bugs, they will send issues to complain about it and think they find a bug, but actually not.

So we will not change it here. You can modify the code by yourself to give the same message text.

**Comment by owziga** [comment]
> @owziga why we give clearer messages than commercial systems is that people always feels confusing about the obselete messages and think the system has bugs, they will send issues to complain about it and think they find a bug, but actually not.
> 
> So we will not change it here. You can modify the code by yourself to give the same message text.

That is the first thing that come to mind and I totally understand it, is that normally for security reasons the recommended approach is the one I mentioned, but as you said, anyone can modify the code to behave it like that.
/
