### ISSUE TITLE
Allow All Users to Perform LDAP Search Lookups in their org

### ISSUE THREAD

**Issue by m-yosefpor** [casdoor/casdoor#3042]
**Description:**

**Problem Statement:**

Currently, Casdoor's LDAP server supports search lookups but restricts this capability to orgAdmins. This design decision poses significant challenges and security risks for organizations using Casdoor. It is common practice for LDAP implementations to allow all users to perform search operations to find and list user information. Restricting this functionality exclusively to orgAdmins results in several issues:

1. **Security Risks:** Requiring orgAdmin credentials for search lookups exposes critical administrative credentials to other teams. For instance, if a team managing Nexus needs to connect to Casdoor, they should not be granted orgAdmin credentials. These credentials allow not only user searches but also modifications to all users and organizational configurations, which is a substantial security vulnerability.

2. **Operational Challenges:** Many organizations need to provide the ability to search the directory to all users for efficiency and operational requirements. Without this capability, users cannot look up contact information or organizational structure details, impeding workflow and communication.

**Proposed Solution:**

Enable a feature in Casdoor's LDAP server that allows regular users to perform search lookups. This feature should:

- Permit search operations without requiring orgAdmin credentials.
- Ensure that users can list and view other users' information without having the ability to modify user data or organizational settings.
- Maintain strict access controls to prevent unauthorized data exposure while enhancing operational efficiency.

We believe this feature will significantly improve the usability and security of Casdoor's LDAP implementation and align it with standard LDAP practices.

**Comment by hsluoyz** [comment]
@m-yosefpor can you make a PR?

**Comment by m-yosefpor** [comment]
> @m-yosefpor can you make a PR?

Sure
