### ISSUE TITLE
How to control access to the console for regular users

### ISSUE THREAD

**Issue by baishu12** [casdoor/casdoor#3044]
I use casdoor as a public unified login service, and I've found that even if a user isn't an organization administrator, they can modify other users' information. This permission is not appropriate. I tried to use casbin to control the permissions of normal users. But it didn't work. Please tell me how to manage the permissions of normal users in the control panel. To prevent someone from messing up. Thanks!

**Comment by hsluoyz** [comment]
See docs: https://casdoor.org/docs/basic/core-concepts#how-does-casdoor-manage-itself
