### ISSUE TITLE
logout not work when concurrent request

### ISSUE THREAD

**Issue by lucklyt** [casdoor/casdoor#3060]
I was building an SSO system with Casdoor, I found that user logins often did not take effect. After investigating the source code and testing, I discovered that Casdoor uses Beego's session to cache the user's login status. When the user logs out, the user data in the session is deleted, but if there are multiple concurrent requests at this time, the request that finishes later will rewrite the deleted data during SessionRelease, causing the user's login status to be restored.

**Comment by lucklyt** [comment]
In the scenario of the /cas/:organization/:application/logout interface, this issue is most likely to occur because multiple HTTP requests are initiated at that time.

**Comment by hsluoyz** [comment]
@lucklyt "the request that finishes later will rewrite the deleted data during SessionRelease" can you prove this? Can you provide reproduce steps?

**Comment by lucklyt** [comment]
> @lucklyt "the request that finishes later will rewrite the deleted data during SessionRelease" can you prove this? Can you provide reproduce steps?

You can directly use the newly installed Casdoor and follow the steps below to simulate concurrent requests and reproduce this phenomenon:

	1.	Find an API endpoint and add a sleep 10s inside it. For example, using /get-sessions as the endpoint, modify it and then run make run again.
	2.	Open the demo at http://localhost:8000/ and log in using the admin account.
	3.	First, initiate a request in the browser to http://localhost:8000/api/get-sessions?owner=&p=1&pageSize=10&field=&value=&sortField=&sortOrder=. Then immediately initiate a request to http://localhost:8000/cas/built-in/app-built-in/logout. At this point, you have logged out of Casdoor. Try accessing http://localhost:8000/ again, and you will find that you need to log in again. However, after the first get-sessions request completes, refresh http://localhost:8000/, and you will find that the login status has been restored.
	4.	You can retry the above steps, and you will almost always be able to reproduce this issue.


![image](https://github.com/user-attachments/assets/3973f73a-cb04-4358-a906-0b650a2d1bdf)

**Comment by lucklyt** [comment]
this is record what i done 
https://github.com/user-attachments/assets/489c0858-af15-43a6-b8ae-9c0f4058ef28

**Comment by lucklyt** [comment]
I believe this is an issue with Beego. I have used this framework before and its design is terrible. Over the past few days, I tried to solve this problem by modifying Beego's Redis session provider and regist with new name in my project. I recorded a negative cache in SessionDestroy, checked for the existence of the negative cache in SessionExisted, and then actively marked the session ID as invalid in the Casdoor's logout interface by calling SessionDestroy.

This solution is too complicated. Do you have any better fixes?

**Comment by hsluoyz** [comment]
@lucklyt can you make a PR?

**Comment by lucklyt** [comment]
> @lucklyt can you make a PR?


Beego has many different session providers, and it's unreasonable to modify all of them. I've already raised an issue on the Beego repository, and I hope they can fix this problem soon.

**Comment by hsluoyz** [comment]
This is more of a Beego issue. So closed here.

**Comment by XdpCs** [comment]
In beego v2.3.0, we support SessionReleaseIfPresent to avoid this situation.

**Comment by hsluoyz** [comment]
@XdpCs we use Beego v1.12.12, can you also back-port it to Beego v1 branch?

**Comment by XdpCs** [comment]
> @XdpCs we use Beego v1.12.12, can you also back-port it to Beego v1 branch?

I will update this later.

**Comment by XdpCs** [comment]
Can you help to confirm this change if actually solve your problem? I support this feature in the develop-1.x branch.

**Comment by hsluoyz** [comment]
@XdpCs do you have a version tag?

**Comment by XdpCs** [comment]
@hsluoyz  https://github.com/beego/beego/releases/tag/v1.12.13

**Comment by lucklyt** [comment]
> Can you help to confirm this change if actually solve your problem? I support this feature in the develop-1.x branch.

how to use SessionReleaseIfPresent? i dont see any code use SessionReleaseIfPresent in beego

**Comment by XdpCs** [comment]
> > Can you help to confirm this change if actually solve your problem? I support this feature in the develop-1.x branch.
> 
> how to use SessionReleaseIfPresent? i dont see any code use SessionReleaseIfPresent in beego

https://github.com/beego/beego-doc/blob/main/docs/en-US/v2.3.x/web/session/README.md
This is a new doc.

**Comment by hsluoyz** [comment]
@lucklyt can you make a PR in Casdoor to use this new API?

**Comment by lucklyt** [comment]
> > > Can you help to confirm this change if actually solve your problem? I support this feature in the develop-1.x branch.
> > 
> > 
> > how to use SessionReleaseIfPresent? i dont see any code use SessionReleaseIfPresent in beego
> 
> https://github.com/beego/beego-doc/blob/main/docs/en-US/v2.3.x/web/session/README.md This is a new doc.
beego router also use SessionRelease when request done

![image](https://github.com/user-attachments/assets/b4ee92ad-feeb-4f92-8077-f3e5227fb46a)

**Comment by XdpCs** [comment]
> @lucklyt can you make a PR in Casdoor to use this new API?

I will fix it and make a PR.

**Comment by lucklyt** [comment]
> > @lucklyt can you make a PR in Casdoor to use this new API?
> 
> I will fix it and make a PR.

ok

**Comment by XdpCs** [comment]
@hsluoyz #3103
