### ISSUE TITLE
sms login

### ISSUE THREAD

**Issue by yangyulele** [casdoor/casdoor#3071]
Does Casdoor support custom applications using SMS verification for login (without CAPTCHA)? Why can't I find the corresponding interface or demo?

**Comment by yangyulele** [comment]
Hello  我会尽快回复的。

**Comment by hsluoyz** [comment]
@yangyulele it's code login: https://door.casdoor.com/login . It can be verification code from Email or phone

![image](https://github.com/user-attachments/assets/6b9881cb-db6c-4fd3-b600-323742ff14b7)
