### ISSUE TITLE
[Bug] Incorrect `Username` fetch in IdP Lark

### ISSUE THREAD

**Issue by Oniokey** [casdoor/casdoor#3074]
In Lark feild `name` is the user's Chinese name, not the user's unique identifier, using this field will result in duplicate UserIDs, the `user_id` field should be used as the user's unique identifier in Casdoor. [see here (code)](https://github.com/casdoor/casdoor/blob/38b9ad1d9feaa5e424b8b6cdc4055e9e47d5d3b6/idp/lark.go#L214)

expect:
```go
userInfo := UserInfo{
		Id:          larkUserInfo.Data.OpenId,
		DisplayName: larkUserInfo.Data.Name, //here we use the Chinese name to be the display name instead
		Username:    larkUserInfo.Data.UserId,  // here we shoule use UserId
		Email:       larkUserInfo.Data.Email,
		AvatarUrl:   larkUserInfo.Data.AvatarUrl,
		Phone:       phoneNumber,
		CountryCode: countryCode,
	}
```
`UserId` is a reference of [user_id](https://github.com/casdoor/casdoor/blob/38b9ad1d9feaa5e424b8b6cdc4055e9e47d5d3b6/idp/lark.go#L157C3-L157C9) in LarkUserInfo

**Comment by hsluoyz** [comment]
@Oniokey can you make a PR?

**Comment by Oniokey** [comment]
of course

**Comment by Oniokey** [comment]
> @Oniokey can you make a PR?

of course

**Comment by ultranity** [comment]
It's better to use Union ID or open ID in case the Lark app don't have user_id access

**Comment by Oniokey** [comment]
In fact, allowing the user to customize which field to use is the best option

**Comment by hsluoyz** [comment]
Not that customizable, you modify the code, it's much faster
