### ISSUE TITLE
[feature] SAML NameID Mapping

### ISSUE THREAD

**Issue by Oniokey** [casdoor/casdoor#3077]
I'm trying to log in to Aliyun using Casdoor, but Aliyun requires that the **NameID field in the SAML response** matches the Aliyun RAM account (**an email account**), but the value of the NameID that Casdoor passes is the **Casdoor username** not the **email address**, and I can't find a place where I can configure this option. 

Is it possible to add a feature for configuring application-specific NameID fetching or mapping?

**Comment by hsluoyz** [comment]
@Oniokey can you make a PR?

**Comment by Oniokey** [comment]
> @Oniokey can you make a PR?

I'm not sure at what point Casdoor processes the SAML response, can you give me the exact location?

**Comment by dacongda** [comment]
SAML response generate function in
https://github.com/casdoor/casdoor/blob/3718d2dc04b775fecf70db6e8c858d5832f094d4/object/saml_idp.go#L40
and
https://github.com/casdoor/casdoor/blob/3718d2dc04b775fecf70db6e8c858d5832f094d4/object/saml_idp.go#L269

**Comment by dacongda** [comment]
> > @Oniokey can you make a PR?
> 
> I'm not sure at what point Casdoor processes the SAML response, can you give me the exact location?
> 
> for example，at which `.go` file

SAML response generate function in
https://github.com/casdoor/casdoor/blob/3718d2dc04b775fecf70db6e8c858d5832f094d4/object/saml_idp.go#L40
and
https://github.com/casdoor/casdoor/blob/3718d2dc04b775fecf70db6e8c858d5832f094d4/object/saml_idp.go#L269

**Comment by Oniokey** [comment]
> > > @Oniokey can you make a PR?
> > 
> > 
> > I'm not sure at what point Casdoor processes the SAML response, can you give me the exact location?
> > for example，at which `.go` file
> 
> SAML response generate function in
> 
> https://github.com/casdoor/casdoor/blob/3718d2dc04b775fecf70db6e8c858d5832f094d4/object/saml_idp.go#L40
> 
> 
> and
> https://github.com/casdoor/casdoor/blob/3718d2dc04b775fecf70db6e8c858d5832f094d4/object/saml_idp.go#L389

ok，I get it.

**Comment by Oniokey** [comment]
@hsluoyz This feature is potentially a breaking change because it requires permanently storing a configuration for determining the style of NameID, meaning that it requires adding a field to the `application` table (similar to `SamlNameIdMode`), which involves updating of the stock user.

Any good advice on this, or is this level of breaking change acceptable?

**Comment by dacongda** [comment]
add a switch to determine whether use NameID is a good idea we can set it to be false by default,  why it will be a breaking change, will it change something when we turn it off? and it seem that this is the proprietary field of aliyun, maybe we can check the prefix of destination  to determine whether use NameID.

**Comment by Oniokey** [comment]
I need to change the table structure to add a configuration item（use default or the email as NameID）

**Comment by dacongda** [comment]
> I need to change the table structure to add a configuration item（use default or the email as NameID）

imho，this is acceptable,  yoi can try to make a pr first

**Comment by Oniokey** [comment]
> > I need to change the table structure to add a configuration item（use default or the email as NameID）
> 
> imho，this is acceptable, yoi can try to make a pr first

ok

**Comment by hsluoyz** [comment]
@Oniokey don't add a new boolean field to application. There are already so many SAML bool fields in it. Better with a SAML field table structure as the property of application to contain all SAML related stuff

**Comment by Oniokey** [comment]
> @Oniokey don't add a new boolean field to application. There are already so many SAML bool fields in it. Better with a SAML field table structure as the property of application to contain all SAML related stuff

it's not a new field in SAML Response, it's a already exist field called NameID, what I need is to change the content of it
