### ISSUE TITLE
SAML providers don't work (neither custom nor pre-installed)

### ISSUE THREAD

**Issue by vdh40** [casdoor/casdoor#3078]
Hi,

I'm trying to add IDP that works via **SAML** to Casdoor' application (I follow this instruction: https://casdoor.org/docs/provider/saml/custom). As result after creating provider with type SAML and adding it to application **there is no button for this provider on login page** (on version **v1.651.0**). At the same time OAuth providers work fine: they are shown at login page and work correctly.

I've tried different Casdoor' versions. On version **v1.554.0** icon button for authenticating via SAML provider aren't shown on login page, but after logging in Okta redirect for http://localhost:8000/api/acs http error with status code 403 is raised:

<img width="1791" alt="Снимок экрана 2024-07-25 в 23 33 27" src="https://github.com/user-attachments/assets/c90ad0c7-9457-4dde-a001-ba29b1f5eb1b">
<img width="1795" alt="Снимок экрана 2024-07-25 в 23 33 32" src="https://github.com/user-attachments/assets/e786fcb4-546b-4314-9b3a-72e253bd5af2">

<img width="597" alt="Снимок экрана 2024-07-26 в 10 21 35" src="https://github.com/user-attachments/assets/c3e65bc8-9ebd-49b3-aacc-5d4f6dc37470">

<img width="732" alt="Снимок экрана 2024-07-26 в 09 30 29" src="https://github.com/user-attachments/assets/58169629-ff12-47f3-9329-eaa5d6457c1c">

Versions from **v1.553.0** to **v1.620.0** are not available for my platform (linux/arm64/v8).
On versions from **v1.621.0** to **v1.651.0** SAML providers' icon button is not displayed on login page.

I'm not sure, but it seems like a bug. Please, help.

**Comment by hsluoyz** [comment]
@vdh40 provide the source code level clue to show this is a bug, not your usage issue

**Comment by hsluoyz** [comment]
Closed as stale

**Comment by Nexyll** [comment]
I'm facing the same issue with the version v1.686.0

None of the SAML providers are visible on the login page (regardless of their type).

All OAuth providers are displayed correctly. We have no errors either in the logs or in the web client console.

However, SAML providers are present in the providers list in the `get-application` route json response, but not in `get-app-login`.

**Comment by hsluoyz** [comment]
@Nexyll create a new issue

**Comment by Nexyll** [comment]
Why can't we just reopen this one to keep our conversations going?

**Comment by dacongda** [comment]
> Why can't we just reopen this one to keep our conversations going?

it seems that this is a CORS question, I try to fix it in #3200 , can you help me to test?

**Comment by Nexyll** [comment]
Hey, we have opened a new issue as requested by @hsluoyz, it was the #3163.

We had investigated the problem a little and I'm pretty sure there was no CORS problem on the API call. Just a wrong return list. The patch proposed for the #3163 correctly fixed the bug.

**Comment by dacongda** [comment]
> Hey, we have opened a new issue as requested by @hsluoyz, it was the #3163.
> 
> We had investigated the problem a little and I'm pretty sure there was no CORS problem on the API call. Just a wrong return list. The patch proposed for the #3163 correctly fixed the bug.

thanks for reply, but there is a problem when we request `/api/acs` using http(not https) protocol
