### ISSUE TITLE
Fail to initialize the MFA of  the user synced from an LDAP

### ISSUE THREAD

**Issue by SidneySun** [casdoor/casdoor#3081]
![image](https://github.com/user-attachments/assets/90261583-2c47-4634-8b8b-72e44ed7d4c0)
In v1.651.0, when I set the MFA, it always tells me my password synced from my LDAP is wrong.

**Comment by hsluoyz** [comment]
@SidneySun it only checks the Casdoor user password, not the LDAP password

**Comment by SidneySun** [comment]
For an LDAP user, it also is wrong to use the Casdoor password. I'm sorry that I can't make the PR recently.

**Comment by hsluoyz** [comment]
Closed for cannot reproduce
