### ISSUE TITLE
Email not available for github login

### ISSUE THREAD

**Issue by anandhu-vasu** [casdoor/casdoor#3089]
When I sign in with github it shows allow access to email. 
But after sign in, in the casdoor users page the email of the user is not available.

**Comment by hsluoyz** [comment]
@anandhu-vasu see org's Account Items: https://casdoor.org/docs/organization/accountCustomization

**Comment by anandhu-vasu** [comment]
This issue happens only for github. When a user is signed up using google sign in, the email is available.

**Comment by luyang93** [comment]
Also tried in demo https://door.casdoor.com
when a user signs up with github, the email is missing

**Comment by hsluoyz** [comment]
@anandhu-vasu @luyang93 you should allow exposing your Email to OAuth in your github settings page

**Comment by luyang93** [comment]
Thanks.
When I set public email in public profile, casdoor does get email value.
By the way, I read the [grafana code](https://github.com/grafana/grafana/blob/f35b9a937f9b12f543e4b3565af55a6808f6de8a/pkg/login/social/connectors/github_oauth.go#L186), it fetched private email from /user/emails [url](https://docs.github.com/en/rest/users/emails?apiVersion=2022-11-28#list-email-addresses-for-the-authenticated-user--code-samples).
Does casdoor need to add fetch private email in github idp?

**Comment by hsluoyz** [comment]
@dacongda

**Comment by hsluoyz** [comment]
@luyang93 fixed in: https://github.com/casdoor/casdoor/pull/3428
