### ISSUE TITLE
[bug] Karma can be edited by non-admin

### ISSUE THREAD

**Issue by tomberek** [casdoor/casdoor#3091]
Karma can be updated by non-admin when Modify Rule is set to "Admin". Same settings on score correctly block edits by user.

**Comment by hsluoyz** [comment]
@tomberek this is impossible. All fields are checked in the same code. Can you point out the code that causes this so-called bug you mentioned?

**Comment by tomberek** [comment]
I didn't find how it differed from Score, but I'll try out the patch, thanks! I was just playing around and exploring the tool to see what it could do and ran into this randomly.
