### ISSUE TITLE
invitation code setting is missing in the 1.659.0

### ISSUE THREAD

**Issue by link89** [casdoor/casdoor#3097]
Hi, I find that the invitation code setting cannot be found after grade to 1.659.0

I have follow the https://casdoor.org/docs/application/invitation-code/ to add invitation code in the signup but seems still not work.

**Comment by hsluoyz** [comment]
@link89 reproduce it in demo site: https://door.casdoor.com/, then provide the demo video

**Comment by link89** [comment]
https://www.loom.com/share/bdf081a519054b7baf7eb25e82df5a92

as you can see, the invitation code is supposed to be in the application config page, but it doesn't exist actually, even after adding the invitation code in the sign up

**Comment by hsluoyz** [comment]
@link89 your setting is incomplete. You should follow this full guide docs: https://casdoor.org/docs/invitation/overview

You need to create invitation objects
