### ISSUE TITLE
What is casdoor's api?

### ISSUE THREAD

**Issue by lsx1205** [casdoor/casdoor#3098]
When openvpn is used to connect to casdoor for identity authentication and oauth2 protocol is used, there is a problem, what is the api interface of casdoor's user information? How to make the call so that the user information obtained from casdoor is passed to openvpn.

**Comment by hsluoyz** [comment]
@lsx1205 see docs: https://casdoor.org/docs/how-to-connect/oauth/#how-to-use-accesstoken
