### ISSUE TITLE
refresh token issue for casdoor

### ISSUE THREAD

**Issue by lsx1205** [casdoor/casdoor#3102]
Does casdoor have refresh token? In other words, does Casdoor store refresh token? At present, I am using openvpn-auth-oauth2 plug-in to connect with casdoor as the authentication mode, but when oauth2 re-authenticates, the refresh token acquisition fails. I suspect that casdoor has not passed refresh token into the server memory at all. Authentication fails.

**Comment by hsluoyz** [comment]
Yes. See docs
