### ISSUE TITLE
Issues related to refresh token

### ISSUE THREAD

**Issue by Allinone-1205** [casdoor/casdoor#3106]
Hello, now I am using a tool to integrate casdoor for authentication, which requires the use of refresh token, but I can't find any information related to refresh token in our official documents. Could you please provide me with some links or information? Thank you

**Comment by hsluoyz** [comment]
@Allinone-1205 this issue list is mainly for bugs or complicated questions, not for your one-line question. You are now trying to register a new github account to spam us. Your account will be forbidden again.
