### ISSUE TITLE
How to Embed Casdoor Login Page in My System's Login Page?

### ISSUE THREAD

**Issue by mingchungchan** [casdoor/casdoor#3109]
**Describe the issue**
I am integrating Casdoor as the third-party authentication platform in my application. I want to embed the Casdoor login page within my own system's login page. I tried using an iframe to achieve this, but after a successful login, the redirection happens within the iframe instead of the whole parent page.

**Steps to reproduce**
Create a Casdoor application and configure the redirect URI to point to a callback handler on my backend.
Embed the Casdoor login page in an iframe on my front-end.
After successful login, Casdoor redirects to the callback URI within the iframe.

**Expected behavior**
After successful login, I want the entire parent page to be redirected to a new URL, not just the iframe content.

**Actual behavior**
The iframe content gets redirected to the callback URI, while the parent page remains unchanged.

**Question**
How can I correctly embed the Casdoor login page into my system's login page and handle the redirection so that the parent page URL changes after a successful Casdoor login, instead of just the iframe content? or is there a better approach to achieve this?

**Comment by hsluoyz** [comment]
No way to do this
