### ISSUE TITLE
When the avatar is too big it does not allow auth in casdoor

### ISSUE THREAD

**Issue by destanqueitopia** [casdoor/casdoor#3114]
When the avatar is too big it does not allow auth in casdoor
![image](https://github.com/user-attachments/assets/5f87e2a5-d119-4c23-91bd-2d5071af10a8)
A possible solution is to increase the size of the avatar field in db, the avatar field is in db as varchar(500)
Regards

**Comment by hsluoyz** [comment]
@destanqueitopia 500 is enough for most cases. Not planned to change

**Comment by reisbel** [comment]
@hsluoyz Is there any guidance on how to handle these cases, besides maintaining our own fork? We've noticed a small but still significant number of users with avatars that exceed the permitted size.

**Comment by hsluoyz** [comment]
@destanqueitopia @reisbel what's the max length you need

**Comment by reisbel** [comment]
@hsluoyz Based on the data we've reviewed, a maximum length of 1500 should be sufficient to handle all cases.

**Comment by hsluoyz** [comment]
@reisbel too much, It's not interesting for me to change it to 1500 to just fit your personal need

**Comment by reisbel** [comment]
@hsluoyz Alright, we already have a private fork, I'll continue maintaining it. I just wanted to give you a heads-up about a recurring issue with Google accounts. Although it affects only a small percentage, when it fails, it provides little to no information, leaving end-users in the dark about what's happening. By the way, we're using casdoor as part of an enterprise solution that will be launched to the market in a few months.
