### ISSUE TITLE
 [feature] Support Custom Claims for OIDC

### ISSUE THREAD

**Issue by Shadow-Labs-Dev** [casdoor/casdoor#3124]
Please add support to add custom claims and scopes for oidc tokens.

**Comment by tanangular** [comment]
Is it possible to add role of user to the JWT-Custom ?

<img width="1090" alt="Screenshot 2567-08-19 at 20 37 59" src="https://github.com/user-attachments/assets/edcabe97-78f7-4f27-8045-051711470c50">

**Comment by hsluoyz** [comment]
@tanangular @Shadow-Labs-Dev can you make a PR?

**Comment by tanangular** [comment]
I found the solution, I can add roles data to custom JWT by typing roles freely even if it is not in the list initially.
<img width="1442" alt="Screenshot 2567-09-12 at 10 42 18" src="https://github.com/user-attachments/assets/06eb9232-c213-4b21-a4e8-d6de02aed482">

<img width="614" alt="Screenshot 2567-09-12 at 10 44 17" src="https://github.com/user-attachments/assets/5d9727e6-1b3b-4688-96fb-6fbbad52331d">

Thanks you, casdoor is awesome.

**Comment by pixeldrew** [comment]
Azure B2C can use an Application API to populate the claims of the token, this allows for additional fields and external claims being populated into the token.  Azure will send the name/oid/email and the service is supposed to generate the claims and then Azure B2C signs them.

Is this possible?

**Comment by hsluoyz** [comment]
Closed as resolved

**Comment by pixeldrew** [comment]
@hsluoyz This isn't closed. Custom claims that can be propagated from a third party API is extremely useful. Can we discuss?
