### ISSUE TITLE
[bug] get-groups API should NOT query all users under the group

### ISSUE THREAD

**Issue by RunningIkkyu** [casdoor/casdoor#3145]
## Issue Description

The `get-groups` API currently retrieves all user IDs from the user table, which can significantly degrade performance when the table contains millions of records. This query could potentially take several minutes to complete, leading to delays and inefficiencies.

## Problem

With a large user base, querying all user IDs at once results in extensive processing time, which impacts the performance of the get-groups API. This is particularly problematic when the user table contains millions of entries, causing substantial delays and reducing overall system efficiency.

## Screenshots

<img width="795" alt="WeChatWorkScreenshot_c712a424-effe-43da-abc4-42d66f10f368" src="https://github.com/user-attachments/assets/38e14c08-c9f4-4fd6-a795-59f53e1c726a">

## Suggested Solutions

-  **Consider eliminating the `ExtendGroupsWithUsers` logic**. Users should not be quried in `get-groups` API actually.

-  **Limit the number of user IDs retrieved during each query.**  Maybe only first 10 users if the users data is really nessesary.

**Comment by hsluoyz** [comment]
@RunningIkkyu your PR to only fetch first 10 users is not a good solution
