### ISSUE TITLE
SAML BINGING HTTP POST login error, response "unexpected EOF"

### ISSUE THREAD

**Issue by tiny-v** [casdoor/casdoor#3148]
I found this issue has been resolved in v1.520.0 (https://github.com/casdoor/casdoor/issues/2643)

But now, i use the v1.651.0 , still get the same issue. 

I use the Azure as the SP,  when redirect to the casdoor login page,  it return the "unexpected EOF" while logining;

The Http Reqeust info is:

curl "http://172.20.154.25:8000/api/login" ^
  -H "Accept: */*" ^
  -H "Accept-Language: zh;q=0.9,en;q=0.8" ^
  -H "Cache-Control: no-cache" ^
  -H "Connection: keep-alive" ^
  -H "Content-Type: text/plain;charset=UTF-8" ^
  -H "Cookie: casdoor_session_id=ccd104878fcbd681749fc10a1ca0f6f9" ^
  -H "Origin: http://172.20.154.25:8000/" ^
  -H "Pragma: no-cache" ^
  -H "Referer: http://172.20.154.25:8000/login/saml/authorize/admin/application_azure_idp?relayState=estsredirect=2&estsrequest=rQQIARAAjZO7jxtVFIfteN9SyCqKopRbgASBse-8PDMrrRTbY3v9mLE9fsyDwpr3jDNz7-zMnfXjL6CMREdHyhUFoYIgJBAI0NKkhg6JJgVCKVBK1pHo0xzpSOd3mu_7He1zZbYMyuBhiSqD03dthrEYwNMEbVmAYASbJCyGcwiBY1yWti3Ho-3uHgtIhgbp3aNj6Y_Vgx_2f370_LeHr-4est9eFd8LME6y00olQSk2o7K5yVO3bMNKFvowhJUQOu6q8nWx-KJYvLqVVWm-ChiKpVmWZapVkuPL-iSI5cUUyJSO9UWHkhoAGG0J9NUmrccdLLebtLGoPzZiORy0JVKaSJQ8iRYDcYqlhRIaYwBksRv2J1FgTDrYEGexrDbXRqwDQxytfr91Z1DLcUBtB0rDjfvq1qGH0nieoAx_VvquNEhc2HEaCELXxuXtmQtxaJs4RHCYosRNcehmZ41hJPcjz1XEGQ_ofiD24aJqalINhblaXRpAbWhwhUR2E9N4tmjYKjDrgGptYKvdmHpJwutrU9aXHuyzrW51tSb1GlX3lyo_zJtpx6JNELTPNcJVuMgkKFGrya4ginGn5Ss4GwK50YmEGPqY2oz785YAeyMw4-ktuJUqEuZMUhhVT4aarc17PkmmowCBcIzn0oxuys4ckcuVbovcsK-ss1XgCdb5IOf1muPXmtxsPmECh7dBO1guTSI8x5rUBRslGvdouYc9YDZQoz9WZF9Y4rUSTtSLS1W9cBu0XG85MJeJOqk2N7OUEPkZx6vsrCsSsCqtuOY6pdaLKRRa0YQcu0LWTepRAimjW5thEWgrj1fIDhyZ9KQ90DAc6bLpoUtjko8CMfIEOc-skae5yIrzwQWhdG11Sva72tB3_VayvCp98L-CsQlN341v4JVttLUwCKFpRyh3zCTcOvlV6TZKfROGmzdss-vS6K2zlTxz03kY39iQIfgmf3KjBgydEzc2w-gkSZEXRu6fpXu2mTkIpY_sPLMJhM2bj_GLneLLnfsH-8e7DwonhffvgdLpwcHRcWG7vd4pPt29adcXnx_9-mPwsfjpwVPJvG8Vrncr7GOpl9LjGqYXBifGISPQPUmhZY1sMgNFwPkFn15O7G4yRWfVU_LJXvHJ3t713mFHnMvNCcNR_-wVP9kvPD98u55-f7vw-p2ffnn2zb9_Pfv7_OWdjwJSCkeJwXKaaXlIH_q-wwJm2dFHMJp2gpXzoWItp5w80KWzL48L_wE1&samlRequest=PHNhbWxwOkF1dGhuUmVxdWVzdCBJRD0iX2JkMzBmNTQ5LWQ5NjgtNDQ5Ni04MTZjLTk3Y2NhYTU1ZWE4ZCIgVmVyc2lvbj0iMi4wIiBJc3N1ZUluc3RhbnQ9IjIwMjQtMDgtMjhUMDc6MDI6NDkuMDk3WiIgeG1sbnM6c2FtbHA9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpwcm90b2NvbCI+PElzc3VlciB4bWxucz0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiI+dXJuOmZlZGVyYXRpb246cGFydG5lci5taWNyb3NvZnRvbmxpbmUuY248L0lzc3Vlcj48c2FtbHA6TmFtZUlEUG9saWN5IEZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOm5hbWVpZC1mb3JtYXQ6cGVyc2lzdGVudCIvPjwvc2FtbHA6QXV0aG5SZXF1ZXN0Pg==" ^
  -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36" ^
  --data-raw "^{^\^"application^\^":^\^"application_azure_idp^\^",^\^"organization^\^":^\^"organization_sso^\^",^\^"username^\^":^\^"casdoor_azure^\^",^\^"autoSignin^\^":true,^\^"password^\^":^\^"Stack^@80^\^",^\^"signinMethod^\^":^\^"Password^\^",^\^"type^\^":^\^"saml^\^"^}" ^
  --compressed ^
  --insecure

The Http Response is:

{
  "status": "error",
  "msg": "unexpected EOF",
  "sub": "",
  "name": "",
  "data": null,
  "data2": null
}

Thanks.

**Comment by hsluoyz** [comment]
@tiny-v find the first broken version number via binary search between v1.520.0 and v1.651.0

**Comment by dacongda** [comment]
can you should how to set azure as a saml sp? the doc of azure is too mess that I can't find effective information

**Comment by tiny-v** [comment]
> @tiny-v find the first broken version number via binary search between v1.520.0 and v1.651.0

sure,  let me try.

**Comment by hsluoyz** [comment]
Closed as stale
