### ISSUE TITLE
rudius wlan

### ISSUE THREAD

**Issue by liuhan252** [casdoor/casdoor#3151]
Hello, when the user synchronized through ldap uses radius for authentication, it prompts access-reject, and the system built-in user admin prompts access-accept. In addition, I tried to use admin authentication on iPhone and it didn't work. What settings did I make wrong?
![image](https://github.com/user-attachments/assets/d59344e7-b63c-40e4-a5ca-0deb425ec053)
![image](https://github.com/user-attachments/assets/52f60f6b-bfcb-4a01-8c5b-14e09a3bde16)
![c814c559e016e12ac00143d3ef6e2c1](https://github.com/user-attachments/assets/38382a58-5a4c-477d-9cea-c9d4d2ad986a)

**Comment by hsluoyz** [comment]
@liuhan252 debug Casdoor by yourself
