### ISSUE TITLE
 Nonce Issue in OIDC: Quick Re-login Without Logout Causes Error

### ISSUE THREAD

**Issue by Blackcbears** [casdoor/casdoor#3152]
Description:

I'm encountering an issue with the parameter in the OIDC Login. The problem arises when a user logs in successfully the first time, but if they attempt to log in again without logging out, the process fails due to a -related error.noncenonce

for url [routers/static_filter.go:61](https://github.com/casdoor/casdoor/blob/master/routers/static_filter.go)
![image](https://github.com/user-attachments/assets/049adfb5-d901-4d97-b73e-57fccbe8ecbc)

**Comment by hsluoyz** [comment]
@Blackcbears can you make a PR to fix it?
