### ISSUE TITLE
emailVerified != email_verified it is not compliant with OIDC Standard

### ISSUE THREAD

**Issue by vint1024** [casdoor/casdoor#3155]
Hello!

When setting up integration via OIDC, I encountered the fact that the field transmitting data on email verification is not implemented according to the standard.
Because of this, third-party software (for example https://github.com/penpot/penpot), which requires email verification, does not allow entry.

According to the standard (https://openid.net/specs/openid-connect-core-1_0.html) the field should be email_verified, but Casdoor returns emailVerified

I think the right place in the code is - https://github.com/casdoor/casdoor/blob/1adb172d6bb9c8ff53f0c3938003e3d5d08917a2/object/token_jwt.go#L66
and
https://github.com/casdoor/casdoor/blob/45dd4cc344e0e418d6f15c5a2df793829d42009b/object/user.go#L69

Relates to the request https://github.com/casdoor/casdoor/issues/443
and the commit https://github.com/casdoor/casdoor/commit/c62588f9bcdbb327dae1b09f38d3916f322d7be0 on the request https://github.com/casdoor/casdoor/issues/2314

could you please make a correction?

**Comment by hsluoyz** [comment]
@vint1024 can you make a PR to fix it?

**Comment by vint1024** [comment]
@hsluoyz 
Sorry, I can't. I don't understand well how everything is arranged in the project.
I'm just good at searching for information :)

Besides, I'm not sure that I correctly found all the places where this needs to be corrected.

**Comment by dacongda** [comment]
the userinfo endpoint of casdoor return correct email_verified field. the userinfo struct is defined in
https://github.com/casdoor/casdoor/blob/ec987851723e09653cc566d5e2008438cdb18d45/object/user.go#L218
as i'm not familiar with clojure used by penpot can you help me to find did penpot get this field from accessToken requested in token end point?

**Comment by dacongda** [comment]
PS: you need to set Token format to JWT-STANDARD

**Comment by vint1024** [comment]
Thank you very much!
with the suggested settings everything worked :)
