### ISSUE TITLE
[feature]More user-friendly for applications deployed privately

### ISSUE THREAD

**Issue by chaos-cn** [casdoor/casdoor#3161]
1. Providers->Notification->Bark
Currently, only official Bark services are supported, and there is no support for deploying Bark services on one's own.
[barkSrv := bark.New(deviceKey)](https://github.com/casdoor/casdoor/blob/master/notification/bark.go)
[NewWithServers](https://github.com/casdoor/notify/blob/master/service/bark/bark.go)

2. Providers->OAuth->WeCom
WeCom also supports private deployment, and in the case of private deployment, its interface domain name will no longer be "https://qyapi.weixin.qq.com",but the path of the API is consistent
[wecom_third_party.go](https://github.com/casdoor/casdoor/blob/master/idp/wecom_third_party.go)
[wecom_internal.go](https://github.com/casdoor/casdoor/blob/master/idp/wecom_internal.go)

It is best to allow users to configure their own service domain names on the configuration page.

**Comment by hsluoyz** [comment]
@chaos-cn we have no env for using those services privately. So we cannot do it. Good-quality PR is welcome.

Closed for now
