### ISSUE TITLE
Invalid response code when failing basic auth

### ISSUE THREAD

**Issue by Timshel** [casdoor/casdoor#3162]
Hey

Was testing Casdoor as an OpenID Connect provider using the `JWT-Standard` token format and with version `v1.686.0` it appears to work, but I stumbled on an issue when using an invalid config.

If the `client_secret` is invalid and provided using Basic auth such as:

```bash
curl -v  \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -H "authorization: Basic dmF1bHR3YXJkZW46dmF1bHR3YXJkZW4y" \
  -d "code=b0667171e727f96a0a5d" \
  -d "grant_type=authorization_code" \ 
  -d "redirect_uri=http://vaultwarden/identity/connect/oidc-signin" \
  "http://casdoor/api/login/oauth/access_token"
```

Then the response is a `200` with:
```json
< HTTP/1.1 200 OK
...
{
  "status": "error",
  "msg": "Incorrect client secret for application: vaultwarden",
  "data": null,
  "data2": null
}
```

If provided using form encoded with:

````bash
curl -v \
  -d "code=8391c006eeda2bc1cc56" \
  -d "client_id=vaultwarden" \
  -d "client_secret=vaultwarden2" \
  -d "grant_type=authorization_code" \
  -d "redirect_uri=http://vaultwarden/identity/connect/oidc-signin" \
  "http://casdoor/api/login/oauth/access_token"
````

Then the response is a `401` with:

```json
< HTTP/1.1 401 Unauthorized
...
{
  "error": "invalid_client",
  "error_description": "client_secret is invalid for application: [admin/vaultwarden], token.CodeChallenge: empty"
}  
```

This was an headscratcher since at first I was not using Basic auth when debugging with `curl` and couldn't understand why I couldn't reproduce the failure.

**Comment by dacongda** [comment]
I sorry that you get confuse about auth, At first case, the request is denied in AutoSigninFilter which is used to auth `basic auth` request and always return restful result, and the second request successfully entry `access_token` api and return correct fail result.

**Comment by dacongda** [comment]
relevant code for basic auth in

https://github.com/casdoor/casdoor/blob/d4c81933571bbfb9e68cc084c22ea3b7edd309aa/routers/auto_signin_filter.go#L82-L91

and

https://github.com/casdoor/casdoor/blob/d4c81933571bbfb9e68cc084c22ea3b7edd309aa/routers/base.go#L68-L92

**Comment by dacongda** [comment]
will vaultwarden or oidc use basic auth to request? maybe i wll add a if statement to fix that if the answer is yes

**Comment by Timshel** [comment]
Yes the [oauth2-rs](https://github.com/ramosbugs/oauth2-rs) lib used in `openidconnect-rs` use basic auth to transmit the client secret.

This mean that if invalid it will handle the 200 as a success and output a missing `access_token` error.
As specified in [spec](https://openid.net/specs/openid-connect-core-1_0.html#TokenErrorResponse) if the request is invalid or unauthorized then a 400 is expected (the lib just handle everything that is not 200 as an error).

**Comment by dacongda** [comment]
ok, i will try to make a pr to fix it later

**Comment by Timshel** [comment]
Note that this is a relative minor issue since it only happen when configuring the server.
But it might confuse the user  (I put a warning in the documentation on my side).

**Comment by Timshel** [comment]
Just tested looks good :)
