### ISSUE TITLE
Casdoor crash when PostgreSQL pool is full

### ISSUE THREAD

**Issue by benbenz** [casdoor/casdoor#3168]
I am using Casdoor with a PostgreSQL database and I am running a load test (50 users / second up to 5000 users).
I am using mostly, /api/signup, /api/login/oauth/access_token and /api/login/oauth/introspect

At some point Casdoor crashes with the following error:

panic: pq: sorry, too many clients already
goroutine 21229 [running]:
github.com/casdoor/casdoor/object.updateUsedByCode(0x14001c7e700)
	/Users/ben/Dev/sxnths/nomo/casdoor/object/token.go:166 +0x114
created by github.com/casdoor/casdoor/object.GetOAuthToken in goroutine 20243
	/Users/ben/Dev/sxnths/nomo/casdoor/object/token_oauth.go:251 +0x424
exit status 2

**Comment by hsluoyz** [comment]
@benbenz I think it's your PG DB's max conn number setting issue

**Comment by benbenz** [comment]
The DB process list doesn't seem to reach 20/30 live queries but I have the max_connections at 100.

**Comment by benbenz** [comment]
I don't think the ticket should be closed. It is an issue that a server crashes when the max connection has been reached. This is likely triggerd by a max connections issue but the server shouldn't stop running.

**Comment by emanuelet** [comment]
Agreed, is it possible to apply the `engine.SetMaxOpenConns()` option? https://xorm.io/docs/chapter-01/readme/#connections-pool

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/1600a6799acce7db11529572245a73fffc4fafbf
