### ISSUE TITLE
Keycloak sync "error 1146: Table 'keycloak.user_entity' "doesn't exist"

### ISSUE THREAD

**Issue by chung1912** [casdoor/casdoor#3171]
Keycloak synchronization "error 1146: Table 'keycloak.user_entity' "doesn't exist" occurs because the table name of Keycloak is capitalized "USER_ENTITY", and when the synchronization type of the synchronizer is selected as Keycloak, the table name is forced to be lowercase and cannot be changed. MySQL data is case-sensitive, so the lowercase "user_entity" table name cannot be found
![e81a50e24c43b22d9ce18ea3b792a2c6](https://github.com/user-attachments/assets/40effcac-d9cb-4034-987d-f9eb6fbfdf40)

**Comment by hsluoyz** [comment]
@chung1912 what do you want? Can you provide PR?

**Comment by chung1912** [comment]
> @chung1912 what do you want? Can you provide PR?
A simple solution is to select keycloak and then edit it, instead of locking it so that users can enter the uppercase text themselves.I can't submit a PR, I'm not familiar with this programming language.
![image](https://github.com/user-attachments/assets/88112e8b-2c50-41f4-8d82-4b9dca131ddc)

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/0d02b5e768f5737c6b38fde73c83fbb69e08f3f6
