### ISSUE TITLE
keycloak cannot sync properly

### ISSUE THREAD

**Issue by chung1912** [casdoor/casdoor#3172]
![9e0cb33cda3303c62552d124c0e5087f](https://github.com/user-attachments/assets/9981e7cb-6490-47b4-8c7b-85b913dacc88)
Keycloak cannot be synchronized normally. The error "SyntaxError: Unexpected token '<,"<!DOCTYPE ".is not valid JSON" occurs during synchronization

**Comment by hsluoyz** [comment]
@chung1912 show the Go crash log (call stack)

**Comment by hsluoyz** [comment]
Closed as stale

**Comment by hsluoyz** [comment]
@alexander-watsup paste your Go backend crash log

**Comment by alexander-watsup** [comment]
> Running syncUsers()..
> 2026/01/07 13:26:02.751 [C]  the request url is  /api/run-syncer
> 2026/01/07 13:26:02.751 [C]  Handler crashed with error strconv.Atoi: parsing "\x00": invalid syntax
> 2026/01/07 13:26:02.751 [C]  /usr/local/go/src/runtime/panic.go:791
> 2026/01/07 13:26:02.751 [C]  /go/src/casdoor/util/string.go:43
> 2026/01/07 13:26:02.751 [C]  /go/src/casdoor/util/string.go:78
> 2026/01/07 13:26:02.751 [C]  /go/src/casdoor/object/syncer_util.go:211
> 2026/01/07 13:26:02.751 [C]  /go/src/casdoor/object/syncer_util.go:340
> 2026/01/07 13:26:02.751 [C]  /go/src/casdoor/object/syncer_database.go:100
> 2026/01/07 13:26:02.751 [C]  /go/src/casdoor/object/syncer_keycloak.go:27
> 2026/01/07 13:26:02.751 [C]  /go/src/casdoor/object/syncer_user.go:28
> 2026/01/07 13:26:02.752 [C]  /go/src/casdoor/object/syncer_sync.go:41
> 2026/01/07 13:26:02.752 [C]  /go/src/casdoor/object/syncer.go:306
> 2026/01/07 13:26:02.752 [C]  /go/src/casdoor/controllers/syncer.go:168
> 2026/01/07 13:26:02.752 [C]  /usr/local/go/src/reflect/value.go:584
> 2026/01/07 13:26:02.752 [C]  /usr/local/go/src/reflect/value.go:368
> 2026/01/07 13:26:02.752 [C]  /go/pkg/mod/github.com/beego/beego/v2@v2.3.8/server/web/router.go:1234
> 2026/01/07 13:26:02.752 [C]  /go/pkg/mod/github.com/beego/beego/v2@v2.3.8/server/web/filter.go:83
> 2026/01/07 13:26:02.752 [C]  /go/pkg/mod/github.com/beego/beego/v2@v2.3.8/server/web/router.go:1003
> 2026/01/07 13:26:02.752 [C]  /usr/local/go/src/net/http/server.go:3210
> 2026/01/07 13:26:02.752 [C]  /usr/local/go/src/net/http/server.go:2092
> 2026/01/07 13:26:02.752 [C]  /usr/local/go/src/runtime/asm_amd64.s:1700
>

**Comment by alexander-watsup** [comment]
I fixed an issue by changing column types in keycloak database.

Table USER_ENTITY:
- EMAIL_VERIFIED: bit(1) to tinyint(1)
- ENABLED: bit(1) to tinyint(1)
