### ISSUE TITLE
User's role mapping from external provider

### ISSUE THREAD

**Issue by viico** [casdoor/casdoor#3173]
We want to use Casdoor with an external identity provider (via SAML). Important user field (id, username, email...) mapping is possible in the provider screen.

But we would like to map also user's roles. Our identity provider give us a list of user's role and we would like to map this role with casdoor's role. Is it possible ?

I thought a workaround was possible with webhooks but I don't think we have access to the token to retrieve informations.

**Comment by dacongda** [comment]
can you show which saml idp you are using?

**Comment by viico** [comment]
It's our enterprise's IDP, based on OpenAM.

**Comment by dacongda** [comment]
> It's our enterprise's IDP, based on OpenAM.

thx for reply, I will try to make a pr in this week

**Comment by hsluoyz** [comment]
Closed as stale

**Comment by viico** [comment]
"Closed as stale" ? Could you reopen the issue or tell us why it is "invalid" please ?

I'm sorry I missed the last notification with the attribute example question... I will find an example for you. But I'm surprise with this question, I guess your solution will be generic so any example should works ?
