### ISSUE TITLE
LDAP cannot log in via ldap password, prompting incorrect password

### ISSUE THREAD

**Issue by chung1912** [casdoor/casdoor#3177]
https://github.com/casdoor/casdoor/pull/3175 Fixed the problem that users can log in with their own passwords. However, a new problem has arisen. Now users cannot log in with LDAP passwords, and the system prompts that the password is wrong.
![image](https://github.com/user-attachments/assets/7b50ddc5-1943-4215-b5b7-9f59a74037ad)

**Comment by hsluoyz** [comment]
@chung1912 PR: https://github.com/casdoor/casdoor/pull/3175 has been reverted. This issue is invalid now
