### ISSUE TITLE
Ldap fields return tag instead title in title value

### ISSUE THREAD

**Issue by aalmenar** [casdoor/casdoor#3184]
I believe this is being wrongfully returned here: https://github.com/casdoor/casdoor/blob/master/ldap/util.go#L70-L72

If you set a title on a user, why ldap returns the tag?

**Comment by hsluoyz** [comment]
@aalmenar tag in Casdoor is the title, like: CTO, CEO, Manager, Sales Manager, etc.

**Comment by aalmenar** [comment]
> @aalmenar tag in Casdoor is the title, like: CTO, CEO, Manager, Sales Manager, etc.

Then the title field in casdoor what is for?

**Comment by hsluoyz** [comment]
@aalmenar your comment will be recorded here. We will collect as many as comments before we decide to change this part
