### ISSUE TITLE
A bug where the login page title changes unexpectedly when multi-factor authentication is set

### ISSUE THREAD

**Issue by chung1912** [casdoor/casdoor#3188]
When multi-factor authentication is set up, the title of the current application is displayed on the login homepage, but after entering the multi-factor authentication page, the title will change to the title of the build-in.
This bug does not occur when logging into the user page (e.g. https://www.mycasdoor.com/login/test),
but does occur during the normal authorization process (e.g. https://www.mycasdoor.com/login/oauth/authorize?response_type=code&client_id=xxxxxxxxxxxxx&redirect_uri=https://my-domain.com/callback&scope=openid+email+profile&code_challenge=xxxxxxxxxxxxxxxx&code_challenge_method=S256)

![image](https://github.com/user-attachments/assets/741c72a2-ad95-4c44-b57e-7dd82e077039)

![image](https://github.com/user-attachments/assets/570cf092-3601-4198-ba78-37d525b9b58e)

![image](https://github.com/user-attachments/assets/8e974dff-010c-4b7d-a473-b8b0a819d303)

**Comment by dacongda** [comment]
![image](https://github.com/user-attachments/assets/559dffe6-4517-48a0-930c-915be153f9e9)

I failed to reproduce this bug , can you reproduce this bug in [demo site](https://demo.casdoor.com) or provide more detail ?

**Comment by hsluoyz** [comment]
@chung1912 use English screenshots, this issue will be deleted shortly
