### ISSUE TITLE
Org choice is not coming up even though org choice mode is set to select in OAuth flow

### ISSUE THREAD

**Issue by maknahar** [casdoor/casdoor#3196]
I am trying to user the org choice mode feature as describe here: https://casdoor.org/docs/application/specify-login-organization/ along with shared application as described here: https://casdoor.org/docs/application/shared-application/

- I have one shared application A1
- Multiple organizations (built-in, O1, O2)
- A1's default organization is built-in
- All organizations have default application set to A1

When I try to login to casdoor with url like `https://door.casdoor.com/login/built-in`, I see a modal to select the org choice.

However, I do not get the same option to select the org in auth flow. I have tried various urls like:
- https://door.casdoor.com/login/oauth/authorize?clientId.....
- https://door.casdoor.com/login/built-in/oauth/authorize?clientId.....
- https://door.casdoor.com/login/oauth/authorize?clientId.....&owner=built-in

Is org choice mode not applicable to users doing authentication in auth flow and only applicable when users are trying to login to casdoor itself?

**Comment by dacongda** [comment]
yes, we cannot choice org when we are using oAuth flow

**Comment by dacongda** [comment]
> yes, we cannot choice org when we are using oAuth flow

org choice mode is design to login to casdoor itself

**Comment by hsluoyz** [comment]
@maknahar I think you need the "Shared Application" feature to support multiple orgs in OAuth: https://casdoor.org/docs/application/shared-application

**Comment by maknahar** [comment]
@hsluoyz Yes. I think, shared application feature should automatically enable multi org support for OAuth.
