### ISSUE TITLE
 The cert "cert-built-in" does not exist

### ISSUE THREAD

**Issue by frankie-zeng** [casdoor/casdoor#3199]
I delete the cert build in, how to recovery it.
admin can't login

**Comment by hsluoyz** [comment]
@frankie-zeng delete DB tables, restart Casdoor

**Comment by frankie-zeng** [comment]
@hsluoyz suggest add disable prop to the button (cert-built-in), like others build in

**Comment by hsluoyz** [comment]
"cert-built-in" is allowed to delete. Direct login like https://door.casdoor.com/login doesn't need the cert, only OAuth needs.
