### ISSUE TITLE
Invalidate Refresh Tokens to Prevent Accumulation of Unused Tokens

### ISSUE THREAD

**Issue by hamidrabedi** [casdoor/casdoor#3209]
Currently, when a refresh token gets invalidated, the token remain in the database, potentially leading to an accumulation of unused or expired tokens. This can result in a large number of unnecessary records, which may negatively impact the database's performance over time.

Proposed Solution:

- Introduce a background cleanup task that periodically removes expired tokens from the database to ensure better performance and scalability.
- Move the old refresh tokens to another table for blocked or expired refresh tokens

**Comment by hsluoyz** [comment]
It's a "Let's your company's DBA do some work" type issue. We will not focus on that.
