### ISSUE TITLE
[Question] How to Extend the Login Session Duration?

### ISSUE THREAD

**Issue by KJZH001** [casdoor/casdoor#3210]
I have noticed that my Casdoor setup automatically logs out after approximately one day (24 hours), which, while beneficial for security, doesn't offer the best user experience for me. I believe a session duration of around a week or a month would be more appropriate.

Previously, I asked a similar question in WeChat and QQ groups, and someone suggested that I modify the `main.go` file by `setting beego.BConfig.WebConfig.Session.SessionCookieLifeTime = 3600 * 24 * 30` to control the session cookie lifetime.

However, as you can see in the code, it is already set to a one-month duration by default.

I’m using Docker for deployment, so I’m wondering if the issue could be that my program version is outdated, and perhaps the default value has changed.

To verify this, I simply checked the cookie information in the browser console. I saw the casdoor_session_id set to 2024-10-17T02:19:43.939Z, and today is September 17th, which is exactly one month from now.

So, the problem doesn’t seem to lie there, but I can't think of any other potential causes to investigate. Therefore, I’m seeking help from the community.

Here’s my site: [https://auth.moeworld.tech/](https://auth.moeworld.tech/)
You can access the Casdoor login page via this URL: [https://blog.moeworld.tech/wp-login.php?redirect_to=https%3A%2F%2Fblog.moeworld.tech](https://blog.moeworld.tech/wp-login.php?redirect_to=https%3A%2F%2Fblog.moeworld.tech
)
Thanks, everyone!

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/pull/3217 and https://github.com/casdoor/casdoor/commit/12d6d8e6ce634a2aae73128c30352e27e05ef7e5

**Comment by lqa0408** [comment]
When I set up Redis to store login information, the 30 day expiration time is too long and requires a very large amount of Redis memory. Can I adjust it to dynamically set the expiration time
