### ISSUE TITLE
The validity period of the token added on the management background is invalid

### ISSUE THREAD

**Issue by afrilead** [casdoor/casdoor#3212]
"code": 500,
    "reason": "",
    "message": "oauth2: \"invalid_grant\" \"authorization code has expired, nowUnix: [2024-09-17T19:03:29Z], token.CodeExpireIn: [1970-01-01T00:00:00Z]\"",
    "metadata": {}

**Comment by hsluoyz** [comment]
@afrilead token.CodeExpireIn should be a non-empty value (5 mins after now) when token is created. Check your DB.

![image](https://github.com/user-attachments/assets/364f627c-81bf-495b-9d6d-25f86147e2aa)
