### ISSUE TITLE
How to set configure backend endpoint

### ISSUE THREAD

**Issue by fantasy-yzj** [casdoor/casdoor#3220]
I deploy casdoor by helm under ingress, I don't know if there is a way to set the console and the backend endpoint, the casdoor admin console should be accessed by prefix path `/auth` and the casdoor api should be requested by `/auth/api/xxx`

**Comment by heng4fun** [comment]
We face the similar problem with deploying the casdoor under a reverse proxy with base path.

If the base path `/auth` proxy to casdoor server, the casdoor console can be request with the proxy host `ip:host/auth`, the casdoor door should be request with `ip:host/auth/api`.

but now, the casdoor frontend use a fixed address ip:host/api` to access the API, can be route to the casdoor server.

**Comment by heng4fun** [comment]
> Casdoor doesn't support being deployed in a subpath. It needs to use a root domain name

thx
