### ISSUE TITLE
[Discussion] Why read app version externally in runtime?

### ISSUE THREAD

**Issue by wintbiit** [casdoor/casdoor#3221]
When reading `controllers/system_info.go` route `/api/get-version-info`, I found that this api  either read the .git dir or read the `version_info.txt` provided by CI explicitly. Moreover it frequently uses `runtime.Caller()` to locate its dir.

I feel quite weird about why designing this. I think reading **version** info directly from external files (either from .git dir or some files) destroys app's **closure** and does not good for performace (although maybe this api is not one of the frequently calleds). And `runtime.Caller()` method may go unpredictable if I just add `-trimpath` when building.

So that's all. I feel weird about use cases of `GetVersionInfo()` and `GetVersionInfoFromFile()` in `utils/system.go`. In my opinion use something like `-ldflags="+X 'utils.version=xxx'"` to inject version info on build time or use `runtime/debug` would be better for both closure and performance. How do you think of this?

**Comment by hsluoyz** [comment]
Read the issues, PRs, commits to understand the background why it is designed as now.

**Comment by wintbiit** [comment]
I mean, of course we easily know that #da7336a9 added `GetVersionInfoFromFile()` with desc "feat: support getting versionInfo in docker". I mean I dont quite get why have to create a file **externally** to get version info just because docker built version is not running with a `.git` dir, sure enough no built version should run with source code dir. What I'm trying to say is that I think its not reasonable for productional uses and there is some more reasonable ways. And thank you again for creating casdoor!
