### ISSUE TITLE
Ui does not look proper near sign up option

### ISSUE THREAD

**Issue by 231tr0n** [casdoor/casdoor#3222]
Hi! I just wanted to notify that the UI does not look good at the sign up part and probably could be improved by putting a space between No account? and sign up now or bringing the sign up now to a new line.
![image](https://github.com/user-attachments/assets/12a641fd-4d6a-443b-9ab0-3ad72bc7769e)

**Comment by hsluoyz** [comment]
@231tr0n fixed by: https://github.com/casdoor/casdoor/commit/8ed6e4f93472f2613d563ffbd2b1241e4c39209d
