### ISSUE TITLE
Helm install failed, unknown driver "sqlite3"

### ISSUE THREAD

**Issue by ybizeul** [casdoor/casdoor#3223]
```
panic: sql: unknown driver "sqlite3" (forgotten import?)

goroutine 1 [running]:
github.com/casdoor/casdoor/object.InitAdapter()
    /go/src/casdoor/object/ormer.go:98 +0x23b
main.main()
    /go/src/casdoor/main.go:35 +0x30
```

**Comment by ZhaoYP-2001** [comment]
@ybizeul I can't reproduce your error. Can you provide specific reproduction steps/command execution screenshots?
![helm](https://github.com/user-attachments/assets/964c9d0f-660f-45e8-9522-c30e0140eb58)

**Comment by hsluoyz** [comment]
Closed as cannot reproduced

**Comment by ybizeul** [comment]
So the driver name in the chart `sqlite3` is normal, and shouldn't be `sqlite` ?
