### ISSUE TITLE
Missing `preferred_username` in claim

### ISSUE THREAD

**Issue by ybizeul** [casdoor/casdoor#3225]
I'm using LDAP backend for users.

When reading claims from the OIDC code, I get a bunch of informations, but there is no `preferred_username` field which should be present for scope `profile`.

**Comment by hsluoyz** [comment]
Prove it's Casdoor's bug, show code lines, which code is missing. Maybe it's just your own config issue like the previous one

Closed for now

**Comment by ybizeul** [comment]
Ok I see. That's the spirit.

I didn't put a totally undocumented obscure config line that's part of a third party library and has nothing to do here but I have to be a developer to use casdoor.

That was a nice trial period, not going to support that attitude.
