### ISSUE TITLE
can't create sqlite database with docker image

### ISSUE THREAD

**Issue by stydxm** [casdoor/casdoor#3227]
![](https://github.com/user-attachments/assets/4fa85ad9-cce0-464f-89fd-6598e8e80247)
![](https://github.com/user-attachments/assets/05503f47-a8ab-4eae-b0e1-d784e5b1d44b)
I followed the document[^1][^2] configuring database, but found errors above

Host memory and storage are sufficient, no limits was set, the same `out of memory` appears even on my physical server with 64G memory

Ubuntu22.04, Docker 27.3.1, image tag v1.706.0

[^1]:https://casdoor.org/docs/basic/try-with-docker

[^2]:https://casdoor.org/docs/basic/server-installation#sqlite3

**Comment by dacongda** [comment]
due to standard image has permission problem in create/read file,you can try to use `docker run -e driverName=sqlite -e dataSourceName='file:/conf/casdoor.db?cache=shared' -p 8999:8000 casbin/casdoor:latest`

**Comment by stydxm** [comment]
> due to standard image has permission problem in create/read file,you can try to use `docker run -e driverName=sqlite -e dataSourceName='file:/conf/casdoor.db?cache=shared' -p 8999:8000 casbin/casdoor:latest`

it's trying to connect to MySQL now
![](https://github.com/user-attachments/assets/ee1de249-50e2-4140-aade-f66c6b393e2b)

**Comment by hsluoyz** [comment]
@stydxm use v1.706.0 and use the suggestion at: https://github.com/casdoor/casdoor/issues/3227#issuecomment-2367746599

We will not modify any code for this issue

Closed here
