### ISSUE TITLE
alipay login  garbled text encoding issues 

### ISSUE THREAD

**Issue by wanghaolonggit** [casdoor/casdoor#3240]
<img width="188" alt="image" src="https://github.com/user-attachments/assets/bee9f8a8-18fc-4264-abe7-eb42d487e43f">

**Comment by hsluoyz** [comment]
@wanghaolonggit it relies on your database's encoding, should use utf8mb4.

**Comment by wanghaolonggit** [comment]
no, it is a bug.

**Comment by wanghaolonggit** [comment]
@hsluoyz  i  fix it , please see the code . https://github.com/casdoor/casdoor/pull/3241
