### ISSUE TITLE
Max length of certain URL fields are extremely limited

### ISSUE THREAD

**Issue by nan0tube** [casdoor/casdoor#3253]
As an example, the organisation favicon field (https://github.com/casdoor/casdoor/blob/034f28def9360cfc009ee67bb221eb840e593053/object/organization.go#L59C1-L59C72) is limited to 100 characters. 100-character is extremely limited by today's standard; is there a reason why it is so?

Past comment on increasing the limit: https://github.com/casdoor/casdoor/issues/1831#issuecomment-1545069944.

**Comment by hsluoyz** [comment]
@nan0tube fixed in: https://github.com/casdoor/casdoor/commit/bf730050d54553ff8fda665b6cbe75b8d4e10042

**Comment by nan0tube** [comment]
Thanks for the quick fix!

But are you able to share why does the project limits URLs to 200 characters? Just curious, why not say 1000 characters?
