### ISSUE TITLE
Provider as sole login method

### ISSUE THREAD

**Issue by marioatpewo** [casdoor/casdoor#3255]
In earlier Casdoor versions it was possible to turn off password logins. If an OAuth2 or a SAML provider was configured (e.g. AzureAD) the user was automatically redirected from the Casdoor app login page to said provider.

Now it is required to choose a signin method (password, verification code, WebAuthn or LDAP) and the user sees Casdoor's login screen even if a provider login is the only desired method.

How can the behavior described in the first paragraph be achieved with the current Casdoor version?

**Comment by dacongda** [comment]
in the new version this function will not be supported any more, but maybe we can consider it as a new feature in later version

**Comment by hsluoyz** [comment]
@marioatpewo which login UI do you mean? Give a screenshot

**Comment by dacongda** [comment]
https://github.com/user-attachments/assets/18c21ccc-7584-45e5-9431-4abb5ccb7213

do you mean like this?
