### ISSUE TITLE
Unexpected end of jason input 

### ISSUE THREAD

**Issue by Shenbagaraj11** [casdoor/casdoor#3256]
Hi Team,

we are trying to build the casdoor application linux machine, we configured everything, upto login page it came, after entering credentials it shows Unexpected end of jason input. 

Uncaught runtime errors:
×
ERROR
Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at http://10.5.1.139:7001/static/js/bundle.js:6236:16

Kindly suggest on this

**Comment by hsluoyz** [comment]
99% is your own issue, closed here

**Comment by gongxianjin** [comment]
> 99% is your own issue, closed here

i met it issue, can you help me ?
