### ISSUE TITLE
Invitation code works only for admin/app-built-in

### ISSUE THREAD

**Issue by baznikin** [casdoor/casdoor#3257]
I am trying to use invitation code. We do not use build-in organization and create own organization and application.
When I do `Copy signup page URL` and follow to this page there is message pop-up with `Invitation code is invalid` text. Sign-up page make requests to `/api/get-application?id=admin/app-built-in` and `/api/get-invitation-info?code=12345678&applicationId=admin/app-built-in` that I believe is not right.
Version: v1.681.0

UPD: when I change organization on built-in no error popups. Didn't try to signup to this organization through
![image](https://github.com/user-attachments/assets/d7da306b-5402-4183-bd15-6e6c5eb0ec0b)

**Comment by hsluoyz** [comment]
@dacongda

**Comment by dacongda** [comment]
I create a new org and application, then create a invitation code and not pop up invalid message
![image](https://github.com/user-attachments/assets/dd85e027-9a55-4761-ac0e-0cde9c8e7c06)
![image](https://github.com/user-attachments/assets/1e97ea0d-04e3-41c6-911a-429ac3357509)

canyou provide a demo video that how to reporduce this issue ?

**Comment by dacongda** [comment]
btw, use shared application may cause `Invitation code is invalid`

**Comment by baznikin** [comment]
Application not shared. I actually compare built-in application and organization and can't find anything THAT different. Looking forward to capture screen. How to share video with you?

**Comment by dacongda** [comment]
you can just capture the setting of invitation code and application

**Comment by dacongda** [comment]
also, share the setting of that organization will be much better

**Comment by baznikin** [comment]
https://youtu.be/hNN3oGgtKOw - please let me know when you check it, I'll close access

**Comment by dacongda** [comment]
> https://youtu.be/hNN3oGgtKOw - please let me know when you check it, I'll close access

ok, i check it

**Comment by dacongda** [comment]
> https://youtu.be/hNN3oGgtKOw - please let me know when you check it, I'll close access

can you show the link you copied, you can mask the domain

**Comment by dacongda** [comment]
> https://youtu.be/hNN3oGgtKOw - please let me know when you check it, I'll close access

emmm, according to the video, I think you can set the default application for your group like below

![image](https://github.com/user-attachments/assets/2958e9d3-c57d-4556-a821-6493731dd73a)

**Comment by baznikin** [comment]
Is it requirement to have default application?

**Comment by baznikin** [comment]
I set default application for organization - doesn't help

**Comment by baznikin** [comment]
I set application for invitation too - after this `Copy signup page URL` adds application name to signup URL.
When I remove specific application for Invitation previous link (with app name in it) still works.
So, looks like there is problem with invite link generation

**Comment by dacongda** [comment]
i try and can not reproduce it
https://github.com/user-attachments/assets/6f27f0e4-2d72-4595-bc83-13ec3924dd8e

**Comment by hsluoyz** [comment]
Closed for not reproducible

**Comment by baznikin** [comment]
Great way to handle issues! *sarcasm*
