### ISSUE TITLE
[feature] allow specify any telephone number

### ISSUE THREAD

**Issue by baznikin** [casdoor/casdoor#3261]
We do not really care what country telephone number is, we want our users to specify any number. Current approach if not really ideal...
I propose to add `ANY` countrycode atop of the list.
Update: if you try to save such list you got error `Failed to save: pq: value too long for type character varying(200)`

![image](https://github.com/user-attachments/assets/0f0a86bb-c91b-4104-902d-16d372ddf1da)

**Comment by baznikin** [comment]
Oops, it's actually not a feature request, it is bug report. When I try to save organization with such list I got `Failed to save: pq: value too long for type character varying(200)` error message

**Comment by hsluoyz** [comment]
Need to add an "All" option to that field as the first item in the drop-down menu

**Comment by dacongda** [comment]
> Oops, it's actually not a feature request, it is bug report. When I try to save organization with such list I got `Failed to save: pq: value too long for type character varying(200)` error message. After removing "duplicates" still do not fit ![image](https://private-user-images.githubusercontent.com/5183334/372484477-fa20af63-353b-45f1-a145-48254d2b7fb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTY3NTksIm5iZiI6MTcyNzg1NjQ1OSwicGF0aCI6Ii81MTgzMzM0LzM3MjQ4NDQ3Ny1mYTIwYWY2My0zNTNiLTQ1ZjEtYTE0NS00ODI1NGQyYjdmYjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMDgwNzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTFjMmFkZDk2NDYyNDBlYjc0ZjBlYjNiZDA3ODlmNGYxNjgwNjUxOWY5ZDVjYTY3ZDQwYThjM2NmNDI4NWVhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.oWvH1zxi8mPlksO_f3vDmNro0Kj711CEW6tKdd6mJkg)

sorry for the uncomfortable experience，you can tried to extend the length of `country_codes` field in database manually, for the limit of xorm. it seems that xorm will not extend length automatically after change the tag.and we will try to add `all` option in future, maybe this week.
