### ISSUE TITLE
feature: Add user to specified groups with invitation link

### ISSUE THREAD

**Issue by baznikin** [casdoor/casdoor#3265]
In our organization we are going to give some basic access to resources based on groups in casdoor. However, there is no way to automatically assign user to groups. It be nice feature to specify a set of groups to assign user to.

**Comment by hsluoyz** [comment]
@baznikin use Casdoor Public API: https://casdoor.org/docs/basic/public-api

**Comment by baznikin** [comment]
@hsluoyz I can't see how this help... Change user groups with some home-made automation via API is pretty same as manual assignment via Casdoor UI - after registration do not have access to our VPN and other services until he is not in set of groups.
I propose to add Groups input within invitation so user will get membership at moment of registration.
