### ISSUE TITLE
MFA uses the captcha when its set to None

### ISSUE THREAD

**Issue by hamidrabedi** [casdoor/casdoor#3268]
This is my config:

![image](https://github.com/user-attachments/assets/37d9d8cd-f766-42e1-85fd-9b3f43020961)

But when I click on the send code on the login page still asks for captcha:
![image](https://github.com/user-attachments/assets/61bb1223-b171-4268-8f25-52f6ebb18227)

**Comment by hsluoyz** [comment]
@hamidrabedi "None" only means captcha is disabled in login process. Captcha will always be enabled for MFA, see docs: https://casdoor.org/docs/provider/captcha/default#applying-in-your-application

**Comment by hamidrabedi** [comment]
So i have to completely remove it from the app so it doesn't appear on mfa?
