### ISSUE TITLE
Connect GitLab to Casdoor with LDAP

### ISSUE THREAD

**Issue by baznikin** [casdoor/casdoor#3270]
Hello! 

I am trying to connect GitLab to Casdoor with LDAP since this way UserSync available. There is issues on the way, but I hope you are interested in success same as me. Each problem by in separate issue.

During login process GitLab makes such request - see info in [GitLab documentation](https://docs.gitlab.com/ee/administration/auth/ldap/#security)
```
LDAPMessage searchRequest(4) "uid=3bc2c5de-058d-4888-a862-ff04aaa8e442,cn=user_btkqev,ou=GROUP,dc=sso,dc=DOMAIN,dc=com" baseObject
    messageID: 4
    protocolOp: searchRequest (3)
        searchRequest
            baseObject: uid=3bc2c5de-058d-4888-a862-ff04aaa8e442,cn=user_btkqev,ou=GROUP,dc=sso,dc=DOMAIN,dc=com
            scope: baseObject (0)
            derefAliases: neverDerefAliases (0)
            sizeLimit: 0
            timeLimit: 0
            typesOnly: False
            Filter: (userAccountControl:1.2.840.113556.1.4.803:=2)
                filter: extensibleMatch (9)
                    extensibleMatch userAccountControl
                        matchingRule: 1.2.840.113556.1.4.803
                        type: userAccountControl
                        matchValue: 2
            attributes: 1 item
                AttributeDescription: dn

```

In response Casdoor closes connection with messages in the logs:
```
2024/10/07 18:09:16 Connection client [81] from 10.244.0.226:55506 accepted
2024/10/07 18:09:16 <<< 81 - BindRequest
2024/10/07 18:09:16 >>> 81 - BindResponse
2024/10/07 18:09:16 <<< 81 - SearchRequest
2024/10/07 18:09:16 ******************************
2024/10/07 18:09:16 **** ROUTE MATCH ;  SEARCH****
2024/10/07 18:09:16 ******************************
2024/10/07 18:09:16 >>> 81 - SearchResultDone
2024/10/07 18:09:16 Error readMessagePacket: EOF
2024/10/07 18:09:16 client 81 close()
2024/10/07 18:09:16 client 81 close() - stop reading from client
2024/10/07 18:09:16 client 81 close() - Abandon signal sent to processors
2024/10/07 18:09:16 client [81] request processors ended
2024/10/07 18:09:16 client [81] connection closed
2024/10/07 18:09:16 Connection client [82] from 10.244.0.226:55518 accepted
2024/10/07 18:09:16 <<< 82 - BindRequest
2024/10/07 18:09:16 >>> 82 - BindResponse
2024/10/07 18:09:16 Error reading Message : runtime error: index out of range [47] with length 47
	3081ab0201026381a5045d7569643d33626332633564652d303538642d343838382d613836322d6666303461616138653434322c636e3d757365725f62746b7165762c6f753d62657467616d696e67732c64633d73736f2c64633d786d796265742c64633d636f6d0a01000a0100020100020100010100a92f8116312e322e3834302e3131333535362e312e342e3830338212757365724163636f756e74436f6e74726f6c83013230040402646e
```

I suppose if answer with empty response (do not close connection silently) GitLab can simply proceed to next steps.

**Comment by hsluoyz** [comment]
@baznikin you should debug the code to locate the code line for error: `Error reading Message : runtime error: index out of range [47] with length 47`

**Comment by baznikin** [comment]
I am not good enough to do debug, but I believe it came from upstream library you are using, there are issue for this case - https://github.com/vjeantet/ldapserver/issues/26. Looks like it is unmaintained - no updates for years. This particular issue was opened 6 years ago...
I suppose there is 2 options for you to implement better protocol handling - change library or make a fork to maintain it on your own.... I am not Golang programmer and can't help you with it

**Comment by baznikin** [comment]
WORKAROUND: Turns out, this request from GitLab can be skiped if set LDAP config option `active_directory: false`

**Comment by hsluoyz** [comment]
We have updated the LDAP import lib (not resolving this issue): https://github.com/casdoor/casdoor/commit/05830b9ff662c0db8a11c8976e54483ec07f6cb1

**Comment by baznikin** [comment]
For all people, who want to implement LDAP auth because you can't autocreate user in GitLab during first sign in - it is not true, you CAN create user in GitlLab during first sign in! 
https://docs.gitlab.com/ee/integration/omniauth.html#configure-common-settings
for helm values
```
global:
  appConfig:
    omniauth:
       allowSingleSignOn: ['openid_connect']
```
