### ISSUE TITLE
Request for Help: How to Migrate from Logto to Casdoor

### ISSUE THREAD

**Issue by cuixiaorui** [casdoor/casdoor#3271]
Hello everyone,

I am currently using Logto for user authentication and authorization management. However, due to certain reasons, we are planning to migrate our system to Casdoor. My understanding of Casdoor is still limited, so I would appreciate some guidance and assistance.

Specifically, I have the following questions:

Migration Process: What is the overall process for migrating from Logto to Casdoor? Is there an official migration guide or documentation available for reference?

Data Migration: How can I migrate user data (such as user information, roles, permissions, etc.) from Logto to Casdoor? Are there any tools or scripts that can help with this process?

I would greatly appreciate any help from the community or any experienced individuals who can share their migration experiences and suggestions. If there are any relevant documents or tutorials, please feel free to share them.

Thank you for your assistance!

**Comment by hsluoyz** [comment]
There's no such migration support from the community.
