### ISSUE TITLE
MFA Multi-factor authentication description is not updatable

### ISSUE THREAD

**Issue by maknahar** [casdoor/casdoor#3272]
When MFA for the user is enabled, dialog box to ask for code looks like below:

![Screenshot 2024-10-08 at 5 41 45 PM](https://github.com/user-attachments/assets/1d11c2df-8dd3-49ba-9390-1a7b43898b7d)

How do I update the `Multi-factor authentication description`? I searched for it in casdoor admin panel as well as in documentation but could not find any way to update it.

**Comment by dacongda** [comment]
according to 
![Uploading image.png…]()
it is a fixed text and cannot be changed

**Comment by dacongda** [comment]
according to 
![Uploading image.png…]()
it is a fixed text and cannot be change

**Comment by maknahar** [comment]
@dacongda This is going to be big problem for any production system then. Right? Just setting the description to empty would make more sense than current one.

**Comment by dacongda** [comment]
you are right, we will try to remove it or make it editable in the future

**Comment by maknahar** [comment]
Thanks for the super fast turn around on this issue @hsluoyz @dacongda .

**Comment by maknahar** [comment]
@hsluoyz @dacongda Thank you for making the change so quickly!  We're really impressed.  The current prompt, however, is a little confusing for our users as the next step in the MFA process is to click "Send Code" - users don't yet have an authentication code.  We are wondering if you could please change the prompt to this instead:
 
"You have enabled Multi-factor Authentication. Please click Send Code and follow the prompts to finish your login process"
 
Thanks

**Comment by maknahar** [comment]
I can raise the PR for the same if that helps.

**Comment by hsluoyz** [comment]
@maknahar it can be other ways than "Send Code"

**Comment by dacongda** [comment]
But in TOTP mode, there's no send button for user to click, maybe you can check the MFA mode and show relevant description, anyway, you're welcome to contribute.

**Comment by maknahar** [comment]
@dacongda @hsluoyz I have raised this PR https://github.com/casdoor/casdoor/pull/3280 to handle this. For TOTP based MFA description remain as is. For SMS/Email based MFA, message is updated to inform user that an action is required before they could enter the code.
