### ISSUE TITLE
Inconsistent username verification

### ISSUE THREAD

**Issue by baznikin** [casdoor/casdoor#3275]
In my organization turned on `Use Email as username` switch. Users join to organization with invite. Their usernames equal to emails.
If I create user manually I can't set its username to email, got validation error `Failed to save: The username may only contain alphanumeric characters, underlines or hyphens, cannot have consecutive hyphens or underlines, and cannot begin or end with a hyphen or underline.`

1. I propose to allow manually set username to email format.
2. Id like to have ability to set username to user part of email (all before `@`). For example if user have email `name.surname@domain.tld` enforce his username to `name.surname`. We use such format everywhere in organization but I have hard times to get this format out of casdoor. Should I add another issue for this one?

![Screenshot from 2024-10-09 11-06-46](https://github.com/user-attachments/assets/ee0391ac-cc03-46f5-aa44-5c67ff5e9bd8)

**Comment by hsluoyz** [comment]
@baznikin create new issue

**Comment by hsluoyz** [comment]
@dacongda
