### ISSUE TITLE
feat: Ability to get user part of email

### ISSUE THREAD

**Issue by baznikin** [casdoor/casdoor#3276]
Id like to have ability to
- either add option to enforce username to user part of email (all before @). For example if user have email `name.surname@domain.tld` enforce his username to `name.surname`
- or have a separate attribute with user part of email so I can request it. I suppose it is simplest variant because it won't affect other users of Casdoor.

We use such format everywhere in organization but I have hard times to get this format out of casdoor. For example, with GitLab we enforce this format of usernames (`name.surname` in our case) for all existing users and like to implement SSO with casdoor now.
If this feature be implemented I can configure GitLab like `uid_field = "userPartOfEmail"` to achieve desired behavior https://casdoor.org/docs/integration/ruby/gitlab/

**Comment by baznikin** [comment]
Researching sources of GitLab I found solution for my particular usecase, but it is hack on GitLab side. Consider this request anyway, maybe you'll find this feature useful for everyone
```
      args = {
        name = "openid_connect"
        gitlab_username_claim = "email"
```

**Comment by hsluoyz** [comment]
Closed for resolved
