### ISSUE TITLE
Support integration with TiDB dashboard

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#328]
See: https://docs.pingcap.com/tidb/stable/dashboard-session-sso (zh: https://docs.pingcap.com/zh/tidb/stable/dashboard-session-sso/)

Casdoor can also be a supported SSO method.

![image](https://user-images.githubusercontent.com/3787410/141328636-fbfe115d-cd43-40dc-abb3-852dfc432eb2.png)

**Comment by hsluoyz** [comment]
@Steve0x2a

**Comment by Steve0x2a** [comment]
I have tested the integration of TiDB and Casdoor using OIDC, and so far they work fine.
![image](https://user-images.githubusercontent.com/17063270/152717127-25b7fc35-ab4c-4f81-b5de-fe78c9ab4865.png)
