### ISSUE TITLE
Issue with Buy Product API via Casdoor Java SDK - "The user: app/rakaz doesn't exist" Error

### ISSUE THREAD

**Issue by MonishK2002** [casdoor/casdoor#3286]
Dear Casdoor Support Team,

I hope this message finds you well. I am writing to report an issue we are encountering with the "Buy Product" API while using the Casdoor Java SDK. Despite passing the correct arguments, we are receiving an error response. Below are the details of our implementation, the request, and the response:

Environment:

Casdoor SDK Version: 1.33.0
Java Version: 17
Operating System: windows 11

Implementation:

```java
  public String buyProduct(String productName, String providerName) {
        try {
            Product product = productService.buyProduct(productName, providerName);
            return "Buy product fetched successfully";
        } catch (Exception e) {
            throw new CustomException("Error Occurred while Buying the product: " + e.getMessage(), HttpStatus.BAD_REQUEST);
        }
    }
```

In this above implementation productService casdoor productService.

Request:
http://localhost:9090/api/v1/product/buyProduct?productName=product_llp7ij&providerName=stripe

Error Details:
Error Code: 400
Error Message: "Error Occurred while Buying the product: Failed fetching http://localhost:8000/api/buy-product?providerName=stripe&id=demo/product_llp7ij : The user: app/demo doesn't exist"

We have ensured that all required parameters are included and correctly formatted. Despite this, we continue to receive the above error indicating that the user "app/demo" does not exist. However, we have already created "demo" as an application in Casdoor, so we are unsure why this error is occurring.

If you need any further information to assist with diagnosing this issue, please let us know. We would appreciate your assistance in identifying the cause of this issue and any steps we can take to resolve it.

Thank you for your prompt attention to this matter.

Best regards,

Monish. K
Software Developer
mail2monishk@gmail.com
+91 8778809768

**Comment by hsluoyz** [comment]
@dacongda we should allow not only users but also applications (SDKs via client id/secret) to call Buy Product API too. Some stuffs need to be cleared up to support this scenario.

**Comment by hsluoyz** [comment]
@MonishK2002 what identity do you want to call the Buy Product API on behalf of? The Casdoor application? Or a specific user?

**Comment by MonishK2002** [comment]
@hsluoyz I wanted to follow up on my previous question. In our scenario when a customer admin creates a plan it automatically creates a corresponding product We want users to be able to buy this product, meaning the Buy Product API should be called on behalf of a specific user (e.g., Alice) making the purchase through the application . Could you please confirm if this is supported or if any additional configurations are needed?

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/7ae067e369a5d9bf4299c72eaae5074405c6a265
