### ISSUE TITLE
Refresh Token API does not work when application is shared and user is from different organization than application's.

### ISSUE THREAD

**Issue by maknahar** [casdoor/casdoor#3290]
Thanks for quickly fixing the issue https://github.com/casdoor/casdoor/issues/3288 I raised earlier.

The fix for that issue, seems to have fixed the panic and error is coming out of API in json format than a HTML. However, it did not fix the root cause of the issue. 

Refresh Token API does not work when application is shared and user is from different organization than application. It is returning the error that user does not exist when application is shared and user is from different organization than application's own organization. Application own organization is always `built-in` for shared application.

**Comment by maknahar** [comment]
@hsluoyz I have raised this PR with a potential fix. Please take a look: https://github.com/casdoor/casdoor/pull/3291

**Comment by hsluoyz** [comment]
Closed due to: https://github.com/casdoor/casdoor/pull/3291#issuecomment-2417037436
