### ISSUE TITLE
feature: errorCodes in API for errors

### ISSUE THREAD

**Issue by AtCliffUnderline** [casdoor/casdoor#3297]
Trying to integrate Casdoor as Backend for Frontend service. As for now, when API returns me an error I am supposed to parse error text. What if some kind of error codes or something else could be created to identify what sort of error happened.

**Comment by hsluoyz** [comment]
You can control the language field in HTTP request to the API, to make sure the returned error text is always specific language like English. You can check that error string. Error codes are not provided and no bandwidth to maintain that for now.
