### ISSUE TITLE
Discord Invite Link has expired

### ISSUE THREAD

**Issue by duckofdeath87** [casdoor/casdoor#3298]
Your discord link is expired. Could you make a new one and update the documentation?

**Comment by hsluoyz** [comment]
@duckofdeath87 which link has expired? Can you provide a screenshot abou the expiration error?

**Comment by rubberduck-ninja** [comment]
![image](https://github.com/user-attachments/assets/74ee2888-d9dc-46b5-aac1-d51afeaec0db)
![image](https://github.com/user-attachments/assets/ce62b6a3-6663-44a5-a1b8-605027e8f0b4)
![image](https://github.com/user-attachments/assets/7a5738b1-24fb-487f-8e2f-ea6c3083dde4)

**Comment by duckofdeath87** [comment]
![image](https://github.com/user-attachments/assets/1974c26c-1313-4b37-9ae6-440ece1e5322)
![image](https://github.com/user-attachments/assets/1d6c8bf0-016c-45e6-acbf-1d2bc8119fdc)
![image](https://github.com/user-attachments/assets/d629bf5e-8d73-4485-bdc6-826d52905fb1)

**Comment by hsluoyz** [comment]
@dacongda can you test the link?

**Comment by dacongda** [comment]
I can join the server via this link successfully

**Comment by hsluoyz** [comment]
Me too.

@duckofdeath87 this is your own issue, like your account has been banned, just a guess
