### ISSUE TITLE
bug: Incorrect `objectKey` Generation in `GetUploadFileUrl` Causes Path Issues with Domain Configuration

### ISSUE THREAD

**Issue by Gk0Wk** [casdoor/casdoor#3302]
Hi team,

I've encountered an issue with the `GetUploadFileUrl` function in the Casdoor project related to the handling of the `objectKey` when the `Domain` contains a path segment. This scenario is common in setups where internal and external networks use different URL rewrites. Here's a detailed explanation:

**Context:**

In internal networks, we're using an address like `http://localhost:1234` for Casdoor to upload files to a MinIO system. However, in external networks, we route traffic through Nginx using `https://test.com/api/s3`. Therefore, we need Casdoor to upload files using `http://localhost:1234/<bucket>/<objectKey>`, but the stored file URL should be `https://test.com/api/s3/<bucket>/<objectKey>`.

Currently, this setup is not supported by Casdoor. When configured as follows:

- **Entrypoint:** `http://localhost:1234`
- **Domain:** `https://test.com/api/s3`
- **Stored File Path:** `/foo/bar/1.jpg`

Casdoor uploads the file successfully and generates a correct URL: `https://test.com/api/s3/foo/bar/1.jpg`. However, the file is actually stored at `/api/s3/foo/bar/1.jpg` in the bucket, leading to an incorrect public file URL: `https://test.com/api/s3/api/s3/foo/bar/1.jpg`.

**Source of the Issue:**

Through reviewing the source code, I identified the problem in the following line:  
https://github.com/casdoor/casdoor/blob/6fcdad2100ea37ae11b00eb35f309ae180c77521/object/storage.go#L87

The `objectKey` is being constructed by concatenating the path from `Domain`, `PathPrefix`, and the file path. The proper approach should only concatenate `PathPrefix` and the file path for `objectKey`, while the path in `Domain` should only be part of the `fileUrl`.

**Proposed Solution:**

1. **objectKey Construction:**  
   - Concatenate only `PathPrefix` with the file path.

2. **fileUrl Construction:**  
   - Concatenate `Domain`, `PathPrefix`, and the file path.

Would appreciate your review of this issue and consideration for updating the logic. Thank you for your attention and help in resolving this problem!

**Comment by hsluoyz** [comment]
@Gk0Wk you should consider all the storage backends we supported, S3, Alibaba, etc. And provide a solution to support them all. Minio should not be the only one to be considered.

**Comment by hsluoyz** [comment]
Closed for stale
