### ISSUE TITLE
bug: Navbar elements get hidden behind Profile button

### ISSUE THREAD

**Issue by sourabhmandal** [casdoor/casdoor#3305]
The navbar elements like - "Loging and Metrics", "Business And Payment", "Admin" gets hidden behind the profile Tab on smaller screens

PC configuration-
Browser - Safari
OS - Mac OS
Size - 13 inch

<img width="1262" alt="Screenshot 2024-10-20 at 10 08 47 PM" src="https://github.com/user-attachments/assets/94a97ccf-0975-401d-82d8-2f783d2eef9e">

**Comment by hsluoyz** [comment]
@sourabhmandal can you make a PR to fix it?

**Comment by sourabhmandal** [comment]
Okay will attempt this one @hsluoyz

**Comment by sourabhmandal** [comment]
@hsluoyz this is fixed in latest in main branch, please close this issue

**Comment by hsluoyz** [comment]
@sourabhmandal which commit/PR fixed this issue?

**Comment by hsluoyz** [comment]
Closed as resolved
