### ISSUE TITLE
bug: improper usage stats UI

### ISSUE THREAD

**Issue by sourabhmandal** [casdoor/casdoor#3306]
The usage stats UI is different that shown in radial progress bar, although usage is mere 0.31% the progress bar is showing 25%.

![image](https://github.com/user-attachments/assets/f3c257d2-f996-4b59-a6f1-e6c8dcc64669)

**Comment by hsluoyz** [comment]
@sourabhmandal can you make a PR to fix it?

**Comment by sourabhmandal** [comment]
I will be glad to, stated on it @hsluoyz

**Comment by sourabhmandal** [comment]
@hsluoyz this is fixed in latest in main branch, please close this issue

**Comment by hsluoyz** [comment]
@sourabhmandal which commit/PR fixed this issue?

**Comment by hsluoyz** [comment]
Closed as resolved
