### ISSUE TITLE
Issue with Sign-In Page Redirection after Plan Selection

### ISSUE THREAD

**Issue by MonishK2002** [casdoor/casdoor#3307]
I am encountering an issue with the redirection to the sign-in page after selecting a plan. Here are the details:

Scenario:
After selecting a plan, the URL is saved successfully
The expected behavior is redirecting the user to the sign-in page upon clicking the plan

Issue:
The plan does not redirect to the sign-in page when clicking on the plan

Steps to Reproduce:
Select a plan from the pricing page.
Observe that the URL is saved successfully.
Click on the selected plan.

Expected Behavior:
After clicking on the selected plan, the user should be redirected to the sign-in page.

Actual Behavior:
The user is not redirected to the sign-in page.

Please let me know if any additional information is required to address this issue.

Could you please assist us?

Monish

**Comment by hsluoyz** [comment]
@MonishK2002 duplicated with: https://github.com/casdoor/casdoor/issues/3304
