### ISSUE TITLE
User is nil for tag: avatar   上传头像时用户为空

### ISSUE THREAD

**Issue by ChenXbFrank** [casdoor/casdoor#3309]
<img width="1366" alt="image" src="https://github.com/user-attachments/assets/a403d9f9-310f-4d9a-8644-e8980b4598c8">
新增用户时，http://xxxx:8001/users/zskj-agent/user_f6o6ol   地址栏会自动添加用户名，并且如果修改了名称，再去上传头像，发现后台会根据地址栏的用户进行检验，而接口传过去的用户名是修改之后的用户名，所以会提示用户为空。

建议将这里的用户名改成ID，浏览器地址上默认追加这里的ID，而不是用户名，界面上的id是不可修改的，后台应该使用该id进行校验合适一点。

**Comment by hsluoyz** [comment]
Use English, this issue will be shortly deleted
