### ISSUE TITLE
bug: resources URL not updated after the qiniu storage provider's endpoint update

### ISSUE THREAD

**Issue by ithilelda** [casdoor/casdoor#3310]
![before](https://github.com/user-attachments/assets/b9e52669-47fa-47c9-8ac4-d881070183b9)
  Using `http://a.example.com` when creating the qiniu storage provider, the resources uploaded in the Identity-Resources page will have the URL pointing to `http://a.example.com`.

  However, when updating the qiniu storage provider's endpoint later, for example, to `http://bbbb.example.com`, the resources will still point to `http://a.example.com`.

  If I delete the resource and reupload, the new resource's URL still points to `http://a.example.com` instead of `http://bbbb.example.com`.

**Comment by hsluoyz** [comment]
@ithilelda 

1. Check DB
2. Give demo video

**Comment by ithilelda** [comment]
@hsluoyz 
I think I found the problem. In the code, the direct source URL is generated using provider's domain property:
https://github.com/casdoor/casdoor/blob/c0800b7fb3402523052b1eaca846b472c4065e47/object/resource_direct.go#L41

However, domain doesn't exist for the qiniu storage provider (and maybe others), so you generate it on the fly when getting providers:
https://github.com/casdoor/casdoor/blob/c0800b7fb3402523052b1eaca846b472c4065e47/object/storage.go#L139C1-L145C3

once generated, it stays. modifying the endpoint property in the provider edit page only changes the endpoint property, as shown in this picture querying the database:
![2024-10-23 23_58_32](https://github.com/user-attachments/assets/02a993fa-baa0-4c56-8f73-691d240d1d59)

notice the endpoint changed, but not the domain.
