### ISSUE TITLE
CAS + Face ID Login Fails Due to Missing signinMethod Parameter

### ISSUE THREAD

**Issue by hyzyxmz** [casdoor/casdoor#3312]
A bug has been identified when attempting to log in using CAS + Face ID. The login attempt fails because the signinMethod parameter is not being passed from the frontend.

Issue:
When using CAS + Face ID, the frontend does not transmit the signinMethod parameter, causing the login to fail.
However, logging in with OAuth + Face ID works as expected without any issues.
![image](https://github.com/user-attachments/assets/644b9daa-845c-4922-91a0-7f6b43bc46a7)

**Comment by hsluoyz** [comment]
@dacongda
