### ISSUE TITLE
Not Receiving Verification Code on Mobile for Sign-In

### ISSUE THREAD

**Issue by MonishK2002** [casdoor/casdoor#3319]
![Casdoor_Subscription_issue](https://github.com/user-attachments/assets/4eed2e52-1a8b-44ce-9175-3124374c4e4f)

@halozhy After creating the pricing plan a URL is provided When I open this URL it redirects me to the sign-in page

I’m having trouble with the verification code when signing in After setting up a subscription plan I entered my email on the sign-in page but the code didn’t come to my mobile phone This stops me from completing the sign-in process.

Could you please check if there is a problem? Let me know if I need to set up anything differently

**Comment by dacongda** [comment]
it seems that the pic you post is the signup page

**Comment by dacongda** [comment]
and have you set a sms provider or email provider for your application? if not you can't receive any code, you can remove these two auth step by remove them in signup item of application setting.

**Comment by hsluoyz** [comment]
@dacongda if no SMS/email provider is found, I think Casdoor will show an error message, instead of not sending code silently. Is this true? If not, we should report error.

**Comment by hsluoyz** [comment]
Closed for not enough info
