### ISSUE TITLE
Can you tell me about Casdoor as a RADIUS server?

### ISSUE THREAD

**Issue by Lotusrootsoup** [casdoor/casdoor#3320]
Casdoor used as a RADIUS server do not know whether it can realize the WIFI Portal SMS authentication function

**Comment by hsluoyz** [comment]
@dacongda

**Comment by dacongda** [comment]
according the code , WIFI Portal SMS auth is unsupported

**Comment by Lotusrootsoup** [comment]
@dacongda Support WIFI Portal LDAP authentication?

**Comment by dacongda** [comment]
In face, I don't really understand what you what to do, can you post some picture or doc to describe it?

**Comment by hsluoyz** [comment]
Closed for stale
