### ISSUE TITLE
Cant start autoSync, but its set to 1

### ISSUE THREAD

**Issue by secure-xxx** [casdoor/casdoor#3323]
Thank You for great work.
I'm trying to deploy Casdoor as a stateless application. To configure the applications, LDAP, and organizations, I use the init_data.json file and have SQLite3 as the database, which gets truncated with each pod restart. The configuration is applied successfully, but user synchronization does not start until I log into the UI and press the "Save" button in ldap section in organization (even without making any changes). After that, syncing starts normally, i see it in a log, and I can connect GitLab via Casdoor.
I try to find any differences in sqlite dump and my config, its no difference. Version - 1.739

Config:
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-volume
data:
  app.conf: |
    appname = casdoor
    httpport = {{ .Values.service.port }}
    runmode = prod
    SessionOn = true
    copyrequestbody = true
    driverName = {{ .Values.database.driver }}
    dataSourceName = {{ include "casdoor.dataSourceName" . }}
    dbName = {{ include "casdoor.dbName" . }}
    redisEndpoint =
    defaultStorageProvider =
    isCloudIntranet = false
    authState = "casdoor"
    socks5Proxy = ""
    verificationCodeTimeout = 10
    initScore = 0
    logPostOnly = false
    origin =
    enableGzip = true
    ldapServerPort = 389
    initDataFile = "/init_data.json"
    initDataNewOnly = false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: casdoor-init-data
data:
  init_data.json: |
    {
        "organizations": [
          {
            "owner": "admin",
            "name": "prod",
            "displayName": "prod",
            "websiteUrl": "prod",
            "favicon": "",
            "passwordType": "plain",
            "passwordSalt": "",
            "passwordOptions": [
              "AtLeast6"
            ],
            "countryCodes": [
              "US",
              "RU"
            ],
            "defaultAvatar": "",
            "defaultApplication": "",
            "tags": [],
            "languages": [
              "en",
              "ru"
            ],
            "masterPassword": "",
            "defaultPassword": "",
            "initScore": 2000,
            "enableSoftDeletion": false,
            "isProfilePublic": true,
            "accountItems": []
          }
        ],
        "applications": [
            {
                "owner": "admin",
                "name": "my-oidc",
                "displayName": "GITLAB",
                "description": "GITLABB",
                "formBackgroundUrl": "https://img.freepik.com/free-photo/background-gradient-lights_23-2149304967.jpg?size=626&ext=jpg&ga=GA1.1.2008272138.1726012800&semt=ais_hybrid",
                "homepageUrl": "https://cdn.casbin.org/img/casdoor-logo_1185x256.png",
                "logo": "https://test.ru/_next/static/media/logo.8ad97082.svg",
                "forgetUrl": "https://sso.test.ru",
                "organization": "prod",
                "cert": "",
                "enablePassword": true,
                "enableSignUp": false,
                "clientId": "gitlab-test",
                "clientSecret": "test-secret",
                "providers": [
                  {
                    "name": "",
                    "canSignUp": true,
                    "canSignIn": true,
                    "canUnlink": false,
                    "prompted": false,
                    "alertType": "None"
                  }
                ],
                "signinMethods": [
                  {
                    "name": "Password",
                    "displayName": "Password",
                    "rule": "All"
                  }
                ],
                "redirectUris": [
                    "http://git.test.ru/users/auth/openid_connect/callback"
                ],
                "expireInHours": 168
            }
        ],
        "ldaps": [
            {
                "autoSync": 1,
                "id": "ldap-example",
                "owner": "prod",
                "serverName": "ldap-example",
                "host": "10.10.10.10",
                "port": 389,
                "enableSsl": false,
                "username": "user@test.local",
                "password": "test",
                "baseDn": "OU=Department,OU=test,DC=test,DC=local",
                "filterFields": ["uid", "sAMAccountName"],
                "filter": "(sAMAccountName=*)",
                "createdTime": "2022-10-31T19:47:36Z",
                "lastSync": "2023-10-31T19:47:36Z"
            }
        ],
        "certs": []
    }

**Comment by hsluoyz** [comment]
@dacongda

**Comment by dacongda** [comment]
this is because we call `InitLdapAutoSynchronizer` before `InitFromFile`, I will try to fix this later

**Comment by dacongda** [comment]
you can restart the service after successfully init data from json file to temporary fix this issue

**Comment by secure-xxx** [comment]
> you can restart the service after successfully init data from json file to temporary fix this issue

How can i do it gracefully inside container?

**Comment by dacongda** [comment]
normally, if u are using docker, restart the container will be better, but I'm not familiar with K8S

**Comment by secure-xxx** [comment]
temporary solution          
command: ["/bin/sh", "-c", "./server & sleep 30 && killall server && ./server"]

**Comment by hsluoyz** [comment]
Closed as resolved

**Comment by hsluoyz** [comment]
@secure-xxx I'm not familar with your specific scenario. It's also not an official deploy option in the docs. You cannot count on someone who never uses stateless + sqlite to learn that for you, deploy it for you, etc. You need to find it by yourself. If it's a Casdoor issue, a bug in the code, we are willing to merge the PR
