### ISSUE TITLE
Adapters automatically create tables

### ISSUE THREAD

**Issue by qq1176914912** [casdoor/casdoor#3324]
Excuse me, I have a few questions for you:
![image](https://github.com/user-attachments/assets/73abfca7-e67a-4837-b352-cd5983c1e10a)

1. I found that when adding Adapters, if the entered table name does not exist in the database, it will be automatically created. Is it only created when using the same database as Casdoor or when using external databases?
2. according to the current point of view, if the table name is not the same every time you fill in, you will always create a table, so the created table will be more and more, I think delete the Adapters data corresponding table will also be deleted, but after I do this operation, the bound table is not deleted, so I want to ask is it necessary to consider deleting the created table?

**Comment by hsluoyz** [comment]
@qq1176914912 

1. I don't remember it. You can see the code.
2. Casdoor doesn't delete the table for security reasons. Or you will say such things like it's unsafe, you should not delete my data. My data is lost, etc. You can write code + webhooks to delete tables by yourself
