### ISSUE TITLE
MFA not enabling in init_data mode

### ISSUE THREAD

**Issue by secure-xxx** [casdoor/casdoor#3326]
Hello, im using init_data.json for configuration all settings, in organization i set forcibly MFA app required (see config), in UI settings all looks normally, like in a config, but when associated LDAP user is logged in (in my case gitlab -->oidc-->casdoor), reqired MFA not asked and user simple login without any QR codes etc. When i remove MFA settings in UI and add again the same settings, all will work fine and user see QR request before login. Please fix it. 
![Uploading Снимок экрана 2024-11-01 в 19.00.21.png…]()

    {
        "organizations": [
          {
            "owner": "admin",
            "name": "prod",
            "displayName": "prod",
            "websiteUrl": "prod",
            "favicon": "",
            "passwordType": "plain",
            "passwordSalt": "",
            "passwordOptions": [
              "AtLeast6"
            ],
            "countryCodes": [
              "US",
              "RU"
            ],
            "defaultAvatar": "",
            "defaultApplication": "my-oidc",
            "tags": [],
            "languages": [
              "en",
              "ru"
            ],
            "masterPassword": "",
            "defaultPassword": "",
            "mfaItems": [
              {
                "name": "App",
                "rule": "Required"
              }
            ],
            "initScore": 2000,
            "enableSoftDeletion": false,
            "isProfilePublic": true,
            "accountItems": []
          }
        ],
        "applications": [
            {
                "owner": "admin",
                "name": "my-oidc",
                "displayName": "GITLAB",
                "description": "GITLABB",
                "formBackgroundUrl": "https://img.freepik.com/free-photo/background-gradient-lights_23-2149304967.jpg?size=626&ext=jpg&ga=GA1.1.2008272138.1726012800&semt=ais_hybrid",
                "homepageUrl": "https://cdn.casbin.org/img/casdoor-logo_1185x256.png",
                "logo": "https://test.ru/_next/static/media/logo.8ad97082.svg",
                "forgetUrl": "https://sso.test.ru",
                "organization": "prod",
                "cert": "",
                "enablePassword": true,
                "enableSignUp": false,
                "clientId": "gitlab-test",
                "clientSecret": "testsecret",
                "providers": [
                  {
                    "name": "",
                    "canSignUp": true,
                    "canSignIn": true,
                    "canUnlink": false,
                    "prompted": false,
                    "alertType": "None"
                  }
                ],
                "signinMethods": [
                  {
                    "name": "Password",
                    "displayName": "Password",
                    "rule": "All"
                  }
                ],
                "redirectUris": [
                    "http://git.test.team/users/auth/openid_connect/callback"
                ],
                "expireInHours": 168
            }
        ],
        "ldaps": [
            {
                "autoSync": 1,
                "id": "ldap-example",
                "owner": "prod",
                "serverName": "ldap-example",
                "host": "10.100.200.200",
                "port": 389,
                "enableSsl": false,
                "username": "dsfsdfsdf",
                "password": "sdfsdfsdf",
                "baseDn": "OU=Department,OU=DocDoc,DC=test,DC=local",
                "filterFields": ["uid", "sAMAccountName"],
                "filter": "(sAMAccountName=*)",
                "createdTime": "",
                "lastSync": ""
            }
        ],
        "certs": []
    }

**Comment by secure-xxx** [comment]
<img width="1207" alt="Снимок экрана 2024-11-01 в 19 00 21" src="https://github.com/user-attachments/assets/61b9175a-5612-4c68-b8d9-36fb77dfbd48">
<img width="1435" alt="Снимок экрана 2024-11-01 в 19 00 33" src="https://github.com/user-attachments/assets/40df8166-4279-4df6-995d-1effad63226d">
<img width="1440" alt="Снимок экрана 2024-11-01 в 19 00 58" src="https://github.com/user-attachments/assets/fa98530d-ee16-41cb-a744-f9e382e99db2">

**Comment by hsluoyz** [comment]
@dacongda

**Comment by secure-xxx** [comment]
> @dacongda

bug was fixed with lowercase for "name" parameter. Working variant:

            "mfaItems": [
              {
                "name": "**app**",
                "rule": "Required"
              }
            ],
Not working variant:
            "mfaItems": [
              {
                "name": "**App**",
                "rule": "Required"
              }
            ],

**Comment by dacongda** [comment]
> > @dacongda
> 
> bug was fixed with lowercase for "name" parameter. Working variant:
> 
> ```
>         "mfaItems": [
>           {
>             "name": "app",
>             "rule": "Required"
>           }
>         ],
> ```
> 
> Not working variant: "mfaItems": [ { "name": "**App**", "rule": "Required" } ],

ok, I don't know how you create your json file, but when I use init_data_dump_test.go to generate init_data file, It works perfect and get a correct mfa name. maybe this issue is cause by your own problem?

**Comment by secure-xxx** [comment]
> > > @dacongda
> > 
> > 
> > bug was fixed with lowercase for "name" parameter. Working variant:
> > ```
> >         "mfaItems": [
> >           {
> >             "name": "app",
> >             "rule": "Required"
> >           }
> >         ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not working variant: "mfaItems": [ { "name": "**App**", "rule": "Required" } ],
> 
> ok, I don't know how you create your json file, but when I use init_data_dump_test.go to generate init_data file, It works perfect and get a correct mfa name. maybe this issue is cause by your own problem?

Maybe, but lowercase variant worked. In UI by default used uppercase values, for example "Required" working, but "App" - no, only "app" - in data_json
