### ISSUE TITLE
The pricing page not working properly

### ISSUE THREAD

**Issue by pzguillaume** [casdoor/casdoor#3328]
The Pricing page is not working properly neither: if we clic on any plan of the Pricing Page (even on the Demo site, or on a live site too), the link forward the return URL of the product, but not to the product page itself.
So, that makes it impossible to pay a subscription...

**Comment by pzguillaume** [comment]
My mistake. User should create an account or login before to access to the product page...

**Comment by hsluoyz** [comment]
Closed as resolved
