### ISSUE TITLE
Optimize Token Validation and Retrieval Efficiency

### ISSUE THREAD

**Issue by notdu** [casdoor/casdoor#3344]
Current Code and Problem:
- The [GetTokenByTokenValue](https://github.com/casdoor/casdoor/blob/ba2e997d54a1d832c34a7b0e0fec378f128260c7/object/token.go#L140) method queries the database using the token’s value (if tokenHash not exist), which is a text field (without index). 
https://github.com/casdoor/casdoor/blob/ba2e997d54a1d832c34a7b0e0fec378f128260c7/object/token.go#L98-L117
- Indexing Limitations: The database currently has an index on [accessTokenHash](https://github.com/casdoor/casdoor/blob/ba2e997d54a1d832c34a7b0e0fec378f128260c7/object/token.go#L38), but doesn't have index in raw token value, this is not efficient for queries using the raw token value, particularly when an invalid token is passed. This results in slower lookups and unnecessary database load.
https://github.com/casdoor/casdoor/blob/ba2e997d54a1d832c34a7b0e0fec378f128260c7/object/token.go#L27-L39
- got error when index raw token field: `[54000] ERROR: index row size 2872 exceeds btree version 4 maximum 2704 for index "access_token_index" Detail: Index row references tuple (0,12) in relation "token". Hint: Values larger than 1/ 3 of a buffer page cannot be indexed. Consider a function index of an MD5 hash of the value, or use full text indexing.`
- Unnecessary Queries: Invalid tokens, particularly if attempted repetitively (e.g., in a brute force scenario), still trigger database calls that could be avoided with a pre-validation step.
https://github.com/casdoor/casdoor/blob/ba2e997d54a1d832c34a7b0e0fec378f128260c7/controllers/token.go#L324-L363

Solution #3343 :
Pre-Validation Step:
- Validate the token format before querying the database, minimizing unnecessary calls for invalid tokens.
- Use of GetTokenByValueOrId: replace GetTokenByValue with a GetTokenByValueOrId function, allowing retrieval by either token ID (primary key) if tokenHash not exist.

**Comment by notdu** [comment]
hi @hsluoyz, plz review it

**Comment by hsluoyz** [comment]
@notdu 

1. accessTokenHash is the hash for the token value. So checking it is OK for DB query. This is why we add the hash at the first place, to give it a short index.
2. I already explained, you access: https://door.casdoor.com/login it already generates a lot of DB queries. You don't need to optimize this one particularlly here, it's waste of time

**Comment by notdu** [comment]
hi @hsluoyz, I totally agree that accessTokenHash is an excellent way to optimize database checks. However, when a query misses, the API falls back to querying by the token itself, which can potentially overload the database, as the token field is too large for efficient indexing. This fallback also opens up a vulnerability where an attacker could spam the introspectToken endpoint with invalid hashes, causing a heavy load on the database.

To mitigate this, I suggest either ignoring queries by token directly or using a token ID for lookup as a preventative measure. What are your thoughts?

**Comment by hsluoyz** [comment]
@notdu Querying by token value is just a backward-compatible assurance. For new data with hash, the hash will be used. So if you clear all old data, you will be totally fine.

**Comment by notdu** [comment]
@hsluoyz, Querying the token by ID still ensures backward compatibility with the old tokens that don’t have a hash. Additionally, querying by tokenId instead of the raw token helps avoid partner issues when they send an invalid token like a said before.

```
curl --location 'localhost:8080/api/login/oauth/introspect' \
--header 'Authorization: Basic ****' \
--form 'token="invalid-token"' \
--form 'token_type_hint="access_token"'
```

**Comment by notdu** [comment]
hi @hsluoyz, Please help me review this, and if the above solution is not feasible, could we just add a config flag to enable/disable querying the raw JWT if its hash is not found? If the flag is not set and keeps its default value, the system will work as usual, but if enabled, it will only query tokenHash without querying the raw token. The database in my current system is overloaded because of querying the raw token when someone deliberately provides a token that does not exist in the database.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/5dc78732013a50aebbbf2aedb3db58e943fda44c

**Comment by notdu** [comment]
thanks @hsluoyz
