### ISSUE TITLE
Placeholder for SignIn Username & Password don't seem to work

### ISSUE THREAD

**Issue by baramustafa** [casdoor/casdoor#3349]
<img width="1337" alt="image" src="https://github.com/user-attachments/assets/1e455672-6682-4926-9e60-8207b6b6286f">

You can see Ive set the placeholders for Username and Password for the signin page but they don't seem to come through on the actual sign-in page below.  I have checked and am running the latest version.

<img width="373" alt="image" src="https://github.com/user-attachments/assets/a9cc1741-896e-4513-a34a-94377e153602">

**Comment by hsluoyz** [comment]
@baramustafa provide a demo video to reproduce the error
