### ISSUE TITLE
Problem in custom sms v1.751.0 - strconv.ParseInt

### ISSUE THREAD

**Issue by realxoman** [casdoor/casdoor#3357]
# Issue: Failed to Sign In Using OTP Code

I am encountering an issue with the Casdoor Docker image (`casbin/casdoor`) while attempting to log in using an OTP code. The login attempt fails, and the following error message is displayed:

`Failed to sign in: phone - strconv.ParseInt: parsing "": invalid syntax
`

## Steps to Reproduce

1. Deploy the Casdoor Docker image (`casbin/casdoor`) using the latest version.
2. Set up an application and configure it to use OTP-based authentication.
3. Attempt to log in by entering a valid phone number and the OTP code sent to it.
4. Observe the error after submitting the login form.

## Observations

- The error suggests that the backend is attempting to parse an empty value (`""`) as a phone number using `strconv.ParseInt`, which fails with a `parsing ""` error.
- Based on the logs and behavior, it seems the `phone` field in the request might not be populated correctly, or the backend is not handling it properly.

## Request Payload

Here is the payload I am sending as part of the login request (sanitized for security):

```json
{
  "application": "app-built-in",
  "organization": "built-in",
  "username": "12345678910",
  "autoSignin": true,
  "code": "943269",
  "signinMethod": "Verification code",
  "type": "login"
}
```

## Environment Details
- Casdoor Docker Image: casbin/casdoor
- Version: [v1.751.0](https://hub.docker.com/layers/casbin/casdoor/v1.751.0/images/sha256-e5bc46309d801074ed26d9db69a317e560d1d87bc9069d76126ccdb9c2bf1f71?context=explore)
- Deployment Environment: Docker
- Request Payload: See above.

![image](https://github.com/user-attachments/assets/acda9e48-159d-4da0-9b64-4c4cdeeb3db7)

**Comment by hsluoyz** [comment]
@realxoman provide the Go backend stack log for this error: `phone - strconv.ParseInt: parsing "": invalid syntax `

**Comment by realxoman** [comment]
I have this log:

![image](https://github.com/user-attachments/assets/2e4542b4-b56e-4c62-9442-76c4859e2fa7)

Note that I have same issue on email too.
In `casbin/casdoor-all-in-one` we don't have this issue but on `casbin/casdoor` we have.

**Comment by hsluoyz** [comment]
Cannot reproduce, closed for now
