### ISSUE TITLE
[Error] the official demo site cannot be logged in with an admin account

### ISSUE THREAD

**Issue by Mcayear** [casdoor/casdoor#3362]
the [demo site](https://demo.casdoor.com/login)
Account: `admin`
Password: `123`

Logging in will get an error.
![f8056e697d89bb21efe86b30735130bf](https://github.com/user-attachments/assets/9ca74bf2-70ec-46a1-8639-9dfbe1a9d8c7)

**Comment by hsluoyz** [comment]
@Mcayear see clarification for the two demo sites: https://github.com/casdoor/casdoor?tab=readme-ov-file#online-demo
