### ISSUE TITLE
[BUG] Changing MFA Configuration

### ISSUE THREAD

**Issue by hamidrabedi** [casdoor/casdoor#3370]
When switching between different MFA types, such as from app-based MFA to SMS-based MFA and back, the configuration for the previously used MFA method is deleted. This forces users to reconfigure their settings each time they revert to a previous MFA type, leading to unnecessary inconvenience and potential access issues. MFA configurations should be preserved for all enabled methods, allowing users to switch seamlessly without losing their setup.

**Comment by ljl66-66** [comment]
@hamidrabedi I conducted a more complete test, but I couldn't reproduce this bug, please give the operation to reproduce this bug.

**Comment by hamidrabedi** [comment]
seems to be fixed
