### ISSUE TITLE
[BUG] Broken Sign in Button Style

### ISSUE THREAD

**Issue by hamidrabedi** [casdoor/casdoor#3373]
When we add other login options the sign in button breaks:
![image](https://github.com/user-attachments/assets/23c7bbe7-0d37-482a-bfa2-1e13c03dc6f7)

Normal login:
![image](https://github.com/user-attachments/assets/b6ce09cb-2ab7-40b9-9fa8-93d47d5772f8)

**Comment by hsluoyz** [comment]
@hamidrabedi demo site doesn't have the issue you mentioned: https://door.casdoor.com/login

![image](https://github.com/user-attachments/assets/697147dc-1a21-45a0-ae0b-faa2a91a4ee5)

**Comment by hamidrabedi** [comment]
Nvm, the style of buttons had been changed and caused that problem. Thanks
