### ISSUE TITLE
can not request /cas/hfwy/zhcw/p3/serviceValidate?

### ISSUE THREAD

**Issue by zzutligang** [casdoor/casdoor#3377]
I use Casdoor as the CAS server, and after successfully login, the Java backend request follow url：http://localhost:7001/cas/hfwy/zhcw/p3/serviceValidate?servier=...&ticket=....
to verify the ticket, but I received the following result.

`<! DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Error</title></head><body><pre>Cannot GET /cas/hfwy/zhcw/p3/serviceValidate</pre></body></html>`

**Comment by hsluoyz** [comment]
@zzutligang CAS API is served by Go backend. you should use the port 8000 instead of 7001
