### ISSUE TITLE
Failed to save: Unauthorized operation

### ISSUE THREAD

**Issue by nanoguo** [casdoor/casdoor#3391]
my casdoor run in docker, it looks fine last week. but today when i edit my account info ,it said that `Failed to save: Unauthorized operation`, I am admin account, why I don't have permission to update my info, I can't create application too, the logs are below, many thanks.

```subOwner = built-in, subName = admin, method = GET, urlPath = /api/get-groups, obj.Owner = built-in, obj.Name = , result = allow
2024/12/02 03:42:01.123 [I]  (10.50.60.167: ) subOwner = built-in, subName = admin, method = GET, urlPath = /api/get-groups, obj.Owner = built-in, obj.Name = , result = allow
2024/12/02 03:42:01.124 [D]  |   10.50.60.167| 200 |   3.497207ms|   match| GET      /api/get-groups   r:/api/get-groups
subOwner = built-in, subName = admin, method = POST, urlPath = /api/update-user, obj.Owner = built-in, obj.Name = admin, result = deny
2024/12/02 03:42:02.448 [I]  (10.50.60.167: ) subOwner = built-in, subName = admin, method = POST, urlPath = /api/update-user, obj.Owner = built-in, obj.Name = admin, result = deny
2024/12/02 03:42:02.448 [D]  |   10.50.60.167| 200 |    690.536µs| nomatch| POST     /api/update-user
```

**Comment by hsluoyz** [comment]
@nanoguo try a new Docker deployment, it seems that your data have been damaged

**Comment by nanoguo** [comment]
@hsluoyz thx for your reply.
my database is in a  separate mysql ,  I stop and delete my old  deployment, and then run a new one, but it seems not work, the same errors still exist.

**Comment by nanoguo** [comment]
@hsluoyz thanks again. I backup my database, recreate deployment, then restore database ,it works. but I don't know what happend
