### ISSUE TITLE
[feature] support CUCloud OSS storage provider

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#3394]
CUCloud OSS: https://www.cucloud.cn/product/oss.html

Previous similar issues: https://github.com/casdoor/casdoor/issues?q=is%3Aissue+storage+provider , both frontend and backend code need to be modified

**Comment by dacongda** [comment]
According to [CuCloud document](https://support.cucloud.cn/document/127/572/133.html?id=133&arcid=4200), it seems that CUCloud is compatible with aws S3

**Comment by Gexinyu2333** [comment]
#3400

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/pull/3400
