### ISSUE TITLE
introspect `token_type` should be 'access_token' not 'access-token'

### ISSUE THREAD

**Issue by hadestructhor** [casdoor/casdoor#3398]
I thought it would be an issue from the merge of my [previous issue here](https://github.com/casdoor/casdoor/issues/3396) and in the pull request for it found [here](https://github.com/casdoor/casdoor/pull/3397) it is the case.

Token_type_hint and the returned response should contain either 'access_token' or 'refresh_token'. The newly changed values 'access-token' and 'refresh-token' are invalid and not what is expected by some systems.

At least now the introspect request goes through from my mail server that I setup to use OAUTH2 with casdoor. It's just giving me this error:

```
oauth2 failed: Introspection failed: Expected Bearer token, got 'access-token'
```

Would it be possible to make it compliant with Oauth2's expected return types as I mentioned in the previous issue ?

**Comment by hsluoyz** [comment]
@dacongda
