### ISSUE TITLE
How to solve the problem that all avatars and icons in the control panel are not displayed

### ISSUE THREAD

**Issue by Lotusrootsoup** [casdoor/casdoor#3403]
![微信截图_20241206214112](https://github.com/user-attachments/assets/57cdc5f7-2118-46c3-9e02-2b904f34933f)

How to solve the problem that all avatars and icons in the control panel are not displayed

**Comment by hsluoyz** [comment]
@Lotusrootsoup see docs, Intranet deployment option: https://casdoor.org/docs/deployment/deploy-intranet and CDN deployment option: https://casdoor.org/docs/deployment/deploy-cdn
