### ISSUE TITLE
Login with WebAuthn don't work on Safari IOS

### ISSUE THREAD

**Issue by EzraRT** [casdoor/casdoor#3404]
When using WebAuthn to login on the Safari browser on iOS, example.com is used for verification instead of xxx.example.com, but xxx.example.com is used when setting the key, resulting in login failure

**Comment by EzraRT** [comment]
BTW: I have configured the conf/app.conf
![ScreenShot 2024-12-07 at 09 24 15@2x](https://github.com/user-attachments/assets/2a3cb493-ed24-4e08-ab4b-18bd8aca4665)

**Comment by hsluoyz** [comment]
@EzraRT why do you think this is a Casdoor bug/issue? What behavior is Casdoor doing wrong?

**Comment by hsluoyz** [comment]
@dacongda

**Comment by EzraRT** [comment]
> @EzraRT why do you think this is a Casdoor bug/issue? What behavior is Casdoor doing wrong? Like 1 + 1, Casdoor should be expected to return 2 but got 3.

This is the only WebAuthn platform I use, and I'm even more inclined to think it's a Safari issue (I just reproduced it on Safari on macos). But maybe someone here has the same problem or solution and can help me?

**Comment by dacongda** [comment]
could you please provide more info? like a error message or a video

**Comment by EzraRT** [comment]
You can focus on the hostname in the GIF.
I can setup a new webauthn credential but can't login with it.
![ScreenShot 2024-12-07 at 10 16 40](https://github.com/user-attachments/assets/f3a7148d-275e-4f50-ab17-14a26fdd3b73)

**Comment by EzraRT** [comment]
Chrome works well, but Safari don't.

**Comment by EzraRT** [comment]
Maybe there's something special in the implement of navigator.credentials.get on Safari?

**Comment by dacongda** [comment]
> Maybe there's something special in the implement of navigator.credentials.get on Safari?

I try to install `docker-osx` and successfully login with passkey generated by icloud keychain, is this issue just happens on security key?

**Comment by dacongda** [comment]
I think you can open web inspector and provide info return by `login` interface

**Comment by EzraRT** [comment]
I upgraded my phone to ISO 18.2 RC, and now Webauthn can login correctly, but my Safari on macOS 15.1.1 still can't login correctly. I'm sure it's a Safari bug...
