### ISSUE TITLE
xml parsed failed when I use cas auth

### ISSUE THREAD

**Issue by nanoguo** [casdoor/casdoor#3411]
My usages：
1st. create an application for some app(in my case, it's jumpserver), then the auth is work well.
2nd. bind my lark account in casdoor.
3rd. when I open jumpserver login page, it will crash.

so, I debug the error, found that cause, xml parses cas response failed:

```text
File "/opt/py3/lib/python3.11/site-packages/cas.py", line 259, in parse_response_xml
    tree = ElementTree.fromstring(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1350, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1662
```

beacuse there're some `&` in  the avatar url in the cas response, `&` is not leagal character for the xml.

I encode the avatar url and then update the database record, it works.

then I read this project code, found it in [this line](https://github.com/casdoor/casdoor/blob/master/idp/lark.go#L219), maybe we should encode it before?

I try to do this, it works:
```go
	var encodedAvatarUrl strings.Builder
	if err := xml.EscapeText(&encodedAvatarUrl, []byte(larkUserInfo.Data.AvatarUrl)); err != nil {
		return nil, err
	}
	userInfo := UserInfo{
		Id:          larkUserInfo.Data.OpenId,
		DisplayName: larkUserInfo.Data.Name,
		Username:    larkUserInfo.Data.UserId,
		Email:       larkUserInfo.Data.Email,
		AvatarUrl:   encodedAvatarUrl.String(),
		Phone:       phoneNumber,
		CountryCode: countryCode,
	}
```

so, is  this case should be fix? maybe other idp's avatar url has same problem for cas auth.

**Comment by hsluoyz** [comment]
@nanoguo https://github.com/casdoor/casdoor/blob/master/idp/lark.go#L219 is Casdoor's internal UserInfo struct. It should not do the escape job. The escaping should be done in the XML generating part.

**Comment by hsluoyz** [comment]
@dacongda
