### ISSUE TITLE
[Feature] Use Logs instead of Print

### ISSUE THREAD

**Issue by hamidrabedi** [casdoor/casdoor#3412]
Add logs and config to change logger level (like debug, info, warning etc.). some prints are just making a mess in the terminal and make debugging hard. example:

https://github.com/casdoor/casdoor/blob/master/object/syncer_sync.go#L52
https://github.com/casdoor/casdoor/blob/master/object/syncer_sync.go#L86C4-L86C33

**Comment by hsluoyz** [comment]
@hamidrabedi seems to be good idea. Can you make a PR?

**Comment by hamidrabedi** [comment]
Casdoor currently is using Beego logs:
https://github.com/casdoor/casdoor/blob/master/main.go#L78

Should we change it to these?
https://github.com/sirupsen/logrus
https://github.com/uber-go/zap 

I'm unsure how far Casdoor can go and what the needs are.

**Comment by hsluoyz** [comment]
@hamidrabedi Beego logs is good. Why change it?

**Comment by hamidrabedi** [comment]
For many many reasons:
- We could make some sort of configuration and allow users to define their own formatter.
- We can have more complex logs, example with logrus:
```go
  log.WithFields(log.Fields{
    "organization":    "Google",
    "Application": "Google Drive",
  }).Fatal("Google is down")
```
- We can define webhooks and export logs with logrus: https://github.com/sirupsen/logrus?tab=readme-ov-file#hooks
- Logging with exact location of that log: https://github.com/sirupsen/logrus?tab=readme-ov-file#logging-method-name (Beego just says the file name with the line I think)

Obviously, these will come with a lot of work, but from now on Casdoor logs can be exported anywhere, and filters will be much easier on them, like on Kibana, users can put filters on organizations or have some alerts on specified Applications or other stuff.

**Comment by hsluoyz** [comment]
@hamidrabedi logrus seems to be ok. Can you make a PR? Want to take a look at what changes it will contain.

**Comment by ljl66-66** [comment]
@hamidrabedi Through exploration, logrus has brought significant changes to the original project, and the effect is not ideal. Some reasons and examples are shown in the file:
[Question examples.pdf](https://github.com/user-attachments/files/18143375/Question.examples.pdf)

**Comment by hamidrabedi** [comment]
@ljl66-66 using `TextFormatter` can help to make the format like beego.
You can set the default Beego logger to Logrus using this code:
```go
type logrusAdapterConfig struct {
	Level         string `json:"level"`
	Formatter     string `json:"formatter"`
	FullTimestamp bool   `json:"fulltimestamp"`
}

type LogrusAdapter struct {
	logger *logrus.Logger
	level  int
}

func NewLogrusAdapter() logs.Logger {
	l := logrus.New()
	return &LogrusAdapter{
		logger: l,
		level:  logs.LevelDebug,
	}
}

func (a *LogrusAdapter) Init(config string) error {
	var conf logrusAdapterConfig
	if err := json.Unmarshal([]byte(config), &conf); err != nil {
		return err
	}

	// Set log level
	switch conf.Level {
	case "debug":
		a.level = logs.LevelDebug
		a.logger.SetLevel(logrus.DebugLevel)
	case "info":
		a.level = logs.LevelInfo
		a.logger.SetLevel(logrus.InfoLevel)
	case "warn":
		a.level = logs.LevelWarn
		a.logger.SetLevel(logrus.WarnLevel)
	case "error":
		a.level = logs.LevelError
		a.logger.SetLevel(logrus.ErrorLevel)
	default:
		a.level = logs.LevelInfo
		a.logger.SetLevel(logrus.InfoLevel)
	}

	if conf.Formatter == "json" {
		a.logger.SetFormatter(&logrus.JSONFormatter{})
	} else {
		a.logger.SetFormatter(&logrus.TextFormatter{
			FullTimestamp: conf.FullTimestamp,
		})
	}

	return nil
}

func (a *LogrusAdapter) WriteMsg(when time.Time, msg string, level int) error {
	switch level {
	case logs.LevelEmergency, logs.LevelAlert, logs.LevelCritical, logs.LevelError:
		a.logger.Error(msg)
	case logs.LevelWarning:
		a.logger.Warn(msg)
	case logs.LevelNotice, logs.LevelInformational:
		a.logger.Info(msg)
	case logs.LevelDebug:
		a.logger.Debug(msg)
	default:
		a.logger.Info(msg)
	}
	return nil
}

func (a *LogrusAdapter) Destroy() {}

func (a *LogrusAdapter) Flush() {}

func (a *LogrusAdapter) SetLevel(l int) {
	a.level = l
	switch l {
	case logs.LevelDebug:
		a.logger.SetLevel(logrus.DebugLevel)
	case logs.LevelInfo:
		a.logger.SetLevel(logrus.InfoLevel)
	case logs.LevelWarn:
		a.logger.SetLevel(logrus.WarnLevel)
	case logs.LevelError:
		a.logger.SetLevel(logrus.ErrorLevel)
	default:
		a.logger.SetLevel(logrus.InfoLevel)
	}
}

func (a *LogrusAdapter) GetLevel() int {
	return a.level
}
```

and main.go:
```go
	beego.BeeLogger.Close()

	level := beego.AppConfig.String("logrus_level")
	if level == "" {
		level = "info"
	}
	formatter := beego.AppConfig.String("logrus_formatter")
	if formatter == "" {
		formatter = "text"
	}
	fulltimestamp := beego.AppConfig.DefaultBool("logrus_fulltimestamp", true)

	configMap := map[string]interface{}{
		"level":         level,
		"formatter":     formatter,
		"fulltimestamp": fulltimestamp,
	}
	configBytes, _ := json.Marshal(configMap)

	logs.Register("logrus", logrusadapter.NewLogrusAdapter)

	// Set Logrus as the logger
	logs.SetLogger("logrus", string(configBytes))
```

**Comment by hamidrabedi** [comment]
You are right about log rotations and it seems like Logrus does not have any plans to add that, but we could achieve complex log rotation using: https://github.com/natefinch/lumberjack , then allow users to have their own custom config for it.

related questions:
https://github.com/sirupsen/logrus/issues/655
https://github.com/sirupsen/logrus/issues/679
https://stackoverflow.com/a/67495666/22169295

**Comment by hsluoyz** [comment]
Too complicated, will not go further on this

**Comment by hamidrabedi** [comment]
what about changing the prints into beego logs at least? @hsluoyz

**Comment by hsluoyz** [comment]
@hamidrabedi there are only 28 matches. Do we really need to do this for just 28 places? So trivial

![26004238d691cdd5c86ef25c2630b487](https://github.com/user-attachments/assets/1a9ebf6d-1131-4b04-ba4e-73ab47a9fe8e)

**Comment by hamidrabedi** [comment]
@hsluoyz we actually had a problem with it, we added a syncer with 10 second interval and over 12 hour we had several problems and it was really hard to find the actual log between all those syncer prints.

**Comment by hsluoyz** [comment]
@hamidrabedi well, I need to see the PR to know whether the change is enough small. But we don't have people working on it now. Can you make a PR?
