### ISSUE TITLE
[bug] GitHub OAuth provider is not working, improve the error message

### ISSUE THREAD

**Issue by parasiteoflife** [casdoor/casdoor#3459]
I've setup GitHub as OAuth2 provider and is not working when trying to sign in: `Failed to login in: json: cannot unmarshal object into Go value of type []idp.GitHubUserEmailInfo` if I click on the `Back` button I'm sent to: `https://github.com/sessions/two-factor/app`

The demo site also fails with the same message.

**Comment by hsluoyz** [comment]
@parasiteoflife can you provide a demo video to reproduce this error?

**Comment by hsluoyz** [comment]
I have reproduced this issue in the demo site: https://demo.casdoor.com/

Need a fix

**Comment by dacongda** [comment]
![d6b8681a-6341-42dc-abce-8630c52d8ff6](https://github.com/user-attachments/assets/444dfcc7-57a8-4a69-ba23-62e4c89adb10)

email address should be set to `read only` or `read and write` if you use `github app`

**Comment by hsluoyz** [comment]
@dacongda the error message about json panic is not good. We need to return a more friendly error

**Comment by dacongda** [comment]
> @dacongda the error message about json panic is not good. We need to return a more friendly error

yes, I have create a pr to fix it

![image](https://github.com/user-attachments/assets/99e009e1-bc92-45cd-adef-714b5fd042b8)
