### ISSUE TITLE
Who is using Casdoor? 🔥🔥🔥🔥

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#361]
Customers are the most important driving power for us! If you are using Casdoor, please leave comment with the following format:

- Name: Casdoor demo site
- Company: Casbin open source organization
- URL: https://door.casbin.com/

Or in Chinese:

- 名称: Casdoor演示站
- 公司: Casbin开源社区
- 网址: https://door.casbin.com/

**Comment by qq690712575** [comment]
名称：深信计协万事屋
公司：萌点云科技（深圳）有限公司联合深圳信息职业技术学院计算机协会
网址：https : //stu.sziitjx.cn/

**Comment by wxc978952419** [comment]
名称：健客网上药店
公司：广州方舟医药有限公司
网址：https://www.jianke.com

**Comment by minmemory** [comment]
名称：乘车通
公司：上海久事公共交通集团有限公司
网址：https://cct.84000.com.cn

**Comment by minmemory** [comment]
名称：Lunadream
组织：Lunadream 新月社
网址：https://auth.lunadream.org （尚未上线）

**Comment by hamlinzheng** [comment]
Name: LoopX.AI
Company: LoopX Shanghai Co., Ltd.
URL: https://loopx.ai (not online yet)

**Comment by jianmaikj** [comment]
名称：简麦云erp
公司：浙江简麦科技有限公司
url：https://jmyunerp.com

**Comment by pangxianfei** [comment]
怎么设置邮箱服务器的呢？

**Comment by hsluoyz** [comment]
Hi @pangxianfei , can you create a new issue for your question and use English? This issue is for tracking Casdoor users. (you are welcomed to enter your company and project here:))

**Comment by pangxianfei** [comment]
名称：万维空间数据科技
公司：万维空间数据科技（深圳）有限公司
url：待定

**Comment by dmxzywy** [comment]
名称：生产者
公司:  生产创新
url : 待定

**Comment by dmxzywy** [comment]
想扩展功能，casdoor页面支持excel导入用户，还有用户自己注册或者后台管理员添加新用户或者修改用户完后，能够调用我们一个接口把用户推送给我们的接口，我们会给casdoor配置这个接口的url,到时用户添加或者信息变化能够把用户推送给这个接口

**Comment by zhongjixiuxing** [comment]
名称：蓝图房车
公司: 上海蓝团信息科技有限公司
url : 待定

**Comment by akun-y** [comment]
Name: Papers door
Company: mfull.cn
URL: https://door.bbs.mfull.cn/

**Comment by Nash-x9** [comment]
Name: FeedsBD
Company: FeedsBD
URL: https://sso.feedsbd.com/

**Comment by neil-lcv-cs** [comment]
Name: La Contre-Voie
Company (nonprofit organization): La Contre-Voie
URL: https://auth.lacontrevoie.fr/

Our organization still in the process of adopting Casdoor. We are planning to contribute to the French translation and eventually suggest / implement new features :)

**Comment by orcswang-lang** [comment]
名称：上海全应科技
公司：上海全应科技有限公司
网址：https://www.allsenseww.com
