### ISSUE TITLE
How/where do we edit and manage policies?

### ISSUE THREAD

**Issue by techarch** [casdoor/casdoor#37]
In the [Admin Portal](https://casbin.org/docs/en/admin-portal) page, it mentions: _"We provide a web-based portal called Casdoor for model management and policy management:"__ but after installing and running casdoor I cannot find any option to access a policy editor, nor do I need any source code related to that topic in the repository.
How/where we edit and manage policies?

**Comment by sourabhmandal** [comment]
@hsluoyz shall I make an editable dashboard to solve this issue.

**Comment by hsluoyz** [comment]
@techarch @mbahpoetih see: https://casdoor.org/docs/permission/overview
