### ISSUE TITLE
Support Hasura integration: Update JWT claims for business logic

### ISSUE THREAD

**Issue by 8byr0** [casdoor/casdoor#387]
I'm exploring casdoor for an integration with hasura but I'd need to add a few additional headers in user token since they're required on the other side.

I'm actually using auth0 which works quite well with post login hooks allowing me to run custom code like so: 
```javascript
/**
* Handler that will be called during the execution of a PostLogin flow.
*
* @param {Event} event - Details about the user and the context in which they are logging in.
* @param {PostLoginAPI} api - Interface whose methods can be used to change the behavior of the login.
*/
const axios = require('axios');

exports.onExecutePostLogin = async (event, api) => {
  
// business logic to fetch data from hasura

// Custom claim definition
  const namespace = "https://hasura.io/jwt/claims";
  api.accessToken.setCustomClaim(namespace, {
    'x-hasura-default-role': 'standard_user',
    'x-hasura-allowed-roles': ['standard_user'],
    'x-hasura-tenant-id': String("azertyuiop"),
    'x-hasura-user-id': "poiuytreza"  });
}
```

From what I've seen so far `/api/update-token` is available to update any token which would make the following work:
successful login > webhook triggered (casdoor) > node micro service > update token 

But I'd better not have to develop and maintain such additional block if not necessary so is there any alternative?

**Comment by hsluoyz** [comment]
@seriouszyx plz take a look

**Comment by hsluoyz** [comment]
@8byr0 

If the hasura claims are static, I think we can just add them to Casdoor code statically:
https://github.com/casdoor/casdoor/blob/3bdc0e0d1b1d74c9165cfc4e9208f5dc63780c93/object/token_jwt.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L40-L85

We will add a new field called `claimType` in the Application struct. Possible values for now can be "Normal" or "Hasura". If it's "Hasura", then the 4 additional claims are provided in JWT.

Is this OK?

**Comment by 8byr0** [comment]
Thanks for your reply, unfortunately the claims are dynamically fetched on successful login.

To make a quick explanation of hasura's working principle, it uses session variables to run business logic (e.g. check user id and his role before giving access to a document). These variables must be filled in the token to be checked at runtime.
More on this: https://hasura.io/docs/latest/graphql/core/auth/authorization/roles-variables.html#roles-variables 

My auth0 snippet is partial, I only included the final part that's updating token content but in reality this hooks starts by querying hasura instance to retrieve user data (role, hasura id, tenant or whatever informations related to current user). In the same way, when a user registers another hook is triggered to create a user in hasura db (and fill it's data with auth server internal id for later data reconciliation).


Regarding your current implementation (thanks for pointing it out), I think the best option would be to implement a logic similar to auth0's one 
```go
// beginning of the function
claims := Claims{ 
 		User:  user, 
 		Nonce: nonce, 
 		RegisteredClaims: jwt.RegisteredClaims{ 
 			Issuer:    beego.AppConfig.String("origin"), 
 			Subject:   user.Id, 
 			Audience:  []string{application.ClientId}, 
 			ExpiresAt: jwt.NewNumericDate(expireTime), 
 			NotBefore: jwt.NewNumericDate(nowTime), 
 			IssuedAt:  jwt.NewNumericDate(nowTime), 
 			ID:        "", 
 		}, 
 	} 

// Call user hook here to add data to claims?

// end of the function

```

I'm definitely not go expert (never used it) but we could imagine a snippet editor in admin panel with static analysis tool to check user input, then use this content (if it exists) to fill claims with additional data? This hook could be a simple function with token data and a few helpers passed as arguments ? 
From my knowledge it may be difficult to run go functions at runtime but a tool like v8go could allow to execute javascript easily (and also be more comfortable for users since javascript may be easier to dive in)  https://golangexample.com/execute-javascript-from-go/ 


Let me know what you think!

**Comment by hsluoyz** [comment]
@8byr0 maybe a claim hook editor would be helpful? How is the hook like? GET or POST? URL path? GET parameters? what are the keys? Are the GET keys the same as claim keys?

**Comment by 8byr0** [comment]
Here's how I actually manage it with auth0

- After user registration: POST to hasura graphql endpoint with created user `id` and `email`
```javascript
/**
* Handler that will be called during the execution of a PostUserRegistration flow.
*
* @param {Event} event - Details about the context and user that has registered.
*/
const axios = require("axios");

exports.onExecutePostUserRegistration = async (event) => {
  const { user, request, secrets } = event;

  const url = `${secrets.HASURA_URL}/v1/graphql`;
  const { user_id: userId, email } = user
  const upsertUserQuery = `
    mutation($userId: String!, $email: String!){
      insert_users(objects: [{ auth0_id: $userId, email: $email }], on_conflict: { constraint: users_pkey, update_columns: [] }) {
        affected_rows
      }
    }`;
  const graphqlReq = { "query": upsertUserQuery, "variables": { userId, email } };

  await axios({
    method: 'POST',
    url,
    headers: {
      'content-type': 'application/json',
      'x-hasura-admin-secret': secrets.HASURA_ADMIN_SECRET,
    },
    data: JSON.stringify(graphqlReq)
  })
};
```

- After user logs in (before returning JWT), POST to hasura graphql endpoint
```javascript
/**
* Handler that will be called during the execution of a PostLogin flow.
*
* @param {Event} event - Details about the user and the context in which they are logging in.
* @param {PostLoginAPI} api - Interface whose methods can be used to change the behavior of the login.
*/
const axios = require('axios');

exports.onExecutePostLogin = async (event, api) => {
  const { user, secrets } = event;

  const url = `${secrets.HASURA_URL}/v1/graphql`;
  const { user_id: userId, email } = user;

  const upsertUserQuery = `
    query ($auth0_id: String!) {
  users(where: {auth0_id: {_eq: $auth0_id}}) {
    id
    default_tenant_id
  }
}`;
  const graphqlReq = { "query": upsertUserQuery, "variables": { auth0_id: userId } };

  const { data: { data: responseContent } } = await axios({
    method: 'POST',
    url,
    headers: {
      'content-type': 'application/json',
      'x-hasura-admin-secret': secrets.HASURA_ADMIN_SECRET,
    },
    data: JSON.stringify(graphqlReq)
  })
  const { users } = responseContent;
  const remoteUser = users[0]
  if (!remoteUser) {
    throw Error('User not found')
  }

  const namespace = "https://hasura.io/jwt/claims";
  api.accessToken.setCustomClaim(namespace, {
    'x-hasura-default-role': 'standard_user',
    'x-hasura-allowed-roles': ['standard_user', 'team_member'],
    'x-hasura-tenant-id': String(remoteUser.default_tenant_id),
    'x-hasura-user-id': remoteUser.id
  });
};
```

Disclaimer: this is **MY** implementation, relevant to my project requirements. This is based on hasura official insights for auth0 integration (https://hasura.io/docs/latest/graphql/core/guides/integrations/auth0-jwt.html).

If we'd try to summarize from an abstract point of view, the best would be to
- execute request after action (login, register)
- choose endpoint url
- choose method request (I only need POST for now but others may need GET or DELETE on account deletion)
- write request body using user data (maybe with presets like `user_id` `user_email` that could be fulfilled at runtime)
- add custom headers
- Before JWT only: parse request result to add custom claim


Data structure could look like this:
```sql 
CREATE TABLE `casdoor`.`webhooks` (
    -- Unique id
    `id` INT NOT NULL AUTO_INCREMENT 
    -- Name of this hook
    `name` TEXT NOT NULL 
    -- Url 
    `url` TEXT NOT NULL 
    -- When this hook should be triggered
    `trigger_on` ENUM('post-login', 'post-register') NOT NULL 
    -- Whether this hook is enabled or not
    `enabled` BOOLEAN NOT NULL DEFAULT TRUE 
    -- HTTP method of the request
    `http_method` ENUM('POST', 'GET', 'DELETE', 'PATCH') NOT NULL DEFAULT 'POST' 
    -- Body of the request
    `body` JSON NOT NULL DEFAULT '{}' 
    -- Headers of the request
    `headers` JSON NOT NULL DEFAULT '{}' 
    -- Only available for post-register, use response to fill claims
    `response_to_claim_mapping` JSON NOT NULL DEFAULT '{}' 
    PRIMARY KEY (`id`)
);
``` 

### Example Post login hook:
- id: 1
- name: `Fill claims with hasura data`
- url: `http://localhost:8080/api/v1/graphql`
- trigger_on: `post-login`
- enabled: `true`
- http_method: `POST`
- body: 
```json 
{
    "query": "query ($auth0_id: String!) { \n users(where: {auth0_id: {_eq: $auth0_id}}) {\n id\n default_tenant_id\n}}",
    "variables": {
        "casdoor_id": "{{ User.id }}"
    }
}
```
- headers:
```json 
{
      "content-type": "application/json",
      "x-hasura-admin-secret": "mylongandsecretadminsecret"
}
``` 
- response_to_claim_mapping
```jsonc
{
    // Namespace
    "https://hasura.io/jwt/claims": {
        "x-hasura-default-role": "standard_user",
        "x-hasura-allowed-roles": ["standard_user", "team_member"],
        "x-hasura-tenant-id": "{{ Response.users[0].tenant_id }}",
        "x-hasura-user-id": "{{ Response.users[0].id }}"
      }
}
``` 


Before running this hook, casdoor would perform template replacement on body and headers. After response is received, template replacement in `response_to_claim_mapping`. 

What do you think?

**Comment by hsluoyz** [comment]
Hi @8byr0 we are working on this issue now, can you help us complete this survey? Thanks! https://github.com/casdoor/casdoor/issues/361

**Comment by hsluoyz** [comment]
@8byr0 all easy ones have been implemented:

![image](https://user-images.githubusercontent.com/3787410/147409604-93802d11-55eb-4c5d-87a4-507ac7fe90c0.png)

For the body and response parsing, actually I think it would be much easier to hard-code it as a "Hasura" webhook type, because it's very hard for Go to inteprete and execute something like `Response.users[0].tenant_id`, using a JS engine to do this is a overkill for now. So:

1. Can you give the accutate body format?
2. Can you provide a real Response data and accurate claims you want?

**Comment by 8byr0** [comment]
Sounds good! 
1. There's no "accurate" format since this is not hasura out of the box behavior (this is a custom implementation). My sample body actually shows standard required fields when querying graphql endpoint (i.e. query and variables) but variables' names and values are depending on actual context
2. Same as 1. it will definitely depend on every developer's implementation. In my case, hasura will return an array of objects like the following:
```json
{
  "users": [ 
    {
      "id": "abcde-fghij-klmno",
      "default_tenant_id": "azerty-uiopqs-dfghjk"
    }
  ]
}
```


Is it more clear? Or may I provide more explanations?

**Comment by hsluoyz** [comment]
@8byr0 can you define a "standard" format for the Hasura scenario, which can be hard-coded into Casdoor? I don't expect every Hasura user is happy, but at least a certain number of them can follow your implementation to connect Hasura with Casdoor.

**Comment by 8byr0** [comment]
@hsluoyz I follow you on this point, there's no trouble defining a standard way to use hasura with casdoor.
My only concern is that the content of the claim is highly related to every project business logic (and its actual architecture).

We can assume that the following should be at least present in JWT claims (should cover most use cases)
Request to fetch data:
```jsonc
{
    "query": "query ($casdoor_id: String!) { \n users(where: {casdoor_id: {_eq: $casdoor_id}}) {\n id \n}}",
    "variables": {
        "casdoor_id": "{{ User.id }}" // id of user that just logged in
    }
}
```
```jsonc
{
    // ...
    // Hasura Namespace
    "https://hasura.io/jwt/claims": {
        "x-hasura-user-id": "{{ Response.users[0].id }}",
        "x-hasura-default-role": "standard_user", // configured in casdoor dashboard
        "x-hasura-allowed-roles": ["standard_user", "team_member"] // configured in casdoor dashboard
      }
}
```

In case you implement a multitenant application there should be the following too:
```jsonc
{
    "query": "query ($casdoor_id: String!) { \n users(where: {casdoor_id: {_eq: $casdoor_id}}) {\n id\n tenant_id\n}}",
    "variables": {
        "casdoor_id": "{{ User.id }}" // id of user that just logged in
    }
}
```
```jsonc
{
    "https://hasura.io/jwt/claims": {
        "x-hasura-user-id": "{{ Response.users[0].id }}", // out of the response
        "x-hasura-tenant-id": "{{ Response.users[0].tenant_id }}", // out of the response
        "x-hasura-default-role": "standard_user", // configured in casdoor dashboard
        "x-hasura-allowed-roles": ["standard_user", "team_member"] // configured in casdoor dashboard
     }
}
```

It would be good to have other hasura users' feedback too!

**Comment by 8byr0** [comment]
Here are the requirements for post-signup hook (it will create a user on hasura's side after successful signup):
```jsonc
{ 
  headers: {
      'content-type': 'application/json',
      'x-hasura-admin-secret': "azertyuiop", // configured in casdoor dashboard
  }
}
```
Body: 
```jsonc
{
    "query": "mutation($userId: String!, $email: String!){\n insert_users(objects: [{ casdoor_id: $userId, email: $email }], on_conflict: { constraint: users_pkey, update_columns: [] }) {\n affected_rows\n}}",
    "variables": {
        "userId": "azertyuio", // out of new user data
        "email": "john@doe.com" // out of new user data
    }
}
```

**Comment by mojerro** [comment]
It's clear that we can use casdoor to inject default hasura settings in the request header.

But I'm still confused about how to generate JWT with custom fields.

**Comment by hsluoyz** [comment]
@8byr0 Hasura is already supported, see docs: https://casdoor.org/docs/integration/Haskell/Hasura
