### ISSUE TITLE
Are there any plans to support WeChat Mini Programs ？

### ISSUE THREAD

**Issue by cnbattle** [casdoor/casdoor#400]
Are there any plans to support WeChat Mini Programs？

**Comment by hsluoyz** [comment]
@cnbattle can you be more specific and describe your scenario with more details?

**Comment by cnbattle** [comment]
@hsluoyz 

微信小程序内，我们的用户系统是只先登录（wx.login拿code后端获取openid），后判断是否绑定手机再绑定这样静默登录的逻辑，或者手机登录同时传递（wx.login的code后端获取openid），然后增加前置接口只拿wx.login的code来现实静默登录相关的逻辑

google translate:
In the WeChat applet, our user system only logs in first (wx.login takes the code backend to get the openid), and then determines whether to bind the mobile phone and then bind the logic of such silent login, or the mobile phone login is transmitted at the same time (wx.login's code backend to get openid), and then increase the front interface and only take the code of wx.login to show the logic related to silent login

**Comment by hsluoyz** [comment]
@cnbattle can you complete this survey for us first? Thanks!

https://github.com/casdoor/casdoor/issues/361

**Comment by hsluoyz** [comment]
@Steve0x2a

**Comment by hsluoyz** [comment]
@cnbattle can you also join the QQ group: 645200447 ?

**Comment by Steve0x2a** [comment]
Perhaps you need to articulate your needs more clearly. If you are trying to use casdoor to implement sso within the mini program, it may be difficult to do so because of the various limitations of the mini program. Or you are trying to get casdoor's user information after logging in within the mini program, which may be easier to implement. You can add our qq group to get more detailed help.

**Comment by mojerro** [comment]
I hope to support the mini-program too. While using mini-program, the user's register path is quite different from using oauth. I draw these 2 diagrams to what's different.

### 小程序
```mermaid
sequenceDiagram
    participant A as 小程序
    participant B as MoAuthCenter
    participant C as 微信开放平台

Note over A: 小程序自动登陆
    A->>A: wx.login 获取 code
    A->>B: code -> POST /wx_mini/oauth/token
    B->>C: AppID,AppSecret,code
    C-->>B: session_key,openid,unionid
    B->>B: JWT 关联 openid,session_key
    B-->>A: JWT
```
### 网页、移动端标准oauth
```mermaid
sequenceDiagram
    actor U as 用户
    participant A as 个人应用
    participant B as MoAuthCenter
    participant C as 微信开放平台

    Note over U: 微信网页登录

    U->>A: 请求微信登录
    A->>B: GET /wx_web/oauth/authorize
    B-->>A: 302 uri:微信登录链接
    A->>C: uri
    C-->>U: 请求用户确认
    U->>C: 用户确认
    C-->>A: 302 携带code重定向到应用uri

    A->>B: uri + code -> /wx_web/oauth/token
    B->>C: AppID,AppSecret,code
    C-->>B: access_token,refresh_token,<br>expires_in,openid,scope

    Note over B: 获取用户信息

    B->>C: openid,accessToken
    C-->>B: userInfo
    Note over B,C: openid,nickname,sex,province,city,<br>country,headimgurl,privilege,unionid

    B->>B: JWT
    B-->>A: JWT

```

@Steve0x2a You can have a check, and I cannot find the api to transfer the code get from the mini-program.

**Comment by mojerro** [comment]
微信小程序支持要注意这几点，感谢官方支持
1、微信openid必须要有，但是同一个企业下的不同应用，微信openid不一样
2、同一个用户的unionid对于微信企业下不同应用是唯一的
3、调用微信官方能力需要使用unionid
4、没有绑定开放平台的微信应用没有unionid
5、上面的企业等效于微信开放平台的一个认证账户
