### ISSUE TITLE
Issue after changing password

### ISSUE THREAD

**Issue by pangxianfei** [casdoor/casdoor#402]
![图片](https://user-images.githubusercontent.com/9346931/147578114-90a0851b-cdea-439a-8cbc-5b1ae428d143.png)

Casdoor cannot recognize the logged-in user after changing password:

![图片](https://user-images.githubusercontent.com/9346931/147578299-fd030f01-e34a-4a95-aeb9-718cfb28e724.png)

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casdoor/casdoor/commit/377ac05928e0c0f82c3e5f0e5ff3b86ce3177cff
