### ISSUE TITLE
Does this support Device Authorization Grant?

### ISSUE THREAD

**Issue by softwareguy74** [casdoor/casdoor#404]
As the title says.

**Comment by hsluoyz** [comment]
@softwareguy74 can you describe your scenario with more details? Like controlling AppleTV?

**Comment by softwareguy74** [comment]
Most OICD providers allow authorizing a device that may not have a keyboard or easy way of input to grant access via a code or QR code that takes your phone or computer to a page that allows you to enter username and password which the device then queries and gets the authorization.

**Comment by hsluoyz** [comment]
@softwareguy74 so what's your device? We will first taget for and support your scenario specifically

**Comment by hsluoyz** [comment]
@softwareguy74

**Comment by hsluoyz** [comment]
Closed as stale
