### ISSUE TITLE
Add GitLab authentication to docs

### ISSUE THREAD

**Issue by nomeguy** [casdoor/casdoor#421]
Similar to: https://docs.gitlab.com/ee/integration/auth0.html

**Comment by hsluoyz** [comment]
Docs has been added: https://github.com/casdoor/casdoor/issues/421

**Comment by hsluoyz** [comment]
@Steve0x2a can we also add docs to gitlab like https://docs.gitlab.com/ee/integration/auth0.html ?

**Comment by Steve0x2a** [comment]
> @Steve0x2a can we also add docs to gitlab like https://docs.gitlab.com/ee/integration/auth0.html ?

@hsluoyz I created a [PR](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/78630)

**Comment by Steve0x2a** [comment]
@hsluoyz here we go~ https://docs.gitlab.com/ee/administration/auth/oidc.html#casdoor

**Comment by hsluoyz** [comment]
@Steve0x2a well done!
