### ISSUE TITLE
Develop a Casdoor plugin for APISIX

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#422]
Here are two plugins can be used as references:

1. KeyCloak: https://apisix.apache.org/docs/apisix/plugins/authz-keycloak/
2. Casbin: https://apisix.apache.org/docs/apisix/plugins/authz-casbin

The new plugin `auth-casdoor` will be added by making PR to APISIX's repo like how it's done for authz-casbin: https://github.com/apache/apisix/pull/4710

We can choose to make a casdoor-lua-sdk first or not, based on how the developer decide it.

There is some existing work to connect APISIX with Casdoor via OIDC: https://github.com/casdoor/casdoor/issues?q=apisix , but plugin is a better and easier solution. So a plugin is also important as well.

**Comment by hsluoyz** [comment]
@Steve0x2a

**Comment by rushitote** [comment]
Hi, this sounds really interesting but sorry I would not be able to actively develop this at this time. Though, if anyone else is willing to take this up I would be happy to help them.

**Comment by ComradeProgrammer** [comment]
https://github.com/apache/apisix/pull/6382
But it's only a draft pr because... I haven't figured out how to add test for it.

**Comment by hsluoyz** [comment]
@rushitote got it. I think @ComradeProgrammer has made a PR: https://github.com/apache/apisix/pull/6382 , can you help review it?

**Comment by rushitote** [comment]
@ComradeProgrammer 
So, if you manually tested the plugin you can then move onto the unit tests. The unit tests are very similar to manually testing the application where you send a request and check for the response to see if it's correct.

First install the submodules by `git submodule update --init --recursive`, that will install the testing toolkit and other required components. Then install `cpan` and then [this](https://github.com/iresty/test-nginx) tool, which APISIX uses for testing. You could look at the [APISIX's docs](https://apisix.incubator.apache.org/docs/apisix/internal/testing-framework/) for detailed information on installing the tool and writing tests. 

Also, you would need to modify the CI files of APISIX to install and configure Casdoor before running tests, but that can be done later on. You could create a folder for authz-casdoor under [t/plugin](https://github.com/apache/apisix/tree/master/t/plugin) for any config files you need to save for CI.

**Comment by ComradeProgrammer** [comment]
> @ComradeProgrammer So, if you manually tested the plugin you can then move onto the unit tests. The unit tests are very similar to manually testing the application where you send a request and check for the response to see if it's correct.
> 
> First install the submodules by `git submodule update --init --recursive`, that will install the testing toolkit and other required components. Then install `cpan` and then [this](https://github.com/iresty/test-nginx) tool, which APISIX uses for testing. You could look at the [APISIX's docs](https://apisix.incubator.apache.org/docs/apisix/internal/testing-framework/) for detailed information on installing the tool and writing tests.
> 
> Also, you would need to modify the CI files of APISIX to install and configure Casdoor before running tests, but that can be done later on. You could create a folder for authz-casdoor under [t/plugin](https://github.com/apache/apisix/tree/master/t/plugin) for any config files you need to save for CI.

Thank you very much. It turned that your advice was of great help! With the help of your instructions, I've successfully added tests for this pr. Besides, it seems that there is no need to add casdoor into CI files, because there are mocking suits in apisix so that some of casdoor's apis can be mocked. I can hardly express my sincere appreciation!

**Comment by ComradeProgrammer** [comment]
> @ComradeProgrammer So, if you manually tested the plugin you can then move onto the unit tests. The unit tests are very similar to manually testing the application where you send a request and check for the response to see if it's correct.
> 
> First install the submodules by `git submodule update --init --recursive`, that will install the testing toolkit and other required components. Then install `cpan` and then [this](https://github.com/iresty/test-nginx) tool, which APISIX uses for testing. You could look at the [APISIX's docs](https://apisix.incubator.apache.org/docs/apisix/internal/testing-framework/) for detailed information on installing the tool and writing tests.
> 
> Also, you would need to modify the CI files of APISIX to install and configure Casdoor before running tests, but that can be done later on. You could create a folder for authz-casdoor under [t/plugin](https://github.com/apache/apisix/tree/master/t/plugin) for any config files you need to save for CI.

Thank you very much. It turned that your advice was of great help! With the help of your instructions, I've successfully added tests for this pr. Besides, it seems that there is no need to add casdoor into CI files, because there are mocking suits in apisix so that some of casdoor's apis can be mocked. I can hardly express my sincere appreciation!

**Comment by rushitote** [comment]
> Thank you very much. It turned that your advice was of great help! With the help of your instructions, I've successfully added tests for this pr. Besides, it seems that there is no need to add casdoor into CI files, because there are mocking suits in apisix so that some of casdoor's apis can be mocked. I can hardly express my sincere appreciation!

That's great, I am really glad to hear that! The tests written by you are really well. Also didn't knew about the mocking suites in APISIX, it's nice that it has that.

**Comment by spacewander** [comment]
The APISIX members will accept https://github.com/apache/apisix/pull/6382, but there are a few questions:
1. Should we rename auth-casdoor to authz-casdoor, as the discussion in https://github.com/apache/apisix/pull/6382#discussion_r820404245?
2. The current implementation hardcodes `state=casdoor` in
> "/login/oauth/authorize?response_type=code&scope=read" ..
                                 "&state=casdoor&client_id="

AFAIK, it is vulnerable to CSRF attack. What do you think?

Finally, please help us to review https://github.com/apache/apisix/pull/6382, thanks!

**Comment by hsluoyz** [comment]
@spacewander thanks for reaching us here :)

> Should we rename auth-casdoor to authz-casdoor, as the discussion in https://github.com/apache/apisix/pull/6382#discussion_r820404245?

We will change to `authz-casdoor` based on the existing naming convention.

> AFAIK, it is vulnerable to CSRF attack. What do you think?

Thanks for bringing this up to us. This is indeed a security concern. We will fix this issue soon at: https://github.com/casdoor/casdoor/issues/564

> Finally, please help us to review https://github.com/apache/apisix/pull/6382, thanks!

Sure! We will help review it.

**Comment by hsluoyz** [comment]
Hi @spacewander , we're done here. Can you take a look at the updated PR: https://github.com/apache/apisix/pull/6382 ?

**Comment by hsluoyz** [comment]
Done at: https://github.com/apache/apisix/pull/6382
