### ISSUE TITLE
Add Casdoor docs to Minio

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#423]
Casdoor already supported Minio by: https://github.com/casdoor/casdoor/issues/409

Next we want to list the progress in Minio community, e.g., writing a docs page like: https://github.com/minio/minio/blob/master/docs/sts/keycloak.md

**Comment by hsluoyz** [comment]
@Abingcbc

**Comment by Abingcbc** [comment]
https://github.com/minio/minio/pull/14185

**Comment by hsluoyz** [comment]
PR merged
