### ISSUE TITLE
Does it support Token Introspection api for resource server?

### ISSUE THREAD

**Issue by LeonDevLifeLog** [casdoor/casdoor#425]
Does it support token introspection restful api for resource server?
Can't find related docs. search nothing.
支不支持Oauth2.0 Resource Server使用的token introspection接口？
没找到相关文档，用 Introspection 关键字在仓库内也没搜到相关内容。
refer: https://oauth.net/2/token-introspection/

**Comment by hsluoyz** [comment]
@Steve0x2a @seriouszyx

**Comment by Steve0x2a** [comment]
What do you prefer to implement using the Introspection endpoint? Our accessToken is in jwt format, and after parsing it we can also get username, exp, iat, etc.

**Comment by LeonDevLifeLog** [comment]
i want to check the token was revoked.
我想检查一下这个token是否被撤销。

**Comment by Steve0x2a** [comment]
> i want to check the token was revoked. 我想检查一下这个token是否被撤销。
@LeonDevLifeLog Currently you can use accessToken to request endpoints such as get-account to determine if the token is available, and we will discuss whether the Inspection endpoint needs to be added to the api list.

**Comment by hsluoyz** [comment]
@LeonDevLifeLog @Steve0x2a I think we have all the building blocks to provide such a API. We have saved all issued tokens into the token list: https://door.casbin.com/tokens . Even if the access token is not JWT, we can still get the metadata from this token list.

**Comment by hsluoyz** [comment]
@Steve0x2a can we add this (how to handle the access token) to docs?
