### ISSUE TITLE
help: how to delete test phone-num in demo site?

### ISSUE THREAD

**Issue by yurenchen000** [casdoor/casdoor#426]
https://door.casbin.com/account

i had try this demo， awsome and works well.
but,

associated telephone number by SMS，
 then how to disassociate my phone num from this online demo?

  the delete account button seems not work: told success, but refresh they still there)

 （I don't want to leave my info in this demo site）

**Comment by hsluoyz** [comment]
@yurenchen000 username?

**Comment by yurenchen000** [comment]
> @yurenchen000 username?

thanks for your reply.


my username "J[.O_O.]L",  and 
 I guess  lots of guys leave their phone-num in demo & can't delete by self, exposed to public access

![user_list.png](https://user-images.githubusercontent.com/8458213/150059581-dab77d30-d79c-47a9-96ec-c44d19ac8c5f.png)

**Comment by hsluoyz** [comment]
@yurenchen000 removed. We will mask the phone in future.
