### ISSUE TITLE
Support Apache DolphinScheduler authentication with Casdoor

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#430]
https://dolphinscheduler.apache.org/

See existing discussions:

- https://github.com/apache/dolphinscheduler/issues/4531
- https://github.com/apache/dolphinscheduler/issues/546
- https://github.com/apache/dolphinscheduler/issues/3451

**Comment by hsluoyz** [comment]
@Steve0x2a

**Comment by Abingcbc** [comment]
Related issue: https://github.com/apache/dolphinscheduler/issues/3451

**Comment by hsluoyz** [comment]
Done
