### ISSUE TITLE
Please support authorization code flow with PKCE

### ISSUE THREAD

**Issue by sep2** [casdoor/casdoor#431]
Spec: https://oauth.net/2/pkce/

This one is necessary for seriously secured SPA.

auth0 and okta all have this functionality.

https://auth0.com/docs/flows/authorization-code-flow-with-proof-key-for-code-exchange-pkce

https://developer.okta.com/blog/2019/08/22/okta-authjs-pkce

**Comment by hsluoyz** [comment]
@seriouszyx @Steve0x2a
