### ISSUE TITLE
[BUG] docker cannot connect to postgres

### ISSUE THREAD

**Issue by sep2** [casdoor/casdoor#433]
the `DockerFile` hard code `db:3306` prevents the image from being used with postgres.

**Comment by hsluoyz** [comment]
@ComradeProgrammer

**Comment by ComradeProgrammer** [comment]
> the `DockerFile` hard code `db:3306` prevents the image from being used with postgres.

Ok, I see where the problem is.  The hard code will be removed soon in an appropriate way.  Is there any other problems for using postgres except this problem?

**Comment by sep2** [comment]
None that I'm aware of for now, will test it with the new image later.

**Comment by sep2** [comment]
Actually you don't have to wait for db in the standalone image build, DBs are generally available anyway in prod environment.

In the all-in-one build you can wait for the db however since it's meant to be used together.

**Comment by ComradeProgrammer** [comment]
> Actually you don't have to wait for db in the standalone image build, DBs are generally available anyway in prod environment.
> 
> In the all-in-one build you can wait for the db however since it's meant to be used together.

Well, if you use docker compose to run it, it's very likely that although the container of database has started running, the database is actually not ready to accept incoming connections when casdoor is started, that's why we choose to wait for the database

**Comment by sep2** [comment]
In a production environment, the deployment of casdoor should not be tied to the deployment of a database. They should be deployed independently from each other, at least they should not be in the same docker-compose file.

Docker/docker-compose itself is not a good option for production database related things anyway. There are lots of discussions [like this one](https://vsupalov.com/database-in-docker/). It is only meant for testing/non-persistent usage. (which is why the All-in-one image is okay)

**Comment by sep2** [comment]
If somehow that's a hard requirement that casdoor must wait for a db to go alive or be immediately panic, the you can use `restart: always` in a docker-compose file to migrate that.

**Comment by hsluoyz** [comment]
@sep2 good solution! Does it mean that we just need to set `restart: always` in docker-compose and the code in PR: https://github.com/casdoor/casdoor/pull/436 is not needed any more, right?

**Comment by sep2** [comment]
That depends on what the deploy requirements are. Noted that we may have multiple requirements as long as they are not conflicted.

For deploying with docker-compose, the `restart: always` solves the issue at compose level, it doesn't care what is actually running inside the container image, it cares only "composibility".

For directly running from compiling source code (without compose and without docker), however the code to check for db liveness maybe necessary. (Or just panic, depends on what you want in this particular situation.)

These two options are separated layer of abstractions. They are complementary to each other.
