### ISSUE TITLE
Support xunlei(迅雷) authentication

### ISSUE THREAD

**Issue by qq690712575** [casdoor/casdoor#435]
docs:http://dev.open-api-auth.xunlei.com/platform?m=Developer&op=docPage&segment=introduce

**Comment by hsluoyz** [comment]
@seriouszyx @Steve0x2a

**Comment by Steve0x2a** [comment]
I'll work on this, but the current problem is that I can't create XUNLEI applications without real name authentication, and  can't find the real name authentication portal.

**Comment by qq690712575** [comment]
I will contact xunlei company

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Steve0x2a ***@***.***>
发送时间: Saturday, January 22, 2022 12:34:34 PM
收件人: casdoor/casdoor ***@***.***>
抄送: Jianle Chen ***@***.***>; Author ***@***.***>
主题: Re: [casdoor/casdoor] Support xunlei(迅雷) authentication (Issue #435)


I'll work on this, but the current problem is that I can't create XUNLEI applications without real name authentication, and can't find the real name authentication portal.

―
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcasdoor%2Fcasdoor%2Fissues%2F435%23issuecomment-1019046952&data=04%7C01%7C%7Cc1c5ddcd5f534e9b2f9f08d9dd607e10%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637784228763536999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=22U5f%2FfVHSZf1k9N7Ypg4r4Og8yf3yWeQietLpbRMZw%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEHBFI7TCRLAP3Z46G3AZHLUXIXVVANCNFSM5MPWGA5Q&data=04%7C01%7C%7Cc1c5ddcd5f534e9b2f9f08d9dd607e10%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637784228763536999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uK6CvEk9HRXcj8g0CmA1QyA2i3yQ6GS63V58hRQL62c%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cc1c5ddcd5f534e9b2f9f08d9dd607e10%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637784228763536999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vJit0Nj%2BzrvOiExtl6TsSQNCVA1mT%2FyyJNVSfU0mKt0%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cc1c5ddcd5f534e9b2f9f08d9dd607e10%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637784228763536999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lseb9YS8wG2DE0SoPrr38hWyhdLMOyUODbmt1e3Yn3o%3D&reserved=0>.

**Comment by Steve0x2a** [comment]
@qq690712575 Xunlei has replied to me with the relevant information: to apply for the application, you need to send an email to Xunlei Business and get permission. So I don't think Casdoor's Xunlei support is a high priority.
If you could provide us with an application to test, it might speed up the process a lot.

**Comment by hsluoyz** [comment]
low-priority, closed.
