### ISSUE TITLE
Support WeCom Internal development authentication

### ISSUE THREAD

**Issue by Herry-too** [casdoor/casdoor#441]
It seems that the current "Login with WeCom" only supports "third-party application development", and I hope it can support "internal development" if possible.
Docs: https://developer.work.weixin.qq.com/document/path/91025

**Comment by hsluoyz** [comment]
@Steve0x2a @seriouszyx

**Comment by hsluoyz** [comment]
@Herry-too frontend part done in: https://github.com/casdoor/casdoor/commit/fbc73de3bbac9cc49c6a8d6bf87345446a43abbe
