### ISSUE TITLE
OIDC Userinfo API response is not compliant with OIDC Standard

### ISSUE THREAD

**Issue by romeupalos** [casdoor/casdoor#443]
The Userinfo API endpoint should reply with all the available claims as part or the JSON root object as specified in the OIDC standard (Please, refer to section 5.3.2 of the standard https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse)

However, the current API is mapped to get-account which has its own response schema, wrapping the claims inside the attribute named "data".

Path to be compliant:
1. Implement an API that follows the OIDC API specification and shown in the link above (suggested path: /api/userinfo)

OIDC applications will look for preferred_username and email fields, which renders the OIDC feature pretty much useless until the userinfo is correctly implemented.

**Comment by hsluoyz** [comment]
@Steve0x2a

**Comment by Steve0x2a** [comment]
@romeupalos Thank you for your feedback! I have submitted a PR to resolve this issue, but for some reason, the userinfo_endpoint in oidc discovery needs to be modified along with the documentation to the new userinfo api. We will resolve this issue as soon as possible.

**Comment by romeupalos** [comment]
@Steve0x2a Thank you for working on this API request so fast! That is remarkable!
I reviewed the code you have and it looks good.

Some considerations and enhancements for the future to make it more secure and more compliant:
The API should only return the claims that are scoped by the current token.
The basic scopes and field relationships are defined here: https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims

I copied and pasted for convenience:
>profile
        OPTIONAL. This scope value requests access to the End-User's default profile Claims, which are: name, family_name, given_name, middle_name, nickname, preferred_username, profile, picture, website, gender, birthdate, zoneinfo, locale, and updated_at.
email
        OPTIONAL. This scope value requests access to the email and email_verified Claims.
address
        OPTIONAL. This scope value requests access to the address Claim.
phone
        OPTIONAL. This scope value requests access to the phone_number and phone_number_verified Claims.

Thank you for your work one more time!

**Comment by Steve0x2a** [comment]
@romeupalos OK, I will modify it according to your suggestion. Thanks again for your advice on Casdoor!

**Comment by Steve0x2a** [comment]
@romeupalos  The latest commit can now support the scopes `profile`, `email`, `address`, `phone` now.

**Comment by romeupalos** [comment]
That's great @Steve0x2a. Thank you for working on this.

**Comment by L11R** [comment]
@Steve0x2a thanks for adding those fields, but I found another example there service require `preferred_username` -- Mastodon. Currently it does not asks user to choose username, so it just takes it from `preferred_username` field. There is no option to set it using Casdoor as far as I understand.

**Comment by hsluoyz** [comment]
@L11R if you have questions, create new issue
