### ISSUE TITLE
No response at permission page

### ISSUE THREAD

**Issue by follisher** [casdoor/casdoor#445]
When I use permission page, it is will be unresponsive and show a blank page, in browser console, we can find an error info
<img width="552" alt="image" src="https://user-images.githubusercontent.com/1535732/150742906-4217a7f8-0c9c-4494-a522-132d8c483df9.png">

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by seriouszyx** [comment]
Hi, did you deploy Casdoor by yourself or test on https://door.casbin.com/? I tested it several times locally but didn't encounter the same problem. Could you please provide more information such as the data in your databse if you deploy it by yourself?

**Comment by follisher** [comment]
maybe you need testing in the initial project, when I testing in already exist project, i'm going to get nothing as well. It seems when project initial the function getTags(tags) of `Setting.js` file, the props `tags` have not value, so the method `forEach` don't know its a array object.
I fixed the issues in the pull request https://github.com/casdoor/casdoor/pull/449
