### ISSUE TITLE
code implementation is susceptible to replay attacks

### ISSUE THREAD

**Issue by sam-blackfly** [casdoor/casdoor#451]
Consider the following test cases to ensure the flow is hardened against such attacks:

- **Limited validity period**: The code should only be usable for 5 to 10 minutes for the time of issue.
- **Reuse**: The code should only be usable once. Consider race conditions on submission as well.
- **replay attacks**: Upon attempted reuse of the code all access tokens previously issues based on the code should be revoked, as it is an indicator of code compromise.

**Comment by hsluoyz** [comment]
@seriouszyx @Steve0x2a @ComradeProgrammer

**Comment by hsluoyz** [comment]
@sam-blackfly if you are using Casdoor, please help us input here: https://github.com/casdoor/casdoor/issues/361 , thanks!
