### ISSUE TITLE
Question: Regarding Docs

### ISSUE THREAD

**Issue by Shivansh-yadav13** [casdoor/casdoor#453]
I was going through Casdoor's Frontend configuration​ documentation
`showMessage()` and `goToLink()` are not exported from the `Setting.js` file due to which I am getting errors.
I think they should be added.
Please correct me if I'm doing something wrong.

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 why do you need these two functions?

**Comment by Shivansh-yadav13** [comment]
@hsluoyz in the react component to receive the `/callback`

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by seriouszyx** [comment]
@Shivansh-yadav13 The two functions you mentioned are exported from the `Setting.js`. What are your errors? Could you please provide more information?

```js
export function showMessage(type, text) {
  if (type === "") {
    return;
  } else if (type === "success") {
    message.success(text);
  } else if (type === "error") {
    message.error(text);
  }
}
...
export function goToLink(link) {
  window.location.href = link;
}
```

**Comment by Shivansh-yadav13** [comment]
@seriouszyx but it's not there in the docs? 😅
![Screenshot_20220127_120325](https://user-images.githubusercontent.com/87603425/151305203-d60d0fe8-7112-4043-8cfa-e1787d143f0f.png)

also this error:


and is there any demo app also?😅

**Comment by Shivansh-yadav13** [comment]
Can you also help me here:
![Screenshot_20220127_130954](https://user-images.githubusercontent.com/87603425/151313393-ab3a0155-6ea8-4135-b9c8-f0300dda8f6c.png)

**Comment by seriouszyx** [comment]
@Shivansh-yadav13 Sorry, I misunderstood your question before and didn't know you were using [casdoor-js-sdk](https://github.com/casdoor/casdoor-js-sdk). You can refer to [casnode](https://github.com/casbin/casnode/blob/master/web/src/Setting.js) and [casbin-oa](https://github.com/casbin/casbin-oa/blob/master/web/src/Setting.js).

**Comment by hsluoyz** [comment]
Done at: https://casdoor.org/docs/how-to-connect/sdk#:~:text=export%20function%20showMessage(type%2C%20text)%20%7B%0A%20%20if%20(type%20%3D%3D%3D%20%22%22)%20%7B%0A%20%20%20%20return%3B%0A%20%20%7D%20else%20if%20(type%20%3D%3D%3D%20%22success%22)%20%7B%0A%20%20%20%20message.success(text)%3B%0A%20%20%7D%20else%20if%20(type%20%3D%3D%3D%20%22error%22)%20%7B%0A%20%20%20%20message.error(text)%3B%0A%20%20%7D%0A%7D%0A%0Aexport%20function%20goToLink(link)%20%7B%0A%20%20window.location.href%20%3D%20link%3B%0A%7D
