### ISSUE TITLE
Support Apache ShardingSphere authentication with Casdoor 

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#456]
See:

- https://shardingsphere.apache.org/document/legacy/4.x/document/en/manual/sharding-proxy/configuration/#authentication
- https://github.com/apache/shardingsphere/issues/9844
- https://github.com/apache/shardingsphere/issues/6140
- https://github.com/apache/shardingsphere/issues/9844
- https://github.com/apache/shardingsphere-ui

See: https://github.com/apache/shardingsphere/search?q=ui&type=issues ,it seems that the UI project has been deprecated:

- https://github.com/apache/shardingsphere/issues/13071#issuecomment-945057427
- https://github.com/apache/shardingsphere/pull/13118
- https://github.com/apache/shardingsphere/issues/12391#issuecomment-926322128

**Comment by linghengqian** [comment]
@hsluoyz FYI. https://github.com/apache/shardingsphere/discussions/13569

**Comment by hsluoyz** [comment]
@linghengqian thanks for the pointer! When will ShardingSphere (open source version or commercial version) have a new controll plane like a web UI?

**Comment by linghengqian** [comment]
> @linghengqian thanks for the pointer! When will ShardingSphere (open source version or commercial version) have a new controll plane like a web UI?

- `Apache ShardingSphere` has a sub-project `ElasticJob` responsible for task scheduling. It has a set of basicauth front-end page `ElasticJob UI`. This is the only front-end component of this project that is still being maintained. The home page of the project is at https://github.com/apache/ shardingsphere-elasticjob-ui . In the discussion on the mailing list, the PMC related to `ShardingSphere` believes that basicauth should be removed and maintained. Please refer to https://lists.apache.org/thread/791z4t628n1mszxgyg4q29b58tt62sr4, I hope it will help you.

- In fact, there is a related early ecological component `CyborgFlow`, from https://github.com/SphereEx/cyborg-flow , but the front-end page of that component is more related to `Apache Skywalking`. This looks related to https://github.com/casdoor/casdoor/issues/457 . For more introduction, please refer to https://skywalking.apache.org/zh/2022-01-18-cyborg-flow/ .

**Comment by hsluoyz** [comment]
@linghengqian thanks for this detailed explanation, it really helps a lot for us! We will first try to help with the `ElasticJob UI` scenario in terms of this issue.

> I don't know how to integrate it with the ShardingSphere community. Refer to https://sphere-ex.com/en/products/console/ .

I think sphereEX can provide a uniform SSO integration mechanism like how TiDB does: https://docs.pingcap.com/tidb/stable/dashboard-session-sso , so everyone can freely integrate with external authentication solutions.

**Comment by linghengqian** [comment]
> I think sphereEX can provide a uniform SSO integration mechanism like how TiDB does: https://docs.pingcap.com/tidb/stable/dashboard-session-sso , so everyone can freely integrate with external authentication solutions.

FYI. @tristaZero

**Comment by seriouszyx** [comment]
@hsluoyz https://github.com/apache/shardingsphere-elasticjob-ui/pull/151

**Comment by hsluoyz** [comment]
Done
