### ISSUE TITLE
Make better integration with the SpringBoot community

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#459]
1. Add name to: https://spring.io/projects/spring-security-saml

![image](https://user-images.githubusercontent.com/3787410/151315090-1211914b-5591-4d89-bcee-7905bb9ada13.png)

2. Listed in the initializer: https://start.spring.io/

![image](https://user-images.githubusercontent.com/3787410/151314961-0fe5e807-20ad-4bb9-b862-26a549839d03.png)

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by seriouszyx** [comment]
done https://github.com/spring-projects/spring-boot/pull/30220 

https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-starters/README.adoc

![image](https://user-images.githubusercontent.com/33992371/159114045-862e4876-3501-41d3-8acf-13091e3a12e6.png)
