### ISSUE TITLE
 Support Istio authentication with Casdoor

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#464]
See similar as: https://www.keycloak.org/2018/02/keycloak-and-istio.html

- Add name to: https://istio.io/latest/docs/concepts/security/#:~:text=ORY%20Hydra-,Keycloak,-Auth0

![image](https://user-images.githubusercontent.com/3787410/151651658-09eb2d57-ec8a-4c73-a7b1-cec5bf2fde7b.png)

- IstioCon: https://mp.weixin.qq.com/s/J3ormnpuYH45vbkN_G7mvg

**Comment by hsluoyz** [comment]
@ComradeProgrammer

**Comment by ComradeProgrammer** [comment]
https://github.com/istio/istio.io/pull/10860

**Comment by hsluoyz** [comment]
Done
