### ISSUE TITLE
LDAP sync user fail

### ISSUE THREAD

**Issue by adam3asy** [casdoor/casdoor#467]
when I use casdoor link LDAP server to sync users,  LDAP server connect success, but sync user fail,  /api/get-ldap-user  return response
`{
  "status": "error",
  "msg": "no result",
  "sub": "",
  "name": "",
  "data": null,
  "data2": null
}`

I don't know how to fix, can any help supply to me , thks

**Comment by seriouszyx** [comment]
@adam3asy Sorry for waiting. As the [doc](https://casdoor.org/docs/ldap/overview#detail-about-casdoor-ldap-synchroniztion-mechanism) says, Casdoor's synchronization only supports those LDAP users which are a subclass of _posixAccount_. So you can check the user in your LDAP server.
