### ISSUE TITLE
Retrieve password error: unknown authentication type (not password or provider)

### ISSUE THREAD

**Issue by Kalinin-Andrey** [casdoor/casdoor#483]
Hello, everyone!

I am just a beginner with casdoor.
I am trying to test a retrieve password, but received this error:
```
unknown authentication type (not password or provider), form = {
	"type": "login",
	"organization": "org",
	"username": "",
	"password": "",
	"name": "",
	"email": "",
	"phone": "",
	"affiliation": "",
	"idCard": "",
	"region": "",
	"application": "socbazar",
	"provider": "",
	"code": "38316",
	"state": "",
	"redirectUri": "",
	"method": "",
	"emailCode": "",
	"phoneCode": "",
	"phonePrefix": "7",
	"autoSignin": false,
	"relayState": "",
	"samlResponse": ""
}
```
The username is found and the email substituted in the form field, but they are not sent to the server.
Email provider is configured and working.

What I am doing wrong?

**Comment by hsluoyz** [comment]
@Kalinin-Andrey what action are you doing?

See code:

https://github.com/casdoor/casdoor/blob/e1c54744dced5751f1671e0d291df8d17bd5b093/controllers/auth.go#L371

`username` and `provider` in the form cannot be both empty.

**Comment by Kalinin-Andrey** [comment]
@hsluoyz , I use casdoor as standalone service in docker contaner. I don`t change a code.
After sending a confirmation code working ApiController.Login() with original code: https://github.com/casdoor/casdoor/blob/e1c54744dced5751f1671e0d291df8d17bd5b093/controllers/auth.go#L127.

**Comment by Kalinin-Andrey** [comment]
@hsluoyz ,
After sending a confirmation code, goes request /api/login with payload:
```
{
application: "socbazar"
code: "48599"
organization: "org"
phonePrefix: "7"
type: "login"
}
```
https://github.com/casdoor/casdoor/issues/483#:~:text=util.StructToJson(form)))-,username%20and%20provider%20in%20the%20form%20cannot%20be%20both%20empty.,-Author

I understand that, but I don't understand why this is happening.
What can I be doing wrong?

**Comment by Kalinin-Andrey** [comment]
@hsluoyz ,
Case 1: in field `username` (`id="step1_username`) I wrote an email - field `username` (in a request) not empty, all working!
Case 2: in field `username` I wrote an username. In form2 substituted an email in field `id="step2_email"`. Field `username` in request is empty.

**Comment by hsluoyz** [comment]
@Kalinin-Andrey what are you trying to do? What's the goal? The Casdoor public API is guaranteed to be called correctly by Casdoor's own web frontend. If you want to call Casdoor public API by yourself, you need to make sure every passed parameter is correct.

**Comment by Kalinin-Andrey** [comment]
@hsluoyz 
> What's the goal?
> The Casdoor public API is guaranteed to be called correctly by Casdoor's own web frontend. 

This is exactly my goal: use casdoor with its own frontend.
I didn't change anything other than the config.

**Comment by Kalinin-Andrey** [comment]
@hsluoyz ,
I have built an Casdoor container from its own Dockerfile and am trying to use it for my application.
At the current stage, I am unable to recover the password, in the case when you enter the username in the username field (when you enter the email, it works).
I explain as detailed as I can. What else can I say?

**Comment by hsluoyz** [comment]
@Kalinin-Andrey then you should show screenshot and video for the Web UI, not the API calls.

**Comment by hsluoyz** [comment]
@ComradeProgrammer

**Comment by Kalinin-Andrey** [comment]
**My steps**

1. Run containers (db, redis, casdoor and my app).

In docker-compose.yaml:
```
  casdoor:
    build:
      context: ./casdoor
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./conf/casdoor:/conf/
```

2. Setup email provider, organisation and application (socbazar).

3. Signup one user (Andrey) to this application.

4. Try to retrieve password.

	1) go to page "Retrieve password": http://localhost:8000/forget/socbazar
![image](https://user-images.githubusercontent.com/8151806/153208471-da3041fa-0626-4992-a489-5e21e4addef6.png)

	2) click "Next Step"
![image](https://user-images.githubusercontent.com/8151806/153208682-607940b4-37cb-4de4-8c46-c530507d83a0.png)

	3) click "Send Code", enter code and click "Next Step"
	
	Payload:
![image](https://user-images.githubusercontent.com/8151806/153209275-6d59c52a-6fda-4001-8099-828773ba1a28.png)

```
{
application: "socbazar"
code: "74383"
organization: "org"
phonePrefix: "7"
type: "login"
}
```
there is no `username`

	Response:
![image](https://user-images.githubusercontent.com/8151806/153209113-a78add2f-d39d-4527-8b44-68391418a5be.png)

```
{
  "status": "error",
  "msg": "unknown authentication type (not password or provider), form = {\"type\":\"login\",\"organization\":\"org\",\"username\":\"\",\"password\":\"\",\"name\":\"\",\"email\":\"\",\"phone\":\"\",\"affiliation\":\"\",\"idCard\":\"\",\"region\":\"\",\"application\":\"socbazar\",\"provider\":\"\",\"code\":\"74383\",\"state\":\"\",\"redirectUri\":\"\",\"method\":\"\",\"emailCode\":\"\",\"phoneCode\":\"\",\"phonePrefix\":\"7\",\"autoSignin\":false,\"relayState\":\"\",\"samlResponse\":\"\"}",
  "sub": "",
  "name": "",
  "data": null,
  "data2": null
}
```

**Comment by ComradeProgrammer** [comment]
Извините, друг мой (I don't speak Russian)
It's indeed a bug. It will be fixed soon, and will be released soon together with other queued releases.

**Comment by Kalinin-Andrey** [comment]
@ComradeProgrammer ,
Great answer!
I can ask you, when it is fixed, somehow let me know about it. For example, in this thread.
Or write me how to find out about it.
To immediately update the code.
Many thanks!
