### ISSUE TITLE
GUI - add user page, no cancel button?

### ISSUE THREAD

**Issue by jingkang99** [casdoor/casdoor#484]
After click add user, there is no cancel button to cancel the action. if jump to other page, new user is added anyway. similar behavior on other page too.

**Comment by seriouszyx** [comment]
Actually when clicking the _add_ button, the user has been added.

**Comment by hsluoyz** [comment]
@seriouszyx can we modify this behavior?

**Comment by seriouszyx** [comment]
@hsluoyz Yes, I will try to work on it.
