### ISSUE TITLE
https://casdoor.org Cannot open on ipad

### ISSUE THREAD

**Issue by jingkang99** [casdoor/casdoor#485]
Chrome displays blank page

**Comment by Steve0x2a** [comment]
Can you be clear about your browser software and system version? I'm using Safari and Alook on my iPad and they both work fine.

**Comment by hsluoyz** [comment]
@jingkang99 Can you share your User-Agent? You can get it from Google:

![image](https://user-images.githubusercontent.com/3787410/153321661-98edf2e5-37ac-4535-bd14-debe08dfd9b4.png)

**Comment by jingkang99** [comment]
Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/71.0.3578.89 Mobile/14G60 Safari/602.1

**Comment by hsluoyz** [comment]
@jingkang99 I'm afraid your iOS 10.3.3 (and iPad) is too old. I tested with a very old iPad (still newer than yours) and it shows OK:

`
Mozilla/5.0 (iPad; CPU OS 12_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/92.0.4515.90 Mobile/15E148 Safari/604.1
`
