### ISSUE TITLE
OAuth 2.0 device authorization grant support

### ISSUE THREAD

**Issue by nodece** [casdoor/casdoor#489]
### Summary

I tried to use casdoor in our project, but I notice it doesn't support the OAuth 2.0 device authorization, this model is simple and powerful. This is a great feature if the casdoor can support this, see [here](https://oauth.net/2/device-flow/) for this model.

**Comment by Steve0x2a** [comment]
Casdoor supports oidc protocol to access the application, and oidc is based on oauth, you can get the relevant information in this document：https://casdoor.org/docs/how-to-connect/oidc-client/

**Comment by nodece** [comment]
OIDC has multiple auth models, such as implicit-grant-flow, auth-code-flow, device-code-flow. I guess the casdoor can support implicit-grant-flow and auth-code-flow, I haven't tested it, but I tried the device-code-flow, the casdoor doesn't provide the `device_authorization_endpoint` in `.well-known/openid-configuration`.

**Comment by Steve0x2a** [comment]
Oh you're right, casdoor doesn't support device-code-flow yet, do we need to add that? @hsluoyz

**Comment by nodece** [comment]
@Steve0x2a Please update #415.

**Comment by Steve0x2a** [comment]
> @Steve0x2a Please update #415.

@nodece Thank you for your review! But totp we have discussed and feel that we still need to make some major changes, so this pr may not progress in a short time, if we continue to move forward with this pr, I will make changes according to your suggestions, thank you very much.

**Comment by nodece** [comment]
@Steve0x2a Could you share this discussion thread? I want to know this progress.

**Comment by LeonDevLifeLog** [comment]
please assign this issue to me,i am interesting to complete it.

**Comment by hsluoyz** [comment]
Done

**Comment by Bu3a3a** [comment]
Hi! Are there any updates on OAuth 2.0 Device Authorization Grant?
