### ISSUE TITLE
Is there an API method to verify the access token?

### ISSUE THREAD

**Issue by Kalinin-Andrey** [casdoor/casdoor#493]
Hello everyone!

1. Is there an API method to verify the access token?
2. Is there a mechanism for forcibly terminating the access token after a compromise?

Thanx!

**Comment by Steve0x2a** [comment]
1. Casdoor currently does not have a dedicated api to verify the accessToken, you can use the userinfo interface to confirm if the user information is available to determine if the accessToken is still available. You can see the discussion in this issue: https://github.com/casdoor/casdoor/issues/425
2. You can use the delete token api to delete the leaked token, or delete it on the token page, e.g.:https://door.casbin.com/tokens

**Comment by Steve0x2a** [comment]
> this

@hsluoyz OK, I'll work on this.
