### ISSUE TITLE
Support Apache Shiro integration with Casdoor

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#495]
We already have an example project: https://github.com/casdoor/casdoor-spring-boot-shiro-example

Next we can develop a plugin based on: https://shiro.apache.org/integration.html , like the CAS SSO server or Stormpath plugin. Then contribute it to the integration list.

Repo is created at: https://github.com/casdoor/shiro-casdoor

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by seriouszyx** [comment]
Done
![image](https://user-images.githubusercontent.com/33992371/156953345-2b03d171-5803-4d18-995e-f64a183579fc.jpeg)

**Comment by hsluoyz** [comment]
@seriouszyx looks good!
