### ISSUE TITLE
Question: OAuth2 Endpoints for ASP.NET Core Authentication

### ISSUE THREAD

**Issue by ikarstein** [casdoor/casdoor#498]
I'm looking for an example how to connect an ASP.NET Core Web App to Casdoor (All-In-One docker image) for OAuth2 authentication.

I have this code in "startup.cs":

```
        services.AddAuthentication(options =>
        {
            options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        })
        .AddCookie(options =>
        {
            options.LoginPath = "/signin";
            options.LogoutPath = "/signout";
        })
        .AddOAuth("CasdoorLocal", options =>
        {
            options.AuthorizationEndpoint = "http://localhost:8000/login/oauth/authorize/";
            options.TokenEndpoint = "http://localhost:8000/login/oauth/access_token/";
            options.UserInformationEndpoint = "http://localhost:8000/login/oauth/userinfo/";
            options.ClientId = "11111111111111111111";
            options.ClientSecret = "11111111111111111111111111111111111111111111111111111111111111111111";
            options.CallbackPath = "/signin-casdoor";
            options.ClaimsIssuer = "Casdoor";
            options.Scope.Add("email");
            options.Scope.Add("openid");
            options.Scope.Add("profile");
        })
```

I get a login and Casdoor redirects the browser to the callback address. But than I get a "500" status code in ASP.NET Core web app.

I'm not sure this depends on the endpoints. But I'm pretty much sure that the endpoints are not configured correctly.

No documentation about that in the internet. 

Any ideas?

Thank you!

**Comment by Steve0x2a** [comment]
Hi, I think there may be a mistake in the following api address:
1. `TokenEndpoint ` should be `http://localhost:8000/api/login/oauth/access_token`
2. `UserInformationEndpoint` should be `http://localhost:8000/api/userinfo`
3. `ClaimsIssuer` maybe  `iss`, but I'm not sure if this field is the one I'm thinking of.

You can make the above changes, if you still get the error, please keep replying, I will follow up.

**Comment by ikarstein** [comment]
THIS WORKS!! Thank you!
