### ISSUE TITLE
Support password hashing in LDAP

### ISSUE THREAD

**Issue by GhostLee** [casdoor/casdoor#499]
sometime we don't save plaintext password in LDAP Server, so support password hashing is very useful, input a plaintext password, convert it into hashed password and compare with LDAP password field output the check result.

**Comment by GhostLee** [comment]
and the attribute should be configurated

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by seriouszyx** [comment]
@GhostLee We will add support for multiple password types as soon as possible. For configurable attributes, we plan to do this during the implementation of LDAP in the syncers.

**Comment by seriouszyx** [comment]
@GhostLee I found that there is no relationship between the password type of Casdoor and the LDAP server. I sent the password entered by the user to the LDAP server using a `bind` request and the authentication all passed regardless of the LDAP password type. On the contrary, if I encrypt the password in Casdoor, it will not pass.

> My environment is Apache Directory Studio 2.0.0.

**Comment by hsluoyz** [comment]
@GhostLee Casdoor always sends plain password to your LDAP server via LDAP protocol. So it's your LDAP server to decide whether to hash the password. It's not a Casdoor issue.
