### ISSUE TITLE
Fix state too long error for WeChat login in WeChat built-in browser

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#504]
Env: WeChat PC version, with WeChat built-in browser enabled

See: https://forum.casbin.com/

https://user-images.githubusercontent.com/3787410/154639187-5dda2634-f02d-4a84-b340-df71966b145b.mp4

**Comment by seriouszyx** [comment]
Also, when I logged in to https://door.casdoor.com/ using wechat, I got the following error.

![image](https://user-images.githubusercontent.com/33992371/154648942-d4882781-ff16-47a2-a5b8-4213c9021f86.png)

**Comment by hsluoyz** [comment]
@fabian4

**Comment by hsluoyz** [comment]
@RyaoChengfeng

**Comment by hsluoyz** [comment]
@qianxi0410

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/94b6eb803da1c476f47a8b857a4493a19efac662
