### ISSUE TITLE
The application parameters in login url will be lost when back form Signup Page

### ISSUE THREAD

**Issue by FishMeng811** [casdoor/casdoor#507]
Steps:
step 1: Redirect to Casdoor Sign In page, now parameters(ex. state/client_id) in Login Url.
step 2: Click Sign Up button into Sign Up page.
step 3: Then Click Sign In button back to Sgin In Page, now bug shows : parameters in Url lost!

**Comment by hsluoyz** [comment]
@seriouszyx
