### ISSUE TITLE
Optimization of wechat providers

### ISSUE THREAD

**Issue by 1307super** [casdoor/casdoor#511]
There are two problems with wechat authorized login:
1. If there is unionid, unionid will be used directly; otherwise, openid will be used; This will have a problem, for example, WeChat has a lot of small programs, official account numbers on the same development platform, but their openid are different, but calling related interfaces need openid, and can the third party information related to OAuth exist in another table. When logging in or registering, query through the provider and unioid or openid
![image](https://user-images.githubusercontent.com/35326304/155706388-e7b36958-e2e2-46b6-8a99-bf7b91b9bfd0.png)

2. The wechat interface is quite special, and the access_token has a valid period, and the old one will become invalid after applying for a new one. However, casdoor does not provide other wechat related interfaces, so the business system needs to develop it by itself. At this time, there will be an access problem The failure of token leads to the failure of interface call. Casdoor can provide an interface to obtain access_token (because there is a limit on the number of times to obtain access_token every day, it is generally cached and re obtained in the Interim)

**Comment by hsluoyz** [comment]
@1307super it is supported. See: https://casdoor.org/docs/provider/oauth/Wechat
