### ISSUE TITLE
response_type bug

### ISSUE THREAD

**Issue by LeonDevLifeLog** [casdoor/casdoor#514]
`.well-known/openid-configuration` API said response_type support `id_token`
![微信截图_20220226143131](https://user-images.githubusercontent.com/28891919/155832571-171a751c-7635-4085-85f1-5c5ed6918417.png)
but actually not support.
![微信截图_20220226143221](https://user-images.githubusercontent.com/28891919/155832611-4d4a990f-3b9d-4d75-ade3-28e605fae21f.png)

**Comment by LeonDevLifeLog** [comment]
> occured when set casdoor as huawei iam ids provider. ref: https://support.huaweicloud.com/usermanual-iam/iam_08_0010.html

huawei ima only support `id_token` option

![微信截图_20220226144119](https://user-images.githubusercontent.com/28891919/155833074-3e400288-9a07-475e-b290-57f5592ec7e7.png)

**Comment by Steve0x2a** [comment]
Yes, currently id_token can only be obtained at the access_token endpoint, and I will support this method as soon as possible with response_type=id_token.

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casdoor/casdoor/pull/534
