### ISSUE TITLE
support more `response_mode` options for Huawei IAM

### ISSUE THREAD

**Issue by LeonDevLifeLog** [casdoor/casdoor#515]
## casdoor only support`login`,`code`,`link`

![微信截图_20220226143941](https://user-images.githubusercontent.com/28891919/155832836-d239285c-13d0-423e-94c3-6a69eddc4e58.png)

## but huawei iam only support `fragment`,`form_post` options

![微信截图_20220226144053](https://user-images.githubusercontent.com/28891919/155832986-361715bb-4716-4db2-9b9d-fbeec1f842df.png)

## please support `fragment` or `form_post` options 😃

**Comment by hsluoyz** [comment]
@Steve0x2a

**Comment by LeonDevLifeLog** [comment]
# error info:
![image](https://user-images.githubusercontent.com/28891919/156274708-f04cc51e-e774-44ca-86e0-c904089b6277.png)
# login is successful
![image](https://user-images.githubusercontent.com/28891919/156274834-d90fa2d3-8585-4d87-9179-d67cd8b54f68.png)
# but it lost query parameters when redirect 
![image](https://user-images.githubusercontent.com/28891919/156274996-980588ee-cac3-488b-8138-31c7e6709680.png)

**Comment by LeonDevLifeLog** [comment]
# may be we do not flow the OAuth 2.0 specs.
## this is implementation by keycloak.
![image](https://user-images.githubusercontent.com/28891919/156276201-6f817f5d-689e-4993-a957-a3f1c3f6b280.png)

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casdoor/casdoor/pull/534
