### ISSUE TITLE
signup webhook callback post null "extendedUser" data

### ISSUE THREAD

**Issue by bobhu2k** [casdoor/casdoor#517]
- 1、use casbin/casdoor:[v1.22.0  docker image](https://hub.docker.com/r/casbin/casdoor/tags)

- 2、new organization

  

> <img width="1313" alt="image" src="https://user-images.githubusercontent.com/8317400/155937636-d98f8e70-5175-46c0-b864-ad81ff48f6fb.png">

- 3、new application

> <img width="1359" alt="image" src="https://user-images.githubusercontent.com/8317400/155937749-b7b23a6e-f57d-488e-9862-a52b289988c6.png">

- 4、new webhook

  - 4.1、in login webhook  extendedUser is right

  - 4.2、in signup  webhook  extendeduser is null 

> <img width="1004" alt="image" src="https://user-images.githubusercontent.com/8317400/155937864-365e6402-9be3-49cf-bdf6-9529492df14b.png">

> <img width="423" alt="image" src="https://user-images.githubusercontent.com/8317400/155937957-1ca85107-d868-4d19-b21a-f5c493e5173b.png">

- 5、frontend  web submit register data
  

> <img width="455" alt="image" src="https://user-images.githubusercontent.com/8317400/155939688-f6716f71-c35c-4ec8-b4e0-d0a42a442518.png">

<img width="1796" alt="image" src="https://user-images.githubusercontent.com/8317400/155939913-402e7fba-bcd7-49c4-819b-1fe6622eebaa.png">

**Comment by hsluoyz** [comment]
@Steve0x2a @seriouszyx
