### ISSUE TITLE
client_secret should not be required in path "/login/oauth/access_token"

### ISSUE THREAD

**Issue by xiaobeiswift** [casdoor/casdoor#524]
Casdoor supports the [Proof Key for Code Exchange](https://tools.ietf.org/html/rfc7636) (PKCE) protocol to make the app flow more secure.
 But the “public” app (a mobile or single-page app) client cannot keep the client_secret confidential.
 Now,the query string parameter "client_secret" is required in path "/login/oauth/access_token". It is recommended to design it as optional

**Comment by Steve0x2a** [comment]
I will work on this.
