### ISSUE TITLE
After updating the user, how to get a token with these updates?

### ISSUE THREAD

**Issue by Kalinin-Andrey** [casdoor/casdoor#529]
Hi all!

I have a small question on using sdk (golang).

After updating the user, how to get a token with these updates?

Steps:

1. Get token
```
token, err := auth.GetOAuthToken(code, state)
```
2. Parse JWT token
```
jwtClaims, err := auth.ParseJwtToken(token.AccessToken)
```
3. Change `jwtClaims.User`

4. Update user
```
ok, err := auth.UpdateUserForColumns(&jwtClaims.User, []string{"properties"})
```
5. How to get AccessToken string (JWT token) with an updated user?

**Comment by Kalinin-Andrey** [comment]
If I try to get token with the same code
```
token, err := auth.GetOAuthToken(code, state)
```
I recieve an error: "authorization code has been used"

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by seriouszyx** [comment]
@Kalinin-Andrey Hi, when you first call `auth.GetOAuthToken(code, state)`, the authorization code is already marked as used. This means that the authorization code can only be used once. 

If you want to get the updated user, there are currently two ways:
1. Call `get-account` API with `accessToken` param to get the latest user.
2. Refresh the token via `/login/oauth/refresh_token` API.

**Comment by Kalinin-Andrey** [comment]
@seriouszyx,
Please tell me what these parameters are and where to get them from?
```
grant_type
scope
```

**Comment by seriouszyx** [comment]
@Kalinin-Andrey They are the standard parameters of the OAuth 2.0 protocol. The value of `grant_type` depends on what API you call, such as `authorization_code` or `refresh_token`. And the value of `scope` can be `read`.

**Comment by Kalinin-Andrey** [comment]
@seriouszyx,
There is no valid value like `refresh_token`.
![image](https://user-images.githubusercontent.com/8151806/163593472-3e7dabeb-4393-450b-a9d6-7d41ff8f0147.png)

**Comment by Kalinin-Andrey** [comment]
@hsluoyz,
probably, need to add `refresh_token` `grand_type` to the application settings in Casdoor UI?

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by Kalinin-Andrey** [comment]
@hsluoyz @seriouszyx ,
Each time the user updates, the token needs to be refreshed in order to have a jwt token with up-to-date information.
I put the `refresh_token` directly in DB and everything work fine. But in production I would like to do this through the interface.

Please, add the `refresh_token` to the application settings interface (to the list of values "Grand types").

Thank you very match!

**Comment by hsluoyz** [comment]
@Kalinin-Andrey can you make a PR to fix it?

**Comment by Kalinin-Andrey** [comment]
@hsluoyz ,
can it be fixed on backend side?

**Comment by Kalinin-Andrey** [comment]
@hsluoyz ,
Looks like I found something similar..
Yes, I will try..

**Comment by Kalinin-Andrey** [comment]
@hsluoyz 
It seems that everything turned out to be simple and one line was enough..
https://github.com/casdoor/casdoor/pull/737
