### ISSUE TITLE
Can one system log in and other systems log in automatically

### ISSUE THREAD

**Issue by hanpenggit** [casdoor/casdoor#530]
For example, there are three systems A, B and C，After the user successfully logs in to system A，system B and system C also log in automatically

**Comment by MayankMittal1** [comment]
@hanpenggit i can't fully understand what you mean, could you please elaborate

**Comment by hanpenggit** [comment]
for two systems: A and B, when the user log in A by sso, change the website to system B, the user can auto log in B without redirecting to sso

**Comment by hsluoyz** [comment]
@hanpenggit  See: https://casdoor.org/docs/how-to-connect/single-sign-on
