### ISSUE TITLE
Improve frontend static asset files size

### ISSUE THREAD

**Issue by zhongjixiuxing** [casdoor/casdoor#541]
Home page first time access, then will loading big static asset files, has a very bad experience

![50333D21A427E2137630E20FF129DA1A](https://user-images.githubusercontent.com/8935235/157065481-02be6691-f8c6-47e1-9e58-641707075bec.jpg)

**Comment by hsluoyz** [comment]
@zhongjixiuxing how do we fix it?

**Comment by hsluoyz** [comment]
Unresolvable
