### ISSUE TITLE
The MySQL default database "casdoor" cannot be automatically created when running for the first time

### ISSUE THREAD

**Issue by halozhy** [casdoor/casdoor#546]
version: v1.27.6

I started the program by following the README document of this repository, but the [simple configuration
 part](https://github.com/casdoor/casdoor#simple-configuration) does not mention that the database needs to be created on the first run.

The [official website documentation](https://casdoor.org/docs/basic/server-installation#configuration) also says that _a MySQL database named: casdoor, will create it if not existed_. But when I actually run it, I find that the program reports an error: 

![image](https://user-images.githubusercontent.com/56069009/157457618-13f5b1f9-ea2c-4c35-a9e3-8b2660fff3f7.png)

After I manually created the database "casdoor" , the program worked fine.

**Comment by leo220yuyaodog** [comment]
I also meet the problem. I solve it by a parameter in main.go ,it maybe defalut 'false'
![image](https://user-images.githubusercontent.com/71440988/157563923-87e32efe-24e3-47c8-b0e6-f6dedbab265c.png)
