### ISSUE TITLE
UI bug after switching to English

### ISSUE THREAD

**Issue by lchjczw** [casdoor/casdoor#548]

**Comment by lchjczw** [comment]
this is front bug

**Comment by hsluoyz** [comment]
@lchjczw can you provide a video about this error?

**Comment by lchjczw** [comment]
![1646883228073](https://user-images.githubusercontent.com/12480676/157583369-2a9d5b86-24c3-4eec-8422-f3d1dd33b194.jpg)
点击英文切换到英文后 ，页面就变成了下面的样子
![1646883244253](https://user-images.githubusercontent.com/12480676/157583378-fc2ae0a4-cf09-4de8-8cca-e68470cfae3e.jpg)

这是前端bug

**Comment by hsluoyz** [comment]
@Nekotoxin

**Comment by Nekotoxin** [comment]
> ![1646883228073](https://user-images.githubusercontent.com/12480676/157583369-2a9d5b86-24c3-4eec-8422-f3d1dd33b194.jpg) 点击英文切换到英文后 ，页面就变成了下面的样子 ![1646883244253](https://user-images.githubusercontent.com/12480676/157583378-fc2ae0a4-cf09-4de8-8cca-e68470cfae3e.jpg)
> 
> 这是前端bug

can you provide your version of casdoor and browser? I have a test, and the latest casdoor is work well on chrome edge and firefox

**Comment by lchjczw** [comment]
I test it on the online demo:
https://door.casdoor.com/

my device 
`MacBook Pro（14英寸，2021年）`
`Apple M1 Pro`

**Comment by lchjczw** [comment]
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/12480676/157644143-5dea4907-13b7-4540-934f-1ab0f6ca68e2.png">
@Nekotoxin

**Comment by Nekotoxin** [comment]
@hsluoyz does the online demo update to the latest version?

**Comment by lchjczw** [comment]
I don't know, this is your online demo,you can browse it

https://door.casdoor.com/

**Comment by hsluoyz** [comment]
@lchjczw @Nekotoxin already updated the demo site, please try again

**Comment by sloorush** [comment]
I cannot reproduce it on brave browser on a 15.6-inch screen. The nav items go into a kebab menu on smaller screen widths. This issue can probably be closed.

**Comment by lchjczw** [comment]
I think you shoud change `Syncers Certs Swagger` to `···`  not 
<img width="319" alt="image" src="https://user-images.githubusercontent.com/12480676/158297391-a4a8fa4c-2967-4910-b96f-4ccaad322aaa.png">
to `···`

**Comment by lchjczw** [comment]
I change the window size 

<img width="870" alt="image" src="https://user-images.githubusercontent.com/12480676/158297973-f92c724c-d86d-4baf-8bd4-dd19ca3be9c6.png">

you can change the window size to see the the effect

**Comment by hsluoyz** [comment]
@Nekotoxin plz fix the height:

![Y4H67L EW~}C%JFNT _BFMT](https://user-images.githubusercontent.com/3787410/158337305-79b18f96-3044-4f46-87b6-9af733bc2dbd.png)
