### ISSUE TITLE
Structuring the files in web/src directory 

### ISSUE THREAD

**Issue by srrathi** [casdoor/casdoor#549]
### Problem/Issue
There are many files present in web/src directory which makes it look very unorganised and difficult to figure out in which file a particular thing on which I have to work belong. Large projects structure their files and folder by making sub folders in which all the files relevant to that page or feature reside.

Currently the files looks like this in a single folder

![Screenshot from 2022-03-10 06-03-05](https://user-images.githubusercontent.com/57089237/157563823-7add6aea-5fd5-47dc-91a6-e337d5857ebc.png)

### Solution
we can structure the web/src directory by making sub folders in it according to the pages we are routing on in frontend. It will also make easy for other developers to work on any particular feature or bug. We can name the sub folders as per below pages/feature name and group files related to that feature in it.

![Screenshot from 2022-03-10 06-11-01](https://user-images.githubusercontent.com/57089237/157564118-3ce2a775-22ae-4d4d-9929-34a8c84a584c.png)

### If you find my issue and its solution valid, please let me know I'll be more than happy to contribute in casdoor  by resolving this issue.

**Comment by srrathi** [comment]
@hsluoyz Is there any other information needed to clarify my issue and its solution ? If there's something else which I have to mention please let me know.

**Comment by hsluoyz** [comment]
@srrathi plz work on existing open issues. We don't recommend non-real-users to create and resolve their own issues.
