### ISSUE TITLE
The forget page does not hidden the phone number and email address

### ISSUE THREAD

**Issue by epis2048** [casdoor/casdoor#554]
As shown in the images, although the frontend hides the mobile phone number and email address in the forget page, the data returned by the background does not.
![image](https://user-images.githubusercontent.com/13732503/157809779-cf4ac2ae-6d7e-4cdf-941a-6618554a302e.png)

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by seriouszyx** [comment]
roger that
