### ISSUE TITLE
Make a Casdoor SDK/example for WeChat mini programs

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#556]

**Comment by hsluoyz** [comment]
@shimmery

**Comment by mojerro** [comment]
hello, I hope to know which route is for wechat mini programs, where the login path is different from wechat web.

**Comment by hsluoyz** [comment]
@Steve0x2a

**Comment by hsluoyz** [comment]
Done at: https://github.com/casdoor/casdoor-wechat-miniprogram-example

**Comment by zuohuadong** [comment]
@hsluoyz It's so exciting.
But I want localized Prisma, not Prisma Cloud. Also, can I add appllographql or graphql API?
