### ISSUE TITLE
Use random state to mitigate CSRF attacks

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#564]
See: https://github.com/casdoor/casdoor/issues/422#issuecomment-1066095439 and https://github.com/jenkins-infra/repository-permissions-updater/issues/2379#issuecomment-1054046999

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by Steve0x2a** [comment]
When cadoor is an idp, it can accept random states, and casdoor will return the states provided by the sp as is. So I think currently casdoor does not need to modify the state policy on apisix, it just needs to generate random states on the apisix plugin.

**Comment by Abingcbc** [comment]
The solution is roughly to generate a random state in SDK (Java, Go...), then Casdoor receives it and just passes it back as part of the response. Is this OK?

**Comment by hsluoyz** [comment]
> When cadoor is an idp, it can accept random state, and casdoor will return the state provided by the sp as is. So I think currently casdoor does not need to modify the state policy, it just needs to generate random state on the apisix plugin.

@Steve0x2a you are right. @ComradeProgrammer plz just update the plugin code to fix this. Casdoor doesn't need to be updated for this part.

> The solution is roughly to generate a random state in SDK (Java, Go...), then Casdoor receives it and just passes it back as part of the response. Is this OK?

@Abingcbc for Casdoor as IdP, we can first update the code in: https://github.com/casdoor/casdoor-js-sdk

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casdoor/casdoor-js-sdk/pull/31
