### ISSUE TITLE
Support JWT token custom payload properties

### ISSUE THREAD

**Issue by zhongjixiuxing** [casdoor/casdoor#576]
## As casdoor default jwt token it too big, has possible to support custom JWT token payload properties to reduct size?

**Comment by hsluoyz** [comment]
@zhongjixiuxing `JWT-Empty` token format can be used: https://casdoor.org/docs/integration/apisix#step2-configure-casdoor-application

**Comment by zhongjixiuxing** [comment]
> @zhongjixiuxing `JWT-Empty` token format can be used: https://casdoor.org/docs/integration/apisix#step2-configure-casdoor-application

Good Jobs.
