### ISSUE TITLE
default signup_application value "built-in-app" in user table different with the default application name in table application lead to an error when click the application name in user page

### ISSUE THREAD

**Issue by hawckodere** [casdoor/casdoor#579]
default signup_application value "built-in-app" in user table different with the default application name in table application lead to an error when click the application name in user page.
![image](https://user-images.githubusercontent.com/1499168/158955105-c1efb85d-69e6-431b-9cc0-3653e8f2e887.png)

![image](https://user-images.githubusercontent.com/1499168/158956171-a4ff511a-63e2-45d6-a73d-01b593ff53d2.png)
the default signup_application value of default user in user table maybe "app-built-in".

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casdoor/casdoor/pull/831
