### ISSUE TITLE
[suggestion] the third-party account information should be removed from the user table, which is not conducive to later expansion

### ISSUE THREAD

**Issue by hanrea** [casdoor/casdoor#582]
The associated plug-in information should be split into a new table as the account table
https://github.com/casdoor/casdoor/blob/865a65d399a88ef0423dc6305e6911533abc8b43/object/user.go#L74

If the product goes in the direction of OAuth, more and more OAuth plug-ins will be accumulated, and the single table is certainly not applicable.

**Comment by hsluoyz** [comment]
@hanrea plz change to English

![image](https://user-images.githubusercontent.com/3787410/159106060-38047c72-ab35-45d6-b19e-6fa18a331ccf.png)

**Comment by hanrea** [comment]
> @hanrea plz change to English
> 
> ![image](https://user-images.githubusercontent.com/3787410/159106060-38047c72-ab35-45d6-b19e-6fa18a331ccf.png)

Translation complete!TKS!

**Comment by hsluoyz** [comment]
@hanrea multiple tables are too complicated. Single table is enough to use for now. Won't fix.
