### ISSUE TITLE
Login limit problem

### ISSUE THREAD

**Issue by epis2048** [casdoor/casdoor#584]
I entered the wrong user name and password in the login page and did not encounter the login times limit, which may be the script burst password.

I would like to have the option to lock the account for some minutes or enable captcha after exceeding the limit.

**Comment by hsluoyz** [comment]
@uivid64

**Comment by uivid64** [comment]
Is it better to limit the number of logins to 5 or 10? 
If the number of logins exceeds the limit, the account will be locked with the password and only the verification code will be allowed to log in.
Is this possible to meet this requirement?

**Comment by T-baby** [comment]
I feel that it may be better to go through the CAPTCHA when logging in.

**Comment by hsluoyz** [comment]
@epis2048 this has been finished, plz try it

![image](https://user-images.githubusercontent.com/3787410/185198925-73dc72a6-2431-4086-a6e2-fb8555d1c84e.png)
