### ISSUE TITLE
The certs page is displayed incorrectly

### ISSUE THREAD

**Issue by epis2048** [casdoor/casdoor#585]
The contents of the public key field are actually the contents of the certificate, not the public key.

Consider changing the name of the field to "certificate" or the contents of the field to the public key.

The Python SDK recently use the certificate to generate public key automaticly, but the PHP SDK still need to convert manually.

**Comment by Steve0x2a** [comment]
I agree with this suggestion, people who don't know this aspect may confuse certificates and public keys.

**Comment by hsluoyz** [comment]
> The Python SDK recently use the certificate to generate public key automaticly, but the PHP SDK still need to convert manually.

@epis2048 can you create an issue at: https://github.com/casdoor/casdoor-php-sdk/issues ?

**Comment by epis2048** [comment]
> > The Python SDK recently use the certificate to generate public key automaticly, but the PHP SDK still need to convert manually.
> 
> @epis2048 can you create an issue at: https://github.com/casdoor/casdoor-php-sdk/issues ?

I think the problem comes from the casdoor. Just like @Steve0x2a 's saying that people who don't know this aspect may confuse certificates and public keys. The casdoor should tell its users that that's certificates not public keys.
![image](https://user-images.githubusercontent.com/13732503/159122698-9b803216-9195-4ec8-8551-21bf165cb7b0.png)

**Comment by epis2048** [comment]
Maybe the SDK can convert it automaticly, but I think the casdoor's field name should be more accurate.

**Comment by hsluoyz** [comment]
@epis2048 yes, I got your question for cert name. We will change it. I mean you can create an issue for PHP SDK.

**Comment by epis2048** [comment]
![image](https://user-images.githubusercontent.com/13732503/159122996-d47a758e-9b40-4b11-b09c-7b67f62a72cc.png)
Like this pic, nearly all SDKs field name is public key. So I think the best efforts is change the content showing in casdoor, not nearly every SDK's code and variable name. Although, it's just my opinion. So, I don't think I should create an issue for PHP SDK. If so, Every SDK(except python) need an issue.

**Comment by hsluoyz** [comment]
@epis2048 if the content is changed, how to change the code logic?

**Comment by epis2048** [comment]
> @epis2048 if the content is changed, how to change the code logic?

Every time visit the cert detail page, convert the certificate to public key. (The result is: DB still store the certificate and the front end show the public key)
I don't know the cost of each conversion, but I don't think the page needs to be visited very often, and a bit slower at a time won't slow the system down overall. Conversion operations can also be done by JS if possible.

**Comment by hsluoyz** [comment]
@epis2048 I agreed to change the "Public key" wording into "Certificate", can you make PRs to change the Casdoor server code and also the possible SDKs you use?

**Comment by FoeverA0** [comment]
Is anyone working on this issue？ maybe I can try to resolve this problem.

**Comment by hsluoyz** [comment]
@FoeverA0 plz work on it

**Comment by FoeverA0** [comment]
#894
