### ISSUE TITLE
Recommend that users of any organization be allowed to log in in the built-in application

### ISSUE THREAD

**Issue by epis2048** [casdoor/casdoor#586]
When attempting to log in to an account of another organization (like organization A) in the Built-in application, A message is displayed indicating that the account does not exist. However, in fact, after logging in to the account of Organization A through the application of Organization A, accessing the built-in application again will automatically log in to CasDoor system, and you can only modify your own account information.

In fact, we want every user to be able to directly log into CasDoor and modify their personal information (like password). Rather than logging into a different system and then automatically logging into the CasDoor app.

**Comment by hsluoyz** [comment]
@epis2048 this is a good idea. But how to specify the organization in the login page? Because we can have the same usernames for different organizations.

**Comment by epis2048** [comment]
> @epis2048 this is a good idea. But how to specify the organization in the login page? Because we can have the same usernames for different organizations.

According to the password? Different users usually have different passwords. The pair of username and password can point to a specific person.
If both users have same passwords, then tell them they should login to their app first.

**Comment by hsluoyz** [comment]
@Steve0x2a @seriouszyx @Abingcbc @ComradeProgrammer any comments?

**Comment by MayankMittal1** [comment]
we could also have a searchable dropdown on the casdoor login page so the user can select the application he wants to login, the preselected option could be default (built-in app).

**Comment by epis2048** [comment]
@MayankMittal1 I don't think it's a good idea. Because two users with same username and password may not be one person. The best efforts is do not let user know who is using the same password. If a dropdown is provided, then a user may login to another org's app whose account doesn't belonging to him/her.

**Comment by epis2048** [comment]
@MayankMittal1 I'm sorry that I misunderstand your idea. I mistakenly thought that the drop-down box appeared after entering the user name and password. If the first entry in the login form is a drop-down box, then I think this idea is ok. However, organization names should be entered by the user (at least some of them), and organization names in the system should not be presented to the user.

**Comment by MayankMittal1** [comment]
@epis2048 but do the users know the organisation that they are registered? or only the application?

**Comment by hsluoyz** [comment]
We should not make the organization list public. So we don't need to work on this issue.
