### ISSUE TITLE
Support multiple-valued response type

### ISSUE THREAD

**Issue by sagilio** [casdoor/casdoor#609]
Support `code token`, `code id_token`, `id_token token`, `code id_token token` and `none`
https://github.com/casdoor/casdoor/blob/d0952ae908b63faea3c6938952668552ea8662f4/object/token.go#L226-L228
ref:
https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#Combinations

**Comment by hsluoyz** [comment]
@sagilio which OAuth/OIDC client uses this feature?

**Comment by hsluoyz** [comment]
Already supported now
