### ISSUE TITLE
Flags should be set to prevent duplicate initialization.

### ISSUE THREAD

**Issue by dextercai** [casdoor/casdoor#629]
It is unexpected to initialize the database directly when container restart or application restart. It may be a coding mistake, because the flag `createDatabase` was designed. 
Unauthorized access also will be caused by using `admin, 123` after restart, which introduces **security risks**.

I will submit a pull requests to fix it later.

**Comment by hsluoyz** [comment]
@dextercai plz make a PR

**Comment by hsluoyz** [comment]
@dextercai it just injects some example data for first-time use, does it harm your service?

**Comment by dextercai** [comment]
But the service should not injects a full-admin user after each container or application restart.

**Comment by dextercai** [comment]
Otherwise, it should be clearly pointed out in the document that when the createDatabase parameter is not specified, the restart of the container or application will still cause the insertion of sample data, especially a high-level admin user.

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casdoor/casdoor/commit/7a95b9c1d53f45fb0a938428c105f3524222c0f1
