### ISSUE TITLE
Support configurable captcha in user flows

### ISSUE THREAD

**Issue by ederparaiso** [casdoor/casdoor#632]
Is there any plans to support configurable captcha in user flows? For example, enable/disable captcha verification in Register, Login, Forget password flows?
In my use case, we expect to use captcha in Login flow (if I'm not mistake, currently captcha verification exists only in Register flow). Thus, due to end to end tests, it would be nice if captcha could be enabled/disabled as a config parameter.

**Comment by nomeguy** [comment]
We can provide a type of provider called captcha provider. It can support different implementations like our built-in captcha provider (https://github.com/casdoor/casdoor/blob/db37f53d6c40519e11f43dff25fe2a723cc2ff80/object/captcha.go), or use the services from cloud providers like:

- reCAPTCHA: https://www.google.com/recaptcha/about/
- Alibaba: https://help.aliyun.com/product/28308.html
- NetEase: https://dun.163.com/product/captcha
- hCaptcha: https://www.hcaptcha.com/
- GeeTest: https://www.geetest.com/

However, integrating with so many vendors take a lot of efforts. Better if we can find a Golang wrapper for major captcha services like the one for .NET: https://github.com/openbullet/CaptchaSharp
