### ISSUE TITLE
Bug: Can't obtain an access_token with curl

### ISSUE THREAD

**Issue by tetra12** [casdoor/casdoor#635]
I have been following [this](https://casdoor.org/docs/how-to-connect/access_token) to obtain an `access_token` with `curl`. However,  `grant_type` == `password` || `grant_type` == `client_credentials` won't work for me.

The only way to get an `access_token` is to craft an OIDC code link and manually copy-paste to browser. 
This won't let me to control/withdraw/expire/remove the issued `access_token` and won't provide a `refresh_token`.

The only way to remove the token is from the Casdoor Admin GUI, which may not be the proper way for us. 

More elaboration on this [here](https://github.com/casdoor/casdoor-go-sdk/issues/8#issuecomment-1084591008).

Version: casbin/casdoor-all-in-one:v1.33.0

**Comment by Steve0x2a** [comment]
I tried to get the token with the following code and it worked, you can try it and give feedback, I will keep following up.
```bash
curl  'http://localhost:8000/api/login/oauth/access_token' -d 'grant_type=authorization_code&client_id=c58c570b63c9bdbfe00c&client_secret=deabbc5717262b162c2b7235bc32496b05549e87&code=4aa380be817bd35ca289'
```

**Comment by tetra12** [comment]
@Steve0x2a 
Thanks for a prompt response. Few points to note:

1. You are using an `authorization_code` here. As I stated here, it works when I handcraft the Auth Code URL and paste it into the browser. When you craft that URL and paste it into the browser, `casdoor` opens an SSO login page and redirects with the OIDC Code to the redirect URI. 

This method doesn't require `curl`, since
- `oidc code` can be exchanged for `access_token` only once
- `casdoor` already issues an access token and it can be accessed by the `admin` user

2. Here''s what I have for `password`

passID.json
```json
{
  "grant_type": "password",
  "client_id": "4fd47f868b2e68aa715e",
  "client_secret": "61b789afdeb66f8ba6ff8037837ac29a1a61bb6a",
  "username": "bku",
  "password": "123456"
}
```
`curl -v -d passID.json 127.0.0.1:8000/api/login/oauth/access_token` yields the following:
```bash
{
  "access_token": "error: invalid client_id",
  "id_token": "",
  "refresh_token": "",
  "token_type": "",
  "expires_in": 0,
  "scope": ""
* Connection #0 to host 127.0.0.1 left intact
}%   
```

3. Here's what I have for `client_credentials`:

clientID.json
```json
{
  "grant_type": "client_credentials",
  "client_id": "4fd47f868b2e68aa715e",
  "client_secret": "61b789afdeb66f8ba6ff8037837ac29a1a61bb6a"
}
```
`curl -v -d clientID.json 127.0.0.1:8000/api/login/oauth/access_token` yields the following:
```bash
{
  "access_token": "error: invalid client_id",
  "id_token": "",
  "refresh_token": "",
  "token_type": "",
  "expires_in": 0,
  "scope": ""
* Connection #0 to host 127.0.0.1 left intact
}%   
```

**Comment by Steve0x2a** [comment]
@tetra12 maybe you can try：
```
curl  'http://localhost:8000/api/login/oauth/access_token' -d'grant_type=password&client_id=c58c570b63c9bdbfe00c&client_secret=deabbc5717262b162c2b7235bc32496b05549e87&username=admin&password=123'
```

It seems that the data sent with json cannot be read in the form, so casdoor cannot read the sent data.
