### ISSUE TITLE
Bug: fail to process input JSON for resource owner requests

### ISSUE THREAD

**Issue by tetra12** [casdoor/casdoor#637]
Following [this](https://casdoor.org/docs/how-to-connect/access_token#client-credentials-grant), I'd like to issue an `access_token` with `curl`. I wanna use `grant_type == client_credentials` and `grant_type == password`. Both work for inlined `curl` requests whith all params pasted in the `curl` request. 

However, neither works for `curl` requests with JSON input parameters. 

clientID.json
```json
{
    "grant_type": "client_credentials",
     "client_id": "4fd47f868b2e68aa715e",
     "client_secret": "61b789afdeb66f8ba6ff8037837ac29a1a61bb6a"
}
```

`curl -v -d clientID.json 127.0.0.1:8000/api/login/oauth/access_token`

Response: 200 with an eror
```bash
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 143
< Content-Type: application/json; charset=utf-8
< Server: beegoServer:1.12.3
< Set-Cookie: casdoor_session_id=c0f9ff61fb3d06e23a633cc0caf52133; Path=/; Expires=Sun, 01 May 2022 09:15:54 GMT; Max-Age=2592000; HttpOnly
< Date: Fri, 01 Apr 2022 09:15:54 GMT
< 
{
  "access_token": "error: invalid client_id",
  "id_token": "",
  "refresh_token": "",
  "token_type": "",
  "expires_in": 0,
  "scope": ""
* Connection #0 to host 127.0.0.1 left intact
}% 
```

NOTE
If you do NOT intend to process JSON as input (which is a bad idea), you should at least return 400 Bad Request.

As a good practice, JSON inputs should be supported.

`Casdoor v1.33.0`

**Comment by hsluoyz** [comment]
@Steve0x2a

**Comment by tetra12** [comment]
@hsluoyz 

1. I'm not sure about your last message. I see a POST /api/login/oauth/access_token in your public Swagger
2. I provided an example with JSON body in a POST request. That would be a normal use case for all DevOps engineers and CI scripts. If you do not intend to support this at this point, return 400 at least. Now I'm getting 200 with an error. Confusing !

**Comment by hsluoyz** [comment]
@tetra12 do you mean that all Casdoor APIs should support body JSON?

**Comment by tetra12** [comment]
@hsluoyz 
I would implement a JSON body support for only `/api/login/oauth/access_token` endpoint now. Since many users, DevOps and CI scripts may use standard images with `curl` to get/refresh/remove a token.

Other APIs may be implemented later upon a request

**Comment by hsluoyz** [comment]
@tetra12 OK.

@Steve0x2a plz work on this
