### ISSUE TITLE
improve config experience with provider or syncer

### ISSUE THREAD

**Issue by ppppfly** [casdoor/casdoor#652]
### Config Email Provider
After several config actions, press saves to submit Email Configuration, but I'm not sure whether the config is even working.

I have to try to change my account email, to verify whether the config is working.

so, is it possible that add a "verify config" function according to the type of Provider before we submit the change?

### A foolish trial to use syncer
I don't understand what's the function of the syncer at the time (even now I don't have successful experience of syncer), I just try and save a syncer without any change to the default settings. 

Unfortunately, It is actually "working", I didn't mean it's really working well, it makes my MySQL DB generates a lot of binary logs by 40M per minute, and break down the DB within 4 days by taking all the disk space. ultimately, all my production service was no response.

so, is it possible that add a "verify config" function according to the type of syncer before we save the config? And then set the "isEnabled" to true if the config passes the verification.

## conclusion

I think that's a good way to improve the config experience and avoid a lot of trouble in the future.

**Comment by hsluoyz** [comment]
@RyaoChengfeng plz work on it
