### ISSUE TITLE
Casdoor fails to start when there is already a database

### ISSUE THREAD

**Issue by niko7g** [casdoor/casdoor#664]
I compiled Casdoor.exe according to the document, and the backend database is MySQL8. The first time I execute Casdoor.exe -createDatabase, it seems that everything is normal, and the login operation of Casdoor also seems to be normal. But when I stop the Casdoor.exe, and then execute the Casdoor.exe for the second time, panic: Error 1054: Unknown column 'INFORMATION_SCHEMA.COLUMNS.ORDINAL_POSITION' in 'order clause' appears. I ran into this issue on 1.37.0, and today upgraded to 1.40.0.

**Comment by hsluoyz** [comment]
@niko7g plz change to English

**Comment by niko7g** [comment]
I compiled Casdoor.exe according to the document, and the backend database is MySQL8. The first time I execute Casdoor.exe -createDatabase, it seems that everything is normal, and the login operation of Casdoor also seems to be normal. But when I stop the Casdoor.exe, and then execute the Casdoor.exe for the second time, panic: Error 1054: Unknown column 'INFORMATION_SCHEMA.COLUMNS.ORDINAL_POSITION' in 'order clause' appears. I ran into this issue on 1.37.0, and today upgraded to 1.40.0.

**Comment by niko7g** [comment]
casdoor>casdoor.exe
[xorm] [info]  2022/04/14 11:14:36.842847 [SQL] SELECT `TABLE_NAME`, `ENGINE`, `AUTO_INCREMENT`, `TABLE_COMMENT` from `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA`=? AND (`ENGINE`='MyISAM' OR `ENGINE` = 'InnoDB' OR `ENGINE` = 'TokuDB') [casdoor] - 50.1683ms
[xorm] [info]  2022/04/14 11:14:36.889304 [SQL] SELECT `COLUMN_NAME`, `IS_NULLABLE`, `COLUMN_DEFAULT`, `COLUMN_TYPE`, `COLUMN_KEY`, `EXTRA`,`COLUMN_COMMENT` FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = ? AND `TABLE_NAME` = ? ORDER BY `INFORMATION_SCHEMA`.`COLUMNS`.ORDINAL_POSITION [casdoor organization] - 30.0039ms
panic: Error 1054: Unknown column 'INFORMATION_SCHEMA.COLUMNS.ORDINAL_POSITION' in 'order clause'

goroutine 1 [running]:
github.com/casdoor/casdoor/object.(*Adapter).createTable(0xc0002072c0)
        .../casdoor/object/adapter.go:123 +0x765
github.com/casdoor/casdoor/object.InitAdapter(0x0)
        .../casdoor/object/adapter.go:48 +0xb1
main.main()
        .../casdoor/main.go:36 +0xa7

**Comment by hsluoyz** [comment]
@Steve0x2a @ComradeProgrammer
