### ISSUE TITLE
Add Casdoor to Pulsar docs: pulsar-manager

### ISSUE THREAD

**Issue by nodece** [casdoor/casdoor#665]
Casdoor support has been added to pulsar-manager in https://github.com/apache/pulsar-manager/pull/446.

We need to add guide documentation on how to use the Casdoor in pulsar-manager.

Add this guide to https://pulsar.apache.org/docs/en/administration-pulsar-manager page.

**Comment by hsluoyz** [comment]
@jakiuncle

**Comment by hsluoyz** [comment]
@nodece PR here: https://github.com/apache/pulsar/pull/17324 , plz review

**Comment by hsluoyz** [comment]
Closed here for now
