### ISSUE TITLE
Support Casdoor authentication integration for Spring Cloud Gateway

### ISSUE THREAD

**Issue by seriouszyx** [casdoor/casdoor#666]
[spring-cloud-gateway](https://github.com/spring-cloud/spring-cloud-gateway) is a Gateway built on Spring Framework and Spring Boot providing routing and more. 

Now we can provide docs or examples for Casdoor authentication integration for Spring Cloud Gateway.

**Comment by hsluoyz** [comment]
@seriouszyx done

- Example code: https://github.com/casdoor/casdoor-springcloud-gateway-example
- Docs: https://github.com/casdoor/casdoor-website/issues/296
