### ISSUE TITLE
How can I integrate casdoor and minio?

### ISSUE THREAD

**Issue by niko7g** [casdoor/casdoor#669]
I have installed Casdoor (v1.40.0) and minio, and set it up according to this page: https://casdoor.org/zh/docs/integration/minio/  (same as https://casdoor.org/docs/integration/minio/ ) . The article prompts me to set "tag: readwrite", but the field is not available in Casdoor's admin console and cannot be set. Skip this step and continue to set up, it seems to be smooth, but finally after clicking "Login With SSO" on the minio console, an error is reported: Error from IDP
An error occurred, please try again
None of the given policies (`staff`) are defined, credentials will not be generated

**Comment by niko7g** [comment]
Done, modify the user's "tag" and change the default value of "staff" to "readwrite".

**Comment by hsluoyz** [comment]
@Abingcbc do we need any fix on our side like code or docs?
