### ISSUE TITLE
When MinIO uses casdoor to log in, how to limit the user's permissions?

### ISSUE THREAD

**Issue by niko7g** [casdoor/casdoor#677]
I followed the instructions of https://casdoor.org/docs/integration/minio/ to set up MinIO to use casdoor for SSO, and the login was successful. But I found that in Casdoor, users can modify the tag attribute value by themselves, which means that users can decide their own permissions in MinIO! This is a big problem. How can I restrict this behavior of users? casdoor version 1.40.0.

**Comment by hsluoyz** [comment]
@niko7g now you can use the "View rule" & "Modify rule" in "Account items" table of the "Edit Organization" page to control the permission for user fields:

- Docs: https://casdoor.org/docs/permission/permission-configuration
- Demo: https://door.casdoor.com/organizations/built-in#:~:text=profile%20public%20%3A-,Account%20items,-%3A

![image](https://user-images.githubusercontent.com/3787410/212482049-932e256f-4110-4a60-9a79-a53a900c0aec.png)
