### ISSUE TITLE
In Casdoor UI application field "Token expire" in hours, but in fact they are minutes.

### ISSUE THREAD

**Issue by Kalinin-Andrey** [casdoor/casdoor#683]
In Casdoor UI application field "Token expire" in hours:
![image](https://user-images.githubusercontent.com/8151806/164327939-d118bbef-c7a8-45c1-abbb-01ef986ec199.png)

Saving in DB in minutes.
But the reverse conversion is done as this value would be stored in seconds:
https://cs.opensource.google/go/x/oauth2/+/97805856:internal/token.go;drc=c85d3e98c914e3a33234ad863dcbff5dbc425bb8;l=265

As a result, hours are indicated in the interface, but in fact they are minutes.

**Comment by hsluoyz** [comment]
@Kalinin-Andrey can you make a PR to fix it?

**Comment by hsluoyz** [comment]
@lulei

**Comment by Kalinin-Andrey** [comment]
@hsluoyz 
Once again, I everything was debugged in great detail.
After deletion, the token's expiration time is overwritten with the magic number 10080. This is what confused me last time.

While the token is active, the time there is correct: in seconds.

All is right.

This issue can be closed.
Thank you. I apologize for the wrong note.

**Comment by hsluoyz** [comment]
@Kalinin-Andrey great to see it's resolved!
