### ISSUE TITLE
DingTalk provider value bug

### ISSUE THREAD

**Issue by akkuman** [casdoor/casdoor#686]
https://github.com/casdoor/casdoor/blob/d3a7a062d3e71fb325c22ebcb0f8b4b43ccef610/object/user_util.go#L26-L42

example:
the provider.Type is DingTalk
but at `User`, it is 
```
DingTalk      string `xorm:"dingtalk varchar(100)" json:"dingtalk"\`
```

This can be a problem if the database field names are case sensitive

**Comment by hsluoyz** [comment]
@ComradeProgrammer
