### ISSUE TITLE
Design and develop a more beautiful frontend portal

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#69]
We use a raw Antd-looking UI for portal. But we need to improve the UI if it's for production use.

**Comment by MayankMittal1** [comment]
@hsluoyz wanted to include this issue in my proposal, what kind of design is required? have i to use antd or develop a design from scratch?

**Comment by MayankMittal1** [comment]
@hsluoyz i was thinking to port casdoor's UI to MaterialUI https://mui.com/ which is more asthetic and looks superior as compared to antd, and also working on making the frontend responsive.

**Comment by hsluoyz** [comment]
@MayankMittal1 we don't change to another UI framework. We will improve existing UI based on antd.

**Comment by MayankMittal1** [comment]
@hsluoyz can you point out in a bit detail,what exactly requires improvment?

**Comment by ZhengLin-Li** [comment]
![image](https://user-images.githubusercontent.com/63448884/211182131-edc7efba-88f8-4cf4-92b6-5e2e9deaf38e.png)


Seams that a new UI has been released, shall we close this issue as completed? @hsluoyz

**Comment by parteekcoder** [comment]
@hsluoyz is there still some work to be done here

do you have any designs

**Comment by hsluoyz** [comment]
This issue has completed.
