### ISSUE TITLE
Need add 'use' and 'alg' in .well-known/jwks

### ISSUE THREAD

**Issue by rakuten** [casdoor/casdoor#691]
I can't use casdoor log in to BookStackApp when using OIDC Mode

I found the need for 'alg' and 'use' in its code, But it's not in casdoor. How can I change it?
```
protected function filterKeys(array $keys): array
    {
        return array_filter($keys, function (array $key) {
            $alg = $key['alg'] ?? null;

            return $key['kty'] === 'RSA' && $key['use'] === 'sig' && (is_null($alg) || $alg === 'RS256');
        });
    }
```
[Link](https://github.com/BookStackApp/BookStack/blob/development/app/Auth/Access/Oidc/OidcProviderSettings.php) Line: 169

**Comment by hsluoyz** [comment]
@halozhy

**Comment by halozhy** [comment]
> I can't use casdoor log in to BookStackApp when using OIDC Mode
> 
> I found the need for 'alg' and 'use' in its code, But it's not in casdoor. How can I change it?
> 

You can add the following code after [object/oidc_discovery.go#L107](https://github.com/casdoor/casdoor/blob/master/object/oidc_discovery.go#L107)
```
jwk.Algorithm = "xxx"
jwk.Use = "xxx"
```
