### ISSUE TITLE
Connecting to APISIX 503 bug

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#696]
Follow docs: https://casdoor.org/docs/integration/apisix

Got 503:

![(DD$XUTUA V`6EZULUDH0@5](https://user-images.githubusercontent.com/3787410/164737979-e2d7bf6c-dafd-4c07-abdf-76185848581a.jpg)

![I{XHT~)) 0BYG}(F 1N0_5V](https://user-images.githubusercontent.com/3787410/164738004-4c55979d-1a66-4ed0-8a99-a181d174d0fd.jpg)

![`KX}VH6I%027P4EGJGG5ZZ0](https://user-images.githubusercontent.com/3787410/164738019-7f6a2b53-93ac-4a63-8548-d0fafeb11286.jpg)

![7E2OBBV9WCD9YB$3~)`AS~5](https://user-images.githubusercontent.com/3787410/164738044-b68ca2d2-bc4f-4a9e-880f-5e79ee8ed2f8.jpg)

**Comment by bestHAI** [comment]
I have encountered the same problem, how can I solve it?

**Comment by hsluoyz** [comment]
@bestHAI hi, this is more of the APISIX middleware issue. Please create an GitHub issue at APISIX community

**Comment by bestHAI** [comment]
> @bestHAI hi, this is more of the APISIX middleware issue. Please create an GitHub issue at APISIX community

ok, thx
