### ISSUE TITLE
OIDC endpoint is always https 

### ISSUE THREAD

**Issue by fukco** [casdoor/casdoor#700]
* env: docker with image casdoor-all-in-one
* OIDC Discovery shows that issuer and other endpoints are start with https not http, not config any tls for this environment and do not find any configuration to change https to http.
* when use OIDC, it always redirect to https, and it's not work.(http works perfectly)

**Comment by hsluoyz** [comment]
@ComradeProgrammer

**Comment by hsluoyz** [comment]
@haoliu97

**Comment by rakuten** [comment]
@fukco 
抱歉我的能力不足以用英文来描述以下内容

你这个事情怎么说才比较好呢.....

我觉得这个事可能不需要改Casdoor就能解决，因为你没有提供你docker环境足够的信息，所以我只能靠猜，假设是你没有用通用做法配置docker环境，同时假设你用的服务和Casdoor处于同一个docker network里，以下是我的建议

1.运行traefik或apisix作为公网80和443的入口网关
2.使用泛域名证书，或为每个要用的服务配置子域名证书
3.运行dnsmasq作为内部dns服务器(你也可以用别的dns server作为替代)
4.dnsmasq上设置域名指向服务器内网地址
5.设置docker使用内网地址作为dns解析
6.运行镜像时不要用docker -h参数

这样你就可以在内网使用域名做指向并不影响443端口了
网关的主要作用是把公网的443转为内网的http通讯，也就是说你的服务启动时只需要支持http就行了，不需要设置https
不用docker -h配置域名是因为它会用docker内置的网桥，这样会越过网关，导致无法做正确的转发

**Comment by fukco** [comment]
@rakuten 

你理解的好像有点偏差哎，我描述的问题是OIDC在这个容器环境中启动后，访问地址是http的，端口是8000，像这样http://<MY-DOMAIN>:8000，这个路径暴露的地址都是https开头的，这些地址是无法访问的，配置ISSUER导致Client跳转地址开头也是https，手动修改为http才能正常访问。

1. 没看明白你说的怎么就到443端口去了，任意端口都可以决定是否开启TLS
2. 我不确定casdoor是否强制OIDC运行在TLS协议之上，我看Oauth2协议有说需要TLS，还是开发环境非必须，这个知道的话望解答
3. 关于容器，如果强制使用TLS的话，看一下[无状态](https://cloud.google.com/architecture/best-practices-for-operating-containers?hl=zh-cn#statelessness)和[不变性](https://cloud.google.com/architecture/best-practices-for-operating-containers?hl=zh-cn#immutability)，我的建议是添加相关配置，证书从宿主机进行挂载。当然如果这个镜像是推荐开发环境使用并且强制TLS的话，我的建议是，容器启动时生成，或者直接打包到镜像
4. 我不清楚裸机部署casdoor是什么情况，有机会我试试看下这个/.well-known/openid-configuration查询到的地址是不是真正可以访问的地址。

**Comment by rakuten** [comment]
那是我误解你的意思了

我这的环境都是把证书放在网关上，所以永远都是通过https请求的，然后网关再把请求都转发到内网服务的http端口，所以Casdoor在我看来并没有问题

**Comment by hsluoyz** [comment]
@fukco @rakuten plz change to English, the issues are supposed to use English

**Comment by hsluoyz** [comment]
@fukco @rakuten the OIDC discovery code is here:

https://github.com/casdoor/casdoor/blob/c05fb772241a0f58650a5ed731208303c76580d5/object/oidc_discovery.go#L45-L91

It offers the JSON here: https://casdoor.org/zh/docs/how-to-connect/oidc-client/

Do you think the code needs to be changed to support your scenario?

**Comment by fukco** [comment]
@hsluoyz Thanks for your response.

From the code, `host := c.Ctx.Request.Host` can not get the Schema . And it only change https to http when the url equals 'localhost', I don't think it's a good choice.

use` c.Ctx.Input.IsSecure() `to check http or https or use `c.Ctx.Input.Scheme()` to get the scheme maybe a good solution.

**Comment by hsluoyz** [comment]
@fukco can you make a PR to fix it?

**Comment by hsluoyz** [comment]
Won't fix, see: https://github.com/casdoor/casdoor/pull/741#issuecomment-1118262900
