### ISSUE TITLE
 how to get jwt-public-key of app?

### ISSUE THREAD

**Issue by zhangchunsheng** [casdoor/casdoor#711]
how to get jwt-public-key of app?

https://github.com/casdoor/casdoor-spring-boot-starter

**Comment by seriouszyx** [comment]
plz refer to https://casdoor.org/docs/how-to-connect/sdk#1-backend-sdk-configuration

**Comment by zhangchunsheng** [comment]
The problem is caused by docker mirror of aliyun. 

It's better to use image tag when docker run.
```
docker run -p 8000:8000 casbin/casdoor-all-in-one:v1.44.0
```

```
casbin/casdoor-all-in-one                                         latest                          0faca091f11d   4 months ago    528MB
```

**Comment by zhangchunsheng** [comment]
> plz refer to https://casdoor.org/docs/how-to-connect/sdk#1-backend-sdk-configuration

Thanks
