### ISSUE TITLE
对SameSite属性的支持不完整

### ISSUE THREAD

**Issue by jazzmozart** [casdoor/casdoor#712]
`beego.BConfig.WebConfig.Session.SessionCookieSameSite = http.SameSiteNoneMode`
当SameSite设置为None 时，需在最新的浏览器版本中使用 Secure属性。目前的beego版本不支持直接配置Secure属性

**Comment by hsluoyz** [comment]
@jazzmozart plz change text into English, thanks!

**Comment by jazzmozart** [comment]
#714
