### ISSUE TITLE
Support Angular frontend integration with Casdoor

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#732]
We already have two frontend SDKs:

1. Pure JS (and React): https://github.com/casdoor/casdoor-js-sdk
2. Vue (2 & 3): https://github.com/casdoor/casdoor-vue-sdk

Now we need the last one for Angular, repo created here: https://github.com/casdoor/casdoor-angular-sdk

**Comment by huiwenhan** [comment]
any progress ?

**Comment by hsluoyz** [comment]
@huiwenhan you can directly use the JS SDK: https://github.com/casdoor/casdoor-js-sdk , 
later we may make an Angular example. Your contribution is also welcome.

**Comment by hsluoyz** [comment]
Done at: https://github.com/casdoor/casdoor-nodejs-angular-example
