### ISSUE TITLE
before click the "Save & Exit" button , items has been saved

### ISSUE THREAD

**Issue by hawckodere** [casdoor/casdoor#738]
As title , this happens in Organizations, Users, Roles, Permissions, Providers, Applications, Tokens, Webhooks, Syncers, Certs, Products and Payments.

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by hsluoyz** [comment]
@greenhandatsjtu

**Comment by greenhandatsjtu** [comment]
From my point of view, it's a feature, not bug. Take Roles for example:
https://github.com/casdoor/casdoor/blob/8b340105c130ddac1724e638b2b79bf92fdbbf02/web/src/RoleListPage.js#L185
As you can see, when you click `Add`, `addRole()` will be called, and a new role record shows in `user` table:
![image](https://user-images.githubusercontent.com/40566803/166619377-60774d24-fcb0-477e-979d-52dfbe13e5c7.png)

https://github.com/casdoor/casdoor/blob/8b340105c130ddac1724e638b2b79bf92fdbbf02/web/src/RoleEditPage.js#L107-L108
When you finish editing and click `Save & Exit`, `submitRoleEdit()` will be called, which is just *updating* the role.
https://github.com/casdoor/casdoor/blob/8b340105c130ddac1724e638b2b79bf92fdbbf02/web/src/RoleEditPage.js#L183
And if you click `Cancel`, `deleteRole()` will be called and role record in DB will be deleted, so everthing is just fine.
![image](https://user-images.githubusercontent.com/40566803/166619462-8c20bdf0-49a6-465e-8b69-f26a27040140.png)

**Comment by hsluoyz** [comment]
@greenhandatsjtu yes, this feature is just not that good, we don't want the item to have been created before saved,

**Comment by hawckodere** [comment]
> 从我的角度来看，这是一个功能，而不是错误。以角色为例：
> 
> https://github.com/casdoor/casdoor/blob/8b340105c130ddac1724e638b2b79bf92fdbbf02/web/src/RoleListPage.js#L185
> 
> 
> 可以看到，当你点击 时`Add`，`addRole()`会被调用，并且一个新的角色记录显示在`user`表格中：
> ![图片](https://user-images.githubusercontent.com/40566803/166619377-60774d24-fcb0-477e-979d-52dfbe13e5c7.png)
> https://github.com/casdoor/casdoor/blob/8b340105c130ddac1724e638b2b79bf92fdbbf02/web/src/RoleEditPage.js#L107-L108
> 
> 
> 当你完成编辑并单击`Save & Exit`时，`submitRoleEdit()`将被调用，这只是_更新_角色。
> https://github.com/casdoor/casdoor/blob/8b340105c130ddac1724e638b2b79bf92fdbbf02/web/src/RoleEditPage.js#L183
> 
> 
> 如果你点击`Cancel`,`deleteRole()`将被调用并删除数据库中的角色记录，所以一切都很好。
> ![图片](https://user-images.githubusercontent.com/40566803/166619462-8c20bdf0-49a6-465e-8b69-f26a27040140.png)

I now understand .
But i think the logic you explained is still not perfect. Accoding to the logic, you must ensure i click the "Save & Exit" or the "Cancel" button, but  i may neither click the "Save & Exit" button nor click the "Cancel" button ,i just click "Organizations" or  "Users" or somelink else.

**Comment by hawckodere** [comment]
I now understand .
But i think the logic you explained is still not perfect. Accoding to the logic, you must ensure i click the "Save & Exit" or the "Cancel" button, but i may neither click the "Save & Exit" button nor click the "Cancel" button ,i just click "Organizations" or "Users" or somelink else.

**Comment by aecra** [comment]
This is a terrible default action.

**Comment by nomeguy** [comment]
@ziliangyu
