### ISSUE TITLE
broken commit related to "RS256"

### ISSUE THREAD

**Issue by Janso123** [casdoor/casdoor#743]
Hi there as of now I found that this commit breaks oidc because CryptoAlgorithm returns RSA instead of RS256 
https://github.com/casdoor/casdoor/pull/708/commits/9083e76cbe338c5adac238c35e021f1ce168b11d

**Comment by nomeguy** [comment]
Fixed in: https://github.com/casdoor/casdoor/commit/39548d5d72eb08660e2385a95dbfe7e890da910d
