### ISSUE TITLE
Support integration with Zentao

### ISSUE THREAD

**Issue by nomeguy** [casdoor/casdoor#745]
See: https://www.zentao.net/

Zentao is an open-source project management platform written in PHP. There are several ways for integrating Zentao with Casdoor SSO:

1. Via 3rd-party OIDC module: https://github.com/wingfeng/zentao-oidc
2. Via Zentao's own non-password login: https://www.zentao.net/book/zentaopmshelp/344.html
3. Via CAS custom code snippet: https://www.bianchengquan.com/article/323615.html

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by nomeguy** [comment]
Fixed by:https://github.com/casdoor/casdoor-website/pull/205
