### ISSUE TITLE
Support BookStack authentication with Casdoor

### ISSUE THREAD

**Issue by nomeguy** [casdoor/casdoor#747]
https://github.com/TruthHun/BookStack

They have a very simple SSO: https://www.bookstack.cn/read/help/windows.md#%E9%85%8D%E7%BD%AE%E7%AC%AC%E4%B8%89%E6%96%B9%E7%99%BB%E5%BD%95

We need to change it to Casdoor

**Comment by hsluoyz** [comment]
Done at: https://www.bookstack.cn/read/help/Casdoor.md
