### ISSUE TITLE
Page not Found for Authorization Endpoint

### ISSUE THREAD

**Issue by hz324** [casdoor/casdoor#754]
Problem Description:

- when requesting the /login/oauth/authorize API endpoint, "404 page not found" is returned.
- The casdoor backend is deployed in a docker container serving http
- an example command I used to access the self hosted backend would be 
- curl -X POST "http://$MY_HOSTNAME/login/oauth/authorize?client_id=$MY_CLIENTID&nonce=$SOME_NONCE&redirect_uri=$MY_APPLICATION_CALLBACK&response_type=code&scope=openid%20profile%20email&state=$SOME_STATE"

Expected Behaviour:

- /login/oauth/authorize is a valid API endpoint, understands and process my request and then successfully redirect to $MY_APPLICATION_CALLBACK uri.
- Incidentally, this can be the case when I access https://door.casdoor.com
- This can be tested with the request below
- https://door.casdoor.com/login/oauth/authorize?client_id=b800a86702dd4d29ec4d&nonce=nonce&redirect_uri=http%3A%2F%2F127.0.0.1%2F%2Fcallback&response_type=code&scope=openid%20profile%20email&state=heyiamastate
- which return Login Error "Redirect URI: "http://127.0.0.1//callback" doesn't exist in the allowed Redirect URI list"
- Thus showing that the request has been understood and processed

Further Details:

Upon checking [http://$MY_HOSTNAME/.well-known/openid-configuration], the authorization endpoint is returned as follows (N.B. I'm serving the backend with http)

{
  "issuer": http://$MY_HOSTNAME,
  "authorization_endpoint": "http://$MY_HOSTNAME/login/oauth/authorize",
  "token_endpoint": "http://$MY_HOSTNAME/api/login/oauth/access_token",
  "userinfo_endpoint": "http://$MY_HOSTNAME/api/userinfo",
  "jwks_uri": "http://$MY_HOSTNAME/.well-known/jwks",
  "introspection_endpoint": "http://$MY_HOSTNAME/login/oauth/introspect",
 ...
}

Upon checking the source code at object/oidc_discovery.go line 74
`AuthorizationEndpoint:                  fmt.Sprintf("%s/login/oauth/authorize", originFrontend),`
It seems that the authorization endpoint is fixed to be /login/oauth/authorize

However in routers/router.go, the path /login/oauth/authorize cannot be found.

Use Case:

I'm trying to setup SSO with an existing application, as autodiscovery is difficult to be done without https, I'm configuring the authorization endpoints, token_endpoints etc. explicitly in the application config file. When trying connect to casdoor through the said application, the authorization endpoint "http://$MY_HOSTNAME/login/oauth/authorize" is requested, but a "page not found" type message is returned.

**Comment by hz324** [comment]
I believe this is not exactly a question , but could be a bug where the /login/oauth/authorize API does not perform with the expected behaviour shown on the demo website

**Comment by hsluoyz** [comment]
@ComradeProgrammer

**Comment by hsluoyz** [comment]
@Steve0x2a

**Comment by ComradeProgrammer** [comment]
> Problem Description:
> 
> * when requesting the /login/oauth/authorize API endpoint, "404 page not found" is returned.
> * The casdoor backend is deployed in a docker container serving http
> * an example command I used to access the self hosted backend would be
> * curl -X POST "http://$MY_HOSTNAME/login/oauth/authorize?client_id=$MY_CLIENTID&nonce=$SOME_NONCE&redirect_uri=$MY_APPLICATION_CALLBACK&response_type=code&scope=openid%20profile%20email&state=$SOME_STATE"
> 
> Expected Behaviour:
> 
> * /login/oauth/authorize is a valid API endpoint, understands and process my request and then successfully redirect to $MY_APPLICATION_CALLBACK uri.
> * Incidentally, this can be the case when I access https://door.casdoor.com
> * This can be tested with the request below
> * https://door.casdoor.com/login/oauth/authorize?client_id=b800a86702dd4d29ec4d&nonce=nonce&redirect_uri=http%3A%2F%2F127.0.0.1%2F%2Fcallback&response_type=code&scope=openid%20profile%20email&state=heyiamastate
> * which return Login Error "Redirect URI: "http://127.0.0.1//callback" doesn't exist in the allowed Redirect URI list"
> * Thus showing that the request has been understood and processed
> 
> Further Details:
> 
> Upon checking [http://$MY_HOSTNAME/.well-known/openid-configuration], the authorization endpoint is returned as follows (N.B. I'm serving the backend with http)
> 
> { "issuer": http://$MY_HOSTNAME, "authorization_endpoint": "http://$MY_HOSTNAME/login/oauth/authorize", "token_endpoint": "http://$MY_HOSTNAME/api/login/oauth/access_token", "userinfo_endpoint": "http://$MY_HOSTNAME/api/userinfo", "jwks_uri": "http://$MY_HOSTNAME/.well-known/jwks", "introspection_endpoint": "http://$MY_HOSTNAME/login/oauth/introspect", ... }
> 
> Upon checking the source code at object/oidc_discovery.go line 74 `AuthorizationEndpoint: fmt.Sprintf("%s/login/oauth/authorize", originFrontend),` It seems that the authorization endpoint is fixed to be /login/oauth/authorize
> 
> However in routers/router.go, the path /login/oauth/authorize cannot be found.
> 
> Use Case:
> 
> I'm trying to setup SSO with an existing application, as autodiscovery is difficult to be done without https, I'm configuring the authorization endpoints, token_endpoints etc. explicitly in the application config file. When trying connect to casdoor through the said application, the authorization endpoint "http://$MY_HOSTNAME/login/oauth/authorize" is requested, but a "page not found" type message is returned.

`http://$MY_HOSTNAME/login/oauth/authorize` locates in the frontend. As you said, I quote "The casdoor backend is deployed in a docker container serving http", if the frontend is not running, it will be normal to get a 404. Besides, it's normal to find that this route doesn't appear in the router.go because it only contains routes available on backend.

Please set up frontend and have a try

**Comment by hz324** [comment]
Thank your reply, that answers a lot questions, I'll have a go at querying the frontend.

However, if I would like to use a backend only setup, is it possible to achieve a similar effect querying the backend API? Or is such arrangement not a recommended way to use casdoor.

**Comment by hz324** [comment]
I see, thank you very much. I have originally assumed that the backend alone is enough for oauth functionalities. However, when I come to think about it, I believe you are indeed correct, a front end is required in the authorization grant stage for username and password.

However, as casdoor does have a frontend and backend separation. Is it an expected behaviour for the backend at  "$MY_HOSTNAME:$BACKEND_PORT/.well-known/openid-configuration" to return 

{
"issuer": http://$MY_HOSTNAME:BACKEND_PORT,
"authorization_endpoint": "http://$MY_HOSTNAME:BACKEND_PORT/login/oauth/authorize",
...
}
instead of some form of error stating that this api method is actually non-existent on this endpoint? (perhaps there are some other use cases for which I'm not familiar with that requires this type of backend behaviour)

I can see that if I query the frontend, it does indeed show the behaviour as you described
{
"issuer": http://$MY_HOSTNAME:$BACKEND_PORT,
"authorization_endpoint": "http://$MY_HOSTNAME:$FRONTEND_PORT/login/oauth/authorize",
"token_endpoint": "http://$MY_HOSTNAME:$BACKEND_PORT/api/login/oauth/access_token",
...
}

Anyway, thank you for your time and your clarification, I believe that my original question has been well-answered.

**Comment by hsluoyz** [comment]
@hz324 plz follow the **Offical** way to setup Casdoor, and then ask questions if you encounter any.

https://casdoor.org/docs/basic/server-installation
