### ISSUE TITLE
Question: what's the meaning about below env vars

### ISSUE THREAD

**Issue by mojerro** [casdoor/casdoor#755]
env in `app.conf` file
```env
defaultStorageProvider = 
isCloudIntranet = false
authState = "casdoor"
verificationCodeTimeout = 10
initScore = 2000
```

**Comment by Resulte** [comment]
@mojerro 
1. 'defaultStorageProvider' is the default file storage service name. If you need to use file storage services such as avatar upload, you need to set up a storage provider and apply it in your application. See this link for details: https://casdoor.org/docs/provider/storage/storage
2. 'isCloudIntranet' is used to identify whether your provider endpoint is intranet endpoint.
3. 'authState' is the authorization application name. This parameter will be checked when logging in.
4. 'verificationCodeTimeout' set the expiration time of the verification code. After the expiration, the user needs to obtain it again.
5. 'initScore' is the initial score of each user. Each user has a score attribute.

**Comment by mojerro** [comment]
> @mojerro
> 
> 1. 'defaultStorageProvider' is the default file storage service name. If you need to use file storage services such as avatar upload, you need to set up a storage provider and apply it in your application. See this link for details: https://casdoor.org/docs/provider/storage/storage
> 2. 'isCloudIntranet' is used to identify whether your provider endpoint is intranet endpoint.
> 3. 'authState' is the authorization application name. This parameter will be checked when logging in.
> 4. 'verificationCodeTimeout' set the expiration time of the verification code. After the expiration, the user needs to obtain it again.
> 5. 'initScore' is the initial score of each user. Each user has a score attribute.

1. about `defaultStorageProvider`, is there any way to create `storage provider` from config files?
5. I see 'initScore' in the source code but I don't know what it truly controls. And I also see some hard-coded code to set  'initScore'  to 2000 in source code which I think it hope to compare with the initial value.

**Comment by mojerro** [comment]
@Resulte thanks for your explanation.

**Comment by Resulte** [comment]
@mojerro 
1. I think you can't create `storage provider` from config files. See this link for details: https://casdoor.org/docs/provider/overview/
2. Each user will set an initial score value when they sign up.  If you do not set an `initScore` value in the config file, the code will write this value as 2000 by default.

**Comment by mojerro** [comment]
@Resulte So, what's the score's real meaning in applications?

**Comment by mojerro** [comment]
Is the score controls some functions?

**Comment by Resulte** [comment]
@mojerro Score is used by https://github.com/casbin/casnode. Score does not control anything in casdoor.

**Comment by hsluoyz** [comment]
@mojerro see: https://github.com/casdoor/casdoor-website/pull/210

**Comment by mojerro** [comment]
thanks a lot~
