### ISSUE TITLE
Cannot read properties of null (reading 'grantTypes')

### ISSUE THREAD

**Issue by xunfeng1980** [casdoor/casdoor#756]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8380489/169264547-85e59834-d837-467a-9f09-104a6578f120.png">

**Comment by hsluoyz** [comment]
@greenhandatsjtu

**Comment by greenhandatsjtu** [comment]
Can you switch to `Network` tab and check if request `/get-application?id=xxx` get response correctly. This may be caused by backend not returning application info correctly.
![image](https://user-images.githubusercontent.com/40566803/169315394-f0153253-9209-4ae6-a1ee-c3a518de725c.png)

**Comment by hsluoyz** [comment]
@xunfeng1980

**Comment by hsluoyz** [comment]
Closed as stale.
