### ISSUE TITLE
json: cannot unmarshal string into Go struct field DingTalkAccessToken.code of type int

### ISSUE THREAD

**Issue by kingfree** [casdoor/casdoor#760]
Both for my local deploy and your casdoor demo deploy, I do login with my DingTalk account, it jumps to this url:

`https://door.casdoor.com/callback?authCode=xxx&state=xxx%3D`

and show:
```
正在登录...
```

then I refresh the page, it shows:
```
There was a problem signing you in..
json: cannot unmarshal string into Go struct field DingTalkAccessToken.code of type int
```

Maybe the DingTalk API has changed, or your application made the BUG.

**Comment by hsluoyz** [comment]
@kingfree the DingTalk login on the demo site works as expected: https://door.casdoor.com/login , so it has no bug. Plz follow the docs again: https://casdoor.org/docs/provider/oauth/DingTalk

![image](https://user-images.githubusercontent.com/3787410/169825987-f4a140db-b960-40dd-9866-6ed8ccf5552e.png)

**Comment by hsluoyz** [comment]
Closed as invalid.
