### ISSUE TITLE
How to realize "your account has been logged in elsewhere" for a casdoor user?

### ISSUE THREAD

**Issue by 313843288** [casdoor/casdoor#774]
How to realize "your account has been logged in elsewhere" for a casdoor user?

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by hsluoyz** [comment]
@313843288 do you mean to limit one user session for your application? Here we have a solution to limit one user session inside the application, see: https://github.com/casbin/confita/commit/ca295d95c49748576d5089d95d85b3206305e027

Next we will integrate it into Casdoor's session management: https://door.casdoor.com/sessions

Casdoor should provide 3 new APIs:

- AddUserSession
- DeleteUserSession
- IsUserSessionDuplicated

The added user session will be managed in the Session table: https://door.casdoor.com/sessions

The application should call these new APIs to achieve similar effect as: https://github.com/casbin/confita/commit/ca295d95c49748576d5089d95d85b3206305e027
