### ISSUE TITLE
Can we use casdoor for centralized authorization system?

### ISSUE THREAD

**Issue by thanhpd56** [casdoor/casdoor#776]
Hi, 
i just learned about casdoor and know it has integration with casbin. Can casdoor become a centralized authorization where user management, permission, and endpoint to check the rights of a user?
Thanks in advanced.

**Comment by thanhpd56** [comment]
@ComradeProgrammer please help.

**Comment by KrishnaPG** [comment]
Looking for similar information. 

For example, 
- How to access the underlying `casbin` API or instance, or 
- get `roles of a user` or 
- query what a user is allowed to do or not allowed to do etc.

**Comment by hsluoyz** [comment]
@thanhpd56 @AmreeshTyagi @KrishnaPG plz help review this PR: https://github.com/casdoor/casdoor/pull/806 This is probaly what you need.

**Comment by thanhpd56** [comment]
> @thanhpd56 @AmreeshTyagi @KrishnaPG plz help review this PR: #806 This is probaly what you need.

I don't think that's what I want.
As I see it only checks permission for the login api right?
<img width="908" alt="image" src="https://user-images.githubusercontent.com/3794898/177143374-5c8c7fc5-a592-4b7f-a28e-4f46a49dfa6c.png">
However, I need an api for other service can call to check whether an user has specific permission or not.
Thanks.

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by KrishnaPG** [comment]
This will be resolved once the TODOs listed in https://github.com/casdoor/casdoor/issues/981 are done. More information is in the references https://github.com/casdoor/casdoor/issues/846 and  https://github.com/casdoor/casdoor/issues/849

**Comment by hsluoyz** [comment]
Done at
