### ISSUE TITLE
Program incompatible with mysql5.6

### ISSUE THREAD

**Issue by star7th** [casdoor/casdoor#777]
When the program installation starts, an error "error 1709: index column size too large. the maximum column size is 767 bytes" is reported

I think the length of a column is so long that the index is invalid. But this should be a small problem. I hope the official team can change the length a little.

**Comment by hsluoyz** [comment]
@ComradeProgrammer

**Comment by ComradeProgrammer** [comment]
please set `innodb_large_prefix=1` in mysql configuration file (for example, `my.ini` usually)

**Comment by star7th** [comment]
ok
