### ISSUE TITLE
Question: how can i access backend apis using Basic auth or some token in scripts?

### ISSUE THREAD

**Issue by xuesea** [casdoor/casdoor#779]
Hi,
I hope init some clients immediately using CURL  in my scripts after casdoor was deployed. When casdoor was deployed, there is only one default admin user: Admin/123. Is there any way to use this account  to access all backend apis using CURL?
I tried Biasc auth and got "msg": "Unauthorized operation"

**Comment by hsluoyz** [comment]
@xuesea see: https://casdoor.org/docs/how-to-connect/oauth#how-to-use-accesstoken

**Comment by xuesea** [comment]
Thanks
