### ISSUE TITLE
password saved in DB is in clear text, not a best practice.

### ISSUE THREAD

**Issue by jingkang99** [casdoor/casdoor#780]
better to use htpasswd to shadow/hash the clear text password

```
htpasswd -nbB new-user 'Super-Secret$Passw0rD'
new-user:$2y$05$gPG03Y1L0m8OpngHtu9vg.Iw0RKK0u4V.dnxSAQdY.LR1MT0GQ5EW
```

use md5 directly isn't strong enough. the db does have salt field, how is it used? 

Thanks. 

![image](https://user-images.githubusercontent.com/10793075/172223369-ad1e02f4-942e-4dcd-b6ea-903b0bbc120f.png)

**Comment by hsluoyz** [comment]
@jingkang99 it supports several different methods, see: https://casdoor.org/docs/organization/overview/

**Comment by jingkang99** [comment]
thanks a lot. it is better to use bcrypt by default.

**Comment by jingkang99** [comment]
thanks a lot. it is better to use bcrypt by default.
