### ISSUE TITLE
Click Register or forget password on the login page will automatically jump to the login page

### ISSUE THREAD

**Issue by igangang** [casdoor/casdoor#781]
Bug in version v1.54.7, click Register or forget password on the login page will automatically jump to the login page.

**Comment by hsluoyz** [comment]
@RyaoChengfeng

**Comment by RyaoChengfeng** [comment]
@igangang I can't reproduce this bug. Can you provide further information, such as relevant pictures or screen recordings? Or other information so that I can understand what's going on.

**Comment by igangang** [comment]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/18605969/172640746-2ee3b3d2-a0c8-45e3-b383-ff77d19cd163.png">
Click the red box in the screenshot above to jump to https://host/sinup at first, and then jump to https://host/# immediately.
@RyaoChengfeng
