### ISSUE TITLE
request for more detailed api docs

### ISSUE THREAD

**Issue by majingbit** [casdoor/casdoor#782]
Dear Casbin Administrator:
    I am using casdoor api recently. I learn the API usage through https://door.casdoor.com/swagger/ ,  but there is no example of input parameters in the document. I don't know how to write the correct input parameters. 
    For example: 
    "/api/login" requires the "oAuthParams" parameter to be passed in. However, there is no example of "oAuthParams" in the document. It only indicates that "oAuthParams" is a string.
    Is there a more detailed explanation?

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by leo220yuyaodog** [comment]
Got it. I will add more parameter descriptions.
