### ISSUE TITLE
Signup page not loading and Social Signup buttons now showing on the signup page

### ISSUE THREAD

**Issue by KrishnaPG** [casdoor/casdoor#784]
- Using the  `casbin/casdoor:latest` docker image, fresh install. When social providers are added to the application, the sign-in page is showing the social login options, but the signup page is not (please refer below screenshot)

![image](https://user-images.githubusercontent.com/4610831/172739966-51d00d42-b257-4894-8e5f-7e3c8796aaa9.png)

- Also when the "test signup page" button is clicked or the signup url of the application is pasted in the browser, it is redirecting to the casdoor home instead of showing the signup page

- On the Signin page the signup link button is also taking to the casdoor home instead of the signup page of the application. 
![image](https://user-images.githubusercontent.com/4610831/172742177-d1cf82b6-0700-4133-82e6-8bf7a8f18c3a.png)

All values are in their default, no special changes have been made. Wondering what is the issue and how to make the signup page load correctly.
![image](https://user-images.githubusercontent.com/4610831/172740655-094eecc8-f57b-45ba-a58c-69177af15672.png)

**Comment by KrishnaPG** [comment]
Looks like this issue https://github.com/casdoor/casdoor/issues/781 is also reporting the same behavior

If you want to test this behavior, you can use this test server: http://20.212.82.171:8081/ (default credentials)

Steps to reproduce:

- login
- in the applications select the first application "application_3o8vzc" click **Edit** 
- Scroll down and click on "Test Signup Page" button

You will see it redirecting to the home page rather than showing the signup page

**Comment by hsluoyz** [comment]
@KrishnaPG the "Test Signup Page" button doesn't work directly actually, because you have logged into Casdoor with existing cookie. You need to copy the URL of the button and enter it in another browser.

**Comment by KrishnaPG** [comment]
Thank you @hsluoyz 

How to fix the issue: social media buttons not appearing in signup, despite opting for signup with social logins?

The **signup** page is not showing the social media buttons (the **signin** page shows them, though)

**Comment by hsluoyz** [comment]
@KrishnaPG you need to disable password to let social buttons show up in signup page. If you still need password, you need to setup the social buttons in prompt page (a page after signup)

**Comment by KrishnaPG** [comment]
Thank you @hsluoyz Is it not possible to show the Password fields along with Social buttons for **Signup** on the same page (so that user can pickup either password or social buttons on the same page), rather than different pages?

For example, similar to the SignIn page where password fields are shown along side with Social buttons below.

**Comment by hsluoyz** [comment]
@KrishnaPG can you make a PR to add it? It's not hard.

**Comment by hsluoyz** [comment]
@wuhao1477

**Comment by hsluoyz** [comment]
@RyaoChengfeng
