### ISSUE TITLE
fail to start a docker image

### ISSUE THREAD

**Issue by tetra12** [casdoor/casdoor#790]
I use a localsetup and run MySQL in a separate container. I made a custom Dockerfile, based on what's shipped.
When I try to start a docker(both compose or directly), I'm getting the following:

```bash
iam    | panic: Unsupported driver name: 
iam    | 
iam    | goroutine 1 [running]:
iam    | github.com/casdoor/casdoor/object.(*Adapter).open(0xc0000b8340)
iam    |        /go/src/casdoor/object/adapter.go:102 +0xb2
iam    | github.com/casdoor/casdoor/object.NewAdapter({0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0})
iam    |        /go/src/casdoor/object/adapter.go:75 +0xd0
iam    | github.com/casdoor/casdoor/object.InitAdapter(0x0)
iam    |        /go/src/casdoor/object/adapter.go:44 +0x76
iam    | main.main()
iam    |        /go/src/casdoor/main.go:37 +0xa7
iam exited with code 2
```

Here's my command:
```bash
docker run -it --rm --name iam1 -v $PWD/conf:/conf/ -p 8001:8000 --add-host host.docker.internal:host-gateway tampler/casdoor-nws:v1.54.9-v1.17.5
```
And [here](https://gist.github.com/tetra12/83ada621942424f85fe62eeef32acdfd) is my config.

I do NOT have issues running Casdoor with `go run main.go`. So it looks like an integration issue.

Any advice? :thinking:

**Comment by hsluoyz** [comment]
@tetra12 the official Docker desployment options are provided in docs: https://casdoor.org/docs/basic/try-with-docker . We cannot provide comments about your customized Docker scripts.

From container viewpoint, Casdoor is just a simple application, which listens to a port and requires access to a database port. You should turn to Docker related forum or stackoverflow for help.
