### ISSUE TITLE
Issue setting up Google provider 

### ISSUE THREAD

**Issue by akeemphilbert** [casdoor/casdoor#802]
Followed the instructions found here https://casdoor.org/docs/provider/oauth/google/

When I try to login with the provider it seems to connect to google correctly but in the cabin app the login endpoint returns the following. I'm using the latest Docker image

```
casdoor:pq: column "Google" of relation "user" does not exist
Stack
/usr/local/go/src/runtime/panic.go:1038
/go/src/casdoor/object/user_util.go:85
/go/src/casdoor/object/user.go:488
/go/src/casdoor/controllers/auth.go:398
/usr/local/go/src/reflect/value.go:543
/usr/local/go/src/reflect/value.go:339
/go/pkg/mod/github.com/astaxie/beego@v1.12.3/router.go:897
/usr/local/go/src/net/http/server.go:2879
/usr/local/go/src/net/http/server.go:1930
/usr/local/go/src/runtime/asm_amd64.s:1581

beego 1.12.3 (beego framework)
golang version: go1.17.5
```

**Comment by akeemphilbert** [comment]
I can confirm that the users table does have a column "google" but it is empty (though there is a record for the user I tried to login as). If I try to login again it makes another user with a couple random characters appended to the email

**Comment by hsluoyz** [comment]
@ChenchengY

**Comment by hsluoyz** [comment]
Unreproducible, closed
