### ISSUE TITLE
Cannot get OAuth token

### ISSUE THREAD

**Issue by 704237006** [casdoor/casdoor#804]
I started one casdoor with docker,and run a CasdoorAuthServiceTest,but cannot get OAuth token.
![image](https://user-images.githubusercontent.com/42430068/174541137-a2808a73-b26a-4cfb-9276-78749184e23f.png)
![image](https://user-images.githubusercontent.com/42430068/174541190-fe964ae8-a45d-4ad0-8ba1-f351b03f0ff9.png)
![image](https://user-images.githubusercontent.com/42430068/174541318-5482ad9e-07ab-4ce3-b12f-71a8519ec4af.png)

**Comment by seriouszyx** [comment]
The code in `testAuthService` is merely a sample and you need to modify it according to your own environment.  Note that the code will be disabled once the token is obtained via the code.

**Comment by 704237006** [comment]
> The code in `testAuthService` is merely a sample and you need to modify it according to your own environment. Note that the code will be disabled once the token is obtained via the code.

Solved！
