### ISSUE TITLE
two app error

### ISSUE THREAD

**Issue by 704237006** [casdoor/casdoor#805]
Copy the casdoor spring boot example as app2, create a new app2 on casdoor, and change the port, client-ID, client-secret, application-name ,redirect ，session name of app2.

Log in to app1 first, then log in to app2. Then switch back to app1. After refreshing, it is found that it is expired. After a few seconds, when I went back to refresh app2, it also expired.

![image](https://user-images.githubusercontent.com/42430068/174574916-bf4a0640-3614-484d-a754-107af4f1b427.png)
![image](https://user-images.githubusercontent.com/42430068/174575057-569d606a-35d4-49f1-a171-289d789977eb.png)
![image](https://user-images.githubusercontent.com/42430068/174575759-993a263a-ff05-4f77-9edb-9f6f207c98ed.png)

**Comment by seriouszyx** [comment]
The cookie name conflict causes it. You can set a custom cookie name for the spring boot application.

ref: https://stackoverflow.com/questions/44657449/how-to-set-cookie-name-in-a-spring-boot-application-running-in-a-standalone-tomc
