### ISSUE TITLE
no captcha provider found

### ISSUE THREAD

**Issue by RongerW** [casdoor/casdoor#807]
![image](https://user-images.githubusercontent.com/34206989/174699465-dcd4c85b-6f1b-4280-9d33-5dffd7f5f9e0.png)
i am set provider in my app.
but when i use captcha login, i got  captcha provider found error
the error appear in request uri:/api/get-captcha?applicationId=admin/app-built-in&isCurrentProvider=false

**Comment by nomeguy** [comment]
@Resulte

**Comment by RongerW** [comment]
the mean is casdoor don't support email login?
or how do what to support this?

**Comment by Resulte** [comment]
Casdoor support email login when you add correct Email Provider and set it in your app.
<img width="449" alt="Screen Shot 2022-06-21 at 10 30 30" src="https://user-images.githubusercontent.com/34178764/174705925-e7916e50-93f8-4e39-8a5c-38e8adebf131.png">
<img width="476" alt="Screen Shot 2022-06-21 at 10 30 35" src="https://user-images.githubusercontent.com/34178764/174705938-4a06cd35-717f-4bc9-9eed-a48b01c69fde.png">
@RongerW

**Comment by RongerW** [comment]
![image](https://user-images.githubusercontent.com/34206989/174708286-7f1cd97f-dd29-49e8-9cac-6d51236035ef.png)
i don't known what set is corrent.
but in your online demo , i got same error.

in this request, the isCurrentProvider effect what?
