### ISSUE TITLE
Support two-factor authentication (2FA)

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#81]
See what's 2FA/MFA: https://en.wikipedia.org/wiki/Multi-factor_authentication

We will add a boolean switch at: https://door.casbin.com/applications/app-built-in

![image](https://user-images.githubusercontent.com/3787410/120912019-64abd200-c6be-11eb-9cec-e1010d844523.png)

When the application enables 2FA, when a user tries to login the application with password, we should do an additional check, either via Email or phone verification code.

We have a closed PR here: https://github.com/casdoor/casdoor/pull/148 , which can be used as a reference.

**Comment by Kininaru** [comment]
I searched in Google but I can not find a 2FA module for Golang, but I found several encapsulations. 

I think we can use the following function from this repo: 
https://github.com/robbiev/two-factor-auth/blob/cfbfa44e9f6a3041489c8a27943fcbf5d6365405/main.go#L28

I will work on this if no one else wants to complete the issue.

**Comment by sh1luo** [comment]
I have done it. :)

**Comment by Kininaru** [comment]
@sh1luo ok

**Comment by hsluoyz** [comment]
@sh1luo where? I didn't remember we have it..

**Comment by hguerrerojaime** [comment]
I'm also interested in this feature, are there any updates for this?
