### ISSUE TITLE
syncers bug

### ISSUE THREAD

**Issue by 704237006** [casdoor/casdoor#817]
syncers initialization is OK. After deleting the data in the user table of the casdoor library, it can be synchronized from the original system normally. However, if you change the data in the user table of the original system, you cannot synchronize this change to the user table of the casdoor table .

**Comment by 704237006** [comment]
![image](https://user-images.githubusercontent.com/42430068/174957563-b3140a6f-9cbd-400b-8456-e9d1035846fe.png)
![image](https://user-images.githubusercontent.com/42430068/174957611-514e7591-2d8b-4eb1-995a-9e4d456ba807.png)
should search the user record with onwer and name, but used onwer and ID.

**Comment by hsluoyz** [comment]
@704237006 can you make a PR to fix it?

**Comment by 704237006** [comment]
> @704237006 can you make a PR to fix it?
here : fix syncers bug
https://github.com/casdoor/casdoor/pull/822#issuecomment-1162731473

**Comment by hsluoyz** [comment]
@704237006 your ID should be mapped to Casdoor's ID, there's no issue here.
