### ISSUE TITLE
How can I use Casdoor in a Chrome extension?

### ISSUE THREAD

**Issue by nexmoe** [casdoor/casdoor#827]
Some extensions need a user login function.

**Comment by hsluoyz** [comment]
@seriouszyx @Resulte @ComradeProgrammer @leo220yuyaodog any advice on how to implement this?

**Comment by wenxuan70** [comment]
Hi @nexmoe, you can refer to my repository [casdoor-chrome-extension](https://github.com/wenxuan70/casdoor-chrome-extension)
First, you need to configure the variables `config` and `extensionId` in the `src/popup.js` file
```js
const extensionId = "your extension id";

const config = {
    endpoint: "your endpoint", // e.g. "http://localhost:8000"
    clientId: "your client id",
    redirectUri: `https://${extensionId}.chromiumapp.org`,
    applicationName: "your application name"
}
```
Then, you need to configure `host_permissions` in the `manifest.json` file
```json
"host_permissions": [
  "<your endpoint>/*"
]
```

**Comment by hsluoyz** [comment]
@nexmoe plz see: https://github.com/casdoor/casdoor-chrome-extension
