### ISSUE TITLE
Type with Provider support Microsoft Office365 has issues

### ISSUE THREAD

**Issue by hungtv31** [casdoor/casdoor#842]
Please support integrate with  Microsoft Office365

**Comment by nomeguy** [comment]
@hungtv31 can you give more details? better with video and screenshot

**Comment by hungtv31** [comment]
@nomeguy 
As you can see. There are two type ADFS and AzureAD. What is difference between them
![image](https://user-images.githubusercontent.com/12571167/177033321-2266ed00-99b6-4ac1-816f-b02e9dc87fa7.png)
And I do not see any guild line about Azure AD on document (https://casdoor.org/docs/provider/oauth/overview).
please add more!

**Comment by hungtv31** [comment]
And I try to login via link demo: https://door.casdoor.com/login but has error, I can not login.
![image](https://user-images.githubusercontent.com/12571167/177034622-1a1c2d9b-d360-4217-9b51-4ee7c204218e.png)
Error:
![image](https://user-images.githubusercontent.com/12571167/177034708-86b45409-d021-4ab3-afe6-2ddfb91b4abd.png)

**Comment by leo220yuyaodog** [comment]
> @nomeguy As you can see. There are two type ADFS and AzureAD. What is difference between them? ![image](https://user-images.githubusercontent.com/12571167/177033321-2266ed00-99b6-4ac1-816f-b02e9dc87fa7.png) And I do not see any guild line about AzureAD on docs (https://casdoor.org/docs/provider/oauth/overview). Please add more!

Azure AD is Microsoft Azure certification https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/auth-oauth2
We will add the documentation about Aure AD.

**Comment by nomeguy** [comment]
@hungtv31 

> And I try to login via AzureAD by link demo: https://door.casdoor.com/login but has error, I can not login.

It's because our AzureAD app registration has expired. We have re-configured it. You can try it now again, it's working.

> As you can see. There are two type ADFS and AzureAD. What is difference between them?

- If you are using Windows Servers, you can use ADFS: https://docs.microsoft.com/en-us/windows-server/identity/active-directory-federation-services 
- If you are using Azure cloud, you can use AAD: https://azure.microsoft.com/en-us/services/active-directory/

**Comment by hungtv31** [comment]
@nomeguy 
I try to re-login. but it has another issues. please check again!
![image](https://user-images.githubusercontent.com/12571167/177044143-05813dfe-90bf-405e-863a-4893cf1db051.png)

**Comment by nomeguy** [comment]
@hungtv31 can you paste the whole URL here?

**Comment by hungtv31** [comment]
@nomeguy 
The link in URL:
https://door.casdoor.com/callback?error=access_denied&error_description=AADSTS650056%3a+Misconfigured+application.+This+could+be+due+to+one+of+the+following%3a+the+client+has+not+listed+any+permissions+for+%27AAD+Graph%27+in+the+requested+permissions+in+the+client%27s+application+registration.+Or%2c+the+admin+has+not+consented+in+the+tenant.+Or%2c+check+the+application+identifier+in+the+request+to+ensure+it+matches+the+configured+client+application+identifier.+Or%2c+check+the+certificate+in+the+request+to+ensure+it%27s+valid.+Please+contact+your+admin+to+fix+the+configuration+or+consent+on+behalf+of+the+tenant.+Client+app+ID%3a+621cc0f0-055f-433f-9894-bfa1bfde169d.%0d%0aTrace+ID%3a+49c42f99-4439-44f6-8f47-b57c5c325b00%0d%0aCorrelation+ID%3a+aa2d62f8-e233-4396-aac6-8ee151122ec3%0d%0aTimestamp%3a+2022-07-03+15%3a28%3a36Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d650056&state=JmFwcGxpY2F0aW9uPWFwcC1idWlsdC1pbiZwcm92aWRlcj1wcm92aWRlcl9jYXNkb29yX2F6dXJlYWQmbWV0aG9kPXNpZ251cA%3d%3d#

**Comment by nomeguy** [comment]
@hungtv31 but I tried and it worked.

@leo220yuyaodog can you try it?

**Comment by hungtv31** [comment]
@nomeguy 
I have just run it on chrome --> it has **error**.
I have just run it on firefox --> it is **ok**

**Comment by leo220yuyaodog** [comment]
> @hungtv31 but I tried and it worked.
> 
> @leo220yuyaodog can you try it?

I meet the same error on chrome.
https://door.casdoor.com/callback?error=access_denied&error_description=AADSTS650056%3a+Misconfigured+application.+This+could+be+due+to+one+of+the+following%3a+the+client+has+not+listed+any+permissions+for+%27AAD+Graph%27+in+the+requested+permissions+in+the+client%27s+application+registration.+Or%2c+the+admin+has+not+consented+in+the+tenant.+Or%2c+check+the+application+identifier+in+the+request+to+ensure+it+matches+the+configured+client+application+identifier.+Or%2c+check+the+certificate+in+the+request+to+ensure+it%27s+valid.+Please+contact+your+admin+to+fix+the+configuration+or+consent+on+behalf+of+the+tenant.+Client+app+ID%3a+621cc0f0-055f-433f-9894-bfa1bfde169d.%0d%0aTrace+ID%3a+5feedf50-eee7-470a-aed9-fdf7f4209000%0d%0aCorrelation+ID%3a+5d058c99-7758-4253-8aa7-060155019689%0d%0aTimestamp%3a+2022-07-03+15%3a54%3a33Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d650056&state=JmFwcGxpY2F0aW9uPWFwcC1idWlsdC1pbiZwcm92aWRlcj1wcm92aWRlcl9jYXNkb29yX2F6dXJlYWQmbWV0aG9kPXNpZ251cA%3d%3d#
![image](https://user-images.githubusercontent.com/71440988/177047478-2257b66d-2159-4df2-b3d0-f0c8b49463fd.png)

**Comment by nomeguy** [comment]
@hungtv31 did you see this commit: https://github.com/casdoor/casdoor/commit/b8e324cadf49f7818143665a523124b4640ab601 ? Can you try the latest release to see if it is fixed?

**Comment by leo220yuyaodog** [comment]
> @leo220yuyaodog I saw you have fix code with the commit: [casdoor/goth@473bc70](https://github.com/casdoor/goth/commit/473bc7010ec27828f57cb6a2b84332112efa9af8) I got new code and re-run. but still have issue. I removed the parameter: &resource=https://graph.windows.net/ It work well :) please check again. Thank you very much!

Yes, removed the parameter: &resource=https://graph.windows.net/ it work well. But it just return the user's displayname, azurad document says we can get all the basic information of the user. I try others scope like openid+profile, it faild. Maybe the results are good now.

**Comment by nomeguy** [comment]
@hungtv31 docs are also added: https://casdoor.org/docs/provider/oauth/azureAD
