### ISSUE TITLE
Feature Request: Expose the casbin API to frontend for current user

### ISSUE THREAD

**Issue by KrishnaPG** [casdoor/casdoor#846]
Please consider exposing the underlying casbin API in the casdoor SDK (JS).

**Comment by hsluoyz** [comment]
@KrishnaPG which API do you need?

**Comment by KrishnaPG** [comment]
In the front-end, it is usually required to disable some routes, buttons and menus based on the permissions of the current user.

For example, "create new record" button disabled for read-only permitted users.

Currently, using Casdoor as the authorization system, there does not seem to be anyway for the frontEnd to tell which routes/menus/buttons are permitted for the current user, unless the action is actually performed and server accepts/rejects the action.

The API required from the casdoor of underlying casbin is: know in a single call which all actions/resources on the page have access to the current user and which are not.  i.e. given a list of resources/actions return back yes/no for each of them in a single API call.

To be specific:

- the [batchEnforce](https://casbin.org/docs/en/management-api#batchenforce) API of casbin
- the [GetAllObjects](https://casbin.org/docs/en/management-api#getallobjects) - needed for enumerating all objects from the frontEnd side (useful to construct routes/buttons etc.)
- [GetAllActions](https://casbin.org/docs/en/management-api#getallactions)
- [GetAllRoles](https://casbin.org/docs/en/management-api#getallroles)

**Comment by hsluoyz** [comment]
@seriouszyx
