### ISSUE TITLE
Use Casdoor to manage Casbin DB table

### ISSUE THREAD

**Issue by KrishnaPG** [casdoor/casdoor#849]
The documentation says: 

> With [Casbin](https://casbin.org/) based authorization management, Casdoor supports ACL, RBAC, ABAC, RESTful accessing control models.

But nowhere any information could be found how to validate a user with RBAC or RESTful access control.

Been struggling to find out how to use the casdoor for authorization. 

1. Created the users (imported them from ldap)
2. Created permissions
3. Retrieving JWT token from front-end
4. ???? 

How to use the JWT token to validate the access permissions (i.e. if the user has roles required etc.), since the JWT does not include the roles for the user

**Comment by thanhpd56** [comment]
I'm confusing about this too.

**Comment by sersoong** [comment]
This is very complicated.
Maybe this is semi-manufactures.
No example.

**Comment by redochenzhen** [comment]
any updates?  I'm stuck here, too.

**Comment by zhuyalun888** [comment]
any updates? I'm stuck here, too.

**Comment by KrishnaPG** [comment]
The new APIs seem to be close to achieving this. But not clear on the exact setup/sequence. Some relevant info can be found here for those following this thread: https://github.com/casdoor/casdoor/pull/955#issuecomment-1206368214

**Comment by KrishnaPG** [comment]
This can be resolved once the TODOs in the https://github.com/casdoor/casdoor/issues/981 are done.

**Comment by hsluoyz** [comment]
@KrishnaPG finally done by: https://github.com/casdoor/casdoor/pull/1317
