### ISSUE TITLE
Feature Request: Initialize casdoor from configuration file

### ISSUE THREAD

**Issue by Abingcbc** [casdoor/casdoor#851]
Currently, users have to log in Casdoor from a browser or call restful API to add an `application`. Both methods require users to make some operations after installation and then Casdoor can be ready to use.

For `out-of-the-box` feature, Casdoor can support initializing the database from a user-defined configuration file.

--------------

The configuration file is named `init_data.json`.
This file will include four parts:

1. Organization
2. Application
3. User
4. Provider

Each one is an array. The data structure of the array element is mapped to the ones in the source code of Casdoor.

When initializing, Casdoor will only create. If the target object exists, Casdoor will skip instead of replacing or updating.

**Comment by fanux** [comment]
Yes, [sealos](https://github.com/labring/sealos) want integrate casdoor, we need this feature~
