### ISSUE TITLE
bug: invalid redirect after sign up

### ISSUE THREAD

**Issue by tetra12** [casdoor/casdoor#856]
Hello I'm using Casdoor v1.62.0 

Currently, when a user successfully `signs up`, a page occurs with the `Your account has been created!` message.
Two issues with that

1. When you click a `Sign In` button, you are redirected to the `${baseUrl}/login` page, which is invalid.
The valid page for my app should look smth like this: `http://localhost:8000/login/oauth/authorize?client_id=cb92c38bb2cd6d3366a4&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauth&scope=read&state=web-console`

2. Following the best practices and a Google example, a `signed up` user needs to be automatically redirected to the valid page `http://localhost:8000/login/oauth/authorize?client_id=cb92c38bb2cd6d3366a4&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauth&scope=read&state=web-console`. Pls, remove the extra `Sign In` button .
![signin](https://user-images.githubusercontent.com/45828526/177138893-e96b3c28-c97b-4ef1-a0f9-b25ca276331c.png)

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by seriouszyx** [comment]
After debugging, I think we need to make two changes:
1. [casdoor-js-sdk/sdk.ts](https://github.com/casdoor/casdoor-js-sdk/blob/72d558769d5cfd7d97ea9d2b77c2027b4f0c2b54/src/sdk.ts#L52). The `getSignupUrl` method doesn't pass params such as client_id and redirect_uri to casdoor. So after successful signup, casdoor will not get this params to jump.
2. [casdoor/SignupPage.js](https://github.com/casdoor/casdoor/blob/master/web/src/auth/SignupPage.js). The signup page should parse the params passed by SDK and build the valid signin URL.

/cc @hsluoyz

**Comment by seriouszyx** [comment]
@tetra12 I made a demo video using [casnode](https://github.com/casbin/casnode).  Now after successful signup, it will jump to the valid signin URL. 


[Casnode.webm](https://user-images.githubusercontent.com/33992371/178295975-65601bd6-b39b-49fa-8e0b-3b0f234ca972.webm)

**Comment by hsluoyz** [comment]
@tetra12

**Comment by tetra12** [comment]
@hsluoyz I'll check it tomorrow. Thanks for your fix @seriouszyx

**Comment by Sesota** [comment]
This issue shouldn't be closed, since the OP has already mentioned a 2nd issue:

> Following the best practices and a Google example, a signed up user needs to be automatically redirected to the valid page http://localhost:8000/login/oauth/authorize?client_id=cb92c38bb2cd6d3366a4&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauth&scope=read&state=web-console. Pls, remove the extra Sign In button .

I assume that what OP requested was not to ask for the credentials again after sign up is done. The app should initiate a session instead. Wdyt?
