### ISSUE TITLE
Sending code to email stopped working. How can I find the error?

### ISSUE THREAD

**Issue by Kalinin-Andrey** [casdoor/casdoor#859]
Hi all!
I am using a ready-made Casdoor container image. Sending code to email stopped working. There are no error messages on standard output. How can I find the error? Where to enable debug level logging?
Thank you!

**Comment by hsluoyz** [comment]
@Kalinin-Andrey did you try the Email tester? https://github.com/casdoor/casdoor/pull/819

**Comment by Kalinin-Andrey** [comment]
@hsluoyz, thanx for Email tester, I did not know!)
I tried the tester - sending emails works, all test emails were sent.

And I seem to have found the problem, look at the screen: password recovery goes through a custom application, and the request goes to the built-in application, and yes, the provider was not set there.
![pass_recovery](https://user-images.githubusercontent.com/8151806/177367294-f60efa3d-2df0-47ad-85f6-985e20282dcc.png)

When I set the provider on the built-in application, the email was sent.

Apparently, this is a bug and password recovery should work through the current application.
Thank you.

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by Kalinin-Andrey** [comment]
@hsluoyz, thank you! The error message is right. But I want to clarify once again, that to send a letter to a user of a custom application, the settings used are not for this application, but for the built-in one. This is right? Was that intended or is this a bug?

**Comment by hsluoyz** [comment]
@Kalinin-Andrey the expected behavior is that the email will be sent via the first Email provider of the application, failed if there's no Email provider for the application.

**Comment by hsluoyz** [comment]
@leo220yuyaodog
