### ISSUE TITLE
WORKDIR changed in Dockerfile

### ISSUE THREAD

**Issue by aecra** [casdoor/casdoor#860]
See [WORKDIR /app](https://github.com/casdoor/casdoor/blob/ec296215471b1e2e35add3826f07ec5bd8165970/Dockerfile#L17).

WORKDIR was changed from "/" to "/app".

But there are no synchronous changes to the use of docker in the documentation.

**Comment by hsluoyz** [comment]
The commit: https://github.com/casdoor/casdoor/commit/cd902a21ba3ad9441bf3c5f6491dced49dfa7177 caused this.

@atompi plz change the work dir back to "/" by making a new PR and keep the docs up-to-update.
