### ISSUE TITLE
Can't edit admin account  while deploying on K8s

### ISSUE THREAD

**Issue by LunziSTU** [casdoor/casdoor#863]
Using external databases. 
Only the admin account does not show the edit form.

![image](https://user-images.githubusercontent.com/50568827/177473450-6417e15d-8751-4b0f-a0b5-1270d85e8cb4.png)

**Comment by hsluoyz** [comment]
See: https://casdoor.org/docs/organization/accountCustomization

**Comment by LunziSTU** [comment]
The reason is related to this  #issue：[The reason is related to this issue](https://github.com/casdoor/casdoor/issues/579)

**Comment by hsluoyz** [comment]
@LunziSTU https://github.com/casdoor/casdoor/issues/579 has been fixed in: https://github.com/casdoor/casdoor/pull/831
