### ISSUE TITLE
[Question] Permission when login by AzureAD provider

### ISSUE THREAD

**Issue by hungtv31** [casdoor/casdoor#864]
Hi all,
I set up login use provider by AzureAD. I created app and set appID and secret. But I can not login by it.
Can you help me. I think that I miss permisson on portal. but i do not it.
![image](https://user-images.githubusercontent.com/12571167/177604635-fa126254-e9a2-458c-ac1b-b6f2e35113f7.png)

**Comment by leo220yuyaodog** [comment]
![image](https://user-images.githubusercontent.com/71440988/177659685-c50871e7-e35f-4dbd-8dd0-2650727f93fc.png)
![image](https://user-images.githubusercontent.com/71440988/177660019-391b0d42-affa-4ac1-9361-ad65f14e9eff.png)

@hungtv31 Please see the API permission and Support account type.

**Comment by leo220yuyaodog** [comment]
@hungtv31 
Hi, I think your configuration and mine are a little different. Please check it again. Your application maybe use the second type. I try it. I also cannot use this type to login. If you do want to use the second type, now I only have personal account, no azuread organization account. I can't help you very well right now.
![image](https://user-images.githubusercontent.com/71440988/177783263-239aead1-204d-49e2-adbb-9db5a2b3dd5d.png)

**Comment by leo220yuyaodog** [comment]
@hungtv31 
You can grant admin consent to resolve the issue.

![A_DZ%OP%_@S 6Q)D25VESSM](https://user-images.githubusercontent.com/71440988/178001188-c40ea8ca-10fa-4e14-a6f2-71ce12fdb321.png)
