### ISSUE TITLE
WeChat state parameter is too long

### ISSUE THREAD

**Issue by gopecan** [casdoor/casdoor#867]
If the login page of the Casdoor app (not app-built-in) is opened on the WeChat client and the WeChat is used to log in, the WeChat returns the error "state parameter is too long".

**Comment by hsluoyz** [comment]
@gopecan similar to: https://github.com/casdoor/casdoor/issues/504

We need to make the state shorter. Perhaps this is a possible solution: https://github.com/casdoor/casdoor/issues/564

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/94b6eb803da1c476f47a8b857a4493a19efac662
