### ISSUE TITLE
Integrating with showdoc via OAuth 2.0 error

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#874]
showdoc: https://github.com/star7th/showdoc

showdoc's OAuth2: https://github.com/star7th/showdoc/issues/973

Error:

![@`(J30 0A0VADE{0SJL 9ZX](https://user-images.githubusercontent.com/3787410/178115475-b9dd9a52-cb81-40b8-9ead-a97dd78d4b7b.jpg)

The config:

![@`(J30 0A0222VADE0SJL 9ZX](https://user-images.githubusercontent.com/3787410/178115501-d9fb2046-27e1-40e7-a24b-0e028c1e350c.png)

**Comment by star7th** [comment]
casdoor获取用户info的路径是  /api/get-account
