### ISSUE TITLE
Can't login with admin/123 use latest docker image version(casbin/casdoor v1.67.0)

### ISSUE THREAD

**Issue by bobhu2k** [casdoor/casdoor#876]
from  1.63.0  - 1.67.0  can't login :

Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at AuthBackend.js:62:22

<img width="827" alt="image" src="https://user-images.githubusercontent.com/8317400/178184141-aee7dc1f-7b4b-452b-9f1a-814b4e4c6acb.png">

**Comment by bobhu2k** [comment]
db version : postgres:14-alpine

**Comment by hsluoyz** [comment]
@bobhu2k is v1.62.0 OK?

**Comment by hsluoyz** [comment]
@Abingcbc @ComradeProgrammer

**Comment by waltcow** [comment]
meet same issue in latest version of casdoor

**Comment by hsluoyz** [comment]
@ComradeProgrammer

**Comment by leo220yuyaodog** [comment]
Commit https://github.com/casdoor/casdoor/commit/b4bf734fe82df908bede10b1a554d56bd221255e add cors filter.  After 1.63.0 image, you need to set `origin` in `app.conf`, make sure the `headorigin` is same as `origin` in `app.conf` https://github.com/casdoor/casdoor/blame/master/routers/cors_filter.go#L34-L37. Or you can choose not to fill it in and there will be no origin judgment.

**Comment by bobhu2k** [comment]
@leo220yuyaodog  got it,tks!

**Comment by bobhu2k** [comment]
@leo220yuyaodog but when i config origin(eg: http://localhost:3000) ,how to use admin to login in (http://localhost:8000)?

**Comment by leo220yuyaodog** [comment]
> @leo220yuyaodog but when i config origin(eg: http://localhost:3000) ,how to use admin to login in (http://localhost:8000)?

See the document https://casdoor.org/docs/basic/server-installation#production-mode. You can build the frontend.

**Comment by bobhu2k** [comment]
the origin config  support multiple domain？

**Comment by SIMULATAN** [comment]
This issue just happened to me. Following a binary search, I found the fix to be setting `copyrequestbody = true` in the `app.conf`. Apart from the DB settings mentioned in the setup guide, I didn't change anything.

**Comment by jinyangyu** [comment]
Title: Login fails in v1.67.0 Docker image, removing origin in app.conf does not help

Comment:

Hi, I’m still unable to log in using the latest Docker image (casbin/casdoor:latest, v1.67.0).

I tried removing origin and originFrontend in app.conf as suggested in previous issues.

The container is using the correct app.conf.

Database connection works.

Login returns:

{
  "status": "error",
  "msg": "unexpected end of JSON input",
  "sub": "",
  "name": "",
  "data": null,
  "data2": null,
  "data3": null
}
Everything else seems running fine, but login fails. Could you provide guidance?

Thanks!

**Comment by hsluoyz** [comment]
@jinyangyu don't dig old issue. Create new issue if needed.
