### ISSUE TITLE
Different domain names, sso login problem?

### ISSUE THREAD

**Issue by chenjpu** [casdoor/casdoor#881]
Integrate two different app through cas. After logging in app1, it is expected to access app2 directly without login. 
After actual operation, no matter which app is logged in first, another app needs to be verified again.

**Comment by chenjpu** [comment]
https://github.com/casdoor/casdoor/issues/530

**Comment by hsluoyz** [comment]
Dup with: https://github.com/casdoor/casdoor/issues/530
