### ISSUE TITLE
Wrong usage of getUserById  

### ISSUE THREAD

**Issue by waltcow** [casdoor/casdoor#884]
When I review code of syncer_user logic, I found something maybe wrong

https://github.com/casdoor/casdoor/blob/895cdd024d52e29ea9df61a0b6ea4219c6e44ac4/object/syncer_user.go#L115-L134

https://github.com/casdoor/casdoor/blob/801302c6e72f8cf82ed563a92694c6ce329456cd/util/string.go#L87-L95

```go
owner, name := util.GetOwnerAndNameFromId(user.GetId()) 
getUserById(owner, name)  
```
when we call `getUserById` method, it should pass through user owner and id rather than owner and name 

https://github.com/casdoor/casdoor/blob/895cdd024d52e29ea9df61a0b6ea4219c6e44ac4/object/user.go#L220-L237

**Comment by hsluoyz** [comment]
@waltcow can you explain a little bit more?

**Comment by waltcow** [comment]
@hsluoyz I have just edit this issue description

**Comment by hsluoyz** [comment]
Actually this is not a bug, won't fix

**Comment by waltcow** [comment]
so misleading code
