### ISSUE TITLE
Add "jti" (JWT ID) to JWT

### ISSUE THREAD

**Issue by KricYi** [casdoor/casdoor#899]
Token format  default JWT is too long ，and  JWT-EMPTY info is too little information.
It is recommended to add a unique identifier  "jti" (JWT ID), Developers can associate session context through jti。

The [JWT spec](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.7) mentions a jti claim which allegedly can be used as a nonce to prevent replay attacks:
The "jti" (JWT ID) claim provides a unique identifier for the JWT. The identifier value MUST be assigned in a manner that ensures that there is a negligible probability that the same value will be accidentally assigned to a different data object; if the application uses multiple issuers, collisions MUST be prevented among values produced by different issuers as well. The "jti" claim can be used to prevent the JWT from being replayed. The "jti" value is a case-sensitive string. Use of this claim is OPTIONAL.

**Comment by KricYi** [comment]
Can the table "token" ower + name be used as "jti"

**Comment by hsluoyz** [comment]
@KricYi maybe. Can you make a PR?

**Comment by hsluoyz** [comment]
@RyaoChengfeng
