### ISSUE TITLE
Can you add the logout URL as get mode in the system

### ISSUE THREAD

**Issue by jyxenlink** [casdoor/casdoor#902]
The system logout API is post mode, but many third-party business systems don ’t support this mode. Can you add the logout URL as get mode in the system, because this URL address logout mode is more general and convenient for system integration. I hope to adopt it!

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by leo220yuyaodog** [comment]
@jyxenlink  My understanding is that add a logout page, after visit the logout url as get mode, go to the logout page. Then click the logout button to send the existing POST request . Is that okay?

**Comment by hsluoyz** [comment]
@leo220yuyaodog why not add an additional GET route for the same handler? It doesn't have to be a logout page, an API that serves GET, returns 200 and do the logout job is also acceptable?
