### ISSUE TITLE
Default action prevents admin to login in

### ISSUE THREAD

**Issue by aecra** [casdoor/casdoor#904]
You go into the permission editor, and then return, this default permission is saved, and it is associated with the admin, so the administrator cannot log in.

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by FoeverA0** [comment]
Hi can I grab this issue?

**Comment by hsluoyz** [comment]
@FoeverA0 go ahead!

**Comment by FoeverA0** [comment]
@aecra I think I found the problem because the default permissions did not set admin to sub user so admin can't log in, I'm working to setting sub user to admin when default permissions initialized.

**Comment by holtenko** [comment]
same issue 😥

**Comment by hsluoyz** [comment]
@FoeverA0 we can add a built-in permission to allow global admins (users in `built-in` org) to do anything. Add it to `InitDb()`

![image](https://user-images.githubusercontent.com/3787410/180595905-89e989da-ebc3-40f3-93ba-6ee3ac803fc1.png)

**Comment by FoeverA0** [comment]
@hsluoyz Thanks for your help, it was very helpful to me

**Comment by FoeverA0** [comment]
#907
