### ISSUE TITLE
Integrate Spring Cloud Gateway with Casdoor

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#905]
https://spring.io/projects/spring-cloud-gateway

About how to develop a plugin to integrate Casdoor with a gateway software, plz refer to:

- APISIX: https://apisix.apache.org/docs/apisix/plugins/authz-casdoor/
- Kong: https://github.com/casdoor/casdoor/issues/280

Example repo created here: https://github.com/casdoor/springcloud-gateway-example

**Comment by conghuhu** [comment]
I try to solve.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/springcloud-gateway-example/pull/1

Example repo is: https://github.com/casdoor/springcloud-gateway-example
