### ISSUE TITLE
After disabling the sign up, the "sign in with code" disappears

### ISSUE THREAD

**Issue by dirname** [casdoor/casdoor#906]
This issue will cause registered users to be unable to sign in with a verification code after the registration of some applications is stopped.

<img width="693" alt="Screenshot 2022-07-24 010600" src="https://user-images.githubusercontent.com/18101258/180615487-274ae5e7-961e-4f40-8123-3ab548eaadd1.png">

<img width="685" alt="Screenshot 2022-07-24 010745" src="https://user-images.githubusercontent.com/18101258/180615491-f2958729-def3-4d66-90ef-10339073c845.png">

**Comment by hsluoyz** [comment]
@RyaoChengfeng

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casdoor/casdoor/pull/925
