### ISSUE TITLE
Social Signup or Linking causes 500 Internal Server Error

### ISSUE THREAD

**Issue by KrishnaPG** [casdoor/casdoor#918]
The following scenarios all are cause this error:

- Enable Signup option for Social buttons (google, github etc.) and Sign-in with any social login. The first signing will cause 500 Internal Server Error. (If you try again, it will work fine). 
- Login with eMail and password, and try to link a social account. It will result in the server 500 error.

It looks like whenever a new user entry is created because of Social login/singup/linking activity the server is returning 500 error and the webpage gets stuck with spinning wheel. Please fix this.

![image](https://user-images.githubusercontent.com/4610831/181159312-ad50c7d2-b1fb-4d65-a308-772c99cb6c38.png)

**Comment by hsluoyz** [comment]
@qianxi0410
