### ISSUE TITLE
’Enable code sign‘ is not displayed in the login page

### ISSUE THREAD

**Issue by jyxenlink** [casdoor/casdoor#921]
In casdoor_v1.75.1, when 'enable sign' is disabled, 'enable code sign' will be disabled together. This is a bug.

**Comment by imp2002** [comment]
When enableSignUp is false, the Footer not be rend. I'll try fix it.

https://github.com/casdoor/casdoor/blob/88652442623020e15074e7c7dba1430381e86ccc/web/src/auth/LoginPage.js#L508

https://github.com/casdoor/casdoor/blob/88652442623020e15074e7c7dba1430381e86ccc/web/src/auth/LoginPage.js#L538-L547
