### ISSUE TITLE
Admins should not be allowed to add third-party login for their members

### ISSUE THREAD

**Issue by qianxi0410** [casdoor/casdoor#924]
Now I have two accounts, one admin and one user.
In the system, the administrator is allowed to click the link button under the user account:
![2022-07-28_18-06](https://user-images.githubusercontent.com/55543743/181480311-35a6e8e4-0da1-4ba2-9368-9546d931e667.png)

And the weirder behavior is that if the administrator clicks the link button at this time, he will add a third-party login for himself instead of user.
I think, the front end should avoid this from happening.

**Comment by hsluoyz** [comment]
@qianxi0410 good point! Here's another similar issue: https://github.com/casdoor/casdoor/issues/888 . I think you can fix them together in one PR

**Comment by qianxi0410** [comment]
@hsluoyz Yes, they are very similar.
Then the logic now becomes, only the user can link/unlink his own three-way link, the administrator does not have this right, right? Just to make sure!

**Comment by qianxi0410** [comment]
@hsluoyz Got it, I'll try to fix it.
