### ISSUE TITLE
Hope the project support arm  CPU

### ISSUE THREAD

**Issue by WarlockFish** [casdoor/casdoor#926]
Hope the project support arm  CPU，example  raspberry-pi et。
 
In  arm64，  I can Build Casdoor Go backend code，but I can not build Casdoor frontend code 。

**Comment by hsluoyz** [comment]
@WarlockFish 

> but I can not build Casdoor frontend code 

What's the error?

**Comment by Resulte** [comment]
My M1 MAC is arm64 core. And I can build Casdoor frontend code successfully on this MAC. So I think that's not the arm64 caused you build failed. @WarlockFish

**Comment by WarlockFish** [comment]
I know why I can't compile it, I use `node==18.7` 。 when use `node==16` , Casdoor frontend code can build successfully。

**Comment by hsluoyz** [comment]
Closed as resolved
