### ISSUE TITLE
Failed to update user information using java SDK

### ISSUE THREAD

**Issue by zhuqiangqiang** [casdoor/casdoor#930]
Failed to update user information using java SDK. After debugging and checking, we found that the updated user interface returned 404, which can be updated in the test environment, and the above exception was reported in the production environment!
![QQ图片20220730204744](https://user-images.githubusercontent.com/28150189/181914995-c884876a-8f5d-4c5e-ad21-b09961b9df2d.jpg)

**Comment by hsluoyz** [comment]
@zhuqiangqiang user claimed it's their own setting's issue, closed here
