### ISSUE TITLE
how to set sqlite3?

### ISSUE THREAD

**Issue by WarlockFish** [casdoor/casdoor#937]
i set `driverName = sqlite` , then run :

```
xubuntu@xubuntu-VirtualBox:~/h/test$ docker run -p 8000:8000 -v /home/xubuntu/h/test/conf:/conf/ casbin/casdoor
panic: Unsupported driver name: sqlite

goroutine 1 [running]:
github.com/casdoor/casdoor/object.(*Adapter).open(0xc0000a5d40)
	/go/src/casdoor/object/adapter.go:103 +0xb2
github.com/casdoor/casdoor/object.NewAdapter({0xc00004290a, 0x6}, {0xc000042940, 0x10}, {0xc000042960, 0x7})
	/go/src/casdoor/object/adapter.go:76 +0xd0
github.com/casdoor/casdoor/object.InitAdapter(0x0)
	/go/src/casdoor/object/adapter.go:45 +0x76
main.main()
	/go/src/casdoor/main.go:37 +0xa7
```

**Comment by hsluoyz** [comment]
@WarlockFish 

1. Disable line 25 and enable line 27
2. Run `go mod tidy`

https://github.com/casdoor/casdoor/blob/1600615acad9810cd16937c0372aa6e3d75837f0/object/adapter.go#L17-L30

**Comment by hsluoyz** [comment]
Closed as resolved

**Comment by WarlockFish** [comment]
> 已解决关闭

 Why not open all database interfaces ？

**Comment by hsluoyz** [comment]
@WarlockFish also add docs: https://casdoor.org/docs/basic/server-installation#sqlite3

> Why not open all database interfaces ？

To avoid too many dependencies in go.mod

**Comment by zzjin** [comment]
Wired here, as with docker usage, the default docker image only supports mysql, users want to use `postgres` or `sqlite3` driver needs to build there docker image selves?

 When we say support many database drivers, we mean out of the box. anyone can use any db driver as their choice.

Why don't add 3 more dependencies in `go .mod`? Has there be some historical decision?

Just for note:
If main repo don't want to maintain all db drivers as dependency, we can open a new repo like `casdoor/dbdriver` and put all supported drivers there, and just import this new repo here, but I think the makes no sense?

**Comment by WarlockFish** [comment]
@hsluoyz 

Docker is for the convenience of users ，  It should support all database drivers。 I support @zzjin 's viewpoints.

**Comment by hsluoyz** [comment]
OK @zzjin @WarlockFish who can make a PR to enable all DBs in Go imports? I also would like to know the diff of Docker images after this change

**Comment by nomeguy** [comment]
Done: https://github.com/casdoor/casdoor/commit/d55ae7d1d2a9221dea3be80911c68eb9a275c3d0
