### ISSUE TITLE
Modify the link of  social app image url and put these images on the local server to improve the access speed.

### ISSUE THREAD

**Issue by jyxenlink** [casdoor/casdoor#942]
The social app image address of the login page is https://cdn.casbin.org/img/xxx.png , the access speed is slow. I suggest to modify the link and put these images on the local server to improve the access speed.

**Comment by imp2002** [comment]
I'm working on it.

**Comment by hsluoyz** [comment]
We need to:

1. Wrap all system images (not user avatar images) into: `StaticBaseUrl`, which is `https://cdn.casbin.org` by default.
2. If some images are missing from the above CDN, then add it by making a PR to: https://github.com/casbin/static

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by leo220yuyaodog** [comment]
> The social app image address of the login page is https://cdn.casbin.org/img/xxx.png , the access speed is slow. I suggest to modify the link and put these images on the local server to improve the access speed.

Your can modify the `StaticBaseUrl` in `web/src/Setting.js `
