### ISSUE TITLE
Reminder binding after registration causes the page to crash

### ISSUE THREAD

**Issue by BaiShaojie123123** [casdoor/casdoor#944]
![image](https://user-images.githubusercontent.com/24069576/182135837-05a911ff-73a4-496e-a587-6f15a98f8986.png)
 
image: casbin/casdoor:v1.78.0
linux 

mac
Source code docker

**Comment by BaiShaojie123123** [comment]
![image](https://user-images.githubusercontent.com/24069576/182136552-e9a9913b-55b7-4ba9-b1ca-a47aebf7a8de.png)
发现有如下报错

**Comment by qianxi0410** [comment]
It's reproduced for now, I'll fix it.

**Comment by qianxi0410** [comment]
Clicking this button will cause the `OAuthWidget` component to re-render. I didn't notice this in the last pr. I'm very sorry for the trouble.

**Comment by qianxi0410** [comment]
cc @hsluoyz
