### ISSUE TITLE
auth2 Jump error after binding

### ISSUE THREAD

**Issue by AubreySte** [casdoor/casdoor#947]
![image](https://user-images.githubusercontent.com/75111676/182276689-ef6be6ea-898f-45bb-a7c8-ef34d9ac71b2.png)

![image](https://user-images.githubusercontent.com/75111676/182276662-6d1b5ae9-b5bc-4e33-add6-7713de08d1c2.png)
When a new account is logged in with an account password, a github account is bound. Then click Complete Submission without jumping to the corresponding app's callback link. Instead, it jumps to the /null page

**Comment by AubreySte** [comment]
source code lastest

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by seriouszyx** [comment]
@AubreySte Can you provide a demo video (including the URL bar), because I wasn't able to reproduce this bug?

**Comment by hsluoyz** [comment]
@AubreySte this should already be fixed after PR: https://github.com/casdoor/casdoor/pull/999
