### ISSUE TITLE
How to realize dynamic switch of Enforcer of casbin？

### ISSUE THREAD

**Issue by biu111biu** [casdoor/casdoor#948]
Casdoor supports each application to customize its own casbin model. I want to know how Casdoor realizes that each application can find its own enforcer (the model and policy of each enforcer are different, so I understand that each user has have their own different enforcers); I now need to use Java to implement a function similar to Casdoor, where each application can define model and policy independently, but I am not sure about switching the enforcer corresponding to each user, I hope to learn from Casdoor I hope you can give me some advice, thank you very much!

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by seriouszyx** [comment]
@biu111biu In fact, in Casdoor, each permission corresponds to an enforcer, and `application` is just a resource type of permission. The `permission` supports specifying models and adapters to construct the enforcer. And the configuration of the `permission` is converted into policies and saved in the enforcer.

**Comment by biu111biu** [comment]
@seriouszyx 您好，感谢您的回复，但是我还是搞不太明白。目前casdoor是支持多应用，并且每个应用都可以自定义自己的model和policy。假如有的应用要使用rbac的权限模型，而有的需要使用abac的模型；实现这种需求的方案，我觉得有两种：1.分别为每一个应用创建各自的enforcer；2.在进行权限判断时找到不同的model和policy直接加载。我用第二种方案尝试过，发现直接在访问时动态加载model和policy成本比较大，导致访问速度变慢。但是第一种方案目前基于Java的spring框架实现起来又感觉不是很优雅。所以我想了解一下casdoor是怎么实现的每个应用都支持各自的enforcer。请您指教，谢谢

**Comment by biu111biu** [comment]
@seriouszyx 您好，感谢您的回复，但是我还是搞不太明白。目前casdoor是支持多应用，并且每个应用都可以自定义自己的model和policy。假如有的应用要使用rbac的权限模型，而有的需要使用abac的模型；实现这种需求的方案，我觉得有两种：1.分别为每一个应用创建各自的enforcer；2.在进行权限判断时找到不同的model和policy直接加载。我用第二种方案尝试过，发现直接在访问时动态加载model和policy成本比较大，导致访问速度变慢。但是第一种方案目前基于Java的spring框架实现起来又感觉不是很优雅。所以我想了解一下casdoor是怎么实现的每个应用都支持各自的enforcer。请您指教，谢谢

**Comment by hsluoyz** [comment]
@biu111biu plz modify text into English

**Comment by biu111biu** [comment]
> @biu111biu plz modify text into English

ok

**Comment by hsluoyz** [comment]
@biu111biu sorry for late response. The Casbin enforcer inside Casdoor is created dynamically, see: https://github.com/casdoor/casdoor/blob/d668022af047ac5dfe7a9a2560a7ab9a097473bf/object/permission_enforcer.go#L26
