### ISSUE TITLE
Suggest : organization can support multi-level departments

### ISSUE THREAD

**Issue by hlj** [casdoor/casdoor#949]
For enterprise applications, company->department->sub-department->user is the actual organizational structure. It is recommended to consider it.

**Comment by hsluoyz** [comment]
@hlj plz change to English

![image](https://user-images.githubusercontent.com/3787410/182649200-0273c656-76f1-4ab1-a5ca-3e7ac517507b.png)

**Comment by hlj** [comment]
It is suggested that the organization can support multi-level departments, and users belong to a specific department. For enterprise applications, company->department->sub-department->user is the actual organizational structure. It is recommended to consider it.

**Comment by hsluoyz** [comment]
@hlj plz modify the title and text, not appending new comment, thanks!

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casdoor/casdoor/issues/1828
