### ISSUE TITLE
Add Casbin model and policy management

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#95]
See: https://github.com/casbin/casdoor/issues/37

We once developed two similar systems: Casbin-Dashboard and Casbin-Cloud, but both projects failed finally. You can just grap some inspirations from them:

Casbin-Dashboard
=====

1. Source code: https://github.com/casbin/casbin-dashboard
2. Online demo: https://dashboard.casbin.org/

Casbin-Cloud
=====

1. Source code: https://github.com/casbin/openstack-policy-editor
2. Online demo: https://cloud.casbin.org/

However, don't copy them, because they have failed and I don't think their designs are good. Just use them as reference and starting point to understand this area.

**Comment by WindSpiritSR** [comment]
Can I work on it?
