### ISSUE TITLE
fix all frontend warnings

### ISSUE THREAD

**Issue by nomeguy** [casdoor/casdoor#958]
like

![image](https://user-images.githubusercontent.com/85475922/183026945-07bffc79-5689-4d4d-b904-546d478e6ba7.png)

**Comment by hsluoyz** [comment]
@joy0010 @AnjanaVakil @jakiuncle can anyone work on this?

**Comment by qianxi0410** [comment]
Now, with `yarn fix`, you can show these warnings to the console. @jakiuncle

**Comment by qianxi0410** [comment]
This issue should be closed by #983

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/pull/983
