### ISSUE TITLE
Need an option to enable the Verification Code without enabling Email or Phone code at login / registration

### ISSUE THREAD

**Issue by Zerek-Cheng** [casdoor/casdoor#972]

**Comment by hsluoyz** [comment]
@Zerek-Cheng what do you mean?

**Comment by Zerek-Cheng** [comment]
> @Zerek-Cheng what do you mean?
Without enabling mobile verification code and email verification code, just ask for the verification code when logging in & sign up

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casdoor/casdoor/issues/1175

**Comment by Zerek-Cheng** [comment]
> Replaced by: #1175

 @hsluoyz 你好 我的意思是在不使用邮箱/手机验证码的情况下，使用密码登录时校验字符/极验验证码
