### ISSUE TITLE
Can't login in at the authorization_endpoint.

### ISSUE THREAD

**Issue by aecra** [casdoor/casdoor#977]
version: 1.82.0

The page is blank, and it throw these errors:

![image](https://user-images.githubusercontent.com/34883050/183275974-8ceb066b-163a-4d77-8eae-23021aad3e3b.png)

**Comment by hsluoyz** [comment]
@aecra print:

- JS error stack
- Go error stack (if has)

**Comment by aecra** [comment]
There is no any JS error stack. It is SyntaxError. 

And there just a 301 request log from go.

```
2022/08/07 05:04:34.883 [D]  |     172.17.0.1| 304 |    229.986µs| nomatch| GET      /login/oauth/authorize
```

**Comment by hsluoyz** [comment]
@aecra I cannot give you any help with the current info you provided.

**Comment by hsluoyz** [comment]
Go to your DB, set the `accountItems` of the organization from empty to `[]`

**Comment by cccy0** [comment]
I repeated this problem   
started it with docker   
request url : `https://xxx.xxx.xxx/login/oauth/authorize?client_id=f208312d4aee1941d102&response_type=code&redirect_uri=http://localhost:9000/callback1&scope=read&state=casdoor`   
the request url of CSS and JS files is not correct   
![1660305982245](https://user-images.githubusercontent.com/29329157/184350632-d07e39e0-657a-4a21-8857-85b03d13f9d1.png)
