### ISSUE TITLE
RBAC with domains + Object resource types in Permissions

### ISSUE THREAD

**Issue by KrishnaPG** [casdoor/casdoor#981]
Creating this issue to track the TODOs discussed here: https://github.com/casdoor/casdoor/pull/955

- RBAC with domains model
- Resource type other than Application in the Permissions

![image](https://user-images.githubusercontent.com/4610831/183300293-fd2a58dd-e6cc-4a00-8632-bea3e2656a46.png)
![image](https://user-images.githubusercontent.com/4610831/183300318-f9bb80b0-d7d8-4f60-b06e-88421d232689.png)

These are required to make the Enforcement API work correctly. Ref: https://github.com/casdoor/casdoor/issues/849 and https://github.com/casdoor/casdoor/issues/846

**Comment by hsluoyz** [comment]
@seriouszyx
