### ISSUE TITLE
k8s login 403

### ISSUE THREAD

**Issue by sunerlin** [casdoor/casdoor#984]
when request /api/login, response 403 forbidden
![Selection_031](https://user-images.githubusercontent.com/25735967/183374916-8fde6305-d0c1-44b1-ad91-18e514d4aa3e.png)
![Uploading Selection_032.png…]()
![Selection_034](https://user-images.githubusercontent.com/25735967/183374987-748fb707-432c-4ee8-9b31-610e9eb6e05f.png)

**Comment by sunerlin** [comment]
![Selection_033](https://user-images.githubusercontent.com/25735967/183376049-90785bd8-0391-4d8a-b0a2-0de85f34a40b.png)
![Selection_032](https://user-images.githubusercontent.com/25735967/183376100-c0a89190-2461-4771-b588-908bfc72bc56.png)

**Comment by hsluoyz** [comment]
@sunerlin why close?

**Comment by ivanmissu** [comment]
@sunerlin I also met this question. Can you answer it

**Comment by hsluoyz** [comment]
Similar as: https://github.com/casdoor/casdoor/issues/1273
