### ISSUE TITLE
Accelerate CI

### ISSUE THREAD

**Issue by qianxi0410** [casdoor/casdoor#996]
Note that the front-end related CI is really slow, which seriously slows down the build. Note that the `yarn install` step is the cause of the serious slowdown, and this step can be accelerated using the cache.

**Comment by hsluoyz** [comment]
@qianxi0410 good point, how to add the cache then?

**Comment by qianxi0410** [comment]
see: [yarn-cache](https://github.com/marketplace/actions/yarn-install-cache)
@hsluoyz

**Comment by hsluoyz** [comment]
@qianxi0410 good, plz make a PR to add it
